### ISSUE TITLE
Error : Not enough actual parameter for macro `max`

### ISSUE THREAD

**Issue by karan-k-deepr** [jtv/libpqxx#101]
While compiling my code with latest version of `libpqxx` i was getting some errors.

```
1>c:\program files\postgresql\10\include\pqxx\pipeline.hxx(165): warning C4003: not enough actual parameters for macro 'max'
1>c:\program files\postgresql\10\include\pqxx\pipeline.hxx(165): error C2589: '(': illegal token on right side of '::'
1>c:\program files\postgresql\10\include\pqxx\pipeline.hxx(165): error C2062: type 'unknown-type' unexpected
1>c:\program files\postgresql\10\include\pqxx\pipeline.hxx(165): error C2059: syntax error: ')'
1>c:\program files\postgresql\10\include\pqxx\pipeline.hxx(163): error C3615: constexpr function 'pqxx::pipeline::qid_limit' cannot result in a constant expression
1>c:\program files\postgresql\10\include\pqxx\pipeline.hxx(166): note: failure was caused by control reaching the end of a constexpr function
```

Then i searched on google and found a patch in `pipeline.hxx`, `LineNumber` 165 changed from 
`return std::numeric_limits<query_id>::max();`
to 
`return (std::numeric_limits<query_id>::max)();`
actually works and now i am not getting any error.
Solution found on https://stackoverflow.com/questions/27442885/syntax-error-with-stdnumeric-limitsmax

Please add this patch to next release.
Thanks

**Comment by karan-k-deepr** [comment]
@egorpugin agree with your solution, maybe it works for someone. I also tried this patch in my code but it leads to some other errors. So, i prefer to go with this FIX.

**Comment by jtv** [comment]
This is an annoying, long-standing incompatibility between Visual C++ and the C++ standard library...  I didn't think there were any uses of `min` or  `max` in the libpqxx _headers,_ so that you could compile your own application with or without `NOMINMAX` so long as it _was_ defined when building libpqxx itself.  But this shows that I was mistaken!

I'll apply the workaround in the header, with a comment to explain why it's needed.

**Comment by dmlo** [comment]
For my fellow google searchers here in the future who are having problems compiling your own code that references pqxx from conan, yes, this is the problem you're having, and yes, inserting `#define NOMINMAX` in your own source code will solve your problem. 

For reasons I do not understand I had to add it to my .cpp files, not my .h files.

**Comment by Laro88** [comment]
Same here, it for some reason resurfaced in my application, using vcpkg witha  reference to  libpqxx 7.3.0

**Comment by jtv** [comment]
@dmlo @Laro88 could you try something for me?

In `include/pqxx/internal/conversions.hxx`, replace `std::max(` with `(std::max)(`.  Does that fix the error?

**Comment by dmlo** [comment]
Yes, that fixes the error. My code compiles cleanly under MSVC without `#define NOMINMAX`

**Comment by jtv** [comment]
Thanks.  I'll commit that change then.
