### ISSUE TITLE
Support for database creation

### ISSUE THREAD

**Issue by capsocrates** [jtv/libpqxx#102]
The command `CREATE DATABASE dbname` cannot be run inside a transaction. libpqxx does not provide any means of executing SQL statements outside of a transaction. Therefore, libpqxx cannot be used to create new logical databases at runtime. Could you please add support for this kind of functionality, either with an explicit function or with the ability to execute arbitrary SQL outside of a transaction?

**Comment by jtv** [comment]
Yes libpqxx does provide a means of executing SQL statements outside of a transaction.  Have a look at `nontransaction`.
