### ISSUE TITLE
Collision with Includes such as <array>

### ISSUE THREAD

**Issue by CleanHit** [jtv/libpqxx#104]
I'm using your API with the [SEAL](https://www.microsoft.com/en-us/research/project/simple-encrypted-arithmetic-library/) library for my project. SEAL uses #include <array> and every time I try to build my code with pqxx and SEAL the #include <array> finds the pqxx/array and causes this error.
`[ 50%] Building CXX object CMakeFiles/my_project.dir/dev/hmmenc_client/test.cpp.o
/usr/bin/c++   -I/pathToCLionProject/my_project -I/pathToCLionProject/my_project/dev/hmmenc_client -I/usr/local/include/pqxx -I/usr/pgsql-10/include  -pthread -std=gnu++11 -o CMakeFiles/my_project.dir/dev/hmmenc_client/test.cpp.o -c /pathToCLionProject/my_project/dev/hmmenc_client/test.cpp
/pathToCLionProject/my_project/dev/hmmenc_client/test.cpp: In function ‘int main()’:
/pathToCLionProject/my_project/dev/hmmenc_client/test.cpp:9:10: error: ‘array’ is not a member of ‘std’
     std::array<std::uint64_t, 3> arr;
          ^~~~~
/pathToCLionProject/my_project/dev/hmmenc_client/test.cpp:9:10: note: ‘std::array’ is defined in header ‘<array>’; did you forget to ‘#include <array>’?
/pathToCLionProject/my_project/dev/hmmenc_client/test.cpp:6:1:
+#include <array>

/pathToCLionProject/my_project/dev/hmmenc_client/test.cpp:9:10:
     std::array<std::uint64_t, 3> arr;
          ^~~~~
/pathToCLionProject/my_project/dev/hmmenc_client/test.cpp:9:29: error: expected primary-expression before ‘,’ token
     std::array<std::uint64_t, 3> arr;
                             ^
/pathToCLionProject/my_project/dev/hmmenc_client/test.cpp:9:34: error: ‘arr’ was not declared in this scope
     std::array<std::uint64_t, 3> arr;
                                  ^~~
gmake[3]: *** [CMakeFiles/my_project.dir/build.make:66: CMakeFiles/my_project.dir/dev/hmmenc_client/test.cpp.o] Error 1
gmake[3]: Leaving directory '/pathToCLionProject/my_project/cmake-build-default'
gmake[2]: *** [CMakeFiles/Makefile2:71: CMakeFiles/my_project.dir/all] Error 2
gmake[2]: Leaving directory '/pathToCLionProject/my_project/cmake-build-default'
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/my_project.dir/rule] Error 2
gmake[1]: Leaving directory '/pathToCLionProject/my_project/cmake-build-default'
gmake: *** [Makefile:121: my_project] Error 2`

I've renamed the pqxx/array file and updated the entry in pqxx file from #include <pqxx/array> ----> #include "pqxx/array.hxx" and the error was gone, but:
1. I'm afraid that I might be having other collisions with other includes when using more of the pqxx and SEAL code together.
2. Every time I'm going to get a new release of pqxx all my file name changes to avoid the errors are going to be overridden.

**Comment by KayEss** [comment]
The problem is the include you've set. This part:

    -I/usr/local/include/pqxx

Should be:

    -I/usr/local/include

Right now if you want to include the array header you do:

    #include <array>

But you should have:

    #include <pqxx/array>

That way the headers won't get confused.

**Comment by CleanHit** [comment]
@KayEss you are right, it was such a small thing and I just didn't see it. Thank you!

**Comment by jtv** [comment]
By the way, this is _exactly_ why libpqxx does it this way.  :-)
