### ISSUE TITLE
License Confusing

### ISSUE THREAD

**Issue by whatisor** [jtv/libpqxx#105]
Could you please make License clear?
+ In web page, http://pqxx.org/development/libpqxx/, it is BSD
+ In COPYING file here, it is your private license : Copyright (c) 2001-2017 Jeroen T. Vermeulen.
Thank you so much for social contribution.

**Comment by KayEss** [comment]
The license is BSD. The first line in the file gives the name of the copyright owner, in this case Jeroen. All instances of the BSD license will have this line changed to reflect who owns it. You can see this clearly in the template here: <https://opensource.org/licenses/BSD-3-Clause>

**Comment by jtv** [comment]
Exactly.  The way a copyright licence works is: "I hold the copyright to this work, and I license it to you."  That includes the BSD licence.  I think international copyright agreements no longer even support saying "this software is in the public domain" like people used to do.  Copyright comes inherently with someone writing it.

Obviously, before I can say "I license this software to you" (under the very loose terms of the BSD licence in this case), I must actually be entitled to do so.  And that means that I must claim copyright before I can give you rights over it.  There's nothing unusual about that.
