### ISSUE TITLE
How to build libpqxx on Windows10?

### ISSUE THREAD

**Issue by colinkong0406** [jtv/libpqxx#107]
Hi, there.
I'm looking for the way of building and libpq library on MFC because I'm programming Desktop app with PostgreSQL.
So please help me with this.
Quick suggestion will be GREAT!
Thanks.
Colin

**Comment by jtv** [comment]
Are you talking about building libpq?  Or about building libpqxx?  MFC is completely unrelated, I think.

The documentation in the `win32` directory is mostly aimed at Visual C++, so that may be the easiest choice of compiler.
