### ISSUE TITLE
raise notice?

### ISSUE THREAD

**Issue by danielpolski** [jtv/libpqxx#108]
Just wonder if I'm supposed to be able to get notices some way (to
output them in my application) or if that's a missing feature?

W.exec("DO language plpgsql $$ BEGIN RAISE NOTICE 'hello, libpqxx!'; END $$;");

**Comment by jtv** [comment]
Oops, no, I don't think there's a way to get that!  If you raise an _exception_ from plpgsql then your client gets a libpqxx exception containing the error message.  But a _notice_ doesn't seem to go anywhere where you can retrieve it.

There's probably a way to get the information from libpq, as a property of a result object.  I don't know how though, and I haven't found any quick answers in the documentation.  If I knew, it would probably be easy to expose it in libpqxx as well.

**Comment by jtv** [comment]
If it's not urgent, I'll close this issue for now.  If it _really_ is a problem then I'm sure it'll come up again.

**Comment by janhec** [comment]
Just came here for - obviously - the same "issue".  Wanted to add this option to a windows client I am building. Urgent? no, unexpected? yes. Structurally, one should not expose debug messages in a client, so I'm okay with the way it is, really.
Have to tell the scripters to use NOTIFY channel payload when they want informative application messages, libpqxx handles those fine.

**Comment by jtv** [comment]
Reading this again, I'm thinking perhaps I was a little hasty in saying that you can't do that.  There's the `errorhandler` class — does that do what you need?

**Comment by jtv** [comment]
@janhec does the `errorhandler` class do what do you need?

**Comment by janhec** [comment]
Jeroen,
Sorry for the late reply, have been working on other things, racing for a
deadline with plenty to do.
I did not think I was going to use it, however, just quickly implemented
it, it's simple and works absolutely fine!
Thanks,
Jan
[image: image.png]

**Comment by jtv** [comment]
So nice to hear!  I'll close the ticket then.

**Comment by danielpolski** [comment]
I ran into the same "issue" again. It's not a production problem really, but it would be great to be able to catch notices during development (my current situation debug output from plpgsql functions).

**Comment by jtv** [comment]
Have you tried setting up an `errorhandler` with your custom code to handle the notices?
