### ISSUE TITLE
The recommended way to escape LIKE '{USER_INPUT}%'

### ISSUE THREAD

**Issue by arteniioleg** [jtv/libpqxx#110]
```cpp
std::cout << transaction.quote(std::string{"test%"}) << std::endl;
```

this code outputs `'test%'` as you can see `%` is not escaped for `LIKE` operator.

Also `_` should be escaped.

[Docs](https://www.postgresql.org/docs/10/static/functions-matching.html#FUNCTIONS-LIKE)

**Comment by jtv** [comment]
That is correct.  The `quote` function is for quoting and escaping SQL strings in general.  It does not escape a string for use with `LIKE`.

At the moment there is no function for LIKE-escaping strings.  It'd make a nice addition, but for now you'll have to take care of this yourself.

**Comment by KayEss** [comment]
The problem would be that the function doesn't know which `%` and `_` characters to escape and which are meant to be wildcards.

**Comment by arteniioleg** [comment]
@KayEss I decide what to escape.

```cpp
"SELECT ... WHERE something LIKE '" + transaction.esc_like(user_input) + "%'"
```

**Comment by jtv** [comment]
Yes, this also means that quoting should _not_ be part of it.

**Comment by jtv** [comment]
The function should probably not include the generic SQL string escaping either.  So you'd end up with something like:

`"SELECT ... WHERE something LIKE " + transaction.quote(transaction.esc_like(user_input) + "%")`

**Comment by arteniioleg** [comment]
@jtv We use the same our own escape function.

**Comment by jtv** [comment]
@arteniioleg Sorry, I don't think I understand what you mean with that last sentence.  Is there another way you could say it?

**Comment by arteniioleg** [comment]
The solution you proposed matches with how I use my escape function in my current project

```cpp
"... WHERE name LIKE " + transaction.quote("%" + Escape(dto->Name) + "%") + " ESCAPE '\'"
```

```cpp
std::string Escape(const std::string& src) const
{
    std::stringstream stream;

    for (const auto &ch : src)
    {
        if (ch == '%' || ch == '_')
        {
            stream << '\\';
        }

        stream << ch;
    }

    return stream.str();
}
```

**Comment by jtv** [comment]
Ah OK.  I'll look into adding something like this.  It won't work for "weird" encodings, so maybe there's no point putting it on the transaction object.

Or maybe before we do this, it's time to have a generic "is this a weird encoding" check.

**Comment by JadeMatrix** [comment]
@jtv Sorry yes I'm still working on encoding iteration, it's almost demo-ready but I've been very busy over the last month

**Comment by jtv** [comment]
This took a while, but I finally got it done.  Hope it's useful.
