### ISSUE TITLE
Move constructor for pqxx::connection

### ISSUE THREAD

**Issue by hectorhon** [jtv/libpqxx#113]
Are there plans to add move constructors for the connection classes? This would allow the connections to be stored in a vector, for example.

Thanks for the great work!

**Comment by jtv** [comment]
I looked into this a few years ago, but there were some complications.  Not necessarily blockers, but adding move constructors may require some changes across the inheritance hierarchy.

In particular, a concrete connection type contains a policy object, and derives from `connection_base` which gets a reference to that object.  It'd be great to find a better design for that whole construct, but the change to the inheritance hierarchy would be profound.  If anybody out there defined their own connection types they could be severely affected.

Which is not to say that the idea is doomed.  It just needs careful thought and discussion, and it's good to have this issue as an impulse for that.

**Comment by hectorhon** [comment]
Is there any specific reason `connection_base` needs to take a reference to the policy object? Other than compatibility issues, would it be a good idea if I moved `m_policy` from the derived classes to the base class?

**Comment by jtv** [comment]
The policy _reference_ is in the base class.  Storing the policy _object_ is more of a problem.  We'd have to have a single class template, with the connection policy as a template parameter.  That would be nice and simple, but different instantiations of the template would no longer be related!  Every mention of a connection class anywhere in client code would have to specify the exact type of connection, or be templated on the connection type.

**Comment by KayEss** [comment]
If you store a `unique_ptr` to it (pimpl style) does that not solve the problem and allow the type to be movable?

**Comment by jtv** [comment]
True.  Hate to do an avoidable heap allocation, but otherwise I think that would work.

**Comment by hectorhon** [comment]
Thanks Jeroen! Currently I've been working around the issue by allocating into an std::array instead, the only downside is the size will be fixed. But that's OK for a basic connection pool :)

**Comment by jtv** [comment]
Glad to hear that you're not stuck for now.  But yes, maybe it's time to be a bit more wasteful with resources and a bit more considerate towards the programmer.

**Comment by jtv** [comment]
Finally added a move constructor for `connection`!  No move assignment as yet, and there are some safety restrictions.
