### ISSUE TITLE
Building the test files on Windows (e.g. vc-test.mak)

### ISSUE THREAD

**Issue by abdoulayediak** [jtv/libpqxx#116]
Hi guys, 

I faced an issue when building the tests on Windows 10 (Visual Studio 2017). And I also found a solution to it, so this post is more to share it.

The command: nmake /f win32\vc-test.mak ALL would end up with the following well known error message: 
_fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'_

This is because I have compiled libpqxx using _VCVARSALL.BAT amd64_ but in some of the mak files, I found the following line:
_LINK_FLAGS_BASE=kernel32.lib ws2_32.lib advapi32.lib /nologo **/machine:I386** /libpath:"$(LIBDIR)"_
Which is clearly the issue (the machine being targeted is i386). Thus the solution for me was simply to replace the i386 by x64 ==> runner.exe built successfully. 

Thanks for your hard work and good luck.

Best,

**Comment by jtv** [comment]
Thanks!  Makes me wonder if we can't leave that option out altogether.

Another alternative now is to use CMake.  I wonder if it might make our VC makefiles obsolete...
