### ISSUE TITLE
Convert Array or Record output into a Row

### ISSUE THREAD

**Issue by CleanHit** [jtv/libpqxx#117]
I'm trying to iterate over my results with:
```
for (pqxx::result::const_iterator row = result.begin(); row != result.end(); row++)
    {
        for (pqxx::const_row_iterator field = row.begin(); field != row.end(); field++) 
            {
                cout << field << '\n';
            }
        }
```
I have a problem if the PostgreSQL function returns `TEXT[ ]` or a `RECORD`, then my `field` looks like this `{foo, bar}` for `TEXT[ ]` or like `(foo)` for `RECORD`.

Is there a libpqxx way to convert the `result` into a row? I mean before the outer for loop or between the outer and inner for loops, so I can iterate over each element with the `field` variable.

**Comment by jtv** [comment]
There's an array parser now!  See the `array_parser` class in `array.hxx`.

(Also, as of C++11 you no longer need to write out the verbose loops with `begin()` and `end()`, and there's no need to spell out the type of every variable either.  You can now write loops like `for (const auto field: row)`.  Life gets much easier.)

**Comment by CleanHit** [comment]
Thanks, I've missed it and the documentation doesn't have a search field.
