### ISSUE TITLE
Building question

### ISSUE THREAD

**Issue by lasdasdas** [jtv/libpqxx#118]
Hi, 

I have a question, idk if this is the right place to ask. 

I am trying to compile with C++17 and I need the 6+ version. When I am building, If I use the cmake system, 
I can generate the dynamic library libpqxx.so however I can't install it. On the other hand, the ./configure && make system seems to have a install (sudo make install) target but it does not generate the dynamic library. 

Right now I am copying the product of cmake .. && make to the /usr/lib folder, what is the correct approach to install the library system wide?

**Comment by jtv** [comment]
The cmake build was a third-party contribution, and I'm not too familiar with cmake...  The build based on the configure script is the "native" build.  When you run `configure`, try passing the `--enable-shared` option.
That said, I would suggest using the _static_ library.  It's a discussion that comes up sometimes, and I don't pretend to know the perfect definitive answer, but in C++ it's just so easy to make a small accidental ABI change and break client code at runtime.

**Comment by lasdasdas** [comment]
Ok, perfect. Thank you very much. I will close this, If you are interested I might contribute in the future to make the target of cmake installable.
