### ISSUE TITLE
Support for single row mode is missing (PGRES_TUPLES_OK)

### ISSUE THREAD

**Issue by amesgames** [jtv/libpqxx#121]
Any plans to support single row mode (PGRES_TUPLES_OK)?

**Comment by jtv** [comment]
I don't think I understand the question...  `PGRES_TUPLES_OK` is a status code that means "command succeeded and returned tuples."

If what you want is to fetch result data from the server one row at a time, consider using a cursor.

**Comment by amesgames** [comment]
Ah, ok.

I have existing code that uses single row mode from libpq and am considering porting to libpqxx. Is the use of single row mode not that common?

**Comment by jtv** [comment]
I honestly don't know how common single-row mode is.  I figured there's really no point in offering this capability when cursors already let you retrieve ''n'' rows at a time!  You can even tune the number of rows you fetch dynamically depending on processing speed or memory usage, if that's what you want.  Have a look at `icursorstream` as well as the other classes in `cursor.hxx`.

Then there's `tablereader` for streaming a result more efficiently, but it was deprecated some time ago and is now undergoing a revamp thanks to @JadeMatrix.

**Comment by jtv** [comment]
If you don't mind, I'll close this issue here.  Feel free to re-open it if you feel the conversation isn't done, or open a new one if you want to take it in a new direction.

I'll just see if I can get a quick release out the door to celebrate libpqxx's 18th birthday.  :-)

**Comment by egorpugin** [comment]
@jtv Congrats!
