### ISSUE TITLE
Exception in field.to() targeting a double type (2)

### ISSUE THREAD

**Issue by woelfchen72** [jtv/libpqxx#125]
Hello Jeroen,

sorry for creating a new issue, but if you close, I can't reopen.
And sorry for this, but it does't work anyway.
I wrote the following testsnippet:

```
bool ok = false;
double output1;
double output2;
std::stringstream  s;

s.clear();
s.seekg(0);
s.str("1.5");
ok = static_cast<bool>(s >> output1);
std::cout << "Success:" << (ok ? "Yep" : "Sorry") << " Result:" << output1 << "\r\n";

s.clear();
s.seekg(0);
s.str("0.815");
ok = static_cast<bool>(s >> output2);
std::cout << "Success:" << (ok ? "Yep" : "Sorry") << " Result:" << output2 << "\r\n";
```

output was:
Success:Sorry Result:-9.25596e+61
Success:Yep Result:0.815

when I just comment the first s.seekg(0);

```
...
s.clear();
//s.seekg(0);
s.str("1.5");
...
```

output was:
Success:Yep Result:1.5
Success:Yep Result:0.815

The s.clear(); doesn't change anything.
Greets from Saxonia

**Comment by jtv** [comment]
Ouch!  It's good to have test code...  But it works just fine with gcc, so I still can't reproduce the problem.  :-/

I think it makes sense to keep the `seekg()` in, because otherwise I imagine we might just be growing its internal buffer indefinitely.  I don't suppose adding a `seekp(0)` as well helps?

**Comment by woelfchen72** [comment]
Am Montag, den 24.09.2018, 08:17 -0700 schrieb Jeroen Vermeulen:
> Ouch! It's good to have test code... But it works just fine with gcc,
> so I still can't reproduce the problem. :-/

That was, what I'am afraid off

> I think it makes sense to keep the seekg() in, because otherwise I
> imagine we might just be growing its internal buffer indefinitely. I
> don't suppose adding a seekp(0) as well helps?

Testing tomorrow, at the company.
Its not nice, if the same code behaves differently in Windows' stdlib
and the gcc one.

Wolfgang

**Comment by woelfchen72** [comment]
In addition here is the Msdn Doc, where they explain the behavior (we use the first member funtion):

>  If fail is false, the first member function calls newpos = rdbuf -> pubseekpos(pos), for some pos_type temporary object newpos. If fail is false, the second function calls newpos = rdbuf -> pubseekoff(off, way). In either case, if (off_type)newpos == (off_type)(-1) (the positioning operation fails), the function calls istr.setstate(failbit). Both functions return *this.
> 
> If fail is true, the member functions do nothing.

**Comment by jtv** [comment]
So apparently the `seekp` fails.  What happens if you print the flags in this way, when _not_ doing the `seekp`?

**Comment by jtv** [comment]
(To be a little clearer: I'd love to know exactly what happens with the `seekg`.)

Meanwhile I'll switch the `seekg` and the `clear` around like you suggested in the beginning.  But it'd still be good to _understand_ what's going wrong here, so we don't repeat the mistake.

**Comment by woelfchen72** [comment]
Here is somebody with the same problem, I think:
[https://stackoverflow.com/questions/20077495/seekg-fails-when-called-on-empty-stringstream](url)

So far...

**Comment by woelfchen72** [comment]
One thing, I mentioned: the position is -1, when seeking an empty stream:

```
..ctor  Flags: good:On bad:Off eof:Off fail:Off position:0
..seekp Flags: good:Off bad:Off eof:Off fail:On position:-1
..clear Flags: good:On bad:Off eof:Off fail:Off position:0
..str   Flags: good:On bad:Off eof:Off fail:Off position:0
Success:Yep Result:1.5
..seekp Flags: good:On bad:Off eof:Off fail:Off position:0
..clear Flags: good:On bad:Off eof:Off fail:Off position:0
..str   Flags: good:On bad:Off eof:Off fail:Off position:0
Success:Yep Result:0.815
```

**Comment by jtv** [comment]
Yes, it does sound as if that may be what's happening to us...  C++ I/O streams are a horrible API to work with, much easier to get wrong than to get right.  Too many failure conditions, unclear error feedback, fragile operations.

I'm beginning to see that omitting the `seekg` probably won't have the effect that I feared.  So I'll just do it that way.

**Comment by jtv** [comment]
Does the current version work OK for you?  If so, I'd like to tag and release the update.

**Comment by woelfchen72** [comment]
Sorry, what is the current version? Is there a branch on github for testing? So I would check it out.

**Comment by jtv** [comment]
It's not tagged yet, but I mean the current master.

**Comment by woelfchen72** [comment]
Ok, sorry, I forgot to merge the current master to my local own branch.

Tested again, and float conversation works, for the first use of the stringstream and all of the following.
So, you could close this issue, Thank you.

**Comment by jtv** [comment]
Thanks for an excellent bug report!
