### ISSUE TITLE
Incorrect windows version check

### ISSUE THREAD

**Issue by dpolunin** [jtv/libpqxx#126]
`connection_base.cxx` has incorrect windows version check:
```c++
#if defined(_WIN32) && (_WIN32_WINNT >= 0x6000)
```
should look like this:
```c++
#if defined(_WIN32) && (_WIN32_WINNT >= 0x0600)
```

Also cmake doesn't link to winsock so I've added this to `src/CMakeLists.txt` to fix it:
```cmake
if(WIN32)
  target_link_libraries(pqxx_static PUBLIC wsock32 ws2_32)
endif()
```

**Comment by jtv** [comment]
Thanks!  They're in.  And if you have any more of these, you may want to do them as pull requests so that we officially get your name on the commit.  :-)
