### ISSUE TITLE
Problem building on Mac OS using cmake configuration

### ISSUE THREAD

**Issue by KayEss** [jtv/libpqxx#130]
After using the new CMake files on our normal Ubuntu builds we moved on to try on Mac (Mojave with latest command line tools). We get the following error:

```
FAILED: libpqxx/test/unit/CMakeFiles/unit_runner.dir/test_string_conversion.cxx.o 
/Library/Developer/CommandLineTools/usr/bin/clang++  -DPQXX_SHARED -I/usr/local/include -I/usr/local/include/server -I../../libpqxx/include -Ilibpqxx/include -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -Wno-unused-command-line-argument -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -std=c++14 -MD -MT libpqxx/test/unit/CMakeFiles/unit_runner.dir/test_string_conversion.cxx.o -MF libpqxx/test/unit/CMakeFiles/unit_runner.dir/test_string_conversion.cxx.o.d -o libpqxx/test/unit/CMakeFiles/unit_runner.dir/test_string_conversion.cxx.o -c ../../libpqxx/test/unit/test_string_conversion.cxx
../../libpqxx/test/unit/test_string_conversion.cxx:11:1: error: unknown type name 'PQXX_DECLARE_ENUM_CONVERSION'
PQXX_DECLARE_ENUM_CONVERSION(EnumA);
^
../../libpqxx/test/unit/test_string_conversion.cxx:12:1: error: unknown type name 'PQXX_DECLARE_ENUM_CONVERSION'
PQXX_DECLARE_ENUM_CONVERSION(EnumB);
^
```

This seems to lead to a cascade of further errors. I couldn't trace through why the header that defines `PQXX_DECLARE_ENUM_CONVERSION` might not be included for this source file. The other thing though is that the cmake configuration builds this source file even though we are not trying to run any tests. It seems like a bit of a waste.

Edit to add that I just checked our Postgres test target and that all runs properly, so the problem is only with building the test files.

**Comment by MadWombat** [comment]
As a workaround you can skip building tests with `-DSKIP_BUILD_TEST=ON` flag

**Comment by jtv** [comment]
Weird.  And that macro's definition is almost entirely unconditional.  All I have to offer right now is some wild guesses:
- headers from an older libpqxx version installed on the system?
- something wrongly defining `PQXX_H_STRINGCONV`?
- somebody intelligently managing `#include` dependencies?

**Comment by KayEss** [comment]
> As a workaround you can skip building tests with `-DSKIP_BUILD_TEST=ON` flag

Is there a reason why this shouldn't be the default?

**Comment by KayEss** [comment]
> * headers from an older libpqxx version installed on the system?

Been thinking about this a bit more over the weekend. I think this is probably the case. Most likely the `CMakeLists.txt` file needs to switch the order of some of the libraries that it depends on so that the the found postgres headers are after its own libpqxx headers. Brew on the Mac will install a version of libpqxx as part of the postgres install so when the postgres headers are found that will also bring in the libpqxx headers. There doesn't seem to be any way of stopping this, other than I suppose logging a bug with the brew maintainers of the postgres cask.

**Comment by jtv** [comment]
Yup, it should definitely prefer its own headers over installed ones!

**Comment by jtv** [comment]
We haven't heard any complaints about this for almost a year.  I'll close the bug, and hope that it got resolved somewhere along the way.
