### ISSUE TITLE
Valgrind Memcheck Invalid read size of 4 after libpq version update?

### ISSUE THREAD

**Issue by danielpolski** [jtv/libpqxx#131]
I started getting Valgrind Memcheck errors after updating some software on my machine.
Anyone have a clue what's going on..? (The "Backend" software source is identical for the 3 runs below):

Backend build 261 starting.
libpq version: 90514
pqxx version: 5.0
-> No valgrind problems reported

Backend build 261 starting.
libpq version: 90514
pqxx version: 6.2.5
-> Still no valgrind problems reported

Backend build 261 starting.
libpq version: 100005
pqxx version: 6.2.5
-> 
==10473== Thread 4:
==10473== Invalid read of size 4
==10473==    at 0x59D9019: ??? (in /usr/lib/x86_64-linux-gnu/libpq.so.5.10)
==10473==    by 0x59DA57F: ??? (in /usr/lib/x86_64-linux-gnu/libpq.so.5.10)
==10473==    by 0x59D12D5: PQnotifies (in /usr/lib/x86_64-linux-gnu/libpq.so.5.10)
==10473==    by 0x174B49: get_notif (/home/daniel/coding/libpqxx/src/connection_base.cxx:544)
==10473==    by 0x174B49: pqxx::connection_base::get_notifs() (/home/daniel/coding/libpqxx/src/connection_base.cxx:560)
==10473==    by 0x15AF4F: guiThread::run() (/home/daniel/coding/eclipse_workspace/Backend/Debug/../guiThread.cpp:41)
==10473==    by 0x1151A3: runThread(void*) (/home/daniel/coding/eclipse_workspace/Backend/Debug/../Thread.cpp:25)
==10473==    by 0x57A46DA: start_thread (/build/glibc-OTsEL5/glibc-2.27/nptl/pthread_create.c:463)
==10473==  Address 0xdcadfec is 12 bytes inside a block of size 14 alloc'd
==10473==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==10473==    by 0x62439B9: strdup (/build/glibc-OTsEL5/glibc-2.27/string/strdup.c:42)
==10473==    by 0x59D8FF3: ??? (in /usr/lib/x86_64-linux-gnu/libpq.so.5.10)
==10473==    by 0x59DA57F: ??? (in /usr/lib/x86_64-linux-gnu/libpq.so.5.10)
==10473==    by 0x59D12D5: PQnotifies (in /usr/lib/x86_64-linux-gnu/libpq.so.5.10)
==10473==    by 0x174B49: get_notif (/home/daniel/coding/libpqxx/src/connection_base.cxx:544)
==10473==    by 0x174B49: pqxx::connection_base::get_notifs() (/home/daniel/coding/libpqxx/src/connection_base.cxx:560)
==10473==    by 0x15AF4F: guiThread::run() (/home/daniel/coding/eclipse_workspace/Backend/Debug/../guiThread.cpp:41)
==10473==    by 0x1151A3: runThread(void*) (/home/daniel/coding/eclipse_workspace/Backend/Debug/../Thread.cpp:25)
==10473==    by 0x57A46DA: start_thread (/build/glibc-OTsEL5/glibc-2.27/nptl/pthread_create.c:463)
==10473==

**Comment by jtv** [comment]
First thing to look at, I'm think, is whether you may be getting a mix of "debug" and "release" builds, with your main programme and the various libraries disagreeing on what memory layouts look like.  Callbacks contribute so much to the joy of debugging...  If in doubt, rebuild the whole thing from libpq up.

**Comment by jtv** [comment]
It's been a while...  I'll close the ticket just to keep the list clean, but feel free to reopen it or open a new one.
