### ISSUE TITLE
Hardcoded architecture flag in VS mak file prevents cross-compilation

### ISSUE THREAD

**Issue by elelel** [jtv/libpqxx#133]
File win32/vc-libpqxx.mak contains linker flags line with machine architecture hardcoded here:
https://github.com/jtv/libpqxx/blob/27ec4c73c667402e2566f97a6c07c31cda166046/win32/vc-libpqxx.mak#L88

This prevents cross-compiling x86 binaries on x64 host, since it overrides standard Microsoft environment flags used for that. I would submit a PR with "/machine:X64" option removed, which fixes the problem for me, but I'm not sure why that option was introduced in the first place.

**Comment by jtv** [comment]
I agree.  That flag started out selecting the 32-bit x86 architecture, and was changed to x86-64... but if we can leave it out, that's better.

**Comment by jtv** [comment]
I've pushed the fix.  By the way, do give the new CMake build a spin!  It should make things a lot easier for Windows users.
