### ISSUE TITLE
No targets specified and no makefile found

### ISSUE THREAD

**Issue by JoshMorrisCS** [jtv/libpqxx#134]
After running cmake in msys, I try and run make but it returns saying that there is no targets specified and no makefile found.

**Comment by JoshMorrisCS** [comment]
If I try and run ./configure it gives me an error "a source file using the pqexec() function did compile without problem, and the libpq library is available for linking, but for some reason a call to pgexec() failed to link properly to the libpq library..."

**Comment by jtv** [comment]
You'll have to look at the `config.log` output to find the error that resulted in this check failing.  It's usually a few pages up from the end of `config.log`.

The `make` error just means (assuming that you're running it in the right directory) that no Makefile has been generated.  Which looks to be the result of the `configure` error.

But, do try the CMake build.  It's probably the easiest way to get a Windows build now.

**Comment by jtv** [comment]
Hopefully this means that you've solved the problem.  I'll close the ticket.
