### ISSUE TITLE
How to build libpqxx for 32bit systems on 64bit debian?

### ISSUE THREAD

**Issue by KashCherry** [jtv/libpqxx#135]
Hi, I tried to compile libpqxx for x86_32 on x86_64 debian. But it's not so simple.
I tried to compile shared library(.so) with libpqxx's static library. I changed flags and added -m32 and -m elf_i386.
And it looks like everything compiled fine.
But when I launched my program I got an error `cannot allocate memory in static TLS block`.
I don't know why it came about.
However, I think the problem in compilling.
So it would be nice if you show me how to compile libpqxx for x86_32 system.
Thanks for the help.

**Comment by jtv** [comment]
I haven't tried this one myself, but bear in mind that you may need the compiler options in multiple variables, to ensure that they're always used: CXXFLAGS for compiling C++ source files, LDFLAGS for linking, and perhaps more...

**Comment by KashCherry** [comment]
Yeah, I changed, but then...
```/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libpq.so when searching for -lpq
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libpq.a when searching for -lpq
/usr/bin/ld: cannot find -lpq
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libm.a when searching for -lm
collect2: error: ld returned 1 exit status
Makefile:383: recipe for target 'rmlo' failed```
How can I install the libpq for the 32bit system?

**Comment by jtv** [comment]
Maybe you need to tell the configure script _itself_ that you're building for a different architecture?  What you're doing is basically cross-compiling.

**Comment by KashCherry** [comment]
Yes, I think so too, but I don't know how to do it :(

**Comment by KashCherry** [comment]
As I understand the problem is not in the libpqxx library.

**Comment by jtv** [comment]
Correct, I think...  This seems to be somewhere between autoconf and your system.
