### ISSUE TITLE
CMake build fails in Visual Studio (test_string_conversion)

### ISSUE THREAD

**Issue by mechkg** [jtv/libpqxx#136]
I am getting the following errors trying to build with CMake from Visual Studio:

`Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static void __cdecl pqxx::enum_traits<enum EnumA>::from_string(char const * const,enum EnumA &)" (__imp_?from_string@?$enum_traits@W4EnumA@@@pqxx@@SAXQEBDAEAW4EnumA@@@Z) referenced in function "void __cdecl pqxx::from_string<enum EnumA>(char const * const,enum EnumA &)" (??$from_string@W4EnumA@@@pqxx@@YAXQEBDAEAW4EnumA@@@Z)	unit_runner	C:\Users\Ivan\Projects\Intake24\Experimental\libs\libpqxx-build64\test\unit\test_string_conversion.obj`

`Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::enum_traits<enum EnumA>::to_string(enum EnumA)" (__imp_?to_string@?$enum_traits@W4EnumA@@@pqxx@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4EnumA@@@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::to_string<enum EnumA>(enum EnumA const &)" (??$to_string@W4EnumA@@@pqxx@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBW4EnumA@@@Z)	unit_runner	C:\Users\Ivan\Projects\Intake24\Experimental\libs\libpqxx-build64\test\unit\test_string_conversion.obj`

`Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::enum_traits<enum EnumB>::to_string(enum EnumB)" (__imp_?to_string@?$enum_traits@W4EnumB@@@pqxx@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4EnumB@@@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::to_string<enum EnumB>(enum EnumB const &)" (??$to_string@W4EnumB@@@pqxx@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBW4EnumB@@@Z)	unit_runner	C:\Users\Ivan\Projects\Intake24\Experimental\libs\libpqxx-build64\test\unit\test_string_conversion.obj`

Not sure what exactly is going on, the code looks fine to me.

pqxx version: tried 6.2.5 and master (3d44eac716e1bdb329febac4a8d6487fe9f5d00b)
Visual Studio version: Community 2017 15.8.0
CMake version: 3.12.14

**Comment by jtv** [comment]
The enum traits are a very recent feature...  It's quite possible that I made some mistake that doesn't show up in my test builds, e.g. because you're using a different compiler.

Could you try rebuilding libpqxcx with the following change in `strconv.hxx`?  The line:

    struct enum_traits

...becomes...

    struct PQXX_LIBEXPORT enum_traits

(Alternatively, maybe your compiler is picking up headers from a different libpqxx version somewhere else on your system — but we're supposed to have protection against that nowadays.)

**Comment by mechkg** [comment]
I've tried that and it doesn't seem to help unfortunately, I am still getting the same error. I am pretty sure that is the only libpqxx version on this machine (it's a Windows machine).

**Comment by jtv** [comment]
It's looking for a `to_string` that takes a const reference to your enum - and the traits template only defines it for a _value_ of your enum.  I guess that's where the problem happens.

So... maybe try changing the signatures in `enum_traits`?  I'm at a Jimmy Carr show right now, so not a good time to play with the code.  Mainly because my laptop's in the cloakroom.  :-P

**Comment by jtv** [comment]
Any news?  Looking at the errors again, I just don't get why an inline function would be missing at _link_ time.  Could it be a problem with precompiled headers maybe?  Clutching at straws here.

**Comment by mechkg** [comment]
I have managed to make it build by removing the `PQXX_LIBEXPORT` modifier from this line: 

https://github.com/jtv/libpqxx/blob/ea09e6f5f3539fdb3b5027e0570a3ebc02fd5cb4/include/pqxx/strconv.hxx#L145

My logic was that the code produced by this macro is in the client binary, not the dynamic library, and therefore linker gets confused when it tries to find it in the DLL.

But I haven't touched C++ code in many years so I may be completely wrong about this.

**Comment by jtv** [comment]
Wow, but that's obscure!  Thanks for finding this.  I'll upload the fix in
a moment.

There's some other major changes going on, so it's possible that you may
find new compile errors.


Jeroen

**Comment by jtv** [comment]
It's in.  But, we've got some experimental stuff in master right now, so be careful taking it into production.  For now I'd recommend keeping your fix as a local patch.  If the release cycle takes too long, I'll release a patch update.

**Comment by jtv** [comment]
I guess we're done with this ticket — it's just a matter of releasing the updates that are already in the pipeline.  I'll close this one.
