### ISSUE TITLE
Windows Copy path correction

### ISSUE THREAD

**Issue by WedgetailSystems** [jtv/libpqxx#14]
In win32/vc-libpqxx.mak, the file copy paths need to be amended to move the quotation mark after the LIBPQPATH variable as follows:

Line 259:  copy $(LIBPQPATH)"\$(LIBPQDLL)" "$(OUTDIR)"
Line 269:  copy $(LIBPQDPATH)"\$(LIBPQDDLL)" "$(OUTDIR)"
Line 272:  copy $(LIBPQPATH)"\$(LIBPQLIB)" "$(OUTDIR)"
Line 275:  copy $(LIBPQDPATH)"\$(LIBPQDLIB)" "$(OUTDIR)"

Kind Regards

Simon Fagg
Wedgetail Systems

**Comment by jtv** [comment]
Thanks!  Hope this helps.
