### ISSUE TITLE
Compatibility with VS17

### ISSUE THREAD

**Issue by Amaracs** [jtv/libpqxx#140]
Hi,

I tried to find the answer everywhere but I couldn't, so I wanted to ask that the pqxx can be compiled with VS17, especially the version 5.0, or should we update it to the new 6.0?

Thank you very much,
Best Regards,
Adam

**Comment by jtv** [comment]
All I can say is: it _should_ be just fine, as long as you have good C++11 support.  I believe any version of Visual Studio 2017 would have good C++11 support.

So... just give it a try!

**Comment by woelfchen72** [comment]
Hello Adam, 
I successfully biult it withVS2017, version 15.7.4. I compiled both, a 32bit version and a 64bit.
Follow the win32/INSTALL.txt
If you run in trouble, feel free to ask.
Cheers, Wolfgang

**Comment by Amaracs** [comment]
Thanks guys. :) 
I close this issue then. :)

Best,
Adam

**Comment by jtv** [comment]
Thanks @woelfchen72
