### ISSUE TITLE
exec_params syntax error near '$1'

### ISSUE THREAD

**Issue by Dig-Doug** [jtv/libpqxx#144]
Hi, I'm trying to use the function `exec_params` but I'm getting a runtime error:

```bash
terminate called after throwing an instance of 'pqxx::syntax_error'
  what():  ERROR:  syntax error at or near "$1"
LINE 2:       CREATE TABLE IF NOT EXISTS $1 (
                                         ^

```

Code to reproduce:

```cpp
#include "pqxx/pqxx"

int main(int argc, char** argv) {
  std::string table_name = "postgres-test";
  pqxx::connection connection_{R"(
      hostaddr=127.0.0.1
      port=32768
      user=postgres
      password=mysecretpassword
    )"};

  pqxx::work create_table(connection_);
  create_table.exec_params(R"(
      CREATE TABLE IF NOT EXISTS $1 (
        id SERIAL PRIMARY KEY
      );
  )",
                           table_name);
  // This works
  /*
  create_table.exec(R"(
      CREATE TABLE IF NOT EXISTS test (
        id SERIAL PRIMARY KEY
      );
  )");
  */
  create_table.commit();
}

```
My connection setup is working since the `exec` call (commented out above) works.

Is this the intended way to use `exec_params`? 

Thanks for your help!

**Comment by jtv** [comment]
A table name isn't really a string in SQL.  It's a special kind of identifier, with its own rules for quoting and escaping.  So you can't insert it as a parameter using `exec_params()`!

The way to do this is to run your table name through `quote_name()` (on the transaction), and insert it into your query yourself.

Off the top of my head, so take with a grain of salt:

    const auto query = (
        "CREATE TABLE IF NOT EXISTS " +
        create_table.quote_name(table_name) +
        "(id SERIAL PRIMARY KEY)"
    );
    create_table.exec(query);

**Comment by Dig-Doug** [comment]
Ah, that makes sense. I tried a variation of your suggestion and everything is working now :)

Thanks for your help and the very quick response!
