### ISSUE TITLE
Big m_query in result type makes copying slow

### ISSUE THREAD

**Issue by floatdrop** [jtv/libpqxx#145]
We have some performance issues with simple code, that iterates over result set and accessing each row.

This is caused by `m_query` in `result` type – in our case query is quite big: https://github.com/jtv/libpqxx/blob/70b0d8f85b0d34f755e0fa393c4d242b2152cfc6/include/pqxx/result.hxx#L206

**Comment by jtv** [comment]
So we may need to make that a `shared_ptr`...  Thankfully not a problem nowadays.  Thanks!

**Comment by floatdrop** [comment]
@jtv thanks for quick response! Looks like a one solution, should I make PR for this?

**Comment by jtv** [comment]
No worries, working on it right now.  :-)
