### ISSUE TITLE
Missing internal/ignore-deprecated-*.hxx after CMake [sudo make install]

### ISSUE THREAD

**Issue by moodboom** [jtv/libpqxx#146]
Recently on a new CMake install, I have found that the ignore-deprecated-{pre|post].hxx files are not getting added to the installation's include folder.  Copying them into place (eg, from source to /usr/local/include/pqxx/internal) allowed me to compile against the library again.  I didn't have time to look further yet, sorry...

**Comment by jtv** [comment]
Thanks for reporting it.  The problem may simply be that the CMake setup uses globbing to  find its files — meaning that you need to re-generate your build files by running cmake every time a file is added.

**Comment by moodboom** [comment]
Doh sorry I misspoke.  I was using autotools and I did a full clone and [make clean] and [configure] but [sudo make install] didn't put those headers in place.  Perhaps because they are in a subdir named internal...?  But other includes were copied (callgate.hxx, encoding_group.hxx, etc.).  I had a previous installation in place, I'll remove it and retry.

**Comment by jtv** [comment]
In that case it may have been me forgetting to re-generate the build files and push them to the repo.  (They're generated files but I keep them under revision control exactly to free people from this hassle.)

**Comment by moodboom** [comment]
Reinstall did not seem to add the files.  OK cool, no worries here, copying them into place works fine.  Thanks so much jtv, love the library!

**Comment by jtv** [comment]
Thanks, so nice to hear that!  I did indeed forget to add these files in the right place and regenerate & push the build files.  Hope the accompanying commit fixes it.

**Comment by moodboom** [comment]
Yep you fixed it, confirmed it.  Thanks!

**Comment by jtv** [comment]
Yes, that looks quite possible...  Does my latest commit on master fix it?

**Comment by dvereb** [comment]
I ran into the same problem with internal/encodings.hxx today, so it appears the latest fix did not fix it.  git log shows the most recent commit to be 6ae2a02c632e36647ed8b080cd2196bc3068e097.  I simply added a symbolic link to point to the file in my cloned copy of the repo, and that got me on my way for now.

**Comment by dvereb** [comment]
Fixed.  Thank you!
