### ISSUE TITLE
Access to Postgres error codes

### ISSUE THREAD

**Issue by KayEss** [jtv/libpqxx#148]
In Fostgres we want to be able to catch exceptions and then forward to code which is configured by the user. To do this we need to have access to the error codes. Ideally the names (like `integrity_constraint_violation`), but if we can't get that then the numeric codes are better than nothing (e.g. 23000 for the same error).

I don't see anything on the exception classes that will tell us this. Do we need to parse the exception strings?

**Comment by jtv** [comment]
Assuming your exception is an `sql_error`, just call its `sqlstate()`.  I'll add some documentation.

**Comment by KayEss** [comment]
The docs at read the docs are a year old now, and the ones you get to from google are often even older (for 2 something).

**Comment by jtv** [comment]
Whoa...  thanks for pointing that out.  It's supposed to update those docs automatically, if I remember correctly.

**Comment by jtv** [comment]
Okay, looks like I never set up the call from Github to the ReadTheDocs webhook.  Done now.  That should help improve the search rankings for the latest version relative to all the older stuff out there.  Toosind tak.

**Comment by KayEss** [comment]
Ingen problem :-)
