### ISSUE TITLE
Documentation Question?

### ISSUE THREAD

**Issue by JalapenoGremlin** [jtv/libpqxx#15]
The following sentence is on the website: http://pqxx.org/development/libpqxx/
> Just one caveat: not all platforms support throwing an exception in a shared library and catching it outside that shared library. It's probably a good habit to use dynamic libraries instead.

What exactly is meant by "use dynamic libraries instead" (of shared library).  I have no idea what that means.  What is the meaning of dynamic and shared libraries in the case of libpqxx? In most literature they are synonymous.

**Comment by jtv** [comment]
Thanks — you're right, that should read "static"!
