### ISSUE TITLE
string_traits<bool>::from_string function throws an argument_error exception in case of a valid input

### ISSUE THREAD

**Issue by Amaracs** [jtv/libpqxx#152]
Hi,

I noticed that since the version 5.0 the following function was refactored:
_void string_traits<bool>::from_string(const char Str[], bool &Obj)_
  starts at line 314 in version 6.3 src\strconv.cxx.

In case the Str[] contains a "1" the version 6.3 is looking for more char in the array as it does for the case 'f' and case 't' (true, false. Maybe it is a copy paste error from that switch case.)
but in case the string contains only a "1" there is no any more string char in the array just the '\0' character which the comparison goes against and throws an unnecessary exception.

version 5.0:

```
  case '1':
    result = true;
    OK = !Str[1];
    break;

```

version 6.3:
 ```
 case '1':
    result = true;
    OK = (Str[1] != '\0');
    break;
```

Our integration tests brought out this issue, after I used the old 'OK = !Str[1];' it did not throw any exception and the integration tests were passed.

**Comment by jtv** [comment]
Ah, thanks — it was just a little confusion with negations!  The `!=` should have been `==`.
