### ISSUE TITLE
Build error on windows

### ISSUE THREAD

**Issue by egorpugin** [jtv/libpqxx#153]
Hi,

I'm using custom builds. My build is broken on the line https://github.com/jtv/libpqxx/blob/master/include/pqxx/internal/encodings.hxx#L76
It seems it takes `CALLBACK` macro somewhere from windows.
Replacing it with `C` or `CB` both on 76 and 78 lines solves the problem.

pqxx ver is 6.3.0.

**Comment by jtv** [comment]
Thanks!  Expect an update release soon.

**Comment by egorpugin** [comment]
Thanks!

Did you consider of replacing and/not/or ... iso646 things with more common(?) logical ops (&&, || ...)?

**Comment by jtv** [comment]
They used to be `&&` and `||` until recently.  I changed them because I think I'll find the new way easier to read.
