### ISSUE TITLE
Float32 precision

### ISSUE THREAD

**Issue by Amaracs** [jtv/libpqxx#158]
Hi,

I saw than in case of float32 type the conversion between text -> float -> text only 8 decimal digits survive, but 9 would be the expected(IEEE single). In case of float it is not a problem, the +2 is suffice: Libpqxx 6.3 /strconv.cxx line 190:

```
    // Kirit reports getting two more digits of precision than
    // numeric_limits::digits10 would give him, so we try not to make him lose
    // those last few bits.
    this->precision(std::numeric_limits<T>::digits10 + 2);
```
But for exactly this expectation max_digits is introduced in c++11:

So my suggestion would be to change the precision to:
`this->precision(std::numeric_limits<T>::max_digits10);`

Excerpt from the original proposal:
[**Source**](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2005.pdf)

![image](https://user-images.githubusercontent.com/19373797/52480608-7cd1bc00-2bac-11e9-9933-cbcb874bc712.png)

**Comment by jtv** [comment]
You're right.  This has been on my wish list for a while, but I never quite got around to it.  Thanks!
