### ISSUE TITLE
warning "C4702: unreachable code" MSVC with /W4

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#160]
I get the following warning message on Visual Studio 2017 with /W4: 
`warning C4702: unreachable code`.

I wrote the reproduce snippet:
```cpp
#include <pqxx/pqxx>

#include <iostream>
#include <stdexcept>

int main()
{
    pqxx::connection conn("...");
    pqxx::work tx(conn);

    try {

        tx.conn().prepare("__SELECT_USERS", "SELECT name FROM users");

        pqxx::result result = tx.exec_prepared("__SELECT_USERS");

        for (auto && row : result) {
            const pqxx::field & f = row.at(1);

            std::string name = f.as<std::string>(); // "include\pqxx\strconv.hxx(194): warning C4702: unreachable code"

            std::cout << "user.name: " << name  << std::endl;
        }

        tx.commit();
    } catch (const std::exception &/* ex */) {
        tx.abort();

        return -1;
    }

    return 0;
}
```

The warning message points to the line No: `function`: `pqxx::string_traits<std::string>::null()`.
This function call `[[noretrun]] throw_null_conversion(const std::string &type)` before `return` statement,
but output warning on Visual Studio.

**Comment by tt4g** [comment]
Disable warning snippet(I do not want to take this measure):

```cpp
#pragma warning(push)
#pragma warning(disable:4702)
#include <pqxx/pqxx>
#pragma warning(pop)
```

Is it possible to change `string_traits<std::string>` like `PQXX_DECLARE_STRING_TRAITS_SPECIALIZATION`?

**Comment by jtv** [comment]
Hilarious.  The compiler is right, and there's dead code there.  _Why_ is there dead code there?  Only to silence warnings from different compilers!  The function call throws an exception, but some compilers then complain about control reaching the end of a non-void function.  And my "helpful" noreturn annotation tells the compiler about the situation.

Maybe it's time to solve this differently, e.g. by moving the `throw` into the caller.

**Comment by jtv** [comment]
I made a bet that the compilers have changed and will no longer complain about the functions not returning.  Hopefully that fixes this warning without reviving the old "control reaches end of non-void function."  If it doesn't work, we'll have to try something new.

**Comment by tt4g** [comment]
Thank you for your response, I don't get warning after 67d7fd3a030358eb5cd870b96cdac46eb7805995.

**Comment by JadeMatrix** [comment]
@jtv I believe you still have to mark the functions _calling_ `internal::throw_null_conversion()` as `[[noreturn]]` for all C++11 compilers to accept the code with no complaints.  Decorating `internal::throw_null_conversion()` with a hypothetical `[[alwaysthrows]]` attribute would be useful in these situations…

**Comment by jtv** [comment]
Good point, @JadeMatrix  — adding those `noreturn` attributes now.
