### ISSUE TITLE
Can not build 6.3.1 with GCC 4.9

### ISSUE THREAD

**Issue by uilianries** [jtv/libpqxx#161]
Hi!

Thanks for updating the libpqxx!

I have a matrix of compilers to build libpqxx where the newest release (6.3.1) can not be built with gcc 4.9

The message error from compiler is:

```
encodings.cxx: In function 'pqxx::internal::encoding_group pqxx::internal::enc_group(const string&)':
encodings.cxx:691:28: error: no match for 'operator==' (operand types are 'std::initializer_list<std::_Rb_tree_const_iterator<std::pair<const std::basic_string<char>, pqxx::internal::encoding_group> > >' and 'std::map<std::basic_string<char>, pqxx::internal::encoding_group>::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const std::basic_string<char>, pqxx::internal::encoding_group> >}')
   if (found_encoding_group == encoding_map.end())
                            ^
encodings.cxx:691:28: note: candidates are:
In file included from /usr/include/c++/4.9/map:62:0,
                 from encodings.cxx:16:
/usr/include/c++/4.9/bits/stl_multimap.h:903:5: note: template<class _Key, class _Tp, class _Compare, class _Alloc> bool std::operator==(const std::multimap<_Key, _Tp, _Compare, _Alloc>&, const std::multimap<_Key, _Tp, _Compare, _Alloc>&)
     operator==(const multimap<_Key, _Tp, _Compare, _Alloc>& __x,
```

The full log can be obtained [here](https://travis-ci.org/bincrafters/conan-libpqxx/jobs/490594328#L1079)

#### Steps
I've used autotools:

    ./configure
    make

If you don't have an environment to reproduce this error, you can try the docker image [conanio/gcc49](https://hub.docker.com/r/conanio/gcc49).

#### Environment
OS: Linux Ubuntu Trusty
ARCH: x86_64
COMPILER: GCC 4.9

Let me know if you want to fix this, or just drop the gcc-4.9 support.

Regards!

**Comment by jtv** [comment]
Thanks.  In the long run, I don't think there's much we can do for gcc 4.9 now.  The next major libpqxx release will require C++17!

_In the short run_ however, I may have a fix.  Hang on.
