### ISSUE TITLE
Static compilation still requires libpq.dll

### ISSUE THREAD

**Issue by grunk** [jtv/libpqxx#162]
Hello,
I'am trying to compile libpqxx statically meaning that i don't want it to search for libpq.dll at runtime.

I followed the INSTALL.txt in win32 directory.

In pqxx/pqxx i added : 

`#define PQXX_PQ_STATIC 1`

I also edited `vc-libpqxx.mak` to change /MD to /MT which is required by my application.

Then in my main cmakelist i added `add_definitions(-DPQXX_PQ_STATIC)` as requested in the INSTALL.txt
Finally i copied libpq.lib,libpqxx_static.lib,libpqxx_staticD.lib and the include dir with the other libs i use. I link my app with this.

When i run my application it complains that libpq.dll is missing. If i put libpq.dll everything goes fine but i'd like to avoid this.

What am i missing ?

VS2015, libpqxx 6.3.1 and postgresql 11

**Comment by egorpugin** [comment]
You link to dynamic libpq.
Find or build it statically and you are set.

**Comment by jtv** [comment]
Well that's the question, isn't it?  Is the static libpq binary installed in the same place as the dynamic one?

**Comment by jtv** [comment]
Sorry, I'm on the move and missed the answer to my own question.  Clearly yes, the static libpq is there.  Unfortunately it's hard for me to debug this because I don't normally use either Windows or CMake, so I'm mostly reliant on contributions from others.  Any chance that the linker is looking for the static library in a different place?

**Comment by egorpugin** [comment]
> Clearly yes, the static libpq is there.

Where? I did not see static libpq in windows PG installations.

**Comment by grunk** [comment]
> > Clearly yes, the static libpq is there.
> 
> Where? I did not see static libpq in windows PG installations.

libpq.lib is available in my installation of postgresql in the same directory as the dll.
At then of the build of libpqxx , i also have a libpq.lib (34ko) generated. This the one i link with in addition to libpqxx_static.lib

@jtv defining PQXX_PQ_STATIC in one of the header is the way to go , to build libpqxx statically with libpq ?
I'm fairly confident on the linking part in my application , but not so sure on libpqxx building part.

**Comment by jtv** [comment]
@grunk  Defining `PQXX_PQ_STATIC` is probably best done in your compile options.

But, reading this again, defining this macro is not enough!  It tells _the library code_ that you're going to link to a static libpq, but it doesn't tell CMake what to do.  I don't know enough CMake to tell it how to link to the static libpq, but you could try using a location that has only the static library and not the DLL.

**Comment by KayEss** [comment]
> libpq.lib is available in my installation of postgresql in the same directory as the dll

That won't be the static version of the library, that'll be the library that contains the exports from the DLL.

**Comment by grunk** [comment]
@jtv i'm not using cmake to compile pqxx (just the .mak given in the win32 folder).
@KayEss That mean i should compile libpq my self statically before anything ?

**Comment by KayEss** [comment]
> That mean i should compile libpq my self statically before anything ?

There would certainly be advantages to that. Not least that versions of other dependencies you may have in common aren't dictated by what libpq was built with (we had this problem with OpenSSL).

I have no idea how easy it is to build libpq on Windows though

**Comment by grunk** [comment]
I tried and it seems fairly easy but it generate a libpq.lib that the exact same size (34ko) as the one that cause me trouble. I did not find anything related to dependancie like openssl and zlib , so i probably missing something to build it correctly.

I'm going to go with the dll , it seems way too complicated to have it fully static unfortunately.

**Comment by jtv** [comment]
Sorry to hear it.  It just seems to be the Windows way of doing things...  On the bright side, at least libpq is going to have a much more stable ABI than libpqxx does, so it's less painful to use a DLL there.  Easier to maintain a stable ABI in C than in C++.
