### ISSUE TITLE
defined old version in file VERSION.

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#165]
I found a libpqxx version 6.3.0 in `CMakeFile.txt` after `cmake -G "..."` command, but I'm using libpqxx 6.3.1

It seems that the version is old.

https://github.com/jtv/libpqxx/blob/d84ac89d7496f05159a21aaa6134e3bfc165d8d8/VERSION#L1

It does not become a big problem. However, I think that it is better to change the version.

**Comment by jtv** [comment]
The libpqxx repo does not contain a CMakeFile.txt, and the autogen script doesn't create one.  At least on my system, cmake doesn't generate one either.  None of the cmake-related files contain the libpqxx version.

Is it possible that either you or somebody else created this file, and now needs to update it?

**Comment by tt4g** [comment]
I recognize that it is used here.

https://github.com/jtv/libpqxx/blob/d8ee9491e88b8a680ed64ba73ad8df72754ec4d5/CMakeLists.txt#L3-L6

**Comment by tt4g** [comment]
Oops, I'm sorry. 'CMakeFile.txt' was typo.

**Comment by jtv** [comment]
Ah, so you're saying that the `VERSION` file itself contains an old version, and the CMake aspect was more or less a red herring?

It's strange though — the 6.3.1 tag has the correct version text  in that file.  Maybe try re-pulling the repo including the tags?

**Comment by tt4g** [comment]
I understood the cause.

`VERSION` file was not updated properly due to my terminal problem.

I'm sorry for confusing you.

**Comment by jtv** [comment]
Glad it's solved.
