### ISSUE TITLE
Missing header <pqxx/pqxx> after installed using CMake

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#166]
I get the following error: "No such file or directory <pqxx/pqxx>"

I'm using CMake to build and install for libpqxx 6.3.1 (the source files from release URL: https://github.com/jtv/libpqxx/archive/6.3.1.tar.gz).

I found the cause of this problem, `include/pqxx`  is missing from the installation target.

https://github.com/jtv/libpqxx/blob/d8ee9491e88b8a680ed64ba73ad8df72754ec4d5/include/CMakeLists.txt#L57-L58

but I did not know how to fix it.

this problem also occurs with the latest sources.

**Comment by jtv** [comment]
Thanks.  Should be fixed now, along with the one for which you submitted the pull request.  Could you try it again?

**Comment by tt4g** [comment]
I try it within a few days.

**Comment by tt4g** [comment]
I built with `cmake -G "Visual Studio 15 2017" -A "x64" -DSKIP_PQXX_STATIC=ON -DSKIP_PQXX_SHARED=OFF ... && cmake install .`, `include/pqxx/pqxx` has been installed.

**Comment by jtv** [comment]
Very well.  I've released an update.
