### ISSUE TITLE
std: invalid_argument is thrown at connection loss

### ISSUE THREAD

**Issue by alkibades** [jtv/libpqxx#168]
Hi,

please consider the following snippet during a connection loss scenario:

```
std::shared_ptr<pqxx::nontransaction> nonransaction
 pqxx::result result = nontransaction->exec("SELECT 1"); 
```

as the result is being constructed it tries to resolve the client encoding from the pq connection:
```
int
PQclientEncoding(const PGconn *conn)
{
	if (!conn || conn->status != CONNECTION_OK)
		return -1;
	return conn->client_encoding;
}
```
Since the connection is broken it will return -1, so the pqxx throws an exception when it attempts to resolve -1 in the encoding map
```
auto found_encoding_group{encoding_map.find(encoding_name)};
  if (found_encoding_group == encoding_map.end())
    throw std::invalid_argument{
      "unrecognized encoding '" + encoding_name + "'"
    };
  return found_encoding_group->second;
```
I think it would make sense to reveal the real issue in the exception and throw and pqxx::broken_connection instead of invalid arguments.

```
int pqxx::connection_base::encoding_id() const
{
    int client_enc = PQclientEncoding(m_conn);
    if (-1 == client_enc)
       throw broken_connection{};
    return client_enc;
}
```

Regards,
Zoltán

**Comment by jtv** [comment]
That makes sense.  Thanks.
