### ISSUE TITLE
stream_to/stream_from headers not being installed

### ISSUE THREAD

**Issue by jbosboom** [jtv/libpqxx#174]
I'm trying to make an updated Arch package for libpqxx 6.4.2 (using the [existing Arch PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libpqxx) with pkgver updated and checksums skipped).  This uses the configure-and-make build system.  The build is successful but the stream_to/stream_from headers were not installed by `make install`, so are not in the resulting package.

I don't really understand configure/automake but I think the problem is these headers are not listed in libpqxx/include/Makefile.am, which seems to be a manually-maintained file.

By the way, these headers are also not in the `pqxx/pqxx` include-everything convenience header.

**Comment by jtv** [comment]
Thanks!  You were both correct.  I'll release the update soon, and then hopefully get going with the C++17 work leading up to 7.0.
