### ISSUE TITLE
Currently seems to be no stable release branch

### ISSUE THREAD

**Issue by moodboom** [jtv/libpqxx#183]
I am hoping to use a stable release of this library.  I only see two branches, and I'm therefore assuming I am expected to use the master branch directly.

I just built the code successfully an hour ago (on commit f2caa945), pulled down two new commits, and found that the build is broken (see below).  That's perfectly understandable, you may not have a linting system in place or I may have something different in my environment... or maybe I'm just doing something wrong (but i can revert and build fine).  

But is it possible that you can support stable releases, that would shield from "realtime churn"?  :-)  Thanks for the work, the library's great!

`/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/unit_runner.dir/test_prepared_statement.cxx.o: in function `(anonymous namespace)::test_registration_and_invocation()':
test_prepared_statement.cxx:(.text+0x119): undefined reference to `pqxx::connection::prepare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
`

**Comment by jtv** [comment]
Thanks for your kind words.  I do support stable releases, it's just that I don't necessarily create branches for them!

Consider:
 * Maintaining a release branch is a pain.
 * It's also not a great help if you're mostly just one developer anyway.
 * Git is not great (especially compared to bzr!) if you want to port individual commits back and forth between branches.  It's basically back to the RCS days.
 * Most of the time with libpqxx there's no urgent need to update old releases anyway.
 * The main thing about having a good release branch is picking the right jump-off point, which can be hard to judge right up front.  Life with release branches is full of little regrets.
 * But if the need arises, hey, the whole point of revision control is that you _can_ go back in time and create that branch from the ideal starting point!

And so, I only create release branches when I actually need to release an update to an older release.  Which as you can see is a rare thing.  To get a stable version, you'll need to check out a release tag.  At the moment 6.4.4 is the most up-to-date release.

Most of the time you really won't need to.  It's just that we're going through the break-everything phase in the run-up to a fairly radically different 7.0 release.  Even then, most code should not be affected at all, so I will have a look at what's breaking in your build and fix it as soon as I can.

**Comment by moodboom** [comment]
Perfect.  Thanks for taking the time to give such a thoughtful answer!  I'll check the recent tags and pay attention to them, appreciate all the work Jeroen!

More details on what i was seeing... I can step back to commit f2caa945 and build, but then I get an error in my code that there's no longer a connection::disconnect() call.  I'll poke around in the docs and see if i can see what I need to do to use the new code.  Thanks!

**Comment by jtv** [comment]
Yeah, `disconnect()` is gone.  I wanted to keep it, but it complicated things so much, and it even violated my own design rules: _a connection object is a connection._  No "connection manager" nonsense.  Creating a `connection` establishes a connection, destroying one closes the connection.

The link error puzzles me...  Yes, `prepare(const string&, const string&)` is gone, replaced by `prepare(string_view, const string&)`, but I'm not seeing anything in the headers or in the test which would make the compiler think that the old version still existed.  Maybe a timestamp mixup on the filesystem, caused perhaps by a "git pull" while a build was ongoing?  Any chance a "make clean" fixes it?

Or maybe there are two copies of the header, perhaps one installed on the system and one local in your build directory?

**Comment by moodboom** [comment]
RAII, sounds good to me!  :-)  The first error was probably my fault.  I pulled and built and removed the disconnect() call and... it looks good!  Thanks so much!  Onwards!  Cheers!

**Comment by jtv** [comment]
Yay!  :)
