### ISSUE TITLE
is possible to build as static lib to use in alpine docker image

### ISSUE THREAD

**Issue by samuaz** [jtv/libpqxx#187]
Hi people, is possible to build as static lib?

im working on google cloud run project in c++ that use libpqxx to connect to PostgreSQL database i need to have a small docker image as possible for that i have a build image with all dependencies and after that i build my app as static and copy the final binary to new alpine image, so when i try to build my app with static flag i have a error:

/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: attempted static link of dynamic object `/usr/local/lib64/libpqxx.so'

if possible to use libpqxx as static using cmake? 

thanks

**Comment by tt4g** [comment]
You need to set CMake variable `SKIP_PQXX_STATIC` and `SKIP_PQXX_SHARED`.

example:
```bash
$ cmake -DSKIP_PQXX_STATIC=OFF -DSKIP_PQXX_SHARED=ON extra args...
```

**Comment by jtv** [comment]
Or, if you're using the `configure` script, configure with the `--enable-static` and `--disable-shared` options.  Depending on your system, that may actually be the default.

**Comment by jtv** [comment]
It's been quiet.  I'll close the issue.
