### ISSUE TITLE
Template errors compiling with GCC 7.3.0

### ISSUE THREAD

**Issue by PaulThiessen** [jtv/libpqxx#188]
I am trying to compile libpqxx (from a clone of https://github.com/jtv/libpqxx) with GCC 7.3.0 on CentOS 7. I'm getting (many) errors like this:

`
make[1]: Entering directory /panfs/pan1.be-md.ncbi.nlm.nih.gov/structure_build/build_2019-04-17/PostgreSQL/libpqxx/src
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -std=c++17 -DHAVE_CONFIG_H   -I../include -I../include -I/panfs/pan1.be-md.ncbi.nlm.nih.gov/structure_build/build_2019-04-17/PostgreSQL/install/include -I/panfs/pan1.be-md.ncbi.nlm.nih.gov/structure_build/build_2019-04-17/zlib-1.2.11/install/include -I/panfs/pan1.be-md.ncbi.nlm.nih.gov/structure_build/build_2019-04-17/PostgreSQL/install/include -O3  -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT array.lo -MD -MP -MF .deps/array.Tpo -c -o array.lo array.cxx
libtool: compile:  g++ -std=c++17 -DHAVE_CONFIG_H -I../include -I../include -I/panfs/pan1.be-md.ncbi.nlm.nih.gov/structure_build/build_2019-04-17/PostgreSQL/install/include -I/panfs/pan1.be-md.ncbi.nlm.nih.gov/structure_build/build_2019-04-17/zlib-1.2.11/install/include -I/panfs/pan1.be-md.ncbi.nlm.nih.gov/structure_build/build_2019-04-17/PostgreSQL/install/include -O3 -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT array.lo -MD -MP -MF .deps/array.Tpo -c array.cxx -o array.o

In file included from array.cxx:9:0:
../include/pqxx/compiler-internal.hxx:34:24: error: explicit template specialization cannot have a storage class

 #define PQXX_LIBEXPORT __attribute__ ((visibility("default")))
                        ^

../include/pqxx/strconv.hxx:87:14: note: in expansion of macro 'PQXX_LIBEXPORT'

   template<> PQXX_LIBEXPORT extern const std::string type_name<TYPE>
              ^~~~~~~~~~~~~~

../include/pqxx/strconv.hxx:93:1: note: in expansion of macro 'PQXX_DECLARE_TYPE_NAME'

 PQXX_DECLARE_TYPE_NAME(bool);

 ^~~~~~~~~~~~~~~~~~~~~~
`

What's the best way to deal with this?

**Comment by jtv** [comment]
Try the current stable version — check out the tag "6.4.4".  The current head of `master` is an intermediate state on the way to 7.0, and lots of things are changing and lots of things still need figuring out.

(The error is because I tried to make one compiler happy and upset the other one.  Working on it.)

**Comment by PaulThiessen** [comment]
Great that works, thank you!
