### ISSUE TITLE
Cancel Request

### ISSUE THREAD

**Issue by Amaracs** [jtv/libpqxx#189]
Hi,

I was wondering if it is possible to cancel requests with libpqxx, for example if the user called a query which is returning with tons of lines and it takes time then He wants to cancel it and rewrite the query for example with more filters. How would you tackle the problem?

Thanks,
Best,
Adam

**Comment by jtv** [comment]
If you use `pqxx::pipeline` to get your results asynchronously, there's a `cancel_query` method.

**Comment by Amaracs** [comment]
Unfortunately I don't, so if I'm not mistaken it leaves me with this solution then:

https://stackoverflow.com/questions/35319597/how-to-stop-kill-a-query-in-postgresql

Which will introduce one more layer of abstraction into the code. 
Thanks for your answer.

**Comment by jtv** [comment]
That's another option.  But do have a look at the pipeline; all extra overhead is annoying but I don't think a pipeline is a lot of extra complexity compared to e.g. setting your timer.

**Comment by jtv** [comment]
What if I added a wait-with-timeout to the pipeline class?

**Comment by Amaracs** [comment]
Actually if I would start over I would use pipeline if this feature what you mentioned would be implemented, but now it would require too much refactor. On the other hand in the code I saw this:
```
void pqxx::connection_base::cancel_query()
{
  cancel_wrapper cancel{m_conn};
  cancel();
}
```

Which is calling this:
```
explicit cancel_wrapper(PGconn *conn) :
    m_cancel{nullptr},
    m_errbuf{}
  {
    if (conn)
    {
      m_cancel = PQgetCancel(conn);
      if (m_cancel == nullptr) throw std::bad_alloc{};
    }
  }
```

On the other hand it is on connection level. 
Do you see any reason to not use it?

**Comment by jtv** [comment]
That sounds plausible, actually!  Just make sure your query doesn't finish just while you're doing this, possibly making your "timeout thread" cancel your _next_ query.

**Comment by Amaracs** [comment]
Thanks for your help and for your insights. 
I am closing the "issue". 

Best,
Adam
