### ISSUE TITLE
Having issues building libpqxx with MinGW + MSYS on windows: libpq-fe.h no such file

### ISSUE THREAD

**Issue by aw18** [jtv/libpqxx#19]
I've downloaded the release distribution libpqxx-4.0.1.tar.gz. I've already installed PostgreSQL 9.6 from the installer and so this includes the libpq-fe.h.

**To Reproduce the Bug:**
1. When running the configure.sh script as-is from the release distribution, the values of pg_config --libdir and pg_config --includedir weren't being stored into the variables, so I added a fix so that it would run pg_config properly and get the values stored to the variable. 

pg_config --libdir returns C:\Program Files\PostgreSQL\9.6\lib
pg_config --includedir returns C:\Program Files\PostgreSQL\9.6\include

With those outputs, I've also added a fix so that the Program Files were replaced with Program/ Files to escape the space, as follows:

pg_config --libdir returns C:\Program/ Files\PostgreSQL\9.6\lib
pg_config --includedir returns C:\Program/ Files\PostgreSQL\9.6\include

2. I've exported LDFLAGS and CPPFLAGS:
LDFLAGS="-IC:\Windows\System32 -IC:\PROGRA~1\PostgreSQL\9.6\include"
CPPFLAGS="-LC:\Boost\" 

3. Ran configure.sh in mingw+msys, the script aborts telling me that libpq-fe.h no such file exists. The config.log shows that it is adding #include<C:\Program/ Files\PostgreSQL\9.6\include\libpq-fe.h>. And just generally looking at the configure.sh code, all the #include<{with_postgres_include}\libpq-fe.h> requires the postgres include directory to be added. 

I've tried not adding the second -I flag in LDFLAGS but I still get this error. 
Any ideas would be greatly appreciated!

**Comment by KayEss** [comment]
I see you've used the 8.3 safe file name in step 2. Did you do so as well in step 1?

**Comment by jtv** [comment]
How did the (forward) slash get into "Program Files"?  Is that an escape character in Windows?

**Comment by aw18** [comment]
Thanks for the response @KayEss and @jtv!
I've managed to finally get it to see libpq-fe.h. 
I've manually changed the configure.sh so that where it assigns the value for with_postgres_include, it is storing ../../Program Files/PostgreSQL/9.6/include. This way when it gets incorporated into the #include <{with_postgres_include}/libpq-fe.h> it can locate it based on the default paths that are inherent from either the ld.exe or gcc.

Right now I have a new issue. 
I can't find the -lpq. I've installed Postgresql via the installer for Windows 7, and I'm building libpqxx using mingw, and it is saying that

**Comment by KayEss** [comment]
I don't know much about mingw. I'd hope it uses the standard Windows ABI in which case you'll be able to link against the libpq and it should just work (once you have the path right for the lib anyway). I expect that the solution you've done to handle the spaces the paths for the includes would need a similar fix for the library paths you have to set.

I think you should try using the 8.3 safe file names always here and not mix in the ones with spaces. It only confuses the issue.

**Comment by aw18** [comment]
@KayEss I've actually tried using the 8.3 safe file names across the board before, but unfortunately the configure.sh script incorporates the path into its #include <{THE INCLUDE PATH}/libpq-fe.h>, and I don't think the 8.3 safe file name works in the context of the #include header.

do you know what it is trying to link to? Is the library pq.lib when it uses the -lpq flag?

**Comment by KayEss** [comment]
As I understand things the 8.3 filenames are guaranteed to always work everywhere as the handling is built into the low level file APIs on the platform, just like the case insensitive file names (this is a feature of the API not of the NTFS format). What happens when you use them in the include?

**Comment by aw18** [comment]
Okay I've changed the Program Files to PROGRA~1 for the with_postgres_include variable, and ran the ./configure.sh.
**Currently running at the moment....**

**Comment by aw18** [comment]
I am still having a difficult time linking -lpq when running the configure.sh. Any advice would be greatly appreciated! :)

**Comment by KayEss** [comment]
I've never really used the mingw environment. My only experience is using visual studio, and I ended up using the sample headers Jeroen has included. Maybe that's something you can do? Just get some headers from somewhere and fix the paths up by hand if you need to.

**Comment by aw18** [comment]
Okay managed to get the static libpqxx built but DLLs can't be built, it still errors out. 

Biggest take home message for those trying to build libpqxx is to use the version from github. Following the instructions for building it with Visual C++ works win32\INSTALL.txt. The release distributions are meant for older systems, so take note of that.

**Comment by jtv** [comment]
I would definitely suggest using the github version and working with static libraries.  The website did say to use dynamic libraries, but that was a typo.  Dynamic libraries make it easier to mess up the versioning on the end-user system.
