### ISSUE TITLE
Availability of charconv

### ISSUE THREAD

**Issue by KayEss** [jtv/libpqxx#195]
One of the latest commits makes use of the new charconv header. What's the minimum g++ that you're supporting now? 7.3 doesn't have the header.

**Comment by tt4g** [comment]
As far as GCC implementation status of charconv, only integral types supported in 8.1: https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017

**Comment by jtv** [comment]
Yes, C++17 is the baseline requirement now and I think you'll need at least a minimal `<charconv>`.

I can reinstate the conditional if it helps you in the short term — the first uses are going to involve integral types, and the new `string_view`-based conversion API will let me apply an optimisation that `to_chars` can't.  So I have a reason to provide a non-charconv implementation of the conversions.

**Comment by KayEss** [comment]
For various other reasons our plan is to stick to the stock compiler of Ubuntu bionic as our base for the time being, that's gcc 7.4 for amd64 and i386. I also want to be able to start to use the charconv stuff, but it looks like we're going to need to wait a couple of years for it yet.

Hopefully this can all be sorted in time for the next LTS.

If you want to go beyond that then it's fine, but it'll mean we'll have to pin our version of libpqxx which means we'll no longer see your changes as quickly as we do now. You may prefer that :-)

**Comment by KayEss** [comment]
I kind of feel like this error is related to the fix:

```
FAILED: /usr/bin/c++   -Ilibpqxx/include -I../../libpqxx/include -I/usr/include/postgresql -I/usr/include/postgresql/10/server -O3 -DNDEBUG   -std=c++1z -MD -MT libpqxx/src/CMakeFiles/pqxx_static.dir/connection.cxx.o -MF libpqxx/src/CMakeFiles/pqxx_static.dir/connection.cxx.o.d -o libpqxx/src/CMakeFiles/pqxx_static.dir/connection.cxx.o -c ../../libpqxx/src/connection.cxx
In file included from ../../libpqxx/include/pqxx/util.hxx:26:0,
                 from ../../libpqxx/include/pqxx/result.hxx:25,
                 from ../../libpqxx/include/pqxx/binarystring.hxx:21,
                 from ../../libpqxx/include/pqxx/binarystring:4,
                 from ../../libpqxx/src/connection.cxx:62:
../../libpqxx/include/pqxx/strconv.hxx:82:7: error: ‘to_chars_result’ is not a member of ‘std’
  std::to_chars_result res, const std::string &type)
       ^~~~~~~~~~~~~~~
../../libpqxx/include/pqxx/strconv.hxx:82:28: error: expected primary-expression before ‘const’
  std::to_chars_result res, const std::string &type)
                            ^~~~~
../../libpqxx/include/pqxx/strconv.hxx:83:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
../../libpqxx/include/pqxx/strconv.hxx: In function ‘std::string_view pqxx::to_buf(char*, char*, T)’:
../../libpqxx/include/pqxx/strconv.hxx:208:25: error: ‘to_chars’ is not a member of ‘std’
   const auto res = std::to_chars(begin, end - 1, value);
                         ^~~~~~~~
../../libpqxx/include/pqxx/strconv.hxx:208:25: note: suggested alternative: ‘is_class’
   const auto res = std::to_chars(begin, end - 1, value);
                         ^~~~~~~~
                         is_class
```

This is on Ubuntu, gcc 7.3 libstdc++

**Comment by jtv** [comment]
Well yes, that's another symptom of not having charconv.  I've pushed a workaround.
