### ISSUE TITLE
I wish to use tuple when passing parameters to exec_params

### ISSUE THREAD

**Issue by mushipu1988** [jtv/libpqxx#197]
I want to use tuple parameter that can be used when passing parameters to exec_params like exec_params(const std::string& query, tuple&& t) , so that I can update data throw gathered tuple  from a map or vector.  emm... how can it be possible?

**Comment by jtv** [comment]
Have a look at `pqxx::dynamic_params`.  It's pretty well hidden, which I will fix before the 7.0 release.

This type is a wrapper around any container type or sequence, and that lets you pass a variable number of arguments.  The only problem is, all items in that container must (of course) be the same type!

**Comment by mushipu1988** [comment]
Yeah, I've learned it, the tuple cannot be accessed in the for loop since the tuple actually cannot be treated as a container , it is defiened as a tool. But my parameters is really complex and the numberof my tables waiting to insert to really too much . If i cannot use tuple it will be a tough work.

**Comment by KayEss** [comment]
i believe that you can just use the tuple as a parameter pack. You'll either need a bit of your own template meta-programming or use something like `std::invoke`

**Comment by mushipu1988** [comment]
I'v tried std::apply but it turned out to accept explicit count of parameters.

**Comment by KayEss** [comment]
Not sure what you mean by "explicit count" here. I was thinking something along the lines of (just off the top of my head):

```
std::apply([&cnx, &sql](auto... args) { return cnx.exec_params(sql, args...); }, tuple);
```

**Comment by mushipu1988** [comment]
I mean only when the parameters defiened previous clearly , because std::apply con't deduce parameter, and do not know who to call.

**Comment by mushipu1988** [comment]
I'm planning to use switch case statement to distribut branches according to the size of tuple . So it doesn't need to define every table interfaces.

**Comment by KayEss** [comment]
I think by this time you really need to show some code of what you're trying to do.

 `std::apply` will deduce the parameter types just fine, but it won't pick a function from an overload set (if that's what you mean). That lambda trick should work around that, but if not then you may need to specify the overload explicitly, or give the overload you need a unique name.

**Comment by mushipu1988** [comment]
Yes ! The std::apply worked ! Sory for my previous demo might be some other problems ,and I didn't understood the warnning description very well.

**Comment by jtv** [comment]
Excellent news.  I think it's worth updating the documentation for.  But quite busy doing other stuff right now.

**Comment by jtv** [comment]
Hmm...  reading this back, I can't think of anything useful I could add to the documentation for this problem.  Any suggestions?

**Comment by mushipu1988** [comment]
yeah... finally I added a new constructure function 
```cpp
template<typename Seq , typename TagMap> 
  params(Seq & item_seq, TagMap & tags)
```
to deal with my problems.

**Comment by mushipu1988** [comment]
May be it can be better insteaded by stream_to

**Comment by jtv** [comment]
I suppose it's specific enough that it won't affect a lot of users...  If you don't mind, I think I'll just close this bug.  We can always open a new one when concrete ideas come along.
