### ISSUE TITLE
PGSQLSRC in win32/common cannot contain spaces?

### ISSUE THREAD

**Issue by ash-j-f** [jtv/libpqxx#200]
Forgive me if the solution to this is obvious, but when trying to set the path for PGSQLSRC in  win32/common for compiling using nmake in Developer Command Prompt as suggested by libpqxx install instructions, the following compile command fails:
```
nmake /f win32/vc-libpqxx.mak ALL
```
The paths I tried were:
```
PGSQLSRC=C:\Program Files\PostgreSQL\11
PGSQLSRC="C:\Program Files\PostgreSQL\11"
PGSQLSRC=C:\Program^ Files\PostgreSQL\11
```
Each one fails to either find the correct directories to include (as the space breaks up the path and cl.exe gets confused), or the compile works and subsequent copy commands in the nmake process fail. None of the above syntax options work to escape the space correctly for all steps in the compile process that use that path.

I made a hasty edit to the file common-sample suggesting to use the quotes method but didn't realise it failed if I did a clean and totally fresh compile using nmake. https://github.com/jtv/libpqxx/commit/9ff78d2db75918d0a2c61dbd93b104502c1680b2

I will update this suggested patch and submit a new one once I find out the best way to escape the path name.

**Comment by ash-j-f** [comment]
The problem stems form vc-libpqxx.mak wrapping paths in quotes when calling ```copy``` and ```del```, but passing the path to cl.exe without quotes. This means that the suggested typical escaping methods I mentioned above will not work for all cases where the path is used in vc-libpqxx.mak

**Comment by ash-j-f** [comment]
I had better luck using the 8 character path variation but this seems a dirty workaround
```
PGSQLSRC=C:\PROGRA~1\PostgreSQL\11
```
Is there a better solution that this which could be suggested? Or could vc-libpqxx.mak be changed in a way to make more typical escaping methods work?

**Comment by ash-j-f** [comment]
I see "fix for spaces" and "don't quote PGSQLSRC" in these earlier commits that change win32/common-sample, but as I demonstrated, spaces are in fact not possible in the path currently :)
3f33d962b8c120e52e5692d49387b96302185bea
68f804dd87449ae748369573e0af0d732091687f

**Comment by jtv** [comment]
I'm entirely reliant on contributions for this part, and I think there's been some yo-yoing in the past between imperfect solutions.  Fix one case, break the other.  :/

It may just be a gap in my memory, but your explanation adds some insights which are new for me.

Would the CMake setup be an acceptable replacement in your case?  I did find a silly bug in there the other day, where the files are not generated when there's nothing in them, so I'll have to fix that of course.

**Comment by ash-j-f** [comment]
> Would the CMake setup be an acceptable replacement in your case?

I was able to get libpqxx to compile for x64 on Windows using nmake via the x64 Native Tools Command Prompt as I pointed out in the config file comment update here 144b2a02dca273be2e95c5ba0529dc1d0924a022. I used the path ```PGSQLSRC=C:\PROGRA~1\PostgreSQL\11``` to get around the spaces in directory names issue (just mentioning this here in case it's useful to someone looking at this ticket in future). That worked good enough for me as a solution even if it's a bit inelegant. :D

As a beginner in compiling things for Windows, I'm not sure right now how to edit vc-libpqxx.mak to solve the issue. I'll try a few ideas and see if I can wrangle it into working. Otherwise if this ticket stays open hopefully someone with more experience can fix it up for us!

**Comment by ash-j-f** [comment]
I have two working solutions to this problem and need help choosing which one is most appropriate:

1. Expect the user to escape the PGSQLSRC and other paths in win32/common config file with quotes if it contains spaces. The solution is to omit all quotes wrapping the paths (PGSQLSRC , PGSQLINC, LIBPQINC) where they are used in the vc-libpqxx.mak script. So paths the user enters into win32/common will always have to look like ```PGSQLSRC="C:\Program Files\PostgreSQL\11"``` if they contain spaces, but can omit the quotes if the path contains no spaces.

2. Allow users to enter paths with spaces and not expect them to worry about quoting them. This means they can enter ```PGSQLSRC=C:\Program Files\PostgreSQL\11``` into win32/common and it will work just fine. The solution here is to wrap ALL uses of the paths in quotes internally in vc-libpqxx.mak.

As stated before, the problem is caused by a mix of quoted and non-quoted path variables in libpqxx.mak which currently mean you cannot use spaces OR quotes around paths in the win32/common config file.

I am a beginner at development on the Windows platform, so there may be some reason to choose one solution over the other I am not aware of. Please let me know! If no one has any preference, I'm inclined to go with solution 2, not expecting users to quote the paths. Whatever solution is chosen I'll add a comment to win32/common-sample to inform users whether they must wrap paths in quotes, or not.

**Comment by KayEss** [comment]
The real problems with quoting start when you have quote characters also in the path. Do both solutions work equally well in that case?

I wouldn't be surprised if the first option makes things clearer if it actually means all quoting can be set by the user. But I also wouldn't be surprised if you need to get the user to quote and also to do something special at each use. I don't know the specifics of the quoting mechanisms you have to deal with in these nmake files though.

**Comment by ash-j-f** [comment]
> The real problems with quoting start when you have quote characters also in the path. Do both solutions work equally well in that case?
If the user understands how the paths are being treated then they can escape quotes and other special characters appropriately. I agree it might be clearer if the user is made responsible for all quoting and escaping. Either way a notice in the config file explaining what is required from the user when entering paths should hopefully avoid confusion. :)

**Comment by ash-j-f** [comment]
For now I'm going to go with wrapping everything in quotes behind the scenes, so users can enter spaces in path names in the config file if they wish, without having to use any special escaping. I'll update the comments in the config file to indicate to the user that this is the case. My reasoning is: it's easier for the user this way and harder for them to make a mistake, and less for me to change in the "common" config file and the .mak files :)

I'll make the pull request soon once I've run the tests.

@KayEss, you pointed out there will be an issue with quote characters in the path, but I can't think of a practical example where this would happen. But my experience with C++ and Visual Studio is very small. Is it likely users would need to be able to have quotes in path names, do you think?

If users find this limits them from using quotes in path names or special escape characters when they really need to, it could be changed to put escaping entirely in the hands of the user in the config file after all. But at the moment we have the worst of both worlds anyway; quotes in path names, escape characters and spaces in path names will all currently break the build process.

**Comment by ash-j-f** [comment]
Just a small update; I can't create folders in Windows 10 that contain quotes in the name, at least not via the UI. I tried using the escape sequences I know for Windows command line and didn't succeed there either. So hopefully it's either difficult or impossible to have quotes in path names on Windows.

**Comment by ash-j-f** [comment]
I just noticed MinGW build might also break if there are spaces in path names entered in win32\common. Is anyone able to easily test this? Otherwise I'll try to set up a MinGW build environment to check it in the next few weeks. The fix should be similar to what I did for nmake in vc-libpqxx.mak. Affected files would be win32\MinGW.mak and win32\MinGW.mak.template

**Comment by jtv** [comment]
@ash-j-f thanks again for all your help.  I'm still wondering if CMake wouldn't be the easiest, most universal  way out of all this...

**Comment by jtv** [comment]
And by the way, I was very surprised to hear that Windows 10 balks at a quote in a filename...  I think the fact that it never seems to have occurred to anyone here to _try_ it could be telling.  :-)

**Comment by ash-j-f** [comment]
@jtv If I had any choice I'd be using a Linux platform, but I'm writing a PostgreSQL connector module for the Amazon Lumberyard game engine so I'm stuck with Windows and Visual Studio as the IDE for now 😭

**Comment by jtv** [comment]
I believe you.  :)  I generally don't use IDEs when I can avoid them (which in workshops sometimes means getting your code finished before the others get their environments set up) but I must admit, I've seen a lot worse than a recent edition of Visual Studio.

Forgive me for not keeping track your work very effectively.. if we're in a good place for the Visual Studio build right now, I would suggest just closing this bug, and opening a new one when we know more about the MinGW build.

**Comment by ash-j-f** [comment]
Sounds good!

**Comment by jtv** [comment]
Update: I've got the CMake build working on AppVeyor.  And since this shows that the CMake build can work on Windows, I have _removed the custom Visual C++ build files._

The one big remaining problem with the CMake build right now is that it only builds a shared library.  We'll fix that.
