### ISSUE TITLE
Documentation inconsistencies in pqxx::connection

### ISSUE THREAD

**Issue by JeffAbrahamson** [jtv/libpqxx#202]
In `connection.hxx` the documentation says

```
 * When you connect to a database, you pass a connection string containing any
 * parameters and options, such as the server address and the database name.
 *
 * These are identical to the ones in libpq, the C language binding upon which
 * libpqxx itself is built:
 *
 * https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
```

This indicates that connection strings should look like `postgresql://other@localhost/otherdb?connect_timeout=10&application_name=myapp` etc.  And this is correct.

Many examples, such as `http://pqxx.org/development/libpqxx/wiki/EmployeeExample`, use default connections.  This might work, but it's a bit lazy and doesn't help.  (I would never do that in production, for example.)

In other contexts, such as `http://pqxx.org/development/libpqxx/`, example code suggests connection strings like `dbname=company user=accounting`.  Perhaps that can be made to work, but the URL referenced in the code suggests it shouldn't, and it didn't for me.

Connecting to a database is the first thing one does when experimenting with libpqxx.  It would be very nice to resolve these points so that the documentation is more consistent.  If multiple methods work, they should surely all at least link to a page that explains all of what works and offers specifications for them.  Even the Connection URI section at `https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING` doesn't really give a spec, just a (very good) set of examples.

**Comment by jtv** [comment]
Thanks for pointing this out!  In my defence, the URL connection strings (or indeed RFC3986) didn't exist when I first drafted that documentation.  There's enough of the stuff that I never wake up in the morning and decide to give it all a systematic fresh look.

That said, I don't see why the "classic" style of connection string wouldn't or shouldn't work for you.  When I look at the libpq documentation I see the "Keyword/Value Connection Strings" right _above_ the one about "Connection URIs."  So I expect there's some other variable at play.

Anyway, I'll see about updating the text.  I may even remove some from the site, and defer to the in-tree documentation.  I'm not sure what I can do about updating the code to use connection strings: it seems convenient to let the user set those parameters through environment variables.

**Comment by JeffAbrahamson** [comment]
Ah, missed that, thanks.  The URL took me right there, so I read from there down.

Maybe the classic method would have worked and I just got something wrong.  But once I thought the docs were saying otherwise, I kinda stopped trying.

To be honest, I'd have preferred a structure I could pass that specifies what it thinks are the right values.  But that's not the way of databases, it seems.  The other db's I support don't offer it either, so I just make friends with ostringstream and move on.

```
struct PgConnectConfig {
    string hostname;
    int port;
    string dbname;
    // ...
    PgConnectOptions options;
};
struct PgConnectOptions {
    // ...
};
```

**Comment by jtv** [comment]
I did toy with the idea of "structured" connection parameters, way back when.  But I didn't want the extensibility headaches: I might end up having to add a field for every new option, and to know the default value for each, with somebody somewhere always stuck waiting for me to catch up to the latest new parameter.

Either that, or it'd be basically just a `std::map<std::string, std::string>` for (in the pre-C++11 days) very little gain in syntax.  Maybe one of these days somebody will come up with a neat, efficient "connection string generator" in modern C++ which actually makes their code simpler.  Anyone could do it on top of the existing API, after all.

**Comment by jtv** [comment]
I've updated the most immediately obvious examples on the site.  I'll have to do the in-tree examples later; right now I'm in the middle of big changes for 7.0.

**Comment by JeffAbrahamson** [comment]
Thanks for the quick update!

**Comment by jtv** [comment]
Got this done at last!
