### ISSUE TITLE
Reusing re-activated connection throws "broken connection"

### ISSUE THREAD

**Issue by hmax** [jtv/libpqxx#205]
Hello. I'm having a problem with reusing broken connections (using pqxx 6.2.5, but I've examined the source code of 6.4.5 and was not able to find any changes in issue-related code that might fix it), which is reproduced with the following steps:

1. Establish connection to postgresql server and execute some simple query (say, SELECT 1)
2. Break the connection in some way, e.g. shutting down the postgres server
3. Restore the connectivity (bring the server back up)
4. Re-activate the connection (check is_open() and call activate())
5. Call the pqxx::work or pqxx::nontransaction connstructor, supplying the re-activated connection

During the 5th step I'm getting the broken_connection exception thrown at this line:
https://github.com/jtv/libpqxx/blob/6.2.5/src/connection_base.cxx#L553

After modifying the code to get the error message at this line, the error is as follows:

> server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

This looks to me as if I'm either not restoring connection properly, or the restoration procedure might leave the connection in some not-quite-clean state.

The issue, however, goes away after this first exception being thrown. Also, explicitly calling get_notifs() on connection is allowing me to use the connection afterwards, but this looks more like a workaround than the solution.

**Comment by jtv** [comment]
Connection reactivation is going away in libpqxx 7, on which I'm currently working.  So to be honest, I'd recommend just not using this feature.  If a connection breaks, just create a new one.

**Comment by hmax** [comment]
Creating new one helped solve the problem, thank you
