### ISSUE TITLE
Documentation of field.as<>() is not satisfying.

### ISSUE THREAD

**Issue by stastnypremysl** [jtv/libpqxx#206]
I am trying to figure out how to correctly select date field using libpqxx and I can't find any help in the documentation. 

I am considering the method described [here](https://stackoverflow.com/questions/57538339/how-to-correctly-select-date-field-using-libpqxx), but the documentation doesn't specify, what types are allowed for field.as<>(). Shouldn't it be written there?

And do you know the answer for my problem please?

**Comment by JadeMatrix** [comment]
`field.as<>()` will work with any type for which a specialization of `pqxx::string_traits<>` exists.  libpqxx comes with support for `std::string`, builtin numerics (`int`, etc.), and maybe a few others I don't remember.
Support for `std::chrono::` types are missing by default, unfortunately.  You can implement your own, but be warned that they will only work for `TIMESTAMP WITHOUT TIME ZONE`, `DATE`, `TIME WITHOUT TIME ZONE`, and `INTERVAL`.  To correctly support `… WITH TIME ZONE` you will need Howard Hinnant's [`date`](https://github.com/HowardHinnant/date) library, which is what I use (there is talk of adding it to the standard library).
If you want, I can share my code, which relies on `date` functionality for parsing Postgres date/time strings (ISO 8601 format).

**Comment by stastnypremysl** [comment]
Thank you.

**Comment by jtv** [comment]
The `type_traits` conversion system is going to be radically different in 7.0, but it will support the same types (and a few more, I  think).  However you can still to `pqxx::to_string` and `pqxx::from_string` on those types.

So far, every time I've looked into date/time support (which was once every few years) I ran into problems: different date formats, mismatches between C++ types and SQL types, and so on.  Highly frustrating.

**Comment by jtv** [comment]
I'll just close this ticket then.

**Comment by JadeMatrix** [comment]
@stastnypremysl Sorry, lost track of this ticket.  Here's the `date` library support I mentioned: https://gist.github.com/JadeMatrix/ef9c5b0292d3370c674233355850528b
