### ISSUE TITLE
Unit test compiled under nmake fails test_type_name

### ISSUE THREAD

**Issue by ash-j-f** [jtv/libpqxx#212]
test_type_name gives the following output:
```
Running: test_type_name
Test failure in test/unit/test_type_name.cxx line 17: type_name<std::shared_ptr<int>> came out weird. (pqxx::type_name<std::shared_ptr<int>> <> "std::shared_ptr<int>": actual=class std::shared_ptr<int>, expected=std::shared_ptr<int>)
FAILED: test_type_name
```
The difference being VC++ adds "class" at the start of the returned name for "std::shared_ptr<int>" for some reason.

Unit test code is:
```
PQXX_CHECK_EQUAL(
	pqxx::type_name<std::shared_ptr<int>>,
	"std::shared_ptr<int>",
	"type_name<std::shared_ptr<int>> came out weird.");
```
Though this error may be benign as I haven't run into any issues using this build yet.

**Comment by ash-j-f** [comment]
I noticed this change might be related https://github.com/jtv/libpqxx/commit/01c8f9b465b2a4153c9c3c49bd9a0ec529adb512

**Comment by ash-j-f** [comment]
The above above changes by KayEss were removed when that series of template definitions were removed here https://github.com/jtv/libpqxx/commit/500025f109b8d1afb5d0051e61d16b776a887318#diff-7c458c8f0ee5dfd0101a8e2fdc3aa392

Perhaps it's just the test needs updating? :)

**Comment by KayEss** [comment]
It just looks like a platform difference in the name demangling to me. Totally benign. Not sure how Jeroen wants to account for that in the test though.

In C `struct` is a separate namespace to the globals, so this might just be an artifact of that in MSVC's mangling mechanism.

**Comment by jtv** [comment]
Yes, it's a totally benign platform difference.  Grrr.  I tried to keep that test minimal exactly to avoid these...  May end up testing just `int`.  :(
