### ISSUE TITLE
Default optimization mode

### ISSUE THREAD

**Issue by kalman5** [jtv/libpqxx#217]
I notice that no optimization mode is used when compiling (tag 6.4.5) so compiler (at least gcc) defaults to -O0. Is there any specific reason for it?

**Comment by jtv** [comment]
How are you building..?  The `configure` script by default produces Makefiles with `-O2`.

**Comment by jtv** [comment]
Whoa!  You're right — it's not `-O2` like it used to be.  What's going on?

**Comment by jtv** [comment]
Wait wait wait I just checked and it's `-O2` when I don't set `CXXFLAGS`.  Any chance that in that case that variable happened to be set for some other reason?

**Comment by kalman5** [comment]
I build using cmake:
mkdir build && cd build && cmake .. && make -j3

**Comment by kalman5** [comment]
I tried with:
./configure --disable-documentation --enable-shared

and I'm observing that some compilation unit are not being built with fPIC, as example row.cxx is missing fPIC while util.cxx

libtool: compile:  g++ -DHAVE_CONFIG_H -I../include -I../include -I/usr/include/postgresql -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT row.lo -MD -MP -MF .deps/row.Tpo -c row.cxx -o row.o >/dev/null 2>&1
libtool: compile:  g++ -DHAVE_CONFIG_H -I../include -I../include -I/usr/include/postgresql -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT util.lo -MD -MP -MF .deps/util.Tpo -c util.cxx  -fPIC -DPIC -o .libs/util.o

This leads to some error in application as:

usr/bin/ld: /usr/local/lib/libpqxx.a(strconv.o): relocation R_X86_64_TPOFF32 against `_ZGVZN12_GLOBAL__N_118to_string_fallbackIlEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_E1S' can not be used when making a shared object; recompile with -fPIC

I'll switch for the moment using the shared lib version

**Comment by tt4g** [comment]
Try specifying the optional argument `-DCMAKE_BUILD_TYPE=Release` when running `cmake`: `mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j3`

* [CMAKE\_BUILD\_TYPE — CMake 3\.15\.3 Documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html)

**Comment by kalman5** [comment]
I'm getting  O3 twice

cd /home/kalman/git_store/libpqxx/build/src && /usr/bin/c++   -I/home/kalman/git_store/libpqxx/build/include -I/home/kalman/git_store/libpqxx/include -I/usr/include/postgresql -I/usr/include/postgresql/10/server  -O3 -O3 -DNDEBUG   -std=c++11 -o CMakeFiles/pqxx_static.dir/array.cxx.o -c /home/kalman/git_store/libpqxx/src/array.cx

**Comment by tt4g** [comment]
> I'm getting O3 twice :D

In CMake, `-O3` may be defined twice in `CMAKE_CXX_FLAGS` or `CMAKE_CXX_FLAGS_RELEASE`.
However, since these are affected by the environment variables, it is not possible to determine whether the cause is only in the project `CMakeLists.txt`.

* [CXXFLAGS — CMake 3\.15\.3 Documentation](https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html)

I think it will take time to investigate the cause. And the `-O3` flag should not affect the compilation result even if it is specified more than once.

For reference, The libpqxx 6.4.5 static library log that I built with Windows Visual Studio 2017 amd64 specified the `/O2` flag only once.

**Comment by kalman5** [comment]
I figure out why -O3 twice, that because I have added a -O3 on my own. No need to investigate.
