### ISSUE TITLE
Trigger broken_connection without sending a sql query

### ISSUE THREAD

**Issue by bogdanul2003** [jtv/libpqxx#219]
I was wondering if there is any function I can call that will only check the connection to DB, if the DB is down it should throw an exeption, otherwise do nothing. At the moment I get a connection exception only if I insert a query in the pipeline. 
Do you recommend that I send a low demanding query (like select now();) from time to time to trigger this check ?

**Comment by jtv** [comment]
For now, yes, sending a query would be the immediate solution.  It can be even lighter than `SELECT now()`; you could just `SELECT null`.

In the longer run, there's a `PQping` function in libpq, so it shouldn't be hard to build something especially for this.

**Comment by jtv** [comment]
Upon closer inspection, `PQping` is not what you want.  :(  It tries to _connect,_ it doesn't check up on an existing connection.

So yeah, `SELECT null` looks like the right thing to do.

**Comment by bogdanul2003** [comment]
@jtv is there a plan to include this kind of ping functionality ?

**Comment by jtv** [comment]
@bogdanul2003 Not without direct support in libpq, no.

The best thing I could do would be to send an empty or minimal query to the server — but then we've got to worry about whether you're in a transaction or not, and what if you're in a special state...  When you execute a query yourself, at least the implications will be obvious.

Mind if I close the ticket?

**Comment by tt4g** [comment]
For your information.

The connection pool library that I used when using Java provided this feature: [brettwooldridge/HikariCP](https://github.com/brettwooldridge/HikariCP)

In the connection pool, if there is a connection that has not been used for a certain period of time, the validity of the connection was verified using a validation statement (e.g. `SELECT 1 as one`).

I think the reason this feature is provided is that the connection pool managed a large number of connections over a long period of time and it was necessary to remove timed out connections from the pool.

It would not be easy to provide equivalent functionality inside libpqxx that is based on single connection delivery.

However, you can store your connection created with libpqxx in your own connection pool and create your own class that validates with a validation statement when you retrieve a connection from the pool.

**Comment by bogdanul2003** [comment]
@jtv , @tt4g  thanks for the details.
