### ISSUE TITLE
Can't Link On Windows 10 x64

### ISSUE THREAD

**Issue by LeonineKing1199** [jtv/libpqxx#220]
I've downloaded PostgreSQL 11.5 for x86-64 Windows.

Pulling down the code and checking out the tag `6.4.5` and then running:
```
C:\Users\cmaza\cpp\libqpxx\6.4.5\libpqxx\build>cmake -G"Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/cmaza/cpp/libpqxx/6.4.5/install -DPostgreSQL_INCLUDE_DIR="/Program Files/PostgreSQL/11/include" -DPostgreSQL_LIBRARY_DIR="/Program Files/PostgreSQL/11/lib" ..

C:\Users\cmaza\cpp\libqpxx\6.4.5\libpqxx\build>cmake --build .
ninja: warning: multiple rules generate src/pqxx.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]
[1/2] Linking CXX executable test\unit\unit_runner.exe
FAILED: test/unit/unit_runner.exe
```

This will fail with output:
```
ng output:
test_transaction_base.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_transactor.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_sql_cursor.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_stateless_cursor.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_stream_from.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_subtransaction.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_read_transaction.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_result_iteration.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_result_slicing.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_row.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_cursor.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_parameterized.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_pipeline.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
test_prepared_statement.cxx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: static int __cdecl pqxx::internal::builtin_traits<int>::null(void)" (__imp_?null@?$builtin_traits@H@internal@pqxx@@SAHXZ)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::string_traits<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,void>::null(void)" (__imp_?null@?$string_traits@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@X@pqxx@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)
```

**Comment by jtv** [comment]
I'm making wild guesses here: what if this compiler does not respect the inline nature of that function, and also does not export it despite _the struct in which it lives_ being exported?

Clutching at straws, but it's something we could try.  If you edit `include/pqxx/strconv.hxx` and change line 108 from:

      [[noreturn]] static TYPE null() { throw_null_conversion(name()); }

...by adding `PQXX_LIBEXPORT`, so it becomes:

      [[noreturn]] static PQXX_LIBEXPORT TYPE null() { throw_null_conversion(name()); }

Does that affect the problem at all?

**Comment by jtv** [comment]
Any news?  It's definitely not an outdated compiler then, so I wonder what we're going to learn here.

**Comment by dazcjones** [comment]
I have run into this problem as well, though in msvc 2017 x64.  I was able to get it to build by moving all the functions in builtin_traits to the macro PQXX_DECLARE_STRING_TRAITS_SPECIALIZATION except from_string and to_string as follows:
....
template<typename TYPE> struct PQXX_LIBEXPORT builtin_traits
{
  static void from_string(const char Str[], TYPE &Obj);
  static std::string to_string(TYPE Obj);
};
} // namespace pqxx::internal


/// Helper: declare a string_traits specialisation for a builtin type.
#define PQXX_DECLARE_STRING_TRAITS_SPECIALIZATION(TYPE) \
  template<> struct PQXX_LIBEXPORT string_traits<TYPE> : \
    internal::builtin_traits<TYPE> { \
        inline static constexpr const char *name() noexcept \
            { return internal::type_name<TYPE>::value; } \
        inline static constexpr bool has_null() noexcept { return false; } \
        inline static bool is_null(TYPE) { return false; } \
        [[noreturn]] static TYPE null() { pqxx::internal::throw_null_conversion(name()); } \
    };

Once I did this, I a few more linker errors.  They were fixed by removing
"PQXX_LIBEXPORT" from pqxx::internal::for_glyphs
and adding "PQXX_LIBEXPORT" to void stream_from::extract_value<std::nullptr_t>


I am not sure what caused the first issue.  I believe the secondary issues where caused because msvc wants you to export specializations but not export templates.

**Comment by jtv** [comment]
Does this problem still occur?

**Comment by LeonineKing1199** [comment]
I've since switched to using vcpkg which can build and link the library correctly.

**Comment by jtv** [comment]
OK, I'll close the ticket then.

**Comment by jtv** [comment]
Update: I've got the CMake build working on AppVeyor.  And since this shows that the CMake build can work on Windows, I have _removed the custom Visual C++ build files._

The one big remaining problem with the CMake build right now is that it only builds a shared library.  We'll fix that.
