### ISSUE TITLE
Error when following VC++ Instalation

### ISSUE THREAD

**Issue by SelfLeaker** [jtv/libpqxx#224]
The following error occurred when running `nmake /f win32/vc-libpqxx.mak ALL`

```
cl.exe /nologo /EHsc /FD /GR /c /std:c++17  /I "include" /I "C:\Program Files\PostgreSQL\12\include" /I "C:\Program Files\PostgreSQL\12\include"  /D "WIN32" /D "_MBCS" /D "_WINDOWS" /D "PQXX_INTERNAL" /D "NOMINMAX" /MDd /Gm /ZI /Od /D "_LIB" /D "_DEBUG" /RTC1 /Fo"ObjStaticDebug\\" /Fd"ObjStaticDebug\\" src/strconv.cxx
cl : Linha de comando warning D9035 : opção 'Gm' foi preterida e será removida em uma versão futura
strconv.cxx
C:\Users\User\libpqxx\src\strconv.cxx(63): error C2737: '`anonymous-namespace'::hard_neg': o objeto 'constexpr' deve ser inicializado
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\bin\HostX64\x64\cl.exe"' : código de retorno '0x2'
Stop.
```

**Comment by jtv** [comment]
Oops, thanks for reporting that!  You're working from the still-experimental 7.0 prototype of libpqxx, so for production use, consider using the 6.4 tag.

However I've just pushed a fix for this problem in the master branch, and I'd be very interested to hear if it works for you.  I tried it on various gcc and clang versions, but I don't have Visual Studio.

**Comment by jtv** [comment]
The additional libraries are needed by libpq, the C-level postgres client library. (And  libpqxx needs libpq, but doesn't really know what's inside of libpq).  It sounds as if you've got an incomplete install of libpq.

Thanks for the updates — it's very important to me to know how things work on Visual Studio!

**Comment by SelfLeaker** [comment]
Dependency problems fixed by using vcpkg.
Command used `vcpkg install libpqxx:x64-windows`
Tips given by @bugproof

**Comment by jtv** [comment]
Good to hear!

**Comment by jtv** [comment]
Update: I've got the CMake build working on AppVeyor.  And since this shows that the CMake build can work on Windows, I have _removed the custom Visual C++ build files._

The one big remaining problem with the CMake build right now is that it only builds a shared library.  We'll fix that.
