### ISSUE TITLE
Serializing/deserializing JSONb

### ISSUE THREAD

**Issue by davidglavas** [jtv/libpqxx#226]
Is there a way to convert a plain text JSON document to the internal JSONb binary format that postgres uses? Ideally there would be serialize() and deserialize() functions, does something like this exist?

My goal is to measure the serialization/deserialization time for some json documents, as well as measuring the time to access specific values of the JSONb document.

**Comment by jtv** [comment]
At the moment libpqxx only supports text formats, and to my knowledge, that's the normal way to read and write JSONB fields.  You don't really notice the internal binary format, it's just a more efficient way of storing JSON.

You can extend the library with additional text conversions for your own types, so it's possible to build your own JSON class(es) and write conversions.  You do that by specialising libpqxx's `string_traits` struct template for your type, and implementing its `to_string` and `from_string` member functions.  It's actually growing into something a bit more complicated to support stronger optimisation, in the run-up to libpqxx 7.0, so you may need to implement additional member functions and specialise the `str` class template.  But for something as complex as JSON, I'd just run it through your own favourite parser and generator at the moment.

**Comment by davidglavas** [comment]
What exactly do you mean by "libpqxx only supports text formats"?

**Comment by JadeMatrix** [comment]
The distinction between `JSON` and `JSONB` is a server-side optimization only, queries are still performed in a text format.  (Unless you want to use the libpq binary API, but I'm not sure how that affects returned JSON blobs).

**Comment by davidglavas** [comment]
I understand that JSONB is only used internally for performance reasons. So the key difference is that json data is stored as an exact copy of the JSON input text, whereas jsonb stores data in a decomposed binary form, that is, not as an ASCII/UTF-8 string, but as binary code.

So when inserting a plain text JSON document, at some point it needs to be converted into the JSONB binary format? And to retrieve the entire JSON document (as plain text) at some point the JSONB document needs to be converted back to plain text JSON. Do you agree?

**Comment by davidglavas** [comment]
I'm looking for something like [this](http://mongocxx.org/mongocxx-v3/working-with-bson/). Its the binary JSON format that MongoDB uses. They offer these two functions:

```
// convert BSON to json
std::string plain_text_JSON = bsoncxx::to_json(bsonObj);

// convert json to BSON
bsoncxx::from_json(plain_text_JSON)
```

I'm wondering if there is something similar for postgres' binary JSON format (JSONB)?

**Comment by jtv** [comment]
Yes, those conversions to and from JSONB need to happen, but the server does them for us.  In terms of transferring data from your client code to libpqxx, and from there to libpq, and from there to the server, it's just regular JSON.

The protocol between libpq and the server also supports a binary transfer format, but it's not fully specified and libpqxx does not support it yet.  It's _possible_ that the binary format exposes a binary encoding of JSONB, but right now we don't know it.

**Comment by davidglavas** [comment]
I see, so right now there is no information on how exactly the jsonb encoding works ([something like this](http://bsonspec.org/spec.html))?

**Comment by jtv** [comment]
Right.  The information exists, of course, but not in our realm.

**Comment by davidglavas** [comment]
By "our realm" do you mean the general public? I can't find a specification of jsonb anywhere, is it accessible only to postgres developers?

**Comment by jtv** [comment]
Of course the information is available to the public (since the full PostgreSQL source code is available to anyone), but to my knowledge it's not _exposed to client code._

But I could be wrong, in which case the encoding would be part of the binary data format.  In which case, it would be accessible except (1) it's not fully documented and/or not guaranteed to remain stable, and (2) libpqxx does not support it yet.

**Comment by davidglavas** [comment]
I see, so these operations are not supported by libpqxx. The functions I want to use are there (in the [postgres code](https://github.com/postgres/postgres/blob/master/src/include/utils/jsonb.h)), so a workaround would be to somehow link to PostgreSQL code to use the jsonb functions I need (as described in this [question](https://stackoverflow.com/questions/59377784/using-postgres-jsonb-directly))?

Do you think it's possible to somehow use Postgres' jsonb code (call the functions and measure time they take to execute)?

**Comment by JadeMatrix** [comment]
@davidglavas It's not very clear what you're trying to accomplish.  If you're not trying to connect to a Postgres server running on the same or a different machine, you probably want to skip `libpqxx` and `libpq` entirely.  If so, I'd suggest creating an issue over on the Postgres repo as those folks will probably be able to help much better.

**Comment by jtv** [comment]
You're talking about using a data format that's _internal to PostgreSQL._  As far as client code is concerned, to my knowledge, the data format is JSON.

To me this is a lot like an object in C++: you can see that the class exists, the object has state, you can call its public member functions, but the way that data is stored in its private data members is abstracted away.  This is how the postgres server presents JSONB to us: you can feed JSON into it and get JSON out of it, and call functions on it, but the actual JSONB format is private.
