### ISSUE TITLE
Question: Pooling?

### ISSUE THREAD

**Issue by Laro88** [jtv/libpqxx#229]
I am fairly new to Postgresql (and therefore libpqxx as well)

Is there some build-in inhibitors that prevents simple connection pooling? I have come to like the rapid response from mysql and ms sqlserver with regards to connection maintenance, just set it up and the connections are immediately ready...

When trying to pool connections the queries fails from time to time, but I haven't seen any mentioning of connections being single query / transactio use only.

**Comment by jtv** [comment]
That's right, there's nothing stopping you from performing multiple transactions on a single connection.  Of course there isn't!  (Just so long as you don't have more than one at the same time — and even _that_ is possible with `subtransaction`, but then they need to be nested).

It may help to know just what failure you see.  For example, could you be opening more connections than your backend will allow?  Or might there be a race condition in your pool?

**Comment by Laro88** [comment]
Our problem seems to be with prepared statements. When reusing a connection a call to unprepare seems to fix it.

**Comment by tt4g** [comment]
IMHO, The Java connection pool library I have used records all the prepared statement registrations. Cleaned all prepared statements that were recorded when returning a connection to the connection pool.

**Comment by jtv** [comment]
I agree with @tt4g: sounds like a possible weakness in the connection pool.  But there's also a change in libpqxx: the current `master` loops "prepare" statements straight through to the back-end, so re-preparing a statement will result in an error.

Older versions, such as the current stable release 6.4,5, cache the definitions and quietly ignore identical re-definitions.  So as long as your prepared statement doesn't change, the older libpqxx releases would have hidden the problem from you.

**Comment by Laro88** [comment]
sidequestion, how large is the overhead on unpreparing? I am asking since it might be a better solution to have a factory that keeps a queue of connections made in advance. Is this sensible. We have irregular loads on the server with a lot of queries running more or less random.

**Comment by jtv** [comment]
Shouldn't be too costly, unless your queries are really hard to plan.  When in doubt of course, measure your own specific case.

But if performance is an issue, I would say the most important question is: Do prepared statements really help performance in your specific case?  I bring that up a lot because the optimiser comes up with an execution plan at the time when you prepare the statement, but the statement typically takes some parameters.  The optimiser may be able to come up with a better plan if it knows the actual argument values that you pass for a given invocation.  So unless your query is particularly hard to _plan,_ or is simple enough that the optimal plan doesn't change from one invocation to the next, it may be faster to use regular, non-prepared statements.

Sometimes the case where prepared statements do well will be repeated INSERTs.  But in those cases, you may be better off with `stream_to`.

**Comment by Laro88** [comment]
Thank you for your assistance @jtv much appreciated.
Sidenote.
I will make a test using "stream_to" to see if we can get a performance improvement. The case is that we would like to make inserts of a lot of MQTT packets as documentation for system behavior. I know that flat files would be easier and more suitable for this stream dumping, but for now we are required to go to the database directly.

**Comment by jtv** [comment]
The `stream_to` class is for doing bulk inserts.  Should save you a lot of time.  But don't let them just go on forever, or your transactions will go on for too long, and that will hurt database performance overall as locks stay open, changes pile up without  being committed, etc.

**Comment by Laro88** [comment]
I have done some benchmarking opn the stream_to vs regular inserts.

Tests with array sizes of 5, 100, 1000, 10K and 30K elements
Short summary:
5 elements then the stream_to is ~1.3 times faster
100 elements 8 times faster
1000 elements 10 times faster
10K elements 11 times faster
30K elements 11.7 times faster

I did not consider memory or cpu usage, just a raw timing dump (ran a couple of times yada yada)
Lets just say that I am perfectly happy with the speedup and will port the other buffer and insert calls to this.
There might be a little to gain by using a bit of std::move magic instead of std::get but it is probably not worth it.

Database inside docker, running on an I7 7th gen. With +1000 items single inserts is around 50-70us with to stream and 500-800us with normal inserts

Insert functions from our lib is here (reprepare is just to clean previous prepared queries which is not present in the test, and the buffer is the implementation to reuse connections.

```
typedef std::tuple<std::string, char*, int, long long> mqttmessage;
```

```
//Save the mqtt capture buffer - to be called from somewhere threadsafe
void RegisterMQTTDatagrams(std::vector<mqttmessage> Messages)
{
  auto c = DatabaseIO::GetPoolConnection();
  std::string q = "INSERT INTO trace_mqtt (rxtimestamp, topic, payload, len) VALUES ($1,$2,$3,$4)";
  pqxx::work w(*c);
  c.reprepare("insert_trace_mqtt", q);

  for(auto const& message : Messages)
  {
    long long rxts = std::get<3>(message);
    std::string topic = std::get<0>(message);
    char* ptr = std::get<1>(message);
    int len = std::get<2>(message);
    w.prepared("insert_trace_mqtt")(rxts)(topic)(ptr)(len).exec();
    delete ptr;
}
w.commit();
}

//Same as RegisterMQTTDatagrams but using stream_to - call from threadsafe
void RegisterMQTTDatagrams_stream_to(std::vector<mqttmessage> Messages)
{
auto c = DatabaseIO::GetPoolConnection();
pqxx::work w(*c);
pqxx::stream_to stream_to{ w, "trace_mqtt"
, std::vector<std::string>{"topic", "payload", "len", "rxtimestamp"} };

for(auto const& message : Messages)
{
stream_to << message;
}

stream_to.complete();
w.commit();
}
```

**Comment by jtv** [comment]
Hey, this is wonderful data, thanks!  @JadeMatrix will be happy to hear it as well — he contributed most of that code.  :)

The speedup in itself is no real surprise, but it's nice to see that the  speedup comes _so early,_ with just a few rows.  So there's no real tradeoff to be made: inserts are basically just faster this way.

**Comment by JadeMatrix** [comment]
@Laro88 I don't think you need to explicitly pass a vector of strings to `stream_to`'s constructor, it *should* be templated generically enough to use an initializer list to reduce code 'noise' (and `std::string` constructor overhead):
```cpp
pqxx::stream_to stream_to{
    w,
    "trace_mqtt",
    {"topic", "payload", "len", "rxtimestamp"}
};
```
If it doesn't work this way that's a bug.

**Comment by jtv** [comment]
@JadeMatrix I hope I didn't break that, but I did remove some of the type cleverness from your code.  I _think_ it only affected the "generic `std::optional`-like type" code though.

(Perhaps we can restore the cleverness with C++20, when we have Concepts and such.  I'm fighting the temptation to skip C++17 altogether.  :-) )

**Comment by Laro88** [comment]
@JadeMatrix @jtv just checked on my setup, std::vector<std::string> is needed, but I can live with that considering the performance gain I get from stream_to :-)

**Comment by jtv** [comment]
I don't know off the top of my head (hey, I'm on vacation!) but if you already have the strings stored somewhere, you might be able to do it with something faster and lighter, e.g. a `std::array<std::string_view>` or something along those lines.

**Comment by JadeMatrix** [comment]
Looking at the current `stream_to`/`stream_from` code, I don't see anything preventing the use of implicit `std::initializer_list<const char*>`, unless the compiler is choking on a lack of `std::forward`s.  I'll take a look at that if I have time.
