### ISSUE TITLE
Build Fails on Mac OS X

### ISSUE THREAD

**Issue by carlosb** [jtv/libpqxx#23]
Consult the full error log here: [log.txt](https://github.com/jtv/libpqxx/files/1234723/log.txt)

So the build fails on Mac OS X with AppleClang8.1 with the error output shown in the log. This is because it apparently doesn't recognize that it is C++11 syntax. This is easily amended by passing the `-std=c++11` flag to the compiler. For anyone having this problem just be sure to pass `make` the flag like so:

`make CXXFLAGS="-std=c++11"` 

Maybe add a flag to the Makefile in order to eliminate any doubts that the compiler will compile for C++11?

**Comment by jtv** [comment]
Remember to run the configure script!  That is where you should set your compiler options, not the Makefile itself.

**Comment by jtv** [comment]
I just got "configure" to add the C++11 option automatically.
