### ISSUE TITLE
Deprecated prepared().exists() replacement?

### ISSUE THREAD

**Issue by leolchat** [jtv/libpqxx#230]
We manage a pool of connections and when we acquire one of them we want to make sure some statement is already prepared (unless what we do call the `prepare()` method). Our current code calls `prepared(name).exists()` but this has been deprecated. What is the replacement? I could not find anything in the documentation.

**Comment by jtv** [comment]
I'm afraid there is no replacement at the moment.  In 7.0 you'll have to query the system catalog to check whether the statement has been prepared, or track it directly in your application.  But if you need this, I could add a function that queries the system catalog for you.

It seemed helpful for libpqxx to track and manage the state of prepared statements, but in the end it was too complicated and error-prone.  It's now once again between the application and the server.

**Comment by BFamzz** [comment]
> But if you need this, I could add a function that queries the system catalog for you.

Hi @jtv please is the function available? If not, how can this be implemented?

Thanks.

**Comment by jtv** [comment]
@BFamzz there's a table `pg_prepared_statements` in the system catalog.  You can just query that:

```
user=> select * from pg_prepared_statements;
 name | statement | prepare_time | parameter_types | from_sql 
------+-----------+--------------+-----------------+----------
(0 rows)

user=> prepare foo as select 1;
PREPARE

user=> select * from pg_prepared_statements;
 name |        statement         |         prepare_time          | parameter_types | from_sql 
------+--------------------------+-------------------------------+-----------------+----------
 foo  | prepare foo as select 1; | 2022-01-27 13:31:27.377793+01 | {}              | t
(1 row)
```

**Comment by BFamzz** [comment]
Alright. Thanks a lot @jtv
