### ISSUE TITLE
Request to have a CI setup for Windows/Linux platforms

### ISSUE THREAD

**Issue by sanojsubran** [jtv/libpqxx#231]
It would be nice to integrate this project into a CI system (like Appveyor) to make sure that the daily builds/tests are successful and supporting OS , Postgres, compiler versions can be summarized in the project page.

**Comment by KayEss** [comment]
It's already on Circle CI I think. Was there anything else in particular you wanted to see?

**Comment by jtv** [comment]
It's on CircleCI, yes.  I think the main area where I could use better CI is in Windows support.  Is there an automated service to test on Windows, particularly to test against Visual C++ and MinGW?

**Comment by sanojsubran** [comment]
Yes, I am more interested in the windows builds right now. I tried to compile the 6.4.5 release code base according to the build steps mentioned in the win32 folder in the repo and building the testcases failed. Also when I tried to integrate with my application it was giving similar linker errors. There is already a bug opened for the same #220 . I used visual studio 2015 in windows 10.

But if I use Visual studio 2017, everything compiles fine and it is working. But for my project, I have to compile it in vs2015. So I was wondering if there is an information summary for which all compilers/OSs it has been tested for the daily builds/release builds, it would be convenient for the library users. I will be glad to help if I can do something towards it.

@jtv  [Appveyor](https://ci.appveyor.com/) seems to have support for windows for automation and testing

**Comment by jtv** [comment]
It would absolutely be useful to have a list of which compilers work and which don't — but of course my resources are limited.  I couldn't possibly maintain such a list, on top of _actually fixing_ the problems that show up, which of course is the main thing.  :)

I'll have a look at AppVeyor, and see if I can set up a build there.  But I'll probably need to stick to a very limited list of compilers.

**Comment by jtv** [comment]
Oo!  I've got a build going.  The initial debugging for these environments is always a little frustrating, but this went pretty fast.

I'm horrified at the number of warnings.  I expect to be busy for a while fixing those.  On my own system I treat all warnings as errors — perhaps I can get Visual Studio to that stage as well.

@sanojsubran thanks for making me do this.  :)

**Comment by sanojsubran** [comment]
@jtv Thats great. Could you please tell me the details of your compiler/OS version ?

I try to download the library using vcpkg and it is crashing with a simple example with making a connection to the database. I am trying out different options now. I am using vs2017 and win10

**Comment by jtv** [comment]
On AppVeyor I'm trying `master` with Visual Studio 2019, and the default OS.  It fails though — I'll have to spend some time sorting through the output and making fixes.

**Comment by sanojsubran** [comment]
I found out the issue with ones from vcpkg. I was using the release libraries, but my project was in debug mode. Sorry, my mistake.
This [link](http://pqxx.org/development/libpqxx/wiki/FaqTroubleshooting) helped.

**Comment by jtv** [comment]
Glad to hear _that's_ resolved then.  But now I have my own VS build to fix!  :-D

**Comment by sanojsubran** [comment]
@jtv  Do you think it is a good idea to distribute prebuilt binaries atleast for windows as part of a major release, since windows doesn't have an official package manager ? I found it quite convenient for boost libraries even though it is not from their official website. 

I understand your time constraints. But would you consider it as an option for major releases from a repo maintainer's perspective?

**Comment by jtv** [comment]
I always sort of hoped that some real Windows developer somewhere would be willing to take up that responsibility.  But if it's easy enough to manage then yes, I can do that.

No promises though until we've done this for a while and know it doesn't fall apart too often.

**Comment by sanojsubran** [comment]
I think I can give it a try. Is there any way I contact you in future, other than by raising a bug here? :)

**Comment by mgoldshteyn** [comment]
I (a real windows developer with decades of experience) will be taking a look at "things," shortly.

**Comment by jtv** [comment]
@mgoldshteyn that would be wonderful!

**Comment by jtv** [comment]
Well, pretty happy to have AppVeyor set up now.  I'm also removing the custom build files for MSVC and MinGW.  It's just more build systems than I can maintain.  From now on, we'll just use either `configure` or CMake.

And at some point, we'll look at paring it down to just CMake.  Unless something better comes along before then.  Even two is one too many, really.

For now we're still stuck with the CMake build trying to build both a shared library and a static library.  After some crazy debugging (and perhaps a bit of beer), we found that the ".lib" library which goes with the ".dll" as the static "glue" was _overwriting the ".lib" library which served as the static library._  Thanks again @KayEss for the wild ride which led to this discovery, and so many others!
