### ISSUE TITLE
Postgres 12.1 error during build of pqxx

### ISSUE THREAD

**Issue by moodboom** [jtv/libpqxx#235]
I recently updated my ubuntu dev box to use postgresql v12.1 from the official postgres repository, and it seems to have confused CMake:
```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_TYPE_INCLUDE_DIR) (found
  version "12.1 (Ubuntu 12.1-1.pgdg18.04+1)")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPostgreSQL.cmake:175 (find_package_handle_standard_args)
  src/CMakeLists.txt:15 (find_package)
```

**Comment by tt4g** [comment]
`FindPostgreSQL.cmake` is provided by CMake.

PostgreSQL 12.x support has recently been added (CMake 3.16.0 and above).

You can provide additional PostgreSQL version by `set(PostgreSQL_ADDITIONAL_VERSIONS 12)`.

https://github.com/Kitware/CMake/blob/1b4482f65dd41f21ec8abc0777b8dc1f0381bbd6/Modules/FindPostgreSQL.cmake#L89-L90

**Comment by jtv** [comment]
Or it could be as simple as running `sudo apt install libpq-dev` in the terminal!

**Comment by moodboom** [comment]
I added that additional postgres version to the libpqxx CMakeLists.txt, and it worked like a charm, thanks @tt4g.  

(I already had libpq-dev installed, btw...)

I guess the final solution is to bump CMake (or wait for ubuntu to do so).  

Really appreciate the quick help, guys!
