### ISSUE TITLE
support PQencryptPasswordConn() (in class connection)

### ISSUE THREAD

**Issue by janhec** [jtv/libpqxx#237]
This is a function which is needed for servers operating with scram-sha-256, unless one wants to send plaintext passwords. PQencryptPassword() only does MD5.
I added
`  /// Interface  to PQencryptPasswordConn()
  PQXX_LIBEXPORT std::string encrypt_password(const char user[],
     const char password[], const char algorithm[]);
`
to connection.hxx and
`std::string pqxx::connection::encrypt_password(
   const char user[], const char password[], const char algorithm[])
{
   std::unique_ptr<char, std::function<void(char*)>> p{
    PQencryptPasswordConn(m_conn, password, user, algorithm),
         pqxx::internal::freepqmem_templated<char> };
   return std::string{ p.get() };
}
`
to connection.cxx
which is totally elementary, of course (and too simple for a pull request).
kind regards,
vriendelijke groet,
Jan

**Comment by jtv** [comment]
That's been on my to-do list for a while, so thanks for making me do it..s  Of course it's not quite as trivial as it sounds: I had to revive the configure header for libpq-related items, add an autoconf check with a new configuration item, and write a test.  And that's not quite the whole job yet: I need a CMake check as well!

**Comment by janhec** [comment]
Sorry for making it seem too easy;)
But thanks, it's a useful feature as people everywhere start shitting about
MD5.
Btw, the user parameter should be immaterial for the generated encrypted
password.
I chose for "quasimodo" as a classical standin. "user" is so ordinary;)
For me it works already, so don't feel pressed too much by me!
Jan
