### ISSUE TITLE
c++11 flag is not added in configure

### ISSUE THREAD

**Issue by Yanpas** [jtv/libpqxx#24]
`g++ -DHAVE_CONFIG_H -I../include -I../include -I/usr/include/postgresql -g -O2 -Wno-long-long -fvisibility=hidden -fvisibility-inlines-hidden -MT binarystring.lo -MD -MP -MF .deps/binarystring.Tpo -c binarystring.cxx  -fPIC -DPIC -o .libs/binarystring.o` - one of the lines that was executed. autotools must explicitly add -std=c++0x

**Comment by jtv** [comment]
Recent gcc versions compile C++14 by default.  If you're using an older version, add the flag to the "configure" command line:

`./configure CXXFLAGS='-std=c++11'`

(Of course you can also say c++14 to get a more modern dialect.)

I could add this option in the configure script, but that opens the door to questions like: What if your compiler uses a different option for this?  Which C++ versions does your compiler version support?  What if you want a different C++ version?  What if the compiler defaults to a newer version?

So the best solution, I think, is to set this option in your "configure" until your systems are upgraded to more recent compiler versions.  I was tempted to make C++14 the minimum, but I kept it to C++11 for now to minimise these problems...

**Comment by Yanpas** [comment]
Thanks, didn't know. I barely know autotools but CMake has `CXX_STANDARD` option. If there is something similar you may add this to configure script.

**Comment by jtv** [comment]
I don't know of anything like that, but now that you bring it up, I did notice something strange: on an _older_ gcc, if I passed `-std=c++17` or `-std=c++20`, the command line would still say `-std=c++14` — I guess maybe that was the newest standard which that compiler supported.

So probably there is _some_ logic for picking the C++ standard in there.  But I'm sort of afraid to mess with it!  :)

**Comment by jtv** [comment]
I just got "configure" to add the C++11 option. This does mean that autogen.sh now requires the autoconf-archive package.
