### ISSUE TITLE
Libpqxx throws an error in prepared statement when an array is included as one of the parameters.

### ISSUE THREAD

**Issue by BFamzz** [jtv/libpqxx#241]
`int createOrganizationOnDb(pqxx::connection& c, pqxx::work& w, std::string id, std::string salt,
	uint8_t hashedPassword[], organization& newOrganization) {

	std::string insertQuery = "INSERT INTO hospitals (" 
				"organization_id, " 
				"organization_name, " 
				"organization_address, "  
				"organization_type, " 
				"organization_rcNumber, " 
				"organization_email, " 
				"organization_country, " 
				"organization_state, "
				"organization_salt, " 
				"organization_hashedPassword, "
				"date_created, " 
				"date_updated" 
	") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW());";

	pqxx::result result;

	try {
		c.prepare("create_organization", insertQuery);
		result = w.prepared("create_organization")(id)(newOrganization.name)
			(newOrganization.address)(newOrganization.type)(newOrganization.rcNumber)
			(newOrganization.email)(newOrganization.country)(newOrganization.state)
			(salt)(hashedPassword).exec();

		w.commit();
	} catch (const std::exception& e) {
		std::cerr << e.what() << "\n";
		return -1;
	}

	return result.size();
}`

The above code is used to create an organization on the database (Postgresql). However, the project won't compile because of this array **(uint8_t hashedPassword[])** in my parameters. 

This is error being thrown: 

`In file included from /usr/local/include/pqxx/internal/statement_parameters.hxx:28,
                 from /usr/local/include/pqxx/prepared_statement.hxx:18,
                 from /usr/local/include/pqxx/connection_base.hxx:26,
                 from /usr/local/include/pqxx/basic_connection.hxx:23,
                 from /usr/local/include/pqxx/connection.hxx:20,
                 from /usr/local/include/pqxx/connection:6,
                 from /usr/local/include/pqxx/pqxx:4,
                 from /usr/src/cppweb/hello_crow/main.cpp:10:
/usr/local/include/pqxx/internal/type_utils.hxx: In instantiation of 'static bool pqxx::string_traits<T, typename std::enable_if<pqxx::internal::is_optional<T>::value>::type>::is_null(const T&) [with T = unsigned char*]':
/usr/local/include/pqxx/internal/statement_parameters.hxx:74:62:   required from 'void pqxx::internal::statement_parameters::add_param(const T&, bool) [with T = unsigned char*]'
/usr/local/include/pqxx/prepared_statement.hxx:135:4:   required from 'pqxx::prepare::invocation& pqxx::prepare::invocation::operator()(T*, bool) [with T = unsigned char]'
/usr/src/cppweb/hello_crow/main.cpp:230:25:   required from here
/usr/local/include/pqxx/internal/type_utils.hxx:187:49: error: incomplete type 'pqxx::string_traits<unsigned char, void>' used in nested name specifier
  187 |     { return (not v || string_traits<I>::is_null(*v)); }
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/usr/local/include/pqxx/internal/type_utils.hxx: In instantiation of 'static std::string pqxx::string_traits<T, typename std::enable_if<pqxx::internal::is_optional<T>::value>::type>::to_string(const T&) [with T = unsigned char*; std::string = std::__cxx11::basic_string<char>]':
/usr/local/include/pqxx/strconv.hxx:335:38:   required from 'std::string pqxx::to_string(const T&) [with T = unsigned char*; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/pqxx/internal/statement_parameters.hxx:76:28:   required from 'void pqxx::internal::statement_parameters::add_param(const T&, bool) [with T = unsigned char*]'
/usr/local/include/pqxx/prepared_statement.hxx:135:4:   required from 'pqxx::prepare::invocation& pqxx::prepare::invocation::operator()(T*, bool) [with T = unsigned char]'
/usr/src/cppweb/hello_crow/main.cpp:230:25:   required from here
/usr/local/include/pqxx/internal/type_utils.hxx:205:39: error: incomplete type 'pqxx::string_traits<unsigned char, void>' used in nested name specifier
  205 |     return string_traits<I>::to_string(*Obj);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/usr/local/include/pqxx/internal/type_utils.hxx: In instantiation of 'static constexpr const char* pqxx::string_traits<T, typename std::enable_if<pqxx::internal::is_optional<T>::value>::type>::name() [with T = unsigned char*]':
/usr/local/include/pqxx/internal/type_utils.hxx:204:59:   required from 'static std::string pqxx::string_traits<T, typename std::enable_if<pqxx::internal::is_optional<T>::value>::type>::to_string(const T&) [with T = unsigned char*; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/pqxx/strconv.hxx:335:38:   required from 'std::string pqxx::to_string(const T&) [with T = unsigned char*; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/pqxx/internal/statement_parameters.hxx:76:28:   required from 'void pqxx::internal::statement_parameters::add_param(const T&, bool) [with T = unsigned char*]'
/usr/local/include/pqxx/prepared_statement.hxx:135:4:   required from 'pqxx::prepare::invocation& pqxx::prepare::invocation::operator()(T*, bool) [with T = unsigned char]'
/usr/src/cppweb/hello_crow/main.cpp:230:25:   required from here
/usr/local/include/pqxx/internal/type_utils.hxx:184:36: error: incomplete type 'pqxx::string_traits<unsigned char, void>' used in nested name specifier
  184 |     { return string_traits<I>::name(); }
      |              ~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/include/pqxx/internal/type_utils.hxx:184:40: error: body of 'constexpr' function 'static constexpr const char* pqxx::string_traits<T, typename std::enable_if<pqxx::internal::is_optional<T>::value>::type>::name() [with T = unsigned char*]' not a return-statement
  184 |     { return string_traits<I>::name(); }
      |                                        ^
make[2]: *** [CMakeFiles/hello_crow.dir/build.make:63: CMakeFiles/hello_crow.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/hello_crow.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
The command '/bin/sh -c make' returned a non-zero code: 2`

Here is a screen shot:
![image](https://user-images.githubusercontent.com/38426051/71466872-3041a000-27c1-11ea-8dd1-b344896f797b.png)

Kindly help please. How do I resolve this?

**Comment by tt4g** [comment]
As far as I know, PostgreSQL Array-Type is not supported yet on pqxx version 6.4.5 and earlier.

I found `pqxx::array`, but only support parsing result set: [libpqxx: pqxx::array\_parser Class Reference](https://libpqxx.readthedocs.io/en/6.4/a00831.html)

If `organization_hashedPassword` is a characters-type such as `text` or `varchar` in PostgreSQL, you can cast `char *` type.

To string example:

```cpp
// Don't forget, must be set null-terminated character.
// `std::string::c_str()` automatically includes a null-terminated character.
std::string hashedPasswordString(static_cast<char *>(hashedPassword), (hashedPassword(a)/hashedPassword(*a));
```

Usage:

```diff
try {
	c.prepare("create_organization", insertQuery);
	result = w.prepared("create_organization")(id)(newOrganization.name)
		(newOrganization.address)(newOrganization.type)(newOrganization.rcNumber)
		(newOrganization.email)(newOrganization.country)(newOrganization.state)
-                (salt)(hashedPassword).exec();
+		(salt)(hashedPasswordString.c_str()).exec();

	w.commit();
} catch (const std::exception& e) {
	std::cerr << e.what() << "\n";
	return -1;
}

return result.size();
```

**Comment by jtv** [comment]
(This code will look profoundly different in 7.0, once it comes out.  I hope you'll find it easier.)

The issue here is not really that an array is being passed in, but that an unsupported form of _string_ is being passed in.  Strictly speaking it's not even an array — it's a _pointer to int8._  But as @tt4g points out, you can just cast that to a pointer to `char`.

**Comment by BFamzz** [comment]
> As far as I know, PostgreSQL Array-Type is not supported yet on pqxx version 6.4.5 and earlier.
> 
> I found `pqxx::array`, but only support parsing result set: [libpqxx: pqxx::array_parser Class Reference](https://libpqxx.readthedocs.io/en/6.4/a00831.html)
> 
> If `organization_hashedPassword` is a characters-type such as `text` or `varchar` in PostgreSQL, you can cast `char *` type.
> 
> To string example:
> 
> ```c++
> // Don't forget, must be set null-terminated character.
> // `std::string::c_str()` automatically includes a null-terminated character.
> std::string hashedPasswordString(static_cast<char *>(hashedPassword), (hashedPassword(a)/hashedPassword(*a));
> ```
> 
> Usage:
> 
> ```diff
> try {
> 	c.prepare("create_organization", insertQuery);
> 	result = w.prepared("create_organization")(id)(newOrganization.name)
> 		(newOrganization.address)(newOrganization.type)(newOrganization.rcNumber)
> 		(newOrganization.email)(newOrganization.country)(newOrganization.state)
> -                (salt)(hashedPassword).exec();
> +		(salt)(hashedPasswordString.c_str()).exec();
> 
> 	w.commit();
> } catch (const std::exception& e) {
> 	std::cerr << e.what() << "\n";
> 	return -1;
> }
> 
> return result.size();
> ```

Wow. Thanks a lot for helping out with this. 

Yes, **organization_hashedPassword is VARCHAR(256) on Postgresql.**

I am still learning C++ and I have some questions. Kindly bear with me. 

> - The function hashedPasswordString does not have a body and a return statement.
> 
> - What is the purpose of the second parameter in the hashedPasswordString function and also what do the variables **"a" and "*a"**  stand for? I know that array elements can be accessed by indexing the array within its bounds.
> 
> - When you called the function hashedPasswordString in the prepared statement, you did not use the parenthesis neither did you pass in any parameters before calling c_str() on it.
> 
>

**Comment by BFamzz** [comment]
> (This code will look profoundly different in 7.0, once it comes out. I hope you'll find it easier.)
> 
> The issue here is not really that an array is being passed in, but that an unsupported form of _string_ is being passed in. Strictly speaking it's not even an array — it's a _pointer to int8._ But as @tt4g points out, you can just cast that to a pointer to `char`.

Thanks alot. I understand it a lot better.

**Comment by tt4g** [comment]
> * The function hashedPasswordString does not have a body and a return statement.

`hashedPasswordString` is variable name, not function.

This is one of several C ++ initializations called direct initialization.

The following links will be helpful.

* [direct initialization \- cppreference\.com](https://en.cppreference.com/w/cpp/language/direct_initialization)
* [Initialization \- cppreference\.com](https://en.cppreference.com/w/cpp/language/initialization)

> * What is the purpose of the second parameter in the hashedPasswordString function and also what do the variables *"a" and "a" stand for? I know that array elements can be accessed by indexing the array within its bounds.

Sorry. my bad. `a` and `*a` are copy and paste mistakes.
This is correct: `std::string hashedPasswordString(static_cast<char *>(hashedPassword), (sizeof(hashedPassword)/ sizeof(*hashedPassword));`

As you may know, get the size of the array with `sizeof(array) / sizeof(*array)`.

> * When you called the function hashedPasswordString in the prepared statement, you did not use the parenthesis neither did you pass in any parameters before calling c_str() on it.

As mentioned earlier, `hashedPasswordString` is a variable.
`hashedPasswordString.c_str()` is `std::string::c_str()`.

The following code combines the two split samples:

```diff
try {
+    std::string hashedPasswordString(static_cast<char *>(hashedPassword), (sizeof(hashedPassword)/ sizeof(*hashedPassword));

	c.prepare("create_organization", insertQuery);
	result = w.prepared("create_organization")(id)(newOrganization.name)
		(newOrganization.address)(newOrganization.type)(newOrganization.rcNumber)
		(newOrganization.email)(newOrganization.country)(newOrganization.state)
-                (salt)(hashedPassword).exec();
+		(salt)(hashedPasswordString.c_str()).exec();

	w.commit();
} catch (const std::exception& e) {
	std::cerr << e.what() << "\n";
	return -1;
}

return result.size();
```

**Comment by BFamzz** [comment]
Thanks @tt4g for your help. Those links were helpful. 

The compiler threw an error when I implemented the above solution.

Here is the error it threw:

`/usr/src/cppweb/hello_crow/main.cpp: In function 'int createOrganizationOnDb(pqxx::connection&, pqxx::work&, std::string, std::string, uint8_t*, organization&)':
/usr/src/cppweb/hello_crow/main.cpp:228:76: error: invalid static_cast from type 'uint8_t*' {aka 'unsigned char*'} to type 'const char*'
  228 |   std::string hashedPasswordString(static_cast<const char *>(hashedPassword), (sizeof(hashedPassword) / sizeof(*hashedPassword)));
      |                                                                            ^
/usr/src/cppweb/hello_crow/main.cpp:228:101: warning: 'sizeof' on array function parameter 'hashedPassword' will return size of 'uint8_t*' {aka 'unsigned char*'} [-Wsizeof-array-argument]
  228 |   std::string hashedPasswordString(static_cast<char *>(hashedPassword), (sizeof(hashedPassword) / sizeof(*hashedPassword)));
      |                                                                                                     ^
/usr/src/cppweb/hello_crow/main.cpp:206:10: note: declared here
  206 |  uint8_t hashedPassword[], organization& newOrganization) {
      |  ~~~~~~~~^~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/hello_crow.dir/build.make:63: CMakeFiles/hello_crow.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/hello_crow.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

Here is a screenshot:

![image](https://user-images.githubusercontent.com/38426051/71512548-022e8f80-2897-11ea-8ec2-006fedb30f62.png)

How do I resolve this please? Thanks.

**Comment by tt4g** [comment]
> The compiler threw an error when I implemented the above solution.

Sure, The compile error is correct.

use `reinterpret_cast<char *>()` if `uint8_t` is `unsigned char` alias.

`sizeof` of array is not working if array is function variable: [ARR01\-C\. Do not apply the sizeof operator to a pointer when taking the size of an array \- SEI CERT C Coding Standard \- Confluence](https://wiki.sei.cmu.edu/confluence/display/c/ARR01-C.+Do+not+apply+the+sizeof+operator+to+a+pointer+when+taking+the+size+of+an+array)

Please append size of `hashedPassword` to function arguments (example: https://wandbox.org/permlink/c8UBvIYGHYjS1xMl).

Fixed example code:

```diff
int createOrganizationOnDb(pqxx::connection& c, pqxx::work& w, std::string id, std::string salt,
-                            uint8_t hashedPassword[], organization& newOrganization) {
+                            uint8_t hashedPassword[], std::size_t hashedPasswordLength, organization& newOrganization) {

    std::string insertQuery = "INSERT INTO hospitals (" 
                            "organization_id, " 
                            "organization_name, " 
                            "organization_address, "  
                            "organization_type, " 
                            "organization_rcNumber, " 
                            "organization_email, " 
                            "organization_country, " 
                            "organization_state, "
                            "organization_salt, " 
                            "organization_hashedPassword, "
                            "date_created, " 
                            "date_updated" 
    ") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW());";

    pqxx::result result;

    try {
+         std::string hashedPasswordString(reinterpret_cast<char *>(hashedPassword), hashedPasswordLength);
+
        c.prepare("create_organization", insertQuery);
        result = w.prepared("create_organization")(id)(newOrganization.name)
            (newOrganization.address)(newOrganization.type)(newOrganization.rcNumber)
            (newOrganization.email)(newOrganization.country)(newOrganization.state)
-             (salt)(hashedPassword).exec();
+             (salt)(hashedPasswordString.c_str()).exec();

        w.commit();
    } catch (const std::exception& e) {
        std::cerr << e.what() << "\n";
        return -1;
    }

    return result.size();
}
```

**Comment by BFamzz** [comment]
It worked perfectly. Thanks alot @tt4g for you help. I'm most grateful. I also learnt some new stuffs here. Thanks once again.

Here is a screenshot:

![image](https://user-images.githubusercontent.com/38426051/71518082-4f1f5f80-28b1-11ea-8de8-77820627f833.png)
