### ISSUE TITLE
The install target is broken

### ISSUE THREAD

**Issue by kpyrkosz** [jtv/libpqxx#244]
Hello. Installing the libraries built from source from the master branch (with `make install`) skips several headers (`config-internal-*.h`). Compiling an example application (the basic one from the main pqxx page) fails with error about missing header file.
```
 Building CXX object CMakeFiles/peiksiksy.dir/main.cpp.o
In file included from /usr/local/include/pqxx/connection:6,
                 from /usr/local/include/pqxx/pqxx:4,
                 from /tmp/example/main.cpp:2:
/usr/local/include/pqxx/connection.hxx:24:10: fatal error: pqxx/config-internal-libpq.h: No such file or directory
   24 | #include "pqxx/config-internal-libpq.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
 Tested on ubuntu and debian, the problem exists both with `./configure` and `cmake .` builds.
Running `ls -1 | wc -l` yields 72 in the build's `include/pqxx` and 59 in the `/usr/local/include/pqxx`.

**Comment by ThomasMcLeod** [comment]
I copied the missing headers from the installation into the include/pqxx directory. But this is not a great way to release code.

**Comment by jtv** [comment]
You shouldn't need the `config-internal-*.h` headers installed.  They are only needed when building libpqxx itself.

The snippet you paste looks as if you are indeed building libpqxx itself.  But you ran `configure` before doing that, right?

**Comment by jtv** [comment]
Ah, reading on, I see that you did.

Looks like I made a mistake: `connection.hxx` tries to include `config-internal-libpq.h` in order to figure out whether the available libpq version supports PQencryptPasswordConn.

**Comment by jtv** [comment]
And of course the build now breaks in CI — but not locally on my system.  Stand by.

**Comment by jtv** [comment]
Fixed now?

**Comment by ThomasMcLeod** [comment]
Yes. Thanks for the quick response.

**Comment by kpyrkosz** [comment]
Rebuilt from scratch, seems to work :)

**Comment by jtv** [comment]
Excellent.  Thanks for the report.
