### ISSUE TITLE
compiling 6.4 on ubuntu 18 aarch64/arm64 architecture

### ISSUE THREAD

**Issue by tavolodobela** [jtv/libpqxx#245]
Hello,

I try to compile libpqxx 6.4 on aarch64 ubuntu 18, and the configure script gets the following error. I have installed libpq-dev:arm64 package.

checking for /usr/include/postgresql/libpq-fe.h... yes
checking for ability to compile source files using libpq... yes
checking for PQexec in -lpq... no
configure: error: 
Did not find the PQexec() function in libpq.  This is the litmus test for a
working libpq installation.

How can I resolve the issue? Thank you for your help.

**Comment by jtv** [comment]
Have a look in `config.log` for the actual error message.  It'll be huge, and the part you're looking for will be a few pages up from the bottom.  Try searching for 'lpq'.

**Comment by jtv** [comment]
By the way, I develop mostly on Ubuntu systems so this absolutely _should_ just work.  Unless there's some kind of wild mismatch perhaps, such as using libpq-dev:amd64 on an x86 system.

**Comment by tavolodobela** [comment]
It says

"/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libpq.so when searching for -lpq"

I forgot to mention that it's actually an amd64 host, however, I try to do a crosscompile to aarch64/arm64. So -lpq is in place (ie. libpq-dev:arm64 and libpq5:arm64 are installed)

**Comment by jtv** [comment]
Then you'll need to customise your linker invocation.  You can do that on the command line when you invoke `configure`.

For example, if previously you just called "configure" but you need to invoke your cross compiler's linker, you might now do:

    ./configure LD=/usr/bin/aarch64-linux-gnu-ld

You can also pass your own linker options by setting `LDFLAGS` there.

**Comment by tavolodobela** [comment]
The CXX option also needed to make it work, ie. the following made it:

LD=/usr/bin/aarch64-linux-gnu-ld CXX=aarch64-linux-gnu-g++ ./configure --disable-documentation

Thank you for your help.

**Comment by jtv** [comment]
Always good to hear of someone cross-compiling — that's still a pretty strong test of a build setup!
