### ISSUE TITLE
How to make a shared lib?

### ISSUE THREAD

**Issue by tavolodobela** [jtv/libpqxx#246]
I'm still working with the crosscompile stuff. I'd like to build a shared lib, not the static one. I passed --enabled-shared to the configure arguments, but it still produces the static .a file. What am I doing wrong?

**Comment by jtv** [comment]
There are two separate options, `--enable-shared` and `--enable-static`.  The one is independent of the other.  So you should be getting a shared library _and_ a static library.

What happens if you pass `--enable-shared` and `--disable-static`?

**Comment by tavolodobela** [comment]
So I tried
_LD=/usr/bin/aarch64-linux-gnu-ld CXX=aarch64-linux-gnu-g++ ./configure --disable-documentation --enable-shared --disable-static && make_

and it produced only the static stuff in src/.libs:

_libpqxx.a  libpqxx.la  libpqxx.lai_

**Comment by jtv** [comment]
It does work on my Ubuntu 18.04 laptop with the native compiler though.  :/

Could it be a problem with your cross compiler?  Is there perhaps some architecture-specific option that you need to pass in `CXXFLAGS` and/or `LFDLAGS` in order to make shared libraries possible?

Also, did you "make clean" before re-configuring, so you don't accidentally preserve object files with non-position-independent code?

Separately from that, I _would_ suggest working with the static library, since the library doesn't really guarantee ABI stability.

**Comment by tavolodobela** [comment]
Yes, I did make clean before. I experimented with some configure options. When I added LD=/usr/bin/aarch64-linux-gnu-ld, then configure output says

_checking whether the aarch64-linux-gnu-g++ linker (**/usr/bin/aarch64-linux-gnu-ld -m elf_x86_64**) supports shared libraries... yes_

The highlighted combination looks odd to me. Anyway it creates only the static lib. However, if I don't specify LD=/usr/bin/aarch64-linux-gnu-ld, then configure output says:

_checking whether the aarch64-linux-gnu-g++ linker (**/usr/bin/ld -m elf_x86_64**) supports shared libraries... yes_

ld and elf_x86_64 makes more sense to me, however it's still odd with the aarch64 compiler. However in this case src/.libs has many more files: all the object files (.o), and the shared library:

_ls src/.libs/
array.o         connection.o       cursor.o         encodings.o     except.o  largeobject.o   libpqxx.a   libpqxx.lai  nontransaction.o  pipeline.o            result.o             row.o         statement_parameters.o  stream_base.o  stream_to.o       tablereader.o  tablewriter.o  transaction_base.o  version.o
binarystring.o  connection_base.o  dbtransaction.o  errorhandler.o  field.o   **libpqxx-6.4.so**  libpqxx.la  **libpqxx.so**   notification.o    prepared_statement.o  robusttransaction.o  sql_cursor.o  strconv.o               stream_from.o  subtransaction.o  tablestream.o  transaction.o  util.o_

**Comment by jtv** [comment]
Just to make sure I understand you correctly: So you're getting the shared library with the native build, but not with the cross compiler?

By the way, `ldd -v src/.libs/libpqxx.so` should tell you (among many, many other things) the architecture for which libpqxx.so has been built.

The GNU ld man page says the "-m" option is for "emulation," and another way of setting it is through the `LDEMULATION` enviornment variable.  Obviously the command-line option would override that, but maybe the configure script accepts LDEMULATION as a variable on the command ilne?

By the way, not sure if it matters, but `configure` accepts variable assignments _as part of its own command line:_

    ./configure CXXFLAGS=-O3

**Comment by tavolodobela** [comment]
Yes, you are right. Btw. I have a modified ldd command (ldd.aarch64) to support aarch64 binaries, and I believe that it produced a proper .so file:

ldd.aarch64 src/.libs/libpqxx.so 
	_libpq.so.5 => /usr/lib/aarch64-linux-gnu/libpq.so.5 (0x00000040008bb000)
	libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x00000040008f5000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000004000a84000)
	/lib/ld-linux-aarch64.so.1 (0x0000004000000000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000004000bcc000)
	libssl.so.1.0.0 => /lib/aarch64-linux-gnu/libssl.so.1.0.0 (0x0000004000bed000)
....
	libcrypt.so.1 => /lib/aarch64-linux-gnu/libcrypt.so.1 (0x00000040017a4000)
	libffi.so.6 => /usr/lib/aarch64-linux-gnu/libffi.so.6 (0x00000040017eb000)_

Anyway, again, I appreciate your help.

**Comment by jtv** [comment]
Great!  I'll close the ticket then, and if you run into more problems, we can start a new one.
