### ISSUE TITLE
Incorrect path in cmake configuration

### ISSUE THREAD

**Issue by KayEss** [jtv/libpqxx#252]
When the CMakeLists.txt file is used directly through `add_directory` then the path of the project will be different. This line https://github.com/jtv/libpqxx/blob/4519227d9329c8bd6e08be8b5db87f47f49fd711/src/CMakeLists.txt.template#L76 assumes that the `libpqxx.pc.in` is in the project route, which is only true if the cmake files are used stand alone.

I think the line should be:

    configure_file(${CMAKE_CURRENT_LIST_DIR}/../libpqxx.pc.in ${CMAKE_BINARY_DIR}/libpqxx.pc)

So it is relative to the CMakeLists.txt file the line appears in. I would submit a PR, but I don't know how to make the real cmake config from these templates to test it.

It is possible the same problem exists elsewhere too. The variable `CMAKE_SOURCE_DIR` is also used in `doc/CMakeLists.txt.template`, but as building docs now turned off by default it might be benign.

**Comment by jtv** [comment]
You re-generate a file from a template by running `template2mak.py` from the project's root:

    ./tools/template2mak.py foo.template foo

**Comment by JadeMatrix** [comment]
They should probably be `CMAKE_CURRENT_SOURCE_DIR` and `CMAKE_CURRENT_BINARY_DIR` to use the source/build directories for the current subdirectory.

**Comment by KayEss** [comment]
Actually, I find the way this all works confusing with so many names used interchangeably. The thing I can't work out at all is that the configure cmake scripts work differently to here.

I don't think I even understand the comment. What are installed configure scripts?

**Comment by jtv** [comment]
I just merged Kirit's patch, then re-opened the bug so we can continue the discussion.

**Comment by JadeMatrix** [comment]
@KayEss Installed configure scripts (e.g. `libpqxx-config.cmake`, `libpqxx-targets.cmake`) are what `FIND_PACKAGE` uses to set up imported targets in dependent builds.  Just a quick summary:
* `CMAKE_SOURCE_DIR` — Project source directory, the one containing the main `CMakeLists.txt`
* `CMAKE_CURRENT_SOURCE_DIR` — Source subdirectory (added with `ADD_SUBDIRECTORY()`); if the project has no subdirectories this will be the same as `CMAKE_SOURCE_DIR`
* `CMAKE_BINARY_DIR` — Project build directory; if the user is performing an in-source build (not recommended), this will be the same as `CMAKE_SOURCE_DIR`
* `CMAKE_CURRENT_BINARY_DIR` — The build directory equivalent for the current subdirectory
* `CMAKE_CURRENT_LIST_DIR` — The directory containing the current CMake script; if a project has no support scripts (i.e. only `CMakeLists.txt`s and no `*.cmake` files) this will always be one of the `CMAKE_CURRENT_SOURCE_DIR`s

So while it's possible for any combination of these to be the same value for a given build for a given project, they all have slightly different semantics in an effort to make build configs more flexible in the face of changes (user's different build toolchains, refactors, etc.)

**Comment by mkrupcale** [comment]
I specifically used `${CMAKE_SOURCE_DIR}/libpqxx.pc.in` since `libpqxx.pc.in` is in the root source directory, which has the exactly desired semantics[1]

> assumes that the libpqxx.pc.in is in the project route, which is only true if the cmake files are used stand alone.

I fail to see how this is an issue. `libpqxx.pc.in` is obviously always in the root source directory, regardless of whether CMake files are used or not. I don't know what you mean by "used stand alone", here.

I believe #253 should thus be reverted.

[1] https://cmake.org/cmake/help/latest/variable/CMAKE_SOURCE_DIR.html

**Comment by KayEss** [comment]
We're using libpqxx as a git submodule and use `add_directory()` in our cmake to add to our build.

From looking at cmake documentation I expect that https://cmake.org/cmake/help/v3.0/variable/PROJECT_SOURCE_DIR.html might be a better variable to use as that is explicitly the folder we're after.

**Comment by mkrupcale** [comment]
Thank you for clarifying what you meant by "stand-alone". Yes, I had not considered consuming `libpqxx` as a bundled dependency. In this case, yes, it looks like[1] `${PROJECT_SOURCE_DIR}` is the appropriate variable to use here. (Although I would also advise perhaps not bundling your dependencies in general and instead use the `find_package` mechanism for installed dependencies.)

Given this, I believe #253 should be reverted and instead use `${PROJECT_SOURCE_DIR}` in place of `${CMAKE_SOURCE_DIR}`.

[1] https://stackoverflow.com/a/32030551

**Comment by KayEss** [comment]
I can submit a new PR tomorrow with that change.

Using the bundled dependency makes it significantly easier to make sure that all build options are consistent and always gives us a single stage build (well, after the cmake bit anyway).

**Comment by JadeMatrix** [comment]
@mkrupcale yep exactly, and sorry I forgot about the `*_PROJECT_*` versions

**Comment by jtv** [comment]
Merged @KayEss' patch, with thanks.  All good now?

If so, I'm thinking I might just make 7.0 official at last.

**Comment by KayEss** [comment]
Can you hold off a little longer? I've been doing Mac builds to test our software and I'm running into a problem. I'm not sure yet where it's coming from. When do a build using libpqxx from a couple of weeks ago it works, but with yesterday's master it fails.

I've not had enough time to narrow this down yet, and it could well be that the problem is on our side. I'll do a git bisect to work out where the problem actually came from and then I'll try to work out what's wrong. I probably won't have enough time with the Mac to do all the builds until over the weekend though (the Mac is *very* slow to build things and there's going to be a lot of big builds to check things).

I'll check a stand-alone libpqxx build as well -- something I've not had time to do yet either.

**Comment by jtv** [comment]
Sure, I'll hold off.  Any other objections, anyone?

**Comment by mkrupcale** [comment]
I'd like to do some test builds on Fedora (i.e. RPM packaging) before the release, which I should be able to do either this week or weekend. Other than that, as long as there are no API/ABI changes you'd like to make, I don't see any reason not to do a release.

**Comment by jtv** [comment]
Perfect, thanks.

**Comment by KayEss** [comment]
Turns out all of the cmake problems I was seeing were due to other things and not related to libpqxx. All of our Mac builds and Linux builds work fine with all tests passing now.

**Comment by jtv** [comment]
Hurray!

**Comment by jtv** [comment]
Unless somebody objects, I'd like to close this bug now.

**Comment by mkrupcale** [comment]
Yeah, this bug should be resolved at this point. I've also done testing on my end regarding Fedora RPM packaging, and things look good there. I guess the only thing still to consider is whether it's worthwhile to move the `include/pqxx/doc` directory and remove some of the CMake templates as discussed in #260.

**Comment by jtv** [comment]
Great, thanks.  I don't feel any strong need to move the docs, and getting rid of the templates doesn't require a point-zero release.
