### ISSUE TITLE
Huge datasets?

### ISSUE THREAD

**Issue by Zeks** [jtv/libpqxx#254]
What happens if I select a dataset of, say, 4 million rows with .exec in pqxx? Will it return a scrollable cursor or will it try to load all 4m rows into the memory first before I can work with data?

**Comment by jtv** [comment]
Good question!  If you just execute the query using `transaction::exec()`, it will load the whole thing.

To avoid that, you can use a cursor or a table stream (replaced with the more modern `stream_from` in the upcoming 7.0 release).

**Comment by Zeks** [comment]
Is there any reason pqxx can't create a cursor automatically? say:

`
pqxx::cursor = pqxx::make_cursor("select * from somthing", 10); // 10 items a pop
for(auto item : cursor)
    //do work that will requery more as needed
`

sorry, if this sounds dumb, I am new both to pqxx and postgres

**Comment by Zeks** [comment]
Oh, I see there is this: https://stackoverflow.com/questions/16128142/how-to-use-pqxxstateless-cursor-class-from-libpqxx 

This could work I guess even if it's a bit cumbersome. Maybe official docs need clarification about scrolling fetches?

**Comment by jtv** [comment]
You may want to look at `icursorstream` as well.  It lets you fetch contiguous chunks of rows, of a pre-defined size.

Generating a name for the cursor seems like a good idea.  Not something we could do back when libpqxx started, because we'd have to generate multiple 32-bit random numbers to avoid clashes.  Hardware has changed since then.

The problem with RAII is that it leaves no room for the cursor to report an error by throwing an exception.  Can't throw from a destructor!

**Comment by jtv** [comment]
Oh, yes, you mentioned the more convenient loops.  I did build something like that once upon a time, but it wasn't good enough.  Far too ambitious...  Fully transparent caching random access.  Raised nasty lifetime issues.  So I ripped it out.  But a simpler, "loop over all rows in this cursor" should be viable.

**Comment by jtv** [comment]
@Zeks have a look at #274 — it's not merged yet but it's a brand new, much easier way of reading query results that I've been working since FOSDEM.

Let me know what you think, while I can still make changes.

**Comment by jtv** [comment]
@Zeks I'm pretty close to releasing 7.1 now, since nobody's found anything wrong with it in a while.  I'll close this ticket, but if you haven't already, please take a look at the change (#274) before I merge it.
