### ISSUE TITLE
What is the correct way to cancel a frozen query?

### ISSUE THREAD

**Issue by Zeks** [jtv/libpqxx#255]
There is cancel_query() method, but supposedly if a query is frozen, the thread is locked in the middle of its execution, so how do you call it then? From a different dedicated thread with a timer? 

Also, is there a way to set a timeout per query, or is passing connection_timeout variable to connection as a whole the only way?

**Comment by tt4g** [comment]
You can use `SET statement_timeout TO <ms>` and `RESET statement_timeout`: https://www.postgresql.org/docs/12/runtime-config-client.html

```sql
SET statement_timeout TO 1000;

SELECT * FROM large_table; --- TIMEOUT
RESET statement_timeout
```

**Comment by Zeks** [comment]
And on the matter of queries that are completely frozen? I don't quitre understand how cancel_query() is supposed to be used tbh when the using thread itself is locked up removing the opportunity to call it.

**Comment by jtv** [comment]
I must admit a lot of this stuff has slipped out of my memory over the years, but if you want to be able to continue doing stuff while your query is running, there's always the `pipeline` class.

**Comment by jtv** [comment]
(And yes, async at some point in the future — definitely want that...)

**Comment by Zeks** [comment]
I am just trying to find matching primitives here compared to ocilib. With ocilib, you also have a function that breaks the query, but it's explicitly stated it should be called in another thread iirc. Since libpqxx doesn't state anything like that and actively warns against multithreading otherwise I wanted to clarify how cancel_query() is supposed to be used.

**Comment by jtv** [comment]
Yeah, I think I was thinking of pipelines at the time.  `cancel_query` calls libpq's `PQcancel`, and it's just not clear to me what its concurrency guarantees are.

**Comment by jtv** [comment]
Actually, I'd like to take that back!  Turns out `PQcancel` is pretty safe, _provided_ you're not moving on to another query in the mean time.

**Comment by Zeks** [comment]
Nice, I will try to fiddle with it then while I am transitioning my stuff from sqlite to postgres

**Comment by jtv** [comment]
And I'll keep this bug open as a reminder to update that documentation.

(The other one stays open as a reminder for me to provide a simpler looping API for cursors — although that may be best for once we start using async C++.)

**Comment by Zeks** [comment]
Actually, speaking of documentation: are there any guidelines to preparing a lot of statements when connection is opened? Is it better to prepare them when they are about to be used or is it perfectly fine to do a wall of .prepare("nameX", "Select...") immediately after connection is initialized?

**Comment by jtv** [comment]
Well, that got a lot easier with the C++11 smart pointers.  No more self-rolled destructors to free resources.

**Comment by jtv** [comment]
No opinion on which is better, except that:
 1. You don't want to waste your time preparing lots of statements that you may end up not using.
 2. Prepared statements can actually perform _worse,_ since they have to be generic and so can't make use of statistics in optimising for the actual argument values that a given call passes.

If you're doing lots of inserts (a common use-case for prepared statements), consider using 7.0's `stream_to`.  It's faster to a ridiculous degree.

**Comment by Zeks** [comment]
Yes, I am already using stream_to, it's pretty nice and is definitely going to be used here a lot, but by pre-preparing I actually solve a different problem than optimisation (maybe in a wrong way). 

By pre-preparing everything I can essentially fully decouple query _purpose_ from actual query itself. This allows me to easily fill table of queries someplace centalized and manage them outside of the places they are used. Where palces that use them will just mention them by name, but won't know the actual details of the query.

Maybe a way to provide such query identification outside just prepare statements is needed then.

**Comment by jtv** [comment]
Definitely use whatever works best for you, but _parameterised_ statements might be another way of doing this.  You could isolate a statement's definition in a variable or function, and just pass it to `exec_params`.  Saves you having to prepare a statement.
