### ISSUE TITLE
zview.hxx

### ISSUE THREAD

**Issue by dmitryp-juganu** [jtv/libpqxx#261]
after make install, newly added zview not copied to system so result.hxx failed to find it.
`In file included from /usr/local/include/pqxx/binarystring.hxx:21:0,
                 from /usr/local/include/pqxx/binarystring:4,
                 from /usr/local/include/pqxx/pqxx:3,
                 from src/libjusql.cpp:3:
/usr/local/include/pqxx/result.hxx:26:10: fatal error: pqxx/zview.hxx: No such file or directory
 #include "pqxx/zview.hxx"
          ^~~~~~~~~~~~~~~~
compilation terminated.
`

`ls /usr/local/include/pqxx/
array                     cursor.hxx         internal            pipeline                robusttransaction.hxx  subtransaction        types.hxx
array.hxx                 dbtransaction      isolation           pipeline.hxx            row                    subtransaction.hxx    util
binarystring              dbtransaction.hxx  isolation.hxx       pqxx                    row.hxx                transaction           util.hxx
binarystring.hxx          errorhandler       largeobject         prepared_statement      strconv                transaction_base      version
compiler-public.hxx       errorhandler.hxx   largeobject.hxx     prepared_statement.hxx  strconv.hxx            transaction_base.hxx  version.hxx
config-public-compiler.h  except             nontransaction      result                  stream_from            transaction.hxx
connection                except.hxx         nontransaction.hxx  result.hxx              stream_from.hxx        transactor
connection.hxx            field              notification        result_iterator.hxx     stream_to              transactor.hxx
cursor                    field.hxx          notification.hxx    robusttransaction       stream_to.hxx          types
`

**Comment by dmitryp-juganu** [comment]
also another one: separated_list.hxx
`In file included from /usr/local/include/pqxx/stream_from:6:0,
                 from /usr/local/include/pqxx/pqxx:15,
                 from src/libjusql.cpp:3:
/usr/local/include/pqxx/stream_from.hxx:19:10: fatal error: pqxx/separated_list.hxx: No such file or directory
 #include "pqxx/separated_list.hxx"
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by jtv** [comment]
Oops!  Recent changes which I forgot to add to the right list.  Having some
trouble getting my laptop on the internet right now, but may be able to fix
it in an hour or so.

**Comment by jtv** [comment]
That took a bit longer than expected.  Ran into some old colleagues, had some catch-up to do,  But... problem solved now?
