### ISSUE TITLE
strconv: stream eofbit not reset before writing a float (PQXX_HAVE_CHARCONV_FLOAT not defined)

### ISSUE THREAD

**Issue by borischikunov** [jtv/libpqxx#262]
We are performing migration from old pqxx3 to pqxx6 and recently we got a couple of our tests broken. Namely, one of prepared statements threw an exception:
```
(pqxx::data_exception) ERROR:  invalid input syntax for type double precision: ""
```
After some debugging we discovered that `dumb_stringstream` has eofbit set before throwing the exception, so it was not reset properly before writing a value. Writing to `stringstream` without goodbit fails, so an empty string was sent to postgres instead of a properly converted number.

Consider the following test (though it uses gmock, it is quite clear):
```cpp
void test()
{
    pqxx::connection conn;

    // Simple - take a float number and return it as it is
    conn.prepare("stmt", "select cast($1 as float)");
    pqxx::work tr(conn);

    // This is an emphasis. We must use the same float type both for passing
    // the value to the statement and for retrieving result of the statement
    // execution. This is due to inner stringstream being instantiated as a
    // a parametrized thread-local singleton. It means, there are separate
    // stream<float>, stream<double>, stream<long double>, but every such
    // instance is a singleton. We should use only one of them.
    using F = float;

    // The value. An arbitrary one, in fact.
    const F x = 1;

    pqxx::result rows;

    // Nothing bad here, pass a float value to the prepared statement.
    // The stream is clear, so just fill it with the value and extract str().
    EXPECT_NO_THROW(rows = tr.exec_prepared("stmt", x));

    // This works properly, but as we parse the value from the stream, the
    // seeking cursor moves towards the EOF. When the inevitable EOF happens
    // 'eof' flag is set in the stream and 'good' flag is unset.
    EXPECT_NO_THROW(rows[0][0].as<F>());

    // The second try. Pass a float value again. The stream is not clean, so
    // we need to put an empty string into its buffer {stream.str("");}. This
    // resets the seeking cursor to 0. Then we will put the value using
    // operator<<().
    // ...
    // ...
    // OOPS. stream.str("") does not reset 'eof' flag and 'good' flag! We are
    // trying to read from EOF! This is no good.
    // Throws on unpatched pqxx v6.4.5
    EXPECT_NO_THROW(rows = tr.exec_prepared("stmt", x));

    // We won't get here without patch. The following statements are just for
    // demonstration of how prepared statements are intended to work. If we
    // simply just reset the stream flags properly, this would work fine.
    // The most obvious patch is just explicitly stream.seekg(0).
    EXPECT_NO_THROW(rows[0][0].as<F>());
    EXPECT_NO_THROW(rows = tr.exec_prepared("stmt", x));
    EXPECT_NO_THROW(rows[0][0].as<F>());
}
```
So far we used this simple and obvious patch to 6.4.5 tag to handle this problem:
```diff
--- a/src/strconv.cxx
+++ b/src/strconv.cxx
@@ -437,6 +437,7 @@ template<typename T> inline std::string to_string_fallback(T Obj)
 {
   thread_local dumb_stringstream<T> S;
   S.str("");
+  S.seekg(0); // reset eofbit
   S << Obj;
   return S.str();
 }
```
Note: `PQXX_HAVE_CHARCONV_FLOAT` is **not** defined in our case.

**Comment by jtv** [comment]
Excellent report, thanks!  Having test code is an enormous help.

Even with that though, I'm having trouble reproducing the problem.  :(  I tried gcc 7—9, clang 6—8, even libc++...  no dice.  What compiler were you using?  And was the problem fixed sometime between your libpqxx version and master?

**Comment by borischikunov** [comment]
Our apologies for false accusations!

The cause of the bug we encountered appeared to be our changes to libpqxx in order to make it compile under our toolchain. We have clang+libcxxrt and this renders us unable to use `thread_local`, so in our codebase `thread_local` was replaced by some kind of thread-local singleton, which is not quite the same, but everyone was confused.

I'm sorry for troubles we made.

There's nothing to do within the scope of this issue, so I'll close it if you don't mind.

Thank you for cooperation!

**Comment by jtv** [comment]
:-D  Just glad to hear it was resolved.

_But_ I wasn't aware of libcxxrt, and I'm intrigued.  If it's something more people need, I could add a configuration test to see whether the compiler supports `thread_local`, and if not, just use a local variable instead.  It'll be slower, but it might tide you over until `charconv` works for floating-point types.

**Comment by borischikunov** [comment]
Clang 7 perfectly supports `thread_local`, implementing it using [__cxa_thread_atexit](https://github.com/llvm-mirror/clang/blob/d4efffdb/lib/CodeGen/ItaniumCXXABI.cpp#L2258), but `__cxa_thread_atexit` is not provided by libcxxrt. `thread_local` non-PODs compile but raise linker errors.

**Comment by jtv** [comment]
In that case, I guess we could have a test programme create a `thread_local` non-POD object, and see if it'll link.  If it doesn't, I suppress the `thread_local` in the string conversion.  But would that solve the problem out of the box, or would we need a bunch more changes to make libpqxx work with libcxxrt?

**Comment by borischikunov** [comment]
AFAIK, it is the only issue we can't handle by configuration flags.

**Comment by jtv** [comment]
I just committed a change which _should_ work around the problem.  Could you try if it works on your setup, out of the box without the patch?
