### ISSUE TITLE
[CMake] pqxx 7.0: failed to create symbolic link 

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#265]
I try to build pqxx 7.0 with CMake but I get the following message before pqxx build step:

```plaintext
.NET Framework  Microsoft (R) Build Engine o[W 15.9.21+g9802d43bc3
Copyright (C) Microsoft Corporation.All rights reserved.

  Checking Build System
CUSTOMBUILD : CMake error : failed to create symbolic link 'pqxx.lib': operation not permitted [pqxx\src\library_symlink.vcxproj]
```

This is reporting CMake custom target `library_symlink` failure.

`library_symlink` is declare `add_custom_target(library_symlink ALL ...)` in `src/CMakeLists.txt` but this  target may be run before the build of the `pqxx` target is completed.

We need to add a CMake dependency between the two targets so that they run after the `pqxx` target is built.

**Comment by tt4g** [comment]
I noticed another probrem,
If Windows 10 developer mode is not enabled then `cmake -E create_symlink` is not working.

* [Windows 10 Creators Update: Symlinks without elevation \- gHacks Tech News](https://www.ghacks.net/2016/12/04/windows-10-creators-update-symlinks-without-elevation/)
* [cmake \-E create\_symlink command portability \(\#13162\) · Issues · CMake / CMake · GitLab](https://gitlab.kitware.com/cmake/cmake/issues/13162)

@jtv We may need the option of not creating symbolic links when building on Windows OS.

**Comment by jtv** [comment]
:-(

**Comment by tt4g** [comment]
I created pull request #267.

However, the problem of Windows 10 is not solved.

**Comment by tt4g** [comment]
I have tree workarounds for the Windows symbolic link creation problem.

1. Use `cmake -E copy` on Windows (see https://github.com/jtv/libpqxx/pull/267#issuecomment-580632338)

    This solution creates and installs a copy of the pqxx library with a version suffix when building for Windows.
    Some users may not like this solution because two identical binary files are generated.
    In addition, the name of the library without version suffix and the name of Windows debug information file (.pbd) do not match: [PDB\_NAME — CMake 3\.16\.3 Documentation](https://cmake.org/cmake/help/latest/prop_tgt/PDB_NAME.html)

2. Install only the pqxx library with the version suffix.

    This solution does not create a copy of pqxx with a version suffix or create a symbolic link when building for Windows.
    Only pqxx with suffix will be installed on the machine.
    As you know, when the library is updated, you need to change the link name.

3. No version suffix is ​​added.

    Don't add the version suffix when building for Windows.
    The version cannot be known from the library file name.

I prefer the third solution.
Most of the libraries I know have no version suffix.
Until now, Windows could not use symbolic links like UNIX-like OS.
I think it's customary to upgrade the library by placing different versions of the DLL with the same name in the executable folder to solve the DLL HELL.

@jtv Which solution do you want? I create a pull request with that solution.

**Comment by jtv** [comment]
Can we make it so that Windows gets a DLL _without_ a version number, but all other operating systems still get a versioned library plus a symlink?

Some of the considerations are unique to Windows.  There's less risk of confusion between library versions on Windows since you'd install the library locally with the application.  On other operating systems you'd install the library globally so we need to support multiple versions side by side.

**Comment by tt4g** [comment]
Sure, change only Windows. Other platforms can create symbolic link and build library with version suffixes.

**Comment by jtv** [comment]
How do we do that?  I'm not too experienced with CMake.

**Comment by tt4g** [comment]
I confirmed that CMake generator-expression works in `OUTPUT_NAME` property.

* [OUTPUT\_NAME — CMake 3\.16\.3 Documentation](https://cmake.org/cmake/help/v3.16/prop_tgt/OUTPUT_NAME.html)
* [cmake\-generator\-expressions\(7\) — CMake 3\.16\.3 Documentation](https://cmake.org/cmake/help/v3.16/manual/cmake-generator-expressions.7.html#manual:cmake-generator-expressions(7))

I create pull request: #268

**Comment by jtv** [comment]
This seems to work, so thanks again.  I'll close the issue, and go for a 7.0.1 release soon after I get back from the conference.  (Or if there's time, _at_ the conference. :) )
