### ISSUE TITLE
cmake: `include/pqxx/doc/README.md` should also be removed from CMake files

### ISSUE THREAD

**Issue by mkrupcale** [jtv/libpqxx#269]
Following the removal of `include/pqxx/doc/README.md` by `0f1d9559581672fbc16e72184d8bd1f471c2dfb2`, this must be removed from the CMake files as well, or CMake will fail to run. In particular, the reference is found in both `doc/CMakeLists.txt` and `include/CMakeLists.txt`. This can be fixed by re-generating from the template files:

```sh
./tools/template2mak.py ./doc/CMakeLists.txt.template ./doc/CMakeLists.txt
./tools/template2mak.py ./include/CMakeLists.txt.template ./include/CMakeLists.txt
```

Should I open a PR, or would you like to do it?

**Comment by jtv** [comment]
Go ahead - you deserve fair mention in the commit log and I'm attending a
conference with my other hand.  :)
