### ISSUE TITLE
configure error 'The Oid typedef in libpq has changed'

### ISSUE THREAD

**Issue by rocksolidwebdesign** [jtv/libpqxx#27]
building on Ubuntu 16.04 64-bit using libpqxx github master as of

https://github.com/jtv/libpqxx/commit/fb1cca3de23ce274262025995e18ba4a390239f3

I receive the following `./configure` error

```
checking that type of libpq's Oid is as expected... configure: error: 
The Oid typedef in libpq has changed.  Please notify the libpqxx authors of the
change!
```

however `./configure && make && make install` and linking my app works fine on my Ubuntu 16.04 system when I use svn trunk revision 1945

```
svn co svn://pqxx.org/libpqxx/trunk/
```

I have installed all the needed postgres dev libs as far as I know, I have installed:

```
sudo apt-get install postgresql-9.5 postgresql-server-dev-9.5 libpq5 libpq-dev
```

I checked `libpq-fe.h` from my `/usr/include` and saw that `Oid` is defined as `unsigned int`, which is the same as `libpqxx` defines it to be, so I don't know what's wrong.

I see in `git log` a commit as follows

```
commit 0bd0167304e3d970aa4ee50c5c95275baf96f3cc
Author: Jeroen Vermeulen <jtvjtv@gmail.com>
...skipping...
    Fixed spurious "Oid type has changed!" error in configure, thanks Kathy
```

but I don't see the message about fixing the spurious ID when I search actual github commits

on github, the commit message for 0bd0167304e3d970aa4ee50c5c95275baf96f3cc is "Use constexpr and noexcept."

I also notice that the `git log` message says `...skipping...`

the autoconf code for this check in the `./configure` script from svn vs github look nearly identical except some minor indentation and whitespace differences

I don't have libpqxx already installed anywhere on my system

was this spurious Oid error something that was fixed at some point? is it a regression? did the commit get skipped for some reason when moving from svn?

the most curious thing to me is why svn trunk does not have this error when the check code is the same

thanks!

**Comment by jtv** [comment]
I may have reproduced the error on one of my older machines.  I think it's something completely unrelated, and really unexpected: The compiler was not compiling C++11, but "old" C++, despite the configure.ac explicitly requesting C++11!

Just to check whether this was the problem, could you try setting `CXXFLAGS=-stdc++11` when running configure?

If so, installing the `autoconf-archive` package (on a Debian-flavoured system) solved the problem for me.  I was so happy with the new, lean configure script — but this makes me feel I should add a check for C++11 support after all.  :-(

**Comment by rocksolidwebdesign** [comment]
it appears https://github.com/jtv/libpqxx/commit/794534165cbfa676805834d41dbad8c55adef6a4 has fixed this issue, thanks

also, it appears there is no need for `autoconf-archive` or adding `CXXFLAGS` your commit appears to fix the issue entirely
