### ISSUE TITLE
lib: ABI break by a76f15a14432c528a67c1ae76931660f3d7bf3d1

### ISSUE THREAD

**Issue by mkrupcale** [jtv/libpqxx#272]
a76f15a14432c528a67c1ae76931660f3d7bf3d1 broke ABI due to the constructor signature change. Thus, this technically requires an ABI increment i.e. `7.0` -> `7.1`. Given that 7.0.0 was just released, it's unfortunate that this would have to be done, but the alternative would be that multiple incompatible `7.0` ABIs will exist. That is, `libpqxx` built from tag `7.0.0` will not be ABI compatible with that built from current `master` ("7.0.1"), but both will currently have ABI version `7.0`.

**Comment by jtv** [comment]
True!  Best I can do right now I think is release it quickly before anyone
relies on that ABI.  What did our mothers tell us about x.0 versions,
right?  :-)

**Comment by egorpugin** [comment]
Maybe it's possible to mark 7.0.0 tag on github as pre-release (orange label) and put a warning there.
Then mark 7.0.1 as Latest release (green), so users know what to use.

**Comment by jtv** [comment]
Oo!  I didn't know you could do that in github!  Wish I'd known.

**Comment by jtv** [comment]
I released the change yesterday, basically as a forgotten part of the 7.0 change.  Hope it's fast enough.  I don't think it'd affect many users...

**Comment by jtv** [comment]
No complaints yet.  :)  I'll close this bug.
