### ISSUE TITLE
stream_from to support 'start' and 'end'

### ISSUE THREAD

**Issue by omerbn** [jtv/libpqxx#275]
If it would be possible to specify 'start' and 'end' to stream_from, we'd be able to concurrently load huge data-sets from DB.

**Comment by jtv** [comment]
You mean an equivalent to LIMIT and OFFSET?  It should be possible in the latest version of that branch, which lets you `pqxx::transaction_base::stream("SELECT * FROM foo OFFSET n LIMIT m")`.

(Just don't let anyone insert or delete rows, or change them in ways that affect ordering, of course.  If you're doing this concurrently, there's no transaction isolation.)

**Comment by jtv** [comment]
Oh, and yes, my branch also adds that support to the `stream_from` class.  But the wrapper in `transaction_base` is probably easier to use.

**Comment by omerbn** [comment]
Cool. when will you merge the branch into master or into a release?

**Comment by jtv** [comment]
When I get enough feedback saying that it seems to work.  :)

I wrote this up while feeling unwell, and I noticed I was making a lot of mistakes in my typing, so I'm not completely confident that my design made sense.  Managing lifetimes was also slightly complicated; I basically had to make an "owning" and a "non-owning" version of the iteration class.  There may be a better way that I'm not seeing.

If you have time, please go through the merge request and criticise my code!

**Comment by jtv** [comment]
Okay, I'm working up a more extensive streaming API for 7.1.  You'll be able to stream regular results as well.

Mind if I close this bug?

**Comment by jtv** [comment]
Actually the new design is expanding to cover `pqxx::result` as well!  So, with my pending branch, you can iterate result objects in the same way, converting rows directly to tuples.  And I think I'll isolate a layer underneath that, where rows get the same conversion methods as fields — just to tuples instead of directly to values.
