### ISSUE TITLE
pqxx::usage_error Error message, don't know how to solve it

### ISSUE THREAD

**Issue by zhangwuqiao** [jtv/libpqxx#276]
I used an interface program developed by pqxx. I migrated it from MySQL version and only used it for a few days, but it kept crashing. I couldn't find the reason. Please help me to see what's the situation?

The error message is as follows:

terminate called after throwing an instance of 'pqxx::usage_error'
  what():  Started nontransaction while nontransaction still active

terminate called after throwing an instance of 'pqxx::usage_error'
  what():  Started nontransaction while transaction<READ COMMITTED> still active

source code:
#include "db.h"
#include "string.h"
#include "stdio.h"

#include "unistd.h"
#include <iostream>
#include <pqxx/pqxx>

using namespace pqxx;

DB::DB()
{
    IsEOF = false;
    connected = false;
    dbgout = true;
    pthread_mutex_init(&mutex, NULL);
}

DB::~DB()
{
}

int DB::open(char *host, char *port, char *user, char *psw, char *db)
{
  char connStr[512] = "";
  sprintf(connStr, "dbname=%s user=%s port=%s password=%s hostaddr=%s", db, user, port, psw, host);
  try{
    c = new pqxx::connection(connStr);
    if (c->is_open()) {
      c->set_client_encoding("GBK");
      // c->set_variable("default_transaction_isolation","'repeatable read'");
      connected = true;

      host_c = host;
      logf::printk(dbgout, "postgreSQL db is connected\n");
      return 0;
    } else {
      last_error = "Couldn't initialize postgreSQL db struct\n";
      logf::printk(dbgout, "%s", last_error.c_str());
      return -1;
    }
  }catch (const pqxx::pqxx_exception &e){
    // cerr << e.what() << std::endl;
    logf::printk(dbgout, "connected error:%s\n", e.base().what());
    return -1;
  }catch(...){
    log("connected faile");
    throw;
    return -1;
  }
}

int DB::query(string sql)
{
  logf::printk(dbgout, "query sql:%s\n", sql.c_str());
  nontransaction n(*c);
  result r;
  result::const_iterator row;
  MATRIX mx;
  int i;

  try{
    pthread_mutex_lock(&mutex);
    r = n.exec(sql.c_str());
    pthread_mutex_unlock(&mutex);
    if(r.size() > 0){
      m_matrix.clear();
      IsEOF = false;
      is = 0;
      
      for(auto row:r)
      {
        mx.value.clear();
        mx.count = r.size();
        for (auto field: row){
          logf::printk(dbgout, "row->field: %s\n",field.name());
          mx.name = field.name();
          m_matrix.insert(m_matrix.end(), mx);
        }
        i = 0;
        for (auto field: row){
          logf::printk(dbgout, "field->col: %s\n",field.is_null() ? "" : field.c_str());
          m_matrix.at(i).value.insert(m_matrix.at(i).value.end(),  field.is_null() ? "" : field.c_str());
          i++;
        }
      }
      return (int)m_matrix.at(0).value.size();
    }else{
      last_error = "empty";
      logf::printk(dbgout, "query result is empty\n");
      return 0;
    }
  }catch (const pqxx::pqxx_exception &e){
    // cerr << e.what() << std::endl;
    logf::printk(dbgout, "query sql:%s\n", sql.c_str());
    logf::printk(dbgout, "query error:%s\n", e.base().what());
    log(sql.c_str());
    pthread_mutex_unlock(&mutex);
    throw;
    return -1;
  }catch(...){
    log(sql.c_str());
    throw;
    return -1;
  }

}

void DB::lower(char *pdat, int ln)
{
	for(int i = 0; i < ln; i++)
	{
		*pdat = tolower(*pdat);
		pdat++;
	}
} 

int DB::exec(string sql)
{
  work w(*c);
  try{
    pthread_mutex_lock(&mutex);
    w.exec(sql.c_str());
    w.commit();
    pthread_mutex_unlock(&mutex);
    return 0;
  }catch (const pqxx::pqxx_exception &e){
    // cerr << e.what() << std::endl;
    logf::printk(dbgout, "query sql:%s\n", sql.c_str());
    logf::printk(dbgout, "query error:%s\n", e.base().what());
    log(sql.c_str());
    pthread_mutex_unlock(&mutex);
    w.abort();
    throw;
    return -1;
  }catch(...){
    log(sql.c_str());
    throw;
    return -1;
  }
}

void DB::close()
{
  c->disconnect();
}

void DB::log(const char *pdat)
{
  time_t tc;
  struct tm *p;
  string s = path_s();
  s += "/db.log";

  time(&tc);
  p = localtime(&tc);

  FILE *fp = fopen(s.c_str(), "a+");
  if(!fp) return;

  fprintf(fp, "[%04u-%02u-%02u %02u:%02u:%02u]\n%s\n",
          p->tm_year + 1900,
          p->tm_mon,
          p->tm_mday,
          p->tm_hour,
          p->tm_min,
          p->tm_sec,
          pdat);
  fclose(fp);
}

**Comment by tt4g** [comment]
As far as I see your code, `DB` is used in multi-thread application.
If so, don't share `pqxx::connection` between multi-thread.

https://github.com/jtv/libpqxx/blame/7662d181ac5890933146818709352e5722d36c16/include/pqxx/doc/thread-safety.md:

> Treat a connection, together with any and all objects related to it, as
a "world" of its own.  You should generally make sure that the same "world"
is never accessed by another thread while you're doing anything non-const
in there.

The `pqxx::usage_error` is probably caused by using `pqxx::nontransaction` with same `pqxx::connection`.
`pqxx::nontransction` cannot use `pqxx::connection` that is already start transaction.

You must create `pqxx::connection` for each thread.

**Comment by jtv** [comment]
Exactly.  You can't have two transactions open in the same connection at the same time.  I think the exception's error message says it pretty clearly!

Also, when you report a problem, try to minimise your example.  Otherwise it's just too much code for people to read.

**Comment by zhangwuqiao** [comment]
Thank you very much for your unselfish help. The problem has been solved. The core problem is that I seldom use C and C + +, so I need to study hard!

**Comment by jtv** [comment]
It's a tough language to get into!  The good news is that the language is still getting better.  Best of luck with your project.

I'll close the bug now, but feel free to file a new one if you run into any other problems.
