### ISSUE TITLE
Create and drop database

### ISSUE THREAD

**Issue by sawantshivaji1997** [jtv/libpqxx#277]
libpqxx version: 6.4
I am trying to create and drop database in the transaction, but getting the following error
`ERROR:  CREATE DATABASE cannot run inside a transaction block`
`ERROR:  DROP DATABASE cannot run inside a transaction block`

 Is there any way by which I can create and drop database?

**Comment by sawantshivaji1997** [comment]
Thanks, I got it from issue #102

**Comment by jtv** [comment]
Good news.
