### ISSUE TITLE
INSTALL-Windows.md doesn't seem to be up to date

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#278]
win32.mak, win32/MinGW.mak and libpqxx.sln appear in INSTALL-Windows.md, but these files have already been deleted.

**Comment by jtv** [comment]
Thanks!  That entire file is no longer relevant, so I'll delete it too.

And now that you bring it up, I'm beginning to wonder if there isn't a lot of duplication between `README.md` and `INSTALL`.

**Comment by jtv** [comment]
The changes are stuck in #274 until I merge it.  At that point, I intend to release it as 7.1.0.  I'm trying to keep the issue tracker clean, so if you don't mind I'll close the ticket now.  Thanks again for reporting it.
