### ISSUE TITLE
Janpnese error 

### ISSUE THREAD

**Issue by zhenghl1** [jtv/libpqxx#282]
when I compile this project In china, Using Visual 2019.The project has errors. for example
 D:\ormpp_deps\libpqxx_master\test\unit\test_stream_to.cxx(31,52): error C2001: 常量中有换行符 [D:\ormpp_deps\libpqxx_master\
test\unit\unit_runner.vcxproj]
I found this row  ownning janpese，I do not  know why this happened, so please confirm this.

**Comment by KayEss** [comment]
The error message looks to be in Chinese ("Line breaks in constants"), so I guess you mean the Japanese text in the source file.

Windows often has problems with UTF-8 text. It may be interpreting the source using a Chinese OEM page, which would corrupt the text. Can you make sure that the `/utf-8` flag is present in the build configuration? It would be helpful if you could tell us everything that MSVC tells you about this failure, including the compiler command line.

**Comment by jtv** [comment]
Thanks @KayEss.  We ought to replace that inline Japanese text with something which at least compiles as ASCII.

**Comment by jtv** [comment]
And @tt4g has already stepped in with a pull request.  Thanks!

Still need to address the client encoding issue, but hopefully not as urgent.

**Comment by jtv** [comment]
See #283 for the fix, or at least the major first step.  I'll release 7.0.3 soon.
