### ISSUE TITLE
Binary largeobject_streambuf does not retrieve whole file

### ISSUE THREAD

**Issue by tomlankhorst** [jtv/libpqxx#284]
I generate a random file and store that in a Postgres database with the `lo` facility. 
```
$ dd if=/dev/urandom of=blob1M bs=1M count=1
```
```
$ stat blob1M
  Size: 1048576         Blocks: 2048       IO Block: 4096   regular file
```

When I instantiate a `pqxx::largeobjectaccess` I am able to retrieve the whole contents: 
```cpp
auto out = std::ofstream("blob_copy", std::ios::binary);
auto in = pqxx::largeobjectaccess(tx, o, std::ios::in | std::ios::binary);

using Buffer = std::array<char, 1u << 10u>;
auto b = Buffer {};

for(;;){
  auto read_bytes = a.read(b.begin(), b.size());
  out.write(b.begin(), read_bytes);
  if(read_bytes < b.size()) break;
}
```
i.e., hashes of `blob1M` and `blob_copy` are the same

But when I try to copy over the same file through a `ilostream`, the operation seems to be aborted prematurely. 

```cpp
auto in = binary_ilostream<char>(tx, o);
auto out = std::ofstream("blob_copy", std::ios::binary);
out << in.rdbuf();
``` 

Now `blob_copy` contains a part of the source file, but not the full source file. If I regenerate a random file, the output length changes.

`binary_ilostream<...>` is like `basic_ilostream<...>` but with `largeobject_streambuf` access mode `std::ios::binary | std::ios::in`.

Am I doing something wrong or is the `largeobject_streambuf` failing at filling the buffer? 

At the end of the copy:
```
$ hexdump -s 18400 -n64 blob_copy
00047e0 4f9d 42b6 f470 a3b8 84f8 f406 118e 2b6e
00047f0 5409 be70 9179 6bcc 42a0 6ef0 ca52 0f61
0004800
``` 
Original:
``` 
$ hexdump -s 18400 -n64 blob1M
00047e0 4f9d 42b6 f470 a3b8 84f8 f406 118e 2b6e
00047f0 5409 be70 9179 6bcc 42a0 6ef0 ca52 0f61
0004800 cfff 96db fcfc 9c46 602b e30d 073c 1bbf
0004810 9de9 683d 85ac 7d08 21c0 4849 f8d0 3154
0004820
```

The missing value is `cfff 96db ....`

**Comment by jtv** [comment]
So the copy stops at the fist zero byte.  That's the typical problem in dealing with binary data.  Let me look a little deeper into  this...

**Comment by jtv** [comment]
Okay, this is going to take me a bit longer.  The C++ standard library's streams can get a little hairy, so in any case I would recommend that you use `pqxx::largeobjectaccess` instead, with its `read()` and `write()` methods.

**Comment by tomlankhorst** [comment]
Thanks for replying so quickly. As I see it, the last copied byte is `0x0f` and the first not-copied byte is `0xff`. How does that imply that the copy stops at the first zero byte? 
A number of zero bytes (0x00, '\0') is present in the copied file. 

Could it have to do with the fact that the `0xff` is at the boundary of a multiple of the buffer size? 
When I increase the buffer of largeobject_streambuf to 4K bytes, the file copy gets a bit further. 
But again, the copy stops when the first byte of a new buffer-read is `0xff`.

**Comment by tomlankhorst** [comment]
It's reproducible. 

Try to stream a file that has a `0xff` on position _N * buffersize_.

**Comment by KayEss** [comment]
`0xff` is what you get when you truncate `int{-1}` to `unsigned char` and -1 is the EOF value. It's hard to believe that's a coincidence.

**Comment by tomlankhorst** [comment]
largeobject.hxx:461
```
return ((res == 0) or (res == eof())) ? eof() : *eb;
```
`eb` is a `char*`, `*eb` is `-1` so it equals `eof()`, which is `-1` of type `int`.

**Comment by KayEss** [comment]
That design decision (which I think we inherit from C) is just an awful bit of trying to be too clever. Note that these functions return an `int` rather than the `char` you might expect: https://en.cppreference.com/w/cpp/io/c/fgetc Just awful :-(

**Comment by tomlankhorst** [comment]
So the idea is that `int {-1}` is the eof, i.e. `0xffffffff`, and that if `char{-1} = 0xff` occurs, this is returned as `0x000000ff = 255`?

**Comment by KayEss** [comment]
There's the added problem that you don't know if `char` is signed or not. I've just stayed away from anything to do with this stuff because it just looks designed to make you fail.

**Comment by jtv** [comment]
Thanks @KayEss — totally forgot about that dirty little detail!  Must have been about 15 years since I wrote that part of the code.

So what I guess I should do when reading a character is to cast it to `std::make_unsigned_t<char_type>` (probably breaking all the rules and technically incurring undefined behaviour), and _then_ promote it to `int_type`.

**Comment by jtv** [comment]
@tomlankhorst You're absolutely right of course.  I got blinded by that zero, and my wish to forget all about the streams API.

This looks worth a retroactive fix.  And perhaps I should just deprecated those streams entirely.

**Comment by tomlankhorst** [comment]
Seems like the `char_traits`' `to_char_type` and `to_int_type` serve this task. 

I would say the streams are nice to have as long as they are maintainable. 
For the time being, I will use `largeobjectaccess`.

**Comment by tomlankhorst** [comment]
This should work
