### ISSUE TITLE
Incorrect exception for parameter binding error

### ISSUE THREAD

**Issue by CelticMinstrel** [jtv/libpqxx#287]
If I pass the wrong number of parameters to a statement (via `exec_params`), it throws a `pqxx::broken_connection` with the message 'bind message supplies 2 parameters, but prepared statement "" requires 1'.

I would expect an error of this type to produce `pqxx::sql_error` instead.

**Comment by jtv** [comment]
Sounds like a reasonable expectation, yes!  I can reproduce the problem, but I'm still wondering what's going on.  My first guess is that this type of error breaks the entire connection somehow.

**Comment by jtv** [comment]
When I generate the problem, I get SQL error code 08P01: protocol_violation.  And in this case, the connection seems to recover from that just fine.  But in general, I don't think it'd be safe to ignore it and keep using the connection.

So overall it seems fair that you get a `broken_connection`, to indicate that you should stop using the connection.

Passing the wrong number of parameters to a statement would normally indicate a bug in the application, so hopefully this complicationwon't inconvenience too many people.

**Comment by CelticMinstrel** [comment]
The problem is that the `broken_connection` exception seems like it's supposed to be something you can recover from and try again (`pqxx::perform` itself makes that assumption), whereas `sql_error` is something you probably can't recover from. So by throwing `broken_connection` the application uselessly retries a query that's doomed to fail, and on top of that, doesn't provide as much error information as an `sql_error` (like, as far as I know there's no way to retrieve the actual query that failed if you only get a `broken_connection`, which is really helpful for locating the actual point of the error in the application).

**Comment by jtv** [comment]
I see the problem, but I don't think there's much I can do about it when the error code just says "protocol error."  At least you get a somewhat helpful error message.  If other people get the same mesage, hopefully the error message will take them to a discussion such as this one.

Hate to do it, but I'll close the bug.  If you have any good ideas about detecting this exact problem without risking confusion with different errors, feel free to file a new one.
