### ISSUE TITLE
Test failed: test_connection_string

### ISSUE THREAD

**Issue by supermitch** [jtv/libpqxx#288]
Can anyone help me figure out why this single test is failing? All other tests pass, for both test runners.

```
Running: test_connection_string
Test failure in C:\Users\<User Name>\source\libpqxx\test\unit\test_connection.cxx line 84:
Connection string specified user name, even when using default:
user=pqtester
password=pqtester
passfile="C:\Users\<User Name>\AppData\Roaming\postgresql\pgpass.conf"
dbname=pqxx-test
host=127.0.0.1
port=5437
tty=
options=
sslmode=disable
sslcompression=0
krbsrvname=postgres
target_session_attrs=any
(failed expression: connstr.find("user=" + std::string{c.username()}) == std::string::npos)
FAILED: test_connection_string
```

The DB user, in this case `pqtester` is actually set up for passwordless login, via `pg_hba.conf`. Adding or removing the `PGPASSWORD` env var makes no difference. Creating, or removing, the `pgpass.conf` file, in the location shown by the error message, similarly makes no difference.

I *can* log into psql without a password (`psql -d pqxx-test -U pqtester -p 5437`)

If I create a postgres user with my Windows `<User Name>`, the test _passes_. I guess that is what's meant by "using the default". Should I not be able to specify the `PGUSER`?

Note that even if I specify `PGUSER=<User Name>` it will still fail with the same error.

libpqxx version 7.0.2
Windows 10 Enterprise version 1809

**Comment by jtv** [comment]
The check verifies that when you open a connection with only default parametrs, and then ask the connection to list its parameters, it will leave out any parameters for which you're using the prevailing default.  Which is a nicety, but not essential.

In this case specifically, you appear to have set PGUSER, which I never do in my own tests, and the test expects the connection details not to show the "user" parameter.

And I now see what's wrong with my code: I end up comparing the parameter value to the _name_ of the environment variable, not its _value._

**Comment by jtv** [comment]
@supermitch does my latest commit fix the problem?
