### ISSUE TITLE
Build by Visual Studio 2019 completed but cannot be used.

### ISSUE THREAD

**Issue by pikapi12321** [jtv/libpqxx#289]
I need libpqxx on Windows and built it using cmake and VS, but I found only some text files in build/x64/Release folder after building.

**Comment by tt4g** [comment]
How did you build with CMake?

The following command works for me:

```bash
$ cd ${LIBPQXX_SOURCE}
$ mkdir build
$ cd build
$ cmake .. (some options)
$ cmake --build . --target all

**Comment by pikapi12321** [comment]
![image](https://user-images.githubusercontent.com/8817895/75423123-08191d80-5979-11ea-985d-ef2a43f05eb1.png)
Seems to be insufficient privileges.

**Comment by pikapi12321** [comment]
Solved with these steps:
1. Run cmd as administrator. 
2. cd the build directory.
3. Run "cmake --build . --target PACKAGE" and "cmake --build . --target INSTALL" respectively.

**Comment by jtv** [comment]
I imagine you could do the build as your regular user and just do the install as administrator.  The less we do with administrator privileges, the better.

**Comment by pikapi12321** [comment]
> I imagine you could do the build as your regular user and just do the install as administrator.  The less we do with administrator privileges, the better.

Um, you're right. Building target PACKAGE does not need administrator privileges. I simply didn't expect that building project INSTALL means installing directly.

**Comment by tt4g** [comment]
@jtv In most cases, `C:\Program Files` has no write permissions for non-administrator users.
However, this folder is used by Windows OS as a library installation destination, and CMake uses this folder as an installation destination by default.

[CMAKE\_INSTALL\_PREFIX — CMake 3\.16\.4 Documentation](https://cmake.org/cmake/help/v3.16/variable/CMAKE_INSTALL_PREFIX.html):

> If make install is invoked or INSTALL is built, this directory is prepended onto all install directories. This variable defaults to /usr/local on UNIX and c:/Program Files/${PROJECT_NAME} on Windows.

I think libpqxx is not a good solution to change where Windows is installed.
Users should make their own decisions to change the installation location or to run CMake install with administrator privileges.
