### ISSUE TITLE
pqxx::connection::connection_string() has several problems

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#290]
`pqxx::connection::connection_string()` access member variable of `PQconninfoOption‘ but this does not work as expected.

* `PQconninfoOption::envvar` is not value of environment variable.

  As far as I see, We expect `PQconninfoOption::envvar` to be the value of an environment variable. 
 https://github.com/jtv/libpqxx/blob/aa5620460dfc322d797b905997952bdc2c70f767/src/connection.cxx#L1076-L1077

  However, this is the name of an environment variable: https://github.com/postgres/postgres/blob/45b88269a353ad93744772791feb6d01bc7e1e42/src/interfaces/libpq/fe-connect.c#L170

* `PQconninfoOption::compiled` may have been assigned `nullptr`.

  Look at the postgresql source code.
  Most options are copied from `PQconninfoOptions` (static storage), but some `PQconninfoOption::compiled` are `nullptr`: https://github.com/postgres/postgres/blob/REL_12_2/src/interfaces/libpq/fe-connect.c#L189

  Here it is `NULL` checked.: https://github.com/postgres/postgres/blob/REL_12_2/src/interfaces/libpq/fe-connect.c#L5732

  If `nullptr` is passed to`std::strcmp()`, it will cause undefined behavior.

**Comment by tt4g** [comment]
Maybe deplicated: #288

**Comment by jtv** [comment]
@ttg I didn't mean to close this one, I just mentioned it in my commit message.

But while we're here..  Does my fix for #288 fix the nullptr problem?

**Comment by jtv** [comment]
Just found some time to read what you wrote properly, and I think the fix for #288 fixes it.

**Comment by tt4g** [comment]
Yes. this issue has been fixed.

However, when the `user` parameter is empty character (`'\0'`), the OS username is used as the `user` parameter, so the function may still not work as intended (this issue is not directly related to this issue).

the PostgreSQL document: [PostgreSQL: Documentation: 11: 34\.1\. Database Connection Control Functions](https://www.postgresql.org/docs/11/libpq-connect.html#LIBPQ-CONNECT-USER)

postgres source: https://github.com/postgres/postgres/blob/45b88269a353ad93744772791feb6d01bc7e1e42/src/interfaces/libpq/fe-connect.c#L1129-L1144


Perhaps this problem occurs when you pass the `user=''` parameter or specify `PGUSER=` as an environment variable.

**Comment by tt4g** [comment]
@jtv Would you edit`@ttg` to `@tt4g`? https://github.com/jtv/libpqxx/issues/290#issuecomment-591884924

**Comment by jtv** [comment]
Done.

**Comment by tt4g** [comment]
> However, when the user parameter is empty character ('\0'), the OS username is used as the user parameter, so the function may still not work as intended (this issue is not directly related to this issue).

The above comment is not a problem because `PQconninfoOption::var` returned by `PQconninfo()`  is copied from `PQConn::pguser`.

**Comment by jtv** [comment]
Thanks once again @tt4g!  Don't know how I'd keep up without your help.
