### ISSUE TITLE
7.0.3 build issues -> can't find libpq headers

### ISSUE THREAD

**Issue by code-mc** [jtv/libpqxx#291]
I've been trying to build the latest release of this library. Building the 6.4.6 version works without any issues, but trying to build the 7.0.3 version gives me the following error:

```
Can't find libpq-fe.h in .  Are you sure the libpq
headers are installed correctly?  They should be in the directory returned by
"pg_config --includedir" or "pkg-config libpq --cflags".
```

I've already checked and the referenced header is present in the include directory that is printed by the pg_config command. (otherwise the 6.4.6 version wouldn't build either anyways)

What I can see is that the 6.4.6 build output shows the following lines:

```
configure: using PostgreSQL headers at /usr/include
configure: using PostgreSQL libraries at /usr/lib
checking /usr/include/libpq-fe.h usability... yes
checking /usr/include/libpq-fe.h presence... yes
checking for /usr/include/libpq-fe.h... yes
```

While the 7.0.3 build output shows these as:

```
configure: using PostgreSQL headers at 
configure: using PostgreSQL libraries at 
checking /libpq-fe.h usability... no
checking /libpq-fe.h presence... no
checking for /libpq-fe.h... no
```

Indicating that the output of the pg_config command probably isn't captured correctly since 7.0.3?

**Comment by code-mc** [comment]
Build can be fixed by manually passing the --with-postgres-include=<dir> argument to the configure command. But still, there's likely something going wrong with the auto-detection of the include dirs.

**Comment by jtv** [comment]
Have a look at config.log.  There may be a helpful error in there.

**Comment by jtv** [comment]
Just remembered: there was a change that may be related to this.  I think
the build now relies entirely on pkg-config, and does not use `pg_config`.
I'm not at the computer now so I can't check, but perhaps you just need
pkg-config installed?

**Comment by jtv** [comment]
@code-mc any chance you could give me the exact output of `pg_config libpq --cflags` and `pkg-config libpq --cflags`?  There may be an issue with leading/trailing whitespace or something like that on your system.

Speaking of which, on what kind of system are you seeing this problem?  The `configure` script is mostly tested on recent current Ubuntu systems.

**Comment by code-mc** [comment]
I'm compiling on alpine linux (docker image), I'll see if I can do some tests later today

**Comment by jtv** [comment]
@code-mc it may help to read the output from `pg_config` and `pkg-config` as _binary,_ to reveal any whitespace or other invisible characters that the configure script may not be handling correctly.

**Comment by code-mc** [comment]
For `pg_config libpq --cflags` I'm getting:

```~ # pg_config libpq --cflags
pg_config: invalid argument: libpq
Try "pg_config --help" for more information.
```
For `pkg-config libpq --cflags` I'm getting empty output, but no error.

So both don't seem to know about libpq weirdly.

Although it is installed as this is the output from my /usr/lib directory:

```~ # ls -al /usr/lib/ | grep libpq
-rw-r--r--    1 root     root        334020 Feb 14 23:38 libpq.a
lrwxrwxrwx    1 root     root            13 Feb 29 17:25 libpq.so -> libpq.so.5.12
lrwxrwxrwx    1 root     root            13 Feb 29 17:25 libpq.so.5 -> libpq.so.5.12
-rwxr-xr-x    1 root     root        313200 Feb 14 23:38 libpq.so.5.12
```

**Comment by code-mc** [comment]
`pg_config` output in case that is useful:

```BINDIR = /usr/bin
DOCDIR = /usr/share/doc/postgresql
HTMLDIR = /usr/share/doc/postgresql
INCLUDEDIR = /usr/include
PKGINCLUDEDIR = /usr/include/postgresql
INCLUDEDIR-SERVER = /usr/include/postgresql/server
LIBDIR = /usr/lib
PKGLIBDIR = /usr/lib/postgresql
LOCALEDIR = /usr/share/locale
MANDIR = /usr/share/man
SHAREDIR = /usr/share/postgresql
SYSCONFDIR = /usr/etc/postgresql
PGXS = /usr/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--build=x86_64-alpine-linux-musl' '--host=x86_64-alpine-linux-musl' '--prefix=/usr' '--mandir=/usr/share/man' '--with-system-tzdata=/usr/share/zoneinfo' '--with-ldap' '--with-libedit-preferred' '--with-libxml' '--with-openssl' '--with-uuid=e2fs' '--disable-rpath' '--with-perl' '--with-python' '--with-tcl' 'build_alias=x86_64-alpine-linux-musl' 'host_alias=x86_64-alpine-linux-musl' 'CC=gcc' 'CFLAGS=-O2 -fomit-frame-pointer' 'LDFLAGS=-Wl,--as-needed' 'CPPFLAGS=-O2 -fomit-frame-pointer' 'CXX=g++' 'CXXFLAGS=-Os -fomit-frame-pointer' 'PYTHON=/usr/bin/python2'
CC = gcc
CPPFLAGS = -O2 -fomit-frame-pointer -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fomit-frame-pointer
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -L/lib -Wl,--as-needed
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxml2 -lssl -lcrypto -lz -ledit -lm 
VERSION = PostgreSQL 12.2```

**Comment by code-mc** [comment]
And a minimal docker file to reproduce the issue:

```# syntax=docker/dockerfile:experimental
FROM alpine:3.11 AS build_deps

# c++ dependencies

# RUN apk add --no-cache \
RUN apk add \
  cmake \
  g++ \
  git \
  make

ADD https://codeload.github.com/jtv/libpqxx/legacy.tar.gz/7.0.3 /usr/local/src/libpqxx.tar.gz

# pqxx deps

# RUN apk add --no-cache \
RUN apk add \
  postgresql-dev \
  autoconf \
  automake \
  bison \
  flex \
  libtool \
  openssl-dev \
  python3

WORKDIR /usr/local/src

RUN mkdir libpqxx \
  && tar xzf libpqxx.tar.gz -C libpqxx --strip-components 1 \
  && cd libpqxx \
  && ./configure --disable-documentation \
  && make -j4 \
  && make install
```

**Comment by code-mc** [comment]
Ok so apparently it works now using the docker file I've provided above, I'm really confused why it now suddenly does work though, I'll see if I can still reproduce it some other way.

**Comment by code-mc** [comment]
So it really seems to be an issue with pkg-config, if I run the --cflags command on my local ubuntu installation it correctly returns the -I/usr/include/postgresql flag. But on alpine it doesn't return anything.

So I also did a version check and on alpine it's running

```~ # pkg-config --version
1.6.3```

And on my local ubuntu install

```~$ pkg-config --version
0.29.1
```

**Comment by code-mc** [comment]
It's a pkg-config bug, I checked the libpq.pc file and the include path is listed there correctly:

```Name: libpq
Description: PostgreSQL libpq library
Url: http://www.postgresql.org/
Version: 12.2
Requires:
Requires.private:
Cflags: -I/usr/include
Libs: -L/usr/lib -lpq
Libs.private: -L/lib -lssl -lcrypto -lm -lldap_r
```
If I add a different include path it correctly returns that with --cflags but still without the /usr/include. When I add a `/` after /usr/include so `I/usr/include/` it does return that with --cflags. So this seems like a weird pkg-config bug

**Comment by jtv** [comment]
(I'm sorry — I think I should have said `pg_config --cflags`, without the `libpq` part)

**Comment by jtv** [comment]
I hate to work around bugs that should be easily fixed in other packages, but if worse comes to worst I guess I could add a check for `pkg-config` returning an empty string, and try to fall back to `pg_config`.

**Comment by code-mc** [comment]
```
~ # pg_config --cflags
-Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fomit-frame-pointer
```

**Comment by code-mc** [comment]
I'm honestly starting to think that because it's installed in /usr/include there is a general assumption that it will be in the default include path anyway. Can't really think of any other explanation at this point.

**Comment by jtv** [comment]
It does sound plausible, as bugs go.  May be worth reporting upstream.

And `pg_config` doesn't add an include path either.  Does it at least do the right thing?

**Comment by code-mc** [comment]
Yeah sorry, apparently the correct command for pg_config is `pg_config --includedir` which does give the expected ouput of `/usr/include` so that would work. (and is also why the previous version does compile)

**Comment by jtv** [comment]
Easiest thing we could possibly do is prefer the answer from `pg_config` over that of `pkg-config`.

**Comment by jtv** [comment]
Actually, it turns out to be awkward, because `pg_config` and `pkg-config` seem to have different ideas about how to include `libpq-fe.h`!

When I ask `pkg-config`, it gives me a path relative to which I can include `libpq-fe.h`.  Whereas `pg_config` gives me a path relative to which I can include `postgresql/libpq-fe.h`.

The configure script was entirely designed to work with `pg_config` output, and then later had `pkg-config` grafted onto it.  I'm tempted to go back to using just `pg_config` as the primary source of truth.

**Comment by jtv** [comment]
No, scratch that bit about `libpq-fe.h` versus `postgresql/libpq-fe.h`.  Both scripts support the former, which is the right one.  Noisy neighbours had me unable to think.

Even so, there's a difference: `pg_config` can give us either _compiler options or a directory._  Whereas `pkg-config` can give us only `a compiler option`.  I'd prefer to avoid parsing compiler options in search for that directory.  So I think I'll just prefer `pg_config`.

**Comment by jtv** [comment]
@code-mc I've tweaked this part of the configure script a bit, changed the design assumption, made it more tolerant of various unexpected situations, and had it prefer `pg_config` over `pkg-config` for the include path, at least for now.

(Eventually we'll want to be rid of that, since `pg_config` is deprecated.)

Could you try the latest `master`?

**Comment by code-mc** [comment]
@jtv Thanks! I'll give it a spin.

**Comment by code-mc** [comment]
Compiled without any issues!

**Comment by jtv** [comment]
Yay!  Thanks.
