### ISSUE TITLE
stream_to help

### ISSUE THREAD

**Issue by lefterise** [jtv/libpqxx#294]
I am not very clear as to what stream_to supports, the documentation doesn't mention much on this topic.

I would like to do multiple inserts in several tables.
-Can I have 2 streams open at the same time one for each table and write to either?
-What should i do if I want to use the column's DEFAULT value?
-Can I use it on a table that has a sequence as a key?

I would like to insert an employee along with his dependents. 
```

Create Table s.employees(
  id integer primary key not null default nextval('s.emploee_id_seq'),
  name character varying(64)
)

Create Table s.dependent(
  employee_id integer not null,
  dependent_id integer not null,
  name character varying(64),
  Constraint Foreign Key (employee_id) references s.employees(id)
)
```

However: employee.id is auto-generated. Using exec_prepared i can get the Id back, can I do something similar with stream_to?

**Comment by jtv** [comment]
You can have only 1 stream on 1 transaction _at any single time._  So if you want two simultaneous streams, you'll need 2 connections.

The only ways to make `stream_to` set a field to its default value are: (a) pass the default value yourself, or (b) don't include that column in your columns list.

You can use `stream_to` write a table which has a sequence as a key, but there are caveats.  Easiest case is where you're letting the sequence itself assign the values, the way it was meant to, and just not mention the key column in your columns list.  But if you do need to set your own values in the key column, you'll have to make sure that those values are unique.  Additionally you'll need to make sure that they remain in the future, which means setting the sequence to some value higher than any in the stream or in the table.  Probably the easiest way to do that is to query the `max(id)`.

**Comment by jtv** [comment]
By the way, I do understand that if it's not clear to you, the class probably needs more documentation.  So I'm keeping the bug open until I find time to do at least _something_ about that.

**Comment by shemake** [comment]
@jtv I have been writing some stream_to usage examples.  I am happy to share them, if that would help.

**Comment by jtv** [comment]
Thanks...  Is there anything particularly interesting that a simple example would demonstrate?  My feeling right now is that we mainly need text to explain the class, and clear promises of what you can expect from it.

Perhaps I should explain why there is basically no documentation for this.  Once upon a time, I had much more primitive stream classes.  I decided they were too messy and deprecated them.  But I was very conservative in removing deprecated features, so as a next "shot across the bow," I removed the documentation.  Later, @JadeMatrix contributed much better, more modern stream classes which solved the problems with the old ones.  These are the `stream_from` and `stream_to` classes you see now.  But they were based on my old classes, and those now set an extreme "low-documentation" standard for the new ones to follow!

High time I started fixing that.  I'll see what I can do right now.

**Comment by jtv** [comment]
By the way, it's really only the inline documentation that is missing.  There is documentation for `stream_to` on readthedocs:

https://libpqxx.readthedocs.io/en/stable/a01332.html

**Comment by jtv** [comment]
Okay, I've made some updates on my `transaction_stream_from` branch.  See #274.  It still needs some work, but unless some horrible problem pops up, it'll become 7.1.

**Comment by jtv** [comment]
Pretty close to being able to release 7.1 now, so I'll close this bug.  Thanks for highlighting a blind spot in the documentation.
