### ISSUE TITLE
esc for string_view

### ISSUE THREAD

**Issue by dpriedel** [jtv/libpqxx#295]
It would be nice if the esc() methods also took a std::string_view in addition to character arrays and strings.

I'm using 7.0.4.

Nice work on the update!

Thanks

**Comment by jtv** [comment]
Thanks!

Yes, it _would_ be nice if `esc()` could take a `string_view`.  Unfortunately, many underlying libpq functions take a C-style, zero-terminated string!

**Comment by jtv** [comment]
Actually, now that I'm actually looking...  You spotted an oversight, thanks!  This is one of the rare cases where we _can_ accept `string_view` for a libpq function.

**Comment by dpriedel** [comment]
Cool. Thanks! !!
