### ISSUE TITLE
Libpqxx version

### ISSUE THREAD

**Issue by jayraaj** [jtv/libpqxx#299]
Which libpqxx version we should use with the c++ compiler 8.2.0 on CentOS?

**Comment by tt4g** [comment]
I think libpqxx 7.0.5 works.

**Comment by jayraaj** [comment]
Do we need to build manually on CentOS or we can install using yum install?

**Comment by tt4g** [comment]
As far as I know, there is no libpqxx rpm package.

You can use autotools or CMake to build libpqxx.

**Comment by jtv** [comment]
This shows very current RPM packages: https://rpmfind.net/linux/rpm2html/search.php?query=libpqxx

They don't actually say "CentOS," but I believe packages for RHEL and CentOS (same major version) are generally interchangeable.  The same may be true for Fedora.

If you want to build from Git, just use the latest _released_ version — look for a release that's tagged in Git.

**Comment by jtv** [comment]
@jayraaj, does that answer your question?

**Comment by jayraaj** [comment]
Yes that helped me thank you. for the quick response.

**Comment by jtv** [comment]
Good to hear, thanks.  I'll close the ticket.
