### ISSUE TITLE
【libpgxx6.0】configure: error: PostgreSQL configuration script pg_config not found. 

### ISSUE THREAD

**Issue by kimi20071025** [jtv/libpqxx#300]
my pg is install at /usr/local. And I can find pg_config at /usr/local/pgsql/bin/. why the configure execute fail? The error detail is:
"PostgreSQL configuration script pg_config not found.  Make sure this is in your
command path before configuring.  Without it, the configure script has no way to
find the right location for the libpq library and its headers."

**Comment by jtv** [comment]
Looks like `/usr/local/pgsql/bin` is not in your `PATH`.  So when the configure script tries to run `pg_config`, the shell does not find the command.

Try doing this before running `configure`:

    PATH="$PATH:/usr/local/pgsql/bin"

Now you should be able to run `pg_config` in that shell.  And if you run `configure`, still in the same shell, it should be able to find the script.

Setting the `PATH` like this is not permanent.  It doesn't need to be; it's just to help `configure` find your postgres install location.

**Comment by kimi20071025** [comment]
> Looks like `/usr/local/pgsql/bin` is not in your `PATH`. So when the configure script tries to run `pg_config`, the shell does not find the command.
> 
> Try doing this before running `configure`:
> 
> ```
> PATH="$PATH:/usr/local/pgsql/bin"
> ```
> 
> Now you should be able to run `pg_config` in that shell. And if you run `configure`, still in the same shell, it should be able to find the script.
> 
> Setting the `PATH` like this is not permanent. It doesn't need to be; it's just to help `configure` find your postgres install location.

thank you.
