### ISSUE TITLE
string_traits' to_buf() for std::optional is not static

### ISSUE THREAD

**Issue by PetrSilar** [jtv/libpqxx#302]
Just a little typo I guess:
`include/pqxx/internal/conversions.hxx` line 205:
should be `static zview to_buf(`... 
The `static` is missing.

Regards Petr

**Comment by jtv** [comment]
You're right!  Fixed it just this week.  :-)

Thanks for reporting it though.  I wasn't really using `to_buf()`, but that just changed.
