### ISSUE TITLE
Wrong message on checking unique registration

### ISSUE THREAD

**Issue by xamix** [jtv/libpqxx#303]
Hello,

I'm running on latest realease 7.0.5
I think that the message exception while registering `non transaction` and `transaction` at the same time is wrong.

Take the following for example:

```
/* Create a transactional object. */
work W(C);
        
/* Create a non-transactional object. */
nontransaction N(C);
```

It lead to the following exception message:

```
Started nontransaction while nontransaction still active.
```

The message should be:

```
Started nontransaction while transaction still active.
```

I think it's because the following statement in function
[check_unique_registration](https://github.com/jtv/libpqxx/blob/e1a3cf23843ee3e0fbed489dc191ab34c0f6b7b7/src/util.cxx#L70) should use `old_ptr`  instead of `new_ptr`.

Can you confirm this?

**Comment by jtv** [comment]
Yup, you're right.  Should be fixed now.  Thanks!
