### ISSUE TITLE
if there has any API to do "pqxx::connection" object copy?

### ISSUE THREAD

**Issue by kimi20071025** [jtv/libpqxx#304]
I intend to keep a "pqxx::connection" object in private. So I can construct a "work" before I operate PG.
But I can not copy  the "pqxx::connection" object. Is there any API to do this. My code is below:

// PgxxApi.h
class PgxxApi
{
private:
	PgxxApi();

public:
	static PgxxApi& getInstance();
	bool initDbConn(const std::string &dbHostIP, const std::string &dbName, const std::string &userName = "postgres", const std::string &password = "postgres", const std::string &dbPort = "5432");

private:
	pqxx::connection conn;
};

// PgxxApi.cc
bool PgxxApi::initDbConn(const std::string &dbHostIP, const std::string &dbName, const std::string &userName, const std::string &password, const std::string &dbPort)
{
	string connInfo = "dbname=" + dbName + " user=" + userName + " password=" + password + " hostaddr=" + dbHostIP + " port" + dbPort;
	pqxx::connection conn(connInfo);
	this->conn = conn; //compile fail;
	if (conn.is_open())
	{
		cout<< "Opened database successfully: " << conn.dbname() <<endl;
	}
	else
	{
		cout<< "Can't open database" <<endl;
		return false;
	}
       return true
}

**Comment by KayEss** [comment]
The connection owns resources so cannot be copied, but can be moved. Try:

    this->conn = std::move(conn);

**Comment by kimi20071025** [comment]
> The connection owns resources so cannot be copied, but can be moved. Try:
> 
> ```
> this->conn = std::move(conn);
> ```

thank you, but is does not work. the "pqxx::connection_base& pqxx::connection_base::operator=(const pqxx::connection_base&)’ is private". The libpgxx version which I use is 6.0.0.

**Comment by KayEss** [comment]
Right... On the older version you may not have the move support needed. Given that it doesn't look like your design uses RAII (it should, everything will be simpler) you'll need to have an owning pointer to the connection instead:

Your declaration becomes:
    std::unique_ptr<pqxx::connection> conn;

And you can now make it with:
    this->conn = std::make_unique<pqxx::connection>(connInfo);

**Comment by jtv** [comment]
@kalman5 I agree with @KayEss.  Or once you upgrade to libpqxx 7, you'll also be able to do `this->conn = std::move(connection)`.

**Comment by kimi20071025** [comment]
Thank you @KayEss @jtv .
