### ISSUE TITLE
Two  minor bugs that show up in Visual Studio 2019

### ISSUE THREAD

**Issue by GordonLElliott** [jtv/libpqxx#307]
I left this in another issue, but realize it may need its own isssue as it is a general problem, just shows up when compiling specifically in latest Visual Studio 2019.

I had bugs appear when running the test suites, both runner and unit_runner. I just installed the new version of VS 2019 in last few days, so I suppose the latest. Compiling for 64 bit (-A flag) and 2019, etc., and test in debug mode. Neither the test suite, nor the actual library, would run correctly until I made 2 modifications. The problems should be explained in the comments.

Here is what I did to fix:

IN strconv.cxx, starting line 478:

case 'N':
case 'n':
    // Accept "NaN," "nan," etc.
    ok =    // [GLE] Note text[3] does not exist and triggers failure.
      (text.length() == 3 and (text[1] == 'A' or text[1] == 'a') and
       (text[2] == 'N' or text[2] == 'n') /*and (text[3] == '\0')*/);
IN test_main.hxx, starting line 134. Note that test_main.hxx does not appear in the project directory, is one directory level above runner.cxx in either of the 'runner' or 'unit_runner' sub-projects. It is included in the respective runner.cxx file, and I followed the link. This is a common file, and only needs to be changed once for both sub-projects:

// [GLE] add argc and make test_name null without an an argv[1].
int main(int argc, char const *argv[])
{
  char const *const test_name = argc>1? argv[1]: NULL;
THESE ARE THE ONLY MODIFICATIONS that I needed to successfully run the entire testing suite for pqxx with Visual Studio 2019.

**Comment by jtv** [comment]
Thanks for spotting these.  That first one was a change I should have made when converting to `std::string_view`.  It does mean that there's also probably a bug in the calling code, but it needed fixing nonetheless.  Fixing it right away.

I'm not so sure about the other one.  As far as I know, `argv[1]` is guaranteed to exist — though of course it'll be null if there are no arguments.

**Comment by jtv** [comment]
Ahhh, read the fine print again and now I see: it's not guaranteed that `argv[0]` points to a string!

**Comment by GordonLElliott** [comment]
More to the problem on strconv. Same sort of non-existent character references, but even more problems. See my whole fix  below.
Also the testing suite does not test the negative infinity or else should have shown a problem. Perhaps a test needs to be added for all the cases.

PS: I loaded the actual libpqxx.sln in the VS 2019, and set up debugging environment variables to point to my database, then ran the runner and unit_runner in the debugger. There it breaks with failures unless fixes on the prior issues. This are further issues that appear not to be tested:

strconv.cxx line 470:
// These are hard, and popular compilers do not yet implement std::from_chars.
template<typename T> inline T from_string_awful_float(std::string_view text)
{
  bool ok{false};
  T result;
  // [GLE] Original would fail with empty string as text[0] would not exist!
  if (text.size() > 0)
  {
    switch (text[0])
    {
    case 'N':
    case 'n':
      // Accept "NaN," "nan," etc.
      ok = // [GLE] Note text[3] does not exist and triggers failure.
        (text.length() == 3 and (text[1] == 'A' or text[1] == 'a') and
         (text[2] == 'N' or text[2] == 'n') /*and (text[3] == '\0')*/);
      result = std::numeric_limits<T>::quiet_NaN();
      break;

    case 'I':
    case 'i':
      ok = valid_infinity_string(text);
      result = std::numeric_limits<T>::infinity();
      break;

    default:
      // [GLE] Note string_view text is not a C character array!
      // The &text[1] is address of a single character, not the substring.
      //if (text[0] == '-' and valid_infinity_string(&text[1]))
      if (text.length() > 1 && text[0] == '-' 
          && valid_infinity_string(text.substr(1)))
      {
        ok = true;
        result = -std::numeric_limits<T>::infinity();
      }
      else
      { // [GLE] End changes except for final brace on the first if....
        if (have_thread_local)
        {
          thread_local dumb_stringstream<T> S;
          // Visual Studio 2017 seems to fail on repeated conversions if the
          // clear() is done before the seekg().  Still don't know why!  See
          // #124 and #125.
          S.seekg(0);
          S.clear();
          ok = from_dumb_stringstream(S, result, text);
        }
        else
        {
          dumb_stringstream<T> S;
          ok = from_dumb_stringstream(S, result, text);
        }
      }
      break;
    }
  }//[GLE]

  if (not ok)
    throw pqxx::conversion_error{
      "Could not convert string to numeric value: '" + std::string{text} +
      "'."};

  return result;
}
