### ISSUE TITLE
More to the problem on strconv. Shows up in VS 2019

### ISSUE THREAD

**Issue by GordonLElliott** [jtv/libpqxx#308]
More to the problem on strconv. Same sort of non-existent character references, but even more problems. See my whole fix  below.
Also the testing suite does not test the negative infinity or else should have shown a problem. Perhaps a test needs to be added for all the cases.

PS: I loaded the actual libpqxx.sln in the VS 2019, and set up debugging environment variables to point to my database, then ran the runner and unit_runner in the debugger. There it breaks with failures unless fixes on the prior issues. These here are further issues that appear not to be tested.
Furthermore I have only tested by running runner and unit_runner which pass, I have not set up specific cases for the positive and negative infinity so I think the code is good but not tested completely. I added an efficienty test for "-i" in "-infinity" so it won't run string checks on every negitive number. My original version could fail to set return value on empty string, fixed.

strconv.cxx line 470:

```
// These are hard, and popular compilers do not yet implement std::from_chars.
template<typename T> inline T from_string_awful_float(std::string_view text)
{
  bool ok{false};
  T result{std::numeric_limits<T>::quiet_NaN()};    // [GLE] Not set all branch
  // [GLE] Original would fail with empty string as text[0] would not exist!
  if (text.length() > 0)
  {
    switch (text[0])
    {
    case 'N':
    case 'n':
      // Accept "NaN," "nan," etc.
      ok = // [GLE] Note text[3] does not exist and triggers failure.
        (text.length() == 3 and (text[1] == 'A' or text[1] == 'a') and
         (text[2] == 'N' or text[2] == 'n') /*and (text[3] == '\0')*/);
      result = std::numeric_limits<T>::quiet_NaN();
      break;

    case 'I':
    case 'i':
      ok = valid_infinity_string(text);
      result = std::numeric_limits<T>::infinity();
      break;

    default:
      // [GLE] Note string_view text is not a C character array!
      // The &text[1] is address of a single character, not the substring.
      //if (text[0] == '-' and valid_infinity_string(&text[1]))
      if (text.length() > 1 and text[0] == '-' 
          and (text[1]=='i' or text[1]=='I')
          and valid_infinity_string(text.substr(1)))
      {
        ok = true;
        result = -std::numeric_limits<T>::infinity();
      }
      else
      {
        if (have_thread_local)
        {
          thread_local dumb_stringstream<T> S;
          // Visual Studio 2017 seems to fail on repeated conversions if the
          // clear() is done before the seekg().  Still don't know why!  See
          // #124 and #125.
          S.seekg(0);
          S.clear();
          ok = from_dumb_stringstream(S, result, text);
        }
        else
        {
          dumb_stringstream<T> S;
          ok = from_dumb_stringstream(S, result, text);
        }
      }
      break;
    }
  }

  if (not ok)
    throw pqxx::conversion_error{
      "Could not convert string to numeric value: '" + std::string{text} +
      "'."};

  return result;
}
```
_Originally posted by @GordonLElliott in https://github.com/jtv/libpqxx/issues/307#issuecomment-617926945_

**Comment by GordonLElliott** [comment]
Sorry I'll have to learn how to mark my code part...

**Comment by GordonLElliott** [comment]
An apologies for mixing .size() and .length() -- should have been uniform usage.

**Comment by jtv** [comment]
Thanks once again.  Really happy to have some critical inspection.

However I am _not_ seeing the code path where `result` gets used without being initialised!  Is it possible that the compiler is merely complaining because `from_dumb_stringstream` gets passed a reference to the default-constructed variable?  Surely there's nothing wrong with that?  If we have to initialise it just to silence that warning, it might be better to do it only in the `default` case, just before we check for `have_thread_local`.  Otherwise we might accidentally hide a genuine uninitialised use in some current or future iteration of the code.

**Comment by jtv** [comment]
The test suite does test negative infinity by the way, in `test/unit/test_float.cxx`, function `test_infinities`.

I doubt any amount of testing could have revealed the `std::string_view::operator[]` problem — hard to imagine why an implementation would not just return `*(data() + index)`.

Anyway, I've applied your fixes, and extended the testing in `test_float` a bit.

Unless you find anything else, I'd like to release 7.0.6 today, with 7.1 hopefully soon to follow.

**Comment by jtv** [comment]
@GordonLElliott I just released 7.0.6, with these fixes in.

**Comment by GordonLElliott** [comment]
> I doubt any amount of testing could have revealed the `std::string_view::operator[]` problem — hard to imagine why an implementation would not just return `*(data() + index)`.

I'm not sure how it worked (or didn't). The main problem is that these string views and other cases apparently don't have the null terminator in VS 2019. A function that returns just a character may return a temp variable with that value (in a new location), instead of acting like it is an array. To do what you say it would have to return a unit-length array of characters, not just a character. Then it compiles without complaining since either a single character address (or string) is a valid input--however if it happens to be missing the null terminator in some cases it would fail by converting a longer string with whatever garbage was next in memory, or possibly just one character. I will say that the original code didn't complain on the tests with only my first round of changes--these are just my being over careful.

--
 
Great, if it is in the tests then it must have worked, because all tests passed. (I have even tested my version with changing to Unicode character set and tests pass--which is my particular intended use with X64)
 
I'll download 7.0.6 and let you know if I have any problems. I will let you know immediately if I have problems but I may not happen fast enought with positive response, so just assume everything is OK. I've already beat upon 7.0.0 with my versions of the changes in only those two places.
 
Thanks for all your work!

**Comment by GordonLElliott** [comment]
Just loaded current, and it  looks like it will reference text[0] even if the position does not exist because it was passed an empty string. On my VS2016 debug, it will trap that case. (I have not set it up to test with empty string in that conversion.)
 
I recommend the if (text.size() > 0) test before using text[0]. (That was the case if failed would not set return value in my example.)

**Comment by jtv** [comment]
A quick note (before lunch) about the `string_view` matter...  Yes, you're absolutely right: there is no guarantee whatsoever that a `string_view` will have a terminating zero behind it.  (I even made my own variant called `pqxx::zview` to mark cases where we do have one.)  It's really nasty to test, because it's not even that easy to produce a test string without the terminating zero!

But do note that `std::string_view::operator[]` returns a _reference_ to the character.  So it can't just copy the character somewhere — it'd have to ensure that the reference remained valid, for as long as the underlying character array remains valid, even if the `string_view` itself no longer exists.  The only sensible way to do that is to just return a reference to the character in the original array.

**Comment by jtv** [comment]
I did add the check to stop `from_string_awful_float` from accessing `text[0] if it doesn't exist`, just slightly differently: I just immediately throw an exception at the top of the function when `text` is empty.  It keeps the rest of the code simple, and it lets me write a more helpful error message for that specific case.

Is that not what you're seeing in your downloaded 7.0.6?  Or are we talking about different functions?

**Comment by GordonLElliott** [comment]
I was either out of sinc, or else didn't read the code carefully. I agree it should work perfectly.

**Comment by jtv** [comment]
Good to hear.  And now I really ought to get 7.1 out...
