### ISSUE TITLE
[libpgxx 6.0.0] Executable program with libpgxx.a deploy to another environment

### ISSUE THREAD

**Issue by kimi20071025** [jtv/libpqxx#310]
I have already use the libpgxx.a to connect a local PG database, and it work very well. The PG database is installed at /usr/local/pgsql. 

I am confused when my executable program deploy to another environment, is the PG database need to be installed at the same path( /usr/local/pgsql.) at that environment?

**Comment by tt4g** [comment]
No. pqxx not dependent PostgreSQL server installed location.
pqxx communicates with PostgreSQL server via TCP socket.

**Comment by jtv** [comment]
Exactly what @tt4g says.  It doesn't matter where the database is installed.  It opens a _socket_ (it may be a Unix domain socket or a TCP socket), and you just tell libpqxx where that socket is.

**Comment by GordonLElliott** [comment]
There is a list of ways to specify the database. Unfortunately I am only familiar with these from Windows standpoint. But the idea is the same, environment variables can be usef for the parts of the specification, or the pqxx::connection arguments can specify or pass the specification from values  determined by the user's program.
 
THAT SAID, there is a distinct requirement when building an application. Even if a local copy of the PostgreSQL is not used either in the application or in the testing applications that come with the build source, a local copy (at least of the PostgreSQL library) need to be installed in the computer when building the pqxx library.

**Comment by jtv** [comment]
@kimi20071025 by the way, consider upgrading libpqxx.  We're currently in the 7.0 series, with 7.1 soon to be released.

**Comment by kimi20071025** [comment]
> Exactly what @tt4g says. It doesn't matter where the database is installed. It opens a _socket_ (it may be a Unix domain socket or a TCP socket), and you just tell libpqxx where that socket is.

Thanks for all. After reading the answers, I have a new quesiton that if PG database restart, can the client reconnect PG automaticly?

**Comment by tt4g** [comment]
> Thanks for all. After reading the answers, I have a new quesiton that if PG database restart, can the client reconnect PG automaticly?

No, the client library will not be able to notice the restart of the PostgreSQL server.
Take a look at #280.

As far as I know, the connection pool library provides the ability to handle server restarts.
These libraries detect broken connections by periodically running validation queries (e.g. `SELECT 1 as one`).
They will automatically discard the broken connection and reconnect when the connection is broken.

**Comment by jtv** [comment]
An application really should not expect a connection to last for very long time periods.  Always count on things breaking, for one reason or another!

**Comment by kimi20071025** [comment]
Thank you @jtv @tt4g . I still has some questions about the connection, it will be an new issuse.
