### ISSUE TITLE
stream_to & bytea column, special "long" insert causes exception

### ISSUE THREAD

**Issue by Laro88** [jtv/libpqxx#312]
I am using libpqxx using stream_to to insert some trace data, things are 99.some9's% fine however I do get an exception on a special packet / payload.
I have tried with and without null termination, tried tested with tuple using std::string and raw char* etc and my tricky payload is still teasing me. It is ~1700 chars

Is there anything in stream_to into a bytea that might be triggered by a specially crafted payload?
I am saving a lot of similar data without problems - it it one specific payload that is causing the exception. Replacing the Payload with a dummy payload then things are fine.
I have tested for extra nulls - data seems good. I have also tested without the null in the end.
![bytea stream_to problem payload](https://user-images.githubusercontent.com/12495700/81268288-0f7b3800-9048-11ea-92fa-749265138d98.png)

The libpxx is 6.4.5-2 from vcpkg - and everything else is running smoothly.

 
![bytea stream_to problem payload 2](https://user-images.githubusercontent.com/12495700/81269106-2706f080-9049-11ea-9bd0-77b678a9383c.png)

**Comment by tt4g** [comment]
I have never used `pqxx::stream_to` so please think my writing is a hint.
I think you should use `pqxx::binarystring` if tracing data is character like type.

https://github.com/jtv/libpqxx/blob/a6b1d60e74c1427c8ac2324b85cd4a0dc2068332/include/pqxx/binarystring.hxx#L29-L31

By the way, the behavior of `pqxx::stream_to` depends on the template parameter, so a snippet similar to the code in question is needed as a hint.

**Comment by jtv** [comment]
Actually, I'm not sure you _can_ safely insert binary data in a `stream_to`.  But if it's meant to be stored as text, it should have worked.

This code has changed a lot between libpqxx 6.x and 7.x.  So do check if 7.0 fixes the problem.

Another thing to do is _bisect_ the problem.  I don't think the length of the data should matter here.

So, see what happens if you send just the _first half_ of the data.  If that works, try the _second_ half.  Keep narrowing it down until you've got the exact part that causes the problem.  It'll make analysis a lot easier.

**Comment by jtv** [comment]
@Laro88, any news on this problem?  Is it gone in 7.x versions of libpqxx?

**Comment by jtv** [comment]
I had another look and I think, given a reasonably recent back-end, I can support `to_string` for `binarystring`.  But I don't know if it's going to work for `stream_to`.

Certainly you shouldn't just use a regular `std::string` as a representation for binary data.  There has to be something to tell libpqxx that it's binary data — that type information comes from your code, not from the server.

**Comment by jtv** [comment]
Just looked around some more and...  it _does_ look as if I can make `binarystring` work with `stream_to`!

**Comment by jtv** [comment]
With my latest commit, you can now insert a `binarystring` into a `BYTEA` field using `stream_to`.

**Comment by Laro88** [comment]
I will try to make use of it as soon as I find the time. Our project is not on latest major yet as we made some connection pooling ourselves to keep a pool of connections ready for use and this has to be updated as well.

**Comment by Laro88** [comment]
I am trying to test it as we speak, seems like vcpkg is not using version 7 yet so I have to rebuild everything manually. Work in progress.

**Comment by jtv** [comment]
Whoops.  Thanks for the update, looking forward to the results.

**Comment by Laro88** [comment]
I am sorry to say that although stream_to works, then it seems to be 5-7 times slower than a normal prepared statement.

Here is a gist of the test program that I made, anything I should do to tweak it further or that I might be abusing?
https://gist.github.com/Laro88/dc7a48556a60ec817808083eeebeb5fe

output from shell:
manual inserts #0 took: 5
manual inserts #1 took: 8
manual inserts #2 took: 9
manual inserts #3 took: 8
manual inserts #4 took: 8
stream inserts #0 took: 45
stream inserts #1 took: 45
stream inserts #2 took: 45
stream inserts #3 took: 44
stream inserts #4 took: 46

**Comment by jtv** [comment]
I'm sorry, I never saw any notification for your message.  If I'm reading your test code right, your timing loop using the prepared statement uses a single transaction.  The one using `stream_to` starts and commits a new transaction for every iteration.  That's going to add some overhead!

**Comment by jtv** [comment]
@Laro88 Actually, looking at your test code again, I see a lot of "shadowing" which means that the code is likely to hide mistakes where different connections or transactions have the same variable names.

So the very first things I would do are:
 * Enable compiler warnings.  (With gcc or clang I'd add `-Wshadow -Wall` to the command line).
 * Split `main()` up into smaller functions, in a way that reduces the room for misunderstandings.

**Comment by jtv** [comment]
I think it's time to retire this ticket, and then if there's still a problem, things are different enough to warrant a new ticket.
