### ISSUE TITLE
Can't stream_to on std::vector<std::string>

### ISSUE THREAD

**Issue by gelldur** [jtv/libpqxx#315]
Such code example doesn't compile

```
std::vector<std::string> fieldValues;
...
pqxx::stream_to stream{work, "xyz", columns};
	stream << fieldValues;
	stream.complete();
```
```
error: no matching function for call to 'separated_list'
  write_raw_line(separated_list("\t", t, internal::TypedCopyEscaper{}));```
```
Using libpqxx 7.0.6

---
Quick fix:

```
namespace pqxx
{

template <>
stream_to& stream_to::operator<<(std::vector<std::string> const& t)
{
	write_raw_line(separated_list("\t", t));
	return *this;
}

} // namespace pqxx
```

**Comment by jtv** [comment]
Could you give it a try with the `transaction_stream_from` branch?  I'm set to release it as 7.1.

**Comment by jtv** [comment]
Okay, that branch has been merged into `master` now, and we're officially at 7.1.0.

Does it work for you now?

**Comment by jtv** [comment]
@gelldur does it work for you now?

**Comment by jtv** [comment]
It seems to work in the other direction for other people, using `stream_from`.  I think we can close this issue now, but feel free to open a new one if there's still a problem.
