### ISSUE TITLE
Compile error "C2039: 'size_t': is not a member of 'std'" on MSVC when using pqxx

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#316]
When I try to build small application with pqxx version 7.1.0, I get a compile error "C2039: 'size_t': is not a member of 'std'" on MSVC.

This error occurred when I tried to build source code like the following

```cpp
#include "pqxx/pqxx"

#include <cstdlib>
#include <iostream>


int main()
{
    try {
        pqxx::connection conn;
        pqxx::work tx(conn);

        pqxx::row row = tx.exec1("SELECT 1");

        tx.commit();

        std::cout << row[0].as<int>() << "\n";
    } catch (const pqxx::broken_connection &ex) {
        std::cerr << "error: " << ex.what() << "\n";

        return 1;
    }

    return 0;
}
```

It seems that `#include <cstddef>` is missing in `include/pqxx/internal/encoding_group.hxx`.
Presumably, if the order of inclusion is lexicographic sorting, `pqxx/internal/encoding_group.hxx` will be included via `pqxx/array`. Maybe MSVC compiler can't find the definition of `std::size_t` at this time.

https://github.com/jtv/libpqxx/blob/b39ae42cfe71825d9641aad7549a4bb7e3b38db1/include/pqxx/array.hxx#L14-L18

https://github.com/jtv/libpqxx/blob/b39ae42cfe71825d9641aad7549a4bb7e3b38db1/include/pqxx/internal/encoding_group.hxx#L50-L51

**Comment by tt4g** [comment]
I'm not likely to be able to confirm today that this problem will be reproduced in gcc and clang.
However, without `#include <cstddef>`, the same problem should be possible.

**Comment by jtv** [comment]
Sometimes the compiler's standard headers include other standard headers as a side effect, making it easy to forget an include on one compiler and having it break on another compiler.
