### ISSUE TITLE
Access column result of array integer[]

### ISSUE THREAD

**Issue by cowabunga1** [jtv/libpqxx#32]
Hello.I have a problem to get the result of a column of integer[] (array of integers) as std::vector<std::int32_t>. Can I do this using libpqxx library methods?

**Comment by jtv** [comment]
No, unfortunately, libpqxx does not parse arrays yet!

**Comment by congleetea** [comment]
Is it supported now?

**Comment by jtv** [comment]
Yes! It's still a bit rough around the edges, but there is now a basic array parser.  Look for the `array_parser` class.

**Comment by congleetea** [comment]
thanks a lot.
