### ISSUE TITLE
New version install error

### ISSUE THREAD

**Issue by yifanguan** [jtv/libpqxx#322]
I installed version 7.0.7 on Ubuntu 16.04 successfully. 
Now, I want to switch to the newest version.

I git pull from the master branch just now.

Then, I ran 
(1)
**`make uninstall`**
(2)
**`./configure`**

checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++17 features by default... no
checking whether g++ supports C++17 features with -std=c++17... yes
configure: WARNING: C++17 is not yet standardized, so the checks may change in incompatible ways anytime
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of g++ -std=c++17... gcc3
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -std=c++17 accepts -g... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -std=c++17 -E
checking for ld used by g++ -std=c++17... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ -std=c++17 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ -std=c++17 option to produce PIC... -fPIC -DPIC
checking if g++ -std=c++17 PIC flag -fPIC -DPIC works... yes
checking if g++ -std=c++17 static flag -static works... yes
checking if g++ -std=c++17 supports -c -o file.o... yes
checking if g++ -std=c++17 supports -c -o file.o... (cached) yes
checking whether the g++ -std=c++17 linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether make sets $(MAKE)... (cached) yes
checking for mkdir... /bin/mkdir
checking for doxygen... no
checking for dot... no
checking for xmlto... /usr/bin/xmlto
checking whether to enable maintainer-specific portions of Makefiles... no
checking maintainer mode... 
checking audit... 
checking g++ visibility attribute... yes
checking g++ pure attribute... yes
checking __cxa_demangle... yes
checking strnlen_s... no
checking strnlen... yes
checking for C++17 charconv integer conversion... no
checking for C++17 charconv floating-point conversion... no
checking for full thread_local support... yes
checking for full std::variant support... yes
checking for poll()... yes
checking for pkg-config... /usr/bin/pkg-config
checking for pg_config... /usr/bin/pg_config
configure: finding PostgreSQL headers using -I/usr/include/postgresql
configure: using PostgreSQL libraries at /usr/lib/x86_64-linux-gnu
checking libpq-fe.h usability... yes
checking libpq-fe.h presence... yes
checking for libpq-fe.h... yes
checking for ability to compile source files using libpq... yes
checking for PQexec in -lpq... yes
checking for PQencryptPasswordConn... yes
checking that type of libpq's Oid is as expected... yes
checking whether make sets $(MAKE)... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/Makefile
config.status: creating doc/Makefile
config.status: creating doc/Doxyfile
config.status: creating src/Makefile
config.status: creating test/Makefile
config.status: creating tools/Makefile
config.status: creating include/Makefile
config.status: creating include/pqxx/Makefile
config.status: creating libpqxx.pc
config.status: creating include/pqxx/config.h
config.status: include/pqxx/config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing configitems commands
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-internal-autotools.h': no changes--skipping.
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-internal-compiler.h': no changes--skipping.
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-internal-libpq.h': no changes--skipping.
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-private-autotools.h': no changes--skipping.
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-private-compiler.h': no changes--skipping.
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-private-libpq.h': no changes--skipping.
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-public-autotools.h': no changes--skipping.
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-public-compiler.h': no changes--skipping.
Generating b'/home/irenelin/cprojects/roaring/libpqxx/include/pqxx/config-public-libpq.h': no changes--skipping.

(3)
**`make`**
Making all in include
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Making all in pqxx
make[2]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make  all-am
make[3]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[3]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[2]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[2]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Making all in src
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/src'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/src'
Making all in test
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/test'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/test'
Making all in tools
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/tools'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/tools'
Making all in config
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/config'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/config'
Making all in doc
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/doc'
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx'

(4)
**`make install`**
Making install in include
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Making install in pqxx
make[2]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[3]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[2]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[2]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
make[3]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include'
 /bin/mkdir -p '/usr/local/include/pqxx'
 /usr/bin/install -c -m 644  pqxx/pqxx pqxx/array pqxx/array.hxx pqxx/binarystring pqxx/binarystring.hxx pqxx/compiler-public.hxx pqxx/connection pqxx/connection.hxx pqxx/cursor pqxx/cursor.hxx pqxx/dbtransaction pqxx/dbtransaction.hxx pqxx/errorhandler pqxx/errorhandler.hxx pqxx/except pqxx/except.hxx pqxx/field pqxx/field.hxx pqxx/isolation pqxx/isolation.hxx pqxx/largeobject pqxx/largeobject.hxx pqxx/nontransaction pqxx/nontransaction.hxx pqxx/notification pqxx/notification.hxx pqxx/pipeline pqxx/pipeline.hxx pqxx/prepared_statement pqxx/prepared_statement.hxx pqxx/result pqxx/result.hxx pqxx/result_iterator.hxx pqxx/robusttransaction pqxx/robusttransaction.hxx pqxx/separated_list pqxx/separated_list.hxx pqxx/strconv pqxx/strconv.hxx pqxx/stream_from '/usr/local/include/pqxx'
 /bin/mkdir -p '/usr/local/include/pqxx/internal'
 /usr/bin/install -c -m 644  pqxx/internal/callgate.hxx pqxx/internal/compiler-internal-pre.hxx pqxx/internal/compiler-internal-post.hxx pqxx/internal/conversions.hxx pqxx/internal/encoding_group.hxx pqxx/internal/encodings.hxx pqxx/internal/ignore-deprecated-post.hxx pqxx/internal/ignore-deprecated-pre.hxx pqxx/internal/libpq-forward.hxx pqxx/internal/result_iter.hxx pqxx/internal/sql_cursor.hxx pqxx/internal/statement_parameters.hxx pqxx/internal/stream_iterator.hxx pqxx/internal/transaction_focus.hxx pqxx/internal/ignore-deprecated-pre.hxx pqxx/internal/ignore-deprecated-post.hxx '/usr/local/include/pqxx/internal'
/usr/bin/install: will not overwrite just-created '/usr/local/include/pqxx/internal/ignore-deprecated-pre.hxx' with 'pqxx/internal/ignore-deprecated-pre.hxx'
/usr/bin/install: will not overwrite just-created '/usr/local/include/pqxx/internal/ignore-deprecated-post.hxx' with 'pqxx/internal/ignore-deprecated-post.hxx'
Makefile:464: recipe for target 'install-nobase_includeHEADERS' failed
make[3]: *** [install-nobase_includeHEADERS] Error 1
make[3]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:680: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:519: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:638: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

**When I compiled my program, I got error below:**
In file included from /usr/local/include/pqxx/array.hxx:14:0,
                 from /usr/local/include/pqxx/array:4,
                 from /usr/local/include/pqxx/pqxx:2,
                 from Gendata.h:8,
                 from Gendata.cpp:1:
/usr/local/include/pqxx/compiler-public.hxx:16:10: fatal error: pqxx/config-public-compiler.h: No such file or directory
 #include "pqxx/config-public-compiler.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Thank you for help!

**Comment by yifanguan** [comment]
I downgrade my lib to version 7.0.7. Maybe I should be patient...

**Comment by jtv** [comment]
Ah, I see the mistake.  Does my latest commit fix the problem?  It's still a bit of a preliminary hack; I'll have to re-generate `configure` etc. on my other machine, but I don't have it available now.

First though: the `master` branch is for ongoing development.  If you want a proper _version_ of libpqxx, look at the tags.  The current version is 7.1.1.

**Comment by yifanguan** [comment]
I see. Thank you!!!

**Comment by jtv** [comment]
Does the fix work though?

**Comment by yifanguan** [comment]
Stay up late all night. I will give it a try once I return to my office.

**Comment by jtv** [comment]
Thanks for your efforts in giving me useful feedback!

**Comment by yifanguan** [comment]
Thank you for updating the README. 
I tried to install the version 7.1.1.

However, when I did make install. 
I got the error below:
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Making install in pqxx
make[2]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[3]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[2]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[2]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
make[3]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include'
 /bin/mkdir -p '/usr/local/include/pqxx'
 /usr/bin/install -c -m 644  pqxx/pqxx pqxx/array pqxx/array.hxx pqxx/binarystring pqxx/binarystring.hxx pqxx/compiler-public.hxx pqxx/connection pqxx/connection.hxx pqxx/cursor pqxx/cursor.hxx pqxx/dbtransaction pqxx/dbtransaction.hxx pqxx/errorhandler pqxx/errorhandler.hxx pqxx/except pqxx/except.hxx pqxx/field pqxx/field.hxx pqxx/isolation pqxx/isolation.hxx pqxx/largeobject pqxx/largeobject.hxx pqxx/nontransaction pqxx/nontransaction.hxx pqxx/notification pqxx/notification.hxx pqxx/pipeline pqxx/pipeline.hxx pqxx/prepared_statement pqxx/prepared_statement.hxx pqxx/result pqxx/result.hxx pqxx/result_iterator.hxx pqxx/robusttransaction pqxx/robusttransaction.hxx pqxx/separated_list pqxx/separated_list.hxx pqxx/strconv pqxx/strconv.hxx pqxx/stream_from '/usr/local/include/pqxx'
 /bin/mkdir -p '/usr/local/include/pqxx/internal'
 /usr/bin/install -c -m 644  pqxx/internal/callgate.hxx pqxx/internal/compiler-internal-pre.hxx pqxx/internal/compiler-internal-post.hxx pqxx/internal/conversions.hxx pqxx/internal/encoding_group.hxx pqxx/internal/encodings.hxx pqxx/internal/ignore-deprecated-post.hxx pqxx/internal/ignore-deprecated-pre.hxx pqxx/internal/libpq-forward.hxx pqxx/internal/result_iter.hxx pqxx/internal/sql_cursor.hxx pqxx/internal/statement_parameters.hxx pqxx/internal/stream_iterator.hxx pqxx/internal/transaction_focus.hxx pqxx/internal/ignore-deprecated-pre.hxx pqxx/internal/ignore-deprecated-post.hxx '/usr/local/include/pqxx/internal'
/usr/bin/install: will not overwrite just-created '/usr/local/include/pqxx/internal/ignore-deprecated-pre.hxx' with 'pqxx/internal/ignore-deprecated-pre.hxx'
/usr/bin/install: will not overwrite just-created '/usr/local/include/pqxx/internal/ignore-deprecated-post.hxx' with 'pqxx/internal/ignore-deprecated-post.hxx'
Makefile:464: recipe for target 'install-nobase_includeHEADERS' failed
make[3]: *** [install-nobase_includeHEADERS] Error 1
make[3]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:680: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:519: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:638: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
(base) irenelin@jserver1:~/cprojects/roaring/libpqxx$ sudo make install
Making install in include
make[1]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Making install in pqxx
make[2]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[3]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[2]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include/pqxx'
make[2]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
make[3]: Entering directory '/home/irenelin/cprojects/roaring/libpqxx/include'
make[3]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/include'
 /bin/mkdir -p '/usr/local/include/pqxx'
 /usr/bin/install -c -m 644  pqxx/pqxx pqxx/array pqxx/array.hxx pqxx/binarystring pqxx/binarystring.hxx pqxx/compiler-public.hxx pqxx/connection pqxx/connection.hxx pqxx/cursor pqxx/cursor.hxx pqxx/dbtransaction pqxx/dbtransaction.hxx pqxx/errorhandler pqxx/errorhandler.hxx pqxx/except pqxx/except.hxx pqxx/field pqxx/field.hxx pqxx/isolation pqxx/isolation.hxx pqxx/largeobject pqxx/largeobject.hxx pqxx/nontransaction pqxx/nontransaction.hxx pqxx/notification pqxx/notification.hxx pqxx/pipeline pqxx/pipeline.hxx pqxx/prepared_statement pqxx/prepared_statement.hxx pqxx/result pqxx/result.hxx pqxx/result_iterator.hxx pqxx/robusttransaction pqxx/robusttransaction.hxx pqxx/separated_list pqxx/separated_list.hxx pqxx/strconv pqxx/strconv.hxx pqxx/stream_from '/usr/local/include/pqxx'
 /bin/mkdir -p '/usr/local/include/pqxx/internal'
 /usr/bin/install -c -m 644  pqxx/internal/callgate.hxx pqxx/internal/compiler-internal-pre.hxx pqxx/internal/compiler-internal-post.hxx pqxx/internal/conversions.hxx pqxx/internal/encoding_group.hxx pqxx/internal/encodings.hxx pqxx/internal/ignore-deprecated-post.hxx pqxx/internal/ignore-deprecated-pre.hxx pqxx/internal/libpq-forward.hxx pqxx/internal/result_iter.hxx pqxx/internal/sql_cursor.hxx pqxx/internal/statement_parameters.hxx pqxx/internal/stream_iterator.hxx pqxx/internal/transaction_focus.hxx pqxx/internal/ignore-deprecated-pre.hxx pqxx/internal/ignore-deprecated-post.hxx '/usr/local/include/pqxx/internal'
/usr/bin/install: will not overwrite just-created '/usr/local/include/pqxx/internal/ignore-deprecated-pre.hxx' with 'pqxx/internal/ignore-deprecated-pre.hxx'
/usr/bin/install: will not overwrite just-created '/usr/local/include/pqxx/internal/ignore-deprecated-post.hxx' with 'pqxx/internal/ignore-deprecated-post.hxx'
Makefile:464: recipe for target 'install-nobase_includeHEADERS' failed
**make[3]: *** [install-nobase_includeHEADERS] Error 1**
make[3]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:680: recipe for target 'install-am' failed
**make[2]: *** [install-am] Error 2**
make[2]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:519: recipe for target 'install-recursive' failed
**make[1]: *** [install-recursive] Error 1**
make[1]: Leaving directory '/home/irenelin/cprojects/roaring/libpqxx/include'
Makefile:638: recipe for target 'install-recursive' failed
**make: *** [install-recursive] Error 1**

When I tried to compile my correct, I got the following error:
In file included from /usr/local/include/pqxx/strconv.hxx:329:0,
                 from /usr/local/include/pqxx/strconv:4,
                 from /usr/local/include/pqxx/internal/statement_parameters.hxx:26,
                 from /usr/local/include/pqxx/prepared_statement.hxx:17,
                 from /usr/local/include/pqxx/connection.hxx:27,
                 from /usr/local/include/pqxx/connection:6,
                 from /usr/local/include/pqxx/pqxx:4,
                 from Gendata.h:8,
                 from Gendata.cpp:1:
/usr/local/include/pqxx/internal/conversions.hxx:681:20: error: ‘strip_t’ does not name a type; did you mean ‘strspn’?
   using elt_type = strip_t<decltype(*std::declval<Container>().begin())>;
                    ^~~~~~~
                    strspn
/usr/local/include/pqxx/internal/conversions.hxx: In static member function ‘static char* pqxx::internal::array_string_traits<Container>::into_buf(char*, char*, const Container&)’:
/usr/local/include/pqxx/internal/conversions.hxx:631:39: error: ‘elt_type’ was not declared in this scope
       else if constexpr (is_sql_array<elt_type>)
                                       ^~~~~~~~
/usr/local/include/pqxx/internal/conversions.hxx:631:39: note: suggested alternative: ‘iswctype’
       else if constexpr (is_sql_array<elt_type>)
                                       ^~~~~~~~
                                       iswctype
/usr/local/include/pqxx/internal/conversions.hxx:634:38: error: type/value mismatch at argument 1 in template parameter list for ‘template<class TYPE> struct pqxx::string_traits’
         here = string_traits<elt_type>::into_buf(here, end, elt) - 1;
                                      ^
/usr/local/include/pqxx/internal/conversions.hxx:634:38: note:   expected a type, got ‘elt_type’
/usr/local/include/pqxx/internal/conversions.hxx:648:33: error: ‘elt_type’ was not declared in this scope
       *here++ = array_separator<elt_type>;
                                 ^~~~~~~~
/usr/local/include/pqxx/internal/conversions.hxx:648:33: note: suggested alternative: ‘iswctype’
       *here++ = array_separator<elt_type>;
                                 ^~~~~~~~
                                 iswctype
/usr/local/include/pqxx/internal/conversions.hxx: In static member function ‘static std::size_t pqxx::internal::array_string_traits<Container>::size_buffer(const Container&)’:
/usr/local/include/pqxx/internal/conversions.hxx:664:38: error: ‘elt_type’ was not declared in this scope
     using elt_traits = string_traits<elt_type>;
                                      ^~~~~~~~
/usr/local/include/pqxx/internal/conversions.hxx:664:38: note: suggested alternative: ‘iswctype’
     using elt_traits = string_traits<elt_type>;
                                      ^~~~~~~~
                                      iswctype
/usr/local/include/pqxx/internal/conversions.hxx:664:46: error: template argument 1 is invalid
     using elt_traits = string_traits<elt_type>;
                                              ^
/usr/local/include/pqxx/internal/conversions.hxx:667:38: error: ‘elt_type’ is not a type
                  [](std::size_t acc, elt_type const &elt) {
                                      ^~~~~~~~
/usr/local/include/pqxx/internal/conversions.hxx: In lambda function:
/usr/local/include/pqxx/internal/conversions.hxx:672:43: error: ‘elt_traits’ has not been declared
                                           elt_traits::size_buffer(elt) - 1};
                                           ^~~~~~~~~~
In file included from /usr/local/include/pqxx/result:12:0,
                 from /usr/local/include/pqxx/pqxx:13,
                 from Gendata.h:8,
                 from Gendata.cpp:1:
/usr/local/include/pqxx/internal/result_iter.hxx: In member function ‘void pqxx::internal::result_iter<TYPE>::read()’:
/usr/local/include/pqxx/internal/result_iter.hxx:64:36: error: ‘class pqxx::row’ has no member named ‘convert’
   void read() { (*m_home)[m_index].convert(m_value); }
                                    ^~~~~~~
In file included from /usr/local/include/pqxx/stream_from.hxx:23:0,
                 from /usr/local/include/pqxx/stream_from:6,
                 from /usr/local/include/pqxx/pqxx:15,
                 from Gendata.h:8,
                 from Gendata.cpp:1:
/usr/local/include/pqxx/separated_list.hxx: In function ‘std::__cxx11::string pqxx::separated_list(std::string_view, ITER, ITER, ACCESS)’:
/usr/local/include/pqxx/separated_list.hxx:50:20: error: ‘strip_t’ does not name a type; did you mean ‘strspn’?
   using elt_type = strip_t<decltype(access(begin))>;
                    ^~~~~~~
                    strspn
/usr/local/include/pqxx/separated_list.hxx:51:32: error: ‘elt_type’ was not declared in this scope
   using traits = string_traits<elt_type>;
                                ^~~~~~~~
/usr/local/include/pqxx/separated_list.hxx:51:32: note: suggested alternative: ‘iswctype’
   using traits = string_traits<elt_type>;
                                ^~~~~~~~
                                iswctype
/usr/local/include/pqxx/separated_list.hxx:51:40: error: template argument 1 is invalid
   using traits = string_traits<elt_type>;
                                        ^
/usr/local/include/pqxx/separated_list.hxx:55:15: error: ‘traits’ has not been declared
     budget += traits::size_buffer(access(cnt));
               ^~~~~~
/usr/local/include/pqxx/separated_list.hxx:63:10: error: ‘traits’ has not been declared
   here = traits::into_buf(here, stop, access(begin)) - 1;
          ^~~~~~
/usr/local/include/pqxx/separated_list.hxx:67:12: error: ‘traits’ has not been declared
     here = traits::into_buf(here, stop, access(begin)) - 1;
            ^~~~~~

I think I will stick to 7.0.7 version for now, and upgrade later.

**Comment by jtv** [comment]
Is it fixed in `master` though?

**Comment by yifanguan** [comment]
@jtv I will try it several days later. I'm focusing on other parts of my program now. I will post here once I give it a try.
Thanks!

**Comment by jtv** [comment]
@yifanguan any news?

**Comment by flokaz** [comment]
@jtv ran into same problem. tested master and works now. thanks

**Comment by yifanguan** [comment]
@flokaz @jtv Great! Then, I will close the issue. I have not given it a try yet because I'm focusing on other parts of my research application, and I will switch to the newest version later.
@jtv Again, thanks for your consistent quick replies.

**Comment by jtv** [comment]
I live for compliments.  :)
