### ISSUE TITLE
Website error - Complete Example syntax error

### ISSUE THREAD

**Issue by DanielDewberry** [jtv/libpqxx#323]
The [Complete Example ](http://www.pqxx.org/development/libpqxx/) is missing a closing `)` for `exec` .

This:

` pqxx::result r{txn.exec("SELECT name, salary FROM Employee"};`

should be:

` pqxx::result r{txn.exec("SELECT name, salary FROM Employee")};`

I couldn't find a website repo to clone and submit a patch so please accept this issue.

**Comment by jtv** [comment]
Fixed, thanks.

Same issue as #321 really.  Had to rewrite the site in a hurry recently.  As discussed in that ticket, once I've dealt with some other drama in my personal environment, I'm hoping to set up automatic syntax checking of code snippets in the documentation.  And I'll probably set up revision control for the website before that point as well.

**Comment by DanielDewberry** [comment]
@jtv thank you for addressing it and being so responsive.  Well done on a pleasant to use library.

**Comment by jtv** [comment]
@DanielDewberry that's very nice to hear.
