### ISSUE TITLE
"No object selected" when importing largeobject.

### ISSUE THREAD

**Issue by tomlankhorst** [jtv/libpqxx#324]
```cpp
pqxx::largeobject { tx, "/some/path" };
```
Throws:
```
 Could not import file '/some/path' to large object: No object selected
```
Thrown by:

https://github.com/jtv/libpqxx/blob/master/src/largeobject.cxx#L292
```cpp
std::string pqxx::largeobject::reason(connection const &c, int err) const
{
  if (err == ENOMEM)
    return "Out of memory";
  if (id() == oid_none)
    return "No object selected";
  return pqxx::internal::gate::const_connection_largeobject{c}.error_message();
}
```
Which ignores the actual `err` code when the `id()` is `oid_none`.

So, if `largeobject { tx, file_name }` construction, fails, the error will be 'No object selected', regardless of the underlying error number.

**Comment by jtv** [comment]
Can't argue with that!  Silly mistake.  Testing a fix now.

**Comment by tomlankhorst** [comment]
Perfect!
