### ISSUE TITLE
Trying to build a "Brief example" results in many errors - i.e. "pqxx::internal::enc_group' redeclared as different kind of entity"

### ISSUE THREAD

**Issue by mikebdp2** [jtv/libpqxx#325]
Good day! I've just built and installed the latest libpqxx 7.1.1 on CentOS 7 _(had to manually delete a couple of hxx lines at ./include/Makefiles, but you already know this)_. However, trying to build a "Brief example" from documentation here - http://pqxx.org/development/libpqxx/ - results in many errors, which didn't happen on Linux Mint 19.3 with libpqxx 6.2_6.2.5-1 installed. Please could you help? C++ toolchain is GNAT 2020 (c++ (GCC) 9.3.1), because a stock CentOS 7 toolchain is way too old.
```
c++ -o example example.cxx -lpqxx -lpq
In file included from /usr/include/pqxx/array.hxx:18,
                 from /usr/include/pqxx/array:4,
                 from /usr/include/pqxx/pqxx:2,
                 from example.cxx:2:
/usr/include/pqxx/internal/encodings.hxx:24:42: error: 'pqxx::internal::encoding_group pqxx::internal::enc_group' redeclared as different kind of entity
   24 | encoding_group enc_group(std::string_view);
      |                                          ^
/usr/include/pqxx/internal/encodings.hxx:23:16: note: previous declaration 'pqxx::internal::encoding_group pqxx::internal::enc_group(int)'
   23 | encoding_group enc_group(int /* libpq encoding ID */);
      |                ^~~~~~~~~
/usr/include/pqxx/internal/encodings.hxx:24:31: error: 'string_view' is not a member of 'std'
   24 | encoding_group enc_group(std::string_view);
      |                               ^~~~~~~~~~~
/usr/include/pqxx/internal/encodings.hxx:24:31: note: 'std::string_view' is only available from C++17 onwards
/usr/include/pqxx/internal/encodings.hxx:37:28: error: 'std::string_view' has not been declared
   37 |   encoding_group enc, std::string_view haystack, char needle,
      |                            ^~~~~~~~~~~
/usr/include/pqxx/internal/encodings.hxx:42:28: error: 'std::string_view' has not been declared
   42 |   encoding_group enc, std::string_view haystack, std::string_view needle,
      |                            ^~~~~~~~~~~
/usr/include/pqxx/internal/encodings.hxx:42:55: error: 'std::string_view' has not been declared
   42 |   encoding_group enc, std::string_view haystack, std::string_view needle,
      |                                                       ^~~~~~~~~~~
In file included from /usr/include/pqxx/array:4,
                 from /usr/include/pqxx/pqxx:2,
                 from example.cxx:2:
/usr/include/pqxx/array.hxx:66:21: error: expected ')' before 'input'
   66 |     std::string_view input,
      |                     ^~~~~~
      |                     )
/usr/include/pqxx/array.hxx:65:24: note: to match this '('
   65 |   explicit array_parser(
      |                        ^
/usr/include/pqxx/array.hxx:78:8: error: 'string_view' in namespace 'std' does not name a type
   78 |   std::string_view m_input;
      |        ^~~~~~~~~~~
/usr/include/pqxx/array.hxx:78:3: note: 'std::string_view' is only available from C++17 onwards
   78 |   std::string_view m_input;
      |   ^~~
In file included from /usr/include/pqxx/result.hxx:25,
                 from /usr/include/pqxx/binarystring.hxx:21,
                 from /usr/include/pqxx/binarystring:4,
                 from /usr/include/pqxx/pqxx:3,
                 from example.cxx:2:
/usr/include/pqxx/util.hxx: In function 'TO pqxx::check_cast(FROM, const char*)':
/usr/include/pqxx/util.hxx:54:22: error: 'is_arithmetic_v' is not a member of 'std'; did you mean 'is_arithmetic'?
   54 |   static_assert(std::is_arithmetic_v<FROM>);
      |                      ^~~~~~~~~~~~~~~
      |                      is_arithmetic
...
```

**Comment by tt4g** [comment]
I guess from the message "note: 'std::string_view' is only available from C++17 onwards" you did not specify `-std=c++17` (or `std=gnu++17`) for the compiler option.

pqxx 7.0.0 or above, C++17 is required.

https://github.com/jtv/libpqxx/releases/tag/7.0.0:

> C++17 is the minimum now

**Comment by mikebdp2** [comment]
@tt4g Thank you, `c++ -o example example.cxx -lpqxx -std=c++17` solves this problem and a program compiles successfully. Although, when I try to run it, I get
```
./example: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./example)
./example: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./example)
./example: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./example)
./example: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /lib/libpqxx-7.1.so)
./example: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /lib/libpqxx-7.1.so)
./example: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /lib/libpqxx-7.1.so)
```
but this is another problem

**Comment by tt4g** [comment]
It seems that the GCC library that the platform is referring to is different from the runtime referencing library.
Also, didn't you do the build with a different version of gcc? (or different `-std=c++<version>` specified?)

Look secion "Symbol versioning on the libstdc++.so binary." in this link: [ABI Policy and Guidelines](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)

> * GCC 5.1.0: GLIBCXX_3.4.21, CXXABI_1.3.9
> * GCC 9.1.0: GLIBCXX_3.4.26, CXXABI_1.3.12

`GLIBCXX_3.4.21` is gcc 5.1.0 library, `GLIBCXX_3.4.26` is gcc 9.1.0 library.

I'm not familiar with gcc, but I suspect you are trying to load a library that is not ABI compatible.

**Comment by KayEss** [comment]
As you built the tool chain yourself I expect this is because you haven't installed the libstdc++ libraries in the correct place, or it's because they are installed but not cached yet as you haven't run `ldconfig`.

You can probably get around this by using `LD_LIBRARY_PATH` with the folder to where the libraries are in your toolchain

**Comment by mikebdp2** [comment]
@KayEss I had to add these lines to ./.bashrc both to my user and root, then run ldconfig under root:
```
# GNAT
export PATH=/opt/GNAT/2020/bin:$PATH
export LD_LIBRARY_PATH=/opt/GNAT/2020/lib64/:/opt/GNAT/2020/lib/:$LD_LIBRARY_PATH
```
Now a program launches correctly, although couldn't connect to 127.0.0.1:5432 because I haven't configured a server yet. Thank you very much for your kind help! :smile:
