### ISSUE TITLE
Incomplete docs: make_dynamic_params

### ISSUE THREAD

**Issue by incapdns** [jtv/libpqxx#329]
c.prepare (id, query)
w.prepared (id);
How can I call make_dynamic_params to use dynamic parameters?
Note: I have not found any documentation regarding make_dynamic_params regarding its use.
The file "prepared-statement.md" only recommends using this function, but I don't know how to use it, would you have an example?

**Comment by incapdns** [comment]
Problem solved, after reading the documentation at https://libpqxx.readthedocs.io/en/stable/ I found the necessary information.

**Comment by jtv** [comment]
Glad to hear you found what you needed.  Documentation is still a bit messy; I think I ought to see if I can ditch the old tutorial written in docbook.  Simplify the build too.
