### ISSUE TITLE
Version bump request

### ISSUE THREAD

**Issue by scottfurry** [jtv/libpqxx#33]
I'm updating code that uses libpqxx but linking fails due to errors stating "undefined reference to `pqxx::internal::clear_result(pg_result const*)'".

The fix appears to have been addressed in response to issue #22. However, the change in git has not propagated out to the linux distributions. As linking inconsistency is a work stoppage problem for me (libpqxx is installed via package management software), would it be possible to tag either current HEAD or, at the least, commit 71ebccd629d4470d884c11eada36ac71e3ef1494 with an incremented version number. The newer version numbering should get package maintainers attention.

libpq ver 9.6.5 build date 2017Sep06
libpqxx ver 5.1.0 build date 2017Aug03

**Comment by jtv** [comment]
I believe I may have to start a 5.1 branch just so I can release this update...

In the meantime, does this problem happen when you link to libpqxx statically?  Or only when using the shared library?  I would normally recommend using the static library.

**Comment by jtv** [comment]
Okay, that's done.  Now you'll have to bug the maintainer of your package to release 5.1.1!

**Comment by scottfurry** [comment]
I'm using the package provided by distribution. Looks like the package provides a shared library.

**Comment by scottfurry** [comment]
I tested a locally packaged version of 5.1.1 today.
Linking was successful.
However, a review of the build log of my application indicated that pkg-config version number may not be correct. 

```pkg-config --modversion libpqxx
5.1.0
```

**Comment by jtv** [comment]
Oops — I bumped the version number but didn't re-generate the configure script etc. with the new version number in place.  Fixed now!

**Comment by jtv** [comment]
No, no, no, not fixed.  Git trouble.  Please bear with me while I sort out this mess.

**Comment by jtv** [comment]
Yes, that seems to do it!

**Comment by scottfurry** [comment]
fixed - thanks!!!
```
$ pkg-config --modversion libpqxx
5.1.1
```

**Comment by jtv** [comment]
👍
