### ISSUE TITLE
New SCRAM-SHA-256 seems not be recognized

### ISSUE THREAD

**Issue by dgasacas7** [jtv/libpqxx#333]
I tested the creation of new SCRAM-SHA-256 user password hash to replace an old one. For this, I used the pqxx::connection::encrypt_password().

1) The HASH seems well formed.
2) The SQL command (ALTER USER user PASSWORD '{HASH}') seems running well too. Also checked the view pg_catalog.pg_authid.

But I cannot connect anymore to PostgreSQL database neither with the old password nor the new one.

I compiled the current master developpement release 7.1.2 (12 June 2020) of libpqxx library and I'm working against the last stable PostgreSQL database (r12.3).

**Comment by tt4g** [comment]
Have you updated the configuration files and restarted postgres?

* [PostgreSQL: Documentation: 12: 20\.1\. The pg\_hba\.conf File](https://www.postgresql.org/docs/12/auth-pg-hba-conf.html)

  Example `pg_hba.conf`:

  ```conf
  # TYPE  DATABASE        USER            ADDRESS                 METHOD
  local   all             all                                     scram-sha-256
  host    all             all             127.0.0.1/32            scram-sha-256
  host    all             all             ::1/128                 scram-sha-256
  ```

* [PostgreSQL: Documentation: 12: 20\.5\. Password Authentication](https://www.postgresql.org/docs/12/auth-password.html)

  > set password_encryption = 'scram-sha-256' in postgresql.conf, make all users set new passwords, and change the authentication method specifications in pg_hba.conf to scram-sha-256.

  Don't forget set `password_encryption = 'scram-sha-256'` in `postgresql.conf`.

**Comment by dgasacas7** [comment]
@tt4g , Yes... Obviously...

1) pg_hba.conf contents

```
$ sudo cat /etc/postgresql/12/main/pg_hba.conf | egrep -v '^[[:space:]]*(#.*)?$' -
local   all             postgres                                peer
local   all             all                                     peer
hostssl all             all             127.0.0.1/32            scram-sha-256
hostssl all             all             ::1/128                 scram-sha-256
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
```

2) password_encryption variable

```
psql=# SHOW password_encryption ;
 password_encryption 
---------------------
 scram-sha-256
(1 row)
```

Meta command \password generates good scram-sha-256 hashes and lets to authenticate further...

**Comment by dgasacas7** [comment]
Here goes what I'm trying

```
#include <iostream>
#include <string>
#include <pqxx/pqxx>

int main (int, char *argv[])
{
	std::string old_passwd = "1234";
	std::string new_passwd = "4321";
	pqxx::connection c1 ("host=localhost dbname=**** user=**** password=" + old_passwd);
	pqxx::work w (c1);
	std::string new_hash = c1.encrypt_password (c1.username(), new_passwd.c_str(), "scram-sha-256");
	std::string sql1 = "ALTER USER " + std::string (c1.username()) + " PASSWORD " + w.quote (new_hash);
	w.exec0 (sql1);
	w.commit();
	c1.close();
	return 0;
}
```

**Comment by tt4g** [comment]
It appears that this is not allowed in the permissions settings.

Are you connecting from local using pqxx?
There does not appear to be a setting in the configuration that allows TCP connections.

Is it possible to temporarily change `pg_hba.conf` to allow connections from all hosts?

```diff
# TYPE  DATABASE        USER            ADDRESS                 METHOD
+ host   all             all             0.0.0.0/0               scram-sha-256
```

**Comment by dgasacas7** [comment]
I'm going to sum up all with 9 steps.

1. I made the changes suggested by @tt4g 
```
$ sudo cat /etc/postgresql/12/main/pg_hba.conf | egrep -v '^[[:space:]]*(#.*)?$' -
local   all             postgres                                peer
local   all             all                                     peer
hostssl all             all             0.0.0.0/0               scram-sha-256
hostssl all             all             ::1/128                 scram-sha-256
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
```
2. I logged in the PostgreSQL database from the client psql.
```
$ psql -h localhost 
Password for user ****: 
psql (12.3 (Debian 12.3-1.pgdg100+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.
```
3. I reloaded the configuration
```
psql=# SELECT pg_reload_conf();
 pg_reload_conf 
----------------
 t
(1 row)
```
4. I checked the password_encryption variable
```
psql=# SHOW password_encryption ;
 password_encryption 
---------------------
 scram-sha-256
(1 row)
```
5. I looked for the rolpassword value
```
psql=# \x
Expanded display is on.
psql=# SELECT rolpassword FROM pg_catalog.pg_authid where rolname=****;
-[ RECORD 1 ]--------------------------------------------------------------------------------------------------------------------------------------
rolpassword | SCRAM-SHA-256$4096:E3fTSNLGVENJzZo7ny8MtA==$Q4BQBn6LVMAcR/iU3U9mTa7XJ/fhbW1WfYYPmzTMI7c=:lUrruN5BOuh+gKAjmlIa3vJtinveie4QCey3+MdhOas=
```
6. From another BASH console from the SAME machine, I recompiled the C++/pqxx code.  
```
$ cat ./pg1.cc
#include <iostream>
#include <string>
#include <pqxx/pqxx>

int main (int, char *argv[])
{
	std::string old_passwd = "1234";
	std::string new_passwd = "4321";
	pqxx::connection c1 ("host=localhost dbname=**** user=**** password=" + old_passwd);
	pqxx::work w (c1);
	std::string new_hash = c1.encrypt_password (c1.username(), new_passwd.c_str(), "scram-sha-256");
	std::string sql1 = "ALTER USER " + std::string (c1.username()) + " PASSWORD " + w.quote (new_hash);
	w.exec0 (sql1);
	w.commit();
	c1.close();
	return 0;
}

$ g++ -std=c++17 pg1.cc -o pg1 -lpqxx -lpq
```
7. I run the code... and seems good fine. The code seems could connect successfully to the database, the password could be changed...
```
$ ./pg1
$ echo $?
0
```
8. I checked for the rolpassword value again... and has changed.
```
psql=# SELECT rolpassword FROM pg_catalog.pg_authid where rolname=****;
-[ RECORD 1 ]--------------------------------------------------------------------------------------------------------------------------------------
rolpassword | SCRAM-SHA-256$4096:Xq+LYZv02z0OZKK1cIYBmQ==$rmmvarbpOaCnZoCOZJ47pBiE1hLNcOw9mqhePN5xJuo=:2r1n/D1di3BzaCfOxCWB71XsrXz9x3YWTgV2OX4Y2kk=
```
9. Now, it's time to try logging in with password 4321 (the result with 1234 is the same error...)
```
$ psql -h localhost
Password for user ****: 
psql: error: could not connect to server: FATAL:  password authentication failed for user "****"
FATAL:  no pg_hba.conf entry for host "::1", user "****", database "****", SSL off
```
Notice that I hide some values with ****

**Comment by KayEss** [comment]
You still have a problem in your pg_hba.conf file. Note the error from Postgres:

    no pg_hba.conf entry for host "::1", user "****", database "****", SSL off

This is the IPv6 localhost address and you have SSL turned off. I don't recall enough about pg_hba.conf configuration now but you should either use SSL for the connection, or you need to add a line to allow non-SSL connections to use SCRAM.

**Comment by dgasacas7** [comment]
@KayEss , I made the changes in pg_hba.conf, I restarted the PostgreSQL database, I checked for the value of ssl variable...
```
$ sudo cat /etc/postgresql/12/main/pg_hba.conf | egrep -v '^[[:space:]]*(#.*)?$' -
local   all             postgres                                peer
local   all             all                                     peer
hostssl all             all             0.0.0.0/0               scram-sha-256
hostssl all             all             ::/0                    scram-sha-256
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5

$ sudo systemctl restart postgresql

$ psql -h localhost 
Password for user ****: 
psql (12.3 (Debian 12.3-1.pgdg100+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

psql=# SHOW ssl;
 ssl 
-----
 on
(1 row)
```
And after trying to reproduce the steps 7 and 9 (from my later post), the result is the same.

```
$ ./pg1 
$ psql -h localhost 
Password for user ****: 
psql: error: could not connect to server: FATAL:  password authentication failed for user "****"
FATAL:  no pg_hba.conf entry for host "::1", user "****", database "****", SSL off
```
Notice that when I set the password with \password (psql metacommand), I can connect without any problem using $ psql -h localhost

**Comment by KayEss** [comment]
I don't know what's changing between the first and second invocation of `psql` to alter the TLS status of the connection. The first time this line tells you about the encryption:

    SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)

On the second connection attempt that line doesn't come up , but nor does the `psql (12.3 (Debian 12.3-1.pgdg100+1))` line.

I don't see any changes in your pg_hba.conf that would affect non-TLS connections. 

What I think is happening is that the SCRAM authentication is done early on over plain TCP and after that succeeds the connection is switched to TLS, which is what happens the first time. In the second connection attempt maybe the connection isn't getting as far as the TLS switch.

I don't know why this difference is happening. I would try to change the password using the `ALTER USER` command through psql and verify that it does in fact work as you expect.

**Comment by dgasacas7** [comment]
@KayEss said,

> I would try to change the password using the ALTER USER command through psql and verify that it does in fact work as you expect.

```
$ psql -h localhost
Password for user ****: 
psql (12.3 (Debian 12.3-1.pgdg100+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

psql=# ALTER USER **** PASSWORD '4321';
ALTER ROLE
psql=# \q
$ psql -h localhost
Password for user ****: 
psql (12.3 (Debian 12.3-1.pgdg100+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

psql=# 
```

**Comment by tt4g** [comment]
pqxx can not connect if remove 

Did you remove `"host all all 0.0.0.0/0 scram-sha-256only"` from `pg_hba.conf` and pqxx can no longer connect to the database?
If so, pq may not be trying to make an SSL connection.

Try append `sslmode=prefer` to connection string.

```diff
int main (int, char *argv[])
{
	std::string old_passwd = "1234";
	std::string new_passwd = "4321";
-	pqxx::connection c1 ("host=localhost dbname=**** user=**** password=" + old_passwd);
+	pqxx::connection c1 ("sslmode=prefer host=localhost dbname=**** user=**** password=" + old_passwd);
	pqxx::work w (c1);
	std::string new_hash = c1.encrypt_password (c1.username(), new_passwd.c_str(), "scram-sha-256");
	std::string sql1 = "ALTER USER " + std::string (c1.username()) + " PASSWORD " + w.quote (new_hash);
	w.exec0 (sql1);
	w.commit();
	c1.close();
	return 0;
}
```

Although `sslmode=prefer` is the default, it may have been overridden by the environment variable `PGSSLMODE`.

* https://www.postgresql.org/docs/12/libpq-envars.html
* https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-CONNECT-SSLMODE

**Comment by dgasacas7** [comment]
@tt4g For TCP connections I use "hostssl" instead of "host". I don't know if it's matters but as far as I know the "host" value is just for plain text connections.
```
hostssl all             all             0.0.0.0/0               scram-sha-256
hostssl all             all             ::/0                    scram-sha-256
```
(If needed, you could find all my pg_hba.conf in a latter post).

Following your suggestion I modified the code as
`pqxx::connection c ("sslmode=prefer host=localhost dbname=david user=david password=" + old_passwd);`

I recompiled the whole code and nothing changes after running it, the result is the same...
```
$ ./pg1 
$ psql -h localhost 
Password for user ****: 
psql: error: could not connect to server: FATAL:  password authentication failed for user "****"
FATAL:  no pg_hba.conf entry for host "::1", user "****", database "****", SSL off
```

**Comment by tt4g** [comment]
Hmmm. I'm weirded out by the fact that I can connect with "host", but not with "hostssl". 

I checked various documentation and error reports and could not find any reports like this one.

One thing I noticed is that "hostssl" says that `ssl = on` must be specified in the `postgresql.conf`.
It looks like you also need to reboot the server after the configuration.
Have you tried rebooting the server instead of reloading the configuration?

* [PostgreSQL: Documentation: 12: 20\.1\. The pg\_hba\.conf File](https://www.postgresql.org/docs/12/auth-pg-hba-conf.html)

  > To make use of this option the server must be built with SSL support. Furthermore, SSL must be enabled by setting the ssl configuration parameter (see Section 18.9 for more information). Otherwise, the hostssl record is ignored except for logging a warning that it cannot match any connections.

**Comment by dgasacas7** [comment]
I'm going to show you another test done with the pg_hba.conf like
```
$ sudo cat /etc/postgresql/12/main/pg_hba.conf | egrep -v '^[[:space:]]*(#.*)?$' -
local   all             postgres                                peer
local   all             all                                     peer
hostssl all             all             0.0.0.0/0               scram-sha-256
hostssl all             all             ::/0                    scram-sha-256
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
```
And with SSL values in postgresql.conf like
```
$ sudo grep -i "^ssl" /etc/postgresql/12/main/postgresql.conf
ssl = on
ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'
```
1. First, I totally restarted the PostgreSQL server
```
$ sudo systemctl restart postgresql
```
2. Once started, I logged in PostgreSQL Database with
```
$ psql
psql (12.3 (Debian 12.3-1.pgdg100+1))
Type "help" for help.
```
3. I changed the user password to '4321'
```
psql=# ALTER USER **** PASSWORD '4321';
ALTER ROLE
```
4. I checked the pg_catalog.pg_authid for the rolpassword
```
psql=# \x
Expanded display is on.
psql=# SELECT rolpassword FROM pg_catalog.pg_authid WHERE rolname='****';
-[ RECORD 1 ]--------------------------------------------------------------------------------------------------------------------------------------
rolpassword | SCRAM-SHA-256$4096:GdZWGrGE85eZikQiN3wuiA==$5dUVltg2J+pElt1SrTeZ6AhEJrzJU8wVdZA2Nl6ofJE=:ZBzI5T2i9MYW3Zak/CHtp66OUttiOj+pR0oGRxs5lK8=
```
5. And then, I copied the field content value to another modified C++ code
```
$ cat ./pg2.cc
#include <string>
#include <pqxx/pqxx>

int main (int, char *argv[])
{
	std::string old_passwd = "1234";
	std::string new_passwd = "SCRAM-SHA-256$4096:GdZWGrGE85eZikQiN3wuiA==$5dUVltg2J+pElt1SrTeZ6AhEJrzJU8wVdZA2Nl6ofJE=:ZBzI5T2i9MYW3Zak/CHtp66OUttiOj+pR0oGRxs5lK8=";

	pqxx::connection c ("host=localhost dbname=**** user=**** password=" + old_passwd);
	pqxx::work w (c);

	w.exec0 ("ALTER USER " + std::string (c.username()) + " PASSWORD '" + new_passwd + "'");

	w.commit();
	c.close();

	return 0;
}
```
Notice that the content of the new_passwd string value is the same as the one generated before in the step 3 and observed in the step 4.
6. Very important: ALTER USER again... to revert password back to '1234'.
```
psql=# ALTER USER **** PASSWORD '1234';
ALTER ROLE
```
7. Compile ./pg2.cc and execute it.
```
$ g++ -std=c++17 pg2.cc -o pg2 -lpqxx -lpq
$ ./pg2
```
8. NOW, IT WORKS !!! (giving, of course, the password 4321)
```
$ psql -h localhost
Password for user ****: 
psql (12.3 (Debian 12.3-1.pgdg100+1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

psql=#
```
So, I guess that the problem should rely mainly on hashes generation.

**Comment by dgasacas7** [comment]
Is there an utility (function, method, online application...) to check if these newly generated hashes matches against the suitable password ?

**Comment by tt4g** [comment]
pqxx seems to be using `PQencryptPasswordConn()` incorrectly.

I look the psql source code, the `\password` command seems to be using a string generated by calling `PQencryptPasswordConn()`.

https://github.com/postgres/postgres/blob/23cbeda50b94c817bed4f7d2127ee09c4e8c8b86/src/bin/psql/command.c#L1988-L2005

Then I looked at the source code for pqxx.

https://github.com/jtv/libpqxx/blob/ddb021ae68f0454e208e8de32a82da1e5e59bd16/src/connection.cxx#L575-L585

pqxx specifies "user" as the second argument and "password" as the third argument.
However, in libpq, the position of the arguments for "user" and "password" are reversed.

The documentation also explains the arguments in the order of libpq: [PostgreSQL: Documentation: 12: 33\.11\. Miscellaneous Functions](https://www.postgresql.org/docs/12/libpq-misc.html#LIBPQ-PQENCRYPTPASSWORDCONN)

We have to fix the pqxx argument.
But I don't have SSL-enabled PostgreSQL, so I can't check it right away.

@dgasacas7 Sorry. If possible, could you modify the pqxx source and check that it works?

**Comment by dgasacas7** [comment]
@tt4g 
THAT'S IT.... Now, It works properly !!!
The parameters order is effectively wrong and must be reversed to fix this issue. 
Please, commit the solution and thanks a lot.

**Comment by tt4g** [comment]
@dgasacas7 Thanks for confirming that!
I create PR #334.

**Comment by jtv** [comment]
Thanks, folks, for digging this up.  I must just never have noticed that the order of those parameters wasn't the obvious one.
