### ISSUE TITLE
efficiency of stream_to 

### ISSUE THREAD

**Issue by chenqingguo** [jtv/libpqxx#337]
The doc shows that using `stream_to` can be significantly faster than `INSERT`,but I found using `stream_to` cost much more time than SQL `INSERT`.
Actually, `stream_to` one row cost 20+ms,but `INSERT` just cost 0.2ms on the same conditions. Am I wrong？

There are not any examples or tests about inserting rows using `stream_to`, can you give me an example?

Thanks,
chenqingguo.

**Comment by jtv** [comment]
There's not much point to using `stream_to` for just one row.  Try inserting a larger number.
