### ISSUE TITLE
mingw64 cross-compile build  on ubuntu host does not create .dll for Windows 

### ISSUE THREAD

**Issue by yscontrol** [jtv/libpqxx#338]
I am building on ubuntu 16.04 xenial using mingw x86_64-w64-mingw32-g++ (GCC) 5.3.1 20160211
x86_64-w64-mingw32-gcc (GCC) 5.3.1 20160211 using
` ./configure --host=x86_64-w64-mingw32 --with-postgres-include=/home/mydir/postgresql-9.3.6/install/mingw64/include --with-postgres-lib=/home/mydir/postgresql-9.3.6/install/mingw64/lib  --disable-documentation PG_CONFIG=$PG_CONFIG --prefix=/home/mydir/libpqxx/install/mingw64
`
postgres-lib contains libpq.dll, .a . Note $PG_CONFIG dir has Windows executable since Postgress was cross-built for Windows so  PG_CONFIG is irrelevant
make shows warning of building only static library:
libtool: compile:  x86_64-w64-mingw32-g++ -std=c++11 -DHAVE_CONFIG_H -I../include -I../include -I/home/mydir/postgresql-9.3.6/install/mingw64/include -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT version.lo -MD -MP -MF .deps/version.Tpo -c version.cxx -o version.o
mv -f .deps/version.Tpo .deps/version.Plo
/bin/bash ../libtool  --tag=CXX   --mode=link x86_64-w64-mingw32-g++ -std=c++11  -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -release 6.4 -rpath /home/cnh/workspace/framework/libpqxx/install/mingw64/lib  -L/home/cnh/workspace/framework/postgresql-9.3.6/install/mingw64/lib -o libpqxx.la -rpath /home/cnh/workspace/framework/libpqxx/install/mingw64/lib array.lo binarystring.lo connection_base.lo connection.lo cursor.lo dbtransaction.lo encodings.lo errorhandler.lo except.lo field.lo largeobject.lo nontransaction.lo notification.lo pipeline.lo prepared_statement.lo result.lo robusttransaction.lo sql_cursor.lo statement_parameters.lo strconv.lo stream_base.lo stream_from.lo stream_to.lo subtransaction.lo tablereader.lo tablestream.lo tablewriter.lo transaction.lo transaction_base.lo row.lo util.lo version.lo  -lpq -lws2_32 
libtool: warning: **undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only**
libtool: link: x86_64-w64-mingw32-ar cru .libs/libpqxx.a  array.o binarystring.o connection_base.o connection.o cursor.o dbtransaction.o encodings.o errorhandler.o except.o field.o largeobject.o nontransaction.o notification.o pipeline.o prepared_statement.o result.o robusttransaction.o sql_cursor.o statement_parameters.o strconv.o stream_base.o stream_from.o stream_to.o subtransaction.o tablereader.o tablestream.o tablewriter.o transaction.o transaction_base.o row.o util.o version.o
x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: x86_64-w64-mingw32-ranlib .libs/libpqxx.a
libtool: link: ( cd ".libs" && rm -f "libpqxx.la" && ln -s "../libpqxx.la" "libpqxx.la" )
make[1]: Leaving directory '/home/cnh/workspace/framework/libpqxxvm/src'
Making all in test
..
and succeeds but only builds libpqxx.a, .lai, libpqxx.la -> ../libpqxx.la, not .dll

What should be done to avoid this "warning"?

BTW: there is a warning :
libtool: compile:  x86_64-w64-mingw32-g++ -std=c++11 -DHAVE_CONFIG_H -I../include -I../include -I/home/cnh/workspace/framework/postgresql-9.3.6/install/mingw64/include -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT connection_base.lo -MD -MP -MF .deps/connection_base.Tpo -c connection_base.cxx -o connection_base.o
connection_base.cxx: In function ‘void pqxx::internal::wait_read(const PGconn*, long int, long int)’:
connection_base.cxx:1299:53: warning: narrowing conversion of ‘(time_t)seconds’ from ‘time_t {aka long long int}’ to ‘long int’ inside { } [-Wnarrowing]
   timeval tv = { time_t(seconds), int(microseconds) };
                                                     ^

**Comment by jtv** [comment]
This conversation suggests adding `-no-undefined` to `LDFLAGS`:

    https://github.com/Ancurio/SDL_sound/issues/3

There's a bit more detail here:

    https://lists.gnu.org/archive/html/libtool/2007-04/msg00068.html

Can't say I really understand what's going on, but I did find one hint online about MinGW not being able to build libraries with functions that return  floating-point types...  Hope that's not it!

**Comment by yscontrol** [comment]
@jtv ok, I added LDFLAGS="$LDFLAGS ${with_postgres_libpath}" -no-undefined to configure.ac file. However after make clean I configure could not find std::this_thread: headers I generated with cmake in mingw-std-threads subdir, so need to add -Imingw-std-threads to  configure.ac and I noticed it generates -I../include twice:
libtool: compile:  /usr/bin/x86_64-w64-mingw32-gcc -std=c++11 -DHAVE_CONFIG_H -I../include -I../include -I/home/mydir/postgresql-9.3.6/install/mingw64/include -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT util.lo -MD -MP -MF .deps/util.Tpo -c util.cxx -o util.o

Do you know why (see my command in the top message), not big deal but still sometheing else might   wrong?

**Comment by jtv** [comment]
Ah, see it now.  The only thing that libpqxx does with `this_thread` is to _sleep for n seconds._  That's something you can do in other ways, e.g. on Windows you can just do `Sleep(n)`; or POSIX has a similar `sleep(n)`.

**Comment by yscontrol** [comment]
Sure, but would not it be cleaner to keep libpqxx code as is and just add
include dir path to dir where I already built the thread headers as you
suggested before.
Only question is how to modify configure.ac to produce -I arg and remove
extra -I../include

**Comment by jtv** [comment]
You may not need to modify it.  Just add your options to `LDFLAGS`, `CXXFLAGS`, and possibly `CPPFLAGS` for the preprocessor.  (That last one is less universal though, so may not work here.)

For example, I like to do a quick test build like this:

    ./configure CXXFLAGS=-O0

**Comment by yscontrol** [comment]
with optimization at -O0 it is built static libraries but LDLAGS=-no-undefined is rejected :
config.log shows:
Thread model: posix
gcc version 5.3.1 20160211 (GCC) 
configure:2544: $? = 0
configure:2533: x86_64-w64-mingw32-g++ -V >&5
x86_64-w64-mingw32-g++: error: unrecognized command line option '-V'
x86_64-w64-mingw32-g++: fatal error: no input files
compilation terminated.
configure:2544: $? = 1
configure:2533: x86_64-w64-mingw32-g++ -qversion >&5
x86_64-w64-mingw32-g++: error: unrecognized command line option '-qversion'
x86_64-w64-mingw32-g++: fatal error: no input files
compilation terminated.
configure:2544: $? = 1
configure:2564: checking whether the C++ compiler works
configure:2586: x86_64-w64-mingw32-g++ -O0  --no-undefined conftest.cpp  >&5
x86_64-w64-mingw32-g++: **error: unrecognized command line option '--no-undefined'**
configure:2590: $? = 1
configure:2628: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libpqxx"
| #define PACKAGE_TARNAME "libpqxx"
| #define PACKAGE_VERSION "6.4.6"
| #define PACKAGE_STRING "libpqxx 6.4.6"
| #define PACKAGE_BUGREPORT "Jeroen T. Vermeulen"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */

**Comment by yscontrol** [comment]
Could you please check if configure.ac has problem with generating correct flags to provide path to PostgreSQL libpq libraries as make generates flag -lpq
/bin/bash ../libtool  --tag=CXX   --mode=link x86_64-w64-mingw32-g++ -std=c++11  -O0 -fvisibility=hidden -fvisibility-inlines-hidden -release 6.4 -rpath /home/cnh/workspace/framework/libpqxx/install/mingw64/lib  -L/home/cnh/workspace/framework/postgresql-9.3.6/install/mingw64/lib -o libpqxx.la -rpath /home/cnh/workspace/framework/libpqxx/install/mingw64/lib array.lo binarystring.lo connection_base.lo connection.lo cursor.lo dbtransaction.lo encodings.lo errorhandler.lo except.lo field.lo largeobject.lo nontransaction.lo notification.lo pipeline.lo prepared_statement.lo result.lo robusttransaction.lo sql_cursor.lo statement_parameters.lo strconv.lo stream_base.lo stream_from.lo stream_to.lo subtransaction.lo tablereader.lo tablestream.lo tablewriter.lo transaction.lo transaction_base.lo row.lo util.lo version.lo  -lpq -lws2_32 
libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only
libtool: link: x86_64-w64-mingw32-ar cru .libs/libpqxx.a  array.o binarystring.o connection_base.o connection.o cursor.o dbtransaction.o encodings.o errorhandler.o except.o field.o largeobject.o nontransaction.o notification.o pipeline.o prepared_statement.o result.o robusttransaction.o sql_cursor.o statement_parameters.o strconv.o stream_base.o stream_from.o stream_to.o subtransaction.o tablereader.o tablestream.o tablewriter.o transaction.o transaction_base.o row.o util.o version.o
x86_64-w64-mingw32-ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: x86_64-w64-mingw32-ranlib .libs/libpqxx.a
libtool: link: ( cd ".libs" && rm -f "libpqxx.la" && ln -s "../libpqxx.la" "libpqxx.la" )

**Comment by jtv** [comment]
Strange that the error message says `--no-undefined` — because AFAICT you did pass the correct `--no-undefined`.

**Comment by jtv** [comment]
@yscontrol I just had a thought: the build doesn't normally invoke the linker directly.  It invokes the compiler front-end, which in turn invokes the linker.  So perhaps `-no-undefined` should be a linker option, rather than a compiler option?  With gcc I think you pass linker options by wrapping them in a special compiler option...  Something like `-Wl,-no-undefined`.  I don't remember the exact spelling.

**Comment by yscontrol** [comment]
@jtv tried ```./configure  ... CXXFLAGS='-O0 -Wl,--no-undefined' ... ``` (and configure.ac LDFLAGS="$LDFLAGS -no-undefined" ) but still ```libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only```

**Comment by jtv** [comment]
Wait...  `-Wl,--no-undefined`?  With the `--no`?  I thought you'd need the single dash here: `-no`.

**Comment by yscontrol** [comment]
Same problem with single -no, but building with mingw gcc 5.3.0 and adding this flag to make  LDFLAGS="-no-undefined ..." worked and runner is built. It fail to run on windows but this is another issue. So now what needs to change in configure.ac to build runner statically ?  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -static -static-libgcc -static-libstdc++") worked with cmake

**Comment by jtv** [comment]
When I try building using the `configure` script, with those options, I get loads of link errors.  :-(  For basically everything: the compiler runtime, pthread, libpq...  everything.  No idea why that would happen.

**Comment by yscontrol** [comment]
I clarified -no-undefined  was added to make command. Anyway I am not having problem with building runner.exe in the current test, but wonder how to change this build to static to be able to run under windows as it is too difficult to match DLLs on windows. This should probable be spawned to a separate question while this one closed.
