### ISSUE TITLE
[Suggestion] bug fix release 6.4.x

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#340]
From this comment: https://github.com/jtv/libpqxx/issues/339#issuecomment-647847379

When buit shared library, pqxx 6.4.6 can not link on Windows OS.
This issue was fixed by 5290329f4610763a2fd8f8379937d87383c570c6 in pqxx 7.0.0, but this patch was not backported to 6.4.x.

Since version 6.4.x is the last version to support C++11, we should do a bug fix release with the relevant commit backported.

**Comment by jtv** [comment]
Fair enough.  Expect a pair of new releases soon.

**Comment by jtv** [comment]
Doing the 6.4.7 release now.

**Comment by tt4g** [comment]
Excellent!
