### ISSUE TITLE
how to handle new data type which is defined in PostgreSQL

### ISSUE THREAD

**Issue by gzliudan** [jtv/libpqxx#346]
If i defined a new data type in PostgreSQL, such as uint64_t or uint128_t or composite structure, then how to map it to C++ native data type or other class in libpqxx ?

**Comment by jtv** [comment]
This question is answered in the documentation: `include/pqxx/doc/datatypes.md`.

But I just noticed that I forgot to _link_ to that page, and so that's why it's not visible on readthedocs.org.  Sorry about that, I'll fix it right away.

**Comment by jtv** [comment]
(Done.  If you look at the "latest" version on readthedocs.org now, you'll see this document added there.  Perhaps a little easier to read than Markdown.)

**Comment by gzliudan** [comment]
I read the document today. It seems libpqxx can only translate new data type from text format and to text format. How can I use the more efficient binary format mode? And some data types have only binary mode and no text mode. For example, I defined unsigned int64 in postgresql:  
```sql
CREATE TYPE     uint8;
CREATE FUNCTION uint8_in(cstring)       RETURNS uint8   IMMUTABLE STRICT LANGUAGE C AS '$libdir/abc', 'uint8_in';
CREATE FUNCTION uint8_out(uint8)        RETURNS cstring IMMUTABLE STRICT LANGUAGE C AS '$libdir/abc', 'uint8_out';
CREATE FUNCTION uint8_receive(internal) RETURNS uint8   IMMUTABLE STRICT LANGUAGE C AS '$libdir/abc', 'uint8_receive';
CREATE FUNCTION uint8_send(uint8)       RETURNS bytea   IMMUTABLE STRICT LANGUAGE C AS '$libdir/abc', 'uint8_send';

CREATE TYPE uint8 
(
    INPUT   = uint8_in, 
    OUTPUT  = uint8_out, 
    RECEIVE = uint8_receive,
    SEND    = uint8_send,
    INTERNALLENGTH = 8, 
    ALIGNMENT = double,
    PASSEDBYVALUE
);

```

```cpp
PG_FUNCTION_INFO_V1(uint8_receive);
Datum uint8_receive(PG_FUNCTION_ARGS) {
    StringInfo msg = (StringInfo)PG_GETARG_POINTER(0);
    PG_RETURN_UINT64((uint64_t)pq_getmsgint64(msg));
}

PG_FUNCTION_INFO_V1(uint8_send);
Datum uint8_send(PG_FUNCTION_ARGS) {
    uint64         arg = PG_GETARG_UINT64(0);
    StringInfoData buf;

    pq_begintypsend(&buf);
    pq_sendint64(&buf, arg);
    PG_RETURN_BYTEA_P(pq_endtypsend(&buf));
}

```

In this case, can I use function memcpy copy C++ uint64 data type to libpqxx driver, let postgresql get uint8 by binary mode use function uint8_receive? And postgressql send uint8 data type by binary mode use function uint8_send, then I copy binary data to C++ type uint64 directly?
