### ISSUE TITLE
Unable to run NOTIFY statements with message/payload. 

### ISSUE THREAD

**Issue by wrmichaelmak** [jtv/libpqxx#349]
I am trying to NOTIFY using both 'prepare and exec_prepared' and 'exec_params'.

My code to do both methods are:

Method 1  'prepare and exec_prepared' :

```
work w(C);
C.prepare("message", "NOTIFY db123, $1"); 
w.exec_prepared("message", "Hello World!"); 
w.commit();
```

Method 2 'exec_params':
```
work w(C);
w.exec_params("NOTIFY db123, $1::text", "Hello World!");
w.commit();
```

Both methods give me an error message of :
```
ERROR:  syntax error at or near "$1"
LINE 1: NOTIFY db123 $1::text
```
or 
```
ERROR: syntax error at or near "$1"
LINE 1: NOTIFY db123 $1
```

**Comment by wrmichaelmak** [comment]
I found a workaround it. In case anyone is wondering. Do:

```
stringstream notifyCommand;
char channelName[] = "db123";
char message[] = "Hello World";
notifyCommand << "Notify " << channelName << ", \'" << message << "\'" << endl;

w.exec(notifyCommand.str());
w.commit();
```

**Comment by jtv** [comment]
Here's something I wasn't aware of...  The postgres docs say that the payload _must be a string literal._

So for example, this won't work either, whether through libpqxx or some other interface:

    NOTIFY db123, now()::text;

**Comment by KayEss** [comment]
> notifyCommand << "Notify " << channelName << ", \'" << message << "\'" << endl;

This looks like an SQL injection attack waiting to happen. You need to use the quoting function on the message so an attacker can't do nasty things.

**Comment by wrmichaelmak** [comment]
> > notifyCommand << "Notify " << channelName << ", '" << message << "'" << endl;
> 
> This looks like an SQL injection attack waiting to happen. You need to use the quoting function on the message so an attacker can't do nasty things.

Correct me if I am wrong but SQL injection attacks are done via SELECT comands right? In this case, this is a NOTIFY command hence SQL injection will not work especially since the message is literally just a string? Nonetheless, it is always better to be safe.

**Comment by KayEss** [comment]
Sort of. If `notify` contains the string `hello'; TRUNCATE TABLE users; -- ` you're still going to have a bad day as it will build the statement `Notify channel, 'hello'; TRUNCATE TABLE users; --'`

The important thing for an injection attack isn't what command you think you're executing, but whether you give an attacker any influence on the string you're inserting into the SQL. As such, as you say, better safe than sorry.

**Comment by wrmichaelmak** [comment]
Got it. Thanks a lot for the insight @KayEss.

**Comment by jtv** [comment]
@KayEss is completely right (except his table should be called "user", not "users").

Use `w.esc_name(channelName)` if it's a variable that the outside world can influence, and `w.esc(message)` for the payload.
