### ISSUE TITLE
C++17 issues

### ISSUE THREAD

**Issue by egorpugin** [jtv/libpqxx#35]
Hi!

When building user code in C++17 mode, there are build errors about removed stuff.
See https://github.com/jtv/libpqxx/blob/master/include/pqxx/errorhandler.hxx#L52
Also in `notification.hxx`, `transactor.hxx`, `pipeline.hxx`.
`std::unary_function` was removed from the language, also `std::binary_function`.

My personal "easyfix" is to comment out those items.

**Comment by jtv** [comment]
Fixed in 16d9aea63a8d5e18230236f132a0bceb8aab8804.

**Comment by egorpugin** [comment]
Thanks!
Great library, very useful, keep improving it!

**Comment by jtv** [comment]
Glad you like it.  :)
