### ISSUE TITLE
May I have a question? which version support the postgres 8.2?

### ISSUE THREAD

**Issue by liwenhui-soul** [jtv/libpqxx#350]

**Comment by tt4g** [comment]
pqxx 7.x supports PostgreSQL 9.3 and above.

Quotes from pqxx web site: https://pqxx.org/development/libpqxx/faq/

> What PostgreSQL versions are supported?
> As a general rule, all currently supported major PostgreSQL releases. At this entry's time of writing, both front-end and back-end need to be version 9.3 or better.

**Comment by jtv** [comment]
The 9.3 requirement is mostly to keep development simple.  But I think the current libpqxx would _work_ with 8.2, just not for all features.

So one thing you could do, is just try the latest libpqxx, and if that doesn't support everything you need, go back to 6.4.7.

**Comment by liwenhui-soul** [comment]
ok thanks

**Comment by markosole** [comment]
Hi guys, I am having very similar problem where my postgres DB is on version 8.2 and pqxx 7.7.x 
I am using vcpkg to install the package in my Visual Studio project but the problem is I don't know how to target older version like 6.4.7 as suggested. 

How can I include older version in project? (vcpgk search feature offers only latest version)

**Comment by KayEss** [comment]
This sounds like a question for the vcpkg project, or whatever help channels they offer

That version of Postgres is end of live already though. You should upgrade it.

**Comment by tt4g** [comment]
The following URL was found by the search engine.
You may want to ask the vcpkg community for more information.

- Issue: microsoft/vcpkg#21357
- Doc: https://vcpkg.readthedocs.io/en/latest/specifications/versioning/
- Blog: https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/

**Comment by jtv** [comment]
The restrictions on postgres versions in libpqxx are mostly about libpq
versions, so client-side.  Off the top of my head I can't think of any
problem with older servers.  The libpq version does not have to match the
postgres version on the server side.

So try building libpqxx with a supported libpq (IIRC at the moment that's
version 10 or newer, but I'd try version 14).  I think you should then be
able to connect to an older database server.

**Comment by jtv** [comment]
Is it possible that you compiled some things in Debug mode and others in
Release mode?

**Comment by markosole** [comment]
Well could be, I've been running it in Debug so far. When I switch to Release, build it (with no errors) and run the app I get this error:
![image](https://user-images.githubusercontent.com/10780405/204870586-5105379a-f6b1-472a-b06a-a47f03839175.png)

This more likely isn't related to pqxx at all.
