### ISSUE TITLE
Does the libpqxx.a contain the libpq.a

### ISSUE THREAD

**Issue by liwenhui-soul** [jtv/libpqxx#351]
Do I need libpq.a when I use libpqxx.a

**Comment by tt4g** [comment]
How did you build `libpqxx.a`?
When using CMake, `libpqxx.a` is linked `libpq.a`.

**Comment by liwenhui-soul** [comment]
I build it like this
```
/configure --prefix=/usr/local/libpqxx --disable-documentation
make && make install
```
is libpqxx.a also linked libpq.a?

I didnt use cmake because I recieved this error

```
CMake Error at /opt/cmake-3.12.4-Linux-x86_64/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY
  PostgreSQL_TYPE_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/cmake-3.12.4-Linux-x86_64/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /opt/cmake-3.12.4-Linux-x86_64/share/cmake-3.12/Modules/FindPostgreSQL.cmake:175 (find_package_handle_standard_args)
  cmake/config.cmake:26 (find_package)
  CMakeLists.txt:27 (include)
```

**Comment by liwenhui-soul** [comment]
> How did you build `libpqxx.a`?
> When using CMake, `libpqxx.a` is linked `libpq.a`.

are you sure? I made it by cmake, and  the detail is :
`/bin/ar qc libpqxx.a  CMakeFiles/pqxx_static.dir/array.cxx.o CMakeFiles/pqxx_static.dir/binarystring.cxx.o CMakeFiles/pqxx_static.dir/connection.cxx.o CMakeFiles/pqxx_static.dir/connection_base.cxx.o CMakeFiles/pqxx_static.dir/cursor.cxx.o CMakeFiles/pqxx_static.dir/dbtransaction.cxx.o CMakeFiles/pqxx_static.dir/encodings.cxx.o CMakeFiles/pqxx_static.dir/errorhandler.cxx.o CMakeFiles/pqxx_static.dir/except.cxx.o CMakeFiles/pqxx_static.dir/field.cxx.o CMakeFiles/pqxx_static.dir/largeobject.cxx.o CMakeFiles/pqxx_static.dir/nontransaction.cxx.o CMakeFiles/pqxx_static.dir/notification.cxx.o CMakeFiles/pqxx_static.dir/pipeline.cxx.o CMakeFiles/pqxx_static.dir/prepared_statement.cxx.o CMakeFiles/pqxx_static.dir/result.cxx.o CMakeFiles/pqxx_static.dir/robusttransaction.cxx.o CMakeFiles/pqxx_static.dir/row.cxx.o CMakeFiles/pqxx_static.dir/sql_cursor.cxx.o CMakeFiles/pqxx_static.dir/statement_parameters.cxx.o CMakeFiles/pqxx_static.dir/strconv.cxx.o CMakeFiles/pqxx_static.dir/stream_base.cxx.o CMakeFiles/pqxx_static.dir/stream_from.cxx.o CMakeFiles/pqxx_static.dir/stream_to.cxx.o CMakeFiles/pqxx_static.dir/subtransaction.cxx.o CMakeFiles/pqxx_static.dir/tablereader.cxx.o CMakeFiles/pqxx_static.dir/tablestream.cxx.o CMakeFiles/pqxx_static.dir/tablewriter.cxx.o CMakeFiles/pqxx_static.dir/transaction.cxx.o CMakeFiles/pqxx_static.dir/transaction_base.cxx.o CMakeFiles/pqxx_static.dir/util.cxx.o CMakeFiles/pqxx_static.dir/version.cxx.o
/bin/ranlib libpqxx.a`
there is no libpq.a

**Comment by jtv** [comment]
If this answers your original question: you need to link your application to _both_ libpqxx _and_ libpq.  So: `-lpqxx -lpq`.

**Comment by tt4g** [comment]
CMake will find libraries in the path specified for installation on many platforms.
Look at [the link](https://github.com/Kitware/CMake/blob/3a77329c40803b02fe33ffc86197c1baf291aaff/Modules/FindPostgreSQL.cmake#L90-L98), this is the list of paths to search in CMake version 3.12 (do not get the library path from `pg_config).

And CMake will only detect versions [it knows about](https://github.com/Kitware/CMake/blob/3a77329c40803b02fe33ffc86197c1baf291aaff/Modules/FindPostgreSQL.cmake#L73-L74).

> are you sure? I made it by cmake, and the detail is:

CMake seems to detect `.so` in preference to `.a`.
For the aforementioned reasons, it is possible that CMake did not find `libpq.a`.

The most reliable way is to tell CMake the location of the library by specifying `PostgreSQL_LIBRARY`.
Example: `cmake -DPostgreSQL_LIBRARY=$PATH_TO_LIBDIR>/libpq.a`

**Comment by liwenhui-soul** [comment]
> CMake will find libraries in the path specified for installation on many platforms.
> Look at [the link](https://github.com/Kitware/CMake/blob/3a77329c40803b02fe33ffc86197c1baf291aaff/Modules/FindPostgreSQL.cmake#L90-L98), this is the list of paths to search in CMake version 3.12 (do not get the library path from `pg_config).
> 
> And CMake will only detect versions [it knows about](https://github.com/Kitware/CMake/blob/3a77329c40803b02fe33ffc86197c1baf291aaff/Modules/FindPostgreSQL.cmake#L73-L74).
> 
> > are you sure? I made it by cmake, and the detail is:
> 
> CMake seems to detect `.so` in preference to `.a`.
> For the aforementioned reasons, it is possible that CMake did not find `libpq.a`.
> 
> The most reliable way is to tell CMake the location of the library by specifying `PostgreSQL_LIBRARY`.
> Example: `cmake -DPostgreSQL_LIBRARY=$PATH_TO_LIBDIR>/libpq.a`

ok,it works

```
[ 19%] Linking CXX shared library libpqxx.so
cd /root/dev/libpqxx/build/src && /opt/cmake-3.12.4-Linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/pqxx_shared.dir/link.txt --verbose=1
/opt/clang/bin/clang++ -fPIC -stdlib=libc++ -L/opt/dependency/package/lib -L/opt/dependency/package/lib -shared -Wl,-soname,libpqxx.so -o libpqxx.so CMakeFiles/pqxx_shared.dir/array.cxx.o CMakeFiles/pqxx_shared.dir/binarystring.cxx.o CMakeFiles/pqxx_shared.dir/connection.cxx.o CMakeFiles/pqxx_shared.dir/connection_base.cxx.o CMakeFiles/pqxx_shared.dir/cursor.cxx.o CMakeFiles/pqxx_shared.dir/dbtransaction.cxx.o CMakeFiles/pqxx_shared.dir/encodings.cxx.o CMakeFiles/pqxx_shared.dir/errorhandler.cxx.o CMakeFiles/pqxx_shared.dir/except.cxx.o CMakeFiles/pqxx_shared.dir/field.cxx.o CMakeFiles/pqxx_shared.dir/largeobject.cxx.o CMakeFiles/pqxx_shared.dir/nontransaction.cxx.o CMakeFiles/pqxx_shared.dir/notification.cxx.o CMakeFiles/pqxx_shared.dir/pipeline.cxx.o CMakeFiles/pqxx_shared.dir/prepared_statement.cxx.o CMakeFiles/pqxx_shared.dir/result.cxx.o CMakeFiles/pqxx_shared.dir/robusttransaction.cxx.o CMakeFiles/pqxx_shared.dir/row.cxx.o CMakeFiles/pqxx_shared.dir/sql_cursor.cxx.o CMakeFiles/pqxx_shared.dir/statement_parameters.cxx.o CMakeFiles/pqxx_shared.dir/strconv.cxx.o CMakeFiles/pqxx_shared.dir/stream_base.cxx.o CMakeFiles/pqxx_shared.dir/stream_from.cxx.o CMakeFiles/pqxx_shared.dir/stream_to.cxx.o CMakeFiles/pqxx_shared.dir/subtransaction.cxx.o CMakeFiles/pqxx_shared.dir/tablereader.cxx.o CMakeFiles/pqxx_shared.dir/tablestream.cxx.o CMakeFiles/pqxx_shared.dir/tablewriter.cxx.o CMakeFiles/pqxx_shared.dir/transaction.cxx.o CMakeFiles/pqxx_shared.dir/transaction_base.cxx.o CMakeFiles/pqxx_shared.dir/util.cxx.o CMakeFiles/pqxx_shared.dir/version.cxx.o /usr/local/postgres/lib/libpq.a
```

so I got libpqxx.so including libpq.a, and no need to take both of them. Thank you.

**Comment by jtv** [comment]
Glad it worked for you.  I'm not a CMake expert...
