### ISSUE TITLE
Does libpqxx support user defined data types with binary mode?

### ISSUE THREAD

**Issue by gzliudan** [jtv/libpqxx#352]
I read the document today. It seems libpqxx can only translate new data type from text format and to text format. How can I use the more efficient binary format mode? Since I have some data types only support binary mode, no text mode. For example, if I defined a new data type named uint8 in postgresql which is uint64 in C++:  
```sql
CREATE TYPE     uint8;
CREATE FUNCTION uint8_in(cstring)       RETURNS uint8   IMMUTABLE STRICT LANGUAGE C AS '$libdir/abc', 'uint8_in';
CREATE FUNCTION uint8_out(uint8)        RETURNS cstring IMMUTABLE STRICT LANGUAGE C AS '$libdir/abc', 'uint8_out';
CREATE FUNCTION uint8_receive(internal) RETURNS uint8   IMMUTABLE STRICT LANGUAGE C AS '$libdir/abc', 'uint8_receive';
CREATE FUNCTION uint8_send(uint8)       RETURNS bytea   IMMUTABLE STRICT LANGUAGE C AS '$libdir/abc', 'uint8_send';

CREATE TYPE uint8 
(
    INPUT   = uint8_in, 
    OUTPUT  = uint8_out, 
    RECEIVE = uint8_receive,
    SEND    = uint8_send,
    INTERNALLENGTH = 8, 
    ALIGNMENT = double,
    PASSEDBYVALUE
);

```

```cpp
PG_FUNCTION_INFO_V1(uint8_receive);
Datum uint8_receive(PG_FUNCTION_ARGS) {
    StringInfo msg = (StringInfo)PG_GETARG_POINTER(0);
    PG_RETURN_UINT64((uint64_t)pq_getmsgint64(msg));
}

PG_FUNCTION_INFO_V1(uint8_send);
Datum uint8_send(PG_FUNCTION_ARGS) {
    uint64         arg = PG_GETARG_UINT64(0);
    StringInfoData buf;

    pq_begintypsend(&buf);
    pq_sendint64(&buf, arg);
    PG_RETURN_BYTEA_P(pq_endtypsend(&buf));
}

```

In this case, can I use function such as memcpy copy C++ uint64 data type to libpqxx, let postgresql get uint8 by binary mode use function uint8_receive? And postgressql send uint8 data type by binary mode use function uint8_send, then I copy binary data to C++ type uint64 directly from libpqxx? 

_Originally posted by @jtv in https://github.com/jtv/libpqxx/issues/346#issuecomment-653631531_

**Comment by jtv** [comment]
You can't.  Binary data transfer just didn't seem worth the trouble of supporting:
 * The formats are neither stable nor documented.  They could change without warning, and then you'd have a very nasty data corruption bug, at best.
 * You have to know the _exact_ SQL type of any field you read or write.  Get it wrong and you have another data corruption bug or worse.
 * If the schema changes, previously correct code can suddenly become another data corruption bug, or memory corruption, or crash, or remote execution vulnerability.
 * Matching various C++ types to SQL types adds another layer of complexity — you could parse an SQL `integer` into an `int32`, or an `int64`, or an `int16`, or a `uint32`, and so on.  We'd need to figure out which of these are valid.
 * These problems wouldn't just be for libpqxx to solve.  They would affect client code as well.
 * Parsing or producing the binary types doesn't look as efficient as I hoped — you don't get simple data like "a big-endian 32-bit signed integer," but variable-length fields that still require dynamic loops to parse.
 * It's not clear to me that the binary types are necessarily more compact than the text format, either.

Even if those things weren't true, you wouldn't be able to just `memcpy` binary data.  You'd have to know exactly what's in each of the fields, and there would still have to be some code to convert it.  You'd need to do stuff like `htonl()` (or if you forgot, your code would become nonportable).

**Comment by gzliudan** [comment]
Yes, use text format is simple and has better compatibility. But there is a case, if a long double type value is LDBL_MAX, it will cost 16 bytes when use binary mode, but the text format will need 4940 bytes when use std::to_string:

1189731495357231765021263853030970205169063322294624200440323733891737005522970722616410290336528882853545697807495577314427443153670288434198125573853743678673593200706973263201915918282961524365529510646791086614311790632169778838896134786560600399148753433211454911160088679845154866512852340149773037600009125479393966223151383622417838542743917838138717805889487540575168226347659235576974805113725649020884855222494791399377585026011773549180099796226026859508558883608159846900235645132346594476384939859276456284579661772930407806609229102715046085388087959327781622986827547830768080040150694942303411728957777100335714010559775242124057347007386251660110828379119623008469277200965153500208474470792443848545912886723000619085126472111951361467527633519562927597957250278002980795904193139603021470997035276467445530922022679656280991498232083329641241038509239184734786121921697210543484287048353408113042573002216421348917347174234800714880751002064390517234247656004721768096486107994943415703476320643558624207443504424380566136017608837478165389027809576975977286860071487028287955567141404632615832623602762896316173978484254486860609948270867968048078702511858930838546584223040908805996294594586201903766048446790926002225410530775901065760671347200125846406957030257138960983757998926954553052368560758683179223113639519468850880771872104705203957587480013143131444254943919940175753169339392366881856189129931729104252921236835159922322050998001677102784035360140829296398115122877768135706045789343535451696539561254048846447169786893211671087229088082778350518228857646062218739702851655083720992349483334435228984751232753726636066213902281264706234075352071724058665079518217303463782631353393706774901950197841690441824738063162828586857741432581165364040218402724913393320949219498422442730427019873044536620350262386957804682003601447291997123095530057206141866974852846856186514832715974481203121946751686379343096189615107330065552421485195201762858595091051839472502863871632494167613804996319791441870254302706758495192008837915169401581740046711477877201459644461175204059453504764721807975761111720846273639279600339670470037613374509553184150073796412605047923251661354841291884211340823015473304754067072818763503617332908005951896325207071673904547777129682265206225651439919376804400292380903112437912614776255964694221981375146967079446870358004392507659451618379811859392049544036114915310782251072691486979809240946772142727012404377187409216756613634938900451232351668146089322400697993176017805338191849981933008410985993938760292601390911414526003720284872132411955424282101831204216104467404621635336900583664606591156298764745525068145003932941404131495400677602951005962253022823003631473824681059648442441324864573137437595096416168048024129351876204668135636877532814675538798871771836512893947195335061885003267607354388673368002074387849657014576090349857571243045102038730494854256702479339322809110526041538528994849203991091946129912491633289917998094380337879522093131466946149705939664152375949285890960489916121944989986384837022486672249148924678410206183364627416969576307632480235587975245253737035433882960862753427740016333434055083537048507374544819754722228975281083020898682633020285259923084168054539687911418297629988964576482765287504562854924265165217750799516259669229114977788962356670956627138482018191348321687995863652637620978285070099337294396784639879024914514222742527006363942327998483976739987154418554201562244154926653014515504685489258620276085761837129763358761215382565129633538141663949516556000264159186554850057052611431952919918807954522394649627635630178580896692226406235382898535867595990647008385687123810329591926494846250768992258419305480763620215089022149220528069842018350840586938493815498909445461977893029113576516775406232278298314033473276603952231603422824717528181818844304880921321933550869873395861276073670866652375555675803171490108477320096424318780070008797346032906278943553743564448851907191616455141155761939399690767415156402826543664026760095087523945507341556135867933066031744720924446513532366647649735400851967040771103640538150073486891798364049570606189535005089840913826869535090066783324472578712196604415284924840041850932811908963634175739897166596000759487800619164094854338758520657116541072260996288150123144377944008749301944744330784388995701842710004808305012177123560622895076269042856800047718893158089358515593863176652948089031267747029662545110861548958395087796755464137944895960527975209874813839762578592105756284401759349324162148339565350189196811389091843795734703269406342890087805846940352453479398080674273236297887100867175802531561302356064878709259865288416350972529537091114317204887747405539054009425375424119317944175137064689643861517718849867010341532542385911089624710885385808688837777258648564145934262121086647588489260031762345960769508849149662444156604419552086811989770240.000000

**Comment by jtv** [comment]
Sure, there's always a worst case.  But that's not as bad as finding out that you've been inserting wrong data. which is a big risk with binary transfers.

**Comment by gzliudan** [comment]
A more common example is binary byte array, text format will cost double size than binary mode.

**Comment by jtv** [comment]
Yes, I'm hoping some day there will be a well-documented, efficient binary format.  At that point I'm hoping to support it fully — I had a really fun design lined up for binary formats, when I hit all those problems I mentioned and had to give the whole thing up.

Specifically for BYTEA values though there _is_ a possibility to get binary transfers.  When you call a prepared statement or a parameterised statement, and you pass a `binarystring` argument to it, then the `binarystring` gets transferred in the binary format, as a special case.  But there's nothing like that going the other way.
