### ISSUE TITLE
problem of create new data type

### ISSUE THREAD

**Issue by gzliudan** [jtv/libpqxx#353]
According to document of create new data type, I write below codes:

```cpp
namespace pqxx {
    template<>
    std::string const pqxx::type_name<baozi::Tag> {"tag"};

    template<>
    struct nullness_traits<baozi::Tag> : pqxx::no_null<baozi::Tag> {};

    template<>
    struct string_traits<baozi::Tag> {
        static baozi::Tag  from_string(std::string_view text);
        static zview       to_buf(char* begin, char* end, const baozi::Tag& value);
        static char*       into_buf(char* begin, char* end, const baozi::Tag& value);
        static std::size_t size_buffer(const baozi::Tag& value) noexcept;
    };
}   // namespace pqxx
```
baozi::Tag is the C++ type name, tag is the sql type name in postgresql. But when I complie the above codes, the below error occurs:  
```
warning: extra qualification on member 'type_name' [-Wextra-qualification]
    std::string const pqxx::type_name<baozi::Tag> {"tag"};
error: explicit specialization of undeclared template struct 'nullness_traits'
    struct nullness_traits<baozi::Tag> : pqxx::no_null<baozi::Tag> {};
```

**Comment by gzliudan** [comment]
It seems that nullness_traits should be nullness ?

**Comment by tt4g** [comment]
I think [datatypes.md](https://github.com/jtv/libpqxx/blob/b39ae42cfe71825d9641aad7549a4bb7e3b38db1/include/pqxx/doc/datatypes.md) is old, `pqxx::nullness_traits` already removed in pqxx 7.0.0.

You must declare a specialized type of `pqxx::nullness`.

https://github.com/jtv/libpqxx/blob/29f8c73492a1bfdf87fda77351c7356ebee5ecde/include/pqxx/strconv.hxx#L86-L104

You can refer to the reference implementation from tests: https://github.com/jtv/libpqxx/blob/7.1.2/test/test_types.hxx#L69

**Comment by gzliudan** [comment]
Than you. Yes, the document should be updated, replace nullness_traits with nullness.  
Then how about warning: extra qualification on member 'type_name' ?

> > It seems that nullness_traits should be nullness ?
> 
> Yes.
> 
> I think [datatypes.md](https://github.com/jtv/libpqxx/blob/b39ae42cfe71825d9641aad7549a4bb7e3b38db1/include/pqxx/doc/datatypes.md) is old, `pqxx::nullness_traits` already removed in pqxx 7.0.0.
> 
> You must declare a specialized type of `pqxx::nullness`.
> 
> https://github.com/jtv/libpqxx/blob/29f8c73492a1bfdf87fda77351c7356ebee5ecde/include/pqxx/strconv.hxx#L86-L104
> 
> You can refer to the reference implementation from tests: https://github.com/jtv/libpqxx/blob/7.1.2/test/test_types.hxx#L69

**Comment by tt4g** [comment]
Probably not necessary `pqxx::type_name<baozi::Tag>` because `pqxx::internal::demangle_type_name` provide your type name (does not declare `pqxx::type_name<ipv4>` in tests):
https://github.com/jtv/libpqxx/blob/29f8c73492a1bfdf87fda77351c7356ebee5ecde/include/pqxx/strconv.hxx#L75-L76

Another way. add `inline` keyword (refer to `PQXX_DECLARE_ENUM_CONVERSION` macro).

https://github.com/jtv/libpqxx/blob/29f8c73492a1bfdf87fda77351c7356ebee5ecde/include/pqxx/strconv.hxx#L232-L235

**Comment by gzliudan** [comment]
Yes, you are right. pqxx::type_name can be removed.

**Comment by jtv** [comment]
Sorry for the typo — I'm just pushing a fix for that.

I would still recommend writing your own `type_name` for your own type, just because your compiler might not have `__cxa_demangle` and the name might come out hard to read and/or different than you would write it.
