### ISSUE TITLE
Is there a simple way to handle composite data type?

### ISSUE THREAD

**Issue by gzliudan** [jtv/libpqxx#355]
If a composite data type is created in PostgreSQL, such as below:
```sql
CREATE TYPE new_data_type AS (
    name            text,
    supplier_id     integer,
    price           double precision
);
```
Then is there a simple way to define it in libpqxx? assume all data type of each field has been defined in libpqxx already.

**Comment by jtv** [comment]
There's nothing ready-made, though I imagine it shouldn't be too hard to extract the array-related parsing code for converting from the text format to your custom type on the C++ side.

**Comment by jtv** [comment]
I had another look, and I think I'll try and build some support for this.  But it does raise the question: should the string conversion functions be encoding-aware?  So far I've been able to get away with supporting only ASCII (plus basically anything you like in strings).  That would still _mostly_ work for arrays and composite types, but not entirely I think.

**Comment by gzliudan** [comment]
For composite data type, PostgreSQL support  ('member1','member2','member3') format

**Comment by jtv** [comment]
Yes, it's documented.  The hard part is dealing with different encodings.  For example, when you see a quote in that text, it _could_ be a quote, or it _could_ be just one byte in a completely different Japanese character.

**Comment by gzliudan** [comment]
We can only support utf8 encoding and refuse input when a quote is not quote.

**Comment by gzliudan** [comment]
BTW, does libpqxx support array data type of PostgreSQL ?

**Comment by jtv** [comment]
Yes, you can convert a `std::vector` or `std::array` directly to a string in the normal way.

The other direction is more complicated, but it is supported: see the `array_parser` class.

**Comment by gzliudan** [comment]
Do you meam: libpqxx can use array_parser convert std::vector to array of postgresql composite data type automatically ?  Should I write string_traits::to_buf function for composite data type, such as (‘StringOfFiled1’,‘StringOfFiled2’,‘StringOfFiled3') format string ?

> Yes, you can convert a `std::vector` or `std::array` directly to a string in the normal way.
> 
> The other direction is more complicated, but it is supported: see the `array_parser` class.

**Comment by gzliudan** [comment]
Since psql can print composite data type in text format when we run select command in console, I believe there is a way to package the whole struct automatically when each field's string_traits is provied.  By use each member field's from_string and to_buf functions, maybe we don't need consider encodings. Only consider format of composite data type, such as single 
 and double quotation mark, arrays. And maybe we need write a function to tell libpqxx handles which fields.

> Yes, it's documented. The hard part is dealing with different encodings. For example, when you see a quote in that text, it _could_ be a quote, or it _could_ be just one byte in a completely different Japanese character.

**Comment by jtv** [comment]
For now, you'll have to write a full `string_traits` specialisation for your type, yes.  But I'm making first steps towards building in more support.  It could become a relatively simple "parse this string and put the values into these fields."

Of course you can use `from_string` and `to_buf` and so on on the element types, yes.  But encodings are important in the code that _looks for the end of a field,_ before you can even do the encoding.  Because that code will have to look for a closing quote, or a comma.  And in some encodings you can have a byte with the same value that an ASCII quote or comma would have, except it's not a character but _just one part of a multibyte character._

I have released features in the past that only work for encodings where this does not happen.  But of course I'd prefer to do it right.  This stuff can be hard to retrofit later.

**Comment by gzliudan** [comment]
I'm work on a project which has many new basic data type and composite data type, all types are ASCII encoding. If there is a feature supports define string_traits for composite data type and array automatically, it will save much time greatly and reduce code errors.

**Comment by jtv** [comment]
Right now I'm thinking along the lines of a function that parses an SQL composite-type value into a `std::tuple`.  But there may be better ideas once I play with it for a bit.  Right now the weather's a little hot for that though!

**Comment by gzliudan** [comment]
std::tuple is not bad. How about use reflect, such as: https://github.com/EOSIO/fc/blob/master/include/fc/reflect/reflect.hpp ?

**Comment by jtv** [comment]
Unlikely.  I'd rather not add dependencies, but also, I'd need better documentation to be sure that I understood the library correctly.

**Comment by jtv** [comment]
@gzliudan I just pushed experimental support for parsing the string representation of a value of a composite type into a series of C++ variables.  See current `master`, in `include/pqxx/composite.hxx`.  (You would include it in your code as `<pqxx/composite>`.)  Could you have a look, and see if it suits your needs?

Once we're happy with how this works, I can build it into `pqxx::field` as well, which will then automatically pass the right encoding group.

And separately from that, I imagine it would be nice to have a way to convert a C++ value to a composite-type string representation as well.

**Comment by gzliudan** [comment]
OK, I will test it this week. Is there any new document?

**Comment by jtv** [comment]
Nested arrays are already supported.  I haven't figured out yet how nested composite types are represented.

**Comment by gzliudan** [comment]
Please refer to https://www.postgresql.org/docs/12/rowtypes.html#ROWTYPES-IO-SYNTAX

**Comment by jtv** [comment]
Of course I did.  If you see something that describes nesting of composite types, please quote that specific part.

**Comment by gzliudan** [comment]
We can use ARRAY and ROW construct some nested composite types, then use select command print it in psql to check the text format of output string. Like this article:  https://stackoverflow.com/questions/7363516/how-to-formulate-an-array-literal-of-a-composite-type-containing-arrays

**Comment by jtv** [comment]
In that case the nesting is just not any kind of special case.  Should work as-is.

**Comment by gzliudan** [comment]
Here's an nested composite type example:
```sql
CREATE TYPE key_weight AS 
(
    weight int2,
    key    text
);


CREATE TYPE authority AS 
(
    threshold int4,
    keys      key_weight[]
);

CREATE TYPE producer AS 
(
    name text,
    auth authority[]
);

CREATE TABLE schedules
(
    id serial PRIMARY KEY,
    version   int4 NOT NULL,
    producers producer[] NOT NULL DEFAULT '{}'
);
```

**Comment by jtv** [comment]
Thanks.  I should incorporate this into a test.

I had some code for converting composite-type values _to_ strings sketched out, but it'll need some more work.  The idea is that you'll say "here are my fields, here's the buffer, go convert."  It would be convenient for use in writing your own `to_buf()` etc.

**Comment by jtv** [comment]
Barring any catastrophic bugs or great new ideas, I intend to release 7.2 soon, and I'll be closing this bug as well.  @KayEss, if you've got anything to add on the naming, this is your chance.  :-)

**Comment by gzliudan** [comment]
I have no objection to closing this issus. Thank you very much.

**Comment by KayEss** [comment]
Given the Postgres term for this is "composite" it seems a little awkward to use that on the C++ side too. Wouldn't something like `to_structure` or `to_fields` or even `to_args` be better? I admit I can't think of a really good alternative, but I do dislike having something called `to_composite` not create a Postgres composite. Maybe `to_values`?

**Comment by jtv** [comment]
@KayEss okay... how about `into_args` then?  It's nicely consistent with my `into<TYPE>(ref)` nomenclature.

Of course at some point I'll be wanting to have something very similar on `pqxx::row`.

**Comment by jtv** [comment]
Actually, I now see that I did not call those functions `into` after all!  Boy, it's been a while since I worked with the non-const-reference version of `to()`.  Completely forgot what it looked like.

Next proposal: `composite_to()`.  Same word, but it's on the right side of the equation.  Expresses the expectation that _the SQL side_ is a composite.

**Comment by gzliudan** [comment]
How about as_composite or as_tuple ?

**Comment by KayEss** [comment]
> `composite_to()`

Genius!

**Comment by jtv** [comment]
@gzliudan I don't think we could do `as_composite` because the existing `as()` functions name the C++ type, not the SQL type.  "Composite" is the SQL type, not the C++ type.  So it sort of gets the relationship between the two types the wrong way around.

I wouldn't want to use "tuple" here because (and this has caused me trouble before) "tuple" already means something on the C++ side and something different on the SQL side.

**Comment by jtv** [comment]
Support is in the latest release...  I'll close this ticket now, and then if there are problems with what I released, we can have a new one.
