### ISSUE TITLE
Can't find file 'pqxx/internal/transaction_focus.hxx' when compiling with std=c++17

### ISSUE THREAD

**Issue by andersbo87** [jtv/libpqxx#359]
Hello!

On my FreeBSD 12.1-RELEASE system, I'm trying to build your simple example code which can be found on your home page, under quick examples. I copied and pasted the code and saved it as pqxx-test.cpp.

However, when I run the compiler in C++17 "mode", I get the following error:

> In file included from pqxx-test.cpp:2:
In file included from /usr/local/include/pqxx/pqxx:5:
In file included from /usr/local/include/pqxx/cursor:6:
In file included from /usr/local/include/pqxx/cursor.hxx:23:
In file included from /usr/local/include/pqxx/transaction_base.hxx:36:
/usr/local/include/pqxx/stream_from.hxx:26:10: fatal error: 
      'pqxx/internal/transaction_focus.hxx' file not found
#include "pqxx/internal/transaction_focus.hxx"
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

The command I'm running, is the following:
`c++ pqxx-test.cpp -std=c++17 -I/usr/local/include -L/usr/local/lib -lpqxx -lpq`

**Comment by andersbo87** [comment]
I'm trying to build it with libpqxx version 7.1.0, btw.

**Comment by tt4g** [comment]
Did you install pqxx with autotools?
If so, this is known issue #320.

This problem already fixed in pqxx 7.1.1.

**Comment by jtv** [comment]
@andersbo87 did upgrading to a later libpqxx version solve it for you?  If so, we can close the ticket.

**Comment by andersbo87** [comment]
Not really sure how the FreeBSD Ports Collection installed libpqxx.

I downloaded libpqxx from your GitHub repository and now everything works as expected.

Thanks for your help. :)

**Comment by jtv** [comment]
Thanks for letting me know.  You may want to prod the port's owner (if there is one) to update to a more recent version.
