### ISSUE TITLE
Question about reuse pqxx::work

### ISSUE THREAD

**Issue by gzliudan** [jtv/libpqxx#367]
Sorry to trouble you again. Here‘s a question about reuse transaction: After commited a transaction, can this transaction object be used to execute a new query?  I saw a std::exception when I doing so: Could not execute query : transaction is already closed.

**Comment by jtv** [comment]
No, you can't re-use a transaction object.  The transaction object is not a thing that _manages_ a transaction; it _is_ the transaction.  And when the transaction is over, the transaction is over.

**Comment by gzliudan** [comment]
thanks.
