### ISSUE TITLE
Build fails in various points for different versions + cmake and configure build options

### ISSUE THREAD

**Issue by manujinda** [jtv/libpqxx#371]
OS: OSX Catalina
PostgreSQL: Installed via the installer from the official cite at /Library/PostgreSQL/12
libpqxx versions tried: 6.4.7 and 7.1.1

Tried both cmake and configure build options

**using configure option**
configure --disable-documentation --with-postgres-lib=/Library/PostgreSQL/12/lib --with-postgres-include=--with-postgres-include=/Library/PostgreSQL/12/include

**7.1.1: Build was successful but the tests fail**
dyld: Symbol not found: _PQencryptPasswordConn
  Referenced from: /Users/manujinda/Downloads/libpqxx/build/test/./runner
  Expected in: /usr/lib/libpq.5.dylib
 in /Users/manujinda/Downloads/libpqxx/build/test/./runner
/bin/sh: line 1: 30297 Abort trap: 6           ${dir}$tst

Tests seem to be still looking for libpq at its default location

**6.4.7: Build fail**
Can't find libpq-fe.h in --with-postgres-include=/Library/PostgreSQL/12/include.  Are you sure the libpq
headers are installed correctly?  They should be in the directory returned by
"pg_config --includedir" or "pkg-config libpq --cflags".

But libpq-fe.h is in the location where build is looking for.

**Using cmake option**

**7.1.1: make fails at 99%**
No rule to make target  8 `/Library/PostgreSQL/12/lib/libpq.lib', needed by `test/runner'
Makes works when -DSKIP\_BUILD\_TEST=on used for cmake, but cannot test before installing.

**6.4.6: make fails earlier**
No rule to make target `/Library/PostgreSQL/12/lib/libpq.lib', needed by   3 `src/libpqxx.dylib'

But libpq is there in the installed location.

**Comment by tt4g** [comment]
> dyld: Symbol not found: _PQencryptPasswordConn

`/usr/lib/libpq.5.dylib` is old version library.
Remove it.
See: https://stackoverflow.com/a/28618942

**Comment by manujinda** [comment]
Above solution is to make psycopg2 work. I used jgshurts's solution in the same post, which is a bit below:

pip3 uninstall psycopg2
pip3 install psycopg2-binary

This prevented me from having to reboot the computer in recovery mode and disabling SIP.

PostgreSQL works well with python, psycopg2 and sqlalchemy, while the default libpq that came with the OSX Catalina installation intact and they all can locate the newer libpq that got installed with PostgreSQL.

For C++, libpqxx is having trouble with locating the version of libpq installed with PostgreSQL.

**Comment by tt4g** [comment]
Perhaps psycopg2 has a different way of searching libpq.

To make sure CMake detects the library, build it with the CMake variables `PostgreSQL_LIBRARY`, `PostgreSQL_INCLUDE_DIR` and `PostgreSQL_TYPE_INCLUDE_DIR`.
Use these variables to force the path to the libpq and header files used by CMake.

Example:

```
cmake -G "<YOUR_GENERATOR>" CMAKE_BUILD_TYPE=Release \
-DPostgreSQL_LIBRARY="/Library/PostgreSQL/12/lib/libpq.lib" \
-DPostgreSQL_INCLUDE_DIR="/Library/PostgreSQL/12/include" \
-DPostgreSQL_TYPE_INCLUDE_DIR="/Library/PostgreSQL/12/include"

**Comment by manujinda** [comment]
I used an almost similar command before opening this issue

`cmake .. -DPostgreSQL_LIBRARY="/Library/PostgreSQL/12/lib/libpq.lib" \
-DPostgreSQL_INCLUDE_DIR="/Library/PostgreSQL/12/include" \
-DPostgreSQL_TYPE_INCLUDE_DIR="/Library/PostgreSQL/12/include"`

And cmake was able to locate the correct libpq.

-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
**-- Found PostgreSQL: /Library/PostgreSQL/12/lib/libpq.lib (found version "12.4")** 
-- Looking for poll
-- Looking for poll - found
-- Looking for PQencryptPasswordConn
-- Looking for PQencryptPasswordConn - found
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Generating config.h
-- Generating config.h - done
-- Configuring done
-- Generating done
-- Build files have been written to:

With version 7.1.1 of libpqxx, make goes all the way till 98% and spits this error:

[ 98%] Building CXX object test/CMakeFiles/runner.dir/unit/test_transactor.cxx.o
make[2]: *** No rule to make target `/Library/PostgreSQL/12/lib/libpq.lib', needed by `test/runner'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building CXX object test/CMakeFiles/runner.dir/unit/test_type_name.cxx.o
make[1]: *** [test/CMakeFiles/runner.dir/all] Error 2
make: *** [all] Error 2

With version 6.4.7, make fails at 37%

[ 37%] Building CXX object src/CMakeFiles/pqxx_shared.dir/util.cxx.o
make[2]: *** No rule to make target `/Library/PostgreSQL/12/lib/libpq.lib', needed by `src/libpqxx.dylib'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 38%] Building CXX object src/CMakeFiles/pqxx_shared.dir/version.cxx.o
[ 38%] Building CXX object src/CMakeFiles/pqxx_static.dir/version.cxx.o
make[1]: *** [src/CMakeFiles/pqxx_shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 39%] Linking CXX static library libpqxx.a
[ 39%] Built target pqxx_static
make: *** [all] Error 2

**Comment by jtv** [comment]
When you're building using `configure`, there should be error output in `config.log`.  Sometimes there's something helpful in there.  You can also pass to `configure` options like `--with-postgres-include=<directory>` and `--with-postgres-lib=<directory>` to specify exactly where the libpq header and library are.  You can also enable or disable the static and dynamic builds independently, using `--disable-shared`, `--enable-shared`, `--disable-static`, and `enable-static`.

Assuming `/Library/PostgreSQL/12/lib/libpq.lib` exists, maybe you could check that it's a valid library, and not (for example) a dangling symlink?

**Comment by tt4g** [comment]
I was referring to the make error message, so I may have used the wrong library extension.
If change `libpq.lib` to `libpq.dylib`, does it still fail to compile?

```bash
cmake .. -DPostgreSQL_LIBRARY="/Library/PostgreSQL/12/lib/libpq.dylib" \
-DPostgreSQL_INCLUDE_DIR="/Library/PostgreSQL/12/include" \
-DPostgreSQL_TYPE_INCLUDE_DIR="/Library/PostgreSQL/12/include"
```

**Comment by jtv** [comment]
Not a lot of activity here now...  Would anyone mind if I closed the ticket?  I believe one or two problems were solved at least, so if there's still a problem, perhaps it'd be best handled as a fresh issue.

**Comment by jtv** [comment]
OK, I'll close this one then.

**Comment by ronytigo** [comment]
why not updating the BUILDING-cmake.md file?

**Comment by ronytigo** [comment]
For me, `sudo apt-get install postgresql-server-dev-all` fixed it.
