### ISSUE TITLE
stream insert with unique key

### ISSUE THREAD

**Issue by teathinker** [jtv/libpqxx#372]
Hi, I uses stream_to to insert data into a table with unique key. It works nicely unless there is a duplicate key which will blow up the whole stream with exception: `ERROR:  duplicate key value violates unique constraint "XXXXXX"`.

I am using Postgres 12. There is upsert and some other options which requires modifying sql. I am not sure how to do it with stream_to. I also tried to use rule and it worked with insert query but not stream_to.

Is there any way to do UPDATE or IGNORE on duplicates with stream_to?

Thanks

**Comment by tt4g** [comment]
Wouldn't your problem be solved by UPSERT?
I don't know exactly what your problem is, as no SQL and snippets are provided.

Does the following SQL execution result solve your problem?

```sql
CREATE TABLE foo (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

INSERT INTO foo VALUES(1, 'foo');
--- UPSERT DO NOTHING
INSERT INTO foo VALUES(1, 'FOO')
  ON CONFLICT (id) DO NOTHING;

INSERT INTO foo VALUES(2, 'bar');
--- UPSERT DO UPDATE
INSERT INTO foo VALUES(2, 'foo')
  ON CONFLICT (id) DO UPDATE
  SET name = 'BAR';

SELECT * FROM foo;

---  id | name |
--- ----+------+
---   1 |  foo |
---   2 |  BAR |

```

Try on [Fiddle](https://www.db-fiddle.com/f/uA2v2zKfKiHMXJKqfYUjsH/1).

**Comment by jtv** [comment]
I can't think of any way to do this directly using `stream_from`, no.

If you really have to have an ID that is assigned from the client side, one thing you could do is:
 1. Temporarily suspend constraint checking for the duration of the transaction.
 2. Insert your data.
 3. Eliminate any duplicates.
 4. Re-enable constraint checking and commit.

That leaves the problem of "when I find a duplicate, how do I know which version I should delete?"  That depends on your schema...  For instance, there may be a server-assigned ID column, or some other field by which you could tell which is the "old" version of the row and which is the "new" one.

**Comment by teathinker** [comment]
Thanks. I found the other option is to just do bulk insert with upsert condition. It has good performance too.

**Comment by teathinker** [comment]
> Wouldn't your problem be solved by UPSERT?
> I don't know exactly what your problem is, as no SQL and snippets are provided.
> 
> Does the following SQL execution result solve your problem?
> 
> ```sql
> CREATE TABLE foo (
>   id INTEGER PRIMARY KEY,
>   name TEXT NOT NULL
> );
> 
> INSERT INTO foo VALUES(1, 'foo');
> --- UPSERT DO NOTHING
> INSERT INTO foo VALUES(1, 'FOO')
>   ON CONFLICT (id) DO NOTHING;
> 
> INSERT INTO foo VALUES(2, 'bar');
> --- UPSERT DO UPDATE
> INSERT INTO foo VALUES(2, 'foo')
>   ON CONFLICT (id) DO UPDATE
>   SET name = 'BAR';
> 
> SELECT * FROM foo;
> 
> ---  id | name |
> --- ----+------+
> ---   1 |  foo |
> ---   2 |  BAR |
> ```
> 
> Try on [Fiddle](https://www.db-fiddle.com/f/uA2v2zKfKiHMXJKqfYUjsH/1).

Yes I originally thought it would be too slow but now I tested with bulk insert it's good:) Thanks.

**Comment by jtv** [comment]
Alright, I'll close the ticket then.
