### ISSUE TITLE
bytea data accessing examples?

### ISSUE THREAD

**Issue by ReverseControl** [jtv/libpqxx#374]
I have a postgresql C extension that takes in a bytea type and returns a bytea type. I was able to figure out how to send my bytea data in a query, but when I read it I get something unexpected.

Simplest example of my extension:

```
#include "postgres.h"
#include "fmgr.h"

PG_MODULE_MAGIC;

PG_FUNCTION_INFO_V1(simple_func);

Datum simple_func(PG_FUNCTION_ARGS) {
    bytea *new_state = (bytea *) palloc(128 + VARHDRSZ);
    memset(new_state, 0, 128 + VARHDRSZ);
    SET_VARSIZE(new_state, 128 + VARHDRSZ);

    PG_RETURN_BYTEA_P(new_state);
}
```

Installation statement:

```

CREATE OR REPLACE FUNCTION agg_simple_func( state bytea, arg1 bytea)
RETURNS bytea
AS '$libdir/agg_simple_func'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE AGGREGATE simple_func( arg1 bytea)  
(
    sfunc = agg_simple_func,
    stype = bytea,
    initcond = "\xFFFF" 
);
```

Client side libpqxx:
```

std::basic_string< std::byte > buffer;

pqxx::connection c{"postgresql://user:simplepassword@localhost/contrib_regression"};
pqxx::work w(c);
c.prepare( "simple_func", "SELECT simple_func( $1 )  FROM table" );
pqxx::result r = w.exec_prepared( "simple_func", buffer );

for (auto row: r){ 
        cout << "  Result Size: " << row[ "simple_func" ].size() << endl;
        cout << "Raw Result Data: ";
        for( int jj=0; jj < row[ "simple_func" ].size(); jj++ ) printf( "%02" PRIx8,   (uint8_t) row[ "simple_func" ].c_str()[jj] )  ;
        cout << endl;
}
```

I expect an array of zeroes as my response, instead I get:

```
Result Size: 258
Raw Result Data: 5c783030303030303030303030303030...
```

Where the `30` pattern repeats. This is a bytea type, so I expect to see zeroes everywhere, not the ASCII decoded "0" to 0x30.

Is this a bug in parsing? Also, the first few bytes should be zero as well.

**Comment by jtv** [comment]
It's quite possible that something goes wrong; I only just introduced the `std::byte` support.  There may be teething problems.

There's a lot of stuff in your code that I don't recognise, such as `PRIx8`, and I haven't written any C extensions etc.  So I'm sort of groping around in the dark.

But one thing jumps out at me: you're going through the field's `c_str()`, but I'm not sure that you can do that with binary data.  It's meant for text fields.

What happens if you read the field as binary?

    row[ "simple_func" ].as<std::basic_string<std::byte>>()

That _should_ return a `std::basic_string<std::byte>` containing your BYTEA value.

**Comment by ReverseControl** [comment]
Let me try that. PRIx8 is from C for the printf function..it just tells printf that the type is printing is a uint8_t and to print it in hex. (http://www.cplusplus.com/reference/cinttypes/)

**Comment by ReverseControl** [comment]
That is beautiful....it prints 258 zeroes, which is what I expect: "00" for every byte and there are 128 bytes. Okay, that does the right thing.


Could you please include an example of how to use bytea in the official documentation? It took me a while to figure out how to input bytea data into a query and how to retrieve it. Adding something to the doxygen documentation might also be quite helpful for future users.

**Comment by jtv** [comment]
My apologies for the incomplete documentation.  I'm committing a fix right now.  If you still see a problem, feel free to start a new ticket.

**Comment by mubinui** [comment]
Is it possible to convert bytea to (uint8_t , size_t)

**Comment by jtv** [comment]
You can convert to `std::basic_string<std::bytea>` and then I think it would be valid to cast its data pointer to `uint8_t *`.
