### ISSUE TITLE
Missing features showing squiggly lines in IDE. (v7.2)

### ISSUE THREAD

**Issue by BFamzz** [jtv/libpqxx#376]
I upgraded from v6.4 to 7.2 but I can't seem to access some functions/classes I don't know if they are deprecated but I looked through the source files and found the features.

Operating System: Window 10 (WSL 2)
WSL - Ubuntu 20.04
Editor: Visual Studio Code via WSL

Kindly see error messages below.

![image](https://user-images.githubusercontent.com/38426051/95912505-ca97c200-0d9a-11eb-9689-ee1f90947b16.png)
![image](https://user-images.githubusercontent.com/38426051/95913171-be603480-0d9b-11eb-92f5-0b5c0d0e8155.png)
![image](https://user-images.githubusercontent.com/38426051/95912802-37ab5780-0d9b-11eb-90b0-1f766df9c766.png)

I don't know why it is giving such errors.

I installed the library correctly and I have all the include files
![image](https://user-images.githubusercontent.com/38426051/95913051-92dd4a00-0d9b-11eb-9664-abe2a047263c.png)

How can I fix this errors please?

**Comment by tt4g** [comment]
`pqxx::work` and `pqxx::nontransaction` are defined in pqxx 7.2.0.

It could be a problem with the Visual Studio Code language support.
Try press `F1` or `Ctrl` + `Shift` + `P` and input `>C/C++ Reset IntelliSense Database`.

**Comment by BFamzz** [comment]
I have found the problem. The compiler was set to c++14 but I changed it to c++17.

Thanks.

**Comment by jtv** [comment]
I love it when bug reports go away all by themselves.  :-)
