### ISSUE TITLE
serialization_failure and deadlock_detected exceptions created with wrong parameters

### ISSUE THREAD

**Issue by PetrSilar** [jtv/libpqxx#378]
Hello,
IMO exceptions of classes `serialization_failure` and `deadlock_detected` are incorrectly created in `result::ThrowSQLError()`. Value of `code` goes to `query` parameter of a constructor. Obviously, such exception has an empty result of `sqlstate()` method.
Also, code of exceptions class hierarchy may benefit from using of _inheriting constructors_, making code shorter.

**Comment by jtv** [comment]
Oops, thanks!  And I found another case too.  Hopefully no great problem to anyone.  Fix & release coming up.
