### ISSUE TITLE
unresolved external symbol while building 

### ISSUE THREAD

**Issue by pasyg** [jtv/libpqxx#379]
Hello, I'm trying to get libpqxx running, but I encounter some problems building it. I use Visual Studio 2017, CMake 3.18.4 and PostgreSQL 13. I got the libpq.dll and libpq.lib from the PostgreSQL lib folder and downloaded libpqxx source from here.

When I create the VS solution I get the messages "Poll not found" and "PQencryptPasswordConn not found", the build gets created though, so I am not sure if the problem lies in there.

I then opened the Project in Visual Studio and added the includes and libraries and get around 100 errors, 70 unresolved external symbols, 13 'constexpr is not valid here' and 13 'E1449 explicit specialization of variable must precede its first use'.

The unresolved external symbols happen in the runner project (pqxx.lib), the others in the pqxx project (conversions.hxx)
. 
`Fehler	LNK2001	Nicht aufgelöstes externes Symbol "_PQfreemem".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(binarystring.obj)	1	
Fehler	LNK2001	Nicht aufgelöstes externes Symbol "_PQunescapeBytea".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(binarystring.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_close" in Funktion ""private: void __thiscall pqxx::largeobjectaccess::close(void)" (?close@largeobjectaccess@pqxx@@AAEXXZ)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_creat" in Funktion ""public: __thiscall pqxx::largeobject::largeobject(class pqxx::dbtransaction &)" (??0largeobject@pqxx@@QAE@AAVdbtransaction@1@@Z)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_import" in Funktion ""public: __thiscall pqxx::largeobject::largeobject(class pqxx::dbtransaction &,class std::basic_string_view<char,struct std::char_traits<char> >)" (??0largeobject@pqxx@@QAE@AAVdbtransaction@1@V?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_export" in Funktion ""public: void __thiscall pqxx::largeobject::to_file(class pqxx::dbtransaction &,class std::basic_string_view<char,struct std::char_traits<char> >)const " (?to_file@largeobject@pqxx@@QBEXAAVdbtransaction@2@V?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_lseek64" in Funktion ""public: __int64 __thiscall pqxx::largeobjectaccess::cseek(__int64,int)" (?cseek@largeobjectaccess@pqxx@@QAE_J_JH@Z)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_open" in Funktion ""private: void __thiscall pqxx::largeobjectaccess::open(int)" (?open@largeobjectaccess@pqxx@@AAEXH@Z)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_read" in Funktion ""public: __int64 __thiscall pqxx::largeobjectaccess::cread(char * const,unsigned int)" (?cread@largeobjectaccess@pqxx@@QAE_JQADI@Z)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_tell64" in Funktion ""public: __int64 __thiscall pqxx::largeobjectaccess::ctell(void)const " (?ctell@largeobjectaccess@pqxx@@QBE_JXZ)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_unlink" in Funktion ""public: void __thiscall pqxx::largeobject::remove(class pqxx::dbtransaction &)const " (?remove@largeobject@pqxx@@QBEXAAVdbtransaction@2@@Z)".	runner	C:\Users\xxx\Documents\Programmieren\C++\Libraries\build\test\pqxx.lib(largeobject.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_lo_write" in Funktion ""public: __int64 __thiscall 
`

**Comment by tt4g** [comment]
> When I create the VS solution I get the messages "Poll not found" and "PQencryptPasswordConn not found", the build gets created though, so I am not sure if the problem lies in there.

Maybe it's a problem with the Visual Studio IDE.

> The unresolved external symbols happen in the runner project (pqxx.lib), the others in the pqxx project (conversions.hxx)

Has the project been configured so that libpq is linked after pqxx?

**Comment by pasyg** [comment]
> Maybe it's a problem with the Visual Studio IDE.

I ran the CMake commands over the command line, not in the Visual Studio IDE, just with the Visual Studio Compiler.

> Has the project been configured so that libpq is linked after pqxx?

I'm not sure if and how I can change the linking order in Visual Studio and used the CMakeLists from the source code, I'm not really good with CMake but I'd assume this would give the Visual Studio solution the correct linking order then?

**Comment by tt4g** [comment]
If you use the `find_package()` command, CMake should be able to adjust the link order of the libraries.
If you are adding the library in any other way, you will adjust the link order yourself.

Can you provide a `CMakeLists.txt` sample?

**Comment by pasyg** [comment]
Sorry, I'm not sure which CMakeLists you mean, I used the one from this source code, then ran 
`cmake -S libpqxx-master -B build -DCMAKE_INSTALL_PREFIX="libpqxx"` to create the Visual Studio solution and included the library paths via the properties in the Visual Studio project, after that I tried to build it in the command line with
`cmake --build build --target INSTALL`
and tried to build it in Visual Studio, both giving me the unresolved external symbols, I didn't use a 'CMakeLists.txt' for that linking.

**Comment by tt4g** [comment]
When you run the `cmake -S libpqxx-master -B build -DCMAKE_INSTALL_PREFIX="libpqxx"` command, CMake should detect the libpq and add it to your Visual Studio project.
CMake does not know that you have changed the generated Visual Studio project, so building with `cmake --build build --target INSTALL` may fail due to different configuration information.

You can tell the path of libpq to CMake with an additional argument `PostgreSQL_ROOT` when executing the `cmake` command.

```bash
$ cmake -S libpqxx-master -B build -DCMAKE_INSTALL_PREFIX="libpqxx" -DPostgreSQL_ROOT:PATH="<PATH_TO_LIBPQ>"
$ cmake --build build --target INSTALL
```

`<PATH_TO_LIBPQ>` is your libpq path, and it should have an `include` or `bin` directory directly underneath it.

**Comment by pasyg** [comment]
Hey thanks a lot for your help, I just downloaded an older version of PostgreSQL to get a 32-Bit version and used the .dll and .lib from there. Now it works.

**Comment by jtv** [comment]
By the way, the missing `PQencryptPasswordConn` suggests that you may have an older libpq binary somewhere.

Glad this got resolved...  And thanks @tt4g once again!
