### ISSUE TITLE
Is there a way to get the result of all the queries inserted in the libpqxx pipeline at once?

### ISSUE THREAD

**Issue by rptprl123** [jtv/libpqxx#380]
I throw a large number of queries into the pipeline.
(This is to get the operation result through Cube Extension with [SELECT] statement.)

Is there a way to get the result of all the queries inserted in the libpqxx pipeline at once?

The only way I've seen is to get one by one through each query ID through the retrieve() function.
But I guess there will be a way to get the whole result in the pipeline at once.

That way can't be found in official documentation.

The pqxx version I use is 7.2.0.

Is there a way to extract the results of the pipeline at once?

**Comment by jtv** [comment]
No, sorry — you'll have to loop over the results to get them all.

If your queries are basically the same, just getting different rows, then perhaps `stream_from` does what you need?

**Comment by jtv** [comment]
@rptprl123 does that answer your question?  I so, I'll close this ticket.  Feel free to open a new one if you have more questions, of course.

**Comment by jtv** [comment]
I'll just close it then.
