### ISSUE TITLE
Unresolved external symbol "__imp__WSAPoll@12"

### ISSUE THREAD

**Issue by pasyg** [jtv/libpqxx#381]
Hey, sorry to bother again, I encountered another problem that I don't know what to do about. I built my library and the header includes all work just fine. 
`LNK2019	Unresolved external symbol "__imp__WSAPoll@12" in function "__catch$?remove_receiver@connection@pqxx@@AAEXPAVnotification_receiver@2@@Z$0".	C:\...\pqxx.lib(connection.obj)	
`
When I built the library I got the message that Poll and PQencryptPasswordConn were not found, but the build went through without any error messages. Since there is 'Poll' in the symbol name, I was thinking maybe that missing Poll is the problem? Or could it be something else?

**Comment by tt4g** [comment]
It's odd that the build succeeds when the necessary symbols are missing.
Did you get an error message during the build?

> When I built the library I got the message that Poll and PQencryptPasswordConn were not found ...

As [previously commented](https://github.com/jtv/libpqxx/issues/379#issuecomment-715942218) by @jtv, there is no `PQencryptPasswordConn` in the old libpq.
What version of libpq are you using?

**Comment by pasyg** [comment]
I did not get an error message, it was just the display "Looking for Poll -not found" "Looking for PQencryptPasswordConn - not found", the build and Installation went without any error messages though.

I use the libpq.lib from the PostgreSQL 10 32-bit version, downloaded the newest version of it a few days ago (I need a 32 bit version, since Visual Studio doesn't support 64-bit, that's why PostgreSQL 10). Are those outdated? Where do I get updated libpq.lib versions?

**Comment by jtv** [comment]
Aren't those messages just from CMake figuring out _whether you have_ these functions?  They're completely optional to libpqxx.

PostgreSQL 10 is not completely current, but it'll probably do just fine.

**Comment by pasyg** [comment]
Yeah that's what I was thinking, but the error message made it look like it coule be because of the missing Poll, so that was my first and so far my only idea where that is coming from.

**Comment by jtv** [comment]
I think the actual _error_ message means that you're not linking to ws2_32.lib (which must come _after_ linking to libpqxx and libpq in the list of libraries to link).

Any chance this is something like a "Debug vs. Release build" mismatch?

**Comment by pasyg** [comment]
Yup, after linking the ws2_32.lib that error is gone. Had to add two more .dlls now I'm only left with a 0x000007b error, looks like I have 64-but versions of my .dlls somewhere that I have to change, but I'll figure that one out, thanks a lot guys!

**Comment by jtv** [comment]
Good news.  I'll close the ticket.
