### ISSUE TITLE
dynamic parameters of differing types

### ISSUE THREAD

**Issue by wryan67** [jtv/libpqxx#382]
In version 6.x, we could build out prepared query argument lists using the prepared/invocation methods.  In 7.2, those methods have been removed, but I'm not seeing any examples of how to build parameter lists dynamically (when said parameters are of differing types).  Can this be done in 7.2?

example from 6.x:    

        for (auto e: preparedStatements) {
            conn->prepare(e.first, e.second);
        }

Where "preparedStatements" is an unordered_map containing prepared statements, some built manually and some built programatically like the below insert statement.  Note: children is a vector containing various object types.  An example is shown further down in this post.

    string xTable::getInsertStatement() {
        StringBuilder str;

        str.appendf("insert into %s (",label.c_str());
        for (auto column: children) {
            str.append(column->name());
            str.append(",");
        }   str.undo();

        str.append(") values (");
        for (unsigned long i=1;i<=children.size();++i) {
            str.appendf("$%d", i);
            str.append(",");
        }   str.undo();

        str.append(")");

        return str.toString();
    }

Then later, during transaction processing, the prepared statement is executed like so:

    void xTable::insert(pqxx::work *txn) {

        auto inv = txn->prepared(tablename+"._insert");

        for (auto column: children) {
            if (column->isNull()) {
                inv();
            } else {
                switch (column->getType()) {
                
                case StringType: {
                        xString *str = (xString*) column;
                        inv(str->value());
                    break;
                }
                case IntegerType: {
                        xInteger *value = (xInteger*) column;
                        inv(value->value());
                    break;
                }
                case LongType: {
                        xLong *value = (xLong*) column;
                        inv(value->value());
                    break;
                }
                case TimestampType: {
                        xTimestamp *value = (xTimestamp*) column;
                        inv(value->value());
                    break;
                }
                case BooleanType: {
                        xBoolean *value = (xBoolean*) column;
                        inv(value->value());
                    break;
                }
                
                default:
                    throw RuntimeException("xTable<%s>: type %s is unaccounted for in the insert switch", 
                                            name().c_str(), xTypeNames[column->getType()]);
                }
            }
        }

        auto rs = inv.exec();
    }

And lastly, how a table is represented in c++.  Note: all of the xTypes are our custom base types for primitives and arrays.

	//transaction_table.h

	#pragma once
	#include "xvars.h"
	using namespace std;

	namespace com::service::tables {

		class transaction_tb:public xTable {
		private:
			static unordered_map<string,string> preparedStatements;

		public:
			transaction_tb();
			xTable *newInstance();
			static const string tablename;
			unordered_map<string,string>& getPreparedStatements();

	// transient variables
			bool upsert=false;

	// table columns 
	//              data_type           c++variable{"postgresql_column_name"}
			xLong               TRANSACTION_ID{"transaction_id"};
			xTimestamp          TRANSACTION_TIME{"transaction_time"};
			xString             EXTERNAL_ID{"external_id"};
			xInteger            TYPE_CD{"type_cd"};
			xInteger            EMAIL{"email_address"};
			xBoolean            OPTION1{"option1"};
		};
	}

And the corresponding .cpp:

	// "transaction_tb.cpp"
	#include "transaction_tb.h"

	namespace com::service::tables {

	/*
	 * Static vars
	 */

		const string transaction_tb::tablename="transaction_tb";

		unordered_map<string,string> idg_config::preparedStatements = {
			{"getAll",          "select * from "+tablename},
			{"getUsingId",      "select * from "+tablename+" where transaction_id = $1"}
		};

		transaction_tb::transaction_tb(): xTable(tablename) {

			children.push_back(&TRANSACTION_ID);
			children.push_back(&TRANSACTION_TIME);
			children.push_back(&EXTERNAL_ID);
			children.push_back(&TYPE_CD);
			children.push_back(&EMAIL);
			children.push_back(&OPTION1);

		}

		unordered_map<string,string>& transaction_tb::getPreparedStatements() {
			return transaction_tb::preparedStatements;
		}

		xTable* transaction_tb::newInstance() {
			return new transaction_tb();
		}

	}

**Comment by jtv** [comment]
No, I'm afraid there's no way to do this now.  I didn't think anybody would want it...

This may be a case for —heaven help us— a _builder_ a bit like what we had before.  But I wouldn't want it to be the default way of building the parameter list.

Or perhaps we could do something with `std::variant`?

**Comment by wryan67** [comment]
I agree, there needs to be multiple ways of creating parameter lists, but without some sort of building tool, it seems you have to hard code everything, right?  If you take a look at the above classes, you'll see that if I want to add or remove a column, all I have to do is define the column in the header file, and then add it to the corresponding children list in the .cpp.  The prepared statement will then automatically adjust, and if we could bring back the builder tool, then the execution could automatically adjust as well, like it used to.    (and if c++ would support reflection, then I'd only have to make one change).  Maybe I could build a pre-processor or something, but I really hate those things.

**Comment by jtv** [comment]
Oh _wait..._  @wryan67!  Am I forgetting a feature we already have?  I now remember that you can just pass a `pqxx::dynamic_params` as any of the arguments, and its contents will expand in-place.

Does that solve your problem?  A `dynamic_params` basically means "insert all of these parameters here."

**Comment by wryan67** [comment]
Possibly, but I don’t see that dynamic_params listed on the 7.2.1 documentation, and make_dynamic_params expects all the arguments to be of the same type.  Could you provide an example for how to use dynamic_params with differing type of variables?   
For reference, this is the page I was using to view the class members:
https://libpqxx.readthedocs.io/en/stable/annotated.html

**Comment by jtv** [comment]
It all depends on the type of variability you really need.  For instance, let's say you've got a statement that takes these parameters:
 1. A string.
 2. An _optional_ integer, depending on some run-time condition.
 3. A floating-point number.

You could do that by passing a string; a `dynamic_params` optionally containing an integer; and a floating-point number.

If the middle parameter should be _either an integer or a string,_ you could pass two `dynamic_params` there; in one scenario the first one holds an int and the second is empty, or in the other scenario the first is empty and the second holds a string.

And if all else fails, I guess you could just convert your parameters to strings.

**Comment by wryan67** [comment]
My situation is that I have 1240 columns on a table, varying in types between strings and integers (of varying sizes).  There is also one column that is an integer array.  During a batch load, some, but not all of the variables will be populated.  Each batch will have a different set of variables.   We will not know which variables will be populated until run-time.  A batch of records may be hundreds of thousands of records, so we want to use a prepared statement to insert rows into the table. 
 The prepared statement will be built dynamically based on the batch control card.  So when we're in the loop that is executing the prepared statement, the parameters need to be defined dynamically as well.   

I.E.  I do **_not_** want to write out manually a txn->exec_prepared( with 1240 parameters! );

**Comment by wryan67** [comment]
I've been looking at the class dynamic_params found in statement_parameters.hxx. It looks to be pretty much what we need, but this is an internal class and as such, I can't use it in my code.  The class has all the add_field() methods setup, so it looks very promising.  Am I on the right track here, or is there something else that would work?

**Comment by jtv** [comment]
The class itself is in the `internal` namespace, but you can use `pqxx::prepare::make_dynamic_params` to produce an instance.

Alternatively, see if you can just convert your parameters to strings.

**Comment by jtv** [comment]
Oh, there's another way, which may even be more efficient: use a `stream_to`, and call its `write_row()` function with a `std::tuple` argument.

**Comment by Zeks** [comment]
_I didn't think anybody would want it..._

.. there's a very real use case for it: compatibility with all the query engines that allow creating parameter bindings 1 by 1. Aka `X.bindValue(name, value)`

Like, for example, I will soon need to make sure that my app supports both sqlite via QSqlQuery and postgres via libpqxx, all of the code was written with the above syntax in mind, so to avoid making an explicit verion I definitely have a need of `pqxx::prepare::make_dynamic_params`

It's good to know this exists because I know of at least one person who doesn't and reimplemented this with a horrible 100 parameter `#define` switch statement.

**Comment by Zeks** [comment]
_call its write_row() function with a std::tuple argument._

I don't think that would work because there will need to be a tuple with 1240 parameter types, no?

**Comment by jtv** [comment]
Then I guess I'll have to revive a version of the old system, but modernised for C++17.  It'll be less efficient and convenient, so for your particular use-case of repeated inserts I would definitely still look at `stream_to`.  You can feed in each row as either a container or a tuple.

Internally, all arguments (except "binary data" ones) get sent across the wire in string form, so your best option right now would be to convert them all to strings yourself.  That goes for both prepared statements and `stream_to`.

**Comment by Zeks** [comment]
Is there a particular reason everything is converted to string before passing btw?

**Comment by jtv** [comment]
Yes, it's the only _documented_ format for passing data (apart from BYTEA data) back and forth between the client and postgres.

There is also a binary format, which in theory should be more efficient.  I've looked into it several times over libpqxx's history, but:
 * Not documented.
 * No guarantees that it'll remain stable.
 * Not necessarily portable, so lots of hard-to-test variability.
 * May require additional knowledge about the server version, server hardware, server OS etc.
 * Not necessarily as efficient as it sounds, e.g. numeric formats still seem to be variable-length and less compact than the string format.
 * Much harder to check for correctness and format mismatches.

So I keep arriving at "no, this is not as good an idea as it seemed."

**Comment by jtv** [comment]
Oh and did I mention `std::variant`?  In cases where a parameter can be one of a limited number of compile-time types depending on run-time conditions, you can pass a `std::variant`.  But it definitely won't solve your whole problem.

**Comment by Zeks** [comment]
In fact, I am already writing a variant vector wrapper for dynamic_params interface.

**Comment by wryan67** [comment]
I am going down the strings route.  I’m using a set of extended objects to store the data.  The extended objects were originally designed to be able to serialize/deserialize beans to/from JSON.  So modifying the serializing to strings for pqxx isn’t going to be difficult, then use make_dynamic_params to get them ready for use by exec_prepared().   BTW, is there a C++ equivalent term for JavaBeans and POJO?

**Comment by jtv** [comment]
IIRC there's no real equivalent, no.  There's stuff like POD objects (Plain Old Data), from which the POJO name was probably copied, but that's going back something like 20 years and not very relevant today.  But it's been a while since I had any real involvement with the Java standards.  :-)

To convert a value to its postgres string equivalent, use `pqxx::to_string(value)` (though not if it's null — there's no null `std::string` value).

Or if you really want to optimise it to the max, do it with just a single memory allocation:
 * Create a single `std::string buf` as a buffer.
 * Resize it to have room for all your values.
 * Call `pos_in_buf = pqxx::string_traits<TYPE>::into_buf(buf.data() + pos_in_buf, buf.data() + std;:size(buf), value)` for each of your values.  This puts the strings all in your one string.
 * Instead of passing `std::string` parameters to your statement, pass `std::string_view` objects referring to each of the values inside `buf`.
 * Just make sure never to allow `buf` to resize while you're doing this, or your pointers will be wrong.

**Comment by jtv** [comment]
And libpqxx 7.3 will probably have direct support for converting multiple values to strings at once, using a single `std::string` as a buffer and returning the "sub-strings" as `std::vector<std::string_view>`.

**Comment by wryan67** [comment]
Thanks for your help Jeroen, it is much appreciated!
