### ISSUE TITLE
zview does not accept const char *

### ISSUE THREAD

**Issue by egorpugin** [jtv/libpqxx#389]
I have the following simple code:
```
#include <pqxx/pqxx>

void f()
{
    pqxx::connection c("");
    pqxx::work txn(c);
    const char *s = "";
    txn.exec_prepared(s); // build error on msvc
}
```

Error:
```
1>1.cpp(10,8): error C2672: 'pqxx::transaction_base::exec_prepared': no matching overloaded function found
1>1.cpp(10,24): error C2440: 'initializing': cannot convert from 'const char *' to 'pqxx::zview'
1>1.cpp(10,24): message : Constructor for class 'pqxx::zview' is declared 'explicit'
1>1.cpp(10,24): error C2784: 'pqxx::zview::zview(const char (&)[size])': could not deduce template argument for 'const char (&)[size]' from 'const char *'
1>include\pqxx\zview.hxx(65): message : see declaration of 'pqxx::zview::zview'
```

**Comment by tt4g** [comment]
What your error message?

**Comment by egorpugin** [comment]
Added error into first message.

**Comment by egorpugin** [comment]
By the way, what's the advantage of `zview` over `std::string_view`?

**Comment by jtv** [comment]
Yeah, it's not perfect but I think it's pretty well documented.  :-)

In the latest versions you can write `zview` strings directly:

```cpp
    using pqxx::operator"" _zv;
```

and then...

```cpp
    auto foo = "bar" _zv";
```

**Comment by egorpugin** [comment]
Ok, but what about constchar*s?

**Comment by egorpugin** [comment]
Removing explicit here helps.
https://github.com/jtv/libpqxx/blob/master/include/pqxx/zview.hxx#L56

As I see zview is inherited from string_view, then it should accept constchar*s like string_view does. See ctor (4) https://en.cppreference.com/w/cpp/string/basic_string_view/basic_string_view.

On line 56 you have forwarding ctor, but with explicit it does not work for constchar*s.

**Comment by jtv** [comment]
Yes, I thought we'd changed that.  Hang on while I investigate.

**Comment by jtv** [comment]
Turns out we had added an implicit constructor _from `std::string`,_ not from `char const *`.

I'll add one.

**Comment by egorpugin** [comment]
Would you consider adding a test? I'm not insisting though. :)
Such small things are easy to change (break) and forget about it.

**Comment by jtv** [comment]
Yeah, I don't think it's worth it.  I know the test suite does exercise this one, because I got compile errors when I initially left out the `constexpr`.
