### ISSUE TITLE
README.md specifies incorrect link order

### ISSUE THREAD

**Issue by dpanzer** [jtv/libpqxx#39]
In the README it says `-lpq -lpqxx` whereas on the project's (old?) homepage [http://pqxx.org/development/libpqxx/](http://pqxx.org/development/libpqxx/) it correctly specifies the order as `-lpqxx -lpq` and notes that if you reverse the order you will get many linker errors. Until I found this I was pulling my hair out for a few hours!

**Comment by jtv** [comment]
Whoops — thanks for spotting that!
