### ISSUE TITLE
 warning: "STDC_HEADERS" redefined

### ISSUE THREAD

**Issue by MykolaLebid** [jtv/libpqxx#390]
Hi there! 

Thanks a lot for your cool lib:) 

I am compiling my c++ project with CMake, g++-10.2(current version) and your super lib as a sub-module of version 6.4.7. 
Life is good. But,  CMake probably wants to say that you have the same name preferences with g++ people: 

In file included from /root/workspace/libs/pqxx/include/pqxx/compiler-public.hxx:13,
                 from /root/workspace/libs/pqxx/include/pqxx/array.hxx:14,
                 from /root/workspace/libs/pqxx/include/pqxx/array:4,
                 from /root/workspace/libs/pqxx/include/pqxx/pqxx:2,
.... 

libs/pqxx/include/pqxx/config-public-compiler.h:69: warning: "STDC_HEADERS" redefined
69 | #define STDC_HEADERS
In file included from /opt/gcc-10_2_0/include/c++/10.2.0/cstddef:49,
                 from /opt/libboost/include/boost/config/compiler/gcc.hpp:165,
                 from /opt/libboost/include/boost/config.hpp:39,
                 from /opt/libboost/include/boost/iterator/iterator_facade.hpp:10,
                 from /root/workspace/libs/boost-enum/boost/enum/iterator.hpp:18,
.... 

include/c++/10.2.0/x86_64-linux-gnu/bits/c++config.h:1494: note: this is the location of the previous definition
 1494 | #define STDC_HEADERS 1.

Did I do something not right or you have to change name?

**Comment by tt4g** [comment]
`STDC_HEADERS` is defined by CMake.
if CMake variable `STDC_HEADERS` is defined, CMake replace `#cmakedefine` with `#define` in `config.h.in`.

Can you add CMake option `-DSTDC_HEADERS=ON`?

**Comment by tt4g** [comment]
Better Workaround: Edit this line: https://github.com/jtv/libpqxx/blob/e63674fec320624e0bea32e5e5b7b5ff2c6c269d/include/pqxx/config.h.in#L99-L101

```diff
+#ifndef STDC_HEADERS
/* Define to 1 if you have the ANSI C header files. */ 
#undef STDC_HEADERS
+#endif
```

**Comment by jtv** [comment]
Glad you like the library, @MykolaLebid!  @tt4g is the CMake expert here.  :-)

A bit silly that we still have that macro in this day and age...  When you're compiling C++17 nobody should be asking whether you have `stdio.h`.

In the autoconf build I minimise the number of macros and rename them with "PQXX" prefixes where possible.  Perhaps we should try to do the same thing in the CMake build.

**Comment by MykolaLebid** [comment]
Hi, @tt4g! I tried you suggestions: 
> Workaround: Can you add CMake option -DSTDC_HEADERS=OFF?
The situation is the same... 
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:1184:0: note: this is the location of the previous definition
 #define STDC_HEADERS 1 (not only for new one 10.2. I check it for for version 4.9 with C++11 settings for CMake)

> Better Workaround: Edit this line:
> libpqxx/include/pqxx/config.h.in

> +#ifndef STDC_HEADERS
> /* Define to 1 if you have the ANSI C header files. */ 
> #undef STDC_HEADERS
> +#endif

Thanks a lot for your help!!!

I suspect, It is name clash between g++ and Cmake-created config.h.

@jtv, you are absolutely right!

Thank you all!!!
