### ISSUE TITLE
\array-composite.hxx(236): error C2440: '<function-style-cast>': cannot convert from 'const _Elem' to 'std::string'

### ISSUE THREAD

**Issue by uwebenner** [jtv/libpqxx#391]
Hello there!
I'm having a problem building your simple example program, starting with version 7.2.0. I'm using Visual Studio 2017.
The line `pqxx::connection c{"postgresql://accounting@localhost/company"};` gives the following problem:
```
1>c:\development\libpqxx\bin\include\pqxx\internal\array-composite.hxx(236): error C2440: '<function-style-cast>': cannot convert from 'const _Elem' to 'std::string'
1>        with
1>        [
1>            _Elem=char
1>        ]
1>c:\development\libpqxx\bin\include\pqxx\internal\array-composite.hxx(236): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>Done building project "pqxxtest.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

Is there something I can do to fix this?

Thanks!

**Comment by tt4g** [comment]
This may be due to the compiler's type inference.
If you compile the following code, does it report an error?

```cpp
const char* con_str = "postgresql://accounting@localhost/company";
pqxx::connection c(conn_str);
```

**Comment by uwebenner** [comment]
It reports the same error.

**Comment by tt4g** [comment]
I can build the following code in Visual Studio 2019 with C++17 support enabled.

Can you build the following code?

```cpp
#include "pqxx/pqxx"

#include <iostream>

int main()
{
    pqxx::connection conn("hostaddr=127.0.0.1 port=5432");

    pqxx::work tx(conn);

    pqxx::row row = tx.exec1("SELECT 1");

    tx.commit();

    return 0;
}
```

**Comment by uwebenner** [comment]
Copy and pasted the code and can not build it. Still the same error. And I have tested it with /std:c++17 and /std:c++latest.
I could try installing and compiling it with Visual Studio 2019 later but I need it for work and am only allowed to use Visual Studio 2017.

**Comment by tt4g** [comment]
Very strange.
How did you install pqxx?

**Comment by uwebenner** [comment]
First `vcpkg install libpqxx` and as the error appeared went through the fun and joy building everything from source.
```
cmake .. ^
-A Win32 ^
-DPostgreSQL_TYPE_INCLUDE_DIR="C:\Development\postgres\install\include" ^
-DPostgreSQL_INCLUDE_DIR="C:\Development\postgres\src\include" ^
-DPostgreSQL_LIBRARY_DIR="C:\Development\postgres\install\lib" ^
-DPostgreSQL_LIBRARY="C:\Development\postgres\install\lib\libpq.lib" ^
-DPostgreSQL_ROOT="C:\Development\postgres\src"
cmake --build . --config Release --target -j 20
cmake --install . --prefix C:\Development\libpqxx\release
```
Since the error is the same and disappears when I use a version before 7.2.0 the error seams to be with Visual Studio 2017.

**Comment by tt4g** [comment]
`array-composite.hxx` is a header file that was added in 7.2.0.

I had linked pqxx 7.2.1 to build the above code. Are you able to try 7.2.1 ?

**Comment by uwebenner** [comment]
I have tried 7.2.1 and master.

**Comment by tt4g** [comment]
Hmmm, if the problem is not reproduced in Visual Studio 2019, then it might be a Visual Studio 2017 specific issue.
I'm sorry I can't help you.

**Comment by uwebenner** [comment]
You have helped enough. I will later test Visual Studio 2019, report back and if it works close the ticket.

Anyhow thank you for your time!

**Comment by jtv** [comment]
And I have very little to add...  The fact that line 236 is a closing brace makes it harder to figure out what's going on.

One thing I can say: I didn't think there are any function-style casts left in the libpqxx code.  So it's all very surprising.

**Comment by uwebenner** [comment]
Okay, it work's with Visual Studio 2019.

**Comment by jtv** [comment]
That's a relief!

**Comment by MMartin09** [comment]
I have the same problem. Is there a solution for Visual Studio 2017?

**Comment by uwebenner** [comment]
I've opened a ticket for Visual Studio, which you can follow here: https://developercommunity2.visualstudio.com/t/1286797

There is no solution as of yet.
