### ISSUE TITLE
Compatible with C++11 standard!!!

### ISSUE THREAD

**Issue by INotfound** [jtv/libpqxx#392]
Hope to choose the standard version of C++ through conditional compilation.
Thanks  :smile:

**Comment by KayEss** [comment]
What do you mean? Normally the standard in use is something that either is just the default for the compiler you're using or you choose through the compiler switches you use in the build. It's not something you can choose through conditional compilation

**Comment by jtv** [comment]
I'm sorry — current versions of libpqxx no longer support C++ versions older than C++17.  Supporting C++11 at this point would involve a massive effort, and produce slower code for everyone.  C++20 will be another massive leap forward, so I'm actually looking forward to making that leap fairly quickly.

If you're stuck on C++11, then I'm afraid you'll have to use libpqxx version 6.

**Comment by INotfound** [comment]
Okay, thanks for the answer. :disappointed:
