### ISSUE TITLE
"Started transaction while transaction still active" when calling function multiple times

### ISSUE THREAD

**Issue by noctera** [jtv/libpqxx#393]
I'm building a Rest server right now, where postgres is running with libpqxx in the background.

When the rest server is receiving multiple queries at once he is calling my libpqxx function multiple times

```
std::string Database::getHash(const std::string &email)
{
	try
	{
		//get hash from users table with the given email
		pqxx::work worker(connection);
		std::string sql = "SELECT hash from users WHERE email='" + email + "';";

		pqxx::result result{worker.exec(sql)};
		worker.commit();
		//iterate through the result and get the key-value pair with the key 'hash'
		for (auto row : result)
		{
			std::string count = row["hash"].c_str();
			return count;
		}
	}
	catch (const std::exception &e)
	{
		std::cerr << e.what() << std::endl;
	}
}
```
For example this one. Everything works fine, when I'm only calling it with one request. But everytime there are two or more, the function gets called two times or more at the same time, which leads to this error
```
Started transaction while transaction still active
```
Could someone help me to solve this
Thanks in advance :)

**Comment by tt4g** [comment]
Connections cannot be shared by multiple threads.
Please create a connection for each request (thread).

**Comment by noctera** [comment]
Oh thank you.  I've been wondering what it can be all the time.  Isn't it really resource consuming if you have to create a new connection for every request?

**Comment by jtv** [comment]
You don't need to create a new connection for every request.  You just can't have two transactions open on the same connection at the same time.

**Comment by jtv** [comment]
You _can_ keep a connection open across requests, just so long as you don't use it for two concurrent requests.  You can allocate a _pool_ of connections, and when a request comes in, you grab one from the pool.  Once you're done serving the request, you return the connection back to the pool for another request to use.

**Comment by noctera** [comment]
Oh this is a great idea. But let's say I have 1000 requests per second. Then I have to create more connections than the scenario when only 10 requests are comming in. I would have to dynamically create connections, for my needs

**Comment by tt4g** [comment]
Generating connections has a cost, and as jtv suggested, connection pooling can reduce the cost.
Connections can be pooled as long as they follow the rule of using a single thread.
However, it is inefficient to pool 1000s of connections.

For example, you can limit the size of the connection pool to 100 connections. When a connection in the pool becomes empty, block it until the connection is returned to the pool, and so on.
The maximum number of connections is always kept at 100.
The disadvantage of this approach is that latency drops when connections are exhausted.
The pool size of connections should be adjusted according to the requirements of the application.

Also, TCP connections that remain open for a long time may be disconnected by firewalls, etc., so it is better to send SQL statements (e.g. `SELECT 1 as one`) periodically for pool connections.

**Comment by noctera** [comment]
Ok I will do this. This is also the only way I can prevent seg faults when there are too many requests. Otherwise the server would go down

**Comment by jtv** [comment]
When you run out of capacity, you should start returning status code 429 or 503 — not crash!

Point to ponder about the difference in load: even when you're only getting 10 requests per second, you want to be _ready_ for those 1,000 per second.  And that means you can't do much else with the resources except keep them waiting for a load peak.  You do need to size your server for the maximum you can handle.  Nothing in the world will fix that.  ☺

If the number of connections really becomes the bottleneck for you (most likely to happen on the database side btw, not the application side) then you may have to re-architect in some way.  For instance you may be able to concentrate the database work in a limited pool of separate worker threads, which hold one connection each.  Sometimes the best solution is to cluster your database across multiple machines using replication.

**Comment by jtv** [comment]
If nobody minds, I'll close the ticket then.  Feel free to open a new one if you run into any problems.
