### ISSUE TITLE
Possible to std::move data out of internal structures?

### ISSUE THREAD

**Issue by Zeks** [jtv/libpqxx#397]
I wonder if one can take ownership of the c strings behind it all to avoid copying.

**Comment by tt4g** [comment]
C string is a pointer to a continuous `char`, so `std::move` will only copy the address.
Copying an address is the same cost as a move.

**Comment by jtv** [comment]
@Zeks, @tt4g is correct.  Plus internally the fields in a result are all allocated as one big block of data, so there is no ownership for the individual strings.

Best thing you can do to avoid copying is generally to read the data as `std::string_view` or `pqxx::zview`, and keep the `result` alive for as long as you need them.

**Comment by Zeks** [comment]
On a somewhat realted note: are row and field classes also cheap to copy as result class is?

**Comment by tt4g** [comment]
It is better to get the lvalue reference for field and row.

**Comment by jtv** [comment]
They're basically just a kind of extended smart pointer though - not too
expensive to copy.  But yes, when efficiency matters you might as well keep
a reference.

**Comment by jtv** [comment]
Cleaning out tickets.  Feel free to open new ones as needed.  Happy new year all!
