### ISSUE TITLE
Unprepare seems to trigger exception if it is not prepared

### ISSUE THREAD

**Issue by Laro88** [jtv/libpqxx#403]
I might have abused the unprepare call my pooling implementation in pqxx 6 which is being converted to 7, unfortunately it seems that unprepare now throws an exception if unpreparing a name that is not prepared.

```
void pqxx::connection::unprepare(std::string_view name)
{
  exec("DEALLOCATE " + quote_name(name));
}
```
The documentation does not state that DEALLOCATE fails if executed with something not allocated.

I can easily create a collection to check for previously prepared statements, so I am just checking if this is a known thing in version 7 (i am on 7.2.1 specifically)

**Comment by jtv** [comment]
Perhaps DEALLOCATE needs an IF NOT EXIST clause...

In libpqxx 6 the prepared statements API was a complex thing, which wasn't carrying its weight.  It tracked all prepared statements, and made its own decisions about how to deal with a double DEALLOCATE.  In libpqxx 7 prepared statements are just a thin wrapper for PREPARE/DEALLOCATE, so basically `unprepare()` handles this situation by doing whatever DEALLOCATE does.

Be aware that prepared statement definitions do not follow the usual transaction rules.  For that reason, `prepare()` is a member of `connection`, not `transaction_base`.  But that doesn't fully reflect the way it works either: IIRC if you prepare a statement during a transaction, and that transaction gets rolled back, the definition does not persist.

**Comment by Laro88** [comment]
IF NOT EXIST makes sense :-)

I would have a hard time what is actually allocated and being able to handle the "prepared state" if something is rolled back.

This is just another reason for me to redo my "connection reuse strategy" to a simpler "keep n connections ready for use strategy".

Please post if you add "IF NOT EXIST", then I will ask the vcpkg maintainers to update again. 

Is the DEALLOCATE actually necessary - it seems free memory on the server, but it seems to be safe just to prepare a new statement on top of another.

**Comment by jtv** [comment]
I don't do any of the server-side development, so not really up to me I'm afraid.  But I can leave a note on the site.

In libpqxx I permitted re-definition of a prepared statement as long as the new definition was exactly, byte-for-byte identical to the old one.  But if they are different, it does not seem safe to let people overwrite their statements.  That's just opening the door to mistakes.

**Comment by Laro88** [comment]
I just made a test for it - it seems like deviations in inline changed values can be changed (same query structure), however changing actual query structure causes a hickup.
I will add a bit of memory to my reuse for now.

**Comment by Laro88** [comment]
Seems like DEALLOCATE does not support IF EXISTS, found a reference to it here: [mailing list](https://www.postgresql.org/message-id/CALDgxVvr3LZVYwOdcAEozUeecYL-W__tuyo2DDpiSJPoRwcT7g%40mail.gmail.com) - found out when I tried to use it.

**Comment by jtv** [comment]
Right, looks like somebody else had the same idea and Heikki felt it was a slippery slope.

Another thing that might work is to prepare and unprepare your statements only while you're outside any transaction.  If `unprepare()` throws an exception, you can just catch it and continue as normal, because the error won't affect any transactions.  It also avoids the rollback complications.

**Comment by Laro88** [comment]
It causes problems as the ->unprepare call breaks the current transaction, and then my implementations fall apart :-(

The main problem is that we have some prepared statements called dynamically and we may reused prepared statement names. This was not a problem in version 6, however the inability to safely unprepare causes problems.

I will make an effort to try and keep track of prepared statement names that has been used - however this is also a bit of a problem in our solution.

**Comment by jtv** [comment]
Well I meant you could unprepare while _not_ in a transaction.  That way,
there's no transaction that gets rolled back.

An easier option: wrap the `unprepare()` in a `subtransaction`!

**Comment by Laro88** [comment]
unprepare in subtransaction it is then :-)

For future reference it is can be done like this (keeping a collection of previously prepared statements would improve perf a bit)
```
try { 
  pqxx::subtransaction s(*m_spW, "sUnprepare"); //m_spW is a std::shared_ptr to a pqxx::work (transaction) and Name is the prepared statement name to unprepare
  m_c->unprepare(Name.c_str());
  s.commit();
}
catch (...) { //do nothing as this exception is a well known problem
}
```

**Comment by jtv** [comment]
@Laro88 yup, that's the trick.
