### ISSUE TITLE
parameter count mismatch - discovered in pqxx version 7 (inline PostGIS conversion calls)

### ISSUE THREAD

**Issue by Laro88** [jtv/libpqxx#404]
I get an error message while testing the conversion from pqxx 6 to 7 that i haven't seen before.
```
ERROR:  bind message supplies 29 parameters, but prepared statement "create_datastruct" requires 27
```
The "sinners" are twoPostGIS pointconversion calls at the end of my query
```
22,$23,ST_SetSRID(ST_MakePoint($25, $24), 4326),ST_SetSRID(ST_MakePoint($27, $26), 4326)) "
```
that we have normally populated like this in version 6 (only last couple of vars shown)
```
, rM.sysAttitude.altitude
, rM.pos.latitudeDegrees
, rM.pos.longitudeDegrees
, rM.sysAttitude.pos.latitudeDegrees
, rM.sysAttitude.pos.longitudeDegrees);
```

So we just convert to postgis coordinates on the fly - however this inline conversion seems to be triggering a count mismatch.

Any advice on how to resolve this situation? 

Note: I can insert the values inline in the query - but I really like the clarity that the $n style gives and would like to keep it :-)

**Comment by jtv** [comment]
If you confirmed that the Point arguments are where the problem happens, it sounds as if somehow they count as two arguments each.  I tried reproducing that problem in a test though, and had no error.  What C++ types are those latitudes and longitudes?

First thing to do with a problem like this is a _minimal reproduction:_  Simplest piece of code that clearly demonstrates the problem.  The cause often becomes clear in the process, but if not, it makes it easier for others to pick it up and help solve it.

(That said, I can't help making a wild guess...  would it make sense to try for an equivalent using `Point()` instead of `ST_MakePoint()` maybe?  Probably not, but it doesn't have the commas.)

(I assume the `22` is probably just a truncated copy of `$22`.)

**Comment by Laro88** [comment]
I also made a testprogram - and it seems to work fine so I have to dig a bit deeper.

```
#include <iostream>
#include<pqxx/pqxx>

int main()
{
    try
    {
        pqxx::connection c("user=postgres dbname=octopus password=postgres");

        { //create test table
            pqxx::work w(c);
            w.exec("DROP TABLE IF EXISTS testquery");
            w.exec("CREATE TABLE testquery (id SERIAL, pos geometry);");
            w.commit();
        }

        { //insert
            pqxx::work w(c);
            c.prepare("A", "INSERT INTO testquery(pos) VALUES (ST_SetSRID(ST_MakePoint($1, $2), 4326))");
            w.exec_prepared("A", 1.1, 2.2);
            w.commit();
        }

        { //readout
            pqxx::work w(c);
            auto r = w.exec("SELECT COUNT(*) FROM testquery");
            w.commit();
            std::cout << "cnt:" << r[0][0] << std::endl;
        }

        { //cleanup
            pqxx::work w(c);
            w.exec("DROP TABLE IF EXISTS testquery");
            w.commit();
        }
    }
    catch (const std::exception& e) {
        std::cout << e.what();
    }
}
```

**Comment by jtv** [comment]
I was not able to reproduce the error either, even when I deliberately passed too many or too few parameters.

What I would suggest you do is: start experimentally _removing parameters_ from your code, to pinpoint where the problem happens.  (Doesn't matter that the code won't work — it's just an experiment.)  Does this particular error go away if you stop passing those two Point parameters?  Does it go away if you keep passing those two, but drop some of the earlier parameters?

AFAICT you don't even need to edit your query — if e.g. `$27` does not receive a parameter, it will just be NULL.

**Comment by Laro88** [comment]
Entirely my bad, sorry. I had two libpxx6 optional parameters as well that used , inside the libpxqq styled chaining (x, exists condition)... - and I had only removed the parantheses to get a compile - but neglected to convert these parameters to libpxqq style std::optional, and this was the cause of the offset of 2 parameters :-(
