### ISSUE TITLE
[Visual Studio 2017] Syntax error pqxx 7.3.1

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#405]
I just created a pull request to release pqxx 7.3.1 with the C++ package manager conan (conan-io/conan-center-index#4215). I found that the syntax error occurs in Visual Studio 2017 (It can be built in Visual Studio 2019).

The attached log file shows that there is a problem with parsing syntax in `stream_from.hxx`, causing many compilation errors.

[create_stdout.txt](https://github.com/jtv/libpqxx/files/5799087/create_stdout.txt)

I tried to investigate the cause of the problem, but it is going to take some time as I am not currently using C++ in my main work.

**Comment by tt4g** [comment]
I found an issue in Visual Studio.
It seems that Visual Studio 2017 does not compile if the `deprecated` attribute is specified in the template constructor.

* https://developercommunity.visualstudio.com/content/problem/139521/compilation-error-on-deprecated-template-construct.html
* https://developercommunity.visualstudio.com/content/problem/421223/deprecated-attribute-with-template-member-function.html

This bug has been fixed in Visual Studio 2019, but does not appear to have been fixed in Visual Studio 2017.

When I have time, I will try to prepare a patch and see if it compiles.

**Comment by jtv** [comment]
Thanks for digging that up.  I'd hate to remove that attribute, but if it solves the issue I guess we could postpone it.

**Comment by mathbunnyru** [comment]
@jtv what library authors usually do is they have some macro-stuff to define the attribute if it's available and to define it as an empty string if it doesn't work under this version.

Something like this (it's a pseudo-code):
```
#if MSVC_OLD_VERSION
  #define LIBPQXX_DEPRECATED
#else
  #define LIBPQXX_DEPRECATED deprecated
#endif 
```

The code will be a bit more messy, but will work on more platforms and will get benefits of modern C++ when possible.

**Comment by jtv** [comment]
@mathbunnyru that is what I normally do too, but to do it _right_ takes work.  Generally it's a bad idea to check for specific compiler versions; it's better to check during configuration whether the actual feature works.

Sigh.  And they promised us that "modern C++" would let us forget about the preprocessor.

**Comment by tt4g** [comment]
I have opened a pull request #406.
Visual Studio 2017 uses `__declspec(deprecated)` instead of `[[deprecated]]`.

**Comment by jtv** [comment]
Urgh.  That means that I can hide this in a macro, _but..._  I have to include the `[[brackets]]` inside the macro.  Which means a single item may not be able to have _two_ attributes.

**Comment by tt4g** [comment]
Yes. To specify the `deprecated` attribute and other attributes at the same time, we need to add more macros.
However, since the `deprecated` function is rarely updated, I don't think we will need to do that.

**Comment by jtv** [comment]
True!
