### ISSUE TITLE
[Fedora 33, libpqxx 7.3.1]: error: constexpr if condition is not a constant expression in field.hxx 

### ISSUE THREAD

**Issue by looopTools** [jtv/libpqxx#407]
I keep seeing this error on Fedora 33 with libpqxx: 

```bash 
/usr/include/pqxx/field.hxx:180:21: error: constexpr if condition is not a constant expression
      if constexpr (nullness<T>::has_null)
```

From any place where I access as a `bytea` in the following way: ` auto b_fingerprint = row[0].as<std::basic_string<std::byte>>();`.  I only see this error on Fedora on macOS I do not have the issue. 
Both OS is compiled with clang version 11. 
I also have it working on Fedora 32 but with clang 10.  

I installed libpqxx in the same way on all systems

```bash
./configure CXX=clang++
make 
sudo make install 
``

Is it a bug in libpqxx or did I do something wrong?


 


Full error output: 

```bash
In file included from /usr/include/pqxx/row.hxx:20:
/usr/include/pqxx/field.hxx:180:21: error: constexpr if condition is not a constant expression
      if constexpr (nullness<T>::has_null)
                    ^~~~~~~~~~~~~~~~~~~~~
../src/alexandria-storage-node/registry.cpp:271:41: note: in instantiation of function template specialization 'pqxx::field::as<std::__cxx11::basic_string<std::byte, std::char_traits<std::byte>, std::allocator<std::byte>>>' requested here
            auto b_fingerprint = row[0].as<std::basic_string<std::byte>>();
                                        ^
/usr/include/pqxx/field.hxx:180:21: note: read of non-const variable 'has_null' is not allowed in a constant expression
      if constexpr (nullness<T>::has_null)
                    ^
/usr/include/pqxx/strconv.hxx:89:15: note: declared here
  static bool has_null;
              ^
1 error generated.
```

**Comment by jtv** [comment]
The odd thing is, `test/test62.cxx` does the same thing, and I've compiled it many times with clang 11.  No problems, even with the strictest warning/error options I could find.

Is it possible that you need to add an option `-std=c++17` to your compiler command line?

**Comment by jtv** [comment]
Also, what version of libpqxx is this?  Did you build it yourself, or did you use a packaged version?

(The current release is 7.3.1)

**Comment by looopTools** [comment]
It is 7.3.1 and build it my self using: 

```
./configure CXX=clang++
make 
sudo make install 
``` 

I don't think any package manager (yet provides 7.3.1)

**Comment by looopTools** [comment]
More info: 
1. I just confirmed I am using `-std=c++17` in my build script.
2. I tried to install newest clang (from trunk) on fedora 32 and there it still works. It is only 33 that is a problem and I have been able to confirm this in a VM as.

**Comment by jtv** [comment]
It _sounds_ as if either:
 * Somehow you're not getting the built-in specialisation of `nullness<std::basic_string<std::byte>>`; or
 * The compiler is taking the `constexpr`-ness from the base template, rather than from the actual specialisation.

I wonder...  If you edited that `if constexpr` in `field.hxx` and turned it into a regular `if`, what other error do you get?

**Comment by looopTools** [comment]
I have not changed anything in libpqxx itself, and it is the same error just for different lines of code and it is only with `std::basic_string<std::byte>`. For instance `std::string`, `size_t`, and `bool` works perfectly fine

**Comment by looopTools** [comment]
oh sorry misread I will try

**Comment by looopTools** [comment]
For somethings sake I found the problem. Sorry for wasting your time. 
For some reason when I ran `dnf remove -y libpqxx-devel` it had only removed the lib files and not the header files, and I had only checked that the lib files were gone. 
So it was getting the old header, sorry for wasting your time :(

**Comment by jtv** [comment]
Ah!  I'll close the bug then.  Glad your problem is resolved at least.
