### ISSUE TITLE
pqxx.org is down

### ISSUE THREAD

**Issue by TimSC** [jtv/libpqxx#41]
pqxx.org is down, at least for the last few days. Is that administered by anyone here?

**Comment by jtv** [comment]
That's all me...  Which also means I don't have a lot of time for it.  :-)  Thanks for letting me know — time for an upgrade and reboot!

**Comment by LinuxDevice** [comment]
I was looking for documentation for the newer libpqxx-5 on the recently released Fedora 27...it seems to rely on C++14 standards, while it used to need only C++11. Unfortunately, Fedora has packaged version 4 docs with version 5 devel packages. With pqxx.org down, is there any alternative place to get the version 5 docs?

**Comment by KayEss** [comment]
The version marked 'latest' on https://readthedocs.org/projects/libpqxx/ just pre-dates the 6 release.

I guess ideally the RTD docs should be versioned with the right tag and generated and pushed as part of the tagging process

**Comment by jtv** [comment]
You could check out the 5.1 branch, configure, and make.  That should build the reference documentation if you have the right tools installed

You'll need Doxygen and xmlto installed — it'll probably take a few attempts to find all the packages you need.
