### ISSUE TITLE
Is BYTEA retrieval binary, like a largeobject? 

### ISSUE THREAD

**Issue by tomlankhorst** [jtv/libpqxx#410]
> [Data is transferred in text form. Can I make it work directly in binary?](http://www.pqxx.org/development/libpqxx/faq/)
> [...] If you want to work with relatively large binary objects but do not wish to use the large-object API, the best alternative is to keep them in regular columns of BYTEA type. Insert them using a prepared statement to avoid text conversion on the way to the server, and retrieve them into binarystring objects.

Question: The document mentions this as an alternative to largeobject, does that imply that retrieval of BYTEA with a binarystring (and more recently a `std::basic_string<std::byte>>`) happens without binary-text-binary conversion? 

I would like to work with binary objects of arbitrary size (1kB - 100MB) in my database. I prefer BYTEA because of simplicity, the ability to build resultsets with joins, operate with functions on the data.

**Comment by jtv** [comment]
BYTEA values do get converted to text (except when passing them to prepared
statements or parameterised statements), but this may not be as much of a
problem as one might think.

The text representation for binary data used to be complex and relatively
costly, and work best with data that had a lot of "ASCII-like" values in
it.  But that has changed.  It's now a simple, fast format that won't cost
much to convert.  So the cost of conversion is probably quite insignificant
compared to the cost of looking it up in the database, possibly reading it
from disc, sending it across the socket, reassembling it from network
packets, and processing it.  Definitely give it a try!

To me the real question is how big a BYTEA can get.  I don't know the limit
off the top of my head, and I can't spend much time at the computer right
now.  Memory usage on the client side can also be an issue there, if you
need a lot of these values in memory at the same time - though
`stream_from` and `stream_to` can help.

**Comment by tomlankhorst** [comment]
I am planning to use it as a shared repository of 3D assets. 
Clients will cache data when they retrieve it. Either in memory or on disk. 

An alternative solution might be to have the database storing paths instead and then use a simple HTTP server for file transfer. But if the performance penalty of using BYTEA is negligible, then I would prefer to go that way instead for the benefit of its simplicity. 

I believe the BYTEA maximum size is somewhere around 1GB, recalling from the libpqxx docs.

**Comment by jtv** [comment]
That all sounds about right to me.  I would guess that the HTTP overhead would be greater than the encoding/decoding overhead.

**Comment by tomlankhorst** [comment]
Thank you for your time and effort.
