### ISSUE TITLE
gcc4.8.5 can't build libpqxx?

### ISSUE THREAD

**Issue by chenqingguo** [jtv/libpqxx#411]
My compiler is gcc 4.8.5. When build libpqxx-6.4.7,I got the error like [issue336](https://github.com/jtv/libpqxx/issues/336).
Which release I can use if I can't update gcc4.8.5?

**Comment by tt4g** [comment]
I think you need at least two patches.

* Replace all List-initialization (https://github.com/jtv/libpqxx/issues/336#issuecomment-645125969).
* Replace `#define PQXX_NOVTABLE __declspec(novtable)` with `#define PQXX_NOVTABLE`. (https://github.com/jtv/libpqxx/issues/336#issuecomment-645751347).

If you are able to upgrade gcc, that is the easiest solution.

**Comment by jtv** [comment]
I don't know exactly how far you'd have to go back in libpqxx history to get a version that works with gcc 4.8 out of the box, but probably not very much further than the version you're trying.

I say that because libpqxx 6.x requires C++11 support, which looks to have been pretty far along in gcc 4.8.  You could search the NEWS file or the commit history for mentions of similar gcc (or "g++") versions.

**Comment by marc1uk** [comment]
i know this issue is closed, but just as an FYI for anyone looking to do this, here are the following list of changes I needed to make according to the above suggestions:
```
include/pqxx/compiler-public.hxx:60:#define PQXX_NOVTABLE __declspec(novtable)
replace with '#define PQXX_NOVTABLE'

replace {xxx} with (xxx) in:
include/pqxx/connection_base.hxx:739
include/pqxx/transaction_base.hxx:47-49
include/pqxx/nontransaction.hxx:66 (first two instances but not last one, which encloses Begin() - thats the body.

src/dbtransaction.cxx:43-45
src/connection_base.cxx:1210-1212
transaction_base.cxx:34-35,57-58
src/largeobject.cxx:150-151, 161-, 172-, 183-
src/notification.cxx:26-27
src/prepared_statement.cxx:27-29
src/pipeline.cxx:35-36
src/sql_cursor.cxx:98-102, 156-161
src/subtransaction.cxx:26-29
src/tablestream.cxx:19-21
src/stream_base.cxx:18-20
src/stream_from.cxx:45-47
src/stream_to.cxx:22-23
```
