### ISSUE TITLE
configure Compilation error

### ISSUE THREAD

**Issue by Aurevoir-68** [jtv/libpqxx#412]
Hello, I used the 

 **“. /configure -- without readline”**  

command in libpqxx-6.4.7 to report the following error

**configure error: 
can't find libpq-fe.h in . Are you sure the libpq headers are installed correctly?They should be in the directory returned by "pg_config --includedir" or "pkg-config libpq --cflags".** 

When I used the command 

 **“. /configure --with-postgres-include=/usr/local/pgsql/include --with-postgres-lib=/usr/local/postgres/lib”** 

to add PostgreSQL's header file and link library, I reported the following error:

**configure error: 
Did not find the PQexec() function in libpq. This is the litmus test for a working libpq installation.
A source file using the PQexec() function did compile without problems, and the libpq library is available for linking,....**

Version information：
**1. postgresql version:12.5.** 
**2. libpqxx6.4.7.** 

Can you help me solve the problem, thank you!!!

**Comment by Aurevoir-68** [comment]
**“. /configure -- without readline”** shoule be **"./configure"**

**Comment by jtv** [comment]
Have a look in `config.log`.  It should contain a lot of logged information
and a lot of errors, but the last error (a few pages before the end) should
tell you a bit more about what went wrong.

**Comment by jtv** [comment]
@Aurevoir-68 any news from `config.log`?

**Comment by jtv** [comment]
No follow-up?  I hope that means that the problem went away.  I'll close this ticket soon.

**Comment by lin-jk** [comment]
I have the same error, but I don't know how to solve it

**Comment by jtv** [comment]
@lin-jk same answer.  Look in `config.log`.
