### ISSUE TITLE
Latest tag 7.3.1 fails to build

### ISSUE THREAD

**Issue by valentin-bc** [jtv/libpqxx#413]
Cmake script that was successfully building libpqxx previously (including version 7.3.0) started to fail with:

`make[3]: *** [src/CMakeFiles/pqxx.dir/build.make:76: src/CMakeFiles/pqxx.dir/binarystring.cxx.o] Error 1
In file included from /mnt/hgfs/pqxx/include/pqxx/result.hxx:25,
                 from /mnt/hgfs/pqxx/include/pqxx/binarystring.hxx:21,
                 from /mnt/hgfs/pqxx/include/pqxx/binarystring:4,
                 from /mnt/hgfs/pqxx/include/pqxx/internal/statement_parameters.hxx:25,
                 from /mnt/hgfs/pqxx/include/pqxx/prepared_statement.hxx:17,
                 from /mnt/hgfs/pqxx/include/pqxx/connection.hxx:34,
                 from /mnt/hgfs/pqxx/include/pqxx/transaction_base.hxx:31,
                 from /mnt/hgfs/pqxx/include/pqxx/dbtransaction.hxx:19,
                 from /mnt/hgfs/pqxx/include/pqxx/blob.hxx:21,
                 from /mnt/hgfs/pqxx/include/pqxx/blob:4,
                 from /mnt/hgfs/pqxx/src/blob.cxx:8:
/mnt/hgfs/pqxx/include/pqxx/util.hxx:29:10: fatal error: version: No such file or directory
 #include <version>
          ^~~~~~~~~
compilation terminated.
make[3]: *** [src/CMakeFiles/pqxx.dir/build.make:89: src/CMakeFiles/pqxx.dir/blob.cxx.o] Error 1
make[3]: Leaving directory '/mnt/hgfs/pqxx/build'
make[2]: *** [CMakeFiles/Makefile2:91: src/CMakeFiles/pqxx.dir/all] Error 2
make[2]: Leaving directory '/mnt/hgfs/pqxx/build'
make[1]: *** [Makefile:152: all] Error 2
make[1]: Leaving directory '/mnt/hgfs/pqxx/build'
make: *** [Makefile:177: build_pqxx] Error 2`

**Comment by jtv** [comment]
That's just in `master`, right?  I forgot that `<version>` was only added in C++20, so the `#include` should be conditional so that a pre-C++20 compiler will still accept the code.  Fix coming up.
