### ISSUE TITLE
write timestamp via pqxx::stream_to

### ISSUE THREAD

**Issue by JensInc** [jtv/libpqxx#414]
I have a timestamp column (`date_time timestamp(3) NOT NULL`)  and want to write a `time_t` / `std::uint64_t` to it.

Doing via SQL command succeeds via `exec`: 
```
INSERT into measured_event (date_time, customer_id, device_id) VALUES ( to_timestamp(1612503819)  , 1, 1);
```
But using using  `pqxx::stream_to` results in:
```
unknown file: Failure
C++ exception with description "ERROR:  invalid input syntax for type timestamp: "to_timestamp(1612505814)"
CONTEXT:  COPY measured_event, line 1, column date_time: "to_timestamp(1612505814)"
" thrown in the test body.
```
when executing `stream.complete()`.
I am writing the timestamp as a `std::string` (inside a `std::tuple<std::string, std::uint32_t, std::uint32_t>`. 
Is there something special to perform? Writing other types works. 
I using libpqxx 6.4.5 with GCC9.3.0.

```
    std::unique_ptr<pqxx::connection> databaseConnection;

    using StreamType = pqxx::stream_to;
    template<typename Stream> void toStream(
             const std::string &tableName,
             const std::vector<std::string> &entryNames,
             std::function<void(Stream& stream)> &&process) {
        pqxx::work txn(*databaseConnection);
        pqxx::stream_to stream{txn, tableName, entryNames};
        process(stream);
        stream.complete();
        txn.commit();
    }

```
```
    using RowType = std::tuple<std::string, std::uint32_t, std::uint32_t>;
    databaseConnection.toStream<RowType>(
        this->TABLE_NAME,
        COLUMNS,
        std::vector<RowType>{ {std::make_tuple("to_timestamp(" + pqxx::to_string(1612505814) + ")",1,1)} });
```

**Comment by Laro88** [comment]
@JensInc  I am also struggling a bit with "inline calling" of the to_timestamp function (different context and pqxx version though) - any change you could try to run it with a native string like '2021-02-05 07:16:54' instead of the call to to_timestamp?

**Comment by JensInc** [comment]
It works - thanks a lot. 
Ok, now i have to do the conversation from the integer in my code (std::chrono etc.). 

P.S.: 
I am still wondering what is passed to the database system by stream_to. In both cases it is a string.

**Comment by Laro88** [comment]
@JensInc this can be done with the date_time library in boost (don't have the code in my finders though)
