### ISSUE TITLE
 pqxx.org is down

### ISSUE THREAD

**Issue by code-mc** [jtv/libpqxx#415]
https://downforeveryoneorjustme.com/pqxx.org

We currently use a very old version (4.x) of pqxx, the source for this version is not available on this github repo so we currently download it in our docker image from pqxx.org. This unfortunately appears to be down for the past week.

We can probably fix our issue by self hosting the source somewhere, but I'd just like to let you know your website is down :)

**Comment by jtv** [comment]
The hosting provider had a migration pending...  I guess that's happening now.  I didn't think enough people would care to make a big hoopla about it.

But it may help to know that the old source code _is_ in the github repo, it's just not tagged!  No idea what happened to the tags; they probably just didn't survive the migration from Subversion, back in the day.  But the history goes back the full 20½ years.

**Comment by jtv** [comment]
Thanks for letting me know about the site being down, by the way.  It's back up now, but for some reason, it didn't do that spontaneously.  I had to go in and reboot it.

**Comment by code-mc** [comment]
Thanks! Yeah I assume we're one of the very few who still depend on such an old version... Unfortunately don't really have the time to migrate to a more modern pqxx version, budgets and stuff :p

**Comment by jtv** [comment]
That's a shame.  But I'd at least give some newer versions a try - the
basics I think have stayed pretty compatible.  And keeping up may save you
pain in the long run.

**Comment by jlowenz** [comment]
The website is down again, unfortunately.

**Comment by jtv** [comment]
Thanks.  No idea what went wrong there.  :-(  Network was out.  Rebooted
and will look at more of the logs.


Jeroen
