### ISSUE TITLE
Building version 6.4.7 on Windows

### ISSUE THREAD

**Issue by gedoensmax** [jtv/libpqxx#418]
Hi am trying to build version 6.4.7 on Windows using cmake and generator windows.
Although it should not really matter during the cmake step i am using Visual Studio 2019 compiler.

```
cmake "-GNinja" "-DPostgreSQL_ROOT=D:/dev/../3rdparty/pgsql" .
-- Looking for C++ include sys/select.h
-- Looking for C++ include sys/select.h - not found
-- Looking for C++ include sys/time.h
-- Looking for C++ include sys/time.h - not found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - not found
-- Looking for poll
-- Looking for poll - not found
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting std::optional
-- Detecting std::optional - not supported
-- Detecting std::experimental::optional
-- Detecting std::experimental::optional - not supported
-- Detecting __attribute__ ((const))
-- Detecting __attribute__ ((const)) - not supported
-- Detecting __attribute__ ((pure))
-- Detecting __attribute__ ((pure)) - not supported
-- Detecting __attribute__ ((visibility))
-- Detecting __attribute__ ((visibility)) - not supported
-- Generating config.h
-- Generating config.h - done
CMake Warning (dev) at src/CMakeLists.txt:15 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable PostgreSQL_ROOT is set to:

    D:/dev/../3rdparty/pgsql

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at test/unit/CMakeLists.txt:15 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable PostgreSQL_ROOT is set to:

    D:/dev/../3rdparty/pgsql

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
CMake Error:
  Running

   'C:/PROGRA~1/Ninja/ninja.exe' '-C' 'C:/Users/maximilianm/Downloads/libpqxx' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:747: multiple rules generate src/pqxx.lib [-w dupbuild=err]





CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by jtv** [comment]
Have you tried a more recent version of libpqxx?  A lot of work has gone
into the CMake build since 6.x.

**Comment by gedoensmax** [comment]
Yes the newer version did compile but with that i have a problem with the `<ranges>` include as we are using C++17 in the project. Furthermore this project is supposed to be cross platform and i want to use the apt package for linux which is 6.4 if i am correct.

**Comment by tt4g** [comment]
@gedoensmax What your CMake version?
The error message reports that multiple Ninja rules are generated to generate `src/pqxx.lib`.
There have been some reports that CMake has this problem when using the Ninja generator.
e.g. https://gitlab.kitware.com/cmake/cmake/-/issues/18584

If you do not have the latest version of CMake, please try upgrading.

**Comment by gedoensmax** [comment]
I was on CMake 3.19.2 and just updated to the slightly newer version to be sure but it did not change the output.

**Comment by tt4g** [comment]
I would like to know if this is due to Ninja rules.
Can you add `-DBUILD_TEST=OFF` to the CMake argument and see if you can build it?

```bash
$ cmake -G "Ninja" -DPostgreSQL_ROOT:PATH="D:/dev/../3rdparty/pgsql" -DBUILD_TEST=OFF .
```

**Comment by gedoensmax** [comment]
I already treid skipping the tests. Sorry that i did not mention, it does not help.

**Comment by tt4g** [comment]
I'll try to reproduce it in my environment, but the earliest I can get it to work is tomorrow.

The only way I can think of right now is to upgrade Ninja or specify the CMake build type (e.g. `-DCMAKE_BUILD_TYPE=Release`) and see if the behavior changes.

**Comment by gedoensmax** [comment]
No hurry. These are also the things i tried.

**Comment by jtv** [comment]
@gedoensmax libpqxx 7.x is C++17.  The current version does include `<ranges>`, but _only_ if that header is actually available.

So now I'm really curious to know why that's failing for you.  I'd much rather fix that than have you stuck with 6.x.

**Comment by jtv** [comment]
It's possible that I accidentally included `<ranges>` unconditionally in a previous version though.  Any chance you could give libpqxx 7.4.1 (the latest) a go?

**Comment by tt4g** [comment]
Hmmm. I was able to download libpqxx-6.4.7 from the Release-Page and build it with CMake.
I used the Ninja generator from x64 Native Tools Command Prompt, but only one rule existed to generate libpqxx.

The version information for each tool is as follows:

```bash
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.8.6
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>ninja --version
1.8.2

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>where ninja
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>cmake --version
cmake version 3.19.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>cl
Microsoft(R) C/C++ Optimizing Compiler Version 19.28.29337 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Comment by gedoensmax** [comment]
@tt4g Ok it seems that the with VS bundled version is slighly oder than mine which is seperately donwloaded. WIth version 1.10.2 it does not work.

@jtv It is a conditional include. All good. My problem was that we activated warnings as errors last week and i forgot so i thought this was ranges concerned: 
```
The contents of <ranges> are available only with C++20 concepts support.
..\modules\logging\cpp\pg_logger.cpp(109): error C2220: the following warning is treated as an error
..\modules\logging\cpp\pg_logger.cpp(109): warning C4100: 'message': unreferenced formal parameter
```

**Comment by jtv** [comment]
That's annoying — I try to compile without any warnings, and at the strictest feasible compiler settings.

Would you mind running a little experiment for me?  If you go into `include/pqxx/connection.hxx` and you replace the condition in...

```cpp
    #if __has_include(<ranges>)
    #   include <ranges>
    #endif
```

...to read...

```cpp
    #if defined(PQXX_HAVE_CONCEPTS) && __has_include(<ranges>)
    #   include <ranges>
    #endif
```
...does that make the warnings go away?

**Comment by gedoensmax** [comment]
No all good it was the other warning below the error message when i got rid of that it works but still prints frequently that information.

**Comment by jtv** [comment]
I don't want my library to pollute your build log though.  :-)

**Comment by gedoensmax** [comment]
Yes the altered if statement makes the warning disappear.

**Comment by jtv** [comment]
OK, I'll add that then.  Thanks for reporting it.
