### ISSUE TITLE
nontransaction always sends ROLLBACK to server in 7.3.1

### ISSUE THREAD

**Issue by rstoner1999** [jtv/libpqxx#419]
I recently migrated from pqxx 6.4.5 to 7.3.1.  I am running PostgreSQL 12.  After upgrading PQXX, I discovered my server logs were full of `WARNING:  there is no transaction in progress` lines.

Upon some digging, I discovered that `nontransaction` is always sending a `ROLLBACK` command to the server, which is triggering this log warning.  Compiling and running this program with pqxx 7.3.1:
```
#include "pqxx/pqxx"
#include <iostream>

int main(int, char**) {
    pqxx::connection conn("postgresql://?service=XXX");
    pqxx::nontransaction txn(conn);
    pqxx::result result = txn.exec_params("SELECT 1;");
    for (pqxx::row const& row : result) {
        int i = row[0].as<int>();
        std::cout << "ROW " << i << std::endl;
    }
}
```
And enabling the appropriate logging on the server results in
```
2021-02-24 16:41:45.464 CST [103177] LOG:  execute <unnamed>: SELECT 1;
2021-02-24 16:41:45.483 CST [103177] LOG:  statement: ROLLBACK
2021-02-24 16:41:45.483 CST [103177] WARNING:  there is no transaction in progress
```
After digging through the pqxx code a little, I think this is because:
`nontransaction::~nontransaction()` calls `transaction_base::close()`
Inside `transaction_base::close()`, I believe `m_status` is `status::active`, although I have not verified this
This results in `abort()` being called
`abort()` calls `do_abort()`
`do_abort()` calls `direct_exec(m_rollback_cmd)`

I believe this could be fixed by having `nontransaction` call `transaction_base::set_rollback_cmd(nullptr)` in its constructor, although I have not tried this.

Does this make sense?  Should a future release of pqxx do this inside of `nontransaction` automatically?

**Comment by rstoner1999** [comment]
Or perhaps a better solution is to have `nontransaction` override `do_abort()` and do nothing.  In fact, that is what the `nontransaction` already claims (and does for `do_commit()`.
> Any query executed in a nontransaction is committed immediately, and neither commit() nor abort() has any effect.

Unfortunately, that will conflict with the comment on `transaction_base::do_abort()`
```
  /// Transaction type-specific way of aborting a transaction.
  /** @warning This will become "final", since this function can be called
   * from the implementing class destructor.
   */
  virtual void do_abort();
```

**Comment by rstoner1999** [comment]
I apologize for the extended string of comments here.  I just noticed that `nontransaction` has this constructor, which uses an empty rollback_cmd.
```
  nontransaction(connection &c, std::string_view tname) :
          transaction_base{c, tname, std::shared_ptr<std::string>{}}
  {
    register_transaction();
  }
```
Indeed, if I switch to this 2-argument constructor then the ROLLBACK command is not sent to the DB.  Therefore, I can workaround this issue.

However, in the future, could you make the single-argument `nontransaction` constructor also use an empty rollback_cmd?

**Comment by jtv** [comment]
Thanks for spotting this, excellent work!

I'm thinking maybe the destructor should just set the status to "committed."

**Comment by jtv** [comment]
No, you're right.  I simply forgot to pass that null `rollback_cmd`.
