### ISSUE TITLE
Evaluating C++20

### ISSUE THREAD

**Issue by egorpugin** [jtv/libpqxx#420]
Hi!

While C++20 is out, it is possible for libraries to start experimenting on some modern features.
As for libpqxx they might go into 1) the next major version (8.0), 2) or into `pqxx::experimental` namespace.

Possible new features:

1. Checking of query parameters number in compile time.

Small example of counting number of params: https://godbolt.org/z/TzqnEe
We can try to pass that number to template, so number of args `(arg1,arg2,...) or (arg1)(arg2)` is controlled at compile time.

2. Async queries (coroutines).

3. Query builder (on constexpr strings). Should be easy with constexpr strings.

**Comment by jtv** [comment]
Thanks for looking into this.  I was in fact hoping to go C++20 with libpqxx 8.0.  The Big Feature that I had in mind was async queries, but it sounds like that's going to require a lot of custom work for managing the suspension and reactivation of coroutines.  For now my first major step looks to be Concepts — search the source for some notes and ideas I've written down.

The "counting parameters" idea is pretty cool.  But I do worry about things like dollar signs inside SQL strings, or perhaps even inside quoted table/column names.  I don't want to parse the SQL, really, and I doubt I can fully do it at compile time because the encodings are set at run time.  :-/

**Comment by jtv** [comment]
Oh, and of course I can't wait for modules!

**Comment by egorpugin** [comment]
> But I do worry about things like dollar signs inside SQL strings

Good catch, indeed.

**Comment by jtv** [comment]
I think I'll just dump notes here about things I'd like to do for C++20, such as:
 * Support any `range` of `byte` as binary data.
 * Use & support `ssize()` and `ssize_t`.
 * For string concatenation and such, _support_ random-access ranges but _optimise_ the special case of forward-only ranges.
 * Support any `range` for dynamic statement parameters.

**Comment by jtv** [comment]
I think I can close this ticket now.  These notes have all been incorporated in the code, even if it's just as comments.

A new script, `tools/todo`, lists the to-do comments in the code.

**Comment by egorpugin** [comment]
From https://github.com/jtv/libpqxx/commit/f1fbdc81f2520b776b612e2ed1f3914e7af88e4b#r51130742

Briefly, you can write templates without `template<...>` as such
```
auto f1(auto &&var) {...}
auto f2(myconcept auto &x) {...}
etc.
```

References
[1] https://en.cppreference.com/w/cpp/language/auto
[2] https://devblogs.microsoft.com/cppblog/abbreviated-function-templates-and-constrained-auto/

**Comment by jtv** [comment]
Thanks, that'll make the code a lot nicer.

For now though, I'm still supporting C++17 so I'll keep the syntax a bit more uniform.  I've been moving a lot of functions back and forth between C++17 and C++20 styles.

**Comment by egorpugin** [comment]
@jtv 
I'll put some of my thought about modern metaprogramming here, if you don't mind.

Let's say we have some code gen for DB.
Possible trasformations
```
tables,fields -> (codegen) -> sql schema -> ... -> some queries with known output types
```
or just from schema
```
sql schema -> ... -> some queries with known output types
```

Now we write
```
for (auto &&[col1,col2,...,colN] : txn.prepared<Type1,Type2,...,TypeN>("query_id")) // or just .exec<Types...>("...")
   ... ;
```

What if we store column types of our codegen chain with our query?
Something like
```
template <const char * (or std::string) Query, typename ... Columns>
struct my_query1 {
    using types = std::tuple<Columns...>; // or just Columns...?
};
```

Then we run it as
```
for (auto &&[col1,col2,...,colN] : txn.prepared(my_query1{})) // or just .exec(my_query1{})
   ... ;
```

What we've got here? Strict type checking of result columns with our compiler.
Am I missing something? Is it viable idea? Maybe something already present in pqxx?

**Comment by jtv** [comment]
There are some similar things in libpqxx, but not exactly this.

You can convert a whole row of data at once using `pqxx::row::as()`, which returns a `std::tuple`.  So you specify the types you want at the point where you read the values, not at the point where you issue the query.

There's also `pqxx::transaction_base::stream()`.  There, you specify the types you want at the point where you issue the query.

What you're suggesting strikes me as something that would be most useful with a prepared statement, because that's where you might want to re-use the combination of the statement and the column types in multiple places in your code.  It can happen with regular statements as well, but the query determines what columns you get back.  Different queries typically get different column lists.  If you want the same query _and_ the same result columns in two places, you might as well just wrap it in a function.

**Comment by egorpugin** [comment]
Again checking some other libs.

https://github.com/yandex/ozo
https://raw.githubusercontent.com/boostcon/cppnow_presentations_2018/master/05-09-2018_wednesday/design_and_implementation_of_dbms_asynchronous_client_library__roman_siromakha__cppnow_05092018.pdf

On slides 37-41 there is something similar to what I described - `txn.make_query<Query>(params);`
That lib also uses `boost::hana` what I'm looking into in some of my projects currently.

Also interesting concept is generated templates from oids - https://github.com/yandex/ozo/blob/master/include/ozo/pg/definitions.h

But at the end, I'm not sure they'll upgrade `ozo` to C++20.

---

Slide 46 shows `vector<...> result` as
```
std::vector<message> rows;
ozo::request(provider, query, std::back_inserter(rows), asio::use_future);
```

---

Some other already mentioned concepts/improvements from there:
1. async (coroutines is the most interesting, I think) - was in my first post here
2. binary mode for libpq transfers. Does pqxx use it?

**Comment by jtv** [comment]
Thanks — didn't you send me a similar slideshow in Russian once?

These are good ideas to bring up and discuss, I think.  As the language changes, new things become possible.

One bit of background from the very early days  of libpqxx may be relevant: Looking at a few other libraries that existed at the time, I came to this unusual (at the time) tradeoff where _transactions are objects,_ but _statements are not._

Object Orientation was still fashionable at the time, but having a connection object _and_ a transaction object _and_ a statement object _and_ a result object seemed like a bit much.  I really want to keep that cognitive overhead down.  The only object I could easily get rid of was the statement, and to me that still looks like a good choice today.

That's not to say that there can never ever be a "statement class," but we'll want to look very carefully at that old question: "could we do the same thing with just a function?"

**Comment by egorpugin** [comment]
> didn't you send me a similar slideshow in Russian once?

Yes, but now I've looked into some other parts of it.
They have good ideas with C++ metaprogramming. I'd like to control types, schema and queries in such way, so it will be checked by compiler as much as possible.

> seemed like a bit much. I really want to keep that cognitive overhead down. 

I agree here. Definitely no need to repeat them 1-to-1.

> question: "could we do the same thing with just a function?"

Also agree.

**Comment by jtv** [comment]
Oh, one other note.  I got distracted before I could write it down, and took a shortcut earlier.  About why re-use is so important to me when it comes to type-safe SQL statements:

I very much like the idea of compile-time type safety, but it only comes into its own with re-use.  When you call something just once, strong typing boils down to "we'll make you write everything down twice and then we'll check if you were consistent."  It becomes useful when you have multiple calls.

**Comment by jtv** [comment]
@egorpugin I missed two things you brought up...  _async_ and _binary transfers._
Both good questions.  Unfortunately I doubt I can do either of those things anytime soon!

The obstacles I see for **async** are:
 * Lots still to learn, obviously.  This one should go away eventually.  ☺
 * My impression so far is that C++ async is a poor fit for `poll()`/`select()` as means of waiting.
 * Perhaps the waiting would work better with epoll?  Not very portable though.
 * If the polling overhead is too great, async code may end up performing worse than synchronous code.
 * Compiler support doesn't look very widespread yet.

Obstacles for **binary transfers:**
 * Undocumented.
 * Not guaranteed to be stable.
 * Not necessarily as simple and efficient as it sounds, e.g. integers are variable-length.
 * Hard to check for bugs, format changes, etc.
 * Possibly sensitive to portability issues.

Of course there _is_ a case where binary transfers are an obvious, big win: BYTEA values.  And libpqxx transparently supports those, if you pass them to a prepared statement or a parameterised statement as a parameter value.  They get transferred in binary form, through template magic.  In theory it would be possible to extend that support a little bit for specific other types.

And so, for now, the main feature I've got lined up for libpqxx 8 and C++20 is _concepts._  And I'd love to go with modules, but we'll have to see how good compiler support is first.

**Comment by egorpugin** [comment]
> binary transfers

Ok, that's fine.

> async
> My impression so far is that C++ async is a poor fit for poll()/select() as means of waiting.

I'm not sure about these, but...

Let's say we have a webapp with db access.

user1 requests page -> epoll/uring signals -> app started request processing -> async db request happened -> we pass control back to os scheduler (epoll/uring)

We will be either waken up by 1) io event from db, 2) io event from other user request.
In case 2) we will start processing of this request -> end it (or go into async db query again) -> during scheduling we may be notified that user1.query1 is ready, so we finish that request.

---

How I see possible coroutine support in libpqxx.
`co_await txn.exec()` or `co_await txn.exec_async()`.

**Comment by jtv** [comment]
The part that's still very unclear to me is: _how_ do we ensure that we get woken up when there's an event from the database, or an I/O event from something else?  That event may arrive at a moment when the thread may be waiting for something else, using an entirely different mechanism.  AIUI it's really up to the application to decide how to wait for things.

(Also of course, uring is probably even _less_ portable than epoll. ☺)

**Comment by KayEss** [comment]
`io_uring` is for sure a lot less portable than `epoll` :-)

So long as everything that runs in the same thread agrees on the same way to wake up then it's fine. This could be `io_uring` or `poll` etc. but it can't be more than one of them.

**Comment by egorpugin** [comment]
I'm not saying pqxx should enforce io loop.
It must provide capabilities of integrating itself into user-choosen io loop.

**Comment by jtv** [comment]
Absolutely.  But I suspect that's easier said than done.

**Comment by egorpugin** [comment]
Also it seems io loop integration is mostly about libpq interfaces, not pqxx.

**Comment by jtv** [comment]
Yes, that's the other side of the problem.  I think we'll need to let the world think about this problem some more, and come up with more ready-made components.

**Comment by egorpugin** [comment]
I see. There is `PQsocket()` so we can integrate it into any(?) io loop.
https://www.postgresql.org/docs/current/libpq-status.html#LIBPQ-PQSOCKET
epoll example - https://gist.github.com/ictlyh/6a09e8b3847199c15986d476478072e0

And we have `sock()` in pqxx
https://github.com/jtv/libpqxx/blob/master/include/pqxx/connection.hxx#L289

Next, we have `consume_input()` which is private :(

Also see comment under https://www.postgresql.org/docs/current/libpq-async.html#LIBPQ-PQFLUSH

---

This means:
1. We take control of the socket.
2. We must be able to tell libpqxx what to do in case of read/write/error readiness of the socket (to connection class?).

**Comment by egorpugin** [comment]
Ok, thank you.

I'll leave this topic for now.
If I really need some pq/pqxx async capabilities in the future, I'll return to it.

**Comment by jtv** [comment]
Thanks for plugging away at it though.  If we keep doing that, a
breakthrough will present itself one day.

**Comment by egorpugin** [comment]
For reference: https://github.com/RobertLeahy/ASIO-PQ

**Comment by egorpugin** [comment]
Some of my experiments - https://github.com/egorpugin/examples/tree/master/pg/libpq_coro
See `simple.cpp`, `simple_oop.cpp`.
These implement non-blocking connection procedure and queries wrapped into coroutines.

I can't yield results row by row yet - the original goal.
Boost asio coro awaitables and promises are not designed for yielding values (no `yield_value()` call).
Or it's just me not understanding how to extend it.

**Comment by jtv** [comment]
I don't see any way to yield one row at a time, unless you stream the data in `stream_from` style.

It's tempting to think that we could just take over the socket completely and talk to the back-end ourselves.  But there's no support for taking over on the SSL level, only the socket itself.  So managing the socket ourselves would entail ripping out libpq, and that in turn would mean dealing with the handshake which has different scenarios depending on the authentication options, and linking to SSL or TLS libraries ourselves, and... just not worth it.

**Comment by egorpugin** [comment]
I do not understand.

I implemented nonblocking libpq connect and query.
We do not need to handle any ssl/pg protocol ourselves. Libpq does this.
We just invoke it in the right way and control socket events (read/write).

See connection loop for example
https://github.com/egorpugin/examples/blob/master/pg/libpq_coro/simple_oop.cpp#L51
Socket events is waited in `co_await wait_for_raw_socket()` calls.

Next, row yielding.
As I understand when libpq receives result in nonblocking mode plus PQsetSingleRowMode(), it can return result row by row.
It is stated right in the doc.
https://www.postgresql.org/docs/current/libpq-single-row-mode.html

> Ordinarily, libpq collects a SQL command's entire result and returns it to the application as a single PGresult. This can be unworkable for commands that return a large number of rows. For such cases, applications can use PQsendQuery and PQgetResult in single-row mode. In this mode, the result row(s) are returned to the application one at a time, as they are received from the server.

**Comment by jtv** [comment]
I'd forgotten about single-row mode.  Never seemed useful for libpqxx, where we have `stream_from`, so I never bothered with it.
