### ISSUE TITLE
Mingw 64bit build fail

### ISSUE THREAD

**Issue by gfgit** [jtv/libpqxx#424]
Hi, I'm trying to build libpqxx on windows.
OS: Win 10 64-bit
Compiler: MingW 8.10 64-bit (Shipped with Qt distribution)
libpq: headers and library from installation of PostgreSQL 13 server

I get this warning (but should not be relevant):
`[11/110 1.2/sec] Building CXX object src/CMakeFiles/pqxx.dir/connection.cxx.obj
In file included from C:/libraries/libpqxx-7.4.1/src/connection.cxx:28:
C:/Qt23/Tools/mingw810_64/x86_64-w64-mingw32/include/winsock2.h:15:2: warning: #warning Please include winsock2.h before windows.h [-Wcpp]
 #warning Please include winsock2.h before windows.h`

And an error about `std::thread`:
`C:\Qt23\Tools\mingw810_64\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\thread:273: error: no match for 'operator==' (operand types are 'std::thread::native_handle_type' {aka 'ptw32_handle_t'} and 'std::thread::native_handle_type' {aka 'ptw32_handle_t'})
In file included from C:/libraries/libpqxx-7.4.1/src/robusttransaction.cxx:16:
C:/Qt23/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/thread: In function 'bool std::operator==(std::thread::id, std::thread::id)':
C:/Qt23/Tools/mingw810_64/lib/gcc/x86_64-w64-mingw32/8.1.0/include/c++/thread:273:26: error: no match for 'operator==' (operand types are 'std::thread::native_handle_type' {aka 'ptw32_handle_t'} and 'std::thread::native_handle_type' {aka 'ptw32_handle_t'})
     return __x._M_thread == __y._M_thread;
            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~`

**Comment by jtv** [comment]
I can't look it up right now, but this sounds like a known problem with
MinGW.  Might be worth looking up outside the context of libpqxx.

Is there a newer version of g++ for MinGW?

**Comment by jtv** [comment]
Doesn't look like there's a newer MinGW.  ☹

Does this help?  It's a few years old, and I think I ran into a similar problem at the time.

http://hectorhon.blogspot.com/2018/05/building-libpqxx-on-msys2-mingw-64-bit.html

**Comment by jtv** [comment]
Curious, also on behalf of people who may have the same problem in the future...

Did you end up having to edit that `<thread>` header?
