### ISSUE TITLE
Path issue (building libpqxx)

### ISSUE THREAD

**Issue by chea1505** [jtv/libpqxx#43]
Building libpqxx on Windows 10 with x64 Native Tool Command Prompt for VS 2017, Community Edition.
Using PostgreSQL 9.5 installed with one-click installer

As instruction in file win32\common to set
PGSQLSRC="C:\Program Files\PostgreSQL\9.5"
Will produce error during copy file:
-------------------------------------------------------------
Copying libpq.dll to lib.

IMPORTANT: you MUST copy this libpq.dll into the directory
where your program's .EXE resides. The system libpq.dll is
not necessarily compatible with the libpq include files that
you built libpqxx with. Do NOT copy this file into your
Windows system32 directory, that may break other programs.
Instead, keep it with your program and distribute it along
with the program.
-------------------------------------------------------------
        copy ""C:\Program Files\PostgreSQL\9.5"\lib\libpq.dll" "lib"
The system cannot find the file specified.
NMAKE : fatal error U1077: 'copy' : return code '0x1'
Stop.

I can fix the error by editing the win32\common:

PGSQLSRC=C:\PROGRA~1\POSTGR~1\9.5

Note the path without quotes and it use short name.
This is a minor issue, but it waste time for new user like me trying to compile the library.
Hope you could mention this in the win32\common-sample.

**Comment by jtv** [comment]
The short name really shouldn't matter...  Are you saying that the quotes were breaking the build?

**Comment by chea1505** [comment]
Yes, the quotes were breaking the build. It produce this command on command prompt.
copy ""C:\Program Files\PostgreSQL\9.5"\lib\libpq.dll" "lib"
Is the quote really needed for space path like Program Files? If yes, what should be the solution?

**Comment by jtv** [comment]
Ah, I think I see now — the quotes get included in the string, so we absolutely cannot have them, but at the same time it looks as if a space in the path _also_ makes them _necessary._

Could you perhaps find out whether there's another way of quoting the string, or maybe the spaces need to be escaped (but not with backslashes I guess, since this is Windows!), or maybe there should be a weird rule like "use quotes if there's a space but not if there's no space"?

**Comment by egorpugin** [comment]
@jtv what do you think about adding cmake build system for win?
(not on your own, but by contributors)

**Comment by jtv** [comment]
Could be interesting.  I do believe some people have their own build setups for libpqxx.

**Comment by ash-j-f** [comment]
I used path C:\Program Files\PostgreSQL\11 and now it's broken when path is used by cl.exe. See #200.

**Comment by jtv** [comment]
Is there a clean way out of this for all reasonable cases?

Now that we have a CMake build, I'm tempted to bless it as the replacement for the custom Visual Studio build files.  Any opinions on whether that would be acceptable to people out there?
