### ISSUE TITLE
std::span compile error if compiler defaults to C++20

### ISSUE THREAD

**Issue by tambry** [jtv/libpqxx#434]
`PQXX_HAVE_SPAN` successfully detects `std::span` as available for me because my vendored Clang defaults to C++20. Compiling libpqxx however fails as it's compiled in C++17 mode but assumes `std::span` availability based on the previous.

Setting [CMP0067](https://cmake.org/cmake/help/latest/policy/CMP0067.html) to `NEW` would solve this issue, as it makes `try_compile()` respect `CMAKE_<LANG>_STANDARD` variables.

libpqxx also defaults `CMAKE_CXX_STANDARD` to `17`, which isn't supported by the current required minimum version CMake 3.7. Bumping the required CMake version 3.8 would fix both of these.

For example:
```
[6/110] Building CXX object src/CMakeFiles/pqxx.dir/blob.cxx.o
FAILED: src/CMakeFiles/pqxx.dir/blob.cxx.o 
/usr/bin/c++  -Iinclude -I../include -I/usr/include/postgresql -O3 -DNDEBUG -std=c++17 -MD -MT src/CMakeFiles/pqxx.dir/blob.cxx.o -MF src/CMakeFiles/pqxx.dir/blob.cxx.o.d -o src/CMakeFiles/pqxx.dir/blob.cxx.o -c ../src/blob.cxx
In file included from ../src/blob.cxx:8:
In file included from ../include/pqxx/blob:4:
../include/pqxx/blob.hxx:105:8: error: no template named 'span' in namespace 'std'
  std::span<std::byte> read(std::span<std::byte> buf)
  ~~~~~^
../include/pqxx/blob.hxx:105:34: error: no template named 'span' in namespace 'std'
  std::span<std::byte> read(std::span<std::byte> buf)
                            ~~~~~^
2 errors generated.
```

**Comment by tt4g** [comment]
Can you create a pull request?
Since @jtv doesn't usually use CMake, CMake is maintained by pull requests.
It would be best to merge the code that worked in your hand.

**Comment by tambry** [comment]
I'll do that later today.

**Comment by jtv** [comment]
Great, thanks!
