### ISSUE TITLE
Idiomatic way to use PostgreSQL's enumerated values

### ISSUE THREAD

**Issue by tomlankhorst** [jtv/libpqxx#439]
PostgreSQL supports [enumerated values](https://www.postgresql.org/docs/13/datatype-enum.html).

I can define conversions for scoped enums with `PQXX_DECLARE_ENUM_CONVERSION` macro but that converts from scoped enum to some integral underlying type. 

Intuitively, it would be nice to convert enumerated values to scoped enums but I am aware that implementation-wise this is troublesome since scoped enum labels are not introspectable so it would require some macro magic or assumptions about the relationship between underlying value and corresponding Postgres enum label. 

What would be the most idiomatic way to use enumerated values in libpqxx? 

My guess would be plain string conversion.

**Comment by jtv** [comment]
You're right, enums support is basically just numbers.

The advantage to scoped enums is that they're distinct types.  So you could
specialise string_traits and nullness for your enum type, with a custom
conversion.

I can't think off the top of my head (and I'm having computer problems)
whether this would work for all situations: inserting as a literal in SQL
text, passing as a statement parameter, streaming, and parsing from a
result.  But it'd be worth a try, and perhaps some library support to make
it easier in future cases.


Jeroen

**Comment by tomlankhorst** [comment]
Thanks for your explanation. I'll close this issue now since I'll be satisfied with the numerical approach but it can be reopened in the future for further discussion.
