### ISSUE TITLE
Compiling with mingw 8.1.0: error: no match for 'operator==' in robusttransaction.cxx:16

### ISSUE THREAD

**Issue by aqa5** [jtv/libpqxx#441]
I get an error while compiling libpqxx. Environment:

- cmake 3.20.1
- mingw_8.1.0_i686-posix-dwarf
- Postgres 13

Looks like my mingw does not support this operator. Can we do anything about it? This version of mingw was selected on purpose and it would impose a real problem if I need to switch it. 

```
In file included from ...\libpqxx-7.4.1\src\robusttransaction.cxx:16:
mingw_8.1.0_i686-posix-dwarf/mingw32/lib/gcc/i686-w64-mingw32/8.1.0/include/c++/thread:273:26: error: no match for 'operator==' (operand types are 'std::thread::native_handle_type' {aka 'ptw32_handle_t'} and 'std::thread::native_handle_type' {aka 'ptw32_handle_t'})
     return __x._M_thread == __y._M_thread;
            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~

```

**Comment by jtv** [comment]
Long-standing known bug in MinGW.  :-(

This may help: http://hectorhon.blogspot.com/2018/05/building-libpqxx-on-msys2-mingw-64-bit.html

**Comment by jtv** [comment]
I just committed a workaround that should allow us to skip `<thread>` on MinGW.  Does that fix the problem for you?

**Comment by jtv** [comment]
@aqa5 I released libpqxx 7.5.0 a few hours ago, and it contains what I hope is a workaround for this problem.  Please let me know!

**Comment by aqa5** [comment]
Hello Jeroen Vermeulen, 

thank you very much. I was not able to test it yet. I will let you know.

**Comment by aqa5** [comment]
@jvt I've tried to compile the 7.5.0 release in my environment, but the error stays the same: `libpqxx-7.5.0\src\robusttransaction.cxx:16 -> mingw_8.1.0_i686-posix-dwarf/mingw32/lib/gcc/i686-w64-mingw32/8.1.0/include/c++/thread:273:26: error: no match for 'operator=='`

I will try to fix this on the mingw side as it was mentioned in another ticket.

**Comment by jtv** [comment]
Ah I see, I failed to remove the `#include <thread>` itself.  Could you try the latest master?

**Comment by aqa5** [comment]
That fixed it for robusttransaction.cxx, now it hat the same complaint in ` \libpqxx-master\src\util.cxx:18`. So I removed #include <thread> there too and reduced the last function to 
```
void pqxx::internal::wait_for(unsigned int microseconds)
{
  timeval tv{microseconds / 1'000'000u, microseconds % 1'000'000u};
  select(0, nullptr, nullptr, nullptr, &tv);
}
```
because it looks like the `PQXX_HAVE_SLEEP_FOR` macro is not defined, so I removed the `#if` to test if it works.

Compiling works now, so with these changes I consider this issue as solved. Of course you can't use them directly as I don't know why that macro is not defined and I performed a very clumsy surgery there. 


Now there is another issue, the linker complains about undefined refences. I don't think that is related but I cannot rule it out. Is that one known?

```
CMakeFiles\pqxx.dir/objects.a(binarystring.cxx.obj):binarystring.cxx:(.text+0x1a2): undefined reference to `PQunescapeBytea'
CMakeFiles\pqxx.dir/objects.a(binarystring.cxx.obj):binarystring.cxx:(.text+0x1af): undefined reference to `PQfreemem'
CMakeFiles\pqxx.dir/objects.a(blob.cxx.obj):blob.cxx:(.text+0xa6): undefined reference to `lo_open'
CMakeFiles\pqxx.dir/objects.a(blob.cxx.obj):blob.cxx:(.text+0x1b0): undefined reference to `lo_create'
[...]
CMakeFiles\pqxx.dir/objects.a(blob.cxx.obj):blob.cxx:(.text+0x15be): undefined reference to `lo_import'
CMakeFiles\pqxx.dir/objects.a(blob.cxx.obj):blob.cxx:(.text+0x16b7): undefined reference to `lo_import_with_oid'
CMakeFiles\pqxx.dir/objects.a(blob.cxx.obj):blob.cxx:(.text+0x17bf): undefined reference to `lo_export'
CMakeFiles\pqxx.dir/objects.a(connection.cxx.obj):connection.cxx:(.text+0x108): undefined reference to `PQencryptPassword'
CMakeFiles\pqxx.dir/objects.a(connection.cxx.obj):connection.cxx:(.text+0x114): undefined reference to `PQfreemem'
CMakeFiles\pqxx.dir/objects.a(connection.cxx.obj):connection.cxx:(.text+0x27d): undefined reference to `PQstatus'
[...]
CMakeFiles\pqxx.dir/objects.a(connection.cxx.obj):connection.cxx:(.text+0xa7f): undefined reference to `PQsocket'
CMakeFiles\pqxx.dir/objects.a(connection.cxx.obj):connection.cxx:(.text+0xabf): undefined reference to `PQprotocolVersion'
CMakeFiles\pqxx.dir/objects.a(connection.cxx.obj):connection.cxx:(.text+0xade): undefined reference to `PQserverVersion'
CMakeFiles\pqxx.dir/objects.a(connection.cxx.obj):connection.cxx:(.text+0xf55): undefined reference to `PQsetNoticeProcessor'
[...]
```
As I can't find these functions in your source except calls to them, it might have something to do with the PostgreSQL sources?

**Comment by tt4g** [comment]
Right, functions starting with PQ are defined in libpq.

The latest PostgreSQL libraries may have additional libraries to link with libpq.
The old CMake may not be able to find them.

Would you please check the path where libpq is installed to see if additional libraries exist?

**Comment by jtv** [comment]
Strange: I made the `#include <thread>` in util.cxx conditional on `PQXX_HAVE_SLEEP_FOR`.  So if the macro is not defined, it should _not_ be including that header.

Did you re-`configure` or re-`cmake` after pulling the latest update?

**Comment by aqa5** [comment]
>  So if the macro is not defined, it should _not_ be including that header.

Sorry, my mistake. The macro is defined and it included the header because of that. So the quick fix was to comment out those 3 lines (util.cxx:17..19)
 
> Did you re-`configure` or re-`cmake` after pulling the latest update?

I always started over by deleting the whole build-folder, that is what my .bat looks like: 

```
rmdir /q /s build
mkdir build
cd build
cmake .. -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=on
cmake --build .
cd ..
``` 
> The latest PostgreSQL libraries may have additional libraries to link with libpq.
The old CMake may not be able to find them.

The CMake  I use is a pretty recent 3.20.1. But the PostgreSQL server is pretty recent too (version 13). I could try an older / latest version 12 PostrgreSQL if that helps. 

The output of cmake: 
```
-- The CXX compiler identification is GNU 8.1.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/devtools/210407/mingw_8.1.0_i686-posix-dwarf/mingw32/bin/g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PostgreSQL: C:/Program Files/PostgreSQL/13/lib/libpq.lib (found version "13.2")
-- Looking for poll
-- Looking for poll - not found
-- Looking for PQencryptPasswordConn
-- Looking for PQencryptPasswordConn - not found
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Generating config.h
-- Generating config.h - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/devtools/210407/libpqxx-master/build
```
CMake did not report an error but I am not sure what those 'not found' mean. It doesn't really complain so I irgnored these messages. 

Might there be a problem with the PostgreSQL 13 installation being a 64bit version (as 32-bit versions are not supported anymore) and the MinGW compiler an i686 version (meaning 32 bit)?

>Would you please check the path where libpq is installed to see if additional libraries exist?

I am not sure what to look for. There are no sources in the PostgreSQL-folder that contain for example "PQunescapeBytea", except for one file defining that function as external. So i suspect libpq is an dll thats included dynamically. There are libpq.dll in the bin and lib folder.

Do I need the sources of libpq? Will I need to compile my own 32-bit Version of PostgreSQL 13?

**Comment by tt4g** [comment]
> Do I need the sources of libpq? Will I need to compile my own 32-bit Version of PostgreSQL 13?

Yes. 32bit library/application can not link 64bit library.
Should get 32bit PostgreSQL or use 64bit MinGW provided by MSYS or others.

**Comment by aqa5** [comment]
Ok, I will close this issue now, but read on. After compiling postgres in a 32bit version, I still had trouble linking the libpqxx to libpq. The reason was that I used a path with backslashes that was not escaped. You need to escape backslashes like this:
```
-DPostgreSQL_LIBRARY=C:\\path\\to\\postgresql_install\\lib\\libpq.dll
```
Otherwise you will get the exact same messages about `undefined references`

== **Please take all changes I made to the source code with a grain of salt.** == During the process I had to revert at least some changes to util.cxx.

**Comment by tt4g** [comment]
It is a specification that backslashes must be escaped; CMake uses backslashes to escape some special symbols. two consecutive backslashes are required for a backslash to be recognized as a character.

Also, you can use UNIX style when setting paths to CMake variables.

**Comment by jtv** [comment]
No worries - we made some changes, but we didn't just copy your local
changes.  I did change the code to avoid the use of <thread> on MinGW, but
that will solve the same problem for a lot of people.

**Comment by yeputons** [comment]
I strongly suspect that it's not _any_ mingw-w64 that is broken, it's the one shipped with Qt. Some people may have both Qt and some other build of mingw installed (e.g. msys2, mingw-builds, win-builds, tdm, etc) and they tend to interleave and conflict with each other.

E.g. #424 uses Qt, and the project I'm helping someone with also uses Qt and encountered this problem. In the meantime, I'm able to build small example with `sleep_for` without any troubles on my system. Did not test with libpqxx, though, as I don't have Postgresql installed yet.

**Comment by jtv** [comment]
Interesting!  Of course I've worked around it now, so it should no longer
happen, but it'd be nice to think that the actual cause of the problem
could get resolved some day.

And it'd be nice to know that we can start using <thread> without breaking
MinGW.
