### ISSUE TITLE
7.5.0 compiler errors on Windows

### ISSUE THREAD

**Issue by Tobias-Fischer** [jtv/libpqxx#442]
Hi, I'm trying to package the new 7.5.0 on conda forge. While Linux and OSX build fine, Windows doesn't: 
```
..\include\pqxx/internal/conversions.hxx(276): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
..\include\pqxx/internal/conversions.hxx(277): error C2059: syntax error: '...'
..\include\pqxx/internal/conversions.hxx(277): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
```

Full log: https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_build/results?buildId=308375

7.4.1 worked fine. I already tried using vs2019 instead of 2017 but same error.

**Comment by jtv** [comment]
Is that Visual Studio 2008?  You probably need a newer version.  It looks like this version just doesn't recognise folding expressions yet.

**Comment by jtv** [comment]
What I mean is: the output from that build you posted says "vs2008".  I'm _guessing_ that this means for some reason it's still stubbornly using Visual Studio 2008, even though you told it to use VS 2017 or VS 2019.

**Comment by jtv** [comment]
It gets a bit confusing: I see mention of Visual Studio components from 2008, 2015, and 2017.  But yes, it does look as if the C++ compiler is Visual Studio 2017.  Yet my appveyor build using Visual Studio 2019 thinks it's fine!

Difference in build options maybe..?

**Comment by jtv** [comment]
Might it be this one?

https://developercommunity.visualstudio.com/t/c17-fold-expressions-not-working-in-visual-studio/131610

**Comment by Tobias-Fischer** [comment]
Indeed sorry it was still using vs2017. Trying again with vs2019 now - will reopen if problem persists
