### ISSUE TITLE
How should we write a SELECT IN with bind parameters

### ISSUE THREAD

**Issue by nmoreaud** [jtv/libpqxx#443]
Hello,

Could you explain how we should write "select in" queries with bind values ?
Do we need to build 1 parameter per value ?
Should I use `make_dynamic_params` ?
I am using version 6.4 (ubuntu package), and I think there have been breaking changes on `exec_params` implementation between version 6 and 7.
Thanks

```
int minAge= 18;
vector<string> names{"Jack", "Bob", "Dylan"};
pqxx::work w(db);
pqxx::result r = db.exec_params("SELECT * FROM users WHERE minAge > $1 and first_name IN ($2)",
                                                 minAge, names);
w.commit();
```

**Comment by tt4g** [comment]
> Do we need to build 1 parameter per value ?

Yes, must append positional parameter to statement.

> Should I use make_dynamic_params ?

Yes.

Example:

```cpp
int minAge= 18;
std::vector<std::string> names{"Jack", "Bob", "Dylan"};

std::string statement = "SELECT * FROM users WHERE minAge > $1 and first_name IN (";

std::size_t startPos = 2;
std::size_t endPos = names.size() + startPos;
for (auto pos = startPos; pos < endPos; ++pos) {
    if (pos != startPos) {
        statement.append(",");
    }

    statement.append("$")
                    // NOTE: It is recommended to use std::to_chars() instead of std::to_string().
                    .append(std::to_string(pos));
}
statement.append(")");

pqxx::work w(db);
pqxx::result r = db.exec_params(statement, minAge, pqxx::prepare::make_dynamic_params(names));
w.commit();
```

**Comment by tt4g** [comment]
NOTE the number of parameters is limited to 16-bit integers due to communication protocol restrictions with the PostgreSQL server.
Therefore, no more than 32767 parameters can be bind.

https://www.postgresql.org/docs/13/protocol-message-formats.html:

> Int16
> The number of parameter values that follow (possibly zero). This must match the number of parameters needed by the query.

**Comment by jtv** [comment]
And in the latest libpqxx versions, use the "params" class for dynamic
parameters.  It's a lot more flexible than dynamic_params and can be more
efficient as well, so dynamic_parameters will go away eventually.

**Comment by jtv** [comment]
It does sound as if it would be nice to have some support for generating those parameter lists, wouldn't it?

**Comment by tt4g** [comment]
@jtv I once tried to see if I could automatically generate SQL that could bind list parameters, but I gave up.
In order to support parameter lists, we need to rewrite the parameter symbols in the statement.
This is because all symbols for the parameters that appear after the list parameters must be changed.

For example, `SELECT * FROM foo WHERE foo.bar IN (<LIST_HERE>) AND foo.baz = $1` will not work correctly unless  replace the `$1` in the parameter symbol.

As an alternative, instead of binding list parameters, I decided to use a template function that generates parameter symbols based on the size of the container, as shown below.

```cpp
#include <iostream>
#include <string>
#include <utility>
#include <vector>

template<typename SizeType>
class parameter_symbol_generated
{
public:

    std::string symbol_string;
    
    SizeType last_index;
    
    parameter_symbol_generated(
        std::string symbol_string,
        SizeType last_index)
        : symbol_string(std::move(symbol_string)),
          last_index(std::move(last_index))
    {

    }
    
};

template<typename Container, typename SizeType = Container::size_type>
parameter_symbol_generated<SizeType> generate_list_parameter_symbol(
    const Container &container,
    SizeType startIndex)
{
    std::string symbols;

    SizeType lastIndex = container.size() + startIndex;
    for (auto index = startIndex; index < lastIndex; ++index) {
        if (index != startIndex) {
            symbols.append(",");
        }

        symbols.append("$")
                // NOTE: It is recommended to use std::to_chars() instead of std::to_string().
                .append(std::to_string(index));
    }

    return parameter_symbol_generated{std::move(symbols), std::move(lastIndex)};
}

int main()
{
    std::string sql = "SELECT * FROM foo WHERE foo.bar IN (";
    std::vector<int> bars{1, 2, 3, 4, 5};
    
    auto generated = generate_list_parameter_symbol(bars, 1);
    sql.append(std::move(generated.symbol_string))
        .append(") AND foo.baz = $")
        .append(std::to_string(generated.last_index));

    std::cout << sql;
    
    return 0;
}
```

**Comment by jtv** [comment]
_Definitely_ don't use `std::string` for this.  :-)  But you could use `pqxx::to_string`.  (No I didn't use a name that was already in the standard — I was there first!)

What if we had a simple counting variable that produces a series of `$1`, `$2`, `$3`, etc. on demand?  Then we could have a completely separate function for "make me a list of _n_ variables, using this counter."

And then after that, maybe we could see if any useful patterns emerged that we could use in `pqxx::params` to make the parameter-passing easier to get right.

**Comment by tt4g** [comment]
It is a good idea to have a counter to share the number of parameters between developers and pqxx.
The counter could be implemented like a statement builder.

```cpp
#include <string>
#include <string_view>
#include <utility>

class dynamic_statement_builder
{
public:
    dynamic_statement_builder()
        : count_(0), statement_()
    {
    }

    dynamic_statement_builder(std::string statement)
        : count_(0), statement_(std::move(statement))
    {
    }

    const std::string& statement() const &
    {
        return this->statement_;
    }

    dynamic_statement_builder append_parameter() &
    {
        increment_and_append_parameter();

        return *this;
    }

    template<typename Container>
    dynamic_statement_builder append_parameter(const Container& container) &
    {
        auto count = std::size(container);
        for (auto i = 0; i < count; ++i) {
            increment_and_append_parameter();
        }

        return *this;
    }

    dynamic_statement_builder append(std::string_view sql) &
    {
        this.statement_.append(sql);

        return *this;
    }

private:
    std::size_t count_;

    std::string statement_;

    void increment_and_append_parameter()
    {
        this->statement_.append("$").append(pqxx::to_string(++this->count_);
    }
};
```

**Comment by jtv** [comment]
ISTM integrating the counter into a statement builder would complicate the "IN" thing we're trying to support.  I'd rather let the caller worry about how to build the statement, and just provide a counter that converts to a `string_view`, plus a little add-on to generate the `IN (...)` list.

There's so many different styles of composing strings, from super-compile-time-optimised to clear-and-convenient.  I don't want to dictate a choice there if I don't have to.

**Comment by jtv** [comment]
The latest commit in `master` has this new helper class, called `placeholders`.  Maybe give it a go?

**Comment by jtv** [comment]
I'll close the ticket now.  Taking us back to... zero issues!
