### ISSUE TITLE
Batch Inserts/Update Statements

### ISSUE THREAD

**Issue by vitruvvius** [jtv/libpqxx#446]
What's the community's best method to batch insert, say 80 rows? Currently, I am building the long update string myself and was hoping there might be an existing api

**Comment by jtv** [comment]
For inserting _new_ rows, use `stream_to`.

For updating _existing_ rows, consider a prepared statement, or a pipeline.  But you'll have to test what works best for you.

**Comment by vitruvvius** [comment]
Btw thanks so much for the swift response!

**Comment by jtv** [comment]
No need to know the order of the columns.  Look at the factory functions in
stream_to.  You specify the list of columns you wish to write, and that's
the order in which you'll write them - regardless of the order in which
they occur in the table.

**Comment by vitruvvius** [comment]
great!
