### ISSUE TITLE
Why std::string_view ? pqxx::stream_to

### ISSUE THREAD

**Issue by gelldur** [jtv/libpqxx#447]
Hello
I was using a lot `pqxx::stream_to` now it is deprecated and I should switch to: `pqxx::stream_to::table`.
Problem here is that I was using `std::string` for columns, now you force using `std::string_view` which is not owning version...

Even example form your documentation do not compile:
```
pqxx::stream_to stream{
    tx,
    "score",
    std::vector<std::string>{"name", "points"}};
for (auto const &entry: scores)
    stream << entry;
stream.complete();
```

```
include/pqxx/stream_to.hxx:401:13: error: too many arguments to function call, expected single argument 'identifier', have 2 arguments
            separated_list(",", columns_begin, columns_end, [&tx](auto col) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I understand that std::string_view is "better" or "less copy" but it can't be copy-replace for previous std::string, std::string_view don't have to be null terminated :(

----

Now it is almost impossible to create vector<string>  then convert it (somehow) to initializerlist of string view... IMO bad

**Comment by gelldur** [comment]
My example quick fix (I didn't test, only check if compiles)

```
template <typename Container>
static stream_to create_stream(transaction_base& tx,
							   std::string_view tableName,
							   const Container& container)
{
	return stream_to::raw_table(
		tx,
		tx.quote_name(tableName),
		separated_list(",", std::begin(container), std::end(container), [&tx](auto col) {
			return tx.quote_name(*col);
		}));
}

template <typename T>
static stream_to create_stream(transaction_base& tx,
							   std::string_view tableName,
							   std::initializer_list<T>&& container)
{
	return create_stream(tx, tableName, std::forward<std::initializer_list<T>>(container));
}
```

**Comment by jtv** [comment]
You don't need to keep the columns string alive after you've constructed the stream.  And `std::string` has an `operator string_view` so the conversion should be easy.

Maybe I'm just not understanding the problem?

**Comment by gelldur** [comment]
Sorry I was little bit frustrated. Ok so example problem:

```
std::vector<std::string> myColumns;
if(myObject.field.has_value()) // optional
{
    myColumns.push_back("columnA"); // here maybe I want to create a string so vector can't be a string_view
    myValues.push_back(...);
}

// repeat such if for many columns then I can't call
pqxx::stream_to stream{
    tx,
    "tableName",
    myColumns};

    stream << myValues;
```

That was old way, new way I should replace it with `pqxx::stream_to::table()` but it doesn't compile or even work as I can't convert vector of string to initializerlist of string view. At least I didn't find any easy replacement.

**Comment by jtv** [comment]
OK that helps, thanks.

Are you on C++20?  Because if so, I was planning to generalise this using
Concepts.  The idea is that calls like this will accept "anything I can
iterate that contains some kind of string type."  I can't wait to move to
C++20 as the baseline and I've already been building this kind of thing for
binary strings.

**Comment by gelldur** [comment]
Mostly C++17 in near future shifting to C++20.
I agree that approach with "anything iterable" is great.

It would be even nice to be able do something like this with `stream_to` 

```
pqxx::stream_to stream{tx,"table_name"};

stream.write_column("column_name", value);
...
```

**Comment by JadeMatrix** [comment]
FWIF, the old generic `separated_list()` I added in #138 did support any iterable, as well as `std::tuple`.

**Comment by jtv** [comment]
I'm about to push code that _should_ fix this.  Would you mind testing it?  The ticket will close automatically, but I'll reopen it so we can continue the conversation.

**Comment by jtv** [comment]
@gelldur this latest revision should support what you need, so long as you configure for C++20.  Please try and let me know!

In the meantime, I'll write some tests.  O:-)

**Comment by gelldur** [comment]
@jtv currently I'm not able to test it with c++20 support.

**Comment by jtv** [comment]
I can try to enable it in C++17, but it'll be a bit trickier.  I'll have to mess with `enable_if`.  I'll have to look into that later.

**Comment by gelldur** [comment]
My tmp fix which I mention on the beginning `create_stream` seems to work for me.

**Comment by jtv** [comment]
OK, I'll close this ticket then.  Just be aware that the problem will magically disappear when you move your baseline to C++20.
