### ISSUE TITLE
connection::encrypt_password() is a bad joke and dangerous

### ISSUE THREAD

**Issue by Ben-Dover-77** [jtv/libpqxx#448]
md5 and scram are both deprecated, unsafe and using them is the same as saving your passwords in plain text -> pointless. Because it is implemented too many people will use it and think they did everything right.

remove that function asap or replace it with scrypt or argon2.

**Comment by sugondese-nuts** [comment]
Well, as harsh as it sounds, Mr. Ben-Dover-77 is absolutely right here. Still proposing MD5 as a viable hashing algorithm, let alone suggesting it as default, is an insult to the cryptographers who spent years working out a multitude of secure password hashes. You should really extend the pool of available hashes, and, most importantly, kick out md5 and scram.

**Comment by KayEss** [comment]
I guess I can see what you're trying to achieve here, but this is not the way to raise an issue. I don't believe that you would talk like this to a stranger in person so don't see why you think it would be OK here.

**Comment by jtv** [comment]
Especially not a stranger who works hard to give you something for free.  At any rate, I'm just the messenger.  Your beef is with `PQencryptPasswordConn` in libpq, so please take it there.
