### ISSUE TITLE
Need documentation on BYTEA handling.

### ISSUE THREAD

**Issue by AlastairGrowcott** [jtv/libpqxx#450]
I have just moved the version of pqxx that we are using forward, and as a result binarystring is now deprecated. The deprecation message is not helpful.

I now cannot find a nice way to convert to and from the "std::string" that my code uses (which handles binary data just fine) to "std::basic_string<std::byte>" which is a very verbose typename and difficult to use.

I have ended up having to implement helper functions like the one below throughout my code:

    std::basic_string<std::byte> MyDBClass::_StringToBlob(const std::string &data)
    {
        std::basic_string<std::byte>  result;
    
        result.assign(reinterpret_cast<const std::byte *>(data.data()), data.size());

        return result;
    }

I really don't like doing this.

I am sure that, as part of deprecating "binarystring", you have thought about a good, concise, way of handling binary data in the database. It would be great if you could enhance the documentation with that information. It would also be good if you could update the documentation on "binarystring" to mention it is deprecated and link to the new documentation on how to handle binary data.

**Comment by jtv** [comment]
You don't have to use `string`.  You can use `string_view` — which means you don't need to copy the data.

**Comment by jtv** [comment]
OK, I just added a documentation page and a helper.
