### ISSUE TITLE
E1919 parameter pack "Args" was referenced but not expanded - conversions.hxx and a linking error!!

### ISSUE THREAD

**Issue by forexstudies** [jtv/libpqxx#456]
so I checked out the code on Windows 10, compiled it using the following command

_cmake -S libpqxx-master -B build -DCMAKE_INSTALL_PREFIX="libpqxx" -A x64 -G "Visual Studio 16 2019" -DPostgreSQL_ROOT="MY_POSTGRESQL_13_FOLDER"_

I got the following output:
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The CXX compiler identification is MSVC 19.29.30037.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/MVisualStudio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PostgreSQL: MY_POSTGRESQL_13_FOLDER/lib/libpq.lib (found version "13.2")
-- Looking for poll
-- Looking for poll - not found
-- Looking for PQencryptPasswordConn
-- Looking for PQencryptPasswordConn - not found
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Generating config.h
-- Generating config.h - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/CPPSources/build

and finally the command:

_cmake --build build --target INSTALL  --config Release_
lots of warning but ultimately was a success

In my sample project ConsoleApplication1, i added the include folder and lib, but when I try to compile I get the following error:
am i missing something?

Rebuild started...
1>------ Rebuild All started: Project: ConsoleApplication1, Configuration: Debug x64 ------
1>ConsoleApplication1.cpp
1>MY_INCLUDE_FOLDER\pqxx\field.hxx(334,5): warning C5051: attribute 'unlikely' requires at least '/std:c++latest'; ignored
1>MY_INCLUDE_FOLDER\include\pqxx\field.hxx(372,5): warning C5051: attribute 'unlikely' requires at least '/std:c++latest'; ignored
1>MY_INCLUDE_FOLDER\include\pqxx\pipeline.hxx(192,5): warning C5051: attribute 'unlikely' requires at least '/std:c++latest'; ignored
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "int __cdecl pqxx::internal::check_pqxx_version_PQXX_VERSION_MAJOR_PQXX_VERSION_MINOR(void)" (?check_pqxx_version_PQXX_VERSION_MAJOR_PQXX_VERSION_MINOR@internal@pqxx@@YAHXZ) referenced in function "void __cdecl pqxx::check_version(void)" (?check_version@pqxx@@YAXXZ)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::internal::demangle_type_name(char const * const)" (?demangle_type_name@internal@pqxx@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEBD@Z) referenced in function "??__E?$type_name@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@pqxx@@YAXXZ" (??__E?$type_name@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@pqxx@@YAXXZ)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: char const * __cdecl pqxx::connection::dbname(void)const " (?dbname@connection@pqxx@@QEBAPEBDXZ) referenced in function main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: void __cdecl pqxx::connection::close(void)" (?close@connection@pqxx@@QEAAXXZ) referenced in function "public: __cdecl pqxx::connection::~connection(void)" (??1connection@pqxx@@QEAA@XZ)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "private: void __cdecl pqxx::connection::init(char const * const)" (?init@connection@pqxx@@AEAAXQEBD@Z) referenced in function "public: __cdecl pqxx::connection::connection(char const * const)" (??0connection@pqxx@@QEAA@QEBD@Z)

**Comment by jtv** [comment]
That's odd.  The preprocessor was supposed to substitute the major & minor libpqxx version numbers into that function name.  Instead, the function name includes the variable names verbatim.

The function exists for just one purpose: to detect the situation where your compiler is picking up the headers from one libpqxx version, but the binary from another libpqxx version.

**Comment by jtv** [comment]
More generally though, it looks as if you have a linking problem.  Usually
this kind of problem means that either you're not linking to libpqxx
properly or you're linking Debug binaries to Release binaries.

I don't see the parameter pack problem anywhere.

**Comment by forexstudies** [comment]
I thought I would attach the error here. its coming from conversions.hxx
![vs-error](https://user-images.githubusercontent.com/35479791/121806383-f7d2a200-cc92-11eb-9932-fb7290d083f1.PNG)

**Comment by forexstudies** [comment]
Well was able to add the pqxx.lib and libpq.dll in postgresql client source, the error has been cleared and I can compile and build the exe successfully, the trouble is I can't run it, I am getting the following error: 

"The code execution cannot proceed because LIBPQ.dll was not found...."

**Comment by jtv** [comment]
To use a dynamic library, such as libpq.dll, you must have it present where
the system can find it at run time.  For example you could keep it in the
same directory as libpqxx.dll.

Not sure how the parameter pack error can make sense...  How recent is your
compiler?

**Comment by forexstudies** [comment]
I will try to copy the library, the parameter pack error has disappeared as well when I linked the correct libs. My compiler is recent

**Comment by jtv** [comment]
Mysterious disappearing error...  That's a little worrying!  If it works
now, let's just close this ticket, but if the problem comes back, feel free
to file a new one.

**Comment by forexstudies** [comment]
Thanks for your help
I have added the postgresql bin directory to the environment path, my sample program is running fine

**Comment by AllLuckBased** [comment]
I am getting this same error quite often. Although it runs even with the error.
![image](https://user-images.githubusercontent.com/42518556/188666298-90c04cef-4b5e-4059-9441-219473361a00.png)

**Comment by jtv** [comment]
But this is just the warning from (some code checker in) the IDE, right?  ISTR we ran into this and we ended up concluding that it was probably just a shortcoming in the checker.

Does it actually stop you from compiling?

**Comment by AllLuckBased** [comment]
No, it still works, but I was not sure if it meant anything serious. So you are saying it is IDE's fault then, and can be safely ignored?

**Comment by jtv** [comment]
Unfortunately yes, it does look like that.  Of course ignoring warnings is a bad habit, and I wish I had a way to work around it.

**Comment by KayEss** [comment]
Looks like it might be that you've given the argument pack template argument a name (`args`), but then don't use that name. Maybe changing the line to `template<typename T, typename... Args, Args...>` will be sufficient? There is a warning that can be turned on to warn about unused named arguments -- I'll dig it out for your maintenance mode.

**Comment by jtv** [comment]
Good idea @KayEss!

@AllLuckBased would you mind trying this for us?  If it works, I'll be happy to get the warning out of the way.

**Comment by jtv** [comment]
Oh wait.  The warning box is hiding a piece of code that _does_ mention `args...`  So I doubt that's going to work.
