### ISSUE TITLE
pqxx::nontransaction seems to start a transaction.  

### ISSUE THREAD

**Issue by looopTools** [jtv/libpqxx#457]
To reduce time for a single `SELECT` statement I am utilising multi-threading to perform concurrent `SELECT` statements and for that to work I expect I need to use `pqxx::nontransaction`. 
However, when I do I get this error: 

```
libc++abi: libc++abi: terminating with uncaught exception of type pqxx::usage_error: Started new transaction while transaction was still active.terminating with uncaught exception of type pqxx::usage_error: Started new transaction while transaction was still active.
```

Which to me indicates that a transaction is started. 
The code for spawning the threads is like follows: 
```c++
            threads.at(i) = std::thread([this, &params, &seen_fingerprints, off, end](){
                std::string params_list = "";

                size_t param_index = 1;

                std::vector<std::basic_string<std::byte>> _sub_params; 
                
                for (size_t i = off; i < end; ++i)
                {
                    params_list = fmt::format("{},", param_index);
                    param_index = param_index + 1;
                    _sub_params.emplace_back(params.at(off + i));
                }
                
                params_list = params_list.substr(0, params_list.size() - 1);

                std::string query = fmt::format("SELECT fingerprint FROM basis_registry WHERE fingerprint IN {}", params_list);

                pqxx::nontransaction thread_worker(this->m_conn);
                pqxx::result rows = thread_worker.exec_params(query, pqxx::prepare::make_dynamic_params(_sub_params));

                for (const auto& row : rows)
                {
                    auto b_fingerprint = row[0].as<std::basic_string<std::byte>>();
                    auto fingerprint = helpers::decode_fingerprint(b_fingerprint);
                    seen_fingerprints[fingerprint] = true;
                }
            });
``` 

With this being the most important part.  
```c++
                pqxx::nontransaction thread_worker(this->m_conn);
                pqxx::result rows = thread_worker.exec_params(query, pqxx::prepare::make_dynamic_params(_sub_params));

                for (const auto& row : rows)
                {
                    auto b_fingerprint = row[0].as<std::basic_string<std::byte>>();
                    auto fingerprint = helpers::decode_fingerprint(b_fingerprint);
                    seen_fingerprints[fingerprint] = true;
                }
```

Am I misunderstanding how `pqxx::nontransaction` is supposed to work?

**Comment by looopTools** [comment]
and I have checked that for all previous `pqxx::work` instance the `commit` command have been called.

**Comment by tt4g** [comment]
Do not use a connection in multiple threads at the same time.

The client sends SQL statements to the server through a connection, and the server parses and executes the SQL statements and finally sends the results back to the client.
These processes are stateful, and the next SQL statement cannot be sent before the server has completed its processing.

Create a dedicated connection for each thread.

**Comment by jtv** [comment]
The error comes from libpqxx itself, not the server.  You _did_ start a transaction from the libpqxx perspective — just not from the server's perspective.  And it would be totally incorrect to open one transaction while another was still open on the same connection.

(I can't really tell from the code what your greater architecture is when it comes to handling the connections, but @tt4g is correct.  You _can_ create a connection in one thread and hand it off to another, but you _can't_ let multiple threads then access that connection concurrently.  At the very least you'd need careful locking.)

**Comment by looopTools** [comment]
Ah okay thankt @tt4g and @jtv I had not caught that `pqxx::connection` worked in that way. 
Thanks a lot :) 
And yes of cause it would incorrect to open two transactions, I just assumed `pqxx::nontransaction` would not cause that :) 

Again thanks a lot :)
