### ISSUE TITLE
std::filesystem error

### ISSUE THREAD

**Issue by VNMNTN** [jtv/libpqxx#458]
Hello! I'm trying build `libpqxx` library with cmake in my dockerfile. Current build be crashed. Build with cache (1 week ago) is correctly. Please, help!..

My dockerfile: https://gitlab.com/alex_malder/configs/-/blob/dev/api/Dockerfile

Informative error:

```
/usr/bin/ld: CMakeFiles/runner.dir/unit/test_blob.cxx.o: in function `std::filesystem::__cxx11::path::path<char [30], std::filesystem::__cxx11::path>(char const (&) [30], std::filesystem::__cxx11::path::format)':
test_blob.cxx:(.text._ZNSt10filesystem7__cxx114pathC2IA30_cS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC2IA30_cS1_EERKT_NS1_6formatE]+0x5e): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/CMakeFiles/runner.dir/build.make:1301: test/runner] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: test/CMakeFiles/runner.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
ERROR: Service 'app' failed to build: The command '/bin/sh -c git clone https://github.com/jtv/libpqxx && cd libpqxx && cmake -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/ . && make -j4 && make install clean' returned a non-zero code: 2
```

**Comment by jtv** [comment]
That was quick!  I only just committed that change, and found that it failed on older gcc than the ones I have installed.

Adding `-lstdc++fs` to your link options should solve the problem.  And I just added a check to the `configure` script to automate this.

To be honest though, I was hoping that CMake would take care of this problem out of the box.  Evidently it doesn't, so we'll have to automate it there as well.  Do you happen to know off the top of your head how, in CMake, we specify "if this piece of code won't link, add this link option"?

**Comment by jtv** [comment]
I've been able to reproduce the problem, but only with gcc 8, which is pretty old.  The fix seems to work out of the box with CMake.

For some reason though, the new test crashes with gcc 8 in the autotools build!  Segfault in the destructor of the `std::filesystem::path`'s internal `vector` of path components.  Works fine in CMake.

The traceback looks weird...  Almost as if the destructor is recursing:
```
Program received signal SIGSEGV, Segmentation fault.

std::vector<std::filesystem::__cxx11::path::_Cmpt, std::allocator<std::filesystem::__cxx11::path::_Cmpt> >::~vector() ()                                                                                                                          
(gdb) bt
#0  std::vector<std::filesystem::__cxx11::path::_Cmpt, std::allocator<std::filesystem::__cxx11::path::_Cmpt> >::~vector() ()                                                                                                                      
#1  std::filesystem::__cxx11::path::~path() ()
#2  std::filesystem::__cxx11::path::_Cmpt::~_Cmpt() ()
#3  void std::_Destroy<std::filesystem::__cxx11::path::_Cmpt>(std::filesystem::__cxx11::path::_Cmpt*) ()
#4  void std::_Destroy_aux<false>::__destroy<std::filesystem::__cxx11::path::_Cmpt*>(std::filesystem::__cxx11::path::_Cmpt*, std::filesystem::__cxx11::path::_Cmpt*) ()                                                                           
#5  void std::_Destroy<std::filesystem::__cxx11::path::_Cmpt*>(std::filesystem::__cxx11::path::_Cmpt*, std::filesystem::__cxx11::path::_Cmpt*) ()                                                                                                 
#6  void std::_Destroy<std::filesystem::__cxx11::path::_Cmpt*, std::filesystem::__cxx11::path::_Cmpt>(std::filesystem::__cxx11::path::_Cmpt*, std::filesystem::__cxx11::path::_Cmpt*, std::allocator<std::filesystem::__cxx11::path::_Cmpt>&) ()  
#7  std::vector<std::filesystem::__cxx11::path::_Cmpt, std::allocator<std::filesystem::__cxx11::path::_Cmpt> >::~vector() ()                                                                                                                      
#8  std::filesystem::__cxx11::path::~path() ()
#9  (anonymous namespace)::test_blob_accepts_std_filesystem_path() ()
#10 main ()
```
_(Edited for legibility)_

**Comment by jtv** [comment]
Worse, there's different libraries we need to link, for different older compilers.  This will take some real work.  :-(

**Comment by jtv** [comment]
Okay, I think I have a partial solution now:
 * The `configure` build checks whether it needs to link in `stdc++fs` or `c++fs`, or neither.
 * The CMake build checks checks whether it needs to link in `stdc++fs`.

That may still leave problems for older clang versions (say version 7, which I don't have) when building with CMake.  And, on my local system, the `configure` build with gcc 8 has that weird destructor crash... _on my local system._  Yet it works in CircleCI with Debian and gcc 8.  So perhaps that's a bug in the older compiler support.

Does anyone know how to make CMake try various alternative libraries until a piece of test code will link?

**Comment by VNMNTN** [comment]
Oh, I tried gcc 11.1.0. `FROM gcc:latest` (and` gcc:10` works too)) in dockerfile and i think is a nice solution.
I dont need older compiler and i teel you Big Thanks!
