### ISSUE TITLE
Wrong version check

### ISSUE THREAD

**Issue by carpikes** [jtv/libpqxx#459]
I think che macro concatenation operator (##) in version.hxx is not used correctly.

You would expect that the compiled check function is `check_pqxx_version_7_5()`
but instead is this one:
```
$ readelf -s /usr/lib/libpqxx.so --wide | c++filt | grep -i "check_pqxx"
pqxx::internal::check_pqxx_version_PQXX_VERSION_MAJOR_PQXX_VERSION_MINOR()
```

**Comment by jtv** [comment]
Yup, you're right.  Crazy thing is, I'm sure this worked in the past.

Anyway, I'm testing a fix now.
