### ISSUE TITLE
Build failing to find -lpgcommon and -lpgport ?

### ISSUE THREAD

**Issue by abrownsword** [jtv/libpqxx#460]
I've recently started having a build problem on a newly rebuilt host.  My link is complaining about this:

```
[ 85%] Linking CXX shared library libpqxx-7.5.so
/usr/bin/ld: cannot find -lpgcommon
/usr/bin/ld: cannot find -lpgport
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm pretty sure this is because I've not installed something, but I can't figure out what that might be.  I have an Ubuntu 20.x.x distro, and have both postgresql12 and postgresql13 installed, along with the libpq client library.

Any suggestions?

**Comment by tt4g** [comment]
Could you try to rebuild libpqxx?

When you build libpqxx with CMake, the link paths of PostgreSQL libraries are recorded, and when you link libpqxx, the recorded PostgreSQL libraries will be added to the link target.
If the PostgreSQL libraries were updated when you rebuilt your host machine, the PostgreSQL libraries to be linked that are recorded may have been lost.

**Comment by abrownsword** [comment]
This happens from an absolutely clean build -- ie destroy the build folder and start again.

**Comment by jtv** [comment]
These libraries shouldn't even come up at all.  From libpqxx's perspective, they should be entirely hidden inside libpq.

In fact, I just read that libpgcommon and libpgport are only available as static libraries.  Is it possible that you accidentally told the linker not to link any static libraries at all?

**Comment by abrownsword** [comment]
Well almost all of my project is static libs, so I don’t think so.  I’m not that familiar with libpqxx’s switches though.  What should I set or not set?

**Comment by jtv** [comment]
It really oughtn't matter, and the defaults should be good enough for most uses.  I have no trouble building with clang-11 on Ubuntu 21.04, whether using `configure` or CMake.  And before I upgraded this system, it worked fine on Ubuntu 20.10.

**Comment by tt4g** [comment]
`pgcommon` and `pgport` exist in the search path of the linker?
It seems that the list of library search paths can be got with the following command.
`ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012`

**Comment by abrownsword** [comment]
Should the cmake find library do that?

**Comment by tt4g** [comment]
I think the only thing not finding the library is the `ld` command.

**Comment by abrownsword** [comment]
Ah, my fault -- I found some old stuff for referring to the local copy of the pg library rather than trying to search the system for it, from back before it was an apt package and I was building from source.  Fortunately ARM64 is catching up with its packages now.

**Comment by abrownsword** [comment]
In the postgresql 13 pgxs Makefile.global I found the following comment which seems relevant as this is the source of the linker arguments (still trying to grok it):
```
# libpq_pgport is for use by client executables (not libraries) that use libpq.
# We force clients to pull symbols from the non-shared libraries libpgport
# and libpgcommon rather than pulling some libpgport symbols from libpq just
# because libpq uses those functions too.  This makes applications less
# dependent on changes in libpq's usage of pgport (on platforms where we
# don't have symbol export control for libpq).  To do this we link to
# pgport before libpq.  This does cause duplicate -lpgport's to appear
# on client link lines, since that also appears in $(LIBS).
# libpq_pgport_shlib is the same idea, but for use in client shared libraries.
ifdef PGXS
libpq_pgport = -L$(pkglibdir) -lpgcommon -lpgport $(libpq)
libpq_pgport_shlib = -L$(pkglibdir) -lpgcommon_shlib -lpgport_shlib $(libpq)
else
libpq_pgport = -L$(top_builddir)/src/common -lpgcommon -L$(top_builddir)/src/port -lpgport $(libpq)
libpq_pgport_shlib = -L$(top_builddir)/src/common -lpgcommon_shlib -L$(top_builddir)/src/port -lpgport_shlib $(libpq)
endif
```

**Comment by abrownsword** [comment]
It appears that installing the package `postgresql-server-dev-13` makes these two libraries available, and the linker no longer complains about not being able to find them.  It seems very strange that this package is required in order to build with the client libraries and yet isn't a package dependency.

**Comment by jtv** [comment]
That sounds like something to bring up with the package maintainer then, @abrownsword!  It's annoying but sneaky little dependencies on the server-dev packages do pop up from time to time.

**Comment by jtv** [comment]
If there's no further news, I'll close this ticket in the coming days.
