### ISSUE TITLE
⚠ C:\Program Files (x86)\libpqxx\include/pqxx/internal/concat.hxx:36:24: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]    char *here = buf.data();

### ISSUE THREAD

**Issue by danbugs** [jtv/libpqxx#461]
**Error message:** C:\Program Files (x86)\libpqxx\include/pqxx/internal/concat.hxx:36:24: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]    char *here = buf.data();

### How to replicate the error?

I installed libpqxx following [this](https://www.youtube.com/watch?v=qDiC1Wja6Og&ab_channel=Instituteofmarxism-leninism) tutorial up until 10:45. If this is relevant but you don't want to watch the video, [here's](http://en.wiki.imlint.org/Pqxx_tutorial) a text version of it.

After that, using VSCode, I tried running the code from the tutorial:
```
#pragma once

#include <string>
#include <iostream>
#include <pqxx/pqxx>

int main()
{
    std::string connectionString = "host=localhost port=5432 dbname=test user=postgres password =123454321";

    try
    {
        pqxx::connection connectionObject(connectionString.c_str());

        pqxx::work worker(connectionObject);

        pqxx::result response = worker.exec("SELECT * FROM users");

        for (size_t i = 0; i < response.size(); i++)
        {
            std::cout << "Id: " << response[i][0] << " Username: " << response[i][1] << " Password: " << response[i][2] << " Email: " << response[i][3] << std::endl;
        }
    }
    catch (const std::exception& e)
    {
        std::cerr << e.what() << std::endl;
    }

    system("pause");
}
```

With the following `Makefile`:
```
CC=g++
LIBPQXX="C:\Program Files (x86)\libpqxx\include"
default:
	${CC} -I$(LIBPQXX) main.cpp -o .\out
```

Now, running `make`, shows the error. 

### Sidenote

I thought that it might be an issue of the C++ version but when I try to add the `-std=c++20` flag, I get: 
```
error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'?
```

AND... From Googling, it looks like I might have to update my G++? It's at 8.3.0 🤷‍♂️ — not super sure how to update it on Windows 10, tbh tho.

**Comment by jtv** [comment]
Your gcc version should juuuust be able to manage.  But it's old enough
that C++20 hadn't been standardised yet, so yes, ask for c++2a or c++17.
(And if you can, upgrade gcc.)

One thing that jumped out at me right away: I wouldn't go slapping `#pragma
once` on everything.  Some of the include chains can get a little
complicated.  I hope that pragma has no effect when used in your main
translation unit though -- I expect it to have an effect only when used in
a header.

Next: you're inserting a field in an output stream.  I'm not even sure
that's supposed to work...  Try replacing `response[i][0]` with
`response[i][0].c_str()`, for instance.  That'll insert into the stream a
C-style string representing the field's value.

By the way, I'd never heard of anyone doing videos teaching libpqxx, so
that just made my day!  I did recently hear from an old friend on the other
side of the world who'd been taught libpqxx by someone, used it in all his
projects, and then one day discovered that I'd written it.  Love these
moments.  Will watch that video later.

**Comment by danbugs** [comment]
> One thing that jumped out at me right away: I wouldn't go slapping `#pragma
once` on everything.  Some of the include chains can get a little
complicated.  I hope that pragma has no effect when used in your main
translation unit though -- I expect it to have an effect only when used in
a header.

That's a good point — I've removed the `#pragma once`.

> Next: you're inserting a field in an output stream.  I'm not even sure
that's supposed to work...  Try replacing `response[i][0]` with
`response[i][0].c_str()`, for instance.  That'll insert into the stream a
C-style string representing the field's value.

I've managed to run the code on Visual Studio sooo... It should work (?) 🤔

Regardless, I've added `.c_str()` to all the `response[i][x]` fields!

> Your gcc version should juuuust be able to manage.  But it's old enough
that C++20 hadn't been standardised yet, so yes, ask for c++2a or c++17.
(And if you can, upgrade gcc.)

I'm pretty sure I got g++ from installing Visual Studio's "Desktop Development with C++" module. That said, I attempted updating stuff there but my g++ version remained the same. I tried googling how to update my g++ on Windows and couldn't really find anything that fit my situation. If you have any tips on how that can be done, I'd very much appreciate it 😅.

Anyway, adding `-std=c++2a` or `-std=c++17` still yields an error (the same one for both options) but it's different from before! Now, I get:
```
C:\Program Files (x86)\libpqxx\include/pqxx/internal/conversions.hxx:39:10: error: 'strnlen_s' was not declared in this scope
   return strnlen_s(text, max);
          ^~~~~~~~~
C:\Program Files (x86)\libpqxx\include/pqxx/internal/conversions.hxx:39:10: note: suggested alternative:  
strnlen'
   return strnlen_s(text, max);
          ^~~~~~~~~
          strnlen
```

I'm not sure how useful that is 🤷‍♂️.

> By the way, I'd never heard of anyone doing videos teaching libpqxx, so
that just made my day!  I did recently hear from an old friend on the other
side of the world who'd been taught libpqxx by someone, used it in all his
projects, and then one day discovered that I'd written it.  Love these
moments.  Will watch that video later.

I'm glad! Plus, I should add that the video was actually very helpful for getting started — tbh, the README file sort of confused me so, watching someone else going through setup, clarified a lot. It might even warrant a place in your docs!

**Comment by jtv** [comment]
Which version of libpqxx are you building?  I don't recall off the top of my head what I did with that `strnlen_s` call, but it's not there now.  There may be a newer libpqxx that solves the problem.

And by the way, if anything in the README is unclear, please file a bug about it!  That's how we improve.

**Comment by danbugs** [comment]
I was building 7.4.1 — regardless, I updated it to the latest version in master now and... I'm getting a different error 🎉

> Which version of libpqxx are you building? I don't recall off the top of my head what I did with that strnlen_s call, but it's not there now. There may be a newer libpqxx that solves the problem.
```
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/array.hxx:14,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/array:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:2,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/params.hxx: In member function 'void pqxx::placeholders<COUNTER>::next()':
C:\Program Files (x86)\libpqxx\include/pqxx/compiler-public.hxx:117:24: error: expected identifier before '[' token
 #  define PQXX_LIKELY [[likely]]
                        ^
C:\Program Files (x86)\libpqxx\include/pqxx/params.hxx:169:7: note: in expansion of macro 'PQXX_LIKELY'
       PQXX_LIKELY
       ^~~~~~~~~~~
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/connection.hxx:37,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/transaction_base.hxx:32,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/dbtransaction.hxx:19,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob.hxx:33,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:4,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/params.hxx: In lambda function:
C:\Program Files (x86)\libpqxx\include/pqxx/params.hxx:171:7: error: expected '{' before '++' token
       ++m_buf[m_len - 1];
       ^~
C:\Program Files (x86)\libpqxx\include/pqxx/params.hxx: In member function 'void pqxx::placeholders<COUNTER>::next()':
C:\Program Files (x86)\libpqxx\include/pqxx/params.hxx:171:9: error: expected ';' before 'm_buf'
       ++m_buf[m_len - 1];
         ^~~~~
         ;
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/array.hxx:14,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/array:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:2,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In member function 'T pqxx::field::as() const':
C:\Program Files (x86)\libpqxx\include/pqxx/compiler-public.hxx:118:26: error: expected identifier before '[' token
 #  define PQXX_UNLIKELY [[unlikely]]
                          ^
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:221:9: note: in expansion of macro 'PQXX_UNLIKELY'
         PQXX_UNLIKELY
         ^~~~~~~~~~~~~
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/row.hxx:20,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/transaction_base.hxx:37,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/dbtransaction.hxx:19,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob.hxx:33,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:4,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In lambda function:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:222:7: error: expected '{'
       internal::throw_null_conversion(type_name<T>);
       ^~~~~~~~
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In member function 'T pqxx::field::as() const':
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:222:7: error: expected ';'
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/array.hxx:14,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/array:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:2,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In member function 'T pqxx::field::as() const [with T = std::basic_string_view<char>]':
C:\Program Files (x86)\libpqxx\include/pqxx/compiler-public.hxx:118:26: error: expected identifier before '[' token
 #  define PQXX_UNLIKELY [[unlikely]]
                          ^
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:334:5: note: in expansion of macro 'PQXX_UNLIKELY'
     PQXX_UNLIKELY
     ^~~~~~~~~~~~~
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/row.hxx:20,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/transaction_base.hxx:37,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/dbtransaction.hxx:19,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob.hxx:33,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:4,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In lambda function:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:335:3: error: expected '{'
   internal::throw_null_conversion(type_name<std::string_view>);
   ^~~~~~~~
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In member function 'T pqxx::field::as() const [with T = std::basic_string_view<char>]':
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:335:3: error: expected ';'
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/array.hxx:14,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/array:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:2,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In member function 'T pqxx::field::as() const [with T = pqxx::zview]':
C:\Program Files (x86)\libpqxx\include/pqxx/compiler-public.hxx:118:26: error: expected identifier before '[' token
 #  define PQXX_UNLIKELY [[unlikely]]
                          ^
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:372:5: note: in expansion of macro 'PQXX_UNLIKELY'
     PQXX_UNLIKELY
     ^~~~~~~~~~~~~
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/row.hxx:20,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/transaction_base.hxx:37,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/dbtransaction.hxx:19,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob.hxx:33,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:4,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In lambda function:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:373:3: error: expected '{'
   internal::throw_null_conversion(type_name<zview>);
   ^~~~~~~~
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In member function 'T pqxx::field::as() const [with T = pqxx::zview]':
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:373:3: error: expected ';'
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/array.hxx:14,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/array:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:2,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In function 'T pqxx::from_string(const pqxx::field&)':
C:\Program Files (x86)\libpqxx\include/pqxx/compiler-public.hxx:118:26: error: expected identifier before '[' token
 #  define PQXX_UNLIKELY [[unlikely]]
                          ^
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:497:7: note: in expansion of macro 'PQXX_UNLIKELY'
       PQXX_UNLIKELY
       ^~~~~~~~~~~~~
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/row.hxx:20,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/transaction_base.hxx:37,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/dbtransaction.hxx:19,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob.hxx:33,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:4,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In lambda function:
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:498:5: error: expected '{'
     internal::throw_null_conversion(type_name<T>);
     ^~~~~~~~
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx: In function 'T pqxx::from_string(const pqxx::field&)':
C:\Program Files (x86)\libpqxx\include/pqxx/field.hxx:498:5: error: expected ';'
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/array.hxx:14,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/array:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:2,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/stream_from.hxx: In member function 'void pqxx::stream_from::extract_value(Tuple&) const':
C:\Program Files (x86)\libpqxx\include/pqxx/compiler-public.hxx:118:26: error: expected identifier before '[' token
 #  define PQXX_UNLIKELY [[unlikely]]
                          ^
C:\Program Files (x86)\libpqxx\include/pqxx/stream_from.hxx:341:7: note: in expansion of macro 'PQXX_UNLIKELY'
       PQXX_UNLIKELY
       ^~~~~~~~~~~~~
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/transaction_base.hxx:38,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/dbtransaction.hxx:19,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob.hxx:33,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/blob:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:4,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/stream_from.hxx: In lambda function:
C:\Program Files (x86)\libpqxx\include/pqxx/stream_from.hxx:342:5: error: expected '{'
     internal::throw_null_conversion(type_name<field_type>);
     ^~~~~~~~
C:\Program Files (x86)\libpqxx\include/pqxx/stream_from.hxx: In member function 'void pqxx::stream_from::extract_value(Tuple&) const':
C:\Program Files (x86)\libpqxx\include/pqxx/stream_from.hxx:342:5: error: expected ';'
In file included from C:\Program Files (x86)\libpqxx\include/pqxx/array.hxx:14,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/array:4,
                 from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:2,
                 from C:\Users\danil\Downloads\test\main.cpp:3:
C:\Program Files (x86)\libpqxx\include/pqxx/pipeline.hxx: In member function 'void pqxx::pipeline::set_error_at(pqxx::pipeline::query_id)':
C:\Program Files (x86)\libpqxx\include/pqxx/compiler-public.hxx:118:25: warning: attributes at the beginning of statement are ignored [-Wattributes]
 #  define PQXX_UNLIKELY [[unlikely]]
                         ^
C:\Program Files (x86)\libpqxx\include/pqxx/pipeline.hxx:192:5: note: in expansion of macro 'PQXX_UNLIKELY'
     PQXX_UNLIKELY
     ^~~~~~~~~~~~~

Build finished with error(s).
```

> And by the way, if anything in the README is unclear, please file a bug about it! That's how we improve.
Problem is, I'm always unsure of what is my own ignorance and what is unclear — in this case, it might just have been my CMake inexperience 😅

**Comment by danbugs** [comment]
Good news — I've _sort of_ solved the issue! 

The solution was...

🥁🥁🥁
 
To drop Windows entirely! lol

Nah, ust kidding — what I did was that I installed libpqxx-dev on Ubuntu (through the Windows Subsystem for Linux) and it all worked with fine with some small modifications to my Makefile (gotta love WSL).

Anyway, I'll be closing the issue now! Thanks for the help ;D

### Sidenote

For future reference, if anyone comes across this issue, my Makefile ended up running the following:
``` 
g++ -c -Wall -g main.cpp -o main.o
g++ main.o -lpq -lpqxx -o main
```

**Comment by JadeMatrix** [comment]
> ```
> In file included from C:\Program Files (x86)\libpqxx\include/pqxx/array.hxx:14,
>                  from C:\Program Files (x86)\libpqxx\include/pqxx/array:4,
>                  from C:\Program Files (x86)\libpqxx\include/pqxx/pqxx:2,
>                  from C:\Users\<user>\Downloads\test\main.cpp:3:
> C:\Program Files (x86)\libpqxx\include/pqxx/params.hxx: In member function 'void pqxx::placeholders<COUNTER>::next()':
> C:\Program Files (x86)\libpqxx\include/pqxx/compiler-public.hxx:117:24: error: expected identifier before '[' token
>  #  define PQXX_LIKELY [[likely]
> ```

The [`likely` & `unlikely` attributes](https://en.cppreference.com/w/cpp/language/attributes/likely) were added in C++20, so that's the same issue as before probably (need `-std=c++2a` and/or GCC upgrade).  You can add that flag to the `CC` variable in your `Makefile`, or use CMake and specify [`CMAKE_CXX_STANDARD`](https://cmake.org/cmake/help/latest/variable/CMAKE_CXX_STANDARD.html) as 20, which will automatically check whether your compiler supports 20 and add either `c++2a` or `c++20` as appropriate 😉

**Comment by jtv** [comment]
By the way, the CMake setup checks whether your compiler supports `[[likely]]`.  If it doesn't, the libpqxx build won't use it.  But I did see a scenario where an older gcc (I think gcc 8) had no problem compiling the check code using `[[likely]]`, and then failed to compile some of the actual code that uses ``[[likely]]`.

I think gcc 8 is getting really iffy.  If toolchains shape up in time, the next major libpqxx release will require C++20 as a minimum.

**Comment by JadeMatrix** [comment]
> By the way, the CMake setup checks whether your compiler supports `[[likely]]`. If it doesn't, the libpqxx build won't use it.

For building `libpqxx`, yes, but once it's built those are baked into `config.h` and wont change even if the user is using a newer (or older) compiler, correct?  So that may be part of the issue here.

**Comment by jtv** [comment]
Yes, it's possible.  When the environment changes, it's important to
re-configure the build.
