### ISSUE TITLE
gcc 7 cannot build version 7.6.0

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#464]
When compile pqxx 7.6.0 with gcc 7, get the following error message (from https://github.com/conan-io/conan-center-index/pull/6566#issuecomment-888257152:

```plaintext
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/e04f4497f6362751e6e3ae90b7a736979ca47be0/source_subfolder/src/strconv.cxx: In function ‘constexpr T {anonymous}::safe_multiply_by_ten(T)’:
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/e04f4497f6362751e6e3ae90b7a736979ca47be0/source_subfolder/src/strconv.cxx:327:22: error: ‘inline’ specifier invalid for variable ‘ten’ declared at block scope
   inline constexpr T ten{10};
                      ^~~
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/e04f4497f6362751e6e3ae90b7a736979ca47be0/source_subfolder/src/strconv.cxx:328:61: error: ‘inline’ specifier invalid for variable ‘high_threshold’ declared at block scope
   inline constexpr T high_threshold(std::numeric_limits<T>::max() / ten);
                                                             ^~~
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/e04f4497f6362751e6e3ae90b7a736979ca47be0/source_subfolder/src/strconv.cxx:334:62: error: ‘inline’ specifier invalid for variable ‘low_threshold’ declared at block scope
     inline constexpr T low_threshold(std::numeric_limits<T>::min() / ten);
```

It is possible to remove the `inline` keyword from local variables.

https://github.com/jtv/libpqxx/blob/221ddc8be329bafb376a3d83b9cd257fd52fc7b7/src/strconv.cxx#L321-L340

**Comment by jtv** [comment]
I'd already given up on gcc 7 to be honest.  Does the rest actually work with gcc 7?  And on newer gcc versions (as well as clang I believe), I had to add the `inline` to get the code to compile in the first place.

**Comment by tt4g** [comment]
I've applied the patch and confirmed that it builds with gcc 7.
I haven't checked all the functions work, so there may be other bugs.

On the other hand, oddly enough, gcc 7 supports inline variables: https://gcc.gnu.org/projects/cxx-status.html#cxx17
I could not figure out why the error occurs.

**Comment by tt4g** [comment]
Oh, I overlooked the next information in the `NEWS` file.

> 7.5.0
> - Now requires `std::variant` support!  No longer works with gcc7.

https://github.com/jtv/libpqxx/blob/221ddc8be329bafb376a3d83b9cd257fd52fc7b7/NEWS#L33-L34

Since support for gcc 7 was dropped in the last major version, I think we can ignore this issue and still close the issue.

@jtv If you are not going to resume support for gcc 7, please close the issue.

**Comment by jtv** [comment]
OK, thanks!

**Comment by tt4g** [comment]
Report.
clang 6 has same issue.

```
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/a2b8f5768ecdd00236fe28e3be04542849dc32f2/source_subfolder/src/strconv.cxx:327:3: error: inline declaration of 'ten' not allowed in block scope
  inline constexpr T ten{10};
  ^~~~~~~
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/a2b8f5768ecdd00236fe28e3be04542849dc32f2/source_subfolder/src/strconv.cxx:328:3: error: inline declaration of 'high_threshold' not allowed in block scope
  inline constexpr T high_threshold(std::numeric_limits<T>::max() / ten);
  ^~~~~~~
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/a2b8f5768ecdd00236fe28e3be04542849dc32f2/source_subfolder/src/strconv.cxx:330:5: warning: unknown attribute 'unlikely' ignored [-Wunknown-attributes]
    PQXX_UNLIKELY
    ^
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/a2b8f5768ecdd00236fe28e3be04542849dc32f2/source_subfolder/include/pqxx/compiler-public.hxx:118:27: note: expanded from macro 'PQXX_UNLIKELY'
#  define PQXX_UNLIKELY [[unlikely]]
                          ^
/home/conan/w/BuildSingleReference/.conan/data/libpqxx/7.6.0/_/_/build/a2b8f5768ecdd00236fe28e3be04542849dc32f2/source_subfolder/src/strconv.cxx:334:5: error: inline declaration of 'low_threshold' not allowed in block scope
    inline constexpr T low_threshold(std::numeric_limits<T>::min() / ten);
```

**Comment by jtv** [comment]
I'm starting to think that I should at least disable the `[[likely]]` and ``[[unlikely]]` in C++17.  Those warnings might just be more annoying than any performance benefit.  :-(

**Comment by tt4g** [comment]
Umm... I looked at the CI build log and noticed that clang 10 also failed to build because of `inline constexpr` local variables.

```plaintext
/home/conan/.conan/data/libpqxx/7.6.0/_/_/build/18c37e5cd947792bc49e30dab95156b2a7980a93/source_subfolder/src/strconv.cxx:327:3: error: inline declaration of 'ten' not allowed in block scope
  inline constexpr T ten{10};
  ^~~~~~~
/home/conan/.conan/data/libpqxx/7.6.0/_/_/build/18c37e5cd947792bc49e30dab95156b2a7980a93/source_subfolder/src/strconv.cxx:328:3: error: inline declaration of 'high_threshold' not allowed in block scope
  inline constexpr T high_threshold(std::numeric_limits<T>::max() / ten);
  ^~~~~~~
/home/conan/.conan/data/libpqxx/7.6.0/_/_/build/18c37e5cd947792bc49e30dab95156b2a7980a93/source_subfolder/src/strconv.cxx:334:5: error: inline declaration of 'low_threshold' not allowed in block scope
    inline constexpr T low_threshold(std::numeric_limits<T>::min() / ten);
    ^~~~~~~
3 errors generated.
```

I couldn't read any explicit specification from the C++17 spec that says "Cannot use `inline` and `constexpr` to define local variables".
This compilation error may be caused by the implementation's different interpretation of the C++ specification.

**Comment by tt4g** [comment]
@jtv I created new pull request (#468).
I have created patches using several alternatives to `inline constexpr`, but only static variables declared as `static inline constexpr` in the class avoided the compilation error.

I'm not familiar with the different compilers' interpretations of `constexpr`, so I don't know if this patch will still produce exactly the same bytecode as before. However, I have seen that some compilers that were failing to build now build successfully after applying the patch.

**Comment by jtv** [comment]
It's really not worth _that_ much code though, IMHO.  The only reason I made them `inline` rather than `static` was that I didn't want them taking up space at link time, being accessed through indirection, etc.  But I'm starting to feel more like just trusting the compiler to constant-fold them.

**Comment by abrownsword** [comment]
I'm getting an annoying number of warnings about likely and unlikely while building C++17 w/ CLang 11.  It would be nice to eliminate this.  I can't switch to C++20 yet because of issues in other dependencies I have.

**Comment by tt4g** [comment]
@abrownsword Since version 7.6.1, `[[likely ]]` and `[[unlikely]]` are defined only in C++20 standard and above (662a3b7ef3f6de8b44dffb0aec997dbdc99ac8dd).

**Comment by jtv** [comment]
Prior to 7.6.1, the configure job only checked whether your compiler _allows_ those attributes.  And as you've experienced @abrownsword, in your case that meant "allows, but with a warning."

At first I tried checking `__cplusplus >= 202002L`, meaning "this is C++20."  The reason that didn't work is that some compilers (including gcc and clang) will let you compile C++20, at support `[[likely]]` and `[[unlikely]]` but do not support _all_ of C++20.  And so they keep `__cplusplus` at something _less_ than 202002.

Given the annoyance the warnings have caused though, I traded off any performance gain for a cleaner compile.
