### ISSUE TITLE
Problem with 6.3

### ISSUE THREAD

**Issue by SUP3RH0MI3** [jtv/libpqxx#466]
I'm trying to use your library in Visual Studio. The master version is working. But when I want to use it in a C++ Project for Linux Development, a Workload from Visual Studio, I get the problem, that the newest language standard is too old to work with the master version. So I used version 6.3 and followed the instructions from the INSTALL.txt, but right now I'm stuck at Line 168.

>2) Run:
>   "nmake /f win32/vc-libpqxx.mak ALL"

I get this error message

> LINK : fatal error LNK1181: Input File "Files\PostgreSQL\11\lib.obj" can not be opened

I'm not sure if this is the right place to ask this question, but I hope somebody can help me with my problem.

**Comment by tt4g** [comment]
Don't use `vc-libpqxx.mak` with `nmake` command for building Linux library,.
I think the goal is to do cross-platform development, but the library has to be built in a Linux environment or cross-platform build.
`nmake` is not supposed to support cross-platform builds.

It is recommended that you install pqxx on Linux to proceed with development.

**Comment by SUP3RH0MI3** [comment]
The error occured while building on windows. I still need to implement the library on this pc.

I should probably add that I'm using PostgreSQL 11.

**Comment by jtv** [comment]
Is it not possible to upgrade your compiler?

**Comment by SUP3RH0MI3** [comment]
Visual Studio is on the newest version.

![image](https://user-images.githubusercontent.com/47524464/127613884-12ce2c85-005e-4af2-831a-f741974b0298.png)

These are the C++ Language Standards I can choose from.  The C++17 is not working with libpqxx version 7.x. It needs the ISO C++17 version, but this one is not available for this kind of project

For example: If I open a "normal" C++ project, I can choose ISO C++17 and libpqxx 7.x is working fine.
![image](https://user-images.githubusercontent.com/47524464/127614708-f27755dd-bb68-4781-b2ce-3e901d74b9ac.png)

**Comment by tt4g** [comment]
Can use `cmake` for cross-platform building pqxx with MSVC?

**Comment by SUP3RH0MI3** [comment]
> Can use `cmake` for cross-platform building pqxx with MSVC?

The problem is not the cross-platform, it's the installation of version 6.3.


>  LINK : fatal error LNK1181: Input File "Files\PostgreSQL\11\lib.obj" can not be opened
To this error message, this file lib.obj doesn't even exist, so that could be the problem.

**Comment by tt4g** [comment]
> The problem is not the cross-platform, it's the installation of version 6.3.
>> LINK : fatal error LNK1181: Input File "Files\PostgreSQL\11\lib.obj" can not be opened
>> To this error message, this file lib.obj doesn't even exist, so that could be the problem.

it looks like the `nmake` command failed to execute the link command.
It only fails to link, so the previous libpqxx build should have succeeded.
There should be a possibility that you can build it by using `cmake` instead of `nmake`.

**Comment by jtv** [comment]
The CMake setup was very different in libpqxx 6.x though.

Parts of the problem are still unclear to me.  "C++17" and "ISO C++17" should be the same thing.  Why do you say you need "ISO C++17" and not "C++17"?  What goes wrong when you build libpqxx using "C++17"?  It should work.  Or "GNU C++17" should work as well.

The presence of GNU dialects in that list makes me think that you're using Visual Studio as the _IDE,_ but maybe it's calling gcc or clang as the _compiler._  If so, maybe gcc needs an upgrade?

**Comment by SUP3RH0MI3** [comment]
I have asked myself the same question, what the difference between the ISO-Version and the non-ISO-Version is. When I use the 7.x version I get these errors

![image](https://user-images.githubusercontent.com/47524464/127661209-4ba8608c-7cb8-457a-acf5-2d27bd93a5e7.png)

The Workload I'm using is this here
[Linux development with C++](https://docs.microsoft.com/en-us/cpp/linux/?view=msvc-160)
Thats why there are GNU dialects.


One thing that makes me curious , is that even tho the 7.x version installation worked fine, with the help of vcpkg, I still need to include the path of it in this project.
![image](https://user-images.githubusercontent.com/47524464/127662793-9ddb53c4-85ee-4a5b-a272-d4d108f7596b.png)
In normal C++ projects I  dont have to do that. And I'm pretty sure I shouldn't have to do that.
What probably leads to this error message
![image](https://user-images.githubusercontent.com/47524464/127663805-49d9e456-ac8b-41f6-8117-8970600deeb4.png)
Translation, because the error message is in my mother tongue.
> 	pqxx / pqxx: File or directory not found
 #include <pqxx / pqxx>
          ^ ~~~~~~~~~~
compilation terminated.

I'm really thankful for your help and wish you a pleasant weekend.

**Comment by tt4g** [comment]
`vcpkg` will install the library on your local machine.
In the guide procedure, it looks like the cross-compilation is done on the target machine connected via SSH.

You cannot use libraries installed on the local machine with `vcpkg`.
Build and install libpqxx on the target machine, and then start working with MSVC.

**Comment by SUP3RH0MI3** [comment]
I will try that.

**Comment by jtv** [comment]
No worries, I can read German.  The "Datei nicht gefunden" just means that
your include path is not set up to find the libpqxx headers.  Libpqxx's
"include" directory must be in the preprocessor's list of search paths.
(But do not list "include/pqxx" there.)

I'm currently stuck in the rain with a very unhappy cat, but will have
another look later.

**Comment by SUP3RH0MI3** [comment]
I installed pqxx on the Raspberry pi now, the error

> pqxx / pqxx: File or directory not found
> #include <pqxx / pqxx>
> ^ ~~~~~~~~~~
> compilation terminated.

is now gone. 

But I installed the wrong version. The link for cloning this git doesn't change, when I change the version. So version 7.x got installed. I need to find a way to install the version 6.3.

**Comment by SUP3RH0MI3** [comment]
![image](https://user-images.githubusercontent.com/47524464/127817349-9ead7a78-9ac1-4629-9375-a23589c42f85.png)
btw these are the errors I now get.

**Comment by tt4g** [comment]
> So version 7.x got installed.

It will be removed by `make uninstall`. Then install 6.x.

> btw these are the errors I now get.

My guess is that it refers to the 7.x header file, but is linked to versions 6.x and earlier.
Because `pqxx::connection::dbname() const` has been added since version 7.0.

**Comment by SUP3RH0MI3** [comment]
![image](https://user-images.githubusercontent.com/47524464/127821710-a913afd5-c9b7-4ee3-b728-60d4f5c32b7b.png)
I now get this error message on the pi. xmlto is installed.

**Comment by jtv** [comment]
That's the way Git works...  First you clone the whole repo, and then
within your local repo you check out the tag you want.

The errors suggest that either you're not linking to libpqxx (you need to
link libpqxx and libpq, in that order) or you're linking to a libpqxx that
was compiled in some way that's fundamentally incompatible with the way you
compiled your application.

For instance, perhaps you compiled your libpqxx and your application with
different compilers, or for different platforms.

**Comment by tt4g** [comment]
Add the `--disable-documentation` option to the `configure` command as described in the error message.
The documentation will not be generated, but the build will be done.

**Comment by SUP3RH0MI3** [comment]
Even tho I only installed branch 6.3 with the command
`git clone --branch 6.3 https://github.com/jtv/libpqxx.git`
I still get the same errors.
e.g. undefined reference to `pqxx::connection_base::dbname()'
I even created a new project, but the errors are still the same

**Comment by tt4g** [comment]
The header referenced by the project is wrong.
There must be a setting somewhere that references the libpqxx 7.x header, so you need to find it and fix it.

**Comment by SUP3RH0MI3** [comment]
I now cutted the program to just connect with try-catch.
I get following errors. 

![image](https://user-images.githubusercontent.com/47524464/127834619-10d3aa42-d8bf-4126-9b9d-3f063a15bc87.png)

**Comment by SUP3RH0MI3** [comment]
> The header referenced by the project is wrong.
> There must be a setting somewhere that references the libpqxx 7.x header, so you need to find it and fix.

I searched for it, but I'm not sure where to look anywhere besides Visual Studio.

**Comment by jtv** [comment]
I'd just open an Explorer window and type e.g. `connection.hxx` in the search box, see what it comes up with.  Try the same with... `libpqxx.lib` I guess, though I'm not completely sure what the name should look like on Windows.

**Comment by SUP3RH0MI3** [comment]
On the Windows pc and also on the Rapsberry Pi there is no `libpqxx.lib`.
On the raspberry pi is only one `connection.hxx` and on my pc too.

**Comment by tt4g** [comment]
Make sure to reference the header file on Raspberry Pi.
And configure the project to link the Raspberry Pi pqxx.

**Comment by SUP3RH0MI3** [comment]
> Make sure to reference the header file on Raspberry Pi.
> And configure the project to link the Raspberry Pi pqxx.

Shouldn't it do that by itself? If not, could you explain it or give me a link, where it gets explained.

**Comment by tt4g** [comment]
I couldn't find a page in the Visual Studio Cross-Platform Development Guide that mentions the project's dependent libraries.
However, it seems that the same rule applies to cross platform projects, since non cross platform projects have to add libraries to their dependencies that have to be linked.

searching for the words "Visual Studio cross platform Linux dependency" in a search engine I found the next pages.

* https://stackoverflow.com/questions/46674763/visual-studio-c-remote-linux-debugging-add-linker-options/46738627#46738627
* https://stackoverflow.com/questions/51809144/how-do-i-link-linux-libraries-for-a-cross-platform-linux-project-in-visual-studi
* https://social.msdn.microsoft.com/Forums/en-US/a43c9f43-eb8c-4af1-9615-49fd58e2de92/visual-studio-2017-cross-platform-library-linking?forum=vcgeneral


Example for using MySQL client project: * https://hq.ipas.nl/?page_id=525

**Comment by SUP3RH0MI3** [comment]
I read the arcticles you gave me and did what they said.
I now added the path of the the pqxx folder that I found on the Raspberry Pi as Additional Include Directory.
![image](https://user-images.githubusercontent.com/47524464/127990623-bf1f8d75-e74a-4804-ac8b-58385c2d19b1.png)

Then I added the path of the folder where libpqxx.a i stored.
![image](https://user-images.githubusercontent.com/47524464/127990812-a8d247bc-67f2-48db-ac29-a98f9eb482dc.png)

and also did this
![image](https://user-images.githubusercontent.com/47524464/127990890-4fe52ef9-33d4-451f-8a54-36637cb3e373.png)

I now get a lot more error messages
![image](https://user-images.githubusercontent.com/47524464/127991101-e3f7ff43-292a-4958-8632-51d85a7d110a.png)

**Comment by tt4g** [comment]
It still looks like it is referring to the libpqxx 7.3 header file.
It seems that the previously installed libpqxx 7.3 has not been uninstalled.
Uninstall libpqxx 7.3.

There are also missing libpq dependencies.

**Comment by SUP3RH0MI3** [comment]
Maybe i forgot something when uninstalling libpqxx 7.3.
I used `sudo make uninstall` and then deleted the directory that got created when I use the git clone command.
Is there anything missing?

**Comment by tt4g** [comment]
Oh, sorry I was looking at the image of the previous compile error.
The remaining problem is that libpq is not linked, and libpqxx is linked to the wrong target.

libpq has to be installed on the Raspberry Pi.
Then add it to the Library Dependencies.

For libpqxx, please remove either Library Dependencies or Additional Dependencies.
It is not possible to link the same library twice.

**Comment by SUP3RH0MI3** [comment]
I installed libpq-dev as said by the pg_config file.

When I ask the package management what files the package contains I get this
![image](https://user-images.githubusercontent.com/47524464/128003639-4998e4da-4af2-43dd-b7ab-2f4a01a35c78.png)

what directory or which file exactly needs to be added as dependency?

**Comment by tt4g** [comment]
I do not have a Raspberry Pi, so I will write my predictions from the installed files.
libpq usually uses the header file `libpq-fe.h`, and then links to `libpq.so` or `libpq.a`.

Include: `/usr/include/postgresql/libpq`
Library Dependencies: `/usr/lib/arm-linux-gnueabinf/libpq.x` or `/usr/lib/arm-linux-gnueabinf/libpq.so`

**Comment by SUP3RH0MI3** [comment]
I added `pq`, so libpq.so and now all the errors are gone.

Thank you so much, especially for being so patient with me. You both are life savers.
