### ISSUE TITLE
Documentation says to checkout a branch that doesn't exist

### ISSUE THREAD

**Issue by moodboom** [jtv/libpqxx#469]
Hey thanks for the code!  I was excited to see a new release since I've been forked for a while to get CMake support for recent postgresql versions.

Docs say:
```
If you're getting the code straight from the Git repo, the master branch contains the current development version. To get a released version, check out the revision that's tagged for that version. For example, to get version 7.1.1:

    git checkout 7.1.1

```

But I only see a tag for v7.6.0.  I'll try my luck with master, perhaps the 7.1.1 release is coming soon?

**Comment by moodboom** [comment]
Looks like I still get CMake issues, master gives me this:

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_TYPE_INCLUDE_DIR) (found
  version "13.3")
```

**Comment by moodboom** [comment]
FYI master branch is compiling and wrorking great here, after installing missing deps:

`apt-get install libpq-dev postgresql-server-dev-13`

I also added a CMake block to find pg 13.. not sure if that was needed, I'll revert and report back...

**Comment by jtv** [comment]
There is a 7.1.1, but it's a tag, not a branch.  I'll try to make that clearer.
