### ISSUE TITLE
Updating apt-get package manager

### ISSUE THREAD

**Issue by vitruvvius** [jtv/libpqxx#471]
How does one update the libpqxx distribution used in apt-get package manager for linux distributions? This is how we currently build apps in cloud native environments

**Comment by jtv** [comment]
Mainly: link to libpqxx _statically._  That way, you won't need to install libpqxx on your servers, only on the systems where you're building your application.

Beyond that, if you really need a shared library or if your build system is on a VM, it gets harder.  Ubuntu doesn't have a backports archive like Debian has, to my knowledge.  I don't have a PPA for libpqxx that I'm keeping current, either.

So *if* you really need to install the shared library and/or do your building in the cloud,  I think your options are:
 * Find a PPA for libpqxx, maintained by someone you trust.
 * Convince the package maintainer to stay up to date with upstream libpqxx.  According to launchpad.net, the maintainer is Marcin Kulisz.
 * Build your own deb, more up-to-date libpqxx package.  The existing Ubuntu packaging should be a good starting point.
 * Build a raw libpqxx and write your own commands to install it on your cloud machine.
 * Live with libpqxx 6.x for now.
 * And then there's _snaps,_ but I'm not too familiar with them myself.

**Comment by KayEss** [comment]
If you're not linking statically then whatever you're doing to distribute your own executables, you just need to include the libpqxx.so in that as well and don't install libpqxx via apt.
