### ISSUE TITLE
stream_to unintentionally ignores client encoding for non-ASCII characters

### ISSUE THREAD

**Issue by vilarion** [jtv/libpqxx#473]
Using PostgreSQL 13.3:

pqxx::stream_to [escapes non-ASCII characters as octal numbers](https://github.com/jtv/libpqxx/blob/master/src/stream_to.cxx#L122). This ignores client encoding, since postgresql evaluates octal and hexadicimal escapes only after encoding conversion when using COPY. Currently [this behaviour is not documented](https://www.postgresql.org/docs/13/sql-copy.html) but it is [intended](https://www.postgresql.org/message-id/d06c9ac0-1e22-7247-8b98-3c13d550d43d%40iki.fi) and a patch to the postgresql docs has been suggested, effectively adding:
```
     All backslash sequences are interpreted after encoding conversion. The bytes
     specified with the octal and hex-digit backslash sequences must form
     valid characters in the database encoding.
```

Test database:
```sql
CREATE DATABASE test WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE= 'C' LC_CTYPE = 'C';
CREATE TABLE test (text character varying(50));
```

Test program:
```c++
#include <iostream>
#include <pqxx/connection.hxx>
#include <pqxx/result.hxx>
#include <pqxx/stream_to.hxx>
#include <pqxx/transaction.hxx>
#include <string>

int main() {
    auto connection = pqxx::connection("dbname=test client_encoding=LATIN1");
    auto transaction = pqxx::transaction(connection);
    std::string text{"\304\366\337"}; //Äöß

    auto stream = pqxx::stream_to::table(transaction, {"public", "test"}, {"text"});
    stream.write_values(text);
    stream.complete();
    transaction.commit();
}
```
Output:
```
terminate called after throwing an instance of 'pqxx::data_exception'
  what():  Failure during '[END COPY]': ERROR:  invalid byte sequence for encoding "UTF8": 0xc4 0xf6
CONTEXT:  COPY test, line 1: "\304\366\337"
```
Expected:
"Äöß" being inserted into the table.

**Comment by jtv** [comment]
Ouch!

Thanks for bringing this up — I had no idea that these escapes bypassed the client encoding.  Doesn't make much sense to me, to be honest.  And thanks also for an exceptionally well-written bug report, by the way.

I see no other way out of this than to make `escape_field_to_buffer` encoding-aware.  Otherwise, it might try to escape a byte that _looks_ like a special character (backslash, newline, etc.), but is actually just part of a multibyte character.

**Comment by vilarion** [comment]
Thanks, and thanks for a great library.

Is it even necessary to escape bytes >127? The documentation only requires escaping "backslash itself, newline, carriage return, and the current delimiter character", but maybe I am missing something obvious here, e.g. backwards compatibility.

**Comment by jtv** [comment]
Indeed.  The idea of making the loop encoding-aware is that it can pass non-ASCII bytes through unchanged.

But I'm running into a new question: what if a multibyte character (e.g. in SJIS) _contains_ a byte that looks like a newline, backslash, backspace, etc?  Will I need to insert a backslash _in the middle of a character?_

**Comment by vilarion** [comment]
I don't think bytes in the middle of a character need or should be escaped if the server indeed converts the input to server encoding before handling escapes. After that conversion these bytes that could look like a newline, etc. would be gone, right?.

**Comment by jtv** [comment]
That makes sense.  So I'll definitely need my loop to be encoding-aware.  It should pass multi-byte characters through unchanged, but check single-byte characters for the need to escape.

**Comment by vilarion** [comment]
I am not sure if these characters are single-byte in every supported encoding.

**Comment by vilarion** [comment]
At the very least it would be possible that they add support for something like UTF-16 at some point, where this wouldn't be true, obviously.

**Comment by jtv** [comment]
UTF-16 would be radical surgery, I think, exactly for this kind of reason.  To my knowledge, all encodings supported by PostgreSQL act as "ASCII supersets," and that assumption is _everywhere._

It was a big nasty surprise, not so very long ago, to realise that some supported encodings could contain byte values like `'/'` inside a multibyte character.  It was so dramatic that we got an incompatible API change in libpq security patches!  AFAICT supporting UTF-16 would be worse.  Otherwise, I think UTF-16 would be supported already.

**Comment by vilarion** [comment]
Ouch, but in any case having this assumption of ASCII supersets will make fixing this issue much easier.

**Comment by jtv** [comment]
Exactly.  And it'll limit the performance penalty as well.

At some point I think I'd like to write a generic helper template for “scan through text S, in encoding E, until you find one of the ASCII characters X, Y, or Z.”  (Of course it could just be one specific character, or any other compile-time-constant number.)  It would let me do some things more efficiently, probably at the cost of some extra complication in one or two loops.

**Comment by vilarion** [comment]
I am not sure how feasible or how performant this would be, but maybe it even makes sense to use `glyph_scanner` in a custom iterator (which would need a type to belong to), so that you could use STL algorithms like std::any_of in this case or even std::ranges::any_of. This would provide access to a vast array of (range based) algorithms and avoid re-implementing them as with `find_with_encoding`.

**Comment by jtv** [comment]
That sounds complicated for variable-length encodings.  And I _definitely_ don't want to take on the cost of converting to UTF-32 first.

The reason I'm thinking of writing a "search this text for any of the following ASCII characters" helper is that I think we can specialise the whole loop for a particular encoding group.  It means the compiler gets to optimise a much more complete picture where much more of the work happens.  And I think it's generic enough that it would cover most of my encoding-dependent use-cases.

**Comment by vilarion** [comment]
So, following the pattern of [encodings.cxx](https://github.com/jtv/libpqxx/blob/master/src/encodings.cxx), that would be adding something like this?
```c++
template<encoding_group E> struct any_char_finder
{
  constexpr static PQXX_PURE std::size_t
  call(std::string_view haystack, std::string_view needles, std::size_t start)
  {
    auto const buffer{std::data(haystack)};
    auto const size{std::size(haystack)};
    for (auto here{start}; here + 1 <= size;
         here = glyph_scanner<E>::call(buffer, size, here))
    {
      // C++23: if (needles.contains(haystack[here]))
      if (needles.find(haystack[here]) != std::string_view::npos)
        return here;
    }
    return std::string_view::npos;
  }
};


PQXX_PURE std::size_t find_any_with_encoding(
  encoding_group enc, std::string_view haystack, std::string_view needles,
  std::size_t start)
{
  using finder_func = std::size_t(
    std::string_view haystack, std::string_view needles, std::size_t start);
  auto const finder{for_encoding<any_char_finder, finder_func>(enc)};
  return finder(haystack, needles, start);
}
```

**Comment by jtv** [comment]
Well, the idea was to make the needles a parameter pack so we get code
statically optimised for exactly the chars we're looking for.

**Comment by jtv** [comment]
@vilarion I think that last commit fixes the issue.  Do you concur?

(Unfortunately I'll have to release it as 7.7.0 because it changes the ABI a tiny bit.)

**Comment by vilarion** [comment]
Yes, this works for me! The release version doesn't matter to me, since I will grab it via sha1 in CMake anyway. Thanks a lot!
Sorry I didn't respond earlier, I got a bit busy today.
