### ISSUE TITLE
error:  "cannot run inside a transaction block"

### ISSUE THREAD

**Issue by abrownsword** [jtv/libpqxx#474]
I am trying to add a new command to my program, and am getting this error message:

`CREATE MATERIALIZED VIEW ... WITH DATA cannot run inside a transaction block`

Looking at the libpqxx API, I don't see any way to _not_ run a command from within a transaction.  I have separated all my setup commands into separate transactions, but alas this didn't seem to help.

Any suggestions?

My command:
`CREATE MATERIALIZED VIEW IF NOT EXISTS Monitor_summary_daily 
 WITH (timescaledb.continuous) AS 
 SELECT loc, time_bucket(INTERVAL '1 day', time) AS bucket, 
       MIN(Health), 
       AVG(Health), 
       MAX(Health) 
FROM Monitor GROUP BY loc, bucket;`

**Comment by jtv** [comment]
To run a command that's not inside a database transaction, use the
"nontransaction" class.  It's a transaction class that does not actually
start a transaction on the database.

**Comment by abrownsword** [comment]
Worked like a treat.  Thanks.
