### ISSUE TITLE
C++20 compilation failed because of `PQXX_UNLIKELY`

### ISSUE THREAD

**Issue by TmLev** [jtv/libpqxx#475]
Error message from `clang++-12`:
```
error: no return statement in constexpr function
constexpr tx_stat parse_status(std::string_view text) noexcept
```

Removing [this line just before the return statement](https://github.com/jtv/libpqxx/blob/8d17b559753cbd9f0c79d7f6ec68ac9b33259beb/src/robusttransaction.cxx#L67) seems to fix the issue.

**Comment by jtv** [comment]
Thanks for reporting.  What compiler is this, and what error does it give
you?

**Comment by TmLev** [comment]
@jtv compiler and its error are mentioned in OP of the GitHub issue: https://github.com/jtv/libpqxx/issues/475#issue-972558765
As well as the pull request that can fix it: https://github.com/jtv/libpqxx/pull/476

**Comment by jtv** [comment]
Ah, OK, sorry.  Read the report on a telephone while dealing with other stuff, so I missed some things.  When I try it here (also with clang 12) I get a whole bunch of these warnings.  I'll remove those attributes.

**Comment by jtv** [comment]
@TmLev wow, this is surprising: I just saw the Github email again, and _it completely left out_ the part about the compiler!  And it showed _only part_ of the error message, so I didn't recognise it as such.

What I got was:

    Error message:

    constexpr tx_stat parse_status(std::string_view text) noexcept```

    Removing [this line just before return]
    (https://github.com/<etc>) seems to fix the issue.

Lesson learned: cant trust the emails...

**Comment by TmLev** [comment]
@jtv To be fair, I edited OP a bit after opening the issue, so no wonder email didn't catch all of it.
