### ISSUE TITLE
[Visual Studio 2019][6.2] Remote development troubles, field.hxx and statement_parameters.hxx

### ISSUE THREAD

**Issue by NysNight** [jtv/libpqxx#477]
So I'm quite out of my depth here and have little idea about how to fix it.
I'm working with a Pi(Raspbian) and VS2019 remote-development (Win10).
On the Pi I installed libpqxx-6.2 and -dev, as those seemed the most up-to-date in the repository. I tried my hand at manually installing the newest one, but didn't have any luck with that and again, out of my depth here.

Writing my code and compiling it on the Pi with `-lpqxx -lpq` is no problem. Compiling it in VS2019 leads to a few errors:
field.hxx , 4 line 177:
```
this declaration has no class storage or type specifier
'experimental' in namespace 'std' does not name a type
expected ';'
name followed by '::' must be a class or namespace name
```
statement_parameters.hxx, 6 in line 210:
```
explicit type is missing ('int' assumed)
name followed by '::' must be a class or namespace name
expected a ')'
'experimental' in namespace 'std' does not name a type
expected unqualified-id before '<' token
expected ')' before '<' token
expected initializer before '<' token
```

My platform toolset is `GCC for remote linux`, using g++ as the compiler.
compiler command line:
`"g++" -W"switch" -W"no-deprecated-declarations" -W"empty-body" -W"conversion" -W"return-type" -W"parentheses" -W"no-pointer-sign" -W"no-format" -W"uninitialized" -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -std=gnu++11 -Wall -fno-strict-aliasing -g1 "g++" -O3 -fthreadsafe-statics -D "NDEBUG" -W"switch" -W"no-deprecated-declarations" -W"empty-body" -W"conversion" -W"return-type" -W"parentheses" -W"no-format" -W"uninitialized" -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -frtti -fomit-frame-pointer -std=gnu11 -fexceptions -I "C:\Users\praktikant\AppData\Local\Microsoft\Linux\HeaderCache\1.0\-1635062655\usr\include\pqxx" "1" -o "C:\Users\praktikant\source\repos\db-test\db-test\obj\ARM\CoTM-Debug\%(filename).o" `

Fix or workaround would both be appreciated.

**Comment by tt4g** [comment]
The last release version is 7.6.0, can you try it?

**Comment by tt4g** [comment]
A macro `PQXX_HIDE_EXP_OPTIONAL` has been added in version 7.0.0 to solve this problem (https://github.com/jtv/libpqxx/issues/93#issuecomment-393481123).

If you have the latest version, you do not need the `PQXX_HIDE_EXP_OPTIONAL` macro.

**Comment by NysNight** [comment]
I would certainly like to, but I've had no success with building it myself with the two provided methods.
with `cmake .`
```
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_TYPE_INCLUDE_DIR) (found
  version "11.12")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindPostgreSQL.cmake:247 (find_package_handle_standard_args)
  cmake/config.cmake:26 (find_package)
  CMakeLists.txt:27 (include)


-- Configuring incomplete, errors occurred!
See also "/home/pi/Downloads/libpqxx/CMakeFiles/CMakeOutput.log".
```

Which cloud probably be it's own bug.
I do have PostgreSQL installed though.
```
libpq5/oldstable,now 11.12-0+deb10u1 armhf  [Installiert,automatisch]
librdf0/oldstable,now 1.0.17-1.1+b1 armhf  [Installiert,automatisch]
libreoffice-base-drivers/testing,now 1:6.1.5-3+rpi1+deb10u7+rpt1 armhf  [Installiert,automatisch]
libreoffice-sdbc-postgresql/testing,now 1:6.1.5-3+rpi1+deb10u7+rpt1 armhf  [Installiert,automatisch]
postgresql-11/oldstable,now 11.12-0+deb10u1 armhf  [Installiert,automatisch]
postgresql-client-11/oldstable,now 11.12-0+deb10u1 armhf  [Installiert,automatisch]
postgresql-client-common/oldstable,now 200+deb10u4 all  [Installiert,automatisch]
postgresql-common/oldstable,now 200+deb10u4 all  [Installiert,automatisch]
python3-logilab-common/oldstable,now 1.4.2-1 all  [Installiert,automatisch]
```

**Comment by KayEss** [comment]
You're missing the server dev package. Try installing `postgresql-server-dev-all` as well

**Comment by tt4g** [comment]
This error will occur if the libpq include directory structure is different from what CMake expects.

You can ignore this error by specifying the path where `pg_type.h` exists in the CMake variable `PostgreSQL_TYPE_INCLUDE_DIR`.

Example: `cmake -DPostgreSQL_TYPE_INCLUDE_DIR=<path/to/include/dir> .`

https://github.com/Kitware/CMake/blob/31c5700d4322ecfa169db2fccf385d6eced4e737/Modules/FindPostgreSQL.cmake#L33-L41

**Comment by NysNight** [comment]
Well, it seems the cmake method is working now that I have `postgresql-server-dev-all`. Maybe the two build-methods should include a list of dependencies. For a newbie like me that was not an easily identifiable problem. Or maybe there is a list somewhere and I was blind. 🤷

**Comment by NysNight** [comment]
So here is how far I got:
I did `sudo apt remove libpqxx-6.2` first ofcourse, which took `libpqxx-dev` with it. Do I need this? It sounds kinda important.
```
$ git clone https://github.com/jtv/libpqxx
cd libpqxx/
cmake .
cmake --build .
sudo cmake --install . --prefix /usr/
```

Til here everything seemed fine, no error messages.

`g++ db-test.cpp -o db-test.ex -lpqxx -lpq`
this threw more errors then my ssh terminal has buffer.
Seems to be mostly repeating in a similar pattern to this:
```
/usr/include/pqxx/except.hxx:185:23: note:   conversion of argument 1 would be ill-formed:
In file included from /usr/include/pqxx/connection.hxx:36,
                 from /usr/include/pqxx/transaction_base.hxx:32,
                 from /usr/include/pqxx/dbtransaction.hxx:19,
                 from /usr/include/pqxx/blob.hxx:33,
                 from /usr/include/pqxx/blob:4,
                 from /usr/include/pqxx/pqxx:4,
                 from db-test.cpp:2:
/usr/include/pqxx/internal/concat.hxx: In instantiation of ‘std::__cxx11::string pqxx::internal::concat(TYPE ...) [with TYPE = {const char*, int, const char*, int, const char*}; std::__cxx11::string = std::__cxx11::basic_string<char>]’:
/usr/include/pqxx/row.hxx:202:12:   required from here
/usr/include/pqxx/internal/concat.hxx:36:28: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
   char *const data{buf.data()};
```

I feel like I'm in a 2 steps forward 1 step back situation here 😅, but at least it's more forward then back.

And thank you for your quick help so far, peeps.

**Comment by jtv** [comment]
_Yes,_ libpqxx-dev is important — but that's basically the thing you're building when you build libpqxx yourself.  There are no other direct dependencies besides libpq, but exactly how that's packaged depends on the environment we're talking about.

Depending on your gcc version, you may need to tell it to compile C++17 or better: `-std=c++17` (or `-std=c++2a` etc.).  There was no non-`const` version of `std::basic_string::data()` before C++17.

**Comment by NysNight** [comment]
Right, the different C++ version requirement totally slipped my mind. adding `-std=c++17` and then a slight change from `Connection.disconnect();` to `Connection.close();` and I can compile just fine on the target machine.
Thanks very much for pointing that out. 

Now I just have to get VS2019 to work like that too. Where I now have 14 errors, but different ones from before:
```
File	Severity	Line	Code	Description
conversions.hxx	Error (active)	8	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
types.hxx	Error (active)	16	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
blob.hxx	Error (active)	21	E0059	function call is not allowed in a constant expression	
strconv.hxx	Error (active)	23	E0059	function call is not allowed in a constant expression	
blob.hxx	Error (active)	25	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
strconv.hxx	Error (active)	27	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
blob.hxx	Error (active)	29	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
connection.hxx	Error (active)	30	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
util.hxx	Error (active)	30	E0059	function call is not allowed in a constant expression	
blob.hxx	Error (active)	240	E0059	function call is not allowed in a constant expression	
blob.hxx	Error (active)	254	E0059	function call is not allowed in a constant expression	
blob.hxx	Error (active)	288	E0059	function call is not allowed in a constant expression	
conversions.hxx	Error (active)	1066	E1919	parameter pack "Args" was referenced but not expanded	
conversions.hxx	Error (active)	1074	E1919	parameter pack "Args" was referenced but not expanded	
```

**Comment by jtv** [comment]
These _also_ look as if the compiler isn't expecting C++17.

**Comment by NysNight** [comment]
I have of course tried not to make the same mistake twice, so my VS2019 is configured for C++17.
Now, after putting `pqxx; pq` in the linker library dependencies, it even compiles and runs, but still shows the same 14 errors?

**Comment by KayEss** [comment]
Do you mean these errors?

```
File	              Severity	Line	Code	Description
conversions.hxx	Error (active)	8	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
types.hxx	Error (active)	16	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
blob.hxx	Error (active)	21	E0059	function call is not allowed in a constant expression	
strconv.hxx	Error (active)	23	E0059	function call is not allowed in a constant expression	
blob.hxx	Error (active)	25	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
strconv.hxx	Error (active)	27	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
blob.hxx	Error (active)	29	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
connection.hxx	Error (active)	30	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type	
util.hxx	Error (active)	30	E0059	function call is not allowed in a constant expression	
blob.hxx	Error (active)	240	E0059	function call is not allowed in a constant expression	
blob.hxx	Error (active)	254	E0059	function call is not allowed in a constant expression	
blob.hxx	Error (active)	288	E0059	function call is not allowed in a constant expression	
conversions.hxx	Error (active)	1066	E1919	parameter pack "Args" was referenced but not expanded	
conversions.hxx	Error (active)	1074	E1919	parameter pack "Args" was referenced but not expanded	
```
That looks like it might be from your editor or IDE or something. You may need to configure it with the same build parameters that the project builds with in order to get it to understand what's going on. I would try looking in your editor documentation.

**Comment by NysNight** [comment]
Yes, I mean exactly those errors. I'll assume that you're right with your guess, since it builds, runs, and debugs as expected.
These errors only show up in IntelliSense, and not in the build section. 
So with that my problem with libqpxx is fixed. 
Thanks for the help, people.

**Comment by jtv** [comment]
With the actual build problems out of the way, I hope you enjoy working with libpqxx!
