### ISSUE TITLE
problem building libpqxx with vcpkg and vs 2017

### ISSUE THREAD

**Issue by gkellerer** [jtv/libpqxx#480]
hello

i am using libpqxx with vs 2017 and vcpkg on Windows 10. The lastest version fails to build with a lot of compile errors. checking the repository shows that with the last commit the fix for VS 2017 has been removed. I don't know who made that port but would it be possibile to reinsertthat patch so that te build is working with vs 2017?

thank you very much,
Georg

**Comment by tt4g** [comment]
libpqxx 7.6.0 and later, require `[[deprecated]]` attribute supports but MSVC 2017 does not support (bug).

https://github.com/jtv/libpqxx/blob/221ddc8be329bafb376a3d83b9cd257fd52fc7b7/NEWS#L17

Update MSVC 2019 or use libpqxx 7.5.2.

**Comment by jtv** [comment]
There may also be an option somewhere to make Visual Studio ignore attributes that it doesn't know.  It's not a good solution, but given that we're working around a bug in an older version of the compiler...

I concur that the ideal solution would be to upgrade the compiler.
