### ISSUE TITLE
How to access field content by field name

### ISSUE THREAD

**Issue by inaryart** [jtv/libpqxx#483]
- such as
```C++
// array / string / int 
auto value= rows["field_name"];
```

**Comment by tt4g** [comment]
`pqxx::row::at(zview) const` and `pqxx::row::operator[](zview) const` will returns `pqxx::field`.
need to call `pqxx::field::to()` or `pqxx::field::as()` to access database value.

```c++
int value = 0;
if (rows["field_name"].to(value)) {
    // Set database value to `value` variable.
} else {
    // failure.
}

// Or

auto value rows["field_name"].as<int>():
// Null safe.
auto value rows["field_name"].as<std::optional<int>>():
```

See documentation: 
* https://libpqxx.readthedocs.io/en/7.6.0/a01029.html#a2ffec6d7bd324a27d9f152dc7e9996b2
* https://libpqxx.readthedocs.io/en/7.6.0/a01029.html#a27f7bb2fe7bd70412feaea0bdcd6464e

**Comment by stonedreamforest** [comment]
> `pqxx::row::at(zview) const` and `pqxx::row::operator[](zview) const` will returns `pqxx::field`.
> need to call `pqxx::field::to()` or `pqxx::field::as()` to access database value.
> 
> ```c++
> int value = 0;
> if (rows["field_name"].to(value)) {
>     // Set database value to `value` variable.
> } else {
>     // failure.
> }
> 
> // Or
> 
> auto value rows["field_name"].as<int>():
> // Null safe.
> auto value rows["field_name"].as<std::optional<int>>():
> ```
> 
> See documentation:
> 
> * https://libpqxx.readthedocs.io/en/7.6.0/a01029.html#a2ffec6d7bd324a27d9f152dc7e9996b2
> * https://libpqxx.readthedocs.io/en/7.6.0/a01029.html#a27f7bb2fe7bd70412feaea0bdcd6464e

I get a string object and get a crash.
```C++
auto str = rows["field_name"].as<std::string>();
```

**Comment by inaryart** [comment]
> `pqxx::row::at(zview) const` and `pqxx::row::operator[](zview) const` will returns `pqxx::field`.
> need to call `pqxx::field::to()` or `pqxx::field::as()` to access database value.
> 
> ```c++
> int value = 0;
> if (rows["field_name"].to(value)) {
>     // Set database value to `value` variable.
> } else {
>     // failure.
> }
> 
> // Or
> 
> auto value rows["field_name"].as<int>():
> // Null safe.
> auto value rows["field_name"].as<std::optional<int>>():
> ```
> 
> See documentation:
> 
> * https://libpqxx.readthedocs.io/en/7.6.0/a01029.html#a2ffec6d7bd324a27d9f152dc7e9996b2
> * https://libpqxx.readthedocs.io/en/7.6.0/a01029.html#a27f7bb2fe7bd70412feaea0bdcd6464e

I get a string object and get a crash
```
auto str = rows["field_name"].as<std::string>();
```

**Comment by tt4g** [comment]
I can't tell from the comments what is going on, but I can guess two causes.

1. `filed_name` is `NULL` in the database.

   This case use `rows["field_name"].as<std::optional<std::string>>();`.

2. `field_name` is not characters type in database.

    In this case, please convert `field_name` type to text type on PostgreSQL (e.g. `SELECT field_name::text ...`).

By the way. To find out the cause, use the `try {} catch {}` expression to get the error message.

**Comment by inaryart** [comment]
> I can't tell from the comments what is going on, but I can guess two causes.
> 
> 1. `filed_name` is `NULL` in the database.
>    This case use `rows["field_name"].as<std::optional<std::string>>();`.
> 2. `field_name` is not characters type in database.
>    In this case, please convert `field_name` type to text type on PostgreSQL (e.g. `SELECT field_name::text ...`).
> 
> By the way. To find out the cause, use the `try {} catch {}` expression to get the error message.

due to capitalization, I need to enclose my field in quotation marks, like this:
```
auto str = rows["\"fieldName\""].as<std::string>();
```

 It works fine at this time

**Comment by inaryart** [comment]
@tt4g  but now get a warning, how to clear it.
```
 message : see reference to function template instantiation 'T pqxx::field::as<std::string>(void) const' being compiled
1>        with
1>        [
1>            T=std::string
1>        ]
```

**Comment by tt4g** [comment]
It's not a complete compilation message, so I can't be sure, but I think it's part of the stack trace of a report that the compiler could not interpret the `[[likely]]` attribute.

If you are able to build it, there is no problem with it working.

**Comment by inaryart** [comment]
> It's not a complete compilation message, so I can't be sure, but I think it's part of the stack trace of a report that the compiler could not interpret the `[[likely]]` attribute.
> 
> If you are able to build it, there is no problem with it working.

you are right:, I switched to` c++ lastest`, the warning no longer appears.
