### ISSUE TITLE
Bug: Results are combined into a single row object

### ISSUE THREAD

**Issue by Jaxkr** [jtv/libpqxx#485]
Following the example at https://libpqxx.readthedocs.io/en/7.1.2/a01338.html
There is only one field and field.c_str() is formatted like "(col1, col2, col3)" and field.name() simply returns "row".

I've tried every option of iterating over results from the link above, but none of them let me access individual column results. They all return a single field for each row with the entire row formatted as a string.

I am using C++20, Ubuntu 20.04. My table  schema contains a JSONB field if that matters, but even when I don’t select that column I am unable to access column values.

**Comment by jtv** [comment]
Which of the examples on that page are you following?  It may help to share a minimal functional reproduction of your code.

**Comment by Jaxkr** [comment]
Thanks for the speed response @jtv ! Sorry, I should have included a code sample in my original bug report.

```cpp
// tableName is sanitized, childIds are integers.
string selectQuery = "SELECT (x, y, z, unix_timestamp_ms) FROM \"" + returnedTableName + "\""
																					   R"( WHERE "childId_0"=)"
	+ to_string(childIds[0]) + R"( AND "childId_1"=)" + to_string(childIds[1]) + ";";

pqxx::work w{c};
pqxx::result r;
try {
  r = w.exec(selectQuery);
  w.commit();
} catch (pqxx::sql_error const &e) {
  if (e.sqlstate() == "42P01") {
	// table not found, move on to the next element in the loop.
	continue;
  }
}
cout << selectQuery << endl;
for (auto row: r) {
  for (auto const &field: row) {
	cout << "field name: " << field.name() << endl;
	cout << "value: " << field.c_str() << endl;
	cout << "column number: " << field.table_column();
  }
}
```

Expected output:
```
SELECT (x, y, z, unix_timestamp_ms) FROM "world,0,0,0" WHERE "childId_0"=0 AND "childId_1"=32;
field name: x
value: 10
column number: 0
field name: y
value: 76
column number: 1
field name: z
value: 1
column number: 2
field name: unix_timestamp_ms
value: 1632217068484
column number: 3
``````

Actual output:
```
SELECT (x, y, z, unix_timestamp_ms) FROM "world,0,0,0" WHERE "childId_0"=0 AND "childId_1"=32;
field name: row
value: (10,76,1,1632217068484)
terminate called after throwing an instance of 'pqxx::usage_error'
  what():  Can't query origin of column 0: not derived from table column.

```

**Comment by tt4g** [comment]
You are grouping columns in `SELECT (x, y, z, unix_timestamp_ms)` clause.
This is the expected behavior, since PostgreSQL treats a group as a single column.
To access individual columns, remove the parentheses `SELECT x, y, z, unix_timestamp_ms`.

**Comment by Jaxkr** [comment]
Good lord... I feel like an idiot. Thank you.
