### ISSUE TITLE
Segmentation fault when trying to iterate through the columns of result.

### ISSUE THREAD

**Issue by NysNight** [jtv/libpqxx#486]
I'm on C++17 because I have not found a way to change to C++20 while remote-developing on my Pi with VS2019 (If anyone can tell me how to achieve this, I'd be quite thankful for that too). I think the problem might be here, but I'm not sure.

I'm trying to read the result of: select * from PAC3200_test order by written_at desc limit 1;

Weather I try from the front or back, I always get 1 result before it gets a segmentation fault with `field.c_str()` 

from front:
```
    auto const& row = PSQL.Result[0];

    for (auto colum_num = 0; colum_num < row.size(); ++colum_num)
    {
        pqxx::field field = row[colum_num];
        std::cout << PSQL.Result.column_name(colum_num) << ": " << field.c_str() << std::endl;
    }
```
from back:
``` 
    auto const& row = PSQL.Result[0];

    for (auto colum_num = row.size() - 1; colum_num >= 0 ; --colum_num)
    {
        pqxx::field field = row[colum_num];
        std::cout << PSQL.Result.column_name(colum_num) << ": " << field.c_str() << std::endl;
    }
```

I tried to make it a little less convoluted by having the result returned to the function in main.cpp that I'm working in, then looking like this:

```
    auto result = PSQL.last_entry_by_date();
    auto const& row = result[0];

    for (int colum_num = 0; colum_num < row.size(); colum_num++)
    {
        pqxx::field field = row[colum_num];
        std::cout << result.column_name(colum_num) << ": " << field.c_str() << std::endl;
    }
```

which results in the same behaviour, but the error is slightly different:
in new_allocator.h (ln 125)
```
::operator delete(__p);
```
and my console writes:
`free(): double free detected in tcache 2`

**Comment by jtv** [comment]
Well the backwards one was always going to crash I guess, because your counter is unsigned and so won't turn negative when you go past zero.

C++17 is fine.  Current versions of libpqxx will work with C++17 or C++20.  (And presumably C++23).

I suspect there's a memory management bug somewhere outside the code you're showing here.  The trick of a good bug report is to bring it down to a minimal functional reproduction -- and usually the problem will become clear in that process.

**Comment by jtv** [comment]
Oh actually, it may be in there: `pqxx::result::operator[]` returns a `row` object.  You're not storing that anywhere, so the row object gets destroyed immediately, but your `row` variable is a _reference to_ the object that no longer exists.

I'm surprised your compiler didn't warn you about that.

**Comment by JadeMatrix** [comment]
> Oh actually, it may be in there: `pqxx::result::operator[]` returns a `row` object. You're not storing that anywhere, so the row object gets destroyed immediately, but your `row` variable is a _reference to_ the object that no longer exists.
> 
> I'm surprised your compiler didn't warn you about that.

It's `auto const& row`, so not surprising it thinks the `&&` → `const&` is okay, since it is for function arguments.  According to godbolt.org, GCC and Clang (latest) both warn about it, but MSVC (what @NysNight is using) does not.

**Comment by jtv** [comment]
So @NysNight to be clear, you need to change...

```cxx
    auto const& row = result[0];
```

to

```cxx
    auto const row = result[0];
```

**Comment by NysNight** [comment]
Busy weekend, but back at it now.

Did what @jtv recommended, but that didn't fix the problem.
so, for complete functions
in PsqlHandler.cpp:
```
pqxx::result PsqlHandler::last_entry_by_date() {

    std::string sql = "select * from PAC3200_test order by written_at desc limit 1;";
    
    try {
        pqxx::work Order(*Connection);
        Result = Order.exec(sql);
    }
    catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        std::cout << "last_entry_ba_date() failed.";
    }
    return Result;
}
```
where Result is declared in PsqlHandler.h (back where it belongs. During my first post I had it as public for testing purposes.)
```
class PsqlHandler {
private:
    std::string connectionString;
    pqxx::connection* Connection;
    pqxx::result Result;
public:
    //...
}
```
and in main.cpp:
```
int mqtt_pub(PsqlHandler PSQL) {

    //init MQTT client
    auto result = PSQL.last_entry_by_date();
    auto const row = result[0];

    for (int colum_num = 0; colum_num < row.size(); colum_num++)
    {    
        //pqxx::field field = row[colum_num];
        std::cout << result.column_name(colum_num) << ": " <<  std::endl;
        //instead of cout, publish with MQTT client
    }
    return 0;
}
```
You'll notice I cleaned out quite a bit here, for testing purposes. Now this only gives me the column names, obviously, not the values. Interestingly, I get exactly the same crash when `colum_num` reaches 9 (my current row.size() ).
To be precise, when stepping through the program with F10, this works while `colum_num` is still on 8 and and crashes when I press F10 on the `for (int colum_num = 0; colum_num < row.size(); colum_num++)` line.

If I change it to:
`std::cout << result.column_name(colum_num) << ": " << row[colum_num].c_str() << std::endl;`
I get both the colum_name and value in my output, but then it immediately crashes when pressing F10 on this line.

And lastly:
```
for (int colum_num = 0; colum_num < row.size(); colum_num++)
{
    pqxx::field field = row[colum_num];
    std::cout << result.column_name(colum_num) << ": " << field.c_str() << std::endl;
    //instead of cout-ing, publish to topic:colum_name and value field.c_str();
}
```
crashes when I press F10 on the `}`, so the end of the loop. I'm not super knowledgeable on C++, but I think this is the point where it would deconstruct the pqxx::field that I made in the loop, right?

In all 3 cases it's the same crash.
new_allocator.h line 125 at `::operator delete(__p);`
```
Excpetion Unhandled
Aborted
```
I can also change `int colum_num` to any other starting position between `0` and `row.size()`, and I'll always get the value for the first loop before it crashes.

**Comment by NysNight** [comment]
To further isolate the problem I made getResultFieldAt() in my PsqlHandler :
```
class PsqlHandler {
private:
    std::string connectionString;
    pqxx::connection* Connection;
    pqxx::result Result;
    
public:

    [...]

    pqxx::result last_entry_by_date();
    pqxx::field getResultFieldAt(int row, int col);
};

pqxx::field PsqlHandler::getResultFieldAt(int rowNr, int colNr) {
    auto row = Result[rowNr];
    auto field = row[colNr];
    return field;
}
```

This leads to the same abort as before when I reach -> `}` in this function (`getResultFieldAt()`) and press F10. Which again leads me to the assumption that the problem is with the deconstruction of pqxx::row &/ pqxx::field.

**Comment by NysNight** [comment]
Huh, I switched my compiler from Clang to gcc, now it works.

**Comment by tt4g** [comment]
As far as I know, libpq manages a lot of data in connection structures.
One of the well-known problems is that when the connection is closed, the result set becomes a dangling pointer.

Here it looks like the connection is not closed, but the transaction is commited when it leaves the `try` block in the following code.

```cpp
pqxx::result PsqlHandler::last_entry_by_date() {

    std::string sql = "select * from PAC3200_test order by written_at desc limit 1;";
    
    try {
        pqxx::work Order(*Connection);
        Result = Order.exec(sql);
    }
    catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        std::cout << "last_entry_ba_date() failed.";
    }
    return Result;
}
```

If `row` can be accessed in this `try` block, then the referenced address of the `Result` variable is considered to be destroyed at the end of the transaction.

**Comment by NysNight** [comment]
Well, at this point my actual problem has changed quite far from where this started originally, but just in case that it might be of interest my current **working** code (when using GCC) looks like this:
```
pqxx::result PsqlHandler::last_entry_by_date(std::string workTable, std::string timeStampName) {

    Result.clear();
    std::string sql = "select * from " + workTable + " order by written_at desc limit 1;"; 

    try {
        pqxx::work Order(*Connection);
        Result = Order.exec(sql);
    }
    catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        std::cout << "last_entry_by_date() failed." << std::endl;
    }


    return Result;
}
```
and:
```
int mqtt_pub( mqtt::client& MQTT,PsqlHandler PSQL) {

    auto result = PSQL.last_entry_by_date(psql_table_name, std::get<0>(column_tuples[0]));

    if (!MQTT.is_connected() )
    {
        return -1;
    }
    else if (result.empty())
    {
        return -2;
    }

    for (int colum_num = 0; colum_num < result[0].size(); colum_num++)
    {
        //std::cout << result.column_name(colum_num) << ": " << result[0][colum_num].c_str() << std::endl; //test line for priting out PSQL result.
        std::string topic =  psql_table_name + "/" + result.column_name(colum_num);
        const char* payload = result[0][colum_num].c_str();
        MQTT.publish(topic, payload, strlen(payload), 0, false);
    }

    return 0;
}
```
My PQXX connection is not closed during this, that only closes right at the end of my program.

This code works just fine when compiling with GCC, and aborts as described above with console output: `free(): double free detected in tcache 2`

**Since I wrote quite a bit altogether here is a TL;DR:**

Trying to work with the Result of a psql query leads to Unhandles Exceptions, with console output: 
`free(): double free detected in tcache 2` &  Unhandled Exception, Abort in new_allocator.h line 125 at `::operator delete(__p);` 
or Segmentation Faults (though this was under very specific circumstances, see  code in original post) when compiling with Clang (C++17) `clang version 7.0.1-8+rpi3+deb10u2`.
At the same time it works just fine when compiling with GCC (C++17) `gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1)`.
My best guess is that it has to do with the deconstruction of the structures `pqxx::result`, `pqxx::row` and `pqxx::field`.

**Comment by jtv** [comment]
Where does that Result variable come from?  Remember - minimal functional
reproduction is usually helpful.

By the way, don't include a terminating semicolon in your statement.  And
instead of calling strlen() on your field it's probably more efficient to
just use its size().

**Comment by NysNight** [comment]
From here: 
```cpp
class PsqlHandler {
private:
    std::string connectionString;
    pqxx::connection* Connection;
    pqxx::result Result;
    
public:

    _[...]_

    pqxx::result last_entry_by_date(std::string workTable, std::string timeStampName);
    };
```

And as far as I know I can't use .size() on a char* ? The MQTT.publish() function asks for a char* specifically there and doesn't work if I try to use a string. Though I guess I could make it a string and call .c_str(), if that's what you mean?

Lastly, it didn't occur to me that my sql statments wouldn't have to be terminated in this case. Why is that?

**Comment by jtv** [comment]
No the field itself has a size() member function:

    auto len = result[row][col].size()

The semicolon is needed when you're in some kind of shell environment where
you might want to enter multiple statements.  In such an environment, SQL
uses a semicolon to terminate a statement and indicate that the server can
start executing it.  But in libpqxx you execute one statement at a time, so
the question never comes up.

**Comment by jtv** [comment]
@NysNight did you get your problems sorted?

**Comment by jtv** [comment]
I'll have to close this ticket.  We'd need a minimally functional reproduction of the problem to do anything about it, and since the problem involves an exception, we'd need the exception's message as well.  We'd also need to see that the problems were not just the result of leaving an exception unhandled.  These are normally the basics of a programming bug report.  There's little point now if the problem is no longer relevant.

Rest assured that I regularly test libpqxx against multiple versions of both clang and gcc, as both C++17 and C++20, and with various tools for detecting these problems.  I am always on the lookout for such things, and if any more concrete signs of a bug show up, please do not hesitate to file a new bug.
