### ISSUE TITLE
Minor bug: Incorrect prepared statement reported on syntax error.

### ISSUE THREAD

**Issue by AlastairGrowcott** [jtv/libpqxx#488]
## How to reproduce:

1. Write code to create two prepared statements, call them "ps_1" and "ps_2". Do this as two separate transactions. I did this on two separate database connections in the same program. The second in a library and the first in a test application linked to the library.
2. Introduce a deliberate syntax error in the second prepared statement.
3. Catch the exception that will be generated and print e.what().
4. Run the code.

## Expected behaviour:

e.what() contains text like:

    Failure during '[PREPARE ps_2]': ERROR:  syntax error ...

## Actual behaviour:

e.what() contains text like:

    Failure during '[PREPARE ps_1]': ERROR:  syntax error ...

Note that the error is reported on prepared statement "ps_1" and not on prepared statement "ps_2" that actually contained the error.

**Comment by jtv** [comment]
If you prepared the two statements in separate connections, there should
not be any single place in either libpqxx or the database that can see both
names.

So this smells of accidental buffer reuse - perhaps a reference to a dead
std::string somewhere?

**Comment by AlastairGrowcott** [comment]
The two pieces of code callling into pqxx are absolutely separate. The names of the prepared statements are constant strings in the code, like this:

    try {
        f_db_connection->prepare("ps_1", "DELETE FROM my_table;");
    } catch (std::exception &e) {
        DIAG_ERROR("Error preparing ps_1 SQL: " + std::string{e.what()});
        result = false;
    }

As a side note, after I prepare "ps_1" I prepare 10 other statements in the same function.

**Comment by AlastairGrowcott** [comment]
I am guessing that, in the error message I get, "Failure during '[PREPARE ps_1]': " comes from libpqxx and the rest comes from the database?

The error reporting in the code where "ps_2" is prepared is basically identical, so the full error message I got was:

    "Error preparing ps_2 SQL: Failure during '[PREPARE ps_1]': ERROR:  syntax error...

which is how I spotted the bug.

**Comment by jtv** [comment]
That's right: the "[PREPARE ps_1]" string is a placeholder for the SQL
command that failed.  In this case there is no SQL statement, so libpqxx
fills in a pseudo-statement.

**Comment by jtv** [comment]
Got it!  There was a `static` variable that shouldn't have been.  Thanks for reporting this.

**Comment by AlastairGrowcott** [comment]
You're welcome. Glad it was fixed so easily.
