### ISSUE TITLE
Enhancement: Report error codes on failure.

### ISSUE THREAD

**Issue by AlastairGrowcott** [jtv/libpqxx#489]
There is a lot of conversation on this under issue #487 where this was (sorry) initially suggested.

It would be very useful for an application to be able to programmatically determine the cause of errors. Parsing strings is extremely awkward, difficult, and unreliable.

Note that error codes do not need to be excessively granular; an error code to indicate that an SQL statement failed is sufficient - it does not necessarily have to indicate the type of statement that failed or whether it failed due to a syntax error or a database restriction. In fact error codes on executing transactions are fairly unnecessary.

Where error codes really come into their own is when connecting to a database. There are many very different failure modes. E.g.:

- Failure to resolve the hostname.
- No route to host, or host does not exist.
- Host refused connection (not listening on that port).
- Host accepted TCP connection but database refused it because of pg_hba.conf settings.
- Authentication (username/password) failure.

The application can usefully behave differently in each of these cases.

**Comment by jtv** [comment]
@AlastairGrowcott Github is nagging me (not that I'm complaining!) about this ticket.  Did things work out with the SQLSTATE error codes you got from `pqxx::sql_error`?  Would special error codes for different types of _connection breakage_ still be useful, or do the existing error codes address your needs?

**Comment by AlastairGrowcott** [comment]
I'm really sorry that I haven't been able to get back to you on this or the async issue. Work has been difficult recently and now we have Christmas.

I just reviewed the documents tt4g linked for pqxx::sql_error::sqlstate():

    PQXX_PURE std::string const  & pqxx::sql_error::sqlstate() const

I don't see an error code. The function returns a string rather than any rot of numerical value, and there are no output parameters. The descriptive text reads:

    SQLSTATE error code if known, or empty string otherwise.

But "SQLSTATE" is not a link nor can I find this type in the documentation.

**Comment by jtv** [comment]
No rush - hope the work situation gets better.

SQLSTATE is a standard thing provided by the server.  Documentation is here:

https://www.postgresql.org/docs/9.4/errcodes-appendix.html

(The 9.4 is the postgres version - other versions should work as well)

All the best for the new year!
