### ISSUE TITLE
result get_value method is private

### ISSUE THREAD

**Issue by whatbeg** [jtv/libpqxx#495]
Why the `get_value` method of a result object is private? this means we cannot fetch the field value of row i, col j directly by a result object.
using res[i][j].c_str() will cause a copy of row object, which is expensive.
so i wonder, is it possible to let `get_value` method to be public?

**Comment by jtv** [comment]
For situations where you absolutely want high performance, consider `stream_from`.

In the longer term however, two changes are in the pipeline that will address your concerns:
1. libpqxx will drop the "result slicing" feature, and this will eliminate some overhead in looking up rows.
2. C++23 is expected to permit multi-dimensional subscript operators, and libpqxx will support them.

With that, I think I'll close the ticket.  Unless you have more to add, @whatbeg?

**Comment by jtv** [comment]
I'll close the ticket then.
