### ISSUE TITLE
sqlstate not available in exceptions

### ISSUE THREAD

**Issue by anse1** [jtv/libpqxx#5]
I'm about to switch [sqlsmith](https://github.com/anse1/sqlsmith) from libpqxx to libpq since the former doesn't record the sqlstate in exceptions.

I looked at the libpqxx code, but I wasn't sure where to introduce it in the class hierarchy.
For example, the standard also defines an sqlstate for errors that appear on the client side, so ideally we'd synthesize these.

also reported here: http://pqxx.org/development/libpqxx/ticket/219

**Comment by jtv** [comment]
Okay, okay, I'll change it!

What is the "the standard" that you're referring to?  I'd like to have a look first.  The SQL language-bindings recommendations?

**Comment by jtv** [comment]
Ah, the standard for SQLSTATE I guess.  It seems a little too much to introduce it for all client-side exceptions...  For now I'm just adding it to sql_error.

**Comment by jtv** [comment]
Okay — I just tagged 5.0.0, and added sql_error::sqlstate() in 5.0.1.  Please let me know how it works for you.

Important to know that the field can be empty, in cases where no sqlstate is known.  As you say we can extend this later by synthesising values, and perhaps moving the new information up the inheritance hierarchy.
