### ISSUE TITLE
[Docs] Wrong usage of quote() ?

### ISSUE THREAD

**Issue by arteniioleg** [jtv/libpqxx#50]
> http://pqxx.org/development/libpqxx/wiki/EmployeeExample
> 
> ```cpp
> void add_employee(pqxx::transaction_base &txn, std::string name, int department)
> {
>   // Use quote() to escape and quote a value safely for use in a
>   // query.  Avoid bugs and security holes when strings contain
>   // backslashes, quotes, or other "weird" characters.
>   // That's not very useful for department (an integer), but it
>   // also represents the value as a string.  We don't want to add
>   // an int to the query, we want to add a string that represents
>   // the int value.
>   txn.exec(
>     "INSERT INTO Employee(name, department) "
>     "VALUES (" +
>     txn.quote(name) + ", " +
>     txn.quote(department) +
>     ")");
> }
> ```

`quote()` calls `quote_raw()` -> `esc_raw()` -> [PQescapeByteaConn()](https://www.postgresql.org/docs/10/static/libpq-exec.html#LIBPQ-PQESCAPEBYTEACONN) which does:

> Escapes binary data for use within an SQL command with the type bytea.

`esc()` calls [PQescapeStringConn()](https://www.postgresql.org/docs/10/static/libpq-exec.html#LIBPQ-PQESCAPESTRINGCONN)

I think the above code should be fixed to:

```cpp
txn.exec(
    "INSERT INTO Employee(name, department) "
    "VALUES (" +
    "'" + txn.esc(name) + "', " +
    "'" + txn.esc(std::to_string(department)) + "'" +
    ")");
```

----

From the docs I got confused about when to use `quote()` and when `esc()` that's why I started investigating the library code. I am still confused because I can't make these two functions return different results to understand the difference (I tried all kinds of characters including unicode).

```cpp
#include <iostream>
#include <pqxx/pqxx>

int main() {
    pqxx::connection c{"postgresql://..."};
    pqxx::work tx{c};

    std::string text{"Hi ' %"};
    std::cout
        << ' ' << tx.esc(text) << std::endl
        << tx.quote(text) << std::endl;

    return 0;
}
```

Output

```text
 Hi '' %
'Hi '' %'
```

**Comment by jtv** [comment]
It's slightly more complicated: _there is a specialisation_ of `quote` that calls `quote_raw`.  But that's only for the case where you pass it a `binarystring`.  For other types, you get the template version of `quote` which converts whatever you gave it to `std::string`, calls `esc`, and adds quotes around it.

So it's really pretty simple: `esc` escapes problematic characters inside your string, and `quote` does the same but also adds the quotes.  That's exactly what your experiment shows.

(For `binarystring` the only option is `quote`; there is no `esc` for that type.)

Assuming that that clears it up, is there something that you think I could change to make this clearer?

**Comment by arteniioleg** [comment]
All clear. Thank you for fast reply!
