### ISSUE TITLE
How to exec a enum Type into a table?

### ISSUE THREAD

**Issue by nickel823** [jtv/libpqxx#503]
For example: 
First,  I create a table field's type as below:
 "create type test as enum('good','bad');"
Then how can i insert a row into the table use pqxx API?
Looking forward to your reply.

**Comment by tt4g** [comment]
As far as I know, most statements should work if you typecast the columns.

```sql
CREATE TYPE test AS ENUM('good','bad');
CREATE TABLE foo (
  id SERIAL PRIMARY KEY,
  test_value test NOT NULL
);
```

```cpp
#include <pqxx/pqxx>

int main()
{
    try
    {
        pqxx::connection connection;
        pqxx::work transaction{connection};

        transaction.prepare(
            "insert_foo",
            "INSERT INTO foo (test_column) VALUES($1::test)");
        transaction.exec_prepared("insert_foo", "good");
        transaction.exec_prepared("insert_foo", "bad");
        transaction.commit();

        pqxx::result result = transaction.exec("SELECT id, test_column::varchar FROM foo"):
        for (auto row : result) {
            std::cout << "id: " << row[0].c_str() << " test_column: " << row[1].c_str() << '\n';
        }

        transaction.commit();
    } catch (std::exception const &ex) {
        std::cerr << e.what() << '\n';

        return 1;
    }

    return 0;
}
```

**Comment by nickel823** [comment]
thanks it works，finally i found that there’s a mistake made by me！ what a shame，thank you！



---Original---
From: ***@***.***&gt;
Date: Wed, Dec 1, 2021 20:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jtv/libpqxx] How to exec a enum Type into a table? (Issue #503)




 
As far as I know, most statements should work if you typecast the columns.
 CREATE TYPE test AS ENUM('good','bad'); CREATE TABLE foo (   id SERIAL PRIMARY KEY,   test_value test NOT NULL );
 #include <pqxx/pqxx&gt; int main() {     try     {         pqxx::connection connection;         pqxx::work transaction{connection};         transaction.prepare(             "insert_foo",             "INSERT INTO foo (test_column) VALUES($1::test)");         transaction.exec_prepared("insert_foo", "good");         transaction.exec_prepared("insert_foo", "bad");         transaction.commit();         pqxx::result result = transaction.exec("SELECT id, test_column::varchar FROM foo"):         for (auto row : result) {             std::cout << "id: " << row[0].c_str() << " test_column: " << row[1].c_str() << '\n';         }         transaction.commit();     } catch (std::exception const &amp;ex) {         std::cerr << e.what() << '\n';         return 1;     }     return 0; }
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jtv** [comment]
Glad to hear it's solved!  Shall we close the bug then?

**Comment by nickel823** [comment]
of course！



---Original---
From: "Jeroen ***@***.***&gt;
Date: Thu, Dec 2, 2021 20:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jtv/libpqxx] How to exec a enum Type into a table? (Issue #503)




 
Glad to hear it's solved!  Shall we close the bug then?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jtv** [comment]
Excellent, thanks.

**Comment by Algebro7** [comment]
Apologies for resurrecting an old issue, but how can you do this when the type is represented as an `enum` in C++ as well? For example, this is resulting in NULL being saved to the DB in the color_pref column:

```
enum Color : int {
    RED,
    BLUE,
    GREEN
};

[...]

namespace pqxx { PQXX_DECLARE_ENUM_CONVERSION(Color); }

    m_connection->prepare("save_color",
                          "INSERT INTO prefs ("
                          "name, "
                          "color_pref"
                          ") "
                          "VALUES ($1, $2::color)"

    exec_prepared("save_color", person.name(),
                      person.color_pref());
```
I also tried with `pqxx::to_string(person.color_pref())` but that didn't work either. Any idea what I could be doing wrong?

**Comment by tt4g** [comment]
@Algebro7 `PQXX_DECLARE_ENUM_CONVERSION` is a helper macro that converts C++ `enum` to its original numeric type.
The `enum Color` value cast to a number is bound to the SQL parameter (`RED` to `0`, `BLUE` to `1`, `GREEN` to `2`).

> **NOTE**
> This feature does not interconvert with PostgreSQL's `ENUM`.

PostgreSQL provides `ENUM`, which is cast from a string literal (e.g. `'RED'::color`).

Your source code is trying to cast a number to PostgreSQL `ENUM` and failing, so I think it is not working the way you want it to.

**Comment by Algebro7** [comment]
> Your source code is trying to cast a number to PostgreSQL ENUM and failing, so I think it is not working the way you want it to.

Thanks for the explanation! So is the only solution either to change the column in Postgres to an int or to write a function to convert the enum values in C++ to strings?

**Comment by tt4g** [comment]
Yes. The ability to convert C++ `enum` is not provided by the C++ standard.
However, there are some libraries that extend C++ `enum`.
[Neargye/magic_enum](https://github.com/Neargye/magic_enum) provides `magic_enum::enum_name()` which returns a string literal of `enum`.

**Comment by jtv** [comment]
To be precise, `PQXX_DECLARE_ENUM_CONVERSION` does not _convert_ an enum value, but it _defines a conversion_ for an enum type.  See the "Supporting additional data types" section of the documentation (or in the source tree, `include/pqxx/doc/datatypes.md`).
