### ISSUE TITLE
Usage examples in comments of the deprecated `.prepared()`

### ISSUE THREAD

**Issue by arteniioleg** [jtv/libpqxx#51]
https://github.com/jtv/libpqxx/blob/a70fb656e769cd585938fc156e300407e50784c2/include/pqxx/connection_base.hxx#L502

https://github.com/jtv/libpqxx/blob/a70fb656e769cd585938fc156e300407e50784c2/include/pqxx/transaction_base.hxx#L429

Should be replaced with `exec_prepared()`.

**Comment by jtv** [comment]
Indeed.  Thanks for spotting it.
