### ISSUE TITLE
pqxx::connection issue

### ISSUE THREAD

**Issue by ROCKFAL1** [jtv/libpqxx#510]
Hello, I think it is necessary to remove the default constructor in pqxx::connection (connection.hxx / 183 line) because it immediately throws an exception. 

```
class A
{
pqxx::connection con;

public:
  A()
  {
  }
}

int main()
{
    A instance;
}
```

Even code like this will throw an exception.
When I was writing my code, I had a {pqxx::connection con} field in my base class and it took me about half an hour to figure out what the problem was. As a result, I just wrapped it in std::unique_ptr. In general, I think that the constructor of a class that will throw an exception in any case is abnormal.

**Comment by jtv** [comment]
The default constructor still creates a connection, but with the default settings.  Obviously this can fail.

**Comment by KayEss** [comment]
> I just wrapped it in std::unique_ptr.

A better way to do defer construction (in most instances at least) is to use a `std::optional` instead -- that will avoid the memory allocation the `unique_ptr` forces.

**Comment by ROCKFAL1** [comment]
Well, thanks for the answer and for the idea with std::optional, because I wouldn't have guessed it myself :)
