### ISSUE TITLE
There is a data structure conversion question, need your help(this may not be a issue)

### ISSUE THREAD

**Issue by nickel823** [jtv/libpqxx#514]
My issue is that I use std::vector<uint8_t> in C++ to represent a SHA-1 hash, which I then need to store in Postgress as BYTEA. So now I need to find a way to convert std::vector<uint8_t> to std::basic_string < std::byte >  and back. 
For std::vector<uint8_t> to std::basic_string < std::byte >  is: 
std::basic_string < std::byte >  a(
    static_cast<const std::byte *>(static_cast<const void *>(data.data())),
    data.size()
);

But what about std::basic_string < std::byte >  to std::vector<uint8_t>?

**Comment by jtv** [comment]
One thing you can do is take a pointer to the vector's data(), cast that to
a std::byte const pointer, and use it to create a
std::string_view<std::byte>.

That way you don't need to move any data around.  It's just a pointer cast.

**Comment by jtv** [comment]
Correction: of course the type you want is `std::basic_string_view<std::byte>`.  I left out the "`basic_`" part.

**Comment by nickel823** [comment]
> Correction: of course the type you want is `std::basic_string_view<std::byte>`. I left out the "`basic_`" part.

sorry, you told is the way from std::vector<uint8_t> to std::basic_string < std::byte >, but my issue is convert std::basic_string < std::byte > to std::vector<uint8_t>?

**Comment by nickel823** [comment]
thanks，this way is correct.
