### ISSUE TITLE
Executing prepared statement with vec of params

### ISSUE THREAD

**Issue by sonicxml** [jtv/libpqxx#521]
I'm currently trying to generate and execute prepared statements dynamically (i.e. at runtime). This means I won't know the number of parameters for each prepared statement until they're generated at runtime. When executing, I have a `std::vector<std::string>` of parameters. The problem is that there does not seem to be a way to pass these parameters into the `exec_prepared` function, since that forces the parameters to be function arguments.

Is there any way around this, or do you know of any better way to do this dynamic prepared statement generation & execution?

Thanks!

**Comment by jtv** [comment]
Use `pqxx::params`.

**Comment by jtv** [comment]
I hope my previous reply came through.  Don't use a `std::vector<std::string>` for this; libpqxx will try to translate that to an SQL _array_ of strings, as a single parameter.

Instead, create a `pqxx::params` object, and pass that as a parameter value.  It supports the "builder" pattern, where you append your values one by one.  But also, you can feed it some initial parameter values as constructor arguments to make it easier.  It also supports `reserve()` to minimise memory allocation overhead.

You can also combine `pqxx::params` with the compile-time scheme: you can pass multiple arguments to `exec_prepared()`, and one or more of those can be `pqxx::params` values.  Each will "expand" into whatever parameter values it contains.

Finally, a `pqxx::params` can in turn contain `pqxx::params` values.  But you'll probably want to keep things simple.  :-)

**Comment by sonicxml** [comment]
Ah, got it. Thanks for the help!!
