### ISSUE TITLE
what is the right code for adding libpqxx library to cmakelists.txt? 

### ISSUE THREAD

**Issue by xkungfu** [jtv/libpqxx#522]
In old version 6.3.4, I wrote code like below and it works:

```
# postgresql 
find_package(PostgreSQL REQUIRED)
include_directories(I:/CXXlibs/LIBPQXX/libpqxx-6.3.4/build/include)
include_directories(I:/CXXlibs/LIBPQXX/libpqxx-6.3.4/include)

... ...

target_link_libraries(${PROJECT_NAME} PRIVATE pqxx)
target_link_directories(${PROJECT_NAME} PRIVATE "I:/CXXlibs/LIBPQXX/libpqxx-6.3.4/build/src")
```

but it don't work now for new version 7.7.0. 

I search from googles, issues, read readme.md and examples,  
and I tried lots of modified and they all not work. 

so what is the exactly right way to merage libpqxx to cmakelists.txt?

**Comment by KayEss** [comment]
How are you getting libpqxx? Is it separately compiled, or are you using `add_subdirectory` with the libpqxx repo?

**Comment by xkungfu** [comment]
I installed libpqxx 7.7.0 by below steps:

```
cd I:\CXXlibs\LIBPQXX\libpqxx-7.7.0\build

cmake .. -G "MinGW Makefiles"

cmake --build .
make install
```

**Comment by xkungfu** [comment]
I tried to modify to the codes below:
```

list(APPEND CMAKE_PREFIX_PATH I:/CXXlibs/LIBPQXX/libpqxx-7.7.0/build/)
find_package(PostgreSQL REQUIRED)
find_package(libpqxx REQUIRED)
include_directories(I:/CXXlibs/LIBPQXX/libpqxx-7.7.0/build/include)
include_directories(I:/CXXlibs/LIBPQXX/libpqxx-7.7.0/include)

... ... 



target_link_libraries(catchfly PUBLIC pqxx pq)
target_link_directories(catchfly PUBLIC "I:/CXXlibs/LIBPQXX/libpqxx-7.7.0/build")
target_link_directories(catchfly PUBLIC "I:/CXXlibs/LIBPQXX/libpqxx-7.7.0/build/src")
```

got error is :

error: cannot find -lpq

**Comment by tt4g** [comment]
CMake target name `pq` is wrong, `PostgreSQL::PostgreSQL` is correct.

```diff
-target_link_libraries(catchfly PUBLIC pqxx pq)
+target_link_libraries(catchfly PUBLIC pqxx PostgreSQL::PostgreSQL)
```

https://cmake.org/cmake/help/v3.22/module/FindPostgreSQL.html:

> This module defines IMPORTED target PostgreSQL::PostgreSQL if PostgreSQL has been found.

**Comment by xkungfu** [comment]
thank you very much! this code works correctly now!

**Comment by jtv** [comment]
Thanks @tt4g & @KayEss for jumping in!
