### ISSUE TITLE
Is there a way to convert columns of  result of selecting query to vector ?

### ISSUE THREAD

**Issue by xkungfu** [jtv/libpqxx#525]
I tried the codes below:
```

        pqxx::connection C;
        pqxx::work W{C};
        pqxx::result R{W.exec(querystr)};

        for (int colum_num = 0; colum_num < R[0].size(); colum_num++)
        {

            std::string current_column_name = R.column_name(colum_num);
            //const char* payload = R[0][colum_num].c_str();
            int current_column_data_type = R.column_type(colum_num);

            if(current_column_data_type == 1700){

                //convert current column to std::vector<double>:

                std::vector<double> current_vector;
                std::transform(R[colum_num].begin(), R[colum_num].end(), std::back_inserter(current_vector), [](const pqxx::field &c){ return atoi(c.c_str()); });


                //deal with this vector

            } else if(current_column_data_type == 1043){

                //convert current column to std::vector<std::string>:

                std::vector<std::string> current_vector;
                std::transform(R[colum_num].begin(), R[colum_num].end(), std::back_inserter(current_vector), [](const auto &c){ return to_string(c); });
                //deal with this vector

            } else {
                // ...
            }
        }
```

as you can see, I tried to convert a column to vector but fail,  R[colum_num] is a value of row in fact.

so, how to get all values of one column?

 how to convert a column to vector?

thanks!

**Comment by jtv** [comment]
There's no direct way of doing that.  The `result` layout is row major, and there's no real point in changing that.  So I think the best way would be to stream the query and build the column vector...  unless you can find an SQL trick to transpose the rows and columns.

**Comment by xkungfu** [comment]
It seems all solutions are very very complex.
I think I wouldn't implement this forever. 
I am falling into this issue because I use hosseinmoein's Dataframe. it take hours if adding data row by row to a dataframe variable.

now I am trying to define some map before iterating pqxx query result. and make column name as map's key, pushing column values into a vector as map's value.

after iterating, continue to iterate all map and store all vectors into Dataframe.

for newbie I only can do this mindless way.

thank you very much.

**Comment by jtv** [comment]
I suppose we can close this one now.
