### ISSUE TITLE
Compilation issues after installing pqxx 7.6.0 unable to resolve them 

### ISSUE THREAD

**Issue by dpasha52** [jtv/libpqxx#527]
Hi , 
I have been facing some compilation issues after installing this library

My code doesn't contain much , except inlcudeing the header file 
`#include<iostream.h>
#include <pqxx>
int main () {

}
`
I believe I am linking the correct .so files and including the right headers while compiling 

command for compiling :
**g++ -L/usr/local/pqxx/lib -I/usr/local trydb.cpp -lpqxx -lpq**

In file included from /usr/local/pqxx/array.hxx:18,
from /usr/local/pqxx/array:4,
from /usr/local/pqxx/pqxx:2,
from trydb.cpp:2:
/usr/local/pqxx/internal/encodings.hxx:24:42: error: ‘pqxx::internal::encoding_group pqxx::internal::enc_group’ redeclared as different kind of symbol
encoding_group enc_group(std::string_view);
^
/usr/local/pqxx/internal/encodings.hxx:23:16: note: previous declaration ‘pqxx::internal::encoding_group pqxx::internal::enc_group(int)’
encoding_group enc_group(int /* libpq encoding ID */);
^~~~~~~~~
/usr/local/pqxx/internal/encodings.hxx:24:31: error: ‘string_view’ is not a member of ‘std’
encoding_group enc_group(std::string_view);
^~~~~~~~~~~
/usr/local/pqxx/internal/encodings.hxx:24:31: note: ‘std::string_view’ is only available from C++17 onwards
/usr/local/pqxx/internal/encodings.hxx:39:28: error: ‘std::string_view’ has not been declared
encoding_group enc, std::string_view haystack, char needle,
^~~~~~~~~~~
/usr/local/pqxx/internal/encodings.hxx:44:28: error: ‘std::string_view’ has not been declared
encoding_group enc, std::string_view haystack, std::string_view needle,
^~~~~~~~~~~
/usr/local/pqxx/internal/encodings.hxx:44:55: error: ‘std::string_view’ has not been declared
encoding_group enc, std::string_view haystack, std::string_view needle,
^~~~~~~~~~~
In file included from /usr/local/pqxx/array:4,
from /usr/local/pqxx/pqxx:2,
from trydb.cpp:2:
/usr/local/pqxx/array.hxx:66:21: error: expected ‘)’ before ‘input’
std::string_view input,
^~~~~~
)
/usr/local/pqxx/array.hxx:65:24: note: to match this ‘(’
explicit array_parser(
^
/usr/local/pqxx/array.hxx:78:8: error: ‘string_view’ in namespace ‘std’ does not name a type
std::string_view m_input;
^~~~~~~~~~~
/usr/local/pqxx/array.hxx:78:3: note: ‘std::string_view’ is only available from C++17 onwards
std::string_view m_input;
^~~
In file included from /usr/local/pqxx/result.hxx:25,
from /usr/local/pqxx/binarystring.hxx:21,
from /usr/local/pqxx/binarystring:4,
from /usr/local/pqxx/pqxx:3,
/usr/local/pqxx/util.hxx:54:44: warning: inline variables are only available with -std=c++17 or -std=gnu++17
[[nodiscard]] inline std::string cat2(std::string_view x, std::string_view y)
^~~~~~~~~~~
/usr/local/pqxx/util.hxx:54:44: warning: ‘nodiscard’ attribute can only be applied to functions or to class or enumeration types [-Wattributes]
/usr/local/pqxx/util.hxx:54:44: error: ‘string_view’ is not a member of ‘std’
/usr/local/pqxx/util.hxx:54:44: note: ‘std::string_view’ is only available from C++17 onwards
/usr/local/pqxx/util.hxx:54:64: error: ‘string_view’ is not a member of ‘std’
[[nodiscard]] inline std::string cat2(std::string_view x, std::string_view y)
^~~~~~~~~~~
/usr/local/pqxx/util.hxx:54:64: note: ‘std::string_view’ is only available from C++17 onwards
/usr/local/pqxx/util.hxx:55:1: error: expected ‘,’ or ‘;’ before ‘{’ token
{
^
/usr/local/pqxx/util.hxx:79:39: error: ‘std::string_view’ has not been declared
inline TO check_cast(FROM value, std::string_view description)
^~~~~~~~~~~
/usr/local/pqxx/util.hxx: In function ‘TO pqxx::check_cast(FROM, int)’:
/usr/local/pqxx/util.hxx:81:22: error: ‘is_arithmetic_v’ is not a member of ‘std’
static_assert(std::is_arithmetic_v<FROM>);
^~~~~~~~~~~~~~~
/usr/local/pqxx/util.hxx:81:22: note: suggested alternative: ‘is_arithmetic’
static_assert(std::is_arithmetic_v<FROM>);
^~~~~~~~~~~~~~~
is_arithmetic
/usr/local/pqxx/util.hxx:81:42: error: expected primary-expression before ‘>’ token
static_assert(std::is_arithmetic_v<FROM>);
^
/usr/local/pqxx/util.hxx:81:43: error: expected primary-expression before ‘)’ token
static_assert(std::is_arithmetic_v<FROM>);
^
/usr/local/pqxx/util.hxx:82:22: error: ‘is_arithmetic_v’ is not a member of ‘std’
static_assert(std::is_arithmetic_v<TO>);
^~~~~~~~~~~~~~~
/usr/local/pqxx/util.hxx:82:22: note: suggested alternative: ‘is_arithmetic’
static_assert(std::is_arithmetic_v<TO>);
^~~~~~~~~~~~~~~
is_arithmetic
/usr/local/pqxx/util.hxx:82:40: error: expected primary-expression before ‘>’ token
static_assert(std::is_arithmetic_v<TO>);
^
/usr/local/pqxx/util.hxx:82:41: error: expected primary-expression before ‘)’ token
`
We did fix the first part of the error by including  -std=c++17 in our command to resolve the compatibility issues But We are still facing some other errors and issues.
we have tried adding the flag c++2a during compilation yet we are still facing few issues Below are the errors  

**(g++ -L/usr/local/pqxx/lib -I/usr/local trydb.cpp std=c++17 -lpqxx -lpq** 

g++ -L/usr/local/pqxx/lib -I/usr/local trydb.cpp -lpqxx -lpq -std=c++17 
In file included from /usr/local/pqxx/array.hxx:14,
from /usr/local/pqxx/array:4,
from /usr/local/pqxx/pqxx:2,
from trydb.cpp:2:
/usr/local/pqxx/params.hxx: In member function ‘void pqxx::placeholders<COUNTER>::next()’:
/usr/local/pqxx/compiler-public.hxx:117:24: error: expected identifier before ‘[’ token
`#` define PQXX_LIKELY [[likely]]
^
/usr/local/pqxx/params.hxx:169:7: note: in expansion of macro ‘PQXX_LIKELY’
PQXX_LIKELY
^~~~~~~~~~~
In file included from /usr/local/pqxx/connection.hxx:37,
from /usr/local/pqxx/transaction_base.hxx:32,
from /usr/local/pqxx/dbtransaction.hxx:19,
from /usr/local/pqxx/blob.hxx:33,
from /usr/local/pqxx/blob:4,
from /usr/local/pqxx/pqxx:4,
from trydb.cpp:2:
/usr/local/pqxx/params.hxx: In lambda function:
/usr/local/pqxx/params.hxx:171:7: error: expected ‘{’ before ‘++’ token
++m_buf[m_len - 1];
^~
/usr/local/pqxx/params.hxx: In member function ‘void pqxx::placeholders<COUNTER>::next()’:
/usr/local/pqxx/params.hxx:171:9: error: expected ‘;’ before ‘m_buf’
++m_buf[m_len - 1];
^~~~~
;
In file included from /usr/local/pqxx/array.hxx:14,
from /usr/local/pqxx/array:4,
from /usr/local/pqxx/pqxx:2,
from trydb.cpp:2:
/usr/local/pqxx/field.hxx: In member function ‘T pqxx::field::as() const’:
/usr/local/pqxx/compiler-public.hxx:118:26: error: expected identifier before ‘[’ token
 `#` define PQXX_UNLIKELY [[unlikely]]
^
/usr/local/pqxx/field.hxx:221:9: note: in expansion of macro ‘PQXX_UNLIKELY’
PQXX_UNLIKELY
^~~~~~~~~~~~~
In file included from /usr/local/pqxx/row.hxx:20,
from /usr/local/pqxx/transaction_base.hxx:37,
from /usr/local/pqxx/dbtransaction.hxx:19,
from /usr/local/pqxx/blob.hxx:33,
from /usr/local/pqxx/blob:4,
from /usr/local/pqxx/pqxx:4,
from trydb.cpp:2:
/usr/local/pqxx/field.hxx: In lambda function:
/usr/local/pqxx/field.hxx:222:7: error: expected ‘{’
internal::throw_null_conversion(type_name<T>);

`
We tried to fix the above mentioned errors using the command given below by adding c++2a yet we were unable to figure this out 
**# g++ -L/usr/local/pqxx/lib -I/usr/local trydb.cpp -lpqxx -lpq -std=c++2a**

Any help is greatly appreciated. 
PS sorry for the long post.

**Comment by jtv** [comment]
My first guess would be that you're working with different compilers (or compiler versions) when _building_ libpqxx vs. when _using_ libpqxx.  It sounds like the g++ version you're using while _using_ libpqxx is too old — the errors you show here would have prevented it from building libpqxx in the first place.

(Also, don't include `<iostream.h>`; include `<iostream>`.  That changed a long time ago, and the difference may affect compilation.)

**Comment by dpasha52** [comment]
We did try g++ -version while compilation it shows 7.8 , while do I check the other version we use ?

**Comment by jtv** [comment]
g++ 7 is definitely too old.  I would recommend upgrading to g++-11 if you can, but anything newer than 7.x should still work for now.  If we're lucky the problem will just go away then.

To find out what compiler you used for building libpqxx, you'll have to figure out how your libpqxx got installed.  If you just installed a third-party package, I wouldn't worry about it and focus on upgrading your compiler.

**Comment by dpasha52** [comment]
Will the same thing work if we use a lower version of pqxx (7.0.0)? I was going through that library branch it's mentioned there that c++17 support starts after that brach.

**Comment by jtv** [comment]
It requires C++17 from 7.0.0 onwards.  And 8.0.0 will probably require C++20.  (Doesn't have to be _complete_ support, but some of the basic features.)

So yes, downgrading to libpqxx 6 would solve this problem, but expose you to any problems that have been fixed in newer versions.  It also won't be as fast as the newer versions.  If at all possible, move forwards, not backwards!

**Comment by dpasha52** [comment]
Thank you, I'll mark this closed as soon as I find a fix for this problem, hope I can keep it alive till then. 
Thanks again.

**Comment by jtv** [comment]
No worries.

**Comment by dpasha52** [comment]
Moving down to libpqxx 6.x.x helps us resolve this issue. Marking the thread closed. Thank you
