### ISSUE TITLE
Documentation doesn't seem to describe usage of pqxx::connection constructor

### ISSUE THREAD

**Issue by keithstellyes** [jtv/libpqxx#53]
The tutorial says it's passed a string for options but doesn't really help anymore than that. I was confused on documentation for it (I was not familiar with the C binding)

A quick StackOverflow search lead me here: https://stackoverflow.com/questions/11202996/strange-behavior-for-libpq-with-pqconnectdb which says it's just using `PQconnectStart`, my look-over the source code seems to confirm this.

Perhaps documentation should at the very least reference this libpqc doc? https://www.postgresql.org/docs/9.0/static/libpq-connect.html I certainly would've saved time. I'd be willing to give a PR to fix this.

**Comment by jtv** [comment]
You're right — I think that's a holdover from days when I was thinking about how to support other database engines.

I could add something, but a PR would be better.  Gets your name officially in there.  :)

**Comment by keithstellyes** [comment]
Filed a PR :)

**Comment by jtv** [comment]
Approved and merged.  Thanks!
