### ISSUE TITLE
Build error: missing #include "pqxx/internal/compiler-public.hxx" in except.hxx

### ISSUE THREAD

**Issue by egorpugin** [jtv/libpqxx#530]
except.hxx uses PQXX_PURE but does not include "pqxx/internal/compiler-public.hxx"

![image](https://user-images.githubusercontent.com/4325333/151840319-61377105-7980-46f7-95cb-66458cb64d88.png)

**Comment by jtv** [comment]
But `except` does.  So if this goes wrong, it probably means that something is including `pqxx/except.hxx` when it should be including `pqxx/except`.

**Comment by egorpugin** [comment]
I see.
I had `#include <pqxx/connection.hxx>` instead of no ext.

**Comment by egorpugin** [comment]
Maybe `.hxx` headers could tell that we should not include them?
```
#ifndef USUAL_PQXX_HEADER
#error include non .hxx header
#endif
```

**Comment by jtv** [comment]
Good idea.  I'll reopen this bug as a reminder.
