### ISSUE TITLE
need to replace values in sqlstatement

### ISSUE THREAD

**Issue by dpasha52** [jtv/libpqxx#532]
Hi ,
I am trying to find alternatives for occi::stmt::setxxx() in postgres
The gist of the function setXXX ( setString , setdate) is that it will replace some sql satement with appropriate values for the field num:
Ex:
prep_stmt = con->prepareStatement("INSERT INTO test(id, label) VALUES (?, ?)");

prep_stmt->setInt(1, 1);
prep_stmt->setString(2, "a")
1 goes into first ?
a goes into second ?

What's the alternative for this ,
As far as my code goes 
I am 
doing the following 

create a conn
conn.prepare("statement ", sqlstamt)
create a glogal transaction tx
tx.doexecprepared("statement")

Any help is grealty appreciated.
Thank you 
dpasha52

**Comment by jtv** [comment]
There are many alternative ways to do it.  Probably the easiest is: `tx.exec_params("INSERT INTO test(id, label) VALUES ($1, $2)", 1, "a")`.

Prepared statements usually aren't worth the bother.  But if you want to do a large number of inserts, have a look at `pqxx::stream_to` for a faster, and pretty simple way to do it.

If you want to do `exec_params` but you don't know at compile time what the arguments will look like, pass a `pqxx::params` containing your arguments.

**Comment by jtv** [comment]
@dpasha52 you can use [prepared statements](https://libpqxx.readthedocs.io/en/stable/a01428.html), if that's what you mean.

Alternatively, you can compose query strings using the [pqxx::transaction_base::quote()](https://libpqxx.readthedocs.io/en/stable/a00243.html#ga6476b6d27bb27a6eb8767080cc3e6a49) helper functions.

**Comment by dpasha52** [comment]
Thank you.
I'll close this thread.
