### ISSUE TITLE
Error when building the VS2019 dll project when connecting pqxx

### ISSUE THREAD

**Issue by vatnic** [jtv/libpqxx#533]
when building the VS2019 dll project, when connecting pbx, an error occurs "a link to the parameter package "Args" is present, but the package is not disclosed" in the file conversions.hxx, in the blocks:

```cxx
/// We don't know how to pass array params in binary format, so pass as text.
template<typename T, typename... Args, Args... args>
inline constexpr format param_format(std::array<T, args...> const &)
{
  return format::text;
}


/// An array of @c std::byte is a binary string.
template<typename... Args, Args... args>
inline constexpr format param_format(std::array<std::byte, args...> const &)
{
  return format::binary;
}
```

And Error C2589 (: invalid token to the right of "::" params.ltx line 127

With a similar connection in the console application, it works without errors. We use C++ 20.

**Comment by jtv** [comment]
(I've edited the code in your message for formatting.  Triple backquotes mark a "preformatted" block in Markdown syntax.)

No idea what that error means!  I tried searching the internet for the text pattern but found nothing.  Have you tried a newer compiler version?  If nothing else, it may give you a more helpful error message.

**Comment by jtv** [comment]
That C2589 error puzzles me as well...  I see nothing weird immediately to the right of a `::` in the code you quote.  Nor do I know what params.ltx is...  Is that a precompiled header?

**Comment by tt4g** [comment]
My guess is that your project has `#include <format>` (to enable `std::format`) and you are also using `using namespace std;`.

This allows `std::format` to be called with `foramt`.
The compiler has interpreted `format::binary` as `std::format::binary`, but the `Args` template argument for `std::format` is missing, so the compilation fails.

In many cases, the following declarations are used in `std::format`:

```c++
namespace std
{

template<class... Args>
string format(string_view fmt, const Args&... args);

}
```

**Comment by jtv** [comment]
Good point @tt4g!

Yes, be careful with `using namespace`.  I no longer use it.  It's still sort of OK with just _one_ namespace, but if you're `using` _two_ namespaces that's very likely to lead to problems.

**Comment by vatnic** [comment]
> params.ltx it is params.hxx  - the translator that I use for some reason changed the name in its own way...

**Comment by vatnic** [comment]
I have removed all the extra code of my project to a minimum:
//------------------------------
#include "pch.h"
#include <pqxx/pqxx>

BOOL APIENTRY DllMain(HMODULE hModule,
    DWORD  ul_reason_for_call,
    LPVOID lpReserved
)
{
    return TRUE;
}
//------------------------------
and here is the output of my compiler:
Rebuild started...
1>------ Rebuild All started: Project: PGDriverLibrary, Configuration: Debug x64 ------
1>pch.cpp
1>dllmain.cpp
1>C:\vcpkg-master\installed\x64-windows\include\pqxx\params.hxx(127,35): warning C4003: not enough arguments for function-like macro invocation 'max'
1>C:\vcpkg-master\installed\x64-windows\include\pqxx\params.hxx(127,35): error C2589: '(': illegal token on right side of '::'
1>C:\vcpkg-master\installed\x64-windows\include\pqxx\params.hxx(194): message : see reference to class template instantiation 'pqxx::placeholders<COUNTER>' being compiled
1>C:\vcpkg-master\installed\x64-windows\include\pqxx\params.hxx(127,35): error C2059: syntax error: '('
1>Done building project "PGDriverLibrary.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by tt4g** [comment]
This is a problem with Windows specific `min` and `max` macros.
If you have `#include <windows.h>` somewhere in your project, the `min` and `max` macros will be added, and these two words will be interpreted as macros, causing many problems.

This problem can be avoided by devising the source code, but in pqxx versions less than 7.7.0, the `max` in line 120 of `include\pqxx\params.hxx` is interpreted as a macro.

Use pqxx version 7.7.0 or later, or make the same changes as commit caf13fe9601fccd4d27ddd151243ba26c8869c02.
As an alternative, you can define the `NOMINMAX` macro to avoid defining the `min` and `max` macros.

**Comment by vatnic** [comment]
I installed pqxx via vcpkg, there is the latest version 7.6. Please tell me when version 7.7 will be? Compiling the library on Win7 is hell! on Win 10, it is going to be more or less stable.

**Comment by tt4g** [comment]
vcpkg is not maintained by this project.
Open an issue of the upgrade request in the vcpkg repository (https://github.com/microsoft/vcpkg).

Would defining the `NOMINMAX` macro as an alternative workaround solve the problem?
