### ISSUE TITLE
Need help with conversion to user defined types

### ISSUE THREAD

**Issue by dpasha52** [jtv/libpqxx#534]
Hi,
I have implemented my own Datetime class,

///*********************************pseudocode******************************** //
class datetime{
private:
int year;
int month;
int sec;
.
.
.
public:
getDate()
.
.
.
overloaded the opreators
.
Datetime opreater=( Datetime){

}
//***************pseuocode ***************************/

}
Now the issue I am facing is this 
if I code this way , 

**Code** 
timestampValue = c.at(fieldNum).as(datetime());

I know that the <template> arg in as( ) function does not conform  to user defined datatypes, What do you suggest I do here ?
**Error**

/usr/include/libpqxx-6.4.5/include/pqxx/strconv.hxx: In instantiation of ‘void pqxx::from_string(const char*, T&) [with T = datetime]’:
/usr/include/libpqxx-6.4.5/include/pqxx/field.hxx:143:16: required from ‘typename std::enable_if<((! std::is_pointer<_Tp>::value) || std::is_same<T, const char*>::value), bool>::type pqxx::field::to(T&) const [with T = datetime; typename std::enable_if<((! std::is_pointer<_Tp>::value) || std::is_same<T, const char*>::value), bool>::type = bool]’
/usr/include/libpqxx-6.4.5/include/pqxx/field.hxx:161:16: required from ‘typename std::enable_if<((! std::is_pointer<_Tp>::value) || std::is_same<T, const char*>::value), bool>::type pqxx::field::to(T&, const T&) const [with T = datetime; typename std::enable_if<((! std::is_pointer<_Tp>::value) || std::is_same<T, const char*>::value), bool>::type = bool]’
/usr/include/libpqxx-6.4.5/include/pqxx/field.hxx:173:5: required from ‘T pqxx::field::as(const T&) const [with T = datetime]’
oldDBDataSourceCommon.cpp:2438:49: required from here
/usr/include/libpqxx-6.4.5/include/pqxx/strconv.hxx:281:32: error: incomplete type ‘pqxx::string_traits<datetime, void>’ used in nested name specifier
string_traits<T>::from_string(Str, Obj);
}

Thank you 
dpasha52

**Comment by jtv** [comment]
The answer I gave in #529 refers you to documentation and code.  I would strongly suggest working with libpqxx 7; I overhauled the string conversion system between versions 6 and 7.

**Comment by dpasha52** [comment]
Ok Thanks.
