### ISSUE TITLE
Suppression State Error (active)	E1919	parameter pack "Args" was referenced but not expanded

### ISSUE THREAD

**Issue by Mermen** [jtv/libpqxx#535]
Hello!
I am trying to connect a library for PostgreSQL.
I get an error  
![image](https://user-images.githubusercontent.com/35529065/152537640-412deacb-51b9-4925-9edb-1e60d8a84966.png)
![image](https://user-images.githubusercontent.com/35529065/152537657-c88c42de-be75-4246-9124-bcf1c4f5c7ed.png)
I've already read https://github.com/jtv/libpqxx/issues/456
But I still don't understand what eventually led to the solution of the problem
I've already connected
![image](https://user-images.githubusercontent.com/35529065/152537893-c3c3e406-f0d6-45d7-aedd-c12119840943.png)
![image](https://user-images.githubusercontent.com/35529065/152537926-fcacdfec-dc6c-470e-9d5d-415d06b1ee32.png)
![image](https://user-images.githubusercontent.com/35529065/152537946-255c52ac-4790-46a0-be8b-c099ad600189.png)
What haven't I done yet for a successful launch?

**Comment by jtv** [comment]
Could this be the same issue as #533?

It's possible that vcpkg has a libpqxx package that needs updating with the latest upstream changes.

**Comment by Mermen** [comment]
![image](https://user-images.githubusercontent.com/35529065/152596516-c48ea52d-bcfc-458b-b2ff-436afc5686b1.png)
it's updated, but error still actual

**Comment by jtv** [comment]
It's not clear to me what that means...  I'm not familiar with vcpkg, but the latest libpqxx release is 7.7.0.

**Comment by Mermen** [comment]
So, I have no idea now it work.
But I reinstall  libpqxx(7.7.0) by guige from http://en.wiki.imlint.org/Pqxx_tutorial
And what I have:
I still have error 
![image](https://user-images.githubusercontent.com/35529065/152608370-7f5c9407-5d43-4bb0-a199-3990e320de76.png)
BUT I connect libpqxx to another my progect (error also still here) but it can buld, compile, run and work with PostgreSQL

Conclusion: error still here, but my program work

If you have no ideas about this error, I\\You may close this issue.

**Comment by tt4g** [comment]
E1919 seems to be an IntelliSense error. If you are able to compile, then the compiler is able to expand the parameter pack.

Is the Visual Studio IDE up to date with the latest version?

**Comment by tt4g** [comment]
There is another report of incorrect errors reported by IntelliSense in August 2021.

https://github.com/jtv/libpqxx/issues/477#issuecomment-908986975

**Comment by jtv** [comment]
Oh, so it's an error in the IDE that doesn't actually affect the compiler?

**Comment by tt4g** [comment]
It seems to be reported from IntelliSense, so I don't think it affects the compilation.

**Comment by jtv** [comment]
This is one of the things I dislike about IDEs.  They hide integration complexity from us, so when things go wrong, the IDE has already obscured from us where the problem might be.  Really I think most IDEs are built for the wrong purpose: they help us _manage_ complexity.  Good software comes from _defeating_ complexity.

Anyway.  So far, all this sounds to me like this might be a bug in IntelliSense.  @Mermen I'd definitely try talking to whoever makes that — Microsoft I guess?

**Comment by tt4g** [comment]
Visual Studio issues are reported to the Developer community.

https://developercommunity.visualstudio.com/home

New reports can be created from Visual Studio (need to sign in).
https://developercommunity.visualstudio.com/report?space=8&entry=problem

Intellisense error E1919 seems to have been reported before: https://developercommunity.visualstudio.com/t/Intellisense-E1919-error-on-Boost-ASIO/1247549?space=8&q=E1919

**Comment by jtv** [comment]
Nothing more to be said here, I guess.  Let's hope Visual Studio fixes the problem soon.
