### ISSUE TITLE
Question on reconnecting

### ISSUE THREAD

**Issue by TheFern2** [jtv/libpqxx#537]
I read on the docs for activate function that pqxx::connection will attempt to reconnect or reactivate the connection.

What's a good way to test this, how to make the connection go to sleep? I tried to stop postgres service but that doesn't work.

**Comment by tt4g** [comment]
To make the server close the connection from pqxx, execute the following query.

```sql
SELECT pg_terminate_backend(pg_stat_activity.pid)
FROM pg_stat_activity
WHERE pg_stat_activity.pid = pg_backend_pid()
```

Never forget `WHERE pg_stat_activity.pid = pg_backend_pid()`. This condition allows only the current connection to be terminated.

**Comment by jtv** [comment]
Be aware though that that whole mechanism is gone in libpqxx 7.x!  The
responsibility for recovering from broken connections now lies with the
application.

**Comment by TheFern2** [comment]
I am currently running 6.4.5, do you have any suggestions on how to recover from broken connections? Should just discard old connection object and create a new one, is that the best way to go about it?

**Comment by jtv** [comment]
Yes, that's the right way.

**Comment by TheFern2** [comment]
Thanks!

**Comment by jtv** [comment]
Looks pretty good.  Of course in addition you should never ever continue using an existing transaction after its connection breaks.

And I suppose `is_connected()` could be `const`.

**Comment by TheFern2** [comment]
For whatever reason if I terminate open connections 

```
SELECT pg_terminate_backend(pg_stat_activity.pid)
FROM pg_stat_activity
WHERE pg_stat_activity.datname = 'timeseries1'
  AND pid <> pg_backend_pid();
 pg_terminate_backend
```

is_open still returns true

```
```

**Comment by jtv** [comment]
@TheFern2 you're using `pid <> pg_backend_pid()` where I suspect you meant to use `pid = pg_backend_pid()`.

**Comment by TheFern2** [comment]
The sql query above terminates all backend pid's except the one you're running the query from hence `< >`. It does terminate the connections because before running that query, my application works fine, but after I run it, I get the connection error, and `is_open` still returns `true` as seen above. Because `is_open` still `true`, I cannot reassign a new connection object. Not sure what else I could use besides is_open or if I should even be worried about this being an issue.

[query source](https://stackoverflow.com/questions/5408156/how-to-drop-a-postgresql-database-if-there-are-active-connections-to-it)

**Comment by jtv** [comment]
The underlying libpq object may need a bit of prodding before it "notices" that the connection is gone.

At any rate, I wouldn't use `is_open()` for much.  I'd just try to use the connection as normal, and handle the `pqxx::broken_connection` exception.

**Comment by TheFern2** [comment]
Understood, I don't know why I was over engineering this. I'll just reset the connection, when the `broken_connection` is catched. Thanks again.
