### ISSUE TITLE
connection constructor that takes an already connected PQconn

### ISSUE THREAD

**Issue by harmic** [jtv/libpqxx#538]
Hi,

We have been updating our application from 6.4.x to 7.6.0 and have struck a problem due to the changed APIs.

Our code base contains code written in a number of languages (C & Perl as well as C++), and to avoid needing multiple backends per client process, we have used a slightly unorthodox connection pooling approach. The process creates a single pooled libpq `PQconn`, and the different subsystems in the process are able to access this pooled connection, perform their queries / transaction, and then return it to the pool.

With libpqxx 6.4.x I was able to do this by writing my own classes that subclassed `connectionpolicy` and `connection_base`, with our `connectionpolicy` actually wrapping the existing connection rather than creating a new one.

This isn't possible using libpqxx 7.6.0 - `connection` does not provide any way to construct an instance that does not connect to the database, and also `m_conn` is private.

I was wondering if you would be amenable to a PR that added a constructor that took an existing `PQconn` instance (and for that matter if you thought it would be feasible to have one)?

Naturally using such a constructor requires the user to uphold certain invariants regarding the state of the `PQconn` - that it should be idle & not in a transaction for instance.

The other thing we would need would be a method to release the `PQconn` so it can be returned to our pool. This could look like the `close` method, but instead of calling `PQfinish` it would just return the `PQconn`.

What do you think - would you be likely to accept such a PR? Or do you have any alternative suggestions?

Thanks in advance
Cheers
Mike.

**Comment by jtv** [comment]
Ouch!  I never thought anyone would be doing that.

What I would _not_ be willing to entertain is a public conversion constructor for this job, like `explicit connection(PQconn *)`.  That would just invite more mixing of sovereignty over those `PQconn` objects.  If we're going to do this, it needs a clear corner carved out for it that normal users aren't going to stray into without a very clear idea of their needs.

But —just chewing this over for a bit, it's been a long day and I'd like to discuss it some more— we could perhaps have a "named constructor" like `static connection seize_pqconn(PQconn *)` and a member function with move semantics like `PQconn *release_pqconn() &&`.

**Comment by harmic** [comment]
Thanks for the super fast response.

Yes - this is definitely a corner case, resulting from a project that has been around for a long time and without the resources to completely rewrite - rather what has happened is that we've re-written performance sensitive functions in C++. Having said that it is probably not all that uncommon to have a code base that mixes C and C++ code.

Your suggestion is exactly what I had in mind.

**Comment by jtv** [comment]
It's just a little counterintuitive from my perspective, since I put so much effort into _hiding_ the C stuff!  I designed libpqxx so that you can use it without even including any libpq definitions at all into your translation unit.

When we pierce that abstraction layer like this, it does create room for "unintentional APIs" that may break applications as I change details of libpqxx's implementation in the future.  Those changes were pretty radical between 6.x and 7.x.

Anyway, first let me get some sleep.  I've got a fairly busy weekend coming up, so expect me to be slower to respond.  If you have any further ideas (such as on naming — “two things are hard”), please just post them here.

**Comment by harmic** [comment]
Re: naming, I like the rust approach to this - `from_xxx(...)` for constructors that take resources and wrap them, and `into_xxx` for methods that consume the object and give you the resource back.

For example [std::fs::File](https://doc.rust-lang.org/stable/std/fs/struct.File.html) has a constructor `from_raw_fd(fd: RawFd)` that takes an OS File descriptor and gives you back a `File` that wraps it. Similarly they have `into_raw_fd(self)` to consume it and give you back the resource.

Of course this is C++ and I'm not aware of any naming convention that applies.

Another approach might be for you to allow subclassing `connection` such that we could make a subclass that meets our need. I think if you provided a protected constructor that initialized an instance with `m_conn` as null, and also made `m_conn` protected, that could work. 

That way could mark this usage out as much more of a "corner case", because it would require subclassing to change the normal behaivour. The down side is the potential for limiting further changes down the track without breaking code for people that start to rely on being able to subclass `connection`.

**Comment by jtv** [comment]
Your pros and cons for the subclassing idea make sense to me — but alas the cons to me outweigh the pros.

My impression about the Rust naming conventions for the constructor is that they don't translate all that well to C++, in that the constructor's signature will already say just as clearly what the argument type is.  In C++, `connection(PQconn *)` would express the exact same information, and at least as concisely.

Moreover, I want the name to encapsulate not just the obvious _what-it-does,_ but the _what-it's-for._  This is not just a type conversion; it's something fairly radical that you may occasionally want to do.  In fact I'm sort of tempted to see if I can put it in the `pqxx::internal` namespace!  That would mean that it could easily change in the future, but it might tide you over to a point where you no longer need the mechanism.

**Comment by jtv** [comment]
@harmic could you give the branch in #540 a try, see if it does what you need?

**Comment by harmic** [comment]
Thanks @jtv much appreciated. I will let you know.

**Comment by harmic** [comment]
Thanks Jeroen.

We've tried it out, and although it solves our initial problem it has highlighted another one.

We had subclassed `connection` to add some logging in, so that every SQL statement that our application executes can be logged through our logging framework. We can't do that now, because the constructor you added is private.

Is there any other way for us to intercept the SQL being executed for logging purposes, so that we don't have to subclass it?

**Comment by jtv** [comment]
Subclassing the _transaction_ class might work.

**Comment by jtv** [comment]
@harmic I've merged the PR, so you can move ahead.  Any news on the logging issue?

**Comment by jtv** [comment]
@harmic I've merged the PR, so you can move ahead.  Any news on the logging issue?

**Comment by harmic** [comment]
Many thanks Jeroen. One of my colleagues is working on the logging. I will check with him and let you know.
