### ISSUE TITLE
remember the results parsed.

### ISSUE THREAD

**Issue by dpasha52** [jtv/libpqxx#542]
Is there an iterator that remembers the last record parsed in the result set pqxx::result. so that I can continue and do a getnextRecord() custom function that will retrieve the next record.

**Comment by jtv** [comment]
Not clear to me what you want, sorry.

**Comment by jtv** [comment]
Are you thinking of iterators?  If so, you can use `pqxx::result::begin()` and `pqxx::result::end()` as usual.  They return `pqxx::result::const_iterator`, which has an increment operator.
