### ISSUE TITLE
does libpqxx hooks thread of mingw64?

### ISSUE THREAD

**Issue by xkungfu** [jtv/libpqxx#543]
I use another libarary "dataframe". 
when use libpqxx and dataframe together.
the thread called by dataframe can't work.
error message is :

`mingw64-800r1_gcc931\include\c++\9.3.1\thread:282:26:`

```
In function 'bool std::operator==(std::thread::id, std::thread::id)':
 error: no match for 'operator==' (operand types are 'std::thread::native_handle_type' {aka 'ptw32_handle_t'} and 'std::thread::native_handle_type' {aka 'ptw32_handle_t'})
  282 |     return __x._M_thread == __y._M_thread;

```

**Comment by xkungfu** [comment]
below is the source code in thread of mingw64:

```
  inline bool
  operator==(thread::id __x, thread::id __y) noexcept
  {
    // pthread_equal is undefined if either thread ID is not valid, so we
    // can't safely use __gthread_equal on default-constructed values (nor
    // the non-zero value returned by this_thread::get_id() for
    // single-threaded programs using GNU libc). Assume EqualityComparable.
    return __x._M_thread == __y._M_thread;
  }

  inline bool
  operator!=(thread::id __x, thread::id __y) noexcept
  { return !(__x == __y); }

  inline bool
  operator<(thread::id __x, thread::id __y) noexcept
  {
    // Pthreads doesn't define any way to do this, so we just have to
    // assume native_handle_type is LessThanComparable.
    return __x._M_thread < __y._M_thread;
  }

  template<class _CharT, class _Traits>
    inline basic_ostream<_CharT, _Traits>&
    operator<<(basic_ostream<_CharT, _Traits>& __out, thread::id __id)
    {
      if (__id == thread::id())
	return __out << "thread::id of a non-executing thread";
      else
	return __out << __id._M_thread;
    }
```

does libqpxx hooks any of these three functions?

**Comment by tt4g** [comment]
Duplicate #424

**Comment by jtv** [comment]
No, libpqxx does not touch those functions.  Problems like this have come up before, and they seem to be a known bug in MinGW's threading support.

Current versions of libpqxx work around this problem, so consider upgrading.

**Comment by xkungfu** [comment]
I am now using 7.7.0 and encounter this problem. now I will try to rebuild to have a further test.
report later.
thanks.

**Comment by xkungfu** [comment]
```

# postgresql =========================================
list(APPEND CMAKE_PREFIX_PATH I:/CXXlibs/LIBPQXX/libpqxx-7.7.0-notchangemingwthread/build/)
find_package(PostgreSQL REQUIRED)
find_package(libpqxx REQUIRED)
include_directories(I:/CXXlibs/LIBPQXX/libpqxx-7.7.0-notchangemingwthread/build/include)
# ====================================================


# +++ postgresql ===========================================
target_link_libraries(${PROJECT_NAME} PRIVATE PostgreSQL::PostgreSQL)
target_link_libraries(${PROJECT_NAME} PRIVATE pqxx)
target_link_directories(${PROJECT_NAME} PRIVATE  "I:/CXXlibs/LIBPQXX/libpqxx-7.7.0-notchangemingwthread/build")
## Windows socket dependency
if(WIN32)
    target_link_libraries(${PROJECT_NAME} PRIVATE  ws2_32)
endif()
# ==========================================================
```

It seems this line make thread of mingw64 not work:

`target_link_libraries(${PROJECT_NAME} PRIVATE PostgreSQL::PostgreSQL)
`
error message:
 error: no match for 'operator==' (operand types are 'std::thread::native_handle_type' {aka 'ptw32_handle_t'} and 'std::thread::native_handle_type' {aka 'ptw32_handle_t'})
  282 |     return __x._M_thread == __y._M_thread;
      |            ~~~~~~~~~~~~~ ^~ ~~~~~~~~~~~~~


what can I do now?

**Comment by tt4g** [comment]
> `target_link_libraries(${PROJECT_NAME} PRIVATE PostgreSQL::PostgreSQL)`

Very strange. libpq is a C library, so I don't think it include `<thread>` header.

`target_link_libraries(${PROJECT_NAME} PRIVATE pqxx)` will automatically add the include paths and link paths of libpq that CMake linked to when it built libpqxx to the compile options.

If libpqxx is installed by CMake, then `target_link_libraries(${PROJECT_NAME} PRIVATE PostgreSQL::PostgreSQL)` is not needed and should be removed.

**Comment by xkungfu** [comment]
thanks! let me have a try.

**Comment by xkungfu** [comment]
use find_library(PQ_LIB pq) resolved the problem.

thank you very much!

**Comment by tt4g** [comment]
There are several possible causes.

1. PostgreSQL library that you libpqxx linked to has been uninstalled from your machine.
	You have another version PostgreSQL installed, but it is not compatible.
    Rebuild libpqxx to use PostgreSQL currently installed on the machine.

2. Other libraries are linked to PostgreSQL that are incompatible with libpqxx.
    You must build all libraries with a configuration that links them to the same version of the PostgreSQL library.

3. libpqxx is linked and built with PostgreSQL for MinGW. As far as the path is concerned, PostgreSQL for Windows is used. Please rebuild libpqxx.

**Comment by tt4g** [comment]
Ah, the posts have crossed paths. Please ignore the previous comment.

**Comment by xkungfu** [comment]
I got you notes and will take attention to other works about them.
and about this bug, can I say the find_package calls a dynamic library and the find_library calls a static library?

**Comment by tt4g** [comment]
It is possible, but we do not encounter such problems unless we change the CMake settings regarding PostgreSQL.

**Comment by xkungfu** [comment]
thank you. too difficult to me, spent two week for this...

**Comment by jtv** [comment]
So glad once again that you're here to help with these things @tt4g!

Technically the application only needs to link with libpq.  It doesn't need
the libpq headers.  But I don't know whether that's helpful in the CMake
context.
