### ISSUE TITLE
Issue while using notification receiver with postgresql

### ISSUE THREAD

**Issue by dineshR478** [jtv/libpqxx#544]
Hi @jtv ,

I am trying to use multiple notification receivers each with different channel name on one connection. While doing so, i am facing an issue that first notification alone is received properly and rest of them are not reaching the operator() overloaded function of the notification_receiver class. Below is the class definition. I m using vector to store the objects created for each notification and using multiple threads to wait for the notification received on each channel. Please provide some insights.

```cxx
class TestReceiver: public pqxx::notification_receiver
  {
      public:     
        pqxx::connection *pconn;
        std::string notificationName;
        std::string payloadString;
        bool m_done;
        explicit TestReceiver(pqxx::connection &conn, std::string const &Name, std::string const &payload) :
          pqxx::notification_receiver(conn, Name), pconn(&conn), notificationName(Name), payloadString(payload), m_done(false)
       {
       }
        void operator()(std::string const &payload, int be_pid) override
        {
          m_done = true;
          std::cout << "Received notification: " << channel() << "with payload:" << payload<< " from pid=" << be_pid<< std::endl;         
        }
        bool done() const {
          return m_done;
        }
        void threadToRead()
        {
          while(true){
            std::cout<<"Waiting for notification..."<<std::endl;
            pconn->await_notification();
          }
        }
        void read_notification()
        {        
          std::thread readerThread(&TestReceiver::threadToRead, this);
          readerThread.detach();
        }
    }; 
```

**Comment by jtv** [comment]
(@dineshR478 I edited your comment to mark the code as a C++ code block, to make it easier to read.  Otherwise, some special characters may get interpreted as Markdown formatting.)

**Comment by jtv** [comment]
I'm not seeing anything wrong with that...  Any chance that your main thread happens to exit before the reader thread can process the second notification?

What happens if you run `threadToRead()` directly in your main thread instead?

**Comment by dineshR478** [comment]
@jtv I found that since i use as many threads as for every notification, threads are not under mutex which caused the issue. Now changed the design in such a way that only one thread to handle all the notification receivers.

**Comment by jtv** [comment]
That would explain.  You can't do anything non-`const` on a connection concurrently with another access.

**Comment by dineshR478** [comment]
got it @jtv . Thanks
