### ISSUE TITLE
impossible to connect to database on windows

### ISSUE THREAD

**Issue by Raftapss** [jtv/libpqxx#549]
Hello,
I managed to compile and I followed this tutorial http://en.wiki.imlint.org/Pqxx_tutorial arrive when testing the c++ code visual studio tells me that I am missing dlls because they are not found.
LIBPQ.dll , libintl-9.dll then another libwinpthread-1.dll. I put these dlls in system32 and syswow64. I have no more message but on the other hand impossible to start the program.
`Thread 0x49f0 terminated with code -1073741701 (0xc000007b).
Thread 0x6c0 terminated with code -1073741701 (0xc000007b).
Program '[4856] testlibpqxx.exe' exited with code -1073741701 (0xc000007b).`
Have an idea?

**Comment by tt4g** [comment]
Exit code `0xc000007b` is almost always due to library compatibility or other problems.
Please review your project settings.

https://stackoverflow.com/questions/28299246/0xc000007b-error

**Comment by jtv** [comment]
Library incompatibility problems usually manifest themselves as link
errors.  Since that didn't happen here...  is it possible that a .lib file
didn't match its corresponding .dll?

Think different library version, or one compiled as Debug and the other
Release, that kind of thing.

**Comment by jtv** [comment]
@Raftapss have you been able to figure out what went wrong?

**Comment by Raftapss** [comment]
I do it that in this week-end. But for the moment i dont find the issue

Le sam. 26 mars 2022 à 08:05, Jeroen Vermeulen ***@***.***> a
écrit :

**Comment by jtv** [comment]
I'd definitely search whether there is perhaps more than one .lib or .dll file.  Even if there is only one of each, I'd check that they were created around the same time.

Also, it might be worth linking to libpqxx statically rather than as a DLL.

**Comment by Raftapss** [comment]
This is what I do.
I clone the git with the command "git clone https://github.com/jtv/libpqxx.git"
Then I run CMake 2.23.0-rc4. I create 1 directory build in the folder where I cloned the git. I press Configure the I have several errors.

PostgresSQl_INCLUDE_DIR-NOTFOUND and PostgresSQl_TYPE_INCLUDE_DIR-NOTFOUND . I provide him with the postgres directory with the includes "C:/Program Files/PostgreSQL/14/include" in both.
By checking on Advanced the postgres libs are not given either (PostgreSQL_LIBRARY_DEBUG and RELEASE
So I provide "C:\Program Files\PostgreSQL\14\lib\postgres.lib" and Repress Configure then Generate
Once the compilation is done, I go to my build directory where a libpqxx.sln project has been generated.
So I run this in visual studio I make sure I'm using a compiler with c++20 x64 release on all solutions. I build ALL_BUILD and then I build INSTALL. I do a quick code I run and
libpq.dll missing exactly the same as last time, any idea?

**Comment by Raftapss** [comment]
however when I link C:\Program Files\PostgreSQL\14\lib I find the libpq.dll in the directory

**Comment by tt4g** [comment]
Check the DLLs on which the executable depends.
You can do it using [lucasg/Dependencies](https://github.com/lucasg/Dependencies).

And make sure that all DLLs are existing in the directory with the environment variable `PATH`.
DLLs that do not have a directory in `PATH` cannot be found at runtime, so please add the directory to `PATH`.

**Comment by Raftapss** [comment]
When you say "PATH" are you talking about environment variables or linker paths?

**Comment by Raftapss** [comment]
Im a Belgian. 
The prints screen is on french
![libpqxx](https://user-images.githubusercontent.com/47546269/161441419-afcef995-194a-4060-b8f4-1c8ca05b2af2.png)
.
![variable d'environnement](https://user-images.githubusercontent.com/47546269/161441479-266920f7-3174-44b0-ae41-ec4df289d0b4.png)

![compilation](https://user-images.githubusercontent.com/47546269/161441552-c1e84882-4bac-4c65-95d8-acdfc3eb4747.png)

**Comment by jtv** [comment]
My French is not great but good enough to follow along...  It's the Windows debugging that's hard for me.

Are you compiling to 32-bit code, or to 64-bit code?  And are you compiling in Release mode or in Debug mode?  It's important that these choices be _completely consistent_ between your libpqxx build, your libpq.lib, and your libpq.dll, as well as the other libraries you need.

If you have a library that's the wrong kind and you copied it into system32 and/or syswow64, that could make things worse, because the loader may find the wrong library before it even looks in the places where the right library should be.

**Comment by tt4g** [comment]
Machine translation of "Impossible d executer le code, car LIBPQ.dll est introuvable." translates to "Impossible to execute the code, because LIBPQ.dll is not found."
So you should be able to run the code by adding `C:\Program Files\PostgreSQL\14\lib` to the environment variable `PATH`.

**Comment by Raftapss** [comment]
Yes, i anderstand that like you. Then i add in environnement path. You can
see it in the second screenshot. POSTGRES14_LIB_DIR. But doesn't work. I
add to linker this path in the first screenshot.
Doesn't work 😭

**Comment by tt4g** [comment]
The path that Windows searches for libraries that depend on the executable file is not affected by the linker path.
Unless you add the same path as `POSTGRES14_LIB_DIR` to `PATH` environment variable, the library will not be found

**Comment by jtv** [comment]
Also, bear in mind that the DLL must be in your path at the time you _run_ the executable.  Not just at the time you _build_ the executable.

**Comment by Raftapss** [comment]
It's working :)
Need to add postgres\bin and postgre\lib to the variable path.
Now its working thank you very much :)

**Comment by jtv** [comment]
Phew!  Glad that's solved.

**Comment by Raftapss** [comment]
Oh, I see.
I need to add at the path environnement variable. And not add à New
environnement variable. I Will try this when i come back to the home.
I have an another question, can i add à name of environnement variable to
path variable or pathneed path

**Comment by tt4g** [comment]
@Raftapss On Windows, environment variable names are expanded to values by enclosing them in `%`.
And, in the `PATH` environment variable, you can enumerate paths separated by `;`.

So, by adding `;%POSTGRES14_LIB_DIR%` to the end of the `PATH` environment variable, `POSTGRES14_LIB_DIR` becomes part of the `PATH` environment variable.
