### ISSUE TITLE
Shared library error when executing a project that uses libpqxx static library

### ISSUE THREAD

**Issue by heiwiper** [jtv/libpqxx#553]
I compiled the library using the following commands on a linux system (Debian) :
```shell
git checkout tags/7.7.2
mkdir build
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -G Ninja --configure .
ninja -C build
sudo cmake --install build
```
and then I added it to my CMakeLists.txt :
```cmake
cmake_minimum_required(VERSION 3.10 FATAL_ERROR)

project (example)

# specify the C++ standard
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)

add_executable(example
  ${PROJECT_SOURCE_DIR}/main.cpp)

target_link_libraries(acquisition-gateway
  -lpqxx
  -lpq)
```

when launching the executable generated by my project build I get the following error :
```
./example: error while loading shared libraries: libpqxx-7.7.so: cannot open shared object file: No such file or directory
```
What am I doing wrong here ?

**Comment by jtv** [comment]
I'm no CMake expert (I use the `configure` script in most of my own builds) — it does sound as if CMake decided to build a shared library after all.  Is `OFF` an accepted value — should it be `off` perhaps?  That's what the documentation says, and I don't know whether CMake is case-sensitive on this point.

**Comment by heiwiper** [comment]
I did try different case type and also checked the generated files. It was generating the appropriate library files (`.so` for shared library and `.a` for static library). But the application built against both static and shared library throw the same error.
I will try to use `configure` tomorrow and report back.

I thought there might be something wrong with the way I make use of the library in my `CMakeLists.txt` file.

**Comment by tt4g** [comment]
If you are using libraries built with CMake, you should use `find_package()`.
This will add the CMake target to your project (`find_package(pqxx)` will add the CMake target `pqxx` to your project).

See: https://cmake.org/cmake/help/v3.23/command/find_package.html

Example:

```diff
 set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_CXX_STANDARD_REQUIRED True)

 add_executable(example
   ${PROJECT_SOURCE_DIR}/main.cpp)

+ find_package(pqxx)
+
 target_link_libraries(acquisition-gateway
-  -lpqxx
-  -lpq)
+  PRIVATE
+    pqxx)
```

**Comment by heiwiper** [comment]
@tt4g thank you, that seemed to have fixed my issue, although there are some slight changes 
```diff
 set(CMAKE_CXX_STANDARD 17)
 set(CMAKE_CXX_STANDARD_REQUIRED True)

 add_executable(example
   ${PROJECT_SOURCE_DIR}/main.cpp)

- find_package(pqxx)
+ find_package(libpqxx)

 target_link_libraries(acquisition-gateway
  PRIVATE
-    pqxx)
+    pqxx
+    pq)
```
