### ISSUE TITLE
Need help resolving connection issues urgently(sorry). unable to reopen thus pasted the previous one for reference 

### ISSUE THREAD

**Issue by dpasha52** [jtv/libpqxx#554]
[dpasha52](https://github.com/dpasha52) commented [16 days ago](https://github.com/jtv/libpqxx/issues/546#issue-1166929815)[](https://github.com/tt4g)
Hi,
I am getting the below mentioned error ,
My code does the following
while (iterate over rs ){
1)makes a connection
2)sets a parameterized query
3) updates some table
4) disconnects
}

FATAL: remaining connection slots are reserved for non-replication superuser connections

Note : I can't make the connection outside the while loop as it breaks existing code structure.
Also please point me to some good articles/links that could help me resolve this.

Any work around would be great help.
Thank you
dpasha52

@[tt4g](https://github.com/tt4g)
 
Contributor
tt4g commented [16 days ago](https://github.com/jtv/libpqxx/issues/546#issuecomment-1065635752)
The cause is that you are creating more connections than the maximum number of database connections.
Please increase the max_connections parameter in postgresql.conf.

Note the number of connections specified in superuser_reserved_connections is reserved for the super user (postgres).
The maximum number of connections that can be used by non-superusers is limited to max_connections - superuser_reserved_connections.

See: https://www.postgresql.org/docs/12/runtime-config-connection.html[](https://github.com/jtv)

@[jtv](https://github.com/jtv)
 
Owner
 jtv commented [15 days ago](https://github.com/jtv/libpqxx/issues/546#issuecomment-1065847436)
Yup, you're simply making too many connections.

But why are you making a new connection for every iteration of your loop?
It usually makes sense to keep the same connection object and use it for
multiple commands.  Your *transaction* object should generally be
short-lived, but the *connection* can live for a long time.

If the loop runs for so long that dropped connections become a problem, you
can build in an exception handler for pqxx::broken_connection that replaces
your connection with a new one and re-does the last iteration.

Or, as a simple compromise, you could turn your loop into an outer loop
that creates a new connection every time, but inside that have a nested
inner loop that does a number of iterations of the actual work, using a
single connection.
[…](https://github.com/jtv/libpqxx/issues/546#)[](https://github.com/leonardsangoroh)
@[leonardsangoroh](https://github.com/leonardsangoroh)
 
leonardsangoroh commented [15 days ago](https://github.com/jtv/libpqxx/issues/546#issuecomment-1065885629)[](https://github.com/jtv)
I'm not sure whether the connection instance should be in a loop

@[jtv](https://github.com/jtv)
 
Owner
 jtv commented [15 days ago](https://github.com/jtv/libpqxx/issues/546#issuecomment-1065888469)
Yeah, it sounds a bit unusual, and inefficient.  Establishing a connection
can be quite slow compared to the cost of executing a simple query.
[…](https://github.com/jtv/libpqxx/issues/546#)[](https://github.com/dpasha52)
@[dpasha52](https://github.com/dpasha52)
 
Author
dpasha52 commented [12 days ago](https://github.com/jtv/libpqxx/issues/546#issuecomment-1068078166)[](https://github.com/jtv)
Thank you for the suggestions. will look into it.and find a way to fix it.
Thank you
Dpasha52.

@[jtv](https://github.com/jtv)
 
Owner
jtv commented [4 days ago](https://github.com/jtv/libpqxx/issues/546#issuecomment-1076937204)[](https://github.com/jtv)
Probably time to close this issue. Feel free to file a new one if you run into problems again.

@[jtv](https://github.com/jtv) jtv closed this [4 days ago](https://github.com/jtv/libpqxx/issues/546#event-6295603559)[](https://github.com/dpasha52)
@[dpasha52](https://github.com/dpasha52)
 
Author
dpasha52 commented [17 minutes ago](https://github.com/jtv/libpqxx/issues/546#issuecomment-1079958402) • 
As a work around to avoid changes to existent code I am only creating connection once and making a static connection object that can be used by other objects.

example
class abc {
static pqxx::connection * c=NULL;
}
abc::make_conne(){
NOTE://initialize it only once done defensive prog to assure the same.
if ( is connected) {
string conn1;
new pqxx::connection(conn1);
}

}

somefunction () {
ABC obj ;
obj.makeconnection();
obj.exec_params()

}

Now I am getting this error on trying to execute query using the static connection object created only once by other dependent code
Could not obtain client encoding : not connected.

Excuse the crude pseudo code written
Any advice/links on this would be would be great help.
Thank you
dpasha52

I am unable to reopen the issue, posting on the same for continuity.

**Comment by jtv** [comment]
I reopened the original ticket before I saw that this was basically a copy.  I'll close this one then.
