### ISSUE TITLE
Issue on using notification receivers

### ISSUE THREAD

**Issue by dineshR478** [jtv/libpqxx#555]
Hi @jtv ,

I am facing an issue while using notification receivers. I have two different binaries(named bin1 & bin2) and both binaries will establish connection to postgres DB and create multiple notification receivers for multiple events.  Here, bin1 has created around 10 notification receivers on its connection to Postgres and everything is working fine. But bin2 has created 1 notification receiver on its connection to Postgres which is leading hung issue. could you please help on this?

here is snippet of the code for interacting to Postgres:

```
void DBConnection::exec_trans(std::string command, bool commit)
{
  if(status == ConnectionStatus::CONNECTED)
  {
    try {
      pqxx::work txn{*_conn};
      txn.exec(command);
      if(commit)
        txn.commit();
      std::cout<<"DBConnection::exec_trans()"<<"Execute command "<< command << " is successfully executed"<<std::endl;
    } catch (const std::exception &e) {
      X_ERROR_LOG("Execute command(%s) is failed with reason:%s", command.c_str(), e.what());
      std::cout<<"DBConnection::exec_trans()"<<"Execute command "<< command << " is failed with reason:"<<e.what()<<std::endl;
    }
  }
}
void DBConnection::RegisterNotificationProcessorAPI(std::string channel, callback_function pFunc)
{
  std::cout<<"Registered Notification Handler for channel "<<channel<< std::endl;
  X_ERROR_LOG("%s: Registered Notification Handler for channel %s", __FUNCTION__, channel.c_str());
  notifyCallbackTable[channel] = pFunc;
}
TestReceiver* DBConnection::createNotificationReceiver(std::string notificationName)
{
  std::cout<<__FUNCTION__ << " called for channel " <<notificationName<<std::endl;
  if(status == ConnectionStatus::CONNECTED)
  {
    TestReceiver *recv = new TestReceiver(*_conn, notificationName, notificationName);
    return recv;
  }
  return nullptr;
}
void DBConnection::AsyncReadNotification()
{
  std::cout<<__FUNCTION__<<" called"<<std::endl;
  X_ERROR_LOG("%s called", __FUNCTION__);
  if(status == ConnectionStatus::CONNECTED)
  {
    std::cout<<__FUNCTION__<<" :: status is Connected"<<std::endl;
    auto& it = NotifVector[0];
    {
      reinterpret_cast<TestReceiver*>(it)->read_notification();
    }
  }
}
class TestReceiver: public pqxx::notification_receiver
{
  public:
    pqxx::connection *pconn;
    std::string notificationName;
    std::string payloadString;
    bool m_done;
    explicit TestReceiver(pqxx::connection &conn, std::string const &Name, std::string const &payload) :
      pqxx::notification_receiver(conn, Name), pconn(&conn), notificationName(Name), payloadString(payload), m_done(false)
   {}
    void operator()(std::string const &payload, int be_pid) override
    {
      m_done = true;
      std::cout << "Received notification: " << channel() << "with payload:" << payload<< " from pid=" << be_pid<< std::endl;
      notifyCallbackTable[channel()](payload);
    }
    bool done() const {
      return m_done;
    }
    void threadToRead()
    {
      std::cout<<__FUNCTION__ <<" called" << std::endl;
      while(true){
        std::cout<<"Waiting for notification..."<<std::endl;
        pconn->await_notification();
      }
    }
    void read_notification()
    {
      std::cout<<__FUNCTION__<<" called"<<std::endl;
      std::thread readerThread(&TestReceiver::threadToRead, this);
      readerThread.detach();
    }
};```

**Comment by KayEss** [comment]
You need to use triple backticks on the lines above and below your code to make it readable:

\`\`\`cpp
your code
\`\`\`

**Comment by dineshR478** [comment]
Thanks @KayEss

**Comment by jtv** [comment]
This is a lot of code to understand and debug.  At the same time, it's not enough to see what's going on.  For all I know the problem could be a simple typo in a notification name, or something that you're doing with the connection in a different thread.

I would recommend _simplifying everything you can_ to get the minimal real example of the problem.  Chances are that you'll figure out what's going wrong along the way.

My suggestions:
* Create a self-contained example of the problem.  Ideally, a simple program you can compile and run.
* Describe inline, in concise comments, the reasoning behind each part of the code, as well as the expectation that is not working out.  Try to anticipate the reader's questions.
* Leave out _anything_ that's not needed to reproduce the problem.
* Keep code outside of classes as much as you can.  We want a simple control flow that shows us what's going wrong.
* Find concise alternatives to long names like `RegisterNotificationProcessorAPI`.  People lose track when they have too much to read and remember.
* The notification payload string comes in with the notification.  Why do you pass one to your receiver constructor?

**Comment by dineshR478** [comment]
@jtv ,

Below is the example how I am creating notification receiver object and started thread to wait for notification and handling.
```
void createRuleForGrpcClientUpdate(DBConnection::Ptr ptr)
{
  std::string sql = "CREATE OR REPLACE FUNCTION mm_config.notify_grpc_client_update() RETURNS TRIGGER AS $$ \
                     DECLARE \
                     row RECORD;output TEXT; \
                     BEGIN \
                     IF (TG_OP = 'DELETE') THEN \
                       row = OLD; \
                     ELSE \
                       row = NEW; \
                     END IF; \
                     output = TG_OP; \
                     PERFORM pg_notify('update_grpc_client', output); RETURN NULL; END; $$ LANGUAGE plpgsql;";
  ptr->exec_trans(sql, true);
  sql = "CREATE OR REPLACE TRIGGER trigger_grpc_client_update AFTER INSERT OR UPDATE OR DELETE ON mm_config.grpc_client FOR EACH ROW EXECUTE PROCEDURE mm_config.notify_grpc_client_
update();";
  ptr->exec_trans(sql, true);
  ptr->NotifVector.emplace_back(ptr->createNotificationReceiver("update_grpc_client"));
  auto& it = ptr->NotifVector.back();
  ptr->RegisterNotificationProcessorAPI(reinterpret_cast<TestReceiver*>(it)->notificationName,
      &call_updateGrpcClient);
}

dbConnObj->AsyncReadNotification();
```

**Comment by dineshR478** [comment]
I think calling pconn->await_notification(); inside threadToRead() and calling AsyncReadNotification() twice makes the problem.

**Comment by dineshR478** [comment]
Hi @jtv ,

I think i have found the issue. I am using pqxx::transaction with the connection object which is been called with await_notification().

Is this an issue?

**Comment by jtv** [comment]
I'm not completely sure I understand what you're saying.  But if I do, then
yes, that sounds like a problem.

The way I read what you're saying, you've got one thread waiting for a
notification on this connection while another thread is doing other work on
that same connection.  That would probably confuse the connection object's
state.

**Comment by dineshR478** [comment]
Yes.

**Comment by dineshR478** [comment]
I have fixed the issue by creating one more connection object and separate the transaction from the main connection object.
