### ISSUE TITLE
[Wiki] Possible wrong example in Statement Parameters section in documentation

### ISSUE THREAD

**Issue by heiwiper** [jtv/libpqxx#557]
When trying to generate dynamic statement parameters using `pqxx::placeholders` class, [the documentation](https://libpqxx.readthedocs.io/en/stable/a01434.html#Generating%20placeholders) suggests starting a new parameter placeholder using `next()` function and then get the placeholder's string using `get()`. Calling these functions in this order generates the second placeholder instead of the first which throws an error later on when executing the SQL statement.

The correct usage would be to call `get()` and then `next()`.

**Comment by jtv** [comment]
You're right, thanks for pointing that out.  Perhaps I should just scrap the `placeholders` class altogether.  It probably complicates more than it simplifies, and there's always the risk of undefined behaviour if there's no sequence point between invocations.

**Comment by heiwiper** [comment]
I think it's quite helpful at least for my case, I am currently writing a code that converts a query in a specific protocol into SQL query in which the number of arguments changes, so using placeholder's class the way it's suggested in the website made it much easier for me since I don't know how many attributes the query contains.

**Comment by jtv** [comment]
Ah OK, if it's actually useful to people I guess that changes things.  :-)  Just fixed the example.  Thanks again.
