### ISSUE TITLE
loop include problem

### ISSUE THREAD

**Issue by walkthetalk** [jtv/libpqxx#56]
if we include <pqxx/row>, we will get compile error.

row ->row.hxx -> field -> field.hxx ->result -> result.hxx -> result_iterator.hxx -> row

**Comment by jtv** [comment]
You're right.  That's annoying.  I'll need to look into this.

For now, as a workaround, just include pqxx/result instead.  It will include pqxx/row for you.

**Comment by jtv** [comment]
I still see no good way out.  The "row" and "result" headers always need to be included together.

So maybe "row" should just include "result."

**Comment by jtv** [comment]
As happens so often, a few helpful words from Kirit Sælensminde put me on the right track.  The row header can now be included independently.

**Comment by KayEss** [comment]
:)
