### ISSUE TITLE
Question on libpqxx float to string conversion when bulk importing

### ISSUE THREAD

**Issue by ckennerknecht** [jtv/libpqxx#566]
Hii,

I am a student and have to export GBs of historical data to PostgreSQL.
Could you explain how libpqxx handles c++ `float` values that explains the following behavior:

First, i set up the table: 
```Cpp
work workingContext(*dbConnection);
std::string createMVDataTableCmd =
         "CREATE UNLOGGED TABLE IF NOT EXISTS my_data ("
         "seconds INT8,"
         "id INT4,"
         "value REAL);";
workingContext.exec(createMVDataTableCmd); 
workingContext.commit();
```

Then i create a `stream_to` object 
```Cpp
auto tableInserter = stream_to::table(workingContext, { "my_data" });
```
and iterate over all my elements. For every element i write the data using the `write _values()` function:
```Cpp
tableInserter->write_values(
         time.getSec(),
         element->getId(),
         element->getValue());
```
Running the above code with a small subset of the data:
> Inserted 6691699 rows into my_data in time: 54.859 seconds

Now when i manually convert the float value with `std::to_string` it takes half the time:
```Cpp
 tableInserter->write_values(
         time.getSec(),
         element->getId(),
         std::to_string(element->getValue()));
```
> Inserted 6691699 rows into my_data in time: 27.812 seconds

'std::to_string' defaults to [6 decimal digits](https://www.cplusplus.com/reference/string/to_string/) for float values.
This is enough precision for my usecase.
So now I ask myself the question what libpqxx is doing and if this justifies double the string-conversion/import time?
I'm a relatively new to C++, so please try not to go too deep into libpqxx implementation details. 

Thank you for your help! 

I am using libpqxx version 7.7.2 compiled with Clang on Windows.

**Comment by jtv** [comment]
Oops, I thought I replied to this in the morning but it seems not to have gotten through somehow.

My best guess at the moment is that your loop spends half or more of its time on that conversion from float to string, and the rounding saves an enormous amount of time.

It could be worth checking whether your libpqxx build found a working floating-point version of std::to_chars, because the workaround

**Comment by ckennerknecht** [comment]
Thank you for your useful tipps!

Do you mean:
```Cpp
/* Define if <charconv> supports floating-point conversion. */
/* #undef PQXX_HAVE_CHARCONV_FLOAT */
```
Otherwise, there is also no `PQXX_HAVE_TO_CHARS_FLOAT` defined in `config-public-compiler.h` as you have guessed.
I will have to try out a different compiler then (Clang version used is 13.0.1 btw.).

Thanks again, I think you can close the issue then.

**Comment by jtv** [comment]
Absolutely go with a recent compiler if you care about performance.  The newer, the better.  You'll probably want to rebuild liboqxx and any other C++ libraries you use.

At some point the performance of client code should cease to matter, and the cost of working with the database will become the dominant use of your code's run time.

**Comment by jtv** [comment]
(And yes, `PQXX_HAVE_CHARCONV_FLOAT` must be what I meant.  It's great to be able to do this on my mobile phone, but looking these things up isn't quite as easy.)

**Comment by jtv** [comment]
Interesting!  I'll assume that you're using a recent 7.x libpqxx version.

The explanation may simply be that your loop spends most of its time
converting those floats to strings.  Rounding to a fixed maximum of 6
digits makes that job much easier, whereas libpqxx tries to preserve the
full original precision.  Rounding is a nasty business, especially if it
happens in multiple steps.

There may be another factor though.  If your compiler does not support
std::to_chars() for floating-point types, libpqxx will use a slow and
horrible stream-based alternative for rendering your float values as
strings.  So have a look at your include/pqxx/config-public-compiler.h (in
your build directory).  Off the top of my head, you're looking for whether
the header defines PQXX_HAVE_TO_CHARS_FLOAT.  If not, then upgrading to a
newer compiler may help, or switching between e.g. gcc and clang.

By the way, there is another nasty caveat with std::to_string() besides the
lower precision: it's locale-sensitive!  So for instance the number 1234.5
may come out as 1,234.5.  Or on a system set to French, 1.234,5.  So you'd
want to set the C locale when running this.
