### ISSUE TITLE
Its possible to avoid terminate calls?

### ISSUE THREAD

**Issue by nonunknown** [jtv/libpqxx#567]
I'm using libpqxx with Godot engine, but everytime an error occurs, it closes the game!

```
terminate called after throwing an instance of 'pqxx::broken_connection'
```

how this can be avoided?

**Comment by jtv** [comment]
That means that the connection to the database was lost.  Could be a
network problem, or perhaps something else on the server side restarted the
database.

I don't know the application but it should catch pqxx::broken_connection
exceptions, and either report it properly or start a new connection.
