### ISSUE TITLE
Error in set_local command when installing via VS 2019

### ISSUE THREAD

**Issue by FelipeRamones** [jtv/libpqxx#569]
Hi guys, i'm following this tutorial to [build and install libpqxx on windows](https://youtu.be/qDiC1Wja6Og?t=194) and in the minute 9:15 of the video when i try to compile the "INSTALL" project it throws me the following error:

![image](https://user-images.githubusercontent.com/32317045/166982943-8853340e-9787-4e01-a9a3-1f6c8fd5e2bc.png)

i'm using the master branch version of libpqxx and C++ 17, tried cleaning and reinstalling, rebuilding with CMake and even recloning the whole repo but nothing seems to work, even previous or more recent versions of C++ still throws that error. I'm using a x64 release build.

**Comment by jtv** [comment]
A bit out of my comfort zone.  But it seems really strange that this _only_ reports that something in these commands returned an error.  It's just not very helpful.
Have you tried running that cmake command line by hand, in case it prints more helpful output?
Also, consider switching your environment to English.  It makes international debugging easier, and also, makes it easier to search for similar errors that others on the internet have run into.

**Comment by tt4g** [comment]
In most cases, it seems to be due to the fact that the installation of built artifacts fails due to the permissions on `CMAKE_INSTALL_PREFIX` directory.

See: https://stackoverflow.com/questions/31457306/visual-studio-msb3073-error-exited-with-code-1

**Comment by FelipeRamones** [comment]
Thanks guys ^^ sorry for the VS 2019 in portuguese, thanks to the link i could realize that i wasn't trying it in admin mode, just rebuilt it launching CMake and VS 2019 both in admin mode and it worked :)
