### ISSUE TITLE
Configuration fails from 7.7.1 onwards

### ISSUE THREAD

**Issue by m-aXimilian** [jtv/libpqxx#570]
I get the following message when I try to configure versions more recent than 7.7.0:
`checking for sufficient C++ language/library level... no
configure: error: This libpqxx version needs at least C++17.
`
This error is thrown from trying to compile the `conftest.$ac_ext` (in the configure file). There are in fact **no "conftest" files** present in **the repo**. Due to this (at least as I understand it) this compile test must fail inevitably. However, there are severeal "conftest*"-files in the **.gitignore**.
Could it be that for the test to succeed those files should go into the repo?

**Comment by jtv** [comment]
In the latest versions, the `configure` script no longer tries to tell your compiler which C++ version you want.  It was just too messy, and autoconf support wasn't keeping up with new C++ versions.

This means you either need a compiler that compiles C++17 or newer out of the box, or pass options to tell the compiler what C++ version you want.

So when you run `configure`, try adding to the command line e.g. `CXXFLAGS=-std=c++17` to make libpqxx build as C++17.  Or replace the 17 with 20 if you want C++20.  And of course you can combine this with your other compiler options.

For example: `./configure CXXFLAGS="-std=c++20 -O3"`
