### ISSUE TITLE
Failed to build 6.4 of libpqxx for mingw64 on win64 platform

### ISSUE THREAD

**Issue by iihero** [jtv/libpqxx#573]
I just tried several version of mingw64: 
x86_64-8.1.0-release-win32-seh-rt_v6-rev0.7z
x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
x86_64-8.1.0-release-posix-sjlj-rt_v6-rev0.7z
x86_64-8.1.0-release-win32-sjlj-rt_v6-rev0.7z

None of them can succeed.  they are all c++11 support.
There are errors like:  `std::thread::native_handle_type` (aka `ptw32_handle_t`) to `std::thread::id`
And also some errors like: 
```
C:/tools/msys64/mingw64/include/c++/11.3.0/thread:70:24: note:   no known conversion for argument 1 from 'std::thread::native_handle_type' to 'std::thread::id'
   70 |   operator<(thread::id __x, thread::id __y) noexcept
      |             ~~~~~~~~~~~^~~
make[1]: *** [Makefile:548: util.lo] Error 1
```

I'm using below command to configure:
 export PATH=$PATH:/c/tools/pgsql/13.5/bin
./configure --enable-shared=yes --enable-static=no

**Comment by tt4g** [comment]
This is known issue #398, #424, #441 and already fixed f5cf977e27bcfc152a44451a2b1723a4e4285139.

Please update libpqxx version to 7.5.0 or above or try workaround: http://hectorhon.blogspot.com/2018/05/building-libpqxx-on-msys2-mingw-64-bit.html

**Comment by jtv** [comment]
Exactly.  It's a known bug in mingw64.  Today's MinGW versions support C++17, so I would recommend upgrading your libpqxx.

(I edited the ticket a little bit to get it to render clearly.)

**Comment by iihero** [comment]
> Exactly. It's a known bug in mingw64. Today's MinGW versions support C++17, so I would recommend upgrading your libpqxx.
> 
> (I edited the ticket a little bit to get it to render clearly.)

for the MingGW support C++17,  is there a download version?   thanks.

**Comment by tt4g** [comment]
Support for the C++ standard is determined by the compiler version that is bundled with MinGW. For example, the GCC compiler fully supports C++17 in version 7.1, so you need MinGW with GCC 7.1 or later.

**Comment by iihero** [comment]
> Support for the C++ standard is determined by the compiler version that is bundled with MinGW. For example, the GCC compiler fully supports C++17 in version 7.1, so you need MinGW with GCC 7.1 or later.

Great.  Thanks for your nice help.
