### ISSUE TITLE
deleting a connection trough a pointer to pqxx::connection_base leaks connection

### ISSUE THREAD

**Issue by kalman5** [jtv/libpqxx#58]
See #57 

Most of methods take a pqxx:connection_base for reference so it seems valid to have pointers to pqxx::connection_base around, but deleting a connection trough a pqxx::connection_base pointer leaks the connection. I'd say fine that pqxx::connection_base doesn't have a virtual table but then in his destructor we need to call the close(). My suggestion is to move the close from ~basic_connection to ~connection_base

**Comment by jtv** [comment]
My apologies for taking so long to deal with this — it's a good thing you're shining a light on an ancient part of the code that I sort of forgot.  And now it would seem I typed my response into Github but never posted it...  This keeps happening.

The problem (which I should at least document properly, and will!) is that there's no guarantee that the `connectionpolicy` object is still alive by the time the `connection_base` destructor runs.  The `connection_base` class is more of a base implementation than a base class.

**Comment by capsocrates** [comment]
If it is a base implementation, shouldn't it be `private`? It is too easy to make this mistake. The code is often the first documentation that a dev encounters, especially in maintenance programming. You should make it impossible to compile. If you need to have an intermediate wrapper that forwards calls to the `connection_base` members that could be a workaround. I don't think it's acceptable to publicly inherit from a class that does not have a virtual destructor.

**Comment by jtv** [comment]
My apologies for taking so long to respond...  New work, personal changes, hard to get some quiet computer time.

You make a strong case, but in my defence: this inheritance pattern was copied from the standard language library!  Private inheritance isn't an option.  Adding a vtable might be, but it has nasty problems.  For now, I think the main thing to do is to document that "this class supports some polymorphism but you'll still need to specify the right type when destroying your object."

**Comment by kalman5** [comment]
I don't see why you can not move the close one level up in the hierarchy

**Comment by capsocrates** [comment]
It is more work for you but it will be less bugs for your users if you make `connection_base` a private member of the "child" classes and forward all calls through to the member.

**Comment by jtv** [comment]
Not released yet, but in `master` now: we're in the run-up to 7.0, where the `connection` hierarchy is now just a single class.  No vtable required!

If you don't mind I'll close this ticket now, so it's off the to-do list.  Please try the latest development versions!
