### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by kimiwanano** [jtv/libpqxx#582]
I get the following message when I try to configure the last version:
`checking for sufficient C++ language/library level... no configure: error: This libpqxx version needs at least C++17.`
I also compiled it with `./configure CXXFLAGS="-std=c++17 -O3 "`
But it turns out
```
checking for g++... g++
checking whether the C++ compiler works...  no
configure: error: in `/libpqxx':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
```
However, my GCC is version 9.4.0 and should support c++17. I wonder what is wrong with this ?

**Comment by jtv** [comment]
In the latest versions it's up to you to ensure that the compiler compiles C++17 or better.

So you can add something like this to your `configure` command line: `CXXFLAGS=-std=c++17`

The `CXXFLAGS` variable lets you add command-line arguments to the way the Makefiles invoke the C++ compiler.  The `-std=c++17` argument tells the compiler to compile C++17.

**Comment by kimiwanano** [comment]
> In the latest versions it's up to you to ensure that the compiler compiles C++17 or better.
> 
> So you can add something like this to your `configure` command line: `CXXFLAGS=-std=c++17`
> 
> The `CXXFLAGS` variable lets you add command-line arguments to the way the Makefiles invoke the C++ compiler. The `-std=c++17` argument tells the compiler to compile C++17.

Yes, the problem has been solved. I actually typed c++20 into the command, which was a stupid mistake. However, since my subsequent software installations may not support c++17, I was wondering if there is a version of libpqxx that only requires c++11. Does libpqxx-6.x not require c++17?
