### ISSUE TITLE
Nontransactions are still treated as active transactions

### ISSUE THREAD

**Issue by dc6c** [jtv/libpqxx#583]
I am confused by the purpose of `nontransaction`: from reading the documentation, I was under the impression that I can use it when I "don't care" about transactional integrity and want to just run a query, but from unit test [`test_simultaneous_transactions.cxx`](https://github.com/jtv/libpqxx/blob/master/test/unit/test_simultaneous_transactions.cxx) it seems like nontransactions still can't coexist or overlap.

Is there a transactional type that will allow me to execute an, e.g., SELECT that may or may not be inside another transaction? Is my only choice to always have an `optional<transaction> T` and use either a `nontransaction` when T is `nullopt` and `subtransaction(T)` when it has a value?

**Comment by jtv** [comment]
I'll just close this issue then.  Feel free to open a new one if another issue comes up.

**Comment by dc6c** [comment]
Thanks for that suggestion @jtv, that's the solution I'm following now and works fine.

**Comment by jtv** [comment]
Great to hear @dc6c!
