### ISSUE TITLE
pqxx::work exec(query) takes too long when connection is lost

### ISSUE THREAD

**Issue by s0bes** [jtv/libpqxx#585]
I'm building my qt application on linux. 
The idea is to perform queries on postgresql9.5 remote server (linux as well) and save results to .xlsx file.
I use libpqxx-7.7.3.

The database sometimes on a first query takes 10-15 second to respond. That is why I keep pointer to pqxx::connection throughout all application life cycle and reconnect only when pqxx::broken_connection has been thrown.

The execute function:
```C++

//simplified code for example

pqxx::result sql_io::execute(QString querry)
{
    pqxx::result response;
    try {
        pqxx::work worker(*connectionObject);
        response =  worker.exec(querry.toStdString());
    }
    catch (const pqxx::broken_connection& e) {       
        if(reconnect())
            return execute(querry);
        else
            return pqxx::result();
    }
    catch (const std::exception& e){        
         return pqxx::result();
    }	
    return response;
}
```
I connect to postgresql and initialize connectionObject 
```C++
 connectionObject = new pqxx::connection(getConnectionString());
```
Then I do the queries
```C++
for(QString query : some_queries_array)
{
    pqxx::result response = this->sql_obj->execute(query );
    print_to_xlsx(response);
}
```
Now if I disconnect my postgresql linux machine from network and try to run queries again I will got pqxx::broken_connection inside my first execute function call and will try to reconnect.

But if connection is lost in the middle of querying the data base the  worker.exec() hangs for hours.

I found similar problem with Psycopg2 https://github.com/psycopg/psycopg2/issues/561
One man said 

> However you will not be able to tell apart the difference from a connection lost and a long running query: the server doesn't send keepalives

I tried different stuff
a) played with variety of socket timeouts 
```C++
const int val5 = 15000;
 setsockopt(connectionObject->sock(), IPPROTO_TCP, TCP_USER_TIMEOUT, &val5, sizeof(val5));
```
b) added "keepalives=1  keepalives_idle=5 keepalives_interval=2 keepalives_count=2" to my connection string

c) editing some global params on my clien linux machine

all with no luck.

I even wanted to perform each worker.exec() in a separate thread using std::async but found no way to stop thread after timeout.

Please guide me somewhere so I can resolve this problen

**Comment by tt4g** [comment]
The fundamental problem is that libpq is not designed for multi-threaded sharing of connections.
Connection uses the TCP protocol to communicate with the PostgreSQL server, but this communication is stateful.
If a client shares a connection with multiple threads and sends multiple queries to the server, the server will become confused and behave unexpectedly.

The communication between server and client has failed, but there is no problem with the TCP connection, so your program will block until someone disconnects the TCP connection.

The solution is to never use libpq connections with multiple threads simultaneously.
Please protect the connection from being used by multiple threads at the same time with `std::mutex` or fix the program to create new connections on a per-thread basis.

**Comment by tt4g** [comment]
If your application is single-threaded and hung, you may be manipulating a dangling pointer.

If I remember correctly, libpq associates response data from the database with the connection.
Therefore, when the connection is deleted, some of the pointers referenced by `pqxx::result` should also become dangling pointers.

I cannot determine from the source code you provided what operations your program is performing on libpq connections through libpqxx, but it is probably causing the above defects.
Please make sure that libpq connections are opened and closed within functions and that connections are not held for long periods of time.

**Comment by tt4g** [comment]
> EDIT: (Sorry, I pressed the Comment button in the middle of writing.) And libpq deletes the pointer associated with the connection each time it sends SQL to the database. For example, if you continuously send SQL from the same connection and assign the returned pqxx::result to a local variable, all but the last returned pqxx::result may refer to a dangling pointer.

The above has been added to the last comment.
Are you performing an operation that sends SQL again during the execution of SQL that takes a long time to execute?

By the way, if you want to detect network disconnection while executing SQL, you may be able to do so by setting `statement_timeout` (there are several other timeout settings).
See: https://www.postgresql.org/docs/current/runtime-config-client.html

`PQExec()` is a simple function that sends SQL from libpq, but from the implementation it does not appear to actively check the status of the connection to the network.
This function gets the result set from `PQgetResult` via `PQexecFinish` at the end, but does not appear to be actively checking to see if the socket is connected to the network.

- https://github.com/postgres/postgres/blob/REL9_6_24/src/interfaces/libpq/fe-exec.c#L1896-L1904
- https://github.com/postgres/postgres/blob/REL9_6_24/src/interfaces/libpq/fe-exec.c#L2053
- https://github.com/postgres/postgres/blob/REL9_6_24/src/interfaces/libpq/fe-exec.c#L1753

**Comment by jtv** [comment]
(FWIW a result object has no reference to the connection.  You should be able to close your connection and continue working with the result object, no problem.)

I'm getting a feeling of déjà vu.  I'm sure we've run into this before, and probably done something to reduce the timeout, but the fundamental problem doesn't look like one libpqxx can do much about.

**Comment by s0bes** [comment]
> By the way, if you want to detect network disconnection while executing SQL, you may be able to do so by setting `statement_timeout` (there are several other timeout settings).
Thanks for being with me for so long ;)
I'm not executing any SQL query while executing other query. It is just one at the time. I wait for the result and only after perform another query. 
I tried option statement_timeout=60000 or statement_timeout=60s in my connection to db string. But then I cant even connect. The connection drops right away. I red that statement_timeout must be set after connection is established via SELECT query. But if statement_timeout affects only server side and not doing much when we are disconnected from server I think it is not my case.

> Found it. Similar issues came up in #280.
As far as I understood the issue was in not throwing proper exception while I got no exception thrown at all.
Anyway, thanks for response as well.

Today I actually found workaround with my problem. I will explain it in the next post here

**Comment by s0bes** [comment]
So, here's my workaround.

The issue is that the pqxx::work::exec method cant tell if the connection with data base was lost or just database is not ready to give back results and hangs. May be I'm wrong but that is how I see it. When after half-an-hour I connect my data base back to network, pqxx::work::exec came alive and I continue to run other transactions.

So, I decided to run each transaction in a separate thread (execute_async function). 
```C++

//connectionObject is a global pointer to pqxx::connection

std::pair<pqxx::result, bool> sql_io::execute_async(const QString& querry) noexcept
{    
    try {
        pqxx::result response;
        pqxx::work worker(*connectionObject);
        response =  worker.exec(querry.toStdString());        // we are waiting here long time for result. But if we call connectionObject->close() exception here will be thrown after some short tcp timeout
        return std::make_pair(response, false);
    }
    catch (...) {       
        return std::make_pair(pqxx::result(), true);
    }
    return std::make_pair(pqxx::result(), true);
}
```
And in the main thread I check if 40 sec timeout is expired. If timeout I call connectionObject->close() and this is enough to raise exception somewhere inside pqxx::work::run.

```C++
pqxx::result sql_io::execute(QString querry)
{
    pqxx::result response;
    bool err = false;
    std::future<std::pair<pqxx::result, bool>> fut = std::async(std::launch::async, &sql_io::execute_async, this, querry);

    int timeout_interval = 40;
    do{
        QApplication::processEvents();
        std::future_status status = fut.wait_for(std::chrono::seconds(1));
        if(status == std::future_status::timeout)
            --timeout_interval;
    }
    while(status != std::future_status::ready && timeout_interval > 0);

    if(timeout_interval == 0)
    {
        qDebug() << "Closing socket explicitly";
        connectionObject->close();
    }

    std::pair<pqxx::result, bool> res_pair = fut.get();
    response = std::get<0>(res_pair);
    err = std::get<1>(res_pair);;

    if(err)
    {
        if(reconnect())         
            return execute(querry);
        else
        {
            qDebug() << "Reconnection is unsuccesful";
            return pqxx::result();
        }
    }
   return response;
}
```

**Comment by jtv** [comment]
That should work...  But one note of caution: if you give up on your query and retry it in a fresh connection, the old query could still continue to run to completion.  Which means that you could be starting a whole bunch of identical parallel queries, eating up resources.

**Comment by jtv** [comment]
I suppose  we can close this ticket now?  No rush though.

**Comment by s0bes** [comment]
> I suppose we can close this ticket now? No rush though.

Yes, you can close it. Thanks

**Comment by alexolog** [comment]
Is there a solution (or workaround) to this problem without using multiple threads?

**Comment by jtv** [comment]
@alexolog fundamentally there's no solution at all.  Without the ability to multithread, the things you can do to work around it just get harder.  You could use a process instead of a thread, I guess.

**Comment by alexolog** [comment]
Thank you for your reply, @jtv 

Is there no way to force a timeout?
Does raw libpq suffer from the same problem?  I would expect people to notice (and complain) if that was the case.

**Comment by jtv** [comment]
Yes, this happens inside the libpq call.

**Comment by alexolog** [comment]
PQexec I presume.
Would using the asynchronous PQsendQuery/PQsendQueryParams/PQsendQueryPrepared help in this case?

**Comment by jtv** [comment]
@alexolog fundamentally there's just no good solution - if you have no communication whatsoever with the server, you don't know what's going on with the server.  I've known queries to run on for hours after the connection was lost, and so it's reasonable for libpq not to want to give up until the OS gives up on the connection.  There may be a way to convince the OS to give up sooner.

If you want to try and work around the problem with PQsendQuery and friends, in libpqxx you'd need to use the `pqxx::pipeline` class...  You'd have to have your own waiting loop with a timeout, and keep calling `is_finished()` to find out whether it's safe to retrieve your query's result (in the sense that you'd know it won't block).  That would allow you the opportunity to abort after a given timeout.

**Comment by leleftheriades** [comment]
I am currently also troubleshooting a connection drop not being detected.
in `interfaces\libpq\fe-connect.c` method `setKeepalivesWin32` seems to have a default idle time of 2 hours.
I am adding `keepalives_idle=60` in my connection string. I am hoping this would fix it, since from my understanding
TCP will drop the connection if it tries to send the keepalive and fails to do so after 2 re-transmissions
