### ISSUE TITLE
How to install the C headers and library for client development

### ISSUE THREAD

**Issue by altitudedashboard** [jtv/libpqxx#594]
According to the documentation:

Compiling this package requires PostgreSQL to be installed -- or at least the C headers and library for client development

All I want is to manually compile libpq on macOS (not using brew):

curl -LJO https://github.com/jtv/libpqxx/archive/refs/tags/7.7.4.zip
unzip libpqxx-7.7.4.zip
cd libpqxx-7.7.4
./configure --with-gssapi --with-openssl CXXFLAGS="-std=c++20 -O3"

but this fails with:

configure: error: 
Can't find the main PostgreSQL client header, libpq-fe.h.  Make sure that it
is installed, and either use the --with-postgres-include option or install
pkg-config

so, how can I install just the necessary files to compile it?

Thanks

**Comment by tt4g** [comment]
The `libpq-fe.h` is expected to be under the include path (e.g. `/usr/local/lib/libpq/libpq-fe.h`). If you built the libpq client, you should have that file somewhere on disk.

**Comment by jtv** [comment]
It's been a while...  Mind if I close this ticket?

**Comment by altitudedashboard** [comment]
Yes. It worked. Closing it
