### ISSUE TITLE
Endian-ness issue with bit type?

### ISSUE THREAD

**Issue by mattagape** [jtv/libpqxx#598]
Hi

I seem to have different endianness if I compare what I see with a `psql` session and what I see with `libpqxx`. The database is on the same machine as the program.

Suppose I have a database called gen2. In my `psql` session:

```
# create table test (name varchar, flagdata bit(32));
# insert into test(name, flagdata) values ('mytest', 1::bit(32));
INSERT 0 1
# select * from test;
 name  |             flagdata             
--------+----------------------------------
mytest | 00000000000000000000000000000001
(1 row 
```

So far, so good. Now let's look at my libpqxx program

```
#include <iostream>
#include <pqxx/pqxx> 

// Prepare a statement called "test" 
void prepare_test(pqxx::connection &c)
{
  c.prepare(
    "test",
    "INSERT INTO Test (name, flagdata) values('' || $1 || '', $2::bit(32))");
}

// Execute the test
pqxx::result execute_test(pqxx::transaction_base &t, std::string name, int value)
{
  return t.exec_prepared("test", name, value);
}


int main(int argc, char* argv[]) 
{

   try 
   {
      pqxx::connection C ("dbname = gen2");

      if (C.is_open()) 
      {
            std::cout << "Opened database successfully: " << C.dbname() << std::endl;
      }
      else
      {
            std::cout << "Can't open database" << std::endl;
            return 1;
      }

      prepare_test(C);
      pqxx::work tx(C);
      pqxx::result r = execute_test(tx, "another test", 1);
      tx.commit();
      C.disconnect ();

   } 
   catch (pqxx::sql_error const &e)
   {
      std::cerr << "SQL error: " << e.what() << std::endl;
      std::cerr << "Query was: " << e.query() << std::endl;
      return 2;
   }
   catch (const std::exception &e) 
   {
      std::cerr << e.what() << std::endl;
      return 1;
   }
   
}
```

Compile:
```
g++ -g bit-test.cpp -I/usr/include/pqxx -L/usr/lib/x86_64-linux-gnu -lpqxx -o bit-test
```

Execute:

```
$ ./bit-test
Opened database successfully: gen2
```

Back in psql session:

```
# select * from test;
     name     |             flagdata             
--------------+----------------------------------
 mytest       | 00000000000000000000000000000001
 another test | 10000000000000000000000000000000
(2 rows)
```

What's going on? The two values of `flagdata` should be identical. Do I need to switch on a setting or something?

Thanks

Matthew

**Comment by tt4g** [comment]
I think this is due to libpq API design.
The `PQexecParams` must pass a `const char * const *` (`char* array`) to the prepared statement parameter `paramValues`.
Each parameter must be converted to `char *`, so data of numeric type is also sent to the server as a decimal string.

This means that SQL statements sent to the server are evaluated by the server as follows:

```sql
INSERT INTO Test (name, flagdata) values('' || 'another test' || '', '1'::bit(32))
```

The solution is to explicitly cast `$2` to `int`.

```diff
 // Prepare a statement called "test" 
 void prepare_test(pqxx::connection &c)
 {
   c.prepare(
     "test",
-    "INSERT INTO Test (name, flagdata) values('' || $1 || '', $2::bit(32))");
+    "INSERT INTO Test (name, flagdata) values('' || $1 || '', $2::int::bit(32))");
 }

**Comment by mattagape** [comment]
OK, thanks, I'll try that next week when I'm back in the office.

**Comment by jtv** [comment]
Thanks @tt4g — I don't think I'd have spotted that.  :-)

(And @mattagape on an unrelated note, there's no need to check whether your connection is open — if it fails, you'll get an exception.)

**Comment by mattagape** [comment]
Hi,

Just tried it and it worked. Thanks.

```
# select * from Test;
     name     |             flagdata             
--------------+----------------------------------
 mytest       | 00000000000000000000000000000001
 another test | 00000000000000000000000000000001
(2 rows)
```

Is this documented anywhere? Other than that, I'm happy for this issue to be closed.

M.

**Comment by tt4g** [comment]
The documentation describes how the types of parameters sent in `PQexecParams` are evaluated.

https://www.postgresql.org/docs/14/libpq-exec.html#LIBPQ-PQEXECPARAMS

> Tip
> Specifying parameter types via OIDs is tedious, particularly if you prefer not to hard-wire particular OID values into your program. However, you can avoid doing so even in cases where the server by itself cannot determine the type of the parameter, or chooses a different type than you want. In the SQL command text, attach an explicit cast to the parameter symbol to show what data type you will send. For example:
> 
> SELECT * FROM mytable WHERE x = $1::bigint;
> This forces parameter $1 to be treated as bigint, whereas by default it would be assigned the same type as x. Forcing the parameter type decision, either this way or by specifying a numeric type OID, is strongly recommended when sending parameter values in binary format, because binary format has less redundancy than text format and so there is less chance that the server will detect a type mismatch mistake for you.

**Comment by mattagape** [comment]
Thanks. Closing this issue.
