### ISSUE TITLE
Need of better guide how to build

### ISSUE THREAD

**Issue by fro0m** [jtv/libpqxx#60]
Hi, it is constant fail to build and run tests due to need of better guide.
I fail to make it work with cmake. commands like 
`include_directories(/usr/local/include/)
target_link_libraries(${PROJECT_NAME} PUBLIC /usr/local/lib/libpqxx.a)`
does not link the lib because of failed make install.
Please provide guides

**Comment by jtv** [comment]
I'm not very familiar with CMake, so you'll have to clarify a bit more what it is exactly that you're trying to do.  Are you trying to create your own build setup to build libpqxx itself using CMake?  Or are you trying to build your own project using CMake, and link with a libpqxx instance built and installed using configure/make?

You say that "make install" failed...  Is that a "make install" from your own custom CMake file?  Or did you run libpqxx's "configure" script and then "make install"?

Finally, what _is_ the actual error you're getting?

**Comment by fro0m** [comment]
@jtv ,dear,
problem not actually with cmake, but with building the lib itself. it fails to build. Please describe detailed instruction with correct installation of libpq and setting up

**Comment by jtv** [comment]
For installation of _libpq_ the easiest thing is probably to install the corresponding package for your operating system.  For example, if you're running Debian or a Debian-derived system, you'd "sudo apt install libpq-dev".

If you don't have that option, you could get the full PostgreSQL source tarball and go through the build/install process as documented there.

To install _libpqxx_, the recommended procedure is basically "./configure && make && sudo make install".  There's no CMake involved.

I can't go into more detail without knowing what the actual failure is that you're getting, and under what circumstances.
