### ISSUE TITLE
your website is down

### ISSUE THREAD

**Issue by cmpunches** [jtv/libpqxx#61]

**Comment by jtv** [comment]
Thanks!  This has been happening a lot lately, and it looks like a failing process not getting restarted.

Hunting down the root causes would probably take longer than I have, but I've added a cron job to restart the web server from time to time.  Let's see if that helps.

**Comment by cmpunches** [comment]
Do you need a systems engineer?  We'd be happy to host you in the SILO GROUP umbrella infrastructure in exchange for someone occasionally telling me "wtf I need to do to consume this pqxx::result type".

**Comment by cmpunches** [comment]
(we have 4 9's for uptime)
