### ISSUE TITLE
Mapping rows/tables to objects using libpqxx

### ISSUE THREAD

**Issue by mcraveiro** [jtv/libpqxx#610]
Hi libpqxx developers,

Thanks for an amazing library. I have a question that follows on from the documentation [1] (FAQ: "Can I let libpqxx write data from the database directly into my objects?"). In there, you state:

> You can do the same thing with stream_from, and stream_to does it in the opposite direction. These work with std::tuple<...>. Each field in the tuple corresponds to a field in the database.

I would like to inquire a bit further into the meaning of this statement. Is the best way to map objects into rows to create one's own class following the patterns of ```stream_from``` / ```stream_to``` [2, 3]? Or is there a better way of achieving this? Also in the documents you mention FOST as an example ORM, but I could not find its source code, and given its last release appears to be from 2009 [4], I assume its not up-to-date with the latest API.

At any rate, any ideas on this topic would be greatly appreciated. Many thanks for all your hard work.

Marco

[1] https://pqxx.org/development/libpqxx/faq/
[2] https://github.com/jtv/libpqxx/blob/master/include/pqxx/stream_from.hxx
[3] https://github.com/jtv/libpqxx/blob/master/include/pqxx/stream_to.hxx
[4] https://kirit.com/Categories:/Fost%204

**Comment by jtv** [comment]
Thank you for your kind words.

The mapping in `stream_to` will work for two kinds of object: (1) a `std::tuple` or (2) a container; you can pass either to `write_row()`.  Alternatively, you could write a conversion function which passes the fields to `write_values()`.  In the future perhaps we could let you provide any object that supports `std::get<>()` — but you'll still need to do some work to glue the C++ object and the SQL object together.

For going the other way, with `stream_from`, I believe you can pass anything that supports `std::get<>()` like a `std::tuple` does.

As for FOST...  Perhaps @KayEss can shed some light?

**Comment by mcraveiro** [comment]
Thanks for the prompt response. As it turns out, I am working on a code generator [1], so creating C++ glue code is very much in keeping with our approach :-) However, my main difficulty at present is in trying to understand how the glue code would work, and designing it in a way that it avoids extra copies where possible. I'll focus on ```stream_to``` to start with, as it seems to be the trickier of the two. I'll have a go at creating a conversion function for ```write_values``` and report back on my experiments.

Cheers

[1] https://github.com/MASD-Project/dogen

**Comment by jtv** [comment]
Sounds like a fun project!  If you want the absolute minimum of copying, "simple" types such as `int` should not be a big issue.  For more complex types, you always have the option of reading them as `std::string_view` and parsing the contents at the last possible moment.

**Comment by mcraveiro** [comment]
Yes, I was thinking the same actually. So, for each class, I could code-generate a matching tuple which represents the fields of the class (assuming only simple types or strings), and then have a method that initialises the tuple with object state. This is probably fairly trivial to code-generate... I'll probably hack together a simple example to prove the idea, and see how far that takes me. Thanks!

**Comment by KayEss** [comment]
> FOST as an example ORM, but I could not find its source code

The latest release is here: https://kirit.com/Blog:/2020-03-22/Fost%205%20release%205.20.03.45095%20now%20out and the projects are all now here: https://github.com/hotkit

It's unclear to me who owns control of these particular repos now, but of course anybody who wants to make use of them is free to fork them.

All of the SQL to object mapping stuff ended up getting removed and it most of the O/RM functionality went with it between about versions 3 and 4 I think and never came back -- everything went to a more dynamic system where the clients held the domain objects and the Fost code intermediated with the databases and HTTP.

**Comment by mcraveiro** [comment]
@KayEss thanks very much for the information. I guess the objective of this ticket will then be to work out a "canonical" example of how to read and write a trivial object to the database, which the maintainers are happy with and which can be added to the documentation. I'll update the ticket with the effort as I go along.

**Comment by jtv** [comment]
Any luck @mcraveiro?  Happy new year!

**Comment by mcraveiro** [comment]
Happy new year! Sadly most of my Christmas hols were taken with low-level maintenance work on my project so I didn't get around to do anything fun :-) to be fair, maybe I should close this ticket for now and re-open it when I get some sample data to look at? Thanks for all your help.

**Comment by jtv** [comment]
Probably for the best, yes.  I don't like to be completely without open tickets but this one's a but vague at this point.

**Comment by mcraveiro** [comment]
Yep makes sense. Thanks.
