### ISSUE TITLE
Compiling Without RTTI

### ISSUE THREAD

**Issue by Alexei-Barnes** [jtv/libpqxx#611]
I'm trying to use libpqxx in an Unreal Engine project. I've gone through a couple of iterations, which I'll describe first before the exact problem I'm trying to resolve:

My first approach to using pqxx in Unreal was to create a self-contained plugin which would make the use if pqxx entirely private. However, I ran into issues doing that while using prepared statements. `exec_prepared` is a templated function, so I'm not sure how I could create a reasonable API around that. Any naïve approach I've tried will end up leaking libpqxx headers outside of the plugin.

My second approach was to use pqxx directly from my Unreal game code. This bypassed needing to hide the use of pqxx, and I could directly use the great API it provides (it was much nicer to program against than other DBs we are working with). This worked great on Windows under MSVC. However, it didn't work while compiling Unreal for Linux, because:

```
[2022-11-16T01:09:55.931Z] .../include/pqxx/strconv.hxx:82:58: error: use of typeid requires -frtti
[2022-11-16T01:09:55.931Z] std::string const type_name{internal::demangle_type_name(typeid(TYPE).name())};
[2022-11-16T01:09:55.931Z]                                                          ^
[2022-11-16T01:09:55.931Z] 1 error generated.
```

From what I understand, building with RTTI is not a great idea in Unreal, as you'll end up mixing RTTI and non-RTTI binaries in an incompatible way (though I'll just go ahead and state I haven't tried this, and I know very little about RTTI).

Sorry for creating a somewhat open-ended issue, but is there some better way I could be approaching this problem, or some way to address my issues?

From what I can tell RTTI is used for creating pretty error messages but is otherwise non-essential. Is it worth considering using libpqxx without RTTI, or is that a non-starter?

Alternatively, is there a good way I could encapsulate the API of libpqxx (particularly `exec_prepared`)? From what I understand if I can compile this all into a self-contained Unreal plugin then I am able to safely turn on RTTI for that plugin alone.

Thanks!

**Comment by jtv** [comment]
RTTI has been a very standard thing for a very long time now, so I never considered that anyone might want to compile without it.  Yes, you are correct that this use of `typeid` is only for making nicer error messages, but that's not going to be the only use of RTTI.  Unless I'm totally misremembering this from decades ago, RTTI is mixed in with the support for C++ virtual member functions.  Of which libpqxx does not use many, but it does use some.

The easiest solution might be to not use prepared statements at all.  Prepared statements were invented as an optimisation, but they aren't even necessarily faster.  You save query planning time, but that does mean you get a query plan that's less specifically optimised for your actual query.  So... try regular `exec` instead.

That does mean that you'll need to compose the full query string yourself, without the `$1` parameter-passing in the SQL.  Instead you'd use `pqxx::quote(...)` to get a value's string representation, including quotes as required.

Alternatively, if I understand your setup correctly, you could try declaring a templated wrapper for `exec_prepared` in your header, and then defining it only in your plugin code, non-inline:

```cxx
template<typename ...Args> auto exec_prep(pqxx::transaction_base &tx, pqxx::zview statement, Args &&...args)
{
    return tx.exec_prepared(statement, args...);
}
```

Then, you'll get link errors because the specific instantiations of this function that you actually call are never defined anywhere.  So what you do next is, below your function's definition, write explicit instantiations.  Off the top of my head, I think the syntax would be:

```cxx
// Example: for a statement with argument types "int" and "std::string_view"...
template auto exec_prep(pqxx::transaction_base &, pqxx::zview, int, std::string_view);
```

**Comment by Alexei-Barnes** [comment]
Thanks, fair enough, if non-RTTI isn't an option then this looks like a reasonable approach.

**Comment by KayEss** [comment]
> Yes, you are correct that this use of `typeid` is only for making nicer error messages, but that's not going to be the only use of RTTI

RTTI is used for only 2 things I think: `typeid` and `dynamic_cast`. Virtual dispatch is available without RTTI, but they're not connected to any reified type information at runtime without it.

**Comment by jtv** [comment]
Ah, in that case it may be an option to compile with RTTI after all!  There's one `dynamic_cast` in a test, and you'd have to stub out the definition of `type_name` in strconv.cxx.  Probably a fair bit of work, but you could just provide explicit specialisations of `type_name`:

```cxx
template<> std::string const type_name<int>{"int"};
template<> std::string const type_name<pqxx::connection>{"connection"};
// ...
```

**Comment by jtv** [comment]
(I'll reopen now that there's a choice of solutions again.)

_Almost_ tempted to provide this workaround as a feature...  But it could involve a lot of types, and doesn't help many modern build scenarios.

**Comment by Alexei-Barnes** [comment]
Yea really it's just Unreal Engine specifically - this is still true as of Unreal 5.0.3, though I haven't tested 5.1 I imagine it will be the same.

**Comment by Alexei-Barnes** [comment]
Another option here would be if there was a different interface than `exec_prepared`, since that would make the encapsulation easier. If there was an interface that allowed me to set one parameter at a time, that would be much easier to wrap since I wouldn't need to define an arbitrary statement for every combination of possible arguments.

**Comment by jtv** [comment]
There's also `pqxx::params`.  You can pass that as a way to encapsulate multiple arguments at once.

**Comment by Alexei-Barnes** [comment]
OK nice, so I guess I can use that in `exec_prepared` then? If so that is a nice solution to my problem I hope.

I've written a wrapper for `pqxx::params` which actually magically gets me back the templated interface (since I can just use the same parameter pack expanding trick to build my wrapper of `params` as `params` uses itself), which is nice. However, I'm still getting some undefined external symbols that I don't expect, so I'll need to do some more work tomorrow to figure that out. I think that's ultimately down to linking through, because I think the pattern is sound now.

**Comment by Alexei-Barnes** [comment]
OK, figured this out. Here's the summary of how to use libpqxx with Unreal:

1. You'll want to compile libpqxx for linux using the Unreal toolchain (set your `sysroot` to the unreal toolchain, also compile all dependencies using this, place them into your sysroot so libpqxx's build finds them)
2. Write a plugin, which forward declares your libpqxx types in its headers, so that the headers never include pqxx
3. Write wrapper types for `pqxx::connection`, `pqxx::transaction_base`, `pqxx::result`, `pqxx::row`, `pqxx::field`, `pqxx::const_result_iterator`, `pqxx::const_row_iterator`, and `pqxx::params` (plus anything else you want)
4. Your wrapper for params should implement a generic `Append<T>(const T&)`
5. You must write a template instantiation of `Append` (and all other generic methods) into your .cpp for your wrapper
6. You must write `extern template MODLE_API ...` instantiations in the .h for your wrapper, so that it ends up in the DLL (MODULE being the module API macro for dllexport)

Point 6 took me a while to figure out because I assumed that plugins were statically linked, however, on Windows they are dynamically linked.

This solution works because you can now write;

```cpp
FPostgreSqlResultSet ExecutePreparedParams(const FString& Name, const FPostgreSqlParams& Params) const;

template <typename ...Types>
FPostgreSqlResultSet ExecutePrepared(const FString& Name, Types&&... Args) const {
    return ExecutePreparedParams(Name, FPostgreSqlParams { std::forward<Types>(Args)... });
}
```

And:

```cpp
template <typename ...Types> FPostgreSqlParams(Types&&... Args)
    : FPostgreSqlParams()
{
    Reserve(sizeof...(Args));
    AppendPack(std::forward<Types>(Args)...);
}

size_t size() const;
void Reserve(size_t);

template <typename T> void Append(const T&);

template<typename HeadT, typename... TailT>
void AppendPack(HeadT&& Head, TailT&&... Tail)
{
    this->Append(std::forward<HeadT>(Head));
    this->AppendPack(std::forward<TailT>(Tail)...);
}

constexpr void AppendPack() noexcept {}
```

Which makes `ExecutePrepared` generic, without needing any NxW instantiations for every possible combination of parameters.

**Comment by jtv** [comment]
Congratulations!  Glad to hear you got this working.

**Comment by Alexei-Barnes** [comment]
Thanks for all the help!
