### ISSUE TITLE
Question: How to handle null values in query1() function?

### ISSUE THREAD

**Issue by MPuust** [jtv/libpqxx#615]
As per the example in README.MD I am trying to query data from database, but get an error casting null into string. What's the best way to handle null's in data when the column type is text and using query1() function?

Example top_name = null.
```
auto [top_name, top_salary] = tx.query1<std::string, int>(
                R"(
                    SELECT name, salary
                    FROM employee
                    WHERE salary = max(salary)
                    LIMIT 1
                )");
```

**Comment by tt4g** [comment]
Columns that may be NULL should be wrapped with `std::optional<T>`.

**Comment by MPuust** [comment]
Worked like a charm, thanks!
