### ISSUE TITLE
how to call a stored procedure?

### ISSUE THREAD

**Issue by qinrhx** [jtv/libpqxx#618]
my stored procedure  as bellow:
```

create or replace procedure F_xxxxxx_query(IN "id" int)
AS 
begin
   select * from "a_c" ac where a = "id";
end;
```
and my c++ code is like this:
```
try {
			_conn->prepare("P_xxxxxx_query", "call F_xxxxxx_query($1);");
			pqxx::work w(*_conn);
			pqxx::result r(w.exec_prepared("P_xxxxxx_query", 0));
			w.commit();
}
catch(....)
```

then i get this exception：

# ERR:  INVALID MODE variable is bound to IN position
, SQL:P_xxxxxx_query)

so how to call stored procedure correctly?

**Comment by tt4g** [comment]
It doesn't seem to match any of the `CREATE FUNCTIION` syntaxes that I know of; check the PostgreSQL documentation for the correct syntax.
See: https://www.postgresql.org/docs/13/sql-createfunction.html

The following syntax will work (DB Fiddle: https://www.db-fiddle.com/f/6yERR8ycgc9QenGJmjtzgo/0):

```sql
CREATE TABLE a_c(id SERIAL PRIMARY KEY, name TEXT);
    
INSERT INTO a_c("name") VALUES ('foo'), ('bar'), ('baz');
    
CREATE FUNCTION F_xxxxxx_query(INTEGER)
    RETURNS TABLE (
        id INTEGER,
        name TEXT
    )
    AS $$
        SELECT id, name FROM "a_c" WHERE "a_c"."id" = $1
    $$
LANGUAGE SQL;
    
SELECT * FROM F_xxxxxx_query(1);
```

| id  | name |
| --- | ---- |
| 1   | foo  |

**Comment by qinrhx** [comment]
> It doesn't seem to match any of the `CREATE FUNCTIION` syntaxes that I know of; check the PostgreSQL documentation for the correct syntax. See: https://www.postgresql.org/docs/13/sql-createfunction.html
> 
> The following syntax will work (DB Fiddle: https://www.db-fiddle.com/f/6yERR8ycgc9QenGJmjtzgo/0):
> 
> ```sql
> CREATE TABLE a_c(id SERIAL PRIMARY KEY, name TEXT);
>     
> INSERT INTO a_c("name") VALUES ('foo'), ('bar'), ('baz');
>     
> CREATE FUNCTION F_xxxxxx_query(INTEGER)
>     RETURNS TABLE (
>         id INTEGER,
>         name TEXT
>     )
>     AS $$
>         SELECT id, name FROM "a_c" WHERE "a_c"."id" = $1
>     $$
> LANGUAGE SQL;
>     
> SELECT * FROM F_xxxxxx_query(1);
> ```
> 
> id	name
> 1	foo

But I'm using a stored procedure，not a function. The stored procedure is correct, and I can call it correctly in the client IDE, but the libpqxx library calls it with error.

**Comment by tt4g** [comment]
I could not find the syntax `F_xxxxxxxx_query(IN "id" int)` in the `CREATE PROCEDURE` document (https://www.postgresql.org/docs/13/sql-createprocedure.html), `IN` gives a syntax error.

Does it work by running it directly with the `psql` command without using the IDE?
And do you know the version of the PostgreSQL server?

**Comment by qinrhx** [comment]
> I could not find the syntax `F_xxxxxxxx_query(IN "id" int)` in the `CREATE PROCEDURE` document (https://www.postgresql.org/docs/13/sql-createprocedure.html), `IN` gives a syntax error.
> 
> Does it work by running it directly with the `psql` command without using the IDE? And do you know the version of the PostgreSQL server?

Sorry, I made a mistake. The database I used was customized based on postgresql. It was the database itself, not the libpqxx library.
