### ISSUE TITLE
connecting from docker container to another container

### ISSUE THREAD

**Issue by ronytigo** [jtv/libpqxx#637]
I have the cpp code in one container, and the postgres server on another one.
In the connection string I have `...hostaddr=postgres...`.
`postgres` is the name of the service in docker-compose (where the postgres server is running).
I get this error:
`could not parse network address "postgres": Name or service not known`.

**Comment by jtv** [comment]
This does not look particularly related to libpqxx, so I probably won't be able to help much.

If you try to "ping postgres", or try to reach the host "postgres" in some other way, _from within the container where you run your C++ code,_ do you get the same error?

**Comment by ronytigo** [comment]
No, I did `ping postgres` and I got a response. I ran it from within the container.

**Comment by jtv** [comment]
Then I'm left only with wild guesses:

Is the next character after "postgres" a normal space?

I don't suppose libpq could be misunderstanding the hostname...  What happens if you run psql with "-h postgres", also from the same container?

**Comment by ronytigo** [comment]
psql works.
and yes, it's a normal space. I take the address from a .yml file.
If the .yml has an IP address of a remote machine, it works. If it has "postgres", it fails with the error I mentioned.

**Comment by jtv** [comment]
This could be it.  From the [libpq connection strings documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING):

```
host

    Name of host to connect to. If a host name looks like an absolute path name, it specifies
    Unix-domain communication rather than TCP/IP communication; the value is the name
    of the directory in which the socket file is stored.  [...]

    [...]

hostaddr

    Numeric IP address of host to connect to. This should be in the standard IPv4 address
    format, e.g., 172.28.40.9. If your machine supports IPv6, you can also use those
    addresses.  [...]
```

So use `hostaddr` only for IP addresses, and `host` for hostnames or Unix domain sockets.

**Comment by ronytigo** [comment]
works, thanks!
