### ISSUE TITLE
Problem Connecting to Database in Google Tests

### ISSUE THREAD

**Issue by nestorcamposgestal** [jtv/libpqxx#639]
Hi!

I am using in my project libpqxx to connect to my PostgreSQL database. I have a docker compose with two services, one for the database, and the other one is a Debian image where I have installed all the dependencies of my C++ program. Libpqxx works fine in all my program and files, but the problem comes when I try to use it on the Google Tests I am implementing. Here an example of the SetUp function for the tests where it is failing:

```c++
//Function called before the test starts
void TestObjectClass::SetUp(){
    object = new ObjectClass("path_to_file.dat");
    object -> ParseFile();
}
```

As you can see in this example, the ParseFile function is the one that inside connects to the database to get some information. The thing is that in my program (outside the tests), everything works great and when I use this function in my main.cpp works, but in this function of the SetUp for a Google Test gives me this error:

```
unknown file: Failure
C++ exception with description "could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
" thrown in SetUp().
```

First I thought it was a problem of CMake that it was not linking correctly libpqxx to the executable of this test, but I already made sure that I am doing that correctly.

Any help?

**Comment by jtv** [comment]
That means that libpqxx could not connect to the database in the default location.  The most likely cause is that you need to configure the host and/or port, and of course the container boundary complicates that.

You'll need to find out under what IP address and port your code can reach the database _from the context in which your code runs,_ and set that either in environment variables or your connection string.  This [page in the documentation](https://libpqxx.readthedocs.io/en/stable/a00251.html) may help with that.

**Comment by nestorcamposgestal** [comment]
Yep! I forgot to load the parameters to connect to the database in the Setup of the tests. Now it is solved! Many thanks for the fast answer!

I will close the issue.
