### ISSUE TITLE
Describe SQL, without execution

### ISSUE THREAD

**Issue by nvanwyen** [jtv/libpqxx#641]
Most databases (e.g. Oracle, SQL*Server, Sybase, ... ) send back a description of the resultset, even if there are zero rows. I cannot seem to find this in pqxx, nor can I find a way to describe SQL of any kind prior to execution. The only way I have been able to get the SQL metadata is by collection upon the first row retrieved, but this is limited to an actual row being retrieved. If there are zero rows, I have no way to determine the metadata.

Looking at the v15.x code for libpq, I see that psql has a "workaround" for this very problem, which I'm hoping can be added to pqxx. In the file ```src/bin/psql/common.c``` there is a function called ```static bool DescribeQuery(const char *query, double *elapsed_msec)``` (on or about line #1248).

This function has a rather ingenious solution for this very problem. They create an "unnamed" prepared statement, which they do not execute, but get the results object which provides the field info, that is subsequently queried against the pg_catalog for the metadata descriptions (source below).

Unfortunately, the pqxx library doesn't provide enough (that I can tell) to duplicate this functionality for client users like myself.

My question is this
    1. Is there a solution, that I'm unaware of, to this problem?
    2. If not, then can this be added to libpqxx?
    3. If it can be added, when can it be done?

excerpt from ```src/bin/psql/common.c``` ...

```
1248 /*  
1249  * DescribeQuery: describe the result columns of a query, without executing it
1250  *      
1251  * Returns true if the operation executed successfully, false otherwise.
1252  *  
1253  * If pset.timing is on, total query time (exclusive of result-printing) is
1254  * stored into *elapsed_msec.
1255  */         
1256 static bool 
1257 DescribeQuery(const char *query, double *elapsed_msec)
1258 {           
1259     bool        timing = pset.timing;
1260     PGresult   *result;
1261     bool        OK;           
1262     instr_time  before,       
1263                 after;        
1264                               
1265     *elapsed_msec = 0;
1266             
1267     if (timing) 
1268         INSTR_TIME_SET_CURRENT(before);
1269                 
1270     /*  
1271      * To parse the query but not execute it, we prepare it, using the unnamed
1272      * prepared statement.  This is invisible to psql users, since there's no
1273      * way to access the unnamed prepared statement from psql user space. The
1274      * next Parse or Query protocol message would overwrite the statement
1275      * anyway.  (So there's no great need to clear it when done, which is a
1276      * good thing because libpq provides no easy way to do that.)
1277      */         
1278     result = PQprepare(pset.db, "", query, 0, NULL);
1279     if (PQresultStatus(result) != PGRES_COMMAND_OK)
1280     {               
1281         pg_log_info("%s", PQerrorMessage(pset.db));
1282         SetResultVariables(result, false);
1283         ClearOrSaveResult(result);
1284         return false;
1285     }
1286     PQclear(result);
1287 
1288     result = PQdescribePrepared(pset.db, "");
1289     OK = AcceptResult(result, true) &&
1290         (PQresultStatus(result) == PGRES_COMMAND_OK);
1291     if (OK && result)
1292     {
1293         if (PQnfields(result) > 0)
1294         {
1295             PQExpBufferData buf;
1296             int         i;
1297 
1298             initPQExpBuffer(&buf);
1299 
1300             printfPQExpBuffer(&buf,
1301                               "SELECT name AS \"%s\", pg_catalog.format_type(tp, tpm) AS \"%s\"\n"
1302                               "FROM (VALUES ",
1303                               gettext_noop("Column"),
1304                               gettext_noop("Type"));
1305 
1306             for (i = 0; i < PQnfields(result); i++)
1307             {
1308                 const char *name;
1309                 char       *escname;
1310 
1311                 if (i > 0)
1312                     appendPQExpBufferStr(&buf, ",");
1313 
1314                 name = PQfname(result, i);
1315                 escname = PQescapeLiteral(pset.db, name, strlen(name));
1316 
1317                 if (escname == NULL)
1318                 {
1319                     pg_log_info("%s", PQerrorMessage(pset.db));
1320                     PQclear(result);
1321                     termPQExpBuffer(&buf);
1322                     return false;
1323                 }
1324 
1325                 appendPQExpBuffer(&buf, "(%s, '%u'::pg_catalog.oid, %d)",
1326                                   escname,
1327                                   PQftype(result, i),
1328                                   PQfmod(result, i));
1329 
1330                 PQfreemem(escname);
1331             }
1332 
1333             appendPQExpBufferStr(&buf, ") s(name, tp, tpm)");
1334             PQclear(result);
1335 
1336             result = PQexec(pset.db, buf.data);
1337             OK = AcceptResult(result, true);
1338 
1339             if (timing)
1340             {
1341                 INSTR_TIME_SET_CURRENT(after);
1342                 INSTR_TIME_SUBTRACT(after, before);
1343                 *elapsed_msec += INSTR_TIME_GET_MILLISEC(after);
1344             }
1345 
1346             if (OK && result)
1347                 OK = PrintQueryResult(result, true, NULL, NULL, NULL);
1348 
1349             termPQExpBuffer(&buf);
1350         }
1351         else
1352             fprintf(pset.queryFout,
1353                     _("The command has no result, or the result has no columns.\n"));
1354     }
1355 
1356     SetResultVariables(result, OK);
1357     ClearOrSaveResult(result);
1358 
1359     return OK;
1360 }
```

**Comment by nvanwyen** [comment]
The easy solution to this issue would be to return the fields based on the result. On 738 of the ```connection.cxx``` you are creating a ```pqxx::result``` object from the return value of ```PQprepare()```, but then you are just throwing it away. If you create the fields, from the return of the object, then it could be used in very much the same way as the ```DescribeQuery()``` call does in psql.

```
 732 void pqxx::connection::prepare(char const name[], char const definition[]) &
 733 {
 734   auto const q{std::make_shared<std::string>(
 735     pqxx::internal::concat("[PREPARE ", name, "]"))};
 736 
 737   auto const r{
 738     make_result(PQprepare(m_conn, name, definition, 0, nullptr), q, *q)};
 739 }
```

**Comment by jtv** [comment]
Have you tried adding a condition `AND false` to your `WHERE` clause to get a prototype of your query result?

**Comment by nvanwyen** [comment]
Thank you for the response, and no I haven't tried that, but I'm not sure how that would work. Adding ```AND false``` as a predicate will simply prevent any rows from returning, correct? If so, that's what I have now so I don't understand how that solves or works around my issue.

I need to describe the SQL, even with no rows returning. As an example in the PGadmin Query Tool if you run a select the tool will display all the columns in the grid, even if no rows are returned. This is what I need to accomplish in pqxx.

BTW: I'm not opposed to a purely SQL solution. If I ```prepare []``` a statement and can figure out how to get the metadata from the catalog, I'd be perfectly happy with that. But all I can find is the ```pg_prepared_statements``` view which doesn't provide the information I need (e.g. column list, oid, ...).

**Comment by nvanwyen** [comment]
You solved it. I couldn't see the forest because of all those trees in the way, but after playing around with your suggestion I got working .... Thank you so much!

**Comment by jtv** [comment]
No worries, glad your problem is solved.  I'll reopen this ticket as a reminder that a "describe query" function may still be useful.
