### ISSUE TITLE
connection string ERROR

### ISSUE THREAD

**Issue by yanboyang713** [jtv/libpqxx#642]
Hello All,

Good day to you.

I want to make a connection string. But, faced the error msg below.

```c++
const std::string connectString = "dbname=" + dbname + " user=" + userName + " password=" + password + " hostaddr=" + hostAddress + " port=" + port;

connection C(connectString);
```

Error:
```
Opened database successfully: anomalyprediction
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::append
```

Below Worked:
```
connection C("dbname = anomalyprediction user = postgres password = password \
hostaddr = 127.0.0.1 port = 5432");

```

Thanks for your help.
Boyang Yan

**Comment by KayEss** [comment]
The error messages indicates that there's a problem in forming the connection string. You don't show your code, but I would guess that at least one of the string parameters you're using (`dbname`, `userName` etc) is pointing to dead memory and the error is thrown during construction of `connectString`

**Comment by yanboyang713** [comment]
Hello @KayEss,

Thanks for your reply,

```
#ifndef DATABASE_H
#define DATABASE_H
#include <string>

class database{
    //protected:

    private:
        std::string dbname;
        std::string userName;
        std::string password;
        std::string hostAddress;
        std::string port;

        std::string url;

    public:
        database();
        database(std::string url);
        ~database();
        bool connect();

};

#endif

```

```
#include "database.h"
#include <cstring>
#include <pqxx/pqxx>
using namespace pqxx;

database::database():
   dbname("anomalyprediction"),
   userName("postgres"),
   password("password"),
   hostAddress("127.0.0.1"),
   port("5432")

{
    std::cout << "Constructor Called" << std::endl;
    bool databaseConnect = connect();
}

database::database(std::string url) {

}

database::~database(){
    std::cout << "De-constructor Called" << std::endl;

}

bool database::connect(){

   const std::string connectString = "dbname=" + dbname + " user=" + userName + " password=" + password + " hostaddr=" + hostAddress + " port=" + port;
   std::cout << "connectString: " << connectString << std::endl;

   //std::cout << connectString.size() << std::endl;
   try {
      //connection C("dbname=" + dbname + " user=" + userName + " password=" + password + " hostaddr=" + hostAddress + " port=" + port);
      connection C(connectString);
      //worked
      //connection C("dbname = anomalyprediction user = postgres password = password \
      //hostaddr = 127.0.0.1 port = 5432");
      if (C.is_open()) {
         std::cout << "Opened database successfully: " << C.dbname() << std::endl;
      } else {
         std::cout << "Can't open database" << std::endl;
         return false;
      }
      C.close ();
   } catch (const std::exception &e) {
      std::cerr << "database cerr: " << e.what() << std::endl;
      return false;
   }
}

```

**Comment by KayEss** [comment]
You must also have something that drives this? Something with `main` in it?

If your error is correct then it seems the database opens, so it looks like the problem is in `main`

**Comment by KayEss** [comment]
It looks like `database::connect` doesn't return a `bool` on every bode path. You should make sure that your code compiles with no warnings, and you may find it useful to increase the warning level that you're getting as high as you can -- how you do that depends on the compiler you're using, but you should be able to find plenty of info online for how to do it

**Comment by yanboyang713** [comment]
I have a very short main function just for testing
```
int main (int argc, char **argv){
    database data;
    bool succ = data.connect();
    if (succ == true) {
        std::cout << "database connect success" << std::endl;
    }

    anomalyPrediction main;


    if (!main.Configure (argc, argv))
        NS_FATAL_ERROR ("Configuration failed. Aborted.");

    main.Run ();

    return 0;
}
```

Have you using Cmake install the libpqxx?
Currently, I am installed libpqxx from Arch Linux package: https://archlinux.org/packages/extra/x86_64/libpqxx/

**Comment by KayEss** [comment]
I see that there's a load of other stuff going on in main after you try to connect to the database. Remember that your `connect` method doesn't actually ever return a `true` on any code path -- you should fix that.

Does remove the code from `anomalyPrediction main;` onwards fix your problem? If so then the problem is in there somewhere.

Turn your warnings up as many levels as you can, and fix all warnings. Your reproduction you show us should be as short as possible and not contain anything that isn't part of the problem.

**Comment by yanboyang713** [comment]
@KayEss 
Strange. I reinstall the **libpqxx** package. problem gone

Nothing change on my code.

I should try to use Cmake install **libpqxx**

Thanks for your help
