### ISSUE TITLE
Support for params in `query` functions

### ISSUE THREAD

**Issue by kylepl** [jtv/libpqxx#646]
Hi,

I'm using `transaction_base::exec_params0` to safely pass parameters into my query, and was wondering if it is reasonable to add to the `query_value`, `query_1`, `query_01` functions - i.e. templated `Args &&...args` as the last argument(s) to each function.

Happy to send a pull request for it, just verifying it seems reasonable.

Kyle

**Comment by jtv** [comment]
That is indeed the plan!

But it will take some time.  The exec functions take an _optional_ extra argument where you can name the command, so that any errors can refer to the statement by name.  That can make debugging easier, but I'm not sure many people have made use of it.

That feature is deprecated now, and in 8.x (which will require C++20) I want to use `std::source_location` instead.  But until I get rid of the optional argument, there's no good way to tell a parameter from a statement name.

Another option I've been considering is to take an optional `pqxx::params` object.  It's not quite as pretty though.

**Comment by kylepl** [comment]
Hm, that is tricky - especially that fact that even once you migrate, it's unclear if the intent was a description (and they should migrate) or a label.

What if, like `exec_params0`, we added `query_value_params` which would be unambiguous, and not take description ever? Then this could proceed independently from deprecation, and matches the current function name style.

**Comment by jtv** [comment]
Long name though!  My idea of a migration path was to add a new overload that takes a `pqxx::params`, and then later once I have some confidence that the name string is no longer in use, we can replace the `pqxx::params` with any parameter pack.  And then the `pqxx::params` would just be one special case of what you could pass, and it would work the same either way.

One other open question is whether I can add the `std::source_location` as an optional parameter _after_ the parameter pack, something like...

```cxx
    template<typename... ARG>
    result exec(
        std::string_view query,
        ARG... &&args,
        const std::source_location loc=std::source_location::current())
    {
        // ...
    }
```

I have a horrible feeling that it may turn out to be a problem to distinguish the `source_location` argument from the parameter-pack arguments.

**Comment by kylepl** [comment]
It is a bit longer, but given it matches the other style, I don't find it too concerning. (Just my opinion, not saying to do it that way)

I think the tricky bit it is never actually safe to eventually have the parameter pack with the same function name, since users may not upgrade for a year or two, and then jump past the intermediate version. Every choice has trade-offs though.

For now I've locally patched my version, so no rush from my side. :)

**Comment by jtv** [comment]
Another consideration by the way for the issue of passing `std::source_location` in addition to a parameter pack: in C++20 I'll be able to define a parameter pack of "anything that's not `std::source_location`, followed by an optional `std::source_location`.  Or with a recent change in the string conversion API, I'll even be able to specify a parameter pack of "values that we know how to convert to SQL."
