### ISSUE TITLE
How does result fetching internally work?

### ISSUE THREAD

**Issue by skinkie** [jtv/libpqxx#65]
Consider that I need multiple passes over my resultset. What happens in libpqxx? Is the result buffered buffered clientside once or is it fetched from the server when iterated over?

```
pqxx::connection C(connection_string);
pqxx::nontransaction N(C);
pqxx::result R( N.exec( sql ));

for (pqxx::result::const_iterator c = R.begin(); c != R.end(); ++c) {

}

for (pqxx::result::const_iterator c = R.begin(); c != R.end(); ++c) {
}
```

**Comment by jtv** [comment]
It's fetched all at once, and then kept in memory so long as your result object (or any copy of it) remains alive.

**Comment by skinkie** [comment]
Thanks, that saves me some effort.
