### ISSUE TITLE
using prepared statement in pipeline

### ISSUE THREAD

**Issue by gms1** [jtv/libpqxx#654]
Hi,

it looks like the pipeline currently just supports PQsendQuery but unfortunately PQsendQueryPrepared is not supported
Is that correct and will this be changed?

**Comment by jtv** [comment]
That is correct.  It would be a fair bit of work to address that.  First thing I want to do with that code is replace it with an implementation on top of libpq's pipeline feature.  Once that works, we can see how we can extend it.

It's a funny story: I wrote the pipeline feature in 2005, and then around 2014 I think the same idea was brought up in the context of the Java postgres API, and then more recently that was taken up into the C postgres API... and it looks very compatible with what I built 18 years ago!  So I think I can just re-implement the existing API on top of that.  There's a certain inevitable logic to the nature of the problem we're solving.  But I'll have to see how that plan affects the prospects for supporting pipelined prepared statements.  Frankly I didn't get the impression that a lot of people were interested in the feature, so it hasn't been a priority.

All that said, before you use prepared statements for optimisation, it's important to know whether they will actually help in your specific situation.  If you're doing a lot of repetitive, relatively complex yet fast SELECTs, where query planning takes up a large chunk of time, then I think prepared statements make sense.  But there may be other ways of optimising for that specific scenario.

If your scenario is different, be aware that prepared statements can make some things faster and other things slower.

**Comment by gms1** [comment]
many thanks for your answer; in my case it is just for sending prepared dml statements in bulk (insert/update/delete), so the real pipeline mode would indeed be the best fit

**Comment by gms1** [comment]
currently the pqxx pipeline seems to work well inside the current transaction, not sure if this would hold true for the "libpq pipeline mode", which seems to open an implicit transaction

anyway, i am actually less interested in the libpq pipeline mode than in the prepared statement support of the pqxx::pipeline :-)

I'd love to do open a PR for this, but unfortunately it is unlikely that i will find the time to do so
