### ISSUE TITLE
[c++17 support] ISO C++1z does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by masterspline** [jtv/libpqxx#66]
When compiling "Brief example" from http://pqxx.org/development/libpqxx/ with c++17 enabled I got error:

/usr/include/pqxx/tuple.hxx:95: error: ISO C++1z does not allow dynamic exception specifications
   reference at(size_type) const throw (pqxx::range_error);   //[t11]

Please, change all throw() to noexcept() or make some other change to fix this error.

==============================================
user@host:/usr/include/pqxx$ cat version.hxx | grep "PQXX_VERSION "
#define PQXX_VERSION "4.0.1"

**Comment by jtv** [comment]
That's a very old version of libpqxx.  Consider upgrading to 6.x.

**Comment by masterspline** [comment]
This surprised me. I use Debian testing and libpqxx version there is really old. I will try to fix this.
Thank You for your answer.
