### ISSUE TITLE
connection-stream_from.hxx not copied in the proper directory at install

### ISSUE THREAD

**Issue by zalmoxis2019** [jtv/libpqxx#660]
Hello 
    When i try to build the last 7.7.4 version from master i get the bellow compile error. To solve: I checked out 7.7.0 rebuilt and make install that instead. There might be an issue with ./configure script (didn't investigate, not sure)

/usr/local/include/pqxx/internal/stream_query.hxx:29:10: fatal error: pqxx/internal/gates/connection-stream_from.hxx: No such file or directory

**Comment by jtv** [comment]
Already being fixed!  See #657, and PRs #658 & #659.

**Comment by jtv** [comment]
@zalmoxis2019 do those updates fix the problem for you?  I hope to release 7.8.0 soon.

**Comment by jtv** [comment]
Meanwhile I have released 7.7.5 with just a few small fixes.  Any luck with that, @zalmoxis2019?

**Comment by jtv** [comment]
No news.  I'll close this ticket, and if there is still a problem, it will come up again.
