### ISSUE TITLE
Hi, does pqxx support automatic reconnection?

### ISSUE THREAD

**Issue by suppersam1** [jtv/libpqxx#673]
I want to reconnect when execute sql statement failed, how can i do this?

**Comment by jtv** [comment]
You'll have to handle that in your own code, and create a new `connection` object.  (And a new transaction, of course.)

**Comment by tt4g** [comment]
Maybe related #310

**Comment by Suppertian** [comment]
> You'll have to handle that in your own code, and create a new `connection` object. (And a new transaction, of course.)

I watched the content of #280 and it seems that when the connection times out or disconnects, using is_ open() will return 'broken_ connection'. Let me do a small experiment

**Comment by Suppertian** [comment]
> > You'll have to handle that in your own code, and create a new `connection` object. (And a new transaction, of course.)
> 
> I watched the content of #280 and it seems that when the connection times out or disconnects, using is_ open() will return 'broken_ connection'. Let me do a small experiment

I try to kill the process and then insert an SQL statement, pqxx will throw 'break'_ connection'. This makes it easy for me to reconnect. thanks a lot!

**Comment by Suppertian** [comment]
> Maybe related #310

thanks a lot!

**Comment by Suppertian** [comment]
> > > You'll have to handle that in your own code, and create a new `connection` object. (And a new transaction, of course.)
> > 
> > 
> > I watched the content of #280 and it seems that when the connection times out or disconnects, using is_ open() will return 'broken_ connection'. Let me do a small experiment
> 
> I try to kill the process and then insert an SQL statement, pqxx will throw 'break'_ connection'. This makes it easy for me to reconnect. thanks a lot!

By the way. is_open() still returns true when the connection is disconnected

**Comment by KayEss** [comment]
The best thing to do is to just try to issue your SQL and catch the exception and try again. `is_open` is really more like "was open the last time we tried anything and not explicitly closed". It's not particularly useful for trying to determine if the connection has just broken -- this is just a normal consequence of TCP connections work.
