### ISSUE TITLE
How query list or array in C++?

### ISSUE THREAD

**Issue by bayueqiankong** [jtv/libpqxx#674]
```sql
select label_name,name, introductions, applications , elements, status  from product where group_id =1 order by id desc;
```

![图片](https://user-images.githubusercontent.com/50512206/232754438-1f79d0c1-5475-4779-b9e0-7d41a1971ab1.png)

```cxx
std::string sql=fmt::format("select label_name,name, introductions, applications , elements, status  from product where group_id =1 order by id desc;");
auto result =tx.query(sql);

// applications , elements, status is list
```

questions:How  translate from result to `std::vector<std::string>` with C++？

**Comment by jtv** [comment]
I edited your question a bit to make it render better in Markdown.

It's not clear to me what kind of conversion you mean exactly.  SQL has array types, and libpqxx supports them, but I'm not seeing those here.

**Comment by bayueqiankong** [comment]
create table sql:
CREATE TABLE test2 (
	id varchar NULL,
	col1_list _varchar NULL,
	col2_list _int4 NULL,
	CONSTRAINT test2_pk PRIMARY KEY (id)
);
// col1_list and col2_list  is a array types,
table structure:
![图片](https://user-images.githubusercontent.com/50512206/232775773-105809fd-a07a-42d1-a5da-a5a77ff7db7f.png)


insert three rows(data):
![图片](https://user-images.githubusercontent.com/50512206/232767083-edeb2705-099c-42ac-809b-6f8a1be245fa.png)


sql query:(SELECT * FROM test2)
result:
![图片](https://user-images.githubusercontent.com/50512206/232776100-d7920fbe-fd88-4809-91d3-bd75c0a0fd3e.png)
![图片](https://user-images.githubusercontent.com/50512206/232776289-baabde7b-6994-4389-ad6a-0d58f1fa9b2d.png)

by C++：
std::string sql=“SELECT * FROM test2”；
auto result =tx.query(sql);

question:How print the result with C++? Coding,I need to translate the result.

it is wrong :
for(auto [id,col1_list,col2_list]:res.iter<std::string,std::vector<std::string>,std::vertor<int>>())
{
    // print
}

**Comment by jtv** [comment]
If they're array types, have a look in the header `<pqxx/array.hxx>`.

**Comment by bayueqiankong** [comment]
I do not know to using <pqxx/array.hxx>,there is not a demo or examples.

**Comment by tt4g** [comment]
Test code here (It is example): https://github.com/jtv/libpqxx/blob/7.7.5/test/unit/test_array.cxx

**Comment by bayueqiankong** [comment]
by the way,if it is json type,what do i need to do?Which demo  i look?

**Comment by tt4g** [comment]
Since you do not describe what problems using JSON type will cause, I am not sure what you want to know.
I answer on the assumption that you want to know how to convert between C++ types and PostgreSQL JSON types.

C++ strings can be cast (`::json` to JSON type, `::text` to TEXT type) on PostgreSQL SQL statements.

```cpp
auto result = tx.query("SELECT json_column::text FROM foo");
```

See also: [PostgreSQL: Documentation: 15: 8\.14\. JSON Types](https://www.postgresql.org/docs/15/datatype-json.html)

**Comment by jtv** [comment]
On the client side, you can use a JSON library of your choice to parse the JSON strings.

**Comment by bayueqiankong** [comment]
OK,thanks,if json type or array(_varch/_int4/_test .el), I can use:
#include "nlohmann/json.hpp"
using json = nlohmann::json;
......
......
std::string sql=fmt::format("select col_name1, to_json(col_name2) ,to_json(col_name3) ,col_name4::json from table_name;");
pqxx:result res=tx.query(sql);
for(auto [value1,value2,value3,value4]:res.iter<std::string,std::string,std::string,std::string>())
{
     json row;
      row["value1"]=value1;
      row["value2"]=json::parse(value2);
      row["value3"]=json::parse(value3);
      row["value4"]=json::parse(value4);
      //...print...//
}
