### ISSUE TITLE
warning STL4036: <ciso646> is removed in C++20

### ISSUE THREAD

**Issue by bka2004** [jtv/libpqxx#680]
We are getting this with a MSVC project using C++20/permissive-:

2>C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\ciso646(15,47): error C2220: the following warning is treated as an error
2>C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\include\ciso646(15,47): warning C4996: '_Header_ciso646': warning STL4036: <ciso646> is removed in C++20. You can define _SILENCE_CXX20_CISO646_REMOVED_WARNING or _SILENCE_ALL_CXX20_DEPRECATION_WARNINGS to suppress this warning.

We do suppress it for now, but it would be nice if the libpq(xx) headers could check for current settings and not include this, if it's not needed.

I found something similar in another repo, and they fixed it somehow (didn't check the details):
https://github.com/nlohmann/json/issues/2089

**Comment by jtv** [comment]
It's a known problem.  The code actually only includes that header _if it's actually available,_ but Visual Studio fails to notice that and issues the warning anyway.

It suggest some macros we could set to silence the warning, but those didn't work when I tried them.

So if you know of an actual way to silence this warning, I'd love to know it.  Eventually of course I'll just remove the `#include` and the warning will disappear.

**Comment by Sil3ntStorm** [comment]
Any idea when we can get a release with this fix?

**Comment by jtv** [comment]
@Sil3ntStorm I'm working my way towards a pretty major release...  Could be soon if you need it, but I'll need some solid feedback on #707 first, unrelated to this.

**Comment by Sil3ntStorm** [comment]
More of a curiosity question as I found this issue and saw it was already fixed when converting to C++20 compilation and looking through all the warnings produced. It would simply allow me to not have to `#pragma warning` chain the pqxx include.
