### ISSUE TITLE
binary_cast for other data types which are not supported

### ISSUE THREAD

**Issue by battalian** [jtv/libpqxx#684]
As per the [docs](https://libpqxx.readthedocs.io/en/7.7.5/a01430.html), binary_cast only supports datatypes that are of size 1 byte.

How to convert `vector<int>` to `basic_string<std::byte>`, Is there any util for doing that in pqxx?

I tried accessing each byte of information for int and appending it to  `basic_string<std::byte>`. I was able to create the basic_string binary object, But I have copied data multiple times in memory doing so.

Is there any better way for doing the above thing efficiently?

**Comment by jtv** [comment]
I wouldn't cast a block of `int` to a block of `std::byte`, for two reasons:
1. I'm not sure you can do it without eliciting _undefined behaviour_ — meaning that there is no guarantee that the compiler will produce the machine code you want.  There are strong technical reasons for these rules.
2. If you take some `int` and store them into the database like this, they may not work on another client running on a different system.  The other system may have the bytes in a different order, or have a different number of bytes.

**Comment by jtv** [comment]
So generally, it makes more sense to translate the numbers to some kind of text format.  This is in fact what libpqxx does all the time when exchanging values with the database.

**Comment by battalian** [comment]
The [docs](https://libpqxx.readthedocs.io/en/7.7.5/a01430.html) states that anything which is a block of contiguous `std::byte` type can be used. `vector<int>` type is nothing but contiguous bytes, So libpqxx should support storing the vector rather than converting it to text format?

**Eliciting undefined behavior**: Won't this be a problem even if we send some kind of text format?

**Comment by jtv** [comment]
A "byte" is not the same thing as a "`std::byte`".  The data consists of bytes, yes, but it's up to the host system to decide how, and you can't necessarily get at the individual bytes in a way that won't confuse the compiler.

I don't see how converting to a text format would elicit undefined behaviour, unless you do it wrong.  For instance you can convert an integer to text by figuring out the first digit and outputting it, then dividing by 10, doing the next digit, and so forth.  You can do that without any undefined behaviour.

Taking an integer value and reading its raw bytes is harder to get right without breaking the language rules - in fact I don't know off the top of my head how you'd do it.

**Comment by battalian** [comment]
Along similar lines, I have one more use case of storing `Matrix<typename Scalar, int RowsAtCompileTime, int ColsAtCompileTime>`.

This matrix can be interpreted as follows `reinterpret_cast<char*>(matrix.data())`. The eventual data pointer is of `char*` type. 

So, pqxx supports storing & retrieving the matrix data without any custom data conversions right?
