### ISSUE TITLE
make check error

### ISSUE THREAD

**Issue by slvno** [jtv/libpqxx#69]
Hello, Jeroen and Ray!

I compiled your library. I'm having the following error
when creating and check libpqxx version 6.1.0 on linux and windows:

make check 
...
/bin/sh: ./config/test-driver: No such file or directory

CentOS release 6.9 (Final)
Linux localhost.localdomain 2.6.32-696.20.1.el6.x86_64 #1 SMP Fri Jan 26 17:51:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[slava@localhost ~]$ scl enable devtoolset-6 bash

[slava@localhost ~]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-6/root/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-6/root/usr --mandir=/opt/rh/devtoolset-6/root/usr/share/man --infodir=/opt/rh/devtoolset-6/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-6.3.1-20170216/obj-x86_64-redhat-linux/isl-install --enable-libmpx --with-mpc=/builddir/build/BUILD/gcc-6.3.1-20170216/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 6.3.1 20170216 (Red Hat 6.3.1-3) (GCC) 

[slava@localhost ~]$ scl enable python27 bash

[slava@localhost ~]$ python --version
Python 2.7.13

export CXXFLAGS=-I/usr/pgsql-10/include 
export PG_CONFIG=/usr/pgsql-10/bin/pg_config
export PGDATABASE=test_schema
export PGHOST=localhost
export PGPORT=5432
export PGUSER=test
export PGPASSWORD=***

export LC_MESSAGES=C

./configure --enable-static
make

[slava@localhost libpqxx-6.1.0]$ make  check
...
Running: test_094
(Expected) Transactor outcome in doubt.

Running: test_abort
Ran 71 test(s).
PASS: runner
=============
1 test passed
=============
make[3]: Leaving directory '/home/slava/projects/libpqxx-6.1.0/test'
make[2]: Leaving directory '/home/slava/projects/libpqxx-6.1.0/test'
make[1]: Leaving directory '/home/slava/projects/libpqxx-6.1.0/test'
Making check in tools
make[1]: Entering directory '/home/slava/projects/libpqxx-6.1.0/tools'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/slava/projects/libpqxx-6.1.0/tools'
Making check in win32
make[1]: Entering directory '/home/slava/projects/libpqxx-6.1.0/win32'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/slava/projects/libpqxx-6.1.0/win32'
Making check in config
make[1]: Entering directory '/home/slava/projects/libpqxx-6.1.0/config'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/slava/projects/libpqxx-6.1.0/config'
Making check in doc
make[1]: Entering directory '/home/slava/projects/libpqxx-6.1.0/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/slava/projects/libpqxx-6.1.0/doc'
make[1]: Entering directory '/home/slava/projects/libpqxx-6.1.0'
make  check-TESTS
make[2]: Entering directory '/home/slava/projects/libpqxx-6.1.0'
make[3]: Entering directory '/home/slava/projects/libpqxx-6.1.0'
/bin/sh: ./config/test-driver: No such file or directory
Makefile:922: recipe for target 'tools/lint.log' failed
make[3]: *** [tools/lint.log] Error 127
make[3]: Leaving directory '/home/slava/projects/libpqxx-6.1.0'
Makefile:901: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/slava/projects/libpqxx-6.1.0'
Makefile:1135: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/slava/projects/libpqxx-6.1.0'
Makefile:681: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

The same error appears in windows on mingw64

/bin/sh: ./config/test-driver: No such file or directory.

Thank you so much!

**Comment by jtv** [comment]
This is something I keep forgetting to test.  I want people to be able to run the configure script as found in the repo and then build the library, without having to run autogen.sh (which generates the configure script and many other files).  Maybe that's an abnormal thing to do, and it introduces a lot of churn in the git history, but it seemed sensible.  To make that work, evidently I needed to commit test-driver to the repo.

Does it work for you now?  On my end I can now `git clean -f -d -x && ./configure && make check` without problems.

**Comment by slvno** [comment]
Hello! It works.  I used the library archive before. The git repository contains the required test-driver file. To build in windows, I used the flag CXXFLAGS="-D_WIN32_WINNT=0x502". Thanks so much.

**Comment by jtv** [comment]
Glad to hear it works.  By the way, Ray is sadly no longer alive.  He is still missed.  :-(

**Comment by slvno** [comment]
Sorry, didn't know. Ray would like to hear his friend remember him.
