### ISSUE TITLE
Building and installing with cmake for Windows is causing countless errors (Postgres 15, msvc)

### ISSUE THREAD

**Issue by cgodlike20** [jtv/libpqxx#691]
It is my first time with libpqxx on Windows, so it's most likely a mistake on my end . I'm following installation steps from "**BUILDING-cmake.md**" provided under "**Building and installing libpqxx yourself**".

Note: Had to update my `PostgreSQL_KNOWN_VERSIONS` in `/cmake-3.26/Modules/FindPostgreSQL.cmake`, so it could find Postgres 15.

**1. Configure**
After cloning source tree, i ran cmake command with following result:

`C:\Libpqxx\build>cmake C:\Libpqxx\libpqxx-master`
`-- Building for: Visual Studio 17 2022`
`-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.`
`-- The CXX compiler identification is MSVC 19.35.32217.1`
`-- Detecting CXX compiler ABI info`
`-- Detecting CXX compiler ABI info - done`
`-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools``/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`-- Found PostgreSQL: C:/Program Files/PostgreSQL/15/lib/libpq.lib (found version "15.3")`
`-- Looking for poll`
`-- Looking for poll - not found`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`-- Generating config.h`
`-- Generating config.h - done`
`-- Configuring done (20.6s)`
`-- Generating done (0.1s)`
`-- Build files have been written to: C:/Libpqxx/build`

Seems fine

**2. Compile**
All hell breaks loose after invoking: 
`C:\Libpqxx\build>cmake --build C:\Libpqxx\build`

Multiple syntax errors, undeclared identifiers etc. with most of them found in:
**Libpqxx/libpqxx-master/include/pqxx/internal/encodings.hxx**
and
**Libpqxx/build/src/pqxx.vcxproj**

Can't even copy any error in particular as i get 2k+ errors.

**3. Install**
Obviously this is not working, with the following result:

`C:\Libpqxx\build>cmake --install C:\Libpqxx\build --prefix C:\Libpqxx\libpqxx`
`-- Install configuration: "Release"`
`-- Installing: C:\Libpqxx\libpqxx/lib/cmake/libpqxx/libpqxx-config.cmake`
`-- Installing: C:\Libpqxx\libpqxx/lib/cmake/libpqxx/libpqxx-config-version.cmake`
`-- Installing: C:\Libpqxx\libpqxx/lib/cmake/libpqxx/libpqxx-targets.cmake`
`-- Installing: C:\Libpqxx\libpqxx/lib/cmake/libpqxx/libpqxx-targets-release.cmake`
`CMake Error at src/cmake_install.cmake:39 (file):`
`  file INSTALL cannot find "C:/Libpqxx/build/src/Release/pqxx.lib": File`
`  exists.`
`Call Stack (most recent call first):`
`  cmake_install.cmake:76 (include)`

I appreciate any help. Should have done the project using wsl, but i just couldn't help torturing myself and now i kinda need to know what might be the issue. Cheers.

**Comment by tt4g** [comment]
What should be passed to the `cmake --build <PATH>` command is the CMake build working directory generated by the `cmake <PATH>` command.

It looks like you are executing the `cmake C:\Libpqxx\libpqxx-master` command first, but the log message shows that `C:/Libpqxx/build` is the CMake build directory, so something is wrong.

> -- Build files have been written to: C:/Libpqxx/build

If `C:\Libpqxx\libpqxx-master` is the libpqxx source code directory, you should be able to build it with the following command.

```shell
$ cd C:\Libpqxx\libpqxx-master

# Generate build files.
$ cmake .

# Build libpqxx.
$ cmake --build . --config Release

# Install libpqxx.
$ cmake --install .
```

> **Note**
> The `--config Release` option is added because it is better to do a release build of the libraries to be installed on the machine.
