### ISSUE TITLE
[Question] Connection-pool in libpqxx

### ISSUE THREAD

**Issue by atari83** [jtv/libpqxx#699]
Hello!
I'm new on using libpqxx library sorry if my questions are basic.
I just wanted to know if libpqxx supports connection-pool functionally internally, or is it left to developer for implementation ?
And if there is no connection-pool in the library, is there any good implementation that you would suggest  to be used ?

Thanks.

**Comment by KayEss** [comment]
You should look at pgpool and pgbouncer

**Comment by jtv** [comment]
There's no built-in connection pooling, but there are stand-alone connection pools.  These are transparent proxies: to libpqxx (or any other client library) they look like they're connecting directly to postgres itself.  I hear good things about pgbouncer for example.

**Comment by atari83** [comment]
Thank you very much for responses :) I'll take a look at them.
