### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by vorlock** [jtv/libpqxx#7]
Hi Jeroen

I'm a Debian maintainer for this lib and long time (2-3y) ago we exchanged some emails related to 5.0.
I see it' been released yey ;-)
Thx a lot for your continuous work on libpqxx.

Also I'd like to ask you to tag 5.0.1 as a release please. It'd make much easier to link it with all the tool chain we're using for building, testing etc.. Actually I think that all libpqxx users will benefit from it been tagged and maybe even signed ;-P

Unfortunately 5 won't make into Stretch but I'll try to upload it to experimental as soon as I can.

Anyway once more thx a lot for your great work.

**Comment by jtv** [comment]
Thanks — I'll try to remember to tag!  I don't think I'll maintain multiple releases in parallel any more though.  The whole project just got bogged down in too much overhead.

**Comment by vorlock** [comment]
Mate it's fine with me to just maintain one release, I'm doing the same :-)

So, could you pls tag already released 5.0.1?

**Comment by drstapletron** [comment]
Hi.  Sorry for the slightly unrelated post., but I'm looking for information on version compatibility.  How can I tell if pqxx version 4.0 will work with postgres version 9.5?  I can't find this anywhere online.

**Comment by jtv** [comment]
@drstapletron: I think it should, but the best way to find out is to try.

**Comment by jtv** [comment]
Lesson learned: git's awful UI by default leaves out tags when you push.  :(  Fixed now.

**Comment by vorlock** [comment]
Thx a lot
