### ISSUE TITLE
Trying to use libpqxx in a qmake project in QT

### ISSUE THREAD

**Issue by Mergpijp** [jtv/libpqxx#700]
Hello,

I use MSVC 2019 qt and I installed Windows SDK and visual studio 2019 16 community edition. I build with cmake and configured a release.

In my .pro file in QT I added the following:

`INCLUDEPATH += "C:/Users/3DLab/Documents/projects/libpqxx_b_2019/include"`
`LIBS += -L"C:/Users/3DLab/Documents/projects/libpqxx_b_2019/src/Release" -lpqxx`

If I try to build and run my project in QT i get:

C:\Users\3DLab\Documents\projects\test_pms\mainwindow.cpp:16: error: C1083: Cannot open include file: 'libpqxx/libpqxx': No such file or directory

I tried running as administrator but nothing seems to work.
Help is much appreciated.

**Comment by Mergpijp** [comment]
I tried libpqxx but it should be pqxx/pqxx I solved it by changing the include path to the actual build from pqxx I had the wrong folder. However now when I am making a connection string conn:

`        // Connection parameters
        std::string host = "localhost";
        std::string port = "5432";
        std::string database = "mydatabase";
        std::string user = "myuser";
        std::string password = "mypassword";

        // Create the connection string
        std::string connString = "host=" + host + " port=" + port + " dbname=" + database + " user=" + user + " password=" + 
        password;

        // Establish a connection to the database
        pqxx::connection conn(connString);`

The exe crashes without further message.

**Comment by Mergpijp** [comment]
I solved it! Had the wrong postgres username all the time... Hope everything works now.

**Comment by jtv** [comment]
(@Mergpijp I edited your comment slightly for formatting.  Code block syntax isn't immediately obvious.)

The _real_ mistake here I think was not catching exceptions from the `pqxx::connection` constructor.  If you catch it, you can print the error.  There will be other failures, e.g. the network might break, and the user will want to know what it was.

**Comment by Mergpijp** [comment]
Yes that is it I am new to C++ but I saw the try things around and removed it..

**Comment by jtv** [comment]
@Mergpijp  it's true that you don't _really need_ them, but if there's an exception with no `try` block to handle it, your application will just crash.
