### ISSUE TITLE
await_notification Issues

### ISSUE THREAD

**Issue by jrch2k20** [jtv/libpqxx#703]
Hi, been using this great library and finally reached the notifications part of my app but i noticed the next:

Once i receive the first notification (which works great btw) every 10 seconds after that the await_notification get called again ad infinitum and is driving me insane since i cannot seem to find any timer enabled either in postgresql.conf or my code (all timeout i can find are force set to 0).

not sure if you have encountered this issue before??

Thx very much for timer and great work

**Comment by jtv** [comment]
Thank you for the kind words.  I'm having some trouble picturing what you're describing...  Perhaps you can boil it down to a minimal compilable example?

**Comment by jrch2k20** [comment]
it will take me a while to get a working example but maybe this help clarify the issue:

if i understand this right, await notification should block the loop until a new pg_notify is emitted from postgresql but instead after receiving the first notification the await_notifications unblock the loop around every 10 secs.

i will admit that i'm not sure if this approach is right, notifications documentation is not very clear here so i'm assuming it works similar to redis(and others) notifications

`auto test_function(std::atomic<bool>& loop_control) -> void {
do {
        my_postgresql_conn.await_notification(); 
        My code ....

    } while (loop_control.load(std::memory_order_acquire) == true);
}
`

I noticed in the code await_notifications call pqxx::internal::wait_fd with a value of 10 which is around the time the loop keep releasing but my epoll fu is rusty so i'm not sure if the issue lies there.

i'm using latest git build on Archlinux with postgresql 15

**Comment by jrch2k20** [comment]
mmm thinking about about it, should i create the connection inside the loop instead of using an existing connection since it seems the code only blocks until the fd is active and start the polling? aka this instead?

```
auto test_function(std::atomic<bool>& loop_control) -> void {
do {
       pqxx::conn my_conn(...);
        my__conn.await_notification(); 
        My code ....
        my_conn.disconnect();
    } while (loop_control.load(std::memory_order_acquire) == true);
}
```

**Comment by jtv** [comment]
Oh!  Right, you've got to be prepared for `await_notification()` to wake up from time to time even when there are no notifications.  You can also call `await_notification()` with a custom timeout (in seconds and microseconds), but there is no version that just waits forever if there's no notification.

There's no need to keep creating new connections — that just slows things down.  If you ever lose the connection (which also happens sometimes, e.g. in the face of network problems or a server restart), then that's a good time to start a new connection.
