### ISSUE TITLE
Compile error - error: invalid use of ‘this’ at top level

### ISSUE THREAD

**Issue by wlynn00** [jtv/libpqxx#705]
when run the code ```make -j8```，get error message as follow:

In file included from ../include/pqxx/pqxx:17:0,
                 from rmlo.cxx:4:
../include/pqxx/range.hxx:143:24: error: invalid use of ‘this’ at top level
     noexcept(noexcept(*this->value() == *rhs.value()))
                        ^~~~
../include/pqxx/range.hxx:154:24: error: invalid use of ‘this’ at top level
     noexcept(noexcept(*this == rhs))
                        ^~~~
../include/pqxx/range.hxx:266:23: error: invalid use of ‘this’ at top level
     noexcept(noexcept(this->lower_bound() == rhs.lower_bound()) and noexcept(
                       ^~~~
../include/pqxx/range.hxx:267:7: error: invalid use of ‘this’ at top level
       this->upper_bound() == rhs.upper_bound()) and noexcept(this->empty()))
       ^~~~
../include/pqxx/range.hxx:267:62: error: invalid use of ‘this’ at top level
       this->upper_bound() == rhs.upper_bound()) and noexcept(this->empty()))
                                                              ^~~~
../include/pqxx/range.hxx:275:24: error: invalid use of ‘this’ at top level
     noexcept(noexcept(*this == rhs))
                        ^~~~
../include/pqxx/range.hxx:315:25: error: invalid use of ‘this’ at top level
     noexcept(noexcept((*this & other) == other))
                         ^~~~
make[1]: *** [Makefile:396：rmlo.o] 错误 1
make[1]: 离开目录“/home/ubuntu/ROOT/ShadeWatcher/lib/libpqxx/tools”
make: *** [Makefile:642：all-recursive] 错误 1

**Comment by jtv** [comment]
You may be compiling an older C++ version.  Current libpqxx requires C++17 or newer.

Assuming you're using gcc or clang, try setting `-std=c++17` or `-std=c++20` on the command line.

**Comment by wlynn00** [comment]
> You may be compiling an older C++ version. Current libpqxx requires C++17 or newer.
> 
> Assuming you're using gcc or clang, try setting `-std=c++17` or `-std=c++20` on the command line.

my gcc version is ```Ubuntu 7.5.0```. The command line I'm using is ```./configure --disable-documentation --prefix=$LIB_INSTALL_PATH CXXFLAGS=-std=c++17```, and execution result is as follows, Is there any problem?

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether make sets $(MAKE)... (cached) yes
checking for mkdir... /usr/bin/mkdir
checking for doxygen... no
checking for dot... no
checking whether to enable maintainer-specific portions of Makefiles... no
checking maintainer mode... 
checking audit... 
checking suggest... 
checking for sufficient C++ language/library level... yes
checking g++ visibility attribute... yes
checking g++ pure attribute... yes
checking __cxa_demangle... yes
checking concepts... no
checking std::span... no
checking for multidimensional subscript operator support... no
checking for strerror_r()... yes
checking for strerror_s()... no
checking for std::chrono::year_month_day etc... no
checking attributes "likely" and "unlikely".... no
checking for C++17 charconv integer conversion... no
checking for C++17 charconv floating-point conversion... no
checking for full thread_local support... yes
checking for std::this_thread::sleep_for... yes
checking for std::cmp_greater, std::cmp_less_equal, etc... no
checking for poll()... yes
checking for pkg-config... /usr/bin/pkg-config
checking for pg_config... /usr/bin/pg_config
configure: finding PostgreSQL headers using -I/usr/include/postgresql
configure: using PostgreSQL libraries at /usr/lib/x86_64-linux-gnu
checking for libpq-fe.h... yes
checking for ability to compile source files using libpq... yes
checking for PQexec in -lpq... yes
checking for usable std::filesystem::path... no
checking for C++23 std::unreachable()... no
checking whether we need a link option for <filesystem> support... 
checking that type of libpq's Oid is as expected... yes
checking whether make sets $(MAKE)... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config/Makefile
config.status: creating doc/Makefile
config.status: creating doc/Doxyfile
config.status: creating src/Makefile
config.status: creating test/Makefile
config.status: creating tools/Makefile
config.status: creating include/Makefile
config.status: creating include/pqxx/Makefile
config.status: creating libpqxx.pc
config.status: creating compile_flags
config.status: creating include/pqxx/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing configitems commands

**Comment by jtv** [comment]
@wlynn00 have you been able to try with a newer compiler?

**Comment by wlynn00** [comment]
> @wlynn00 have you been able to try with a newer compiler?

yes, I have successfully compliled！

**Comment by jtv** [comment]
Great.  I'll close the ticket then.
