### ISSUE TITLE
Unsupported server version

### ISSUE THREAD

**Issue by daniilrozanov** [jtv/libpqxx#708]
When i run my program, it terminates with exception
```
terminate called after throwing an instance of 'pqxx::feature_not_supported'
  what():  Unsupported server version; 9.0 is the minimum.
```
I checked my PostgreSQL version by `select version()` and it prints:
```
version                                                                 
----------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
```

I also reinstall `libpq` directly from [https://ftp.postgresql.org/pub/source/v14.8/](url), build this separately and include to my project, that do not helps. Before that i used `libpq` from `apt install libpq-dev`(doesn't works too).

What kind of problem it could be?

EDIT. Before installation i ran `make check` for `libpqxx` and it worked succesfully.

**Comment by tt4g** [comment]
Have you checked that you have the correct PostgreSQL server connected?
Check the host of the connection string.

**Comment by jtv** [comment]
I agree with @tt4g (as usual, to be honest :-) )  — this sounds to me like you've got connections to two different databases somehow.  That can happen especially when you're dealing with a bunch of containers.  Did you run `psql` from exactly the same environment where you run your own application, and with exactly the same connection parameters?  Is it possible that you've got an OS package running postgresql plus the one you build yourself on a different port or address?

(On a sidenote...  If this exception ends up calling `terminate()`, that probably means that your code does not catch exceptions at the highest level.  It's generally a good idea to catch exceptions and print the errors yourself.  But it's probably not relevant to this problem.)

**Comment by daniilrozanov** [comment]
Excuse me, this is my fault). I just tried to connect to another database, which has less than 9 version. I am closing issue
