### ISSUE TITLE
`result::errorposition()` might throw while being declared `noexcept`

### ISSUE THREAD

**Issue by sth** [jtv/libpqxx#71]
While wondering why different compiler options wouldn't warn about problems like #68, I ran cppcheck over the library and (in addition to #70) it's most significant finding is:

> [result.cxx:361]: (error) Exception thrown in function declared not to throw exceptions.

https://github.com/jtv/libpqxx/blob/933e2b5ce57b93fa1be05ed8a374d32bcc475fa6/src/result.cxx#L353-L364

`from_string()` ends up calling [`from_string_signed()`][fss] which throws on invalid inputs.

Probably the `noexcept` should simply be removed from `errorposition()`.

[fss]: https://github.com/jtv/libpqxx/blob/933e2b5ce57b93fa1be05ed8a374d32bcc475fa6/src/strconv.cxx#L97

**Comment by jtv** [comment]
Absolutely right.  Committing a fix.
