### ISSUE TITLE
Question: What version of PostgreSQL is this compatible with? 

### ISSUE THREAD

**Issue by cyrusbehr** [jtv/libpqxx#712]
In the readme, it states:

> Compiling this package requires PostgreSQL to be installed -- or at least the C headers and library for client development. The library builds on top of PostgreSQL's standard C API, libpq, though your code won't notice.

I imagine that each version of PostgreSQL has some differences in the C API. I'm therefore wondering what version of PostgreSQL the latest release (7.7.5) is compatible with. I am using PostgreSQL 12 at the moment (and am unable to upgrade). I have been using libpqxx 7.0.7. Can I upgrade to 7.7.5?

**Comment by jtv** [comment]
Yes.  It should work with all PostgreSQL versions that the PostgreSQL maintainers themselves support.  Right now I think the minimum version is 10, and next year, 12.

Once your PostgreSQL version is no longer supported, newer libpqxx releases will _probably_ still work with the server.  But it becomes less likely
that libpqxx will work with the libpq that came with that PostgreSQL version.

**Comment by cyrusbehr** [comment]
Ok thanks for the answer.
