### ISSUE TITLE
libpqxx 7.8.0 build issue

### ISSUE THREAD

**Issue by chenrui333** [jtv/libpqxx#715]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
checking build system type... Invalid configuration `aarch64-apple-darwin22.5.0': machine `aarch64-apple' not recognized
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5639345753/job/15274512125
relates to Homebrew/homebrew-core#137375

**Comment by KayEss** [comment]
Is this new with this release? It looks like the build is using autoconf, does cmake understand the new apple hardware better?

**Comment by chenrui333** [comment]
maybe, but I think we use automake might be because of the pc files.

**Comment by chenrui333** [comment]
> Are you able to try a manual build? I don't think any of us have access to new Mac hardware to try this on

you dont need a mac machine, the github action hosted runner plus tmate action would help with debugging, https://github.com/chenrui333/github-action-test/blob/main/.github/workflows/brew-debug.yml

I can debug a bit as well.

**Comment by jtv** [comment]
It does look like autoconf or some other piece of infrastructure has trouble figuring out the system.  Turns out it was time to re-generate config.sub.  An annoying chore that _of course_ I forget to do.

See #716 for the fix.

**Comment by jtv** [comment]
@chenrui333 does that latest commit on `master` fix it for you?

**Comment by chenrui333** [comment]
let me give it a shot, thanks for the re-generation.

**Comment by chenrui333** [comment]
considering the build is resolved, gonna close this issue for now. It would be good to have a new release for the build script patch.
