### ISSUE TITLE
How to execute commands outside of a transaction

### ISSUE THREAD

**Issue by fukanchik** [jtv/libpqxx#717]
I see no way to call `exec()` directly on `pqxx::connection`.

However, if I do
``` 
pqxx::connection conn{"host=localhost dbname=postgres replication=database"};
pqxx::transaction tx{conn};
pqxx::result r = tx.exec("BASE_BACKUP (LABEL='mylabel')");

```

I get an error:
    `what():  ERROR:  BASE_BACKUP cannot run inside a transaction block`

I tried to `grep -Ri BASE_BACKUP` in libpqxx sources but there was nothing.

So is there a way to exec outside of a transaction?

**Comment by tt4g** [comment]
Use `pqxx::nontransaction`.

Doc: https://libpqxx.readthedocs.io/en/stable/a01082.html#details
Test: https://github.com/jtv/libpqxx/blob/5934bbddaad26227b75b9ce71f3b431398940e66/test/test20.cxx#L50-L61

**Comment by fukanchik** [comment]
Thanks, this worked ok.
