### ISSUE TITLE
How to use SFINAE with v7 string_traits?

### ISSUE THREAD

**Issue by zencak-ica** [jtv/libpqxx#718]
In v6 we had `template<typename T, typename = void> struct string_traits`, which allowed specializations which could be constrained with SFINAE. In v7, there is only `template<typename TYPE> struct string_traits`, which leaves no way to leverage SFINAE (that I know of).
Is there some other way I could specify string_traits for an entire class of types?

**Comment by jtv** [comment]
Concepts I guess..?

(Sorry I'm a bit under the weather, may not be thinking too clearly.)

**Comment by zencak-ica** [comment]
Unfortunately, I can't use C++20 yet, so no concepts for me. Although I guess once v8 comes, c++20 will be required.

**Comment by jtv** [comment]
That is correct.  Perhaps you can sneak your SFINAE conditions into regular parameters and/or return types, instead of putting them into template parameters?

**Comment by zencak-ica** [comment]
That works for functions, but string_traits is a structure, which has neither of those.

**Comment by jtv** [comment]
I don't understand what you mean...  `string_traits` is a struct template.  What's inside?  Template functions.  If you can conditionally disable those, I think that will have much the same effect.

**Comment by zencak-ica** [comment]
Unfortunately, when I tried it didn't work:
* `template <typename T> std::enable_if_t<std::is_integral_v<T>, zview> string_traits<T>::to_buf(char *begin, char *end, T const &value) {}`
complained that `Return type of out-of-line definition of 'pqxx::string_traits::to_buf' differs from that in the declaration`
* `template <typename T> zview string_traits<T>::to_buf(char *begin, char *end, std::enable_if_t<std::is_integral_v<T>, T> const &value) {}` got error `Out-of-line definition of 'to_buf' does not match any declaration in 'string_traits<TYPE>'`
* `template <typename T> zview string_traits<std::enable_if_t<std::is_integral_v<T>, T>>::to_buf(char *begin, char *end, T const &value) {}` got error `Nested name specifier 'string_traits<std::enable_if_t<std::is_integral_v<T>, T>>::' for declaration does not refer into a class, class template or class template partial specialization`
* `template <typename T, typename = std::enable_if_t<std::is_integral_v<T>, T>> zview string_traits<T>::to_buf(char *begin, char *end, T const &value) {}` got error `Too many template parameters in template redeclaration`

Would you please provide an example of how to do it correctly?

**Comment by jtv** [comment]
Are you trying to define string conversions for _all integral types?_  That's going to clash with the conversations that libpqxx already implements.

Three of those four errors are saying "this function has a different signature than in its declaration."  That seems appropriate if you were trying to override the existing specialisations.

So let's look at a more basic question first: what is the purpose of the specialisations you're trying to compile?

**Comment by zencak-ica** [comment]
No, I am not. I am trying to define it for my types for which I have defined a string conversion function, `std::is_integral_v` was just used for the sake of example. When done with a different traits value, the errors are exactly the same, so I didn't think it particularly relevant.

**Comment by jtv** [comment]
It does still sound to me like you may have added the `enable_if` in the function definitions but not in the declarations, or the other way around, or had some other slight difference between the definitions and the declarations.

Here's an example that works for me if I set `enabled = true` but fails to compile if I set `enabled = false`:
```cxx
#include <type_traits>
#include <pqxx>

namespace pqxx
{
// Some sample type.
struct foo{int x;};

// Some condition to control whether the string conversion should be enabled.
constexpr int enabled = false;

template<> struct string_traits<foo>
{
  static constexpr bool converts_to_string{enabled};
  static constexpr bool converts_from_string{enabled};

  [[nodiscard]] static zview
  to_buf(std::enable_if_t<enabled, char *> begin, char *end, foo const &value)
  {
    return string_traits<int>::to_buf(begin, end, value.x);
  }

  static char *into_buf(
    std::enable_if_t<enabled, char *>begin, char *end, foo const &value)
  {
    return string_traits<int>::into_buf(begin, end, value.x);
  }

  [[nodiscard]] static foo from_string(
    std::enable_if_t<enabled, std::string_view> text)
  {
    foo f;
    f.x = string_traits<int>::from_string(text);
    return f;
  }

  [[nodiscard]] static std::size_t size_buffer(
    std::enable_if_t<enabled, foo> const &value) noexcept
  {
    return string_traits<int>::size_buffer(value.x);
  }
};

template<> struct nullness<foo>
{
  /// Does this type have a null value?
  static constexpr bool has_null{false};

  /// Is this type always null?
  static constexpr bool always_null{false};

  /// Is @c value a null?
  static constexpr bool is_null(foo const &) { return false; }
};
}
```

**Comment by zencak-ica** [comment]
This indeed works, but the `enable_if` has no purpose, as it is just a simple specialization for a single type. I still don't see how I might extend that if, building on your example, I added types
```c++
struct bar {int x;};
struct baz {char *x};
```
and wanted the specialization to only work with `foo` and `bar`, but not `baz`. With an `enable` type parameter on the struct (as `struct nullness` has), I could just declare the struct as
```c++
template <typename T>
struct string_traits<T, std::enable_if_t<std::is_same_v<int, decltype(T::x)>> {
  //impl
};
```
But without it, I don't know how to change it from `string_traits<foo>` to something that can handle multiple (but not all) types.

**Comment by jtv** [comment]
Argh.  Right.  I can't think of a way to do that.  :-(  Best approximation I have is to define `string_traits` secialisations using a template base class — that still requires you to name each specialisation individually.  It's just down to a single line of code per type.

**Comment by jtv** [comment]
@zencak-ica any progress on this?

**Comment by zencak-ica** [comment]
Well, I didn't find anything better than inheriting from a common base class for every specialization. I'm afraid that unless you add some sort of `enable` template param in a future version, it's the best that can be done.

**Comment by jtv** [comment]
I'm sorry that this affected you like this.  I wasn't expecting something like this to come up so close to the transition to C++20 and concepts.
