### ISSUE TITLE
msys2+mingw64 build hangs there (win2019)

### ISSUE THREAD

**Issue by iihero** [jtv/libpqxx#719]
I'm using msys2 + mingw64 (latest) to build libpqxx: 

Administrator@windev- MINGW64 ~
# cpp --version
cpp.exe (Rev7, Built by MSYS2 project) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Below is my related config: 
export PATH=$PATH:/c/tools/pgsql/15.3.ssl/bin
./configure --enable-shared=yes --enable-static=no --with-postgres-include=/c/tools/pgsql/15.3.ssl/include --with-postgres-lib=/c/tools/pgsql/15.3.ssl/lib --prefix=/c/tools/pgsql/15.3.ssl/libpqxx7.5

....
At last it hangs at:
libtool: compile:  g++ -DHAVE_CONFIG_H -I../include -I../include -I/c/tools/pgsql/15.3.ssl/include -I/c/tools/pgsql/15.3.ssl/include -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -MT wait.lo -MD -MP -MF .deps/wait.Tpo -c wait.cxx  -DDLL_EXPORT -DPIC -o .libs/wait.o
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2 -fvisibility=hidden -fvisibility-inlines-hidden -release 7.8 -rpath /c/tools/pgsql/15.3.ssl/libpqxx-shapshot/lib  -L/c/tools/pgsql/15.3.ssl/lib -no-undefined -o libpqxx.la -rpath /c/tools/pgsql/15.3.ssl/libpqxx-shapshot/lib array.lo binarystring.lo blob.lo connection.lo cursor.lo encodings.lo errorhandler.lo except.lo field.lo largeobject.lo notification.lo params.lo pipeline.lo result.lo robusttransaction.lo sql_cursor.lo strconv.lo stream_from.lo stream_to.lo subtransaction.lo time.lo transaction.lo transaction_base.lo row.lo util.lo version.lo wait.lo  -lpq -lws2_32

I tried the branch: 7.5, 7.6,7.7,  all has the similar result.

**Comment by jtv** [comment]
That's unusual.  And hard to debug, since this is all standard third-party Software.

Was it still using CPU?  For how long did you wait?  Could there be a slow or failing resource such as a network filesystem, or a physical disc problem?  Did you try libpqxx 7.8.1, which has updated versions of some of these scripts?

**Comment by iihero** [comment]
Dear jtv,
I found the reason now.  
It's caused by the running user Administrator@windev.  
I just compared the same build instruction with that in the other machine,  the other machine can work.
Finally, I run the msys2 (mingw) with non-Administrator user,  it will not hang now.
Really very strange.  

Thanks a lot.

**Comment by jtv** [comment]
Weird...
