### ISSUE TITLE
Quetion: `PQXX_HAVE_RANGES`

### ISSUE THREAD

**Issue by tt4g** [jtv/libpqxx#721]
There is a source code that confirms that `PQXX_HAVE_RANGES` macro is defined that seems to have the same role as the other `PQXX_HAVE_***` macros.
However, it does not appear that this macro is defined in `config-tests`.

https://github.com/jtv/libpqxx/blob/bc7d3d1807adfcb9c967167a8a34219d94809acb/include/pqxx/blob.hxx#L26-L28

https://github.com/jtv/libpqxx/blob/bc7d3d1807adfcb9c967167a8a34219d94809acb/include/pqxx/strconv.hxx#L29-L31

Is this macro unnecessary?

**Comment by jtv** [comment]
Thank you for spotting that.  Yes, it looks entirely unnecessary.  The code that uses ranges also relies on concepts, and I think it's kind of reasonable to assume that a compiler that supports concepts is not going to lack ranges.  I'm preparing a PR.
