### ISSUE TITLE
Cant get pqxx to download on windows 64

### ISSUE THREAD

**Issue by nfaciano** [jtv/libpqxx#734]
Hello I am using a mingw compiler with gcc version 13.2
ive downloaded version 7.8.1 of libpqxx using gitclone.
I have all the prerequisites installed yet im getting errors on the last step. Here is my complete compilation process please let me know if this is a common issue or new. Ive been trying for 4 days now to get it up.

nickf@DESKTOP-NQFFB93 MINGW64 /c/libpqxx/build
$ ninja
[115/115] Linking CXX executable test\runner.exe
FAILED: test/runner.exe
cmd.exe /C "cd . && C:\msys64\mingw64\bin\c++.exe   test/CMakeFiles/runner.dir/runner.cxx.obj test/CMakeFiles/runner.dir/test00.cxx.obj test/CMakeFiles/runner.dir/test01.cxx.obj test/CMakeFiles/runner.dir/test02.cxx.obj test/CMakeFiles/runner.dir/test04.cxx.obj test/CMakeFiles/runner.dir/test07.cxx.obj test/CMakeFiles/runner.dir/test10.cxx.obj test/CMakeFiles/runner.dir/test11.cxx.obj test/CMakeFiles/runner.dir/test13.cxx.obj test/CMakeFiles/runner.dir/test14.cxx.obj test/CMakeFiles/runner.dir/test16.cxx.obj test/CMakeFiles/runner.dir/test17.cxx.obj test/CMakeFiles/runner.dir/test18.cxx.obj test/CMakeFiles/runner.dir/test20.cxx.obj test/CMakeFiles/runner.dir/test21.cxx.obj test/CMakeFiles/runner.dir/test26.cxx.obj test/CMakeFiles/runner.dir/test29.cxx.obj test/CMakeFiles/runner.dir/test30.cxx.obj test/CMakeFiles/runner.dir/test32.cxx.obj test/CMakeFiles/runner.dir/test37.cxx.obj test/CMakeFiles/runner.dir/test39.cxx.obj test/CMakeFiles/runner.dir/test46.cxx.obj test/CMakeFiles/runner.dir/test56.cxx.obj test/CMakeFiles/runner.dir/test60.cxx.obj test/CMakeFiles/runner.dir/test61.cxx.obj test/CMakeFiles/runner.dir/test62.cxx.obj test/CMakeFiles/runner.dir/test69.cxx.obj test/CMakeFiles/runner.dir/test70.cxx.obj test/CMakeFiles/runner.dir/test71.cxx.obj test/CMakeFiles/runner.dir/test72.cxx.obj test/CMakeFiles/runner.dir/test74.cxx.obj test/CMakeFiles/runner.dir/test75.cxx.obj test/CMakeFiles/runner.dir/test76.cxx.obj test/CMakeFiles/runner.dir/test77.cxx.obj test/CMakeFiles/runner.dir/test78.cxx.obj test/CMakeFiles/runner.dir/test79.cxx.obj test/CMakeFiles/runner.dir/test82.cxx.obj test/CMakeFiles/runner.dir/test84.cxx.obj test/CMakeFiles/runner.dir/test87.cxx.obj test/CMakeFiles/runner.dir/test88.cxx.obj test/CMakeFiles/runner.dir/test89.cxx.obj test/CMakeFiles/runner.dir/test90.cxx.obj test/CMakeFiles/runner.dir/unit/test_array.cxx.obj test/CMakeFiles/runner.dir/unit/test_binarystring.cxx.obj test/CMakeFiles/runner.dir/unit/test_blob.cxx.obj test/CMakeFiles/runner.dir/unit/test_cancel_query.cxx.obj test/CMakeFiles/runner.dir/unit/test_column.cxx.obj test/CMakeFiles/runner.dir/unit/test_composite.cxx.obj test/CMakeFiles/runner.dir/unit/test_connection.cxx.obj test/CMakeFiles/runner.dir/unit/test_cursor.cxx.obj test/CMakeFiles/runner.dir/unit/test_encodings.cxx.obj test/CMakeFiles/runner.dir/unit/test_error_verbosity.cxx.obj test/CMakeFiles/runner.dir/unit/test_errorhandler.cxx.obj test/CMakeFiles/runner.dir/unit/test_escape.cxx.obj test/CMakeFiles/runner.dir/unit/test_exceptions.cxx.obj test/CMakeFiles/runner.dir/unit/test_field.cxx.obj test/CMakeFiles/runner.dir/unit/test_float.cxx.obj test/CMakeFiles/runner.dir/unit/test_largeobject.cxx.obj test/CMakeFiles/runner.dir/unit/test_nonblocking_connect.cxx.obj test/CMakeFiles/runner.dir/unit/test_notification.cxx.obj test/CMakeFiles/runner.dir/unit/test_pipeline.cxx.obj test/CMakeFiles/runner.dir/unit/test_prepared_statement.cxx.obj test/CMakeFiles/runner.dir/unit/test_range.cxx.obj test/CMakeFiles/runner.dir/unit/test_read_transaction.cxx.obj test/CMakeFiles/runner.dir/unit/test_result_iteration.cxx.obj test/CMakeFiles/runner.dir/unit/test_result_slicing.cxx.obj test/CMakeFiles/runner.dir/unit/test_row.cxx.obj test/CMakeFiles/runner.dir/unit/test_separated_list.cxx.obj test/CMakeFiles/runner.dir/unit/test_simultaneous_transactions.cxx.obj test/CMakeFiles/runner.dir/unit/test_sql_cursor.cxx.obj test/CMakeFiles/runner.dir/unit/test_stateless_cursor.cxx.obj test/CMakeFiles/runner.dir/unit/test_strconv.cxx.obj test/CMakeFiles/runner.dir/unit/test_stream_from.cxx.obj test/CMakeFiles/runner.dir/unit/test_stream_query.cxx.obj test/CMakeFiles/runner.dir/unit/test_stream_to.cxx.obj test/CMakeFiles/runner.dir/unit/test_string_conversion.cxx.obj test/CMakeFiles/runner.dir/unit/test_subtransaction.cxx.obj test/CMakeFiles/runner.dir/unit/test_test_helpers.cxx.obj test/CMakeFiles/runner.dir/unit/test_thread_safety_model.cxx.obj test/CMakeFiles/runner.dir/unit/test_time.cxx.obj test/CMakeFiles/runner.dir/unit/test_transaction.cxx.obj test/CMakeFiles/runner.dir/unit/test_transaction_base.cxx.obj test/CMakeFiles/runner.dir/unit/test_transaction_focus.cxx.obj test/CMakeFiles/runner.dir/unit/test_transactor.cxx.obj test/CMakeFiles/runner.dir/unit/test_type_name.cxx.obj test/CMakeFiles/runner.dir/unit/test_zview.cxx.obj -o test\runner.exe -Wl,--out-implib,test\librunner.dll.a -Wl,--major-image-version,0,--minor-image-version,0  src/libpqxx.dll.a  -lwsock32  -lws2_32  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test/CMakeFiles/runner.dir/test69.cxx.obj:test69.cxx:(.text$_ZN4pqxx8pipelineC1ERNS_16transaction_baseE[_ZN4pqxx8pipelineC1ERNS_16transaction_baseE]+0x1a): undefined reference to `__imp__ZN4pqxx8pipeline11s_classnameE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test/CMakeFiles/runner.dir/unit/test_binarystring.cxx.obj:test_binarystring.cxx:(.text$_ZN4pqxx9stream_to16append_to_bufferIiEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEvE4typeERKS4_[_ZN4pqxx9stream_to16append_to_bufferIiEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEvE4typeERKS4_]+0x2b): undefined reference to `__imp__ZN4pqxx9stream_to10null_fieldE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test/CMakeFiles/runner.dir/unit/test_binarystring.cxx.obj:test_binarystring.cxx:(.text$_ZN4pqxx9stream_to16append_to_bufferINS_12binarystringEEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEvE4typeERKS5_[_ZN4pqxx9stream_to16append_to_bufferINS_12binarystringEEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEvE4typeERKS5_]+0x2b): undefined reference to `__imp__ZN4pqxx9stream_to10null_fieldE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test/CMakeFiles/runner.dir/unit/test_binarystring.cxx.obj:test_binarystring.cxx:(.text$_ZN4pqxx9stream_to16append_to_bufferISt6vectorINS_12binarystringESaIS3_EEEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEvE4typeERKS8_[_ZN4pqxx9stream_to16append_to_bufferISt6vectorINS_12binarystringESaIS3_EEEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEvE4typeERKS8_]+0x2b): undefined reference to `__imp__ZN4pqxx9stream_to10null_fieldE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test/CMakeFiles/runner.dir/unit/test_binarystring.cxx.obj:test_binarystring.cxx:(.text$_ZN4pqxx9stream_to15estimate_bufferIiEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEyE4typeERKS4_[_ZN4pqxx9stream_to15estimate_bufferIiEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEyE4typeERKS4_]+0x1f): undefined reference to `__imp__ZN4pqxx9stream_to10null_fieldE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test/CMakeFiles/runner.dir/unit/test_binarystring.cxx.obj:test_binarystring.cxx:(.text$_ZN4pqxx9stream_to15estimate_bufferINS_12binarystringEEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEyE4typeERKS5_[_ZN4pqxx9stream_to15estimate_bufferINS_12binarystringEEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEyE4typeERKS5_]+0x1f): undefined reference to `__imp__ZN4pqxx9stream_to10null_fieldE'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: test/CMakeFiles/runner.dir/unit/test_binarystring.cxx.obj:test_binarystring.cxx:(.text$_ZN4pqxx9stream_to15estimate_bufferISt6vectorINS_12binarystringESaIS3_EEEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEyE4typeERKS8_[_ZN4pqxx9stream_to15estimate_bufferISt6vectorINS_12binarystringESaIS3_EEEENSt9enable_ifIXntsrNS_8nullnessIT_vEE11always_nullEyE4typeERKS8_]+0x1f): more undefined references to `__imp__ZN4pqxx9stream_to10null_fieldE' follow
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

nickf@DESKTOP-NQFFB93 MINGW64 /c/libpqxx/build
$

**Comment by jtv** [comment]
This is a weird one.  My best guess right now is that there might be a second libpqxx binary already on your system somewhere, perhaps a different version, or built with different options.  Any chance that that might be what's happening?

**Comment by jtv** [comment]
@nfaciano did you find the problem?

**Comment by jtv** [comment]
No response.  Hopefully that means the problem has been resolved.

I'll close the ticket.
