### ISSUE TITLE
exec_prepared not working with runtime parameter list

### ISSUE THREAD

**Issue by frankbenderumn** [jtv/libpqxx#736]
I recently upgraded to pqxx7 but am beginning to regret it as it broke all my old code.
In the past I would use an invocation to do this and it worked great.
But now trying to use a parameter list again as such:

```
try {
    std::string prep_name = "insert_model" + std::to_string(++Q_CT);
    C->prepare(prep_name, insertQuery);
    pqxx::work txn{*C};
    pqxx::params attrs;
    for (const auto& attr : p.second) {
        attrs.append(attr);
        MAG("param: %s\n", attr.c_str());
    }

    BLU("Attrs size: %li\n", attrs.size());
    txn.exec_prepared(prep_name, insertQuery, attrs);
    txn.commit();

    BGRE("INSERTED RECORD\n");
} catch (const std::exception& e) {
    BRED("FAILED TO INSERT RECORD\n");
    std::cout << e.what() << std::endl;
}
```
 I receive the error: Failure during 'insert_model1': ERROR:  bind message supplies 9 parameters, but prepared statement "insert_model1" requires 8.
 
 This makes no sense because there are very clearly only 8. I have even confirmed that the attrs.size() is in fact 8.
 
 My system has too many tables and queries to manually type the prepared arguments every query.

**Comment by jtv** [comment]
You're supplying the query text as a first parameter.

**Comment by jtv** [comment]
@frankbenderumn did you get my last message?  In your call to the prepared statement, you are passing both the statement name (which is correct) and the statement code (which is not).

**Comment by jtv** [comment]
(No response but I hope the solution came through.  Simple typo on the client side, basically.  I'll close the ticket.)
