### ISSUE TITLE
Compilation Error: Invalid Use of 'this' at Top Level in range.hxx (libpqxx 7.8.0, openSUSE Leap 15.5)

### ISSUE THREAD

**Issue by lenin41211** [jtv/libpqxx#737]
I'm encountering an issue while attempting to **install libpqxx 7.8.0 on openSUSE Leap 15.5**. I've configured it using **./configure CXXFLAGS="-std=c++17"**. However, during the compilation, I'm facing errors related to invalid use of 'this' at the top level in the range.hxx file. The specific lines causing trouble are related to comparisons and noexcept specifications.

Here's a snippet of the errors:
../include/pqxx/range.hxx:143:24: error: invalid use of ‘this’ at top level
     noexcept(noexcept(*this->value() == *rhs.value()))
                        ^~~~
...
../include/pqxx/range.hxx:315:25: error: invalid use of ‘this’ at top level
     noexcept(noexcept((*this & other) == other))

These errors seem to be pointing to improper usage of 'this' in the range.hxx file, please assist me resolve this...

**Comment by tt4g** [comment]
This appears to be a bug that has been reproduced many times in GCC.
Try updating your compiler.

- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52869
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100752

**Comment by jtv** [comment]
For the record @lenin41211, what compiler & version are you using?  I don't track it very closely but the known minimum gcc version that'll work is 8.

**Comment by lenin41211** [comment]
I switched from using gcc-11 to gcc-13, and the upgrade has resolved the issue, ensuring smooth functionality, thank you.

**Comment by jtv** [comment]
Glad that's solved!  I'll close the ticket.
