### ISSUE TITLE
6.2.0 build regression

### ISSUE THREAD

**Issue by anthraxx** [jtv/libpqxx#74]
Hi, with 6.2.0 i get a build regression (used gcc is 7.3.0):

```
...
make[1]: Entering directory '/build/libpqxx/src/libpqxx-6.2.0/tools'
g++ -DHAVE_CONFIG_H   -I../include -I../include -I/usr/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fvisibility=hidden -fvisibility-inlines-hidden -MT rmlo.o -MD -MP -MF .deps/rmlo.Tpo -c -o rmlo.o rmlo.cxx
g++ -DHAVE_CONFIG_H   -I../include -I../include -I/usr/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fvisibility=hidden -fvisibility-inlines-hidden -MT pqxxthreadsafety.o -MD -MP -MF .deps/pqxxthreadsafety.Tpo -c -o pqxxthreadsafety.o pqxxthreadsafety.cxx
mv -f .deps/pqxxthreadsafety.Tpo .deps/pqxxthreadsafety.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fvisibility=hidden -fvisibility-inlines-hidden  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/lib -o pqxxthreadsafety pqxxthreadsafety.o ../src/libpqxx.la  -lpq 
libtool: link: g++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fvisibility=hidden -fvisibility-inlines-hidden -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -o .libs/pqxxthreadsafety pqxxthreadsafety.o  -L/usr/lib ../src/.libs/libpqxx.so -lpq
mv -f .deps/rmlo.Tpo .deps/rmlo.Po
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fvisibility=hidden -fvisibility-inlines-hidden  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/lib -o rmlo rmlo.o ../src/libpqxx.la  -lpq 
libtool: link: g++ -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fvisibility=hidden -fvisibility-inlines-hidden -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -o .libs/rmlo rmlo.o  -L/usr/lib ../src/.libs/libpqxx.so -lpq
rmlo.o: In function `pqxx::basic_connection<pqxx::connect_lazy>::basic_connection()':
rmlo.cxx:(.text._ZN4pqxx16basic_connectionINS_12connect_lazyEEC2Ev[_ZN4pqxx16basic_connectionINS_12connect_lazyEEC5Ev]+0x10f): undefined reference to `pqxx::connection_base::clearcaps()'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:384: rmlo] Error 1
make[1]: Leaving directory '/build/libpqxx/src/libpqxx-6.2.0/tools'
make: *** [Makefile:681: all-recursive] Error 1

```

**Comment by KayEss** [comment]
Latest master is also giving me a link problem, but with `_ZN4pqxx15connection_base9clearcapsEv`

**Comment by jtv** [comment]
This must be something to do with a change I made in 6.2: the `connection_base` (basically right where this error happens, next to the call to clearcaps!) now tries to cause a link error if your version of the library binary does not match the version of the library headers against which you've compiled your client.  Not _this_ link error though, obviously!

**Comment by jtv** [comment]
No luck reproducing this with gcc 7.2 either.  And the 6.2.0 tag does seem to be at the head of master.  (@KayEss, you simply got the mangled version of the same identifier where @anthraxx saw the link error as well.)

Any chance that you might have an old library, old headers, or an old object file lying around causing trouble?  Clutching at straws here though — maybe it's something like `noexcept` breaking the link, or different language versions...  Ideas welcome.

**Comment by anthraxx** [comment]
What do you mean by mangled version of the same. Identifier? Was the tag republished as the same label?
Unclean environment is out of the possibilities as im building in a clean chroot environment.

If you are looking for a reproducible environment you can use the archlinux/base docker image and build the package https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/libpqxx

Cheers

**Comment by jtv** [comment]
@anthraxx  I meant "mangled" in the sense of "C++ name mangling."  Linkers don't permit symbols like "::" in names.  C++ compilers turn identifiers like `pqxx::connection_base::clearcaps` into linker symbols like `_ZN4pqxx15connection_base9clearcapsEv`.  They are probably the exact same name, but the latter got "mangled."  Besides escaping the unacceptable characters, it can also include additional type information that was never designed into the C linking system, such as `noexcept`, or compile options which may make the code binary-incompatible with code compiled with different options.

Looking at that build script I see two differences from what I tested:

1. The version number still says 6.1.1
2. You configure with `--enable-shared`.  I'll see if that works for me — I normally build statically, which I think makes more sense for a complex C++ library.

**Comment by jtv** [comment]
Yay!  Found it.  `clearcaps` was marked `PQXX_PRIVATE`, which means that the symbol is left out of the shared library.  Which used to be appropriate, but for this new feature, I made the one call to that function inline.  So the client object file now calls it, and so it needs external linkage.

New release is forthcoming.  I'll have to make a habit out of testing with `--enable-shared`...

**Comment by anthraxx** [comment]
Thx for explaining, but I was aware how cpp name mangling works, it just sounded like you are speaking about git project state somehow. :p

Well it's not the newest because it doesn't build ;-)
There is only build scripts that work. just increment the version there. :)

**Comment by anthraxx** [comment]
Awesome, yeah that makes sense :D nice that you found the issue. Gonna give it another try.
Thx for the project and bug handling.
