### ISSUE TITLE
Lib LNK failure on windows.I build the lib by myself

### ISSUE THREAD

**Issue by zhaohe36** [jtv/libpqxx#744]
cmake_minimum_required(VERSION 3.2)
project(postgre_test)
include_directories(F:/DBC/install/include)
set(CMAKE_CXX_STANDARD 17)
link_directories(F:/DBC/install/lib)
add_executable(postgre_test main.cpp)
target_link_libraries(postgre_test pqxx)

[1/2] Building CXX object CMakeFiles\postgre_test.dir\main.cpp.obj
E:\Visual Studio\VC\Tools\MSVC\14.37.32822\include\ranges(12): warning STL4038: The contents of <ranges> are available only with C++20 or later.
E:\Visual Studio\VC\Tools\MSVC\14.37.32822\include\span(13): warning STL4038: The contents of <span> are available only with C++20 or later.
C:\Users\15437\Desktop\postgre_test\main.cpp(20): warning C4101: ��e��: δ���õľֲ�����
[2/2] Linking CXX executable postgre_test.exe
FAILED: postgre_test.exe 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\postgre_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- "E:\Visual Studio\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\link.exe" /nologo CMakeFiles\postgre_test.dir\main.cpp.obj  /out:postgre_test.exe /implib:postgre_test.lib /pdb:postgre_test.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console -LIBPATH:F:\DBC\install\lib pqxx.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK: command "E:\Visual Studio\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\link.exe /nologo CMakeFiles\postgre_test.dir\main.cpp.obj /out:postgre_test.exe /implib:postgre_test.lib /pdb:postgre_test.pdb /version:0.0 /machine:x64 /INCREMENTAL:NO /subsystem:console -LIBPATH:F:\DBC\install\lib pqxx.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST:EMBED,ID=1" failed (exit code 1120) with the following output:
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQresultStatus������ "private: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::result::status_error(void)const " (?status_error@result@pqxx@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQresultErrorMessage������ "private: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::result::status_error(void)const " (?status_error@result@pqxx@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQresultErrorField������ "private: int __cdecl pqxx::result::errorposition(void)const " (?errorposition@result@pqxx@@AEBAHXZ) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQntuples������ "public: bool __cdecl pqxx::result::operator==(class pqxx::result const &)const " (??8result@pqxx@@QEBA_NAEBV01@@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQnfields������ "public: bool __cdecl pqxx::result::operator==(class pqxx::result const &)const " (??8result@pqxx@@QEBA_NAEBV01@@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQfname������ "public: char const * __cdecl pqxx::result::column_name(int)const & " (?column_name@result@pqxx@@QEGBAPEBDH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQfnumber������ "public: int __cdecl pqxx::result::column_number(class pqxx::zview)const " (?column_number@result@pqxx@@QEBAHVzview@2@@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQftable������ "public: unsigned int __cdecl pqxx::result::column_table(int)const " (?column_table@result@pqxx@@QEBAIH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQftablecol������ "public: int __cdecl pqxx::result::table_column(int)const " (?table_column@result@pqxx@@QEBAHH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQftype������ "public: unsigned int __cdecl pqxx::result::column_type(int)const " (?column_type@result@pqxx@@QEBAIH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQfsize������ "public: int __cdecl pqxx::result::column_storage(int)const " (?column_storage@result@pqxx@@QEBAHH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQfmod������ "public: int __cdecl pqxx::result::column_type_modifier(int)const " (?column_type_modifier@result@pqxx@@QEBAHH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQcmdStatus������ "private: char const * __cdecl pqxx::result::cmd_status(void)const " (?cmd_status@result@pqxx@@AEBAPEBDXZ) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQoidValue������ "public: unsigned int __cdecl pqxx::result::inserted_oid(void)const " (?inserted_oid@result@pqxx@@QEBAIXZ) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQcmdTuples������ "public: int __cdecl pqxx::result::affected_rows(void)const " (?affected_rows@result@pqxx@@QEBAHXZ) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQgetvalue������ "private: char const * __cdecl pqxx::result::get_value(int,int)const " (?get_value@result@pqxx@@AEBAPEBDHH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQgetlength������ "private: unsigned __int64 __cdecl pqxx::result::get_length(int,int)const " (?get_length@result@pqxx@@AEBA_KHH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQgetisnull������ "private: bool __cdecl pqxx::result::get_is_null(int,int)const " (?get_is_null@result@pqxx@@AEBA_NHH@Z) �������˸÷���
pqxx.lib(result.obj) : error LNK2019: �޷��������ⲿ���� PQclear������ "void __cdecl pqxx::internal::clear_result(struct pg_result const *)" (?clear_result@internal@pqxx@@YAXPEBUpg_result@@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� __imp_ioctlsocket������ "public: void __cdecl pqxx::connection::set_blocking(bool)& " (?set_blocking@connection@pqxx@@QEGAAX_N@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� __imp_WSAGetLastError������ "public: void __cdecl pqxx::connection::set_blocking(bool)& " (?set_blocking@connection@pqxx@@QEGAAX_N@Z) �������˸÷���
pqxx.lib(wait.obj) : error LNK2001: �޷��������ⲿ���� __imp_WSAGetLastError
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQconnectStart������ "public: __cdecl pqxx::connecting::connecting(class pqxx::zview)" (??0connecting@pqxx@@QEAA@Vzview@1@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQconnectPoll������ "private: struct std::pair<bool,bool> __cdecl pqxx::connection::poll_connect(void)" (?poll_connect@connection@pqxx@@AEAA?AU?$pair@_N_N@std@@XZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQconnectdb������ "private: void __cdecl pqxx::connection::init(char const * const)" (?init@connection@pqxx@@AEAAXQEBD@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQconnectdbParams������ "private: void __cdecl pqxx::connection::init(char const * * const,char const * * const)" (?init@connection@pqxx@@AEAAXQEAPEBD0@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQfinish������ "public: void __cdecl pqxx::connection::close(void)" (?close@connection@pqxx@@QEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQconninfo������ "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::connection::connection_string(void)const " (?connection_string@connection@pqxx@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQconninfoFree������ "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::connection::connection_string(void)const " (?connection_string@connection@pqxx@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQgetCancel������ "public: void __cdecl pqxx::connection::cancel_query(void)" (?cancel_query@connection@pqxx@@QEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQfreeCancel������ "public: void __cdecl pqxx::connection::cancel_query(void)" (?cancel_query@connection@pqxx@@QEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQcancel������ "public: void __cdecl pqxx::connection::cancel_query(void)" (?cancel_query@connection@pqxx@@QEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQdb������ "public: char const * __cdecl pqxx::connection::dbname(void)const " (?dbname@connection@pqxx@@QEBAPEBDXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQuser������ "public: char const * __cdecl pqxx::connection::username(void)const " (?username@connection@pqxx@@QEBAPEBDXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQhost������ "public: char const * __cdecl pqxx::connection::hostname(void)const " (?hostname@connection@pqxx@@QEBAPEBDXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQport������ "public: char const * __cdecl pqxx::connection::port(void)const " (?port@connection@pqxx@@QEBAPEBDXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQstatus������ "public: __cdecl pqxx::connecting::connecting(class pqxx::zview)" (??0connecting@pqxx@@QEAA@Vzview@1@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQprotocolVersion������ "private: void __cdecl pqxx::connection::complete_init(void)" (?complete_init@connection@pqxx@@AEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQserverVersion������ "private: void __cdecl pqxx::connection::complete_init(void)" (?complete_init@connection@pqxx@@AEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQerrorMessage������ "public: __cdecl pqxx::connecting::connecting(class pqxx::zview)" (??0connecting@pqxx@@QEAA@Vzview@1@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQsocket������ "public: int __cdecl pqxx::connection::await_notification(void)" (?await_notification@connection@pqxx@@QEAAHXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQbackendPID������ "public: int __cdecl pqxx::connection::backendpid(void)const & " (?backendpid@connection@pqxx@@QEGBAHXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQclientEncoding������ "public: int __cdecl pqxx::connection::encoding_id(void)const " (?encoding_id@connection@pqxx@@QEBAHXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQsetClientEncoding������ "public: void __cdecl pqxx::connection::set_client_encoding(char const * const)& " (?set_client_encoding@connection@pqxx@@QEGAAXQEBD@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQinitOpenSSL������ "void __cdecl pqxx::internal::skip_init_ssl(int)" (?skip_init_ssl@internal@pqxx@@YAXH@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQsetErrorVerbosity������ "public: void __cdecl pqxx::connection::set_verbosity(enum pqxx::error_verbosity)& " (?set_verbosity@connection@pqxx@@QEGAAXW4error_verbosity@2@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQsetNoticeProcessor������ "private: void __cdecl pqxx::connection::complete_init(void)" (?complete_init@connection@pqxx@@AEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQtrace������ "public: void __cdecl pqxx::connection::trace(struct _iobuf *)" (?trace@connection@pqxx@@QEAAXPEAU_iobuf@@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQuntrace������ "public: void __cdecl pqxx::connection::trace(struct _iobuf *)" (?trace@connection@pqxx@@QEAAXPEAU_iobuf@@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQexec������ "private: void __cdecl pqxx::connection::add_receiver(class pqxx::notification_receiver *)" (?add_receiver@connection@pqxx@@AEAAXPEAVnotification_receiver@2@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQexecParams������ "private: class pqxx::result __cdecl pqxx::connection::exec_params(class std::basic_string_view<char,struct std::char_traits<char> >,struct pqxx::internal::c_params const &)" (?exec_params@connection@pqxx@@AEAA?AVresult@2@V?$basic_string_view@DU?$char_traits@D@std@@@std@@AEBUc_params@internal@2@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQprepare������ "public: void __cdecl pqxx::connection::prepare(char const * const,char const * const)& " (?prepare@connection@pqxx@@QEGAAXQEBD0@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQexecPrepared������ "private: class pqxx::result __cdecl pqxx::connection::exec_prepared(class std::basic_string_view<char,struct std::char_traits<char> >,struct pqxx::internal::c_params const &)" (?exec_prepared@connection@pqxx@@AEAA?AVresult@2@V?$basic_string_view@DU?$char_traits@D@std@@@std@@AEBUc_params@internal@2@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQsendQuery������ "private: void __cdecl pqxx::connection::start_exec(char const * const)" (?start_exec@connection@pqxx@@AEAAXQEBD@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQgetResult������ "private: void __cdecl pqxx::connection::end_copy_write(void)" (?end_copy_write@connection@pqxx@@AEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQisBusy������ "private: bool __cdecl pqxx::connection::is_busy(void)const " (?is_busy@connection@pqxx@@AEBA_NXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQconsumeInput������ "private: bool __cdecl pqxx::connection::consume_input(void)" (?consume_input@connection@pqxx@@AEAA_NXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQnotifies������ "public: int __cdecl pqxx::connection::get_notifs(void)" (?get_notifs@connection@pqxx@@QEAAHXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQputCopyData������ "private: void __cdecl pqxx::connection::write_copy_line(class std::basic_string_view<char,struct std::char_traits<char> >)" (?write_copy_line@connection@pqxx@@AEAAXV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQputCopyEnd������ "private: void __cdecl pqxx::connection::end_copy_write(void)" (?end_copy_write@connection@pqxx@@AEAAXXZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQgetCopyData������ "private: struct std::pair<class std::unique_ptr<char,void (__cdecl*)(void const *)>,unsigned __int64> __cdecl pqxx::connection::read_copy_line(void)" (?read_copy_line@connection@pqxx@@AEAA?AU?$pair@V?$unique_ptr@DP6AXPEBX@Z@std@@_K@std@@XZ) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQescapeStringConn������ "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::connection::esc(class std::basic_string_view<char,struct std::char_traits<char> >)const " (?esc@connection@pqxx@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_string_view@DU?$char_traits@D@std@@@4@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQescapeIdentifier������ "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::separated_list<class std::basic_string_view<char,struct std::char_traits<char> > const *,class <lambda_a112315309aca38dbae962208451c35e> >(class std::basic_string_view<char,struct std::char_traits<char> >,class std::basic_string_view<char,struct std::char_traits<char> > const *,class std::basic_string_view<char,struct std::char_traits<char> > const *,class <lambda_a112315309aca38dbae962208451c35e>)" (??$separated_list@PEBV?$basic_string_view@DU?$char_traits@D@std@@@std@@V<lambda_a112315309aca38dbae962208451c35e>@@@pqxx@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_string_view@DU?$char_traits@D@std@@@2@PEBV32@1V<lambda_a112315309aca38dbae962208451c35e>@@@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQunescapeBytea������ "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::connection::unesc_raw(char const * const)const " (?unesc_raw@connection@pqxx@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEBD@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQencryptPassword������ "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::encrypt_password(char const * const,char const * const)" (?encrypt_password@pqxx@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEBD0@Z) �������˸÷���
pqxx.lib(connection.obj) : error LNK2019: �޷��������ⲿ���� PQencryptPasswordConn������ "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::connection::encrypt_password(char const * const,char const * const,char const *)" (?encrypt_password@connection@pqxx@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEBD0PEBD@Z) �������˸÷���
pqxx.lib(util.obj) : error LNK2019: �޷��������ⲿ���� PQisthreadsafe������ "struct pqxx::thread_safety_model __cdecl pqxx::describe_thread_safety(void)" (?describe_thread_safety@pqxx@@YA?AUthread_safety_model@1@XZ) �������˸÷���
pqxx.lib(util.obj) : error LNK2019: �޷��������ⲿ���� PQfreemem������ "void __cdecl pqxx::internal::pq::pqfreemem(void const *)" (?pqfreemem@pq@internal@pqxx@@YAXPEBX@Z) �������˸÷���
pqxx.lib(encodings.obj) : error LNK2019: �޷��������ⲿ���� pg_encoding_to_char������ "enum pqxx::internal::encoding_group __cdecl pqxx::internal::enc_group(int)" (?enc_group@internal@pqxx@@YA?AW4encoding_group@12@H@Z) �������˸÷���
pqxx.lib(wait.obj) : error LNK2019: �޷��������ⲿ���� __imp_WSAPoll������ "void __cdecl pqxx::internal::wait_fd(int,bool,bool,unsigned int,unsigned int)" (?wait_fd@internal@pqxx@@YAXH_N0II@Z) �������˸÷���
postgre_test.exe : fatal error LNK1120: 69 ���޷��������ⲿ����
ninja: build stopped: subcommand failed.

**Comment by KayEss** [comment]
Looks like you may not be linking libpq. Try this instead: `target_link_libraries(postgre_test pqxx pq)`

**Comment by zhaohe36** [comment]
> Looks like you may not be linking libpq. Try this instead: `target_link_libraries(postgre_test pqxx pq)`

there's no pq.lib

**Comment by KayEss** [comment]
How did you build libpqxx? You are going to need both libpqxx and libpq

**Comment by zhaohe36** [comment]
> How did you build libpqxx? You are going to need both libpqxx and libpq

Cmake by adding PostgreSQL_ROOT path,then generate sln
ALL_BUILD and then INSTALL


F:\DBC\install
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/11/4     12:27                include
d-----         2023/11/4     13:27                lib
d-----         2023/11/4     12:27                share

目录: F:\DBC\install\lib


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2023/11/4     12:27                cmake
d-----         2023/11/4     12:27                pkgconfig
-a----         2023/11/4     12:21        4299842 pqxx.lib

**Comment by KayEss** [comment]
In that case I expect you should find libpq somewhere under PostgreSQL_ROOT.

If you're using cmake it's generally easier to integrate the libpqxx source under your project (maybe as a git submodule) and then use `add_subdirectory` to bring it in. This will ensure you won't have any weird issues switching build options (like release and debug).

**Comment by zhaohe36** [comment]
> In that case I expect you should find libpq somewhere under PostgreSQL_ROOT.
> 
> If you're using cmake it's generally easier to integrate the libpqxx source under your project (maybe as a git submodule) and then use `add_subdirectory` to bring it in. This will ensure you won't have any weird issues switching build options (like release and debug).

Cmake knows where to find libpq
I use vcpkg to build libpqxx，the outcome is all the same ,LNK error

**Comment by tt4g** [comment]
It is not a libpqxx problem that vcpkg cannot find libpq.
Since the vcpkg package is not maintained in this repository, I recommend moving the issue to the [vcpkg repository](https://github.com/microsoft/vcpkg).

**Comment by zhaohe36** [comment]
> It is not a libpqxx problem that vcpkg cannot find libpq. Since the vcpkg package is not maintained in this repository, I recommend moving the issue to the [vcpkg repository](https://github.com/microsoft/vcpkg).

it's not the vcpkg problem
problem
error LNK2019: �޷��������ⲿ���� __imp_WSAPoll������ "void __cdecl `
anyway ,I found that it can be solved by  Ws2_32.lib in the visual studio #pragma comment(lib, "Ws2_32.lib")
and then It worked

**Comment by tt4g** [comment]
I can only assume that your procedure was incorrect, since `ws2_32.lib` will be added to the link target if CMake is used correctly.

https://github.com/jtv/libpqxx/blob/75868467f6808cd712144ebfa2ba26ebbf05e4cb/src/CMakeLists.txt#L30-L32

**Comment by zhaohe36** [comment]
> I can only assume that your procedure was incorrect, since `ws2_32.lib` will be added to the link target if CMake is used correctly.
> 
> https://github.com/jtv/libpqxx/blob/75868467f6808cd712144ebfa2ba26ebbf05e4cb/src/CMakeLists.txt#L30-L32

why in my procedure it must link to libpq.lib
as it already was linked in src cmakelist
    target_link_libraries(${tgt} PRIVATE ${PostgreSQL_LIBRARIES})

**Comment by tt4g** [comment]
Look above one line.

https://github.com/jtv/libpqxx/blob/75868467f6808cd712144ebfa2ba26ebbf05e4cb/src/CMakeLists.txt#L29-L32

**Comment by zhaohe36** [comment]
pqxx::connection connection("dbname=covered user=covered password=covered hostaddr=database-1.ca9pud6sknas.ap-east-1.rds.amazonaws.com");
pqxx::work transaction(connection);
Error: could not parse network address "database-1.ca9pud6sknas.ap-east-1.rds.amazonaws.com"

**Comment by tt4g** [comment]
You should first read the PostgreSQL documentation.
`hostaddr` is wrong, `host` must be used.

https://www.postgresql.org/docs/16/libpq-connect.html

> host 
>
> Name of host to connect to. If a host name looks like an absolute path name, it specifies Unix-domain communication rather than TCP/IP communication; the value is the name of the directory in which the socket file is stored. (On Unix, an absolute path name begins with a slash. On Windows, paths starting with drive letters are also recognized.) If the host name starts with @, it is taken as a Unix-domain socket in the abstract namespace (currently supported on Linux and Windows). The default behavior when host is not specified, or is empty, is to connect to a Unix-domain socket in /tmp (or whatever socket directory was specified when PostgreSQL was built). On Windows, the default is to connect to localhost.
> 
> A comma-separated list of host names is also accepted, in which case each host name in the list is tried in order; an empty item in the list selects the default behavior as explained above. See [Section 34.1.1.3](https://www.postgresql.org/docs/16/libpq-connect.html#LIBPQ-MULTIPLE-HOSTS) for details.
> 
>
> hostaddr 
>
> Numeric IP address of host to connect to. This should be in the standard IPv4 address format, e.g., 172.28.40.9. If your machine supports IPv6, you can also use those addresses. TCP/IP communication is always used when a nonempty string is specified for this parameter. If this parameter is not specified, the value of host will be looked up to find the corresponding IP address — or, if host specifies an IP address, that value will be used directly.

**Comment by zhaohe36** [comment]
> You should first read the PostgreSQL documentation. `hostaddr` is wrong, `host` must be used.
> 
> https://www.postgresql.org/docs/16/libpq-connect.html
> 
> > host
> > Name of host to connect to. If a host name looks like an absolute path name, it specifies Unix-domain communication rather than TCP/IP communication; the value is the name of the directory in which the socket file is stored. (On Unix, an absolute path name begins with a slash. On Windows, paths starting with drive letters are also recognized.) If the host name starts with @, it is taken as a Unix-domain socket in the abstract namespace (currently supported on Linux and Windows). The default behavior when host is not specified, or is empty, is to connect to a Unix-domain socket in /tmp (or whatever socket directory was specified when PostgreSQL was built). On Windows, the default is to connect to localhost.
> > A comma-separated list of host names is also accepted, in which case each host name in the list is tried in order; an empty item in the list selects the default behavior as explained above. See [Section 34.1.1.3](https://www.postgresql.org/docs/16/libpq-connect.html#LIBPQ-MULTIPLE-HOSTS) for details.
> > hostaddr
> > Numeric IP address of host to connect to. This should be in the standard IPv4 address format, e.g., 172.28.40.9. If your machine supports IPv6, you can also use those addresses. TCP/IP communication is always used when a nonempty string is specified for this parameter. If this parameter is not specified, the value of host will be looked up to find the corresponding IP address — or, if host specifies an IP address, that value will be used directly.

THANKS

**Comment by tt4g** [comment]
Oops, wrong issue to post.
[This comment](https://github.com/jtv/libpqxx/issues/744#issuecomment-1793447798) was mistakenly posted to #745.
