### ISSUE TITLE
Cannot connect to DB with URL

### ISSUE THREAD

**Issue by zhaohe36** [jtv/libpqxx#745]
connecting to db server with ip only is bad

**Comment by tt4g** [comment]
Nothing is known from the issue.
Please provide minimal source code that can reproduce the problem.

**Comment by zhaohe36** [comment]
> Nothing is known from the issue. Please provide minimal source code that can reproduce the problem.

pqxx::connection connection("dbname=covered user=covered password=covered hostaddr=database-1.ca9pud6sknas.ap-east-1.rds.amazonaws.com");
pqxx::work transaction(connection);
Error: could not parse network address "database-1.ca9pud6sknas.ap-east-1.rds.amazonaws.com"

**Comment by jtv** [comment]
What you're passing is _not_ a host IP.

Use `hostaddr` for a host IP _address,_ or `host` for a host _name._

**Comment by tt4g** [comment]
I had posted my response to this issue in another issue: https://github.com/jtv/libpqxx/issues/744#issuecomment-1793551005
My apologies.
