### ISSUE TITLE
pqxx::transaction::exec_prepared does not allow for runtime variable arguments

### ISSUE THREAD

**Issue by alteryxMChadwick** [jtv/libpqxx#75]
With the deprecation of `transaction::prepared`, there is no longer a supported way to pass an arbitrary number of arguments generated at runtime.

For example, this use case

```
pqxx::result
ExecWithRuntimeArgs(
    pqxx::work &transaction
    , string runtimeGeneratedPreparedQuery
    , const vector<string>& args)
{
    auto invocation{ transaction.prepared(runtimeGeneratedPreparedQuery) };
    for(const auto &arg : args)
    {
        invocation(arg);
    }
    return invocation.exec();
}
```

Is not supported by any overload of `exec_prepared*`. I would like to see at least one overload of `exec_prepared` and its kin that takes
- a `gsl::span`
- a templated range with perfect forwarding (a la Boost.Ranges)
- or even just a pair of templated iterators (like the STL algorithms)

**Comment by jtv** [comment]
Boy, is this awkward.  And there's no way to add an optional parameter after the templatised ones!

Any kind of range or container or generator we pass could conceivably, in the future, be meant to represent an SQL array as a single parameter.  So maybe what we need is a custom wrapper class (or class template) for "pass these further items as varargs."  You'd just pass one of those as a regular argument, and it would be expanded into however many arguments it contains.

**Comment by alteryxMChadwick** [comment]
That seems like a good solution to me. That would be nice because it would allow multiple containers to be passed to a single prepared statement in arbitrary combination with single-argument values.

**Comment by rocksolidwebdesign** [comment]
:+1: for runtime variable arguments

**Comment by jtv** [comment]
Implemented!  Needed a profound change in how parameters are marshalled, and it probably cost some performance there, but on the bright side, it reduces the sort of complexity that may lead to memory bugs.
