### ISSUE TITLE
vcpkg installation - link errors

### ISSUE THREAD

**Issue by peterritter** [jtv/libpqxx#752]
I had to move my vcpkg installation directory to another disk because building libtorch was creating tens of gigabytes of files during its build. So I reinstalled all packages I had installed with vcpkg - including libpqxx.  libpqxx had been linking fine with my project, but now, with the latest version I'm getting link errors:

```
pqxx::conversion_error::conversion_error
referenced in function "... pqxx::to_string<char [9]>(char const (&)[9])"
pqxx::conversion_overrun::conversion_overrun
```

This is with the latest libpqxx version on Windows 10 64-bit. I can't remember which version I had installed previously but it was from earlier this year. I'll try to go back to something earlier - else I will try to build it without vcpkg. I just wanted to mention these linking errors in case others are having the same problem on Windows. I hadn't changed anything in my project other than reinstalling all dependencies with vcpkg. It's only libpqxx that is giving me problems.   I'm using CLion/CMake with the microsoft toolchain.

The full message looks like this: 

```
t24000__libpqxx.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl pqxx::conversion_error::conversion_error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct std::source_location)" (__imp_??0conversion_error@pqxx@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Usource_location@3@@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::to_string<char [9]>(char const (&)[9])" (??$to_string@$$BY08D@pqxx@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAY08$$CBD@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: __cdecl pqxx::conversion_error::conversion_error(struct pqxx::conversion_error const &)" (__imp_??0conversion_error@pqxx@@QEAA@AEBU01@@Z)
t24000__libpqxx.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl pqxx::conversion_overrun::conversion_overrun(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct std::source_location)" (__imp_??0conversion_overrun@pqxx@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Usource_location@3@@Z) referenced in function "public: static char * __cdecl pqxx::string_traits<char [9]>::into_buf(char *,char *,char const (&)[9])" (?into_buf@?$string_traits@$$BY08D@pqxx@@SAPEADPEAD0AEAY08$$CBD@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: __cdecl pqxx::conversion_overrun::conversion_overrun(struct pqxx::conversion_overrun const &)" (__imp_??0conversion_overrun@pqxx@@QEAA@AEBU01@@Z)
PR_TEST_VS_CMAKE.exe : fatal error LNK1120: 2 unresolved externals
ninja: build stopped: subcommand failed.
```

**Comment by jtv** [comment]
(I edited your text for formatting, to make sure that no important text was getting lost in there.)

Some guesses...
* Did the object file `except.obj` get lost somehow?
* Was there a difference in C++ language versions, compiler versions, or compiler options between builds?
* It's not a Debug/Release build difference?
* Did you clean up all the old libpqxx files before building the new libpqxx?
* Are you sure part of the build isn't picking up another libpqxx binary, e.g. one left over from the previous install?

**Comment by peterritter** [comment]
Well, all I am doing to install is:
D:\vcpkg>.\vcpkg install libpqxx:x64-windows

There really isn't a lot I can do wrong here. For years I had been using an old version of libpqxx for which I had created a Visual Studio project from scratch and was building it like that. I remember that was quite an effort at the time to build on windows. You can imagine how happy I was to discover the vcpkg installer. In fact vcpkg has been working extremely well for me. Cmake is not so transparent when it comes to default compiler settings - but in general I just use the default settings. So, this problem with libpqxx is really the first major failure I'm getting using vcpkg. This c++ project of mine is really just a 'testing ground' project for testing features and usage of various libraries before using in other projects - I'm linking to dozens of libraries and they all work except this problem now with libpqxx. I actually rely on libpqxx quite heavily in other projects as I am heavily invested in PostgreSql, so I'm motivated to get this working one way or another.

In my CMake file I am setting: 

set(CMAKE_TOOLCHAIN_FILE "D:/vcpkg/scripts/buildsystems/vcpkg.cmake"
        CACHE STRING "Vcpkg toolchain file")

I have about 20 other dependencies and these are all linking fine. 

The previous vcpkg directory was on C: drive, so I don't think it is picking up anything from any previous builds. Anyhow, I renamed the old vcpkg directory to 'vcpkg__obsolete'  just to be sure.

The link errors are happening when I use functions like  .exec_params0, for example:

std::string cmd = "update test.table_a set COL_STR = $1";
tx.exec_params0(cmd, "string A");

This looks like a variadic template. Somehow the linker now can't find pqxx::conversion_error and pqxx::conversion_overrun. 

The error is: 
t24000__libpqxx.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl pqxx::conversion_error::conversion_error(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct std::source_location)" (__imp_??0conversion_error@pqxx@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Usource_location@3@@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl pqxx::to_string<char [9]>(char const (&)[9])" (??$to_string@$$BY08D@pqxx@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAY08$$CBD@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: __cdecl pqxx::conversion_error::conversion_error(struct pqxx::conversion_error const &)" (__imp_??0conversion_error@pqxx@@QEAA@AEBU01@@Z)
t24000__libpqxx.cpp.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl pqxx::conversion_overrun::conversion_overrun(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,struct std::source_location)" (__imp_??0conversion_overrun@pqxx@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@Usource_location@3@@Z) referenced in function "public: static char * __cdecl pqxx::string_traits<char [9]>::into_buf(char *,char *,char const (&)[9])" (?into_buf@?$string_traits@$$BY08D@pqxx@@SAPEADPEAD0AEAY08$$CBD@Z)
  Hint on symbols that are defined and could potentially match:
    "__declspec(dllimport) public: __cdecl pqxx::conversion_overrun::conversion_overrun(struct pqxx::conversion_overrun const &)" (__imp_??0conversion_overrun@pqxx@@QEAA@AEBU01@@Z)
PR_TEST_VS_CMAKE.exe : fatal error LNK1120: 2 unresolved externals
ninja: build stopped: subcommand failed.

**Comment by jtv** [comment]
By the way, do have a look at #743 in case it's the same issue.  I must warn you though: there's a long discussion there!  If memory serves, it boiled down to "we do not have great package managers in C++."

**Comment by tt4g** [comment]
As discussed in the issue linked in @jtv's comment, vcpkg does not set `CMAKE_CXX_STANDARD` when building CMake.
CMake looks at the `CMAKE_CXX_STANDARD` variable to determine the C++ version of libpqxx to build.

Because `CMAKE_CXX_STANDARD` is not set, libpqxx is built with the default C++ version.
And if the project's C++ version is not the default, a link error will occur.

The solution is to use the vcpkg triplet to force vcpkg to set the `CMAKE_CXX_STANDARD` when it builds libpqxx.
See: https://github.com/microsoft/vcpkg/pull/34941#issuecomment-1795330700

**Comment by peterritter** [comment]
ok, thanks for this comment!!  I'm going to have to think about this a little. Everything is so complicated these days.  I just installed libpqxx using:

FetchContent_Declare(
        libpqxx
        GIT_REPOSITORY https://github.com/jtv/libpqxx.git
        7.8.1         # Replace with the specific tag/commit you want
)

And this worked and I no longer have link errors although I had to link against 'pqxx' instad of 'libpqxx::pqxx'. I suppose this is because it's part of my own project now. I did notice that there is a 'version' mismatch. I clearly used tag 7.8.1 but PQXX_VERSION is definitely set to '7.9.0' . I'll create another issue just to point that out.

**Comment by tt4g** [comment]
`PQXX_VERSION` issue #758

**Comment by jtv** [comment]
@peterritter Some blockers for the next release have cleared up in recent days, so hoping to release 7.9.0 soon, and hopefully the problem won't happen with that.

However in the grander scale, we're still stuck with the problem that all package managers encourage us to link things together that may or may not actually be compatible, because of different language versions etc.
