### ISSUE TITLE
 Bind results of selects directly to a variable of type std::vector for array types

### ISSUE THREAD

**Issue by realnn** [jtv/libpqxx#753]
Hello,

I am a new user of psql&libpqxx, I apologize if my question is stupid.

Is there a way to bind the result of a select query directly to a variable of type std::vector, let's say std::vector < int >  , for columns that are defined as arrays?
When I say directly I mean without having to go through a conversion from string to int (at least not explicit, preferably nor implicit, either).
I have found the array_parser, as_array, get_next functions, but they seem to always work with string representation (conversion from string to something else).

For instance, I have found a way to bind std::vector variables for insert operations

    pqxx::connection c("host=localhost dbname=sensordb user=user_test password=user_test_passwd");
    pqxx::work          txn(c);
    c.prepare("myInsert", "INSERT INTO sensors_table VALUES($1)");

    std::vector<int>    sensValues = {1001, 1002, 1003, ... (not real code here) ... , 2001, 2002, 2003};

    txn.exec_prepared("myInsert", sensValues);
    txn.commit();
	
I would like to have the same mechanism at query time, too. Reasons:
- the arrays I have are quite big (hundreds/thousands of values for any given row) - to convert them from string to vector<int> is simply too costly in terms of time (more or less the same amount of time as to insert the data, and a few times more than retrieving the data without doing any conversion - tested with array_parser and with istringstream)
- I want to send the data further on via network using a messaging library - this library knows how to handle std::vector, so I would much prefer to use it as data structure for sending it, rather that sending string representation (which is much bigger in size), or compressing it, protobuffing it, etc.

If it's not possible, what are the alternatives? Thank you !

**Comment by jtv** [comment]
If you want `int` values out of the query, there will have to be a conversion, there's just no way around that.  But something is not quite clear to me in your question: at one point you're talking about using a query's _result_ data, but in other places it looks like you're talking about passing your data as _parameters_ to a query.

(The "at query time" confuses me further, since all of this happens at query time.)

**Comment by realnn** [comment]
Hi, thanks for the quick reply and sorry for the confusion/s.

By "query", I meant "select"/reading from the DB as opposed to "insert"/writing to the DB.
What I meant, also - the same way as we can use std::vector as a parameter  for inserts (although I suspect there is a conversion here, too, from int to string), I was looking for a way to use a std::vector for selects, too  - not necessarily as a function (output) parameter, but as a variable to which I can assign some result/s of the "select" statements (again, preferably without any conversion, supposing that psql holds int values differently than strings).

The final goal being two-fold: speed (by avoiding the string to int conversion, or, to be more precise, parsing) and memory/disk/network throughput (std::vector<int> being more compact than a plain string containing int values of 6 digits each, let's say, plus some separators).
Let's say that the space constraint can be accepted and worked-around, but I don't see how I can overcome the speed constraint - for instance, reading (select *) from 100k rows takes 2 seconds, but afterwards, converting/parsing the array values from string to int takes an extra 15 seconds (and that would be just one day worth of data).

The definition of the table is quite simple, too: a timestamp as first column (again, returned as string, I was hoping for a long long, or something), and then a couple of these arrays of integers as next columns. 
Anyway, if psql stores everything as strings, then I might just as well store the whole array as one single string, since I use only timestamps in select statements (half joking). 
The only solution for my purpose (speed) would be, I think, to use BYTEA data type for the arrays. I will benchmark it a bit and see what it gives.

Thank you and sorry again for my possible lack of clarity, it's been only a week since I started this project.

**Comment by jtv** [comment]
The conversion part is a recurring discussion...  Let me just address that first: unfortunately, _a conversion is needed._  There are two ways to transmit the data: "text" and "binary."  In libpqxx I support only the text format, which needs conversion.  However the binary format is not as trivial as it sounds either — an `int` in binary format is not something as straightforward as a simple 32-bit integer or anything like that.  It's variable-length.  It too would need conversion, just potentially a faster one than the text conversion.  On the bright side, libpqxx delegates the text conversions to the C++ standard library where it can, meaning that a lot of optimisation has gone into them.

What I recommend for a use-case like yours is to _stream_ the query result.  In that way of working, you write a loop which on each iteration receives the values for one row, with the conversions already done.  You can use that to write values to a `std::vector`, or even just to process them directly:

```cxx
pqxx::work tx{my_connection};
for (auto [id, name, value] : tx.stream<int, std::string_view, double>(
    "SELECT id, name, value FROM my_table"))
{
    process_row(id, name, value);
}
```

This goes through the results one row at a time.  In my example one of the columns is a text column, for which I used `std::string_view`.  However the buffer containing the string is only valid for the one iteration where you receive the value; if you wanted to _store_ the values you might want to receive them as `std::string` instead, or for maximum efficiency, copy them all into a single big buffer like you said.

As for speed, the last time I benchmarked it, for larger result sets this method in libpqxx was actually faster than reading a result set of `int` in raw C and doing no conversion on it at all!

**Comment by jtv** [comment]
Of course you can skip the conversion if you need it.  I still don't really understand what you're trying to do exactly, but if it works, that's good news.

**Comment by realnn** [comment]
This is the part I am most interested in

> Of course you can skip the conversion if you need it. 

Here is some pseudo/code, I hope it makes it clear
`
# some SQL code
CREATE TABLE points_table (
    ts timestamp without time zone NOT NULL,
    x_points integer[] NOT NULL,
    y_points integer[] NOT NULL,
    z_points integer[] NOT NULL
);

INSERT INTO points_table VALUES ('2023-11-20 15:39:07.829', '{37187,37188,37295,37296,37297,37298}', '{67,260848,208,2786,10493,6693}', '{37298,37299,37406,37407,37408,37409}');



// some pseudo/C++ code
void pqxx_rapid_function()
{
    std::vector<int>  &xPoints;
    std::vector<int>  &yPoints;
    std::vector<int>  &zPoints;
    xPoints.reserve(10000);
    yPoints.reserve(10000);
    zPoints.reserve(10000);
	
    // get all rows in some return type
    pqxx::some_result_type all_rows = pqxx::get_all_rows_from_table("points_table");
	
	for (auto currIt(all_rows.begin()); currIt != all_rows.end(); ++currIt)
	{
        xPoints.clear();
	    yPoints.clear();
        zPoints.clear();
	
	    // pq/pqxx code that would fill in above vectors with the ints from corresponding column of current row
	    // for columns with thousands of values, the conversion/parsing from string to std::vector<int> values takes a long time
		xPoints = pqxx::getIntValues((*currIt)[1]);
		yPoints = pqxx::getIntValues((*currIt)[2]);
	    zPoints = pqxx::getIntValues((*currIt)[2]);
	}
}
`

**Comment by jtv** [comment]
All I can add is that it does sound like streaming the query may still be useful for your use-case.

**Comment by tt4g** [comment]
As already commented, PostgreSQL returns strings or binaries as the result of the query.
And libpq and libpqxx cannot guess how many dimensions the query result array will have.

If you want to save the cost of converting array data to `std::vector`, you will have to use `pqxx:array_parser`.
This should consume less memory than using `pqxx:array<TYPE>`, but requires the developer to write the array parsing process

The libpqxx array parsing test is in https://github.com/jtv/libpqxx/blob/7.8.1/test/unit/test_array.cxx.
It will be helpful to understand how `test_array_multiple_values()` and `test_array_roundtrip()` use `pqxx::array_parser` to parse `integer[]`.

**Comment by realnn** [comment]
Thank you all for the comments!
Issue closed.
