### ISSUE TITLE
Efficient UUIDs

### ISSUE THREAD

**Issue by kylepl** [jtv/libpqxx#756]
Hi, I use UUIDs quite a bit, and am currently accessing them from results using `as<std::string>()`.

While I understand I can write specializations to convert it to another type (e.g. `as<MyUUIDType>`) - is it possible for it to never be a string? From what Postgres returns itself, directly to my saving of it?

That was not quite clear to me (possibly possible with pure `libpq`)?

Thanks!

**Comment by jtv** [comment]
What postgres itself returns across the wire _is_ a string.  The could be a more efficient representation in binary mode, but those formats are not actually documented (nor guaranteed to remain stable) so liboqxx does not support that.

I'm not sure what you have in mind for it "never" being a string...  It's up to your code to dictate what type you want to use on your end, and libpqxx does not use any knowledge of the server-side type.  If you had a string that happened to be a valid uuid, that would convert in exactly the same way as an actual uuid value, and libpqxx would not see the difference.

**Comment by jtv** [comment]
Oh one thing...  If speed is an issue, you'll probably be better off covering to `std::string_view` or `char const *` - it may reduce the number of memory allocations for all those `std::string`.  Depends on your compiler's Small String Optimisation details.

**Comment by kylepl** [comment]
Thanks for the info and explanation of binary mode.

While I don't think `int128_t` is an actual type, that would be my ideal case for a UUID - it's returned as binary as `int128_t`, and I store it as that, and I add it for substitution like that. But of course if it can't be returned like that, then it will at some point be a string.

And ack on the Small String Optimization.
