### ISSUE TITLE
PQXX_VERSION says '7.9.0' but I used tag 7.8.1

### ISSUE THREAD

**Issue by peterritter** [jtv/libpqxx#758]
Ok, I fixed my ealier linking error by using FetchContent instead of vcpkg. It all works now! Thanks for the earlier responses! 

I was checking the version in my code just to reconcile things and now PQXX_VERSION shows 7.9.0 which doesn't even look like it's listed here on github. Just FYI.

 This is what I did in my cmake:

FetchContent_Declare(
        libpqxx
        GIT_REPOSITORY https://github.com/jtv/libpqxx.git
        7.8.1         
)

**Comment by tt4g** [comment]
You are getting the latest source code because you have not been able to specify a version.
Please add the missing argument name `GIT_TAG`.

```diff
 FetchContent_Declare(
 libpqxx
 GIT_REPOSITORY [jtv/libpqxx.git](https://github.com/jtv/libpqxx.git)
-7.8.1
+GIT_TAG 7.8.1
 )
```

See: https://cmake.org/cmake/help/v3.28/module/FetchContent.html
