### ISSUE TITLE
Is there a better way of doing this ?

### ISSUE THREAD

**Issue by pkfox** [jtv/libpqxx#766]
Hi All, I have the function shown below that returns a vector<int> from a setof int function on the pg side, all is working ok, is there a way I can populate a vector without using a loop ?

<pre>
std::vector<<int>> GetData()
{
	std::vector<<int>> Primes;
	std::string ConnectionString = "host=localhost port=5432 dbname=commands user=postgres password=******";
	pqxx::connection PGConnection = pqxx::connection(ConnectionString);
	PGConnection.prepare("getprimes", "select getprimes()");
	pqxx::transaction txn(PGConnection);
	pqxx::result r(txn.exec_prepared("getprimes"));

	for (auto const& row : r)
	{
		for (auto const& field : row) 
			Primes.push_back(field.as<int>());
	}
	txn.commit();
       return Primes;
}
</pre>
I thought it was possible to populate a vector via its constructor using the iterator of the pqxx::result like this
<pre>
Primes = std::vector<<int>>(r.begin(), r.end());
</pre>

But it doesn't compile, I get this error (shortened for brevity)
<pre>
	C2440	'initializing': cannot convert from '_Ty' to '_Objty'
        with
        [
            _Ty=pqxx::const_result_iterator::reference
        ]
</pre>
Any advice/help much appreciated ( it should show int in between the <> but I doesn't appear on here
I'm building on Visual Studio 2022 using std=c++17

**Comment by pkfox** [comment]
Hi Jeroen, to answer your question first
I don't really see why you're going to the trouble of using a prepared query for this
It's because I don't know libpqxx very well and thought there must be a cleaner way , I know there is always a loop of some sort going on but if I can avoid a visible one I will
Thank you for your excellent suggestions, I like the lambda method best but both are nice to know. Thanks again.

**Comment by jtv** [comment]
OK, I'll close the ticket then.
