### ISSUE TITLE
Transaction declaration error

### ISSUE THREAD

**Issue by pkfox** [jtv/libpqxx#767]
Hi all, firstly I apologise for bombarding you with noobie questions but I'm keen to learn this stuff.
I have a class
```cxx
#ifndef PGMERSENNE_H
#define PGMERSENNE_H
#include <pqxx/pqxx>
#include <gmpxx.h>
#include <string>
#include <sstream>
#include <iostream>
#include "PrimeStatus.h"
#include "MersennePrime.h"
#include "Utils.h"

class PGMersenne
{
public:
	PGMersenne();
	PGMersenne(mpir_ui Mersenne,std::string MersenneResult,int Probability);
	std::size_t EditMersenne();
	void GetData(std::vector<int>& Primes);
private:
	MersennePrime MP;
	mpir_ui Mersenne;
	std::string MersenneResult;
	int Probability;
	std::string PrimeProbabilityText;
	std::string ConnectionString = "host=nuc port=5432 dbname=commands user=postgres password=Giraffes09";
	pqxx::connection PGConnection = pqxx::connection(this->ConnectionString);
	pqxx::transaction PGTransaction = pqxx::transaction(this->PGConnection);
        // The compiler doesn't like the line above. It complains about argument list is missing for class template .
};
#endif
```

The compiler doesn't like the declaration of pqxx::transaction , It complains about argument list is missing for template
pqxx::transaction
Any ideas guys ?

**Comment by tt4g** [comment]
The error message says it all.
Two parameters `ISOLATION` and `READWRITE` are missing.

See: https://github.com/jtv/libpqxx/blob/21afb0d6ec3d31424df6b7aac04c6b20c55c0a65/include/pqxx/transaction.hxx#L68-L71

For most use cases, `pqxx::work` (or `pqxx::read_transaction`) is sufficient.

You can also specify these parameters exactly.
Please check https://github.com/jtv/libpqxx/blob/7.8.1/include/pqxx/isolation.hxx for the template parameter values (`enum`) that can be specified.

**Comment by jtv** [comment]
Thanks once again @tt4g for stepping in before I've even seen the question!

I'm going to PGConf.eu this week so may be less available.

**Comment by jtv** [comment]
@pkfox don't be too worried about asking newbie questions - provided you've done some looking for yourself first, these can be useful indicators of what needs to be clearer.

One of the hardest things to do, I find, is to put yourself in the shoes of someone who doesn't know something you do.

I've edited your question for formatting: I hadn't tried `<pre>` myself but evidently it doesn't work on Github.  The triple backticks do, and when you add the right language descriptor, you get syntax highlighting as well.  Win.  :-)

One note for future reference: before you report a problem (in fact even when you first try to solve it yourself), try to reduce it to the _absolute minimal example_ that will reproduce it without further context.  Whittle away as many details as you can while still reproducing the problem.

Often that process itself will lead you to the answer, and if not, it'll also be easier for others when you ask for help.

**Comment by pkfox** [comment]
@tt4g thanks for the help, I'm a bit confused as to why pqxx::transaction works (compiles) when declared in a function but not in a class definition
```
void MyMethod()
{
    pqxx::transaction txn(this->PGConnection);
}
```
the above compiles ok, thanks again

**Comment by tt4g** [comment]
In that writing style, the default template parameters are used, so it can be compiled.
The first writing style requires a template parameter to be specified.
This is a difficult specification to understand in C++. It is not beginner-friendly.

**Comment by pkfox** [comment]
@tt4g how would I specify the parameters ? thanks again

**Comment by jtv** [comment]
To get the defaults, you'd use the class `pqxx::transaction<pqxx::isolation_level::read_committed, pqxx::write_policy::read_write>`.

**Comment by jtv** [comment]
And `pqxx::work` is nothing but a shorthand for that type.

**Comment by pkfox** [comment]
Thanks you both @tt4g  and @jtv I now declare the transaction thus and all is cool and groovy - I'll try and not pester you too much  :-)
```CXX
pqxx::work PGTransaction = pqxx::work(PGConnection);
```

**Comment by jtv** [comment]
Excellent.  I'll close the ticket.
