### ISSUE TITLE
This doesn't compile on Linux

### ISSUE THREAD

**Issue by pkfox** [jtv/libpqxx#768]
Hi all, I recently asked for help #766 on how to best populate a vector of int and received two excellent examples from @jtv both methods compile fine on Windows using Visual Studio 2022 (std:c++17)
When I attempt to compile on my Debian box I get errors
```CXX
Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux

g++ -std=c++17 Example.cpp  -lpq -lpqxx  -o example

‘class pqxx::result’ has no member named ‘for_each’
```
and receive a similar error using the streaming method
```CXX
class pqxx::transaction<>’ {aka ‘class pqxx::transaction<>’} has no member named ‘stream’
```
Both boxes have the same version of libpqxx, any ideas guys ?

**Comment by tt4g** [comment]
I don't know the reason for the error message because `Example.cpp` is not provided.
Please provide the source code.

**Comment by tt4g** [comment]
It is odd that `for_each` is missing.
Do you know what version of libpqxx you are using?
You can check by printing the `PQXX_VERSION` macro.


```cpp
#include <iostream>
#include <pqxx/pqxx>

int main()
{
    std::cout << "libpqxx version: " << PQXX_VERSION << std::endl;
    return 0;
}
```

**Comment by tt4g** [comment]
By the way, there is a missing space between `host` and `post`.

```diff
 int main()
 {
     std::vector<int> Primes;
-    pqxx::connection c("host=localhostport=5432 dbname=commands user=postgres password=*******");
+    pqxx::connection c("host=localhost port=5432 dbname=commands user=postgres password=*******");
      pqxx::work w(c);
```

**Comment by jtv** [comment]
It does look like an older version.  That `for_each` function is _relatively_ new.

**Comment by pkfox** [comment]
> It is odd that `for_each` is missing. Do you know what version of libpqxx you are using? You can check by printing the `PQXX_VERSION` macro.
> 
> ```c++
> #include <iostream>
> #include <pqxx/pqxx>
> 
> int main()
> {
>     std::cout << "libpqxx version: " << PQXX_VERSION << std::endl;
>     return 0;
> }
> ```

I'm in the process of reinstalling libpqxx using vcpkg - will run your code as soon as I'm up and running - thanks

**Comment by jtv** [comment]
Good news.  Packaged versions of libpqxx with binaries are generally not a great idea, sadly.

I'll close the ticket.
