### ISSUE TITLE
Prepared Statement Unit Test Run Aborts in Visual Studio

### ISSUE THREAD

**Issue by rocksolidwebdesign** [jtv/libpqxx#77]
Occuring in
 - Visual Studio 2015
 - Visual Studio 2017

Occurring as of 19f22d869611c2bd8afbeb2b09e509457555944f

Performing 64-bit nmake builds with e.g. `vcvarsall.bat amd64`

# Test Runner Aborts on Prepared Statement in UnitStaticDebug

On running static unit tests in debug mode, prepared statement test is aborted

Steps to reproduce:

```
nmake /f win32\vc-libpqxx.mak STATIC
nmake /f win32\vc-test-unit.mak ALL DEBUG=1
cd UnitStaticDebug
.\runner.exe
```

example output:

```
Running: test_exceptions

Running: test_exec_params

Running: test_infinities

Running: test_notification

Running: test_pipeline

Running: test_prepared_statement
```

a GUI dialog window then opens with:

```
Debug Assertion Failed!

Program: C:\WINDOWS\SYSTEM32\MSVCP140D.dll
File: c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\vector
Line: 1820

Expression: vector subscript out of range

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)

[Abort] [Retry] [Ignore]
```

With only very small variations, e.g. VS2015 reports line 1218 and a slightly different location for vector

The unit tests work fine in release mode, it's using DEBUG=1 that causes the issue.

I can confirm with an independent test case that the problem at least happens with `exec_params` but maybe other functions too.

**Comment by jtv** [comment]
That sounds like a bug in the handling of the arguments arrays, but I'm not seeing what it could be.  There _used_ to be a bug like this, but that one was fixed.  I tried reproducing the problem by replacing all array-style indexing of vectors with `at()`, but it didn't find any problems.

Is there any chance the debugger could give you a traceback?

**Comment by jtv** [comment]
Is the problem still there in 6.2.2?  It involved a rewrite of the piece of code where this problem would probably have occurred.

**Comment by jtv** [comment]
Would be really interested to hear whether this problem was still occurring!

**Comment by rocksolidwebdesign** [comment]
this appears resolved now, thanks!
