### ISSUE TITLE
Streams as C++20 ranges

### ISSUE THREAD

**Issue by rbrugo** [jtv/libpqxx#771]
Hi,
streams are already compatible with range-based for, but I can find no way to use them in a pipeline with C++20 ranges, for example:
```cpp
// Example 1
auto stream1 = tx.stream<int, int>("SELECT width, height FROM table");
auto areas = stream1
           | std::views::transform([](auto tp) { auto [w, h] = tp; return w * h; })
           | std::ranges::to<std::vector>();  // C++23
           
// Example 2
struct person
{
    std::string name;
    int age;
    std::string address;
};
auto build(std::string, int, std::string) -> person;
auto stream2 = tx.stream<std::string, int, std::string>("SELECT name, age, address FROM people");
for (auto const & person :  stream2 | std::views::transform(build)) {
    ...
}
```
If I understand correctly, the first compilation error I get boils down to the fact that `decltype(stream.begin())` does not model the [`std::input_iterator` concept](https://en.cppreference.com/w/cpp/iterator/input_iterator), so `std::ranges::begin` can't work with the stream.
There is any plan to support this kind of iteration?

**Comment by jtv** [comment]
It wasn't _designed_ to work as an `input_iterator`, no.  But if you have a use for it, that helps.  Did the error say by any chance exactly which requirements were not satisfied?

I deliberately kept the iterator class out of view so I'd have elbow room for a future better implementation.  I was thinking perhaps as a generator, but we'll see.  Main thing is that it should perform well.

**Comment by rbrugo** [comment]
Compiling the following code:
```cpp
#include <pqxx/pqxx>
#include <ranges>

int main()
{
    auto connection = pqxx::connection{""};
    auto tx = pqxx::work{connection};
    auto stream = tx.stream<int>("");
    using iterator = decltype(stream.begin());
    // using sentinel = decltype(stream.end());
    std::input_iterator auto it = stream.begin();
    //std::sentinel_for<iterator> auto end = stream.end();
}
```
the requirement is not satisfied here:
```
/usr/include/c++/13.2.1/concepts:139:13:   required for the satisfaction of ‘assignable_from<_Tp&, _Tp>’ [with _Tp = pqxx::internal::stream_query_input_iterator<int>]
...
/usr/include/c++/13.2.1/concepts:142:10:   in requirements with ‘_Lhs __lhs’, ‘_Rhs&& __rhs’ [with _Lhs = pqxx::internal::stream_query_input_iterator<int>&; _Rhs = pqxx::internal::stream_query_input_iterator<int>]
/usr/include/c++/13.2.1/concepts:143:17: note: the required expression ‘__lhs = static_cast<_Rhs&&>(__rhs)’ is invalid
  143 |         { __lhs = static_cast<_Rhs&&>(__rhs) } -> same_as<_Lhs>;
      |           ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by jtv** [comment]
Does #772 solve the probem?

**Comment by rbrugo** [comment]
The following code
```cpp
pqxx::connection conn;
pqxx::work tx{conn};
std::ranges::input_range auto s = tx.stream<int>("SELECT generate_series(1, 10)");
auto res = s | std::views::transform([](std::tuple<int> n) { return std::get<0>(n) * 2; });
fmt::print(">>> {}\n", res);
```
compiles in C++20 mode and gives the right result:
```
>>> [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
```
So #772  solves the problem.

Thank you!

**Comment by jtv** [comment]
Nice.  The post-increment operator is not something you'd actually want to use, but why would one?  I'm not sure why it's even in all these concepts.
