### ISSUE TITLE
Stream fails parsing empty `varchar`/`text` fields

### ISSUE THREAD

**Issue by rbrugo** [jtv/libpqxx#774]
With a table prepared as follow:
```sql
CREATE TABLE test (
    id SERIAL PRIMARY KEY,
    description VARCHAR(255) -- Adjust the length as needed
);
INSERT INTO test (description) VALUES ('');
```
The following code compiles, but an inner assertion fails:
```cpp
#include <pqxx/pqxx>
#include <fmt/core.h>

int main()
{
    auto connection = pqxx::connection{...};
    auto tx = pqxx::work{connection};
    auto stream = tx.stream<std::string>("SELECT description FROM test");

    for (auto const & [s] : stream) {
        fmt::print(">{}<\n", s);
    }
}
```
With error:
```
test: [...]/.conan2/p/b/libpqbb24f7e3aca8d/p/include/pqxx/internal/stream_query.hxx:270: TARGET pqxx::internal::stream_query<TYPE>::parse_field(pqxx::zview, std::size_t&, char*&) [with TARGET = std::__cxx11::basic_string<char>; TYPE = {std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >}; std::size_t = long unsigned int]: Assertion `offset < std::size(line)' failed.
[1]    604409 IOT instruction (core dumped)  build/test
```
Replacing the `tx.stream` with a `tx.query` seems to solve the problem.

I don't know if it helps, but I'm using `libpqxx/7.8.1` via conan, with GCC 13.2.1.

**Comment by pkfox** [comment]
I just tried your code and it worked perfectly with a text field I'm using 7.9

**Comment by pkfox** [comment]
I missed the EMPTY part of your question - I now get the same result as you

**Comment by jtv** [comment]
Ouch!  That is a painful bug.  And what a day for my laptop to fail, too.  :-(

It turns out that streaming a row of data ending in an empty field (not null, but actually empty) hit a corner case that I didn't think was going to happen.  Good thing that assertion was there.

I'm putting a fix up.  Took a bit longer because... well...  time of year plus broken laptop.

**Comment by pkfox** [comment]
@rbrugo I can confirm the latest version of this lib fixes this issue
