### ISSUE TITLE
Update source question

### ISSUE THREAD

**Issue by pkfox** [jtv/libpqxx#778]
I installed libpqxx from source and built/installed using the configure/make method. My question is, is a git pull and then a rebuild make install all that is required to keep up to date ?

**Comment by jtv** [comment]
My one point of doubt is: I'm not sure what `make install` does when a file disappears or gets renamed in a newer version.  The scripting for these things is all automatically generated, so I don't know the details.  I _think_ it should be fine but it may help to uninstall before installing a newer version.

Also, two recommendation:
1. To keep things neat, build in a temporary directory, which you discard after the install.  It's called an _out-of-tree build:_ the source tree is in one location and your build tree in another.
2. Use git tags to pull the latest released version, unless you're sure you want to track the very latest changes.

**Comment by pkfox** [comment]
@jtv I deleted the build folder and reinstalled from scratch , I can confirm your stream empty string fix has worked

**Comment by jtv** [comment]
Nice.  I guess we're done with this ticket?

**Comment by pkfox** [comment]
I find it cleaner deleting my build folder and then 
``` 
git clone git@github.com:jtv/libpqxx.git BuildPG
cd BuildPG
./configure
make
make install
```

**Comment by pkfox** [comment]
All done

**Comment by jtv** [comment]
Nice.  Thanks for confirming @pkfox - and happy new year!
