### ISSUE TITLE
Is calling to exec_prepared() considered as blocking operation ?

### ISSUE THREAD

**Issue by atari83** [jtv/libpqxx#781]
Hello!

So I'm running PostgreSQL 15.4 on a remote host and defined a simple void function (returning no values) in there. The function is basically calling one INSERT INTO command.

Then in my program, first I have used prepare() to make prepared statement/function for calling the function.
and then used it like this in my program:

```
        try
        {
            pqxx::work tx1{psql_db};
            tx1.exec_prepared( "ins_rpt", val1, val2);
            tx1.commit();
        }
        catch (std::exception &e)
        {
              .....
        }
```

Now, I just want to know if calling to exec_prepared() actually block the thread until the record get inserted (or failed) to database or not ?

Thanks.

**Comment by jtv** [comment]
_Yes,_ just about everything you do in libpqxx blocks until it completes.

(From memory, the exceptions are `pqxx::connecting` for asynchronous connection; polling for notifications; and `pqxx::pipeline`.)

**Comment by atari83** [comment]
Got it! Thank you Jeroen :)
