### ISSUE TITLE
Is it possible to build libpqxx without SSL support

### ISSUE THREAD

**Issue by afpgit** [jtv/libpqxx#783]
I am having difficulty using `libpqxx` in my application due to a version conflict. `libpqxx` uses OpenSSL 3 and my application uses OpenSSL 1.1.1. I can't upgrade from 1.1.1 to 3. I installed `libpqxx` using `vcpkg`, which brings in OpenSSL 3. 

- Is it possible to build `libpqxx` without the SSL support in Linux? 
- If `vcpkg` is not an option, can building from source remove the dependency to OpenSSL? 
- If none of these work, is there any way to get an older version of `libpqxx` with OpenSSL 1.1.1 support?

**Comment by jtv** [comment]
You'd have to build _libpq_ without SSL.  That's where the SSL support is - libpqxx doesn't interact with the SSL libraries directly.

**Comment by jtv** [comment]
@afpgit I'll close this ticket now.
