### ISSUE TITLE
CMakeLists.txt update c++ standard to 20

### ISSUE THREAD

**Issue by leleftheriades** [jtv/libpqxx#785]
Curently the cmake file is configured to 17 standard

**Comment by jtv** [comment]
Exactly.  I plan to stop supporting C++17 soon, but then the whole game will just start over again with C++20 vs. C++23.

**Comment by leleftheriades** [comment]
I tried to link the library which got built with default options to a c++20 project and got linker errors in msvc, so i assumed the support for c++17 was dropped that was why i raised an issue. Thank u, i will use the cmake command line argument to ensure i get the version i want

**Comment by jtv** [comment]
Yes, it's a thorny issue that the package managers are totally ignoring: you can't _reliably_ link code compiled in one C++ version to code compiled in another.

Perhaps the worst part is that it *sometimes* works.  At least when it breaks consistently you will know when it needs fixing.
