### ISSUE TITLE
Usage with meson?

### ISSUE THREAD

**Issue by Bluebotlabz** [jtv/libpqxx#789]
I was wondering if there is any way to use this library in a meson project, I've already tried adding it as a cmake submodule but with no success

Thanks

**Comment by tt4g** [comment]
meson is not supported.
It is better to ask [meson repository](https://github.com/mesonbuild/meson) how to import CMake modules into meson, because I don't know if meson experts are looking here.

**Comment by Bluebotlabz** [comment]
Found the issue, for whatever reason, Meson seems to be building the root directory of the repo instead of the `src/` folder...
