### ISSUE TITLE
More Documentation for INSERT

### ISSUE THREAD

**Issue by anthonygclark** [jtv/libpqxx#790]
Hey all,

First, thanks so much for your time and effort on `libpqxx`!

As a first time user, coming from things like psycopg and sqlalchemy, I'm having trouble finding enough references for the INSERT path. There is plenty of documentation and tests are around SELECT. Some of my initial attempts have failed while figuring out how to use both the stream interface and the prepared statement interface for INSERT with just the doxygen API, FAQ, and concept documentation.

A good example would go a long way here and I just couldn't find one in the documentation.

Thanks!

**Comment by anthonygclark** [comment]
Maybe I posted too soon since the answer is simply `prepared statements`. It's just a bit confusing without any explicit examples. It didn't take too much focus time to sort it out;) Cheers! 

Closing.

**Comment by jtv** [comment]
Thanks @anthonygclark.  Perhaps the documentation ought to link to the part of the PostgreSQL docs that describe SQL statements...  I don't think I can document all such things myself, because it would become too much to maintain.

By the way, if performance is of the essence, then you can do fast bulk inserts using `pqxx::stream_to`.

**Comment by anthonygclark** [comment]
@jtv I appreciate the reply - I know you must be busy. I think I just tried to do generally unsupported things. Either unsupported by `libpq` or by `libpqxx` naturally. 

Specifically trying to use placeholders for schema name. In my case, I have a database `D` and a schema `D.S`. So my insert via "INSERT INTO D.B(data) VALUES 1234567" manually works, but I couldn't translate into `libpqxx` prepared statements with placeholders.

```c++
// simplified
pqxx::connection conn{...}; // connect to database 'D'
conn.prepare("foo", "INSERT INTO $1.$2(data) VALUES $3");
pqxx::work w{conn};
auto r = w.exec_prepared("foo", "first", "second", 1234567);
w.commit();
```

The runtime errors is:

```
terminate called after throwing an instance of 'pqxx::syntax_error'
  what():  Failure during '[PREPARE foo]': ERROR:  syntax error at or near "$1"
LINE 1: INSERT INTO $1.$2(data) VALUES ($1)
                    ^
```

(I tried various syntax for $1.$2, like "$1" and "$1.$2")

I cannot determine if `libpqxx` supports this or if I should just use some string concats. I also couldn't figure out from the documentation IF AND WHEN I should escape except for the case of taking raw user input and pushing into SQL. I think on the topic of documentation, the limitations (like above, if it's actually a limitation) would be helpful if documented.

Again, thanks so much for your work!

**Comment by KayEss** [comment]
libpqxx just forwards the text to postgres to deal with, so there's nothing for libpqxx or libpq to do.

You'll have to check the postgres documentation for the version you're running on your server. But, I don't believe you can use the `$` syntax to specify a schema.

**Comment by jtv** [comment]
I suspect that might even be a limitation at a lower level...  I guess doing this would make parameters kind of pointless.  The main reason for parameters is to prevent SQL injections - you don't want users to insert values that could change the meaning of the query.  Passing a schema name as a parameter does kind of change that meaning.

Of course I would guess that you're not using a user-supplied string here.  In that case, you can just ignore prepared statements, and use string concatenation to produce your query.  You can still pass your parameters by running the statement as a parameterized statement.
