### ISSUE TITLE
have libpqxx subscribe to a channel

### ISSUE THREAD

**Issue by afpgit** [jtv/libpqxx#796]
I am trying to listen to an event in a PostgreSQL database when a table is updated. The trigger is created in the database and I would like to have `libpqxx` listen to the trigger signal.

I have tried the following code:

```
pqxx::notification_receiver receiver(conn, "my_event");
conn.prepare("LISTEN my_event");
while (true) {
    // Some sort of receiver wait

    // Getting info about the channel
}
```

The code logic makes sense but the compiler is complaining that variable type `pqxx::notification_receiver` is an abstract class. How can I create a derived class to be able to subscribe to the event?

**Comment by jtv** [comment]
You derive your own class from `pqxx::notification_receiver` and overload the function call operator to handle a notification in your own way.  See [test/unit/test_notification.cxx](../blob/master/test/unit/test_notification.cxx) for an example.

It's a pretty old style of design now.  I think in libpqxx 8.0 you'll just register a lambda.  But this was once the standard way to handle these things, and it's been hard to change.

**Comment by afpgit** [comment]
Thank you. Would you point me to an example of the new style, please?

**Comment by jtv** [comment]
Not there yet!  I still have to write that, and I'm still unsure what to do about lambda lifetimes to be honest.

It'll be a while before 8.0 comes out.  There will be some fairly radical changes.

**Comment by jtv** [comment]
Can we close this ticket now @afpgit ?
