### ISSUE TITLE
subscribing to two trigger channels

### ISSUE THREAD

**Issue by afpgit** [jtv/libpqxx#797]
I am trying to subscribe to two different notifications using `libpqxx`. I found this [unit test][1] which I modified to serve my objective.

```
class TestListener final : public pqxx::notification_receiver
{
  bool m_done;

public:
  explicit TestListener(pqxx::connection &conn, std::string Name) :
          pqxx::notification_receiver(conn, Name), m_done(false)
  {}

  void operator()(std::string const &, int be_pid) override
  {
    m_done = true;
    std::cout << "Received notification: " << channel() << " pid=" << be_pid
              << std::endl;
  }

  bool done() const { return m_done; }
};

```

I am trying to create a function that simply waits for the notifications and exits as soon as it receives them.

```

// ...

void waitForChannel(TestListener &L){
    while(!L.done()){};
    std::cout << "received notificaton for channel " << L.channel() << "\n";
};

int main(){
    
    // assume the connection is made
    // ...

    TestListener L1{conn, "channel1"};
    TestListener L2{conn, "channel2"};

    pqxx::perform([&conn, &L1] {
        pqxx::work tx{conn};
        tx.exec0("NOTIFY " + tx.quote_name(L1.channel()));
        tx.commit();
    });

    pqxx::perform([&conn, &L2] {
        pqxx::work tx{conn};
        tx.exec0("NOTIFY " + tx.quote_name(L2.channel()));
        tx.commit();
    });


    while(true){
        waitForChannel(L1);

        waitForChannel(L2);
    }

    return 0;
}
```

However, I have not been able to receive any signal and it gets stuck in `while(!L.done())`.

Is this the correct way to listen to multiple different channels?

Could someone kindly help?

  [1]: https://github.com/jtv/libpqxx/blob/master/test/test87.cxx

**Comment by tt4g** [comment]
You forgot to call function `pqxx::connection::get_notifs()` to receive notifications.

- https://github.com/jtv/libpqxx/blob/2ffb711bc4e9b086bf0c549a9c22b19f61ab5476/include/pqxx/connection.hxx#L481-L503
- https://github.com/jtv/libpqxx/blob/2ffb711bc4e9b086bf0c549a9c22b19f61ab5476/src/connection.cxx#L560-L611

> [!Note]
> There is also a convenience function `pqxx::connection::await_notification()` that waits for N seconds until notified.
>
> - https://github.com/jtv/libpqxx/blob/2ffb711bc4e9b086bf0c549a9c22b19f61ab5476/include/pqxx/connection.hxx#L505-L533
> - https://github.com/jtv/libpqxx/blob/2ffb711bc4e9b086bf0c549a9c22b19f61ab5476/src/connection.cxx#L1041-L1068

**Comment by afpgit** [comment]
I replaced 

```
while(true){
    waitForChannel(L1);
    waitForChannel(L2);
}
```

with

```
while (true) {
    conn.await_notification();
}
```

and things started to work. Thank you. I get the correct messages:

```
Received notification: channel1 pid=128
Received notification: channel2 pid=43
```

My question is how I can tell which channel was triggered?

**Comment by tt4g** [comment]
The `TestListener` is the object corresponding to each channel.
L1` receives notifications for `channel1` and `L2` for `channel2`.
Or you can use `pqxx::notification_receiver::channel()` to get the channel name.

**Comment by tt4g** [comment]
@afpgit If the problem has been resolved, close this issue.
