### ISSUE TITLE
Receiving false positive signals through conn.await_notification()

### ISSUE THREAD

**Issue by afpgit** [jtv/libpqxx#798]
The code below uses `libpqxx` C++ library to listen to two trigger signals coming from a TimescaleDB database. There are two infinite loops to wait until a trigger occurs.

```
while (true){
    conn.await_notification();
    spdlog::info("channel1_updated");
}

// and

while (true){
    conn.await_notification();
    spdlog::info("channel2_updated");
}
```

The issue is although no trigger is generated, I get false positive messages, and `channel1_updated` and `channel2_updated` get printed without any signal generated as if `conn.await_notification()`  did not behave properly. I am expecting it to simply block the code until a signal is received.

Is there any other blocking mechanism to wait indefinitely until a trigger arrives?

```
#include "pqxx/config-public-compiler.h"
#include <cctype>
#include <cerrno>
#include <cstring>
#include <ctime>
#include <iostream>

#include <pqxx/internal/header-pre.hxx>
#include <pqxx/internal/wait.hxx>
#include <pqxx/internal/header-post.hxx>
#include <pqxx/notification>
#include <pqxx/transaction>
#include <pqxx/transactor>
#include <thread>

#include "spdlog/spdlog.h"
#include "spdlog/cfg/env.h"
#include "spdlog/fmt/ostr.h" 

class PostgresChannelListener final : public pqxx::notification_receiver {
    bool m_done;
public:
    int backend_pid;

    explicit PostgresChannelListener(pqxx::connection &conn, std::string Name) :
            pqxx::notification_receiver(conn, Name), m_done(false) {}

    void operator()(std::string const &, int be_pid) override {
        m_done = true;
        this->backend_pid = be_pid;
        spdlog::info("Received notification: {} pid=", channel(), be_pid);
    }

    bool done() const { return m_done; }
};

int waitForChannelUpdated(const std::string& channel){
    try {
        pqxx::connection conn("dbname=postgres user=postgres password=password hostaddr=127.0.0.1 port=5432");
        if (!conn.is_open()) {
            spdlog::error("Failed to open database");
            return 1;
        }

        PostgresChannelListener L{conn, channel};

        pqxx::perform([&conn, &L] {
            pqxx::work tx{conn};
            tx.exec0("NOTIFY " + tx.quote_name(L.channel()));
            tx.commit();
        });

        while (true) {
            conn.await_notification();

            // Perform some action on the received signal
            spdlog::info(channel);
        }

    } catch (const std::exception &e) {
        spdlog::error("Error: {}", e.what());
        return 1;
    }

    return 0;
}


int main() {

    std::thread threadChannel1([](){ waitForChannelUpdated("channel1_updated"); });
    std::thread threadChannel2([](){ waitForChannelUpdated("channel2_updated"); });

    threadChannel1.join();
    threadChannel2.join();

    return 0;
}
```

**Comment by tt4g** [comment]
> I am expecting it to simply block the code until a signal is received.

The `await_notification()` comment (document) does not say "block until notified".
The "await" in the name also makes it unlikely that it is a blocking function.

https://github.com/jtv/libpqxx/blob/2ffb711bc4e9b086bf0c549a9c22b19f61ab5476/include/pqxx/connection.hxx#L505-L518

It also describes how to wait until notified.

> ```cpp
>   * To wait for notifications into your own event loop instead, wait until
>   * there is incoming data on the connection's socket to be read, then call
>   * @ref get_notifs() repeatedly until it returns zero.
> ```

Example:

```diff
         while (true) {
-            conn.await_notification();
+            while (conn.get_notifs() == 0) {
+                // wait notification
+            }

             // Perform some action on the received signal
             spdlog::info(channel);
         }
```

**Comment by jtv** [comment]
@afpgit as far as I can see you did not receive false positive notifications.  All that happened is that `await_notification()` can wake up for more reasons than just a notification coming in.

Note the first paragraph in its documentation:

```cxx
  /** There are other events that will also terminate the wait, such as the
   * backend failing.  It will also wake up periodically.
   *
   * If a notification comes in, the call will process it, along with any other
   * notifications that may have been pending.
   *
   * To wait for notifications into your own event loop instead, wait until
   * there is incoming data on the connection's socket to be read, then call
   * @ref get_notifs() repeatedly until it returns zero.
   *
   * @return Number of notifications processed.
   */
```

To determine whether you received a notification, rely only on the actual callback in your `notification_receiver`.

Why does `await_notification()` wake up periodically?  Two reasons.
1. Waiting forever isn't all _that_ useful.  Sometimes you should take a step back and see if perhaps it's been too long and you should give up.
2. Things can get complicated when signals come into play.  That's when differences between operating systems, different libraries, possible threading implementations, and different system calls get finicky.  Sometimes different applications want to do different things when a signal comes in.  So we have to be prepared for a wait sometimes ending spuriously.  But who's going to write integration tests for their signal handling?  If a signal can wake up the loop unexpectedly, the best way to make people handle it properly is to _ensure_ that the function sometimes returns early.
