### ISSUE TITLE
Converting TIMESTAMP datatypes into a std::chrono::time_point

### ISSUE THREAD

**Issue by AA1999** [jtv/libpqxx#801]
According to #206 at that point in time `.as<>()` did not support std::chrono:: types
I was wondering if it does now? I didn't find an answer in the documentation

**Comment by AA1999** [comment]
Also sidenote: ibpqxx.readthedocs.io/en/stable is dead as we speak

**Comment by tt4g** [comment]
Not supported as far as I know.
I assume that this is because the time that `std::chrono::time_point` is based on is platform-dependent, and the time zone and format of `TIMESTAMP` retrieved from PostgreSQL is configuration-dependent, making it difficult for libpqxx to parse the time string.

**Comment by jtv** [comment]
There is built-in support for `std::chrono::year_month_day` and friends, but that's about it.  The system for supporting data types is extensible though — see [include/pqxx/doc/datatypes.md](../blob/master/include/pqxx/doc/datatypes.md).

**Comment by jtv** [comment]
Thanks for the warning about `readthedocs.io`...  As far as I can tell the class documentation is there, but not the indexes.

**Comment by AA1999** [comment]
> There is built-in support for `std::chrono::year_month_day` and friends, but that's about it.  The system for supporting data types is extensible though — see [include/pqxx/doc/datatypes.md](../blob/master/include/pqxx/doc/datatypes.md).

What if I do .as<std::string>() on the timestamp row? Would it return a specific format?

**Comment by tt4g** [comment]
The column values received from the database are in string format.
`TIMESTAMP` is in ISO format (default).

https://www.postgresql.org/docs/16/datatype-datetime.html#DATATYPE-DATETIME-OUTPUT

> The output format of the date/time types can be set to one of the four styles ISO 8601, SQL (Ingres), traditional POSTGRES (Unix date format), or German. The default is the ISO format. (The SQL standard requires the use of the ISO 8601 format. The name of the “SQL” output format is a historical accident.) [Table 8.14](https://www.postgresql.org/docs/16/datatype-datetime.html#DATATYPE-DATETIME-OUTPUT-TABLE) shows examples of each output style. The output of the date and time types is generally only the date or time part in accordance with the given examples. However, the POSTGRES style outputs date-only values in ISO format.

**Comment by jtv** [comment]
In other words: the database sends the data in a human-readable text format (in the case of a timestamp: in ISO-8601 format), and so from libpqxx's standpoint all data in a result are _already_ strings.  If you request it using `.as<std::string>()`, you simply get that string exactly as you would hope.

The part that's more complicated is if you want to convert the string that the database sent to a C++ type that libpqxx doesn't yet support.  (Or going the other way: if you want to pass such an object as a parameter to an SQL statement.)  However it is possible for an application to "inject" support for additional data types.

**Comment by jtv** [comment]
I hope this has been resolved.  Closing the ticket.
