### ISSUE TITLE
Error building a project with the library

### ISSUE THREAD

**Issue by Arterium36** [jtv/libpqxx#803]
I built a library for Windows. When trying to use it, it returns errors in the zview.xxx file - the identifier text, str, len are not defined. Also in conversions.hxx - "a link to the "Args" parameter package is present, but the package is not disclosed." I made the assembly according to this guide - http://en.wiki.imlint.org/Pqxx_tutorial

**Comment by Arterium36** [comment]
I am writing specifically about the libpqxx library. The installation process is prescribed by the link

**Comment by tt4g** [comment]
If you have libpqxx installed, then it is a problem with your project, not libpqxx.
Your project's source code is not maintained in this repository, so no one here can solve the problem unless you provide accurate information.

**Comment by Arterium36** [comment]
Please reread this question. The errors are not in my project, but in the files that belong to libpqxx.

**Comment by jtv** [comment]
And really the first question: what are the actual error messages?

**Comment by jtv** [comment]
@Arterium36 do you have the error messages for us?  Those will probably help.

**Comment by jtv** [comment]
Closing this one for lack of a usable problem description.  :-(
