### ISSUE TITLE
Make of libpqxx on Red Hat Enterprise Linux 8.8 fails

### ISSUE THREAD

**Issue by FabioMBB** [jtv/libpqxx#806]
Hi, sorry to bother but I tried to build libpqxx in Red Hat Enterprise Linux 8.8 and I keep having the following problem when I run make:

make[1]: Entering directory '/home/fabio/Desktop/libpqxx/tools'
depbase=`echo rmlo.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H   -I../include -I../include -I/usr/pgsql-16/include  -I/usr/pgsql-16/include   -std=c++17 -fvisibility=hidden -fvisibility-inlines-hidden -MT rmlo.o -MD -MP -MF $depbase.Tpo -c -o rmlo.o rmlo.cxx &&\
mv -f $depbase.Tpo $depbase.Po
In file included from ../include/pqxx/pqxx:17,
                 from rmlo.cxx:4:
../include/pqxx/range.hxx:149:24: error: invalid use of ‘this’ at top level
     noexcept(noexcept(*this->value() == *rhs.value()))
                        ^~~~
../include/pqxx/range.hxx:160:24: error: invalid use of ‘this’ at top level
     noexcept(noexcept(*this == rhs))
                        ^~~~
../include/pqxx/range.hxx:272:23: error: invalid use of ‘this’ at top level
     noexcept(noexcept(this->lower_bound() == rhs.lower_bound()) and noexcept(
                       ^~~~
../include/pqxx/range.hxx:273:7: error: invalid use of ‘this’ at top level
       this->upper_bound() == rhs.upper_bound()) and noexcept(this->empty()))
       ^~~~
../include/pqxx/range.hxx:273:62: error: invalid use of ‘this’ at top level
       this->upper_bound() == rhs.upper_bound()) and noexcept(this->empty()))
                                                              ^~~~
../include/pqxx/range.hxx:281:24: error: invalid use of ‘this’ at top level
     noexcept(noexcept(*this == rhs))
                        ^~~~
../include/pqxx/range.hxx:321:25: error: invalid use of ‘this’ at top level
     noexcept(noexcept((*this & other) == other))
                         ^~~~
make[1]: *** [Makefile:405: rmlo.o] Error 1
make[1]: Leaving directory '/home/fabio/Desktop/libpqxx/tools'
make: *** [Makefile:644: all-recursive] Error 1

Can you guys please let me know what I'm doing wrong?

**Comment by FabioMBB** [comment]
I'm using pgsql-16

**Comment by jtv** [comment]
I believe that's a known old compiler bug.  Does it still happen with a newer version of gcc?

**Comment by tt4g** [comment]
I agree @jtv. `g++` compiler has reproduced this bug many times before.
Similar issue: #737 #750

**Comment by jtv** [comment]
Thanks @tt4g!

**Comment by FabioMBB** [comment]
Thank you so much guys. Updating gcc solved the problem. In case someone end up here: https://developers.redhat.com/articles/2023/11/10/install-gcc-and-build-hello-world-application-rhel-8#step_3__build_a_hello_world_application

**Comment by FabioMBB** [comment]
The main part is to run the command: scl enable gcc-toolset-12 bash
