### ISSUE TITLE
Query streaming doesn't compile anymore

### ISSUE THREAD

**Issue by randolf** [jtv/libpqxx#810]
According to c++ and clang++, pqxx::stream_from::query is deprecated and I need to use pqxx::transaction_base::stream instead, but the documentation doesn't explain how to use it and I can't find any examples with Google.  Are there any examples available, or even blog postings, etc., that show how this new part of the API is used?

Here's a portion of my code that used to work...

```
  try {
    pqxx::nontransaction tx{*conn};
    auto stream{pqxx::stream_from::query(tx,
                                         "SELECT col1,col2,col3 FROM table1 WHERE col7 IS TRUE"
                                       + " OR col8 >= 21 ORDER BY col2 NULLS FIRST")};
    std::tuple<std::string, std::string> row;
    while (stream >> row) {
      std::cout << "col1=" << std::get<0>(row) << " col2=" << std::get<1>(row) << " col3=" << std::get<2>(row) << std::endl;
    }
    stream.complete();
  } catch (const std::exception &e) {
    std::cerr << "Can't read table1: " << e.what() << std::endl;
    return nullptr;
  }
```

Thanks in advance.

**Comment by tt4g** [comment]
`pqxx::transaction_base::stream()` has the tests (the tests are also example code). see test file https://github.com/jtv/libpqxx/blob/7.9.0/test/unit/test_stream_query.cxx

---

There is also a `stream_for()` that uses a callback.

- Source: https://github.com/jtv/libpqxx/blob/7.9.0/include/pqxx/transaction_base.hxx#L514-L552
- Test: https://github.com/jtv/libpqxx/blob/7.9.0/test/unit/test_transaction_base.cxx#L211-L227

**Comment by randolf** [comment]
That looks like what I need.  Thank you! 🍻

**Comment by randolf** [comment]
That looks like what I need. Thank you! 🍻

**Comment by jtv** [comment]
I suppose I'll close the issue then.
