### ISSUE TITLE
error C2039: 'converts_from_string': is not a member of 'pqxx::string_traits<pgvector::Vector>'

### ISSUE THREAD

**Issue by VamshiGowdaHP** [jtv/libpqxx#819]
tried using libpqxx library for running example cpp application which is under test folder of pgvector-cpp repository - https://github.com/pgvector/pgvector-cpp

but facing error while building the project and the error looks like this 
- error C2065: 'converts_to_string': undeclared identifier
- error C2131: expression did not evaluate to a constant
- error C2039: 'converts_from_string': is not a member of 'pqxx::string_traits<pgvector::Vector>'
- error C2065: 'converts_from_string': undeclared identifier
- error C2131: expression did not evaluate to a constant

all these errors are referring to the file conversions.hxx

steps followed to install lipqxx library

.\vcpkg\vcpkg install libpqxx:x64-windows
.\vcpkg\vcpkg integrate install
.\vcpkg\vcpkg install libpqxx

and i also tried installing lipqxx from the steps given in this repo - https://github.com/GordonLElliott/Easy-PQXX-Build-for-Windows-Visual-Studio 

But it gave same error in both the cases.

is there any solution to resolve this error>?

**Comment by VamshiGowdaHP** [comment]
> There should be libpqxx version requirement for pgvector-cpp to work, you should open this issue in libdx repository.

I'm unable to find libdx repository. Can you provide the link for this repository?

**Comment by tt4g** [comment]
Resolved: pgvector/pgvector-cpp#3

**Comment by jtv** [comment]
@VamshiGowdaHP it sounds like the authors of pgvector-cpp have built libpqxx support, but haven't updated it to the latest libpqxx versions.  The newer versions add a few requirements for how to define conversion support between a C++ type and its SQL text equivalent.  in particular, the conversion now needs to define `converts_to_string` and `converts_from_string`.  (See [include/pqxx/doc/datatypes.md](../blob/master/include/pqxx/doc/datatypes.md) for the current requirements.)

**Comment by jtv** [comment]
I suppose we can close this ticket now?

**Comment by vamgowda-git** [comment]
Yes, you can close this ticket.

**Comment by jtv** [comment]
Thanks for letting me know.
