### ISSUE TITLE
std::optional<std::chrono::year_month_day> to DATE error if optional is empty

### ISSUE THREAD

**Issue by Alfrink** [jtv/libpqxx#826]
Hi, I've been making a lot of use of letting pqxx automatically handle my std::optional fields, but am having trouble with a DATE field in particular when I do the following:

```
work.exec_params(
                "UPDATE ladder_entry SET rating = $1, reliability_deviation = $2, last_game = $3 WHERE id = $4;",
                ladderEntry.rating, ladderEntry.reliabilityDeviation, ladderEntry.lastGame, ladderEntry.id
        );
```

The table in question includes `reliability_deviation INT, last_game DATE`, so both are nullable. ladderEntry.reliabilityDeviation is an `std::optional<int>`, ladderEntry.lastGame is an `std::optional<std::chrono::year_month_day>`. If they both have values, this works just fine. If neither of them have values, I get the following error:

```
date/time field value out of range: "0001-00-00 BC"
HINT:  Perhaps you need a different "datestyle" setting.
CONTEXT:  unnamed portal parameter $3 = '...'
```

At this point, fields have actually been updated as expected, with both std::optional-fields being null in the DB in this case and other fields being edited correctly, even though there's an error. The same procedure with other nullable optional fields without values throws no errors, it only seems to happen with DATE. I also don't get this error if I manually do an UPDATE directly in my DB with the fields in question set to `null`. Am I doing something wrong or is this an issue with the std::optional-support in conjunction with the chrono type?

Thank you for your help!

**Comment by tt4g** [comment]
I think this is a bug because libpqxx has to send NULL to the database when `std::optional<T>` is `std::nullopt`.
However, the actual error message is "0001-00-00 BC", so I don't know where this date string came from.

Maybe the `datestyle` is different from what libpqxx assumes, as described in the hint "Perhaps you need a different "datestyle" setting.".
What style is set for `datestyle`?

**Comment by Alfrink** [comment]
After trying to reproduce this in a separate environment, failing to do so and attempting to eliminate any differences, it turns out that an additional query has been running that also has a date as its $3 parameter, causing me to mix them up. The error was obvious in the other query. Sorry about that :(
