### ISSUE TITLE
After compilation, there are only pqxx files but no pqxx.hxx files. Is this normal?

### ISSUE THREAD

**Issue by RageCPP** [jtv/libpqxx#829]
```CMakeLists.txt
# root CMakeLists.txt
FetchContent_Declare(libpqxx
  GIT_REPOSITORY git@github.com:jtv/libpqxx.git
  GIT_TAG 2ffb711bc4e9b086bf0c549a9c22b19f61ab5476 # v7.9.0
  OVERRIDE_FIND_PACKAGE
  GIT_SHALLOW ON
)
FetchContent_MakeAvailable(libpqxx)

# use libpqxx target CMakeLists.txt
find_package(libpqxx REQUIRED)

target_link_libraries(${PROJECT_NAME} PUBLIC
  pqxx)
```
after build my include folder just had pqxx, not have pqxx.hxx
![image](https://github.com/jtv/libpqxx/assets/45113206/e0fd0242-5c50-44aa-8afd-7f8d430d9e75)
pqxx content
![image](https://github.com/jtv/libpqxx/assets/45113206/99d5d07e-02c3-427b-8c24-60938d986e2a)
but when use it in neovim tell me error.
![image](https://github.com/jtv/libpqxx/assets/45113206/6c78c13f-d857-423a-b89f-3b55ad629115)

**Comment by RageCPP** [comment]
I would like to add that although an error is reported, when I use the definition jump, I can jump successfully.

**Comment by jtv** [comment]
Yes, it is normal that there is no `pqxx.hxx` file.  There is no need for such a file.

**Comment by tt4g** [comment]
`pqxx/pqxx.hxx` file  does not exist in this repository.
And the include error is probably a Neovim problem.

**Comment by RageCPP** [comment]
Can I create a file with `.hxx` suffix to help identify it? I think it may be a problem with clangd, but I haven’t found a solution yet.

**Comment by tt4g** [comment]
Since you have imported libpqxx as part of your project, isn't clangd recognizing the local header files?
As far as [the clangd documentation](https://clangd.llvm.org/installation#project-setup) is reading, you need to create [`compile_commands.json`](https://clangd.llvm.org/installation#compile_commandsjson) or [`compile_flags.txt`](https://clangd.llvm.org/installation#compile_flagstxt) and make clangd recognize the compile flag.

It also says that `compile_commands.json` is generated by `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1`.

**Comment by jtv** [comment]
Of course you can create whatever files you like on your system, but first I'd do a bit more searching to find out what the actual problem might be.  It looks likely that somebody else will have run into it.

None of the headers in the C++ standard library have a suffix like ".hxx" to their names, and presumably neovim works with those.  But perhaps the error you're seeing is indicative of a different problem, several layers of `#include` down.  So perhaps open `pqxx` in neovim and see whether this error comes from one of the `#include` directives in there?

**Comment by RageCPP** [comment]
> Since you have imported libpqxx as part of your project, isn't clangd recognizing the local header files? As far as [the clangd documentation](https://clangd.llvm.org/installation#project-setup) is reading, you need to create [`compile_commands.json`](https://clangd.llvm.org/installation#compile_commandsjson) or [`compile_flags.txt`](https://clangd.llvm.org/installation#compile_flagstxt) and make clangd recognize the compile flag.
> 
> It also says that `compile_commands.json` is generated by `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1`.

Other imported packages can recognize header files, but it may not be correct because pgxx does not have a suffix, but I can't be sure.

**Comment by RageCPP** [comment]
> Of course you can create whatever files you like on your system, but first I'd do a bit more searching to find out what the actual problem might be. It looks likely that somebody else will have run into it.
> 
> None of the headers in the C++ standard library have a suffix like ".hxx" to their names, and presumably neovim works with those. But perhaps the error you're seeing is indicative of a different problem, several layers of `#include` down. So perhaps open `pqxx` in neovim and see whether this error comes from one of the `#include` directives in there?

I tried to change pqxx to pqxx.hpp or pqxx.hxx and the file could not be found.
![image](https://github.com/jtv/libpqxx/assets/45113206/8fa42792-81f5-46c9-ab55-7689da08a8e2)

**Comment by tt4g** [comment]
STL header files such as `vector` and `utility` also have no suffix.
It seems strange that only `pqxx` is not recognized.

**Comment by tt4g** [comment]
Have you generated `compile_commands.json`?
Also, if you are using some plugin to use LSP in neovim, have you checked how to use `compile_commands.json` in that plugin?
For example, neovim-lsp seems to have a restriction that it only recognizes `compile_commands.json` in the project root directory: https://github.com/neovim/nvim-lspconfig/blob/v0.1.7/doc/server_configurations.md#clangd

**Comment by RageCPP** [comment]
> 你生成了吗`compile_commands.json`？ 另外，如果您在 neovim 中使用某些插件来使用 LSP，您是否检查过如何`compile_commands.json`在该插件中使用？ 例如，neovim-lsp 似乎有一个限制，它只能`compile_commands.json`在项目根目录中识别：https://github.com/neovim/nvim-lspconfig/blob/v0.1.7/doc/server_configurations.md#clangd

I'm sure it was generated
![image](https://github.com/jtv/libpqxx/assets/45113206/bcfdaf0c-0b62-4430-92f8-211d4185ea7c)

**Comment by RageCPP** [comment]
> 你用什么LSP插件？ 无法识别 libpqxx 提供的头文件是 LSP 插件或 clangd 的问题，应该在这些社区中询问。 libpqxx 存储库中没有人知道原因。

Yes, I posted a link to this issue in the clangd community, but no one has answered me yet.

**Comment by RageCPP** [comment]
[clangd.log](https://github.com/jtv/libpqxx/files/15279703/clangd.log)

**Comment by RageCPP** [comment]
[clangd.log](https://github.com/jtv/libpqxx/files/15279708/clangd.log)

**Comment by tt4g** [comment]
Even if we look at the clangd logs, we cannot investigate the problem from there.

**Comment by RageCPP** [comment]
I rechecked compile_commands.json, I found this
```json
{
  "directory": "/home/rage/code/chessmeta/build/_deps/libpqxx-build/src",
  "command": "/usr/bin/g++-13  -I/home/rage/code/chessmeta/build/_deps/libpqxx-build/include -I/home/rage/code/chessmeta/build/_deps/libpqxx-src/include -I/usr/include/pgsql -std=c++17 -o CMakeFiles/pqxx.dir/binarystring.cxx.o -c /home/rage/code/chessmeta/build/_deps/libpqxx-src/src/binarystring.cxx",
  "file": "/home/rage/code/chessmeta/build/_deps/libpqxx-src/src/binarystring.cxx",
  "output": "_deps/libpqxx-build/src/CMakeFiles/pqxx.dir/binarystring.cxx.o"
},
```
```bash
rage@localhost:~/code/chessmeta/include/pqxx> ls /home/rage/code/chessmeta/build/_deps/libpqxx-build/include/pqxx/
config_cmake.h.in  config-internal-compiler.h  config-internal-libpq.h  config-public-compiler.h
```
Does this mean I'm missing a header file?

**Comment by tt4g** [comment]
@RageCPP Did you make a comment here by mistake, thinking it was a clangd community?

**Comment by RageCPP** [comment]
> @RageCPP Did you make a comment here by mistake, thinking it was a clangd community?

Well, I think this problem may occur in many people who use nvim and pqxx, so I want to leave a record here so that people who have doubts can check it later. Should I stop what I submit here?

**Comment by tt4g** [comment]
I think it is a great idea to record the problem in case others encounter the same problem.
However, the cost of all the information other than cause and solution also makes it difficult to find the really important information.
It is better to just comment on how to solve the problem when it is solved.

**Comment by RageCPP** [comment]
> I think it is a great idea to record the problem in case others encounter the same problem. However, the cost of all the information other than cause and solution also makes it difficult to find the really important information. It is better to just comment on how to solve the problem when it is solved.

Hello, I think I found the problem, but now I can't continue to troubleshoot. Does libpqxx have a discussion forum similar to discord? I will delete all irrelevant comments later and only keep the solutions.

![image](https://github.com/jtv/libpqxx/assets/45113206/e6b8c4f6-056d-4e89-b0a4-0ebda8e1294d)
当我删除pqxx文件下的这些行时，不在报错
```hpp
#include "pqxx/array.hxx"
#include "pqxx/binarystring.hxx"
#include "pqxx/blob.hxx"
#include "pqxx/connection.hxx"
#include "pqxx/cursor.hxx"
#include "pqxx/errorhandler.hxx"
#include "pqxx/except.hxx"
#include "pqxx/largeobject.hxx"
#include "pqxx/nontransaction.hxx"
#include "pqxx/notification.hxx"
#include "pqxx/params.hxx"
#include "pqxx/pipeline.hxx"
#include "pqxx/prepared_statement.hxx"
#include "pqxx/range.hxx"
#include "pqxx/result.hxx"
#include "pqxx/internal/result_iterator.hxx"
#include "pqxx/internal/result_iter.hxx"
#include "pqxx/robusttransaction.hxx"
#include "pqxx/row.hxx"
#include "pqxx/stream_from.hxx"
#include "pqxx/stream_to.hxx"
#include "pqxx/subtransaction.hxx"
#include "pqxx/time.hxx"
#include "pqxx/transaction.hxx"
#include "pqxx/transactor.hxx"
```

**Comment by tt4g** [comment]
There is no Discord, etc.
It is a clangd or LSP problem that the header file is not recognized properly, so you should look for a Discord or something like that.
And changing `include/pqxx/pqxx` will affect many users badly.

**Comment by RageCPP** [comment]
I think I may have found the final cause of the problem
```hpp
// C++20: Assume support.
#if __has_include(<ranges>)
#include <ranges>
#endif
```
There is a problem with this code. Not all compilation options that support cpp20 contain this header file.
![image](https://github.com/jtv/libpqxx/assets/45113206/3536ae3c-437f-4e35-baf1-86350dfb5a61)
![1996d2e579f243fc86e80ac88454f14](https://github.com/jtv/libpqxx/assets/45113206/87eae928-2232-47b8-9584-40f5184567a9)
![94f6dec3efd3be372ca378a3f594985](https://github.com/jtv/libpqxx/assets/45113206/3b8c2189-9826-4236-b026-0f096443677c)
my g++13 compiler
```bash
rage@localhost:/usr> g++-13 --version
g++-13 (SUSE Linux) 13.2.1 20240206 [revision 67ac78caf31f7cb3202177e6428a46d829b70f23]
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
and i am sure i use it
![image](https://github.com/jtv/libpqxx/assets/45113206/2336cdc6-ccc8-46c1-a108-2581d000804f)

**Comment by tt4g** [comment]
Since the existence of the header is checked by `#if __has_include(<ranges>)`, if `<ranges>` is not provided, then `#include <ranges>` is ignored.

**Comment by tt4g** [comment]
>  it may be a false positive from clangd

Yes.

**Comment by RageCPP** [comment]
issue end
![db2f1f8ac0f7bfc0769a922fe14a8d7](https://github.com/jtv/libpqxx/assets/45113206/ee0a0f6d-ceaa-4fad-9c33-960d35f8ca98)

**Comment by RageCPP** [comment]
!!! use clang17 not use clang15

**Comment by jtv** [comment]
@RageCPP @tt4g We do have a Discussions forum.

For a moment I thought that it might help for me to add a configure-time check for ranges support.  But no — ranges support is used in the headers only.  I don't think it would make sense to nail that down at configure time.

**Comment by tt4g** [comment]
@jtv Perhaps this is a clangd or Language Server issue.
I am assuming that the project configuration was not loaded correctly because the header files that actually existed were not detected.
