### ISSUE TITLE
Rtti usage on demand

### ISSUE THREAD

**Issue by Balalarga** [jtv/libpqxx#831]
Hi!
RTTI is required now only for enum names at error handling.
```
template<typename TYPE>
std::string const type_name{internal::demangle_type_name(typeid(TYPE).name())};
```

It's not always good, as many big projects disable it mandatory
Is it a big deal to make it a optional feature?

**Comment by jtv** [comment]
That's annoying: Technically nothing here actually requires RTTI, but it requires _the compiler's RTTI support._  The `typeid` operator used here is the one that takes a type, which is evaluated at compile time.

I think it would be possible to work around this without losing any functionality: we'll need a second version of `PQXX_DECLARE_ENUM` where the caller provides a human-readable name for the type.  (Well, _or_ an optional second argument but that only works in C++20 and is also just too ugly for this situation.)  And then we'll need to make sure that libpqxx defines explicit names for all the types that need them.

**Comment by jtv** [comment]
@Balalarga what exactly makes you say the problem happens with enum types?  It now looks to me more like it happens with non-enum types.

**Comment by Balalarga** [comment]
> @Balalarga what exactly makes you say the problem happens with enum types? It now looks to me more like it happens with non-enum types.

Thank you for the answer
I'm trying to use your lib with UnrealEngine, and cannot cross compile Linux build. And i haven't wrote any code, except of connection.
After a small research, i found clang do not support RTTI by default and it should be recompiled manually. Maybe it happen only with EpicGames's toolchain, but i haven't figure it out yet.

**Comment by jtv** [comment]
You could try defining a constant `pqxx::type_name<A_TYPE>` for every type that's likely to need it, very early on in the source, specialising the template that's in strconv.hxx.  But I tried that and it didn't work.

Or perhaps it would be possible to enable RTTI by passing `-frtti` on the compiler command line.

**Comment by Balalarga** [comment]
kk, thanks.
I'll enable rtti and hide all pqxx code inside a higher-level wrapper!!
