### ISSUE TITLE
linking issue when using torch+pqxx in cmake. 

### ISSUE THREAD

**Issue by blueberry64** [jtv/libpqxx#833]
I get the `undefined reference to pqxx::internal::demangle_type_name(char const*)` thing when I try to include both pqxx and libtorch.  This is a minimal c++ project with the problem.  I tried installing it from `sudo apt install libpqxx-dev` and the git clone+sudo make install with various ./configure permutations of c++20 and 17 and enabling/disabling static and shared. also I tried replacing ${PQXX_LIBRARIES} with "/usr/local/lib/libpqxx.a" and that made no difference. If i comment out the  ${TORCH_LIBRARIES} line it works fine.

```
#include "pqxx/pqxx"
int main() { return 0; }
```

```
cmake_minimum_required(VERSION 3.28)
project(untitled)

set(CMAKE_CXX_STANDARD 17)

find_package(PkgConfig REQUIRED)
pkg_check_modules(PQXX REQUIRED libpqxx)
pkg_check_modules(PQ REQUIRED libpq)
include_directories(${PQXX_INCLUDE_DIRS} ${PQ_INCLUDE_DIRS})

find_package(Torch REQUIRED PATHS "/usr/local/lib/libtorch/share/cmake/Torch")
message(STATUS "Torch Libraries: ${TORCH_LIBRARIES}")
message(STATUS "pqxx: ${PQXX_LIBRARIES}")
message(STATUS "pq: ${PQ_LIBRARIES}")

add_executable(untitled main.cpp)
target_link_libraries(untitled PRIVATE
        ${PQXX_LIBRARIES}
        ${PQ_LIBRARIES}
        ${TORCH_LIBRARIES}
)
```

**Comment by jtv** [comment]
What's the actual linking command line that gets executed?

That seems to be the most common cause of this symptom right now - the `-lpqxx -lpq` options need to occur on the command line, in that order, _after_ the object files.

Otherwise, with gcc at least, you get these errors.

**Comment by tt4g** [comment]
I may be guessing incorrectly since distribution details are not provided, but libpqxx-dev as provided by Debian is version 7.8.1: https://packages.debian.org/ja/sid/libpqxx-dev
You are building libpqxx, but libpqxx-dev contains only header files. So you must have downloaded the libpqxx source code from somewhere.
Is that source code version 7.8.1?

**Comment by blueberry64** [comment]
This has started happening to me again when trying to build my project on a different system.  What should I do to install/configure libpqxx for this cmake? `cmake_minimum_required(VERSION 3.25)
project(retriever VERSION 1.0)

set(CMAKE_BUILD_TYPE Debug)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED True)

set(CMAKE_CUDA_STANDARD 20)
set(CMAKE_CUDA_STANDARD_REQUIRED ON)

set(CMAKE_CUDA_ARCHITECTURES 86)
set(CMAKE_CUDA_COMPILER /usr/bin/nvcc)

set(CMAKE_VERBOSE_MAKEFILE ON)

set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -O0")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O0")

include_directories(/usr/local/lib/onnxruntime/include)
link_directories(/usr/local/lib/onnxruntime/lib)

find_package(PkgConfig REQUIRED)
find_package(OpenMP)

pkg_check_modules(PQXX REQUIRED libpqxx)
pkg_check_modules(PQ REQUIRED libpq)
include_directories(${PQXX_INCLUDE_DIRS} ${PQ_INCLUDE_DIRS})

find_package(Torch REQUIRED PATHS "/usr/local/lib/libtorch/share/cmake/Torch")

find_package(ICU REQUIRED COMPONENTS uc io i18n)
include_directories(${ICU_INCLUDE_DIRS})

find_package(Boost REQUIRED COMPONENTS system filesystem)
include_directories(${Boost_INCLUDE_DIRS})

find_package(cpprestsdk REQUIRED)

find_package(OpenSSL REQUIRED)
include_directories(/usr/include/openssl)
link_directories(/usr/lib/x86_64-linux-gnu)

find_package(OpenMP REQUIRED)

include_directories(src/)
file(GLOB_RECURSE PROJECT_SOURCES "src/*.cpp")

add_executable(retriever ${PROJECT_SOURCES})

target_link_libraries(retriever PRIVATE
    onnxruntime
    ${Boost_LIBRARIES}
    ${ICU_LIBRARIES}
    ${PQXX_LIBRARIES}
    ${PQ_LIBRARIES}
    ${TORCH_LIBRARIES}
    OpenSSL::SSL
    OpenSSL::Crypto
    cpprestsdk::cpprest
    OpenMP::OpenMP_CXX
)
`

**Comment by tt4g** [comment]
If reinstalling Torch solved the problem, then it is probably a Torch issue.
Have you asked a question in the Torch community?

**Comment by blueberry64** [comment]
Idk no other library has this issue, and if I search this repo for "undefined reference" there's a ton of other similar problems.  I think the problem is probably here?

**Comment by tt4g** [comment]
"undefined reference" can easily occur simply because the compilation options differ between the library and the application.
And many of the users who encountered "undefined reference" in this repository did so because they installed libpqxx from the package manager and did not know the compiler flags.

However, the `demangle_type_name` symbol missing error was caused by the link order of libpqxx and libpq in many cases (https://github.com/jtv/libpqxx/issues/833#issuecomment-2119842395).
Looking at `CMakeLists.txt`, I can't think of any more causes for this for me, since they are linked in the order libpqxx and libpq.

**Comment by blueberry64** [comment]
I installed with 
```git clone --branch 7.9.0 https://github.com/jtv/libpqxx.git && cd libpqxx```
 ```./configure``` (tried a couple different things like setting c++ to 20 or disabling shared etc, but also having this problem with no paramaters)
```make```
```sudo make install```
Maybe ./configure needs some arguments? I'm not sure what they could be.

**Comment by jtv** [comment]
@blueberry64 do you have a way of obtaining the exact linking command line that cmake executes when linking your application?

**Comment by blueberry64** [comment]
`/usr/bin/cmake -E cmake_link_script CMakeFiles/untitled.dir/link.txt --verbose=1
/usr/bin/c++ CMakeFiles/untitled.dir/main.cpp.o -o untitled   -L/lib/intel64  -L/lib/intel64_win  -L/lib/win-x64  -Wl,-rpath,/lib/intel64:/lib/intel64_win:/lib/win-x64:/usr/local/lib/libtorch/lib /usr/local/lib/libtorch/lib/libtorch.so /usr/local/lib/libtorch/lib/libc10.so /usr/local/lib/libtorch/lib/libkineto.a /usr/lib/x86_64-linux-gnu/libcuda.so /usr/lib/x86_64-linux-gnu/libnvrtc.so /usr/lib/x86_64-linux-gnu/libnvToolsExt.so /usr/lib/x86_64-linux-gnu/libcudart.so /usr/local/lib/libtorch/lib/libc10_cuda.so -lpqxx -lpq -Wl,--no-as-needed,"/usr/local/lib/libtorch/lib/libtorch_cpu.so" -Wl,--as-needed -Wl,--no-as-needed,"/usr/local/lib/libtorch/lib/libtorch_cuda.so" -Wl,--as-needed /usr/local/lib/libtorch/lib/libc10_cuda.so /usr/local/lib/libtorch/lib/libc10.so /usr/lib/x86_64-linux-gnu/libcudart.so /usr/lib/x86_64-linux-gnu/libnvToolsExt.so -Wl,--no-as-needed,"/usr/local/lib/libtorch/lib/libtorch.so" -Wl,--as-needed 
`

**Comment by blueberry64** [comment]
Ok sorry folks it was pytorch not libpqxx!!! ${TRIGGERED_NOISE_HERE}.
Similar problem to this: https://discuss.pytorch.org/t/library-conflict-between-libtorch-and-opencv/64489/6
