### ISSUE TITLE
Update libpqxx on Ubuntu

### ISSUE THREAD

**Issue by lawben** [jtv/libpqxx#84]
Are there any plans on updating the lib in ubuntu repositories? AFAICT it is still at version 4.x. For a project I am working on it would be a lot more convenient to install this directly instead of cloning the github repository. `brew` on OSX is on 6.1.1

**Comment by keithstellyes** [comment]
I think this is handled on the Ubuntu side of things as they're the ones who package it and upload it, should probably reach out to its maintainer, Marcin Kulisz (kuLa)

https://launchpad.net/ubuntu/+source/libpqxx

**Comment by jtv** [comment]
Yes, @keithstellyes is right — this is for the package maintainer on the Ubuntu side to arrange.
