### ISSUE TITLE
Allow parsing arrays without connection

### ISSUE THREAD

**Issue by alexolog** [jtv/libpqxx#841]
Currently, parsing an array requires an active connection, which is used only to retrieve the client encoding. This prevents using containers inside tuples for automatic conversion and requires jumping through hoops to parse arrays.

This also applies to `pqxx::array` constructor.

However, in many cases the encoding is known in advance, especially when developing a product where both the client and the server are controlled by the same actor.

I believe it would be better if we could have a standalone function to globally set the encoding to a constant or from a connection, and it would persist until changed.

**Comment by tt4g** [comment]
There is a constructor `pqxx::array` that can be created without a connection by passing `pqxx::internal::encoding_group`  as the 2nd argument.

https://github.com/jtv/libpqxx/blob/9f378c0390c62ca23c5290679df64e093c6579c2/include/pqxx/array.hxx#L203-L223

However, it is a private API and cannot be used by applications.
The reason why this is a private API cannot be read from the source code, but there must be a reason.

**Comment by jtv** [comment]
The reason is that so far, encodings and encoding groups are entirely hidden from the application.  If we're going to introduce it into the API, then we'll have to answer some questions:
* As the API evolves, will we ever need to know the actual encoding, or is just the encoding group enough?
* Do we need stability guarantees for the enum as encodings and encoding groups are added or removed?
* Will we be able to work encoding awareness into the string conversion API in the future?

**Comment by alexolog** [comment]
Adding the following constructor can alleviate the problem:
```
  explicit array(std::string_view data, std::string_view encoding_name = "UTF8") :
          array{data, pqxx::internal::enc_group(encoding_name)}
  {}
```

**Comment by jtv** [comment]
Yes, I suppose using the encoding's _name_ would solve it.  I'd probably want a way for the caller to move that string lookup out of loops though.

We'd also need to check lifetime guarantees.  If that encoding name happens to live inside a buffer held by the libpq-level connection struct somewhere, then closing the connection would invalidate that memory and we'd be back to the original problem.

I wonder if it would help to encapsulate encoding in a class.  You'd construct an object using an encoding name, but internally it might store just the encoding group.  No transparency of enums, no persistent storage of the numerical values.

**Comment by fallenworld1** [comment]
the problem we're trying to solve here is we're unable to write something like this:
```
auto array = row[field_id].as<array<int>>();

// or

using Tuple = std::tuple<pqxx::array<int>>;
auto tuple = row.as<Tuple>();
```

because `as` internally only passes `view`

if you could create template specification for `as` that would work for `pqxx::array` (or maybe even for vector like containers) - it would keep groups internal

e.g.:
```
  template<T> pqxx::array<T> as() const
  {
    if (is_null())
    {
      if constexpr (not nullness<T>::has_null)
        internal::throw_null_conversion(type_name<T>);
      else
        return nullness<T>::null();
    }
    else
    {
      return  pqxx::array<T>(this->view(), this->m_home.m_encoding);
    }
  }
```

**Comment by alexolog** [comment]
It seems that we only pass connections for encoding in `array`, so we could do something quick like this:
```cpp
template<...>
class array final
{
public:
  array(std::string_view data, connection const &conn) :
          array{data, m_default_enc_group}
  {}

  static void set_default_encoding(std::string_view encoding_name) {
    m_default_enc_name = encoding_name;
    m_default_enc_group = pqxx::internal::enc_group(encoding_name);
  }

  static [[nodiscard]] std::string_view get_default_encoding() {
    return m_default_enc_name;
  }

private:
  static std::string m_default_enc_name{"UTF8"};
  static pqxx::internal::encoding_group m_default_enc_group{UTF8};
};
```
Alternatively, the "default encoding" could be a static property of `connection`, and `array` will query it.

**Comment by alexolog** [comment]
> (or maybe even for vector like containers)

C++20 ranges would be nice :)

**Comment by alexolog** [comment]
> libpqxx needs to be aware in various situations of _where the next character begins._ Without that, for example, it might stumble when it sees a byte that happens to be the same numeric value as an ASCII quote or backslash, but is actually just a byte inside a multi-byte character value. It's a painful problem with real security implications.

This cannot happen with UTF-8. I am not familiar with other multi-byte encodings.

That said, the problem we are trying to solve is array parsing without an active connection, when both the client and server encodings are known.

**Comment by jtv** [comment]
@fallenworld1 the problem with specialising `field::as()` is that it's not the only place where we use string conversion.  We'd probably have to do that for more functions.  But much worse, the trick won't work for streaming queries.

**Comment by jtv** [comment]
@alexolog two points that I want to get out of the way:
1. Server encoding is (thankfully) irrelevant here.  It's client encoding that matters.  (Unfortunately it can change on the fly, even though it rarely will.)
2. I'm not going to introduce a global or static variable for the default encoding.

Now, one thing we _could_ try doing, is make `result` aware of its encoding.   I see two advantages:
* can support `field::as()` and streaming queries more or less equally
* behaves sensibly when client encoding changes on the fly

That still leaves us with the problem of passing the encoding into the string conversions.  This is in a way the hard one: it affects the string conversion API, and therefore it may affect people who have written their own string conversions.

**Comment by jtv** [comment]
Phew.  I _finally_ got the documentation working again.  That's been a big de-motivating factor for the last three months.  @alexolog @fallenworld1 I'd like to focus on this issue next, barring any urgent problems elsewhere, since we seem to have a clear direction.

**Comment by jtv** [comment]
Again there were lots of things to distract me but I did discover that `pqxx::result` is _already_ aware of its encoding.

So I'm now thinking along the lines of @fallenworld1's idea.

_First step:_ Add a completely separate function for reading an SQL array field as a `pqxx::array<...>`.

This new function would have an entirely new name.  That means you can't use it in row-at-a-time conversions.  So yes, its utility would be limited.

_Second step:_ Start integrating the new function into the existing field conversions system, so you can use the regular `field::as()` template on array types.

_Third step:_ Make this work with streaming queries.

**Comment by jtv** [comment]
I'm trying the first step.

(At the _second_ step I run into the problem that I need a partial template specialisation for `pqxx::field::as()`.  Current C++ does not allow partial specialisations of template functions — only for classes and variables.  IIRC future C++ versions may fix this.)

**Comment by jtv** [comment]
@alexolog, @fallenworld1, @tt4g — I think #854 would take care of the first step.  Any thoughts?

**Comment by fallenworld1** [comment]
@jtv couple of thoughts on second step - you can hide your encoding type inside
```
struct ConnectionEncoding {};

array_paser(string_view data, const ConnectionEncoding *enc): encoding(std::bitcast<pqxx::internal::encoding_group>(enc))

// or something like this
class ConnectionEncoding 
{
private:
    ConnectionEncoding(pqxx::internal::encoding_group);

    friend fiel, array, array_parser;
    int val
};
```

**Comment by tt4g** [comment]
LGTM.

**Comment by jtv** [comment]
> @jtv couple of thoughts on second step - you can hide your encoding type inside
> 
> struct ConnectionEncoding {};
> 
> array_paser(string_view data, const ConnectionEncoding *enc): encoding(std::bitcast<pqxx::internal::encoding_group>(enc))

@fallenworld1  I think this is more or less what we've already discussed.  Be aware however that `pqxx::array_parser` is an awful API, and `pqxx::array` supersedes it.

**Comment by jtv** [comment]
> LGTM.

Thanks @tt4g!

**Comment by jtv** [comment]
@alexolog I suppose `field::as_sql_array()` actually solves this ticket!  Not perfectly, but we can expand on it gradually.  Mind if I close this one?

**Comment by jtv** [comment]
There's more work to be done, but not quite as urgent I suppose.

**Comment by alexolog** [comment]
> 1. Compiler support for _concepts,_ and therefore, C++20 as a minimum.  That means 8.0 at the earliest, but I'm working on that right now.

Not necessarily.  Concepts give you better error messages, but they are not required for correctness.
SFINAE and `static_assert` can be viable pre-C++20 alternatives.

**Comment by jtv** [comment]
> > 1. Compiler support for _concepts,_ and therefore, C++20 as a minimum.  That means 8.0 at the earliest, but I'm working on that right now.
> 
> Not necessarily.  Concepts give you better error messages, but they are not required for correctness.
> SFINAE and `static_assert` can be viable pre-C++20 alternatives.

I'm not just talking about what is required to get something that compiles.  It also has to be maintainable and fit in with my plans.
