### ISSUE TITLE
ERROR: Unsupported server version; 9.0 is the minimum.

### ISSUE THREAD

**Issue by yanli-china** [jtv/libpqxx#844]
Connect to Redshift, but error occurs..

**ERROR: Unsupported server version; 9.0 is the minimum.**

Then I checked the redshift version like this 
```
SELECT version();
```
it return 

```
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.66954
```

it is 8.02, does it means this package only support >=9.0 version ? Or previous code package release can support < 9.0 version. I use the master branch to test.

**Comment by tt4g** [comment]
Yes. libpqxx 7 requires PostgreSQL 9.

https://pqxx.org/libpqxx/faq/

> What PostgreSQL versions are supported?
> As a general rule, all currently supported major PostgreSQL releases. At this entry's time of writing, both front-end and back-end need to be version 9.3 or better.

**Comment by jtv** [comment]
So yes, if you want to work with an even older server version, you'll have to search back for an older version of libpqxx as well.

Obviously this is not the preferred route; best would generally be to upgrade.  This is the modern state of software, for better or for worse.

**Comment by yanli-china** [comment]
thank you for all guys reply. Really helpful, very appreciated.
