### ISSUE TITLE
Readthedocs /stable documentation page is empty.

### ISSUE THREAD

**Issue by 1Rogue** [jtv/libpqxx#845]
As seen here: https://libpqxx.readthedocs.io/stable/

Screenshot of that page: 
![image](https://github.com/jtv/libpqxx/assets/1635236/8504168c-fc89-40cd-89b1-13a45688e9b8)

Notably, all the indices are empty. I believe this is the primary path that google drops users searching documentation into, thus most libpqxx documentation searches lead to 404 pages.

**Comment by tt4g** [comment]
The Read The Docs build was broken once at the time of the release of version 7.9.0.
@jtv's efforts have resolved this issue (#802).
The documents will be viewable as they should be in the next version release.
Until then, please view the documentation for the latest commit: https://libpqxx.readthedocs.io/latest/

**Comment by jtv** [comment]
That's a good point.  I'll just release 7.9.1 so readthedocs will pick up the fixed documentation.  Also a good excuse for getting a bunch of other pending fixes out the door.

**Comment by jtv** [comment]
@1Rogue, @tt4g: I have just released 7.9.1.  I'm seeing [working documentation on ReadTheDocs](https://libpqxx.readthedocs.io/stable/).

This has been wearing me down for 3 months!

**Comment by alexolog** [comment]
Images are broken:

![image](https://github.com/jtv/libpqxx/assets/2112513/146b84a1-d57b-4abb-9a40-7e357b67aaf3)

**Comment by jtv** [comment]
@alexolog I think that _may_ be because... the documentation build is now disabled by default but I forgot to _enable_ it in the readthedocs build.

Trying a fix for that...

**Comment by jtv** [comment]
Nope, it's not even that.  For some reason we've got the "dot" files but not the "png" files.

**Comment by jtv** [comment]
Found it.  For some reason installing the graphviz _pip_ package did not install the `dot` binary into the path, but installing the graphviz _system_ package did.
