### ISSUE TITLE
CMakeDetermineCompileFeatures throwing errors

### ISSUE THREAD

**Issue by KillerDiek** [jtv/libpqxx#851]
Hello, obligatory very new to this and C++ programming in general. I'm trying to build the files using [the provided guide](https://github.com/jtv/libpqxx/blob/master/BUILDING-cmake.md) and whenever I try and run the build, no matter what I change, I get this information:
```
Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
The CXX compiler identification is MSVC 19.40.33811.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
CMake Error at cmake/config.cmake:14 (include):
  include could not find requested file:

    CMakeDetermineCompileFeatures
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)


Found PostgreSQL: C:/Program Files/PostgreSQL/16/lib/libpq.lib (found version "16.3")
Looking for poll
Looking for poll - not found
CMake Error at cmake/config.cmake:42 (cmake_determine_compile_features):
  Unknown CMake command "cmake_determine_compile_features".
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)


Configuring incomplete, errors occurred!
```
I'm very lost on what to do and I've been at this for several hours now so I'm throwing in the towel and asking here. Any help is much appreciated.

**Comment by jtv** [comment]
Is it possible that you need a different CMake version?

**Comment by tt4g** [comment]
It seems that `CMakeDetermineCompileFeatures` has been renamed to `CMakeDetermineCompilerSupport` and `cmake_determine_compile_features` to `cmake_determine_compiler_support` in CMake version 3.30 (not released yet): https://gitlab.kitware.com/cmake/cmake/-/commit/588371d2d5fdda0340b29058147f49e40723ba71
If you are using version 3.30.0-rc3, that is probably the cause.

https://github.com/jtv/libpqxx/blob/5031f5b46f2e6eb6eb80b1fda7a88acabec531a0/cmake/config.cmake#L14
https://github.com/jtv/libpqxx/blob/5031f5b46f2e6eb6eb80b1fda7a88acabec531a0/cmake/config.cmake#L42

This problem should be avoided by making the following changes to `cmake/config.cmake`:

```diff
+if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.30.0)
+    include(CMakeDetermineCompilerSupport)
+    cmake_determine_compiler_support(CXX)
+else()
+    include(CMakeDetermineCompileFeatures)
+    cmake_determine_compile_features(CXX)
+endif()
 
 include(CheckIncludeFileCXX)
 include(CheckFunctionExists)
 include(CheckSymbolExists)
-include(CMakeDetermineCompileFeatures)
 include(CheckCXXSourceCompiles)
 include(CMakeFindDependencyMacro)

(skip...)

 
-cmake_determine_compile_features(CXX)
 cmake_policy(SET CMP0057 NEW)
```

**Comment by KillerDiek** [comment]
That solved it, thank you for your help and patience, I truly appreciate it!

**Comment by jtv** [comment]
Reopening this.  It's not enough to have a solution that users can find for themselves.  It should work out of the box, so I'll integrate the fix.

Thanks again @tt4g!

**Comment by killerbot242** [comment]
I spotted this problem yesterday, and asked around on the cmake support/forum.

The solution implemented here, will indeed solve the problem. But it seems by design this snippet is bad and should not be used.

The answer I got from Craig Scott: 
That file is an internal implementation detail of CMake. It is not part of CMake’s public API, projects and developers should not be trying to use it directly. It can (and apparently now has in the 3.30 release) change without notice.


See here : https://discourse.cmake.org/t/cmakedeterminecompilerfeatures-cmake-is-no-more-in-3-30-bug-or-not/11176


kind regards,
Lieven

**Comment by jtv** [comment]
No word on what we should do instead?  Because we probably need to do _something._

**Comment by jtv** [comment]
(Mentioning @killerbot242 because Github may not notify you on a closed ticket.  In fact I'd be in favour of opening a new one.)

**Comment by killerbot242** [comment]
Hi Jeroen, could you answer what you try to accomplish on the cmake discourse link above. I asked for the apis to use, but Craig  turned the question around, and would like to know what you are trying to do.

**Comment by killerbot242** [comment]
I have the impression, you are doing this in order to get the value of "CMAKE_CXX_COMPILE_FEATURES" ?

but one can just do this, no include of something needed it seems ???

cmake_minimum_required(VERSION 3.30)
project(CompileFeatures)
message("CMAKE_CXX_COMPILE_FEATURES : ${CMAKE_CXX_COMPILE_FEATURES}")

**Comment by tt4g** [comment]
I found `include(CMakeDetermineCompileFeatures)` added in fc2a530f55a8d2f62a49f4273e1c275bc2d2fa1a.

As @killerbot242 pointed out, it looks like it was added for the following code that references `CMAKE_CXX_COMPILE_FEATURES `.

https://github.com/jtv/libpqxx/commit/fc2a530f55a8d2f62a49f4273e1c275bc2d2fa1a#diff-7520a891ea97b695753e3db2aaf7b2e26a6ab475ff0d62e4071355f74a06304dR43-R47

```cmake
cmake_determine_compile_features(CXX)
cmake_policy(SET CMP0057 NEW)
if (cxx_attribute_deprecated IN_LIST CMAKE_CXX_COMPILE_FEATURES)
  set(PQXX_HAVE_DEPRECATED)
endif ()
```

Since this code has already been removed, `include(CMakeDetermineCompileFeatures)` may not be necessary.

**Comment by killerbot242** [comment]
with respect to keeping the config.cmake clean, I think the following are also no longer needed:

CheckIncludeFileCXX  --> there are no more checks for certain include files (at least not here)
CheckSymbolExists  --> it is still using check_function_exists for "poll" --> CheckFunctionExists.

I have not checked the purpose of CMakeFindDependencyMacro, by its name it sounds like another internal api not to be used ??

**Comment by killerbot242** [comment]
by the way, modern cmake discourages GLOB, and advices to explicitly enumerate the source files

**Comment by tt4g** [comment]
@killerbot242 Can you send a PR?

**Comment by killerbot242** [comment]
what do you think of the idea, to include stuff only where needed ? 

# Incorporate feature checks based on C++ feature test mac
include(pqxx_cxx_feature_checks)


==> so only in there, we actually need :
* include(CheckCXXSourceCompiles)
* CMAKE_REQUIRED_DEFINITIONS backup before compile checks
* CMAKE_REQUIRED_DEFINITIONS restore after compile checks
* CMAKE_REQUIRED_QUIET ON/OFF

**Comment by killerbot242** [comment]
**detect_code_compiled** also seems no longer used  and can be removed ?

**Comment by tt4g** [comment]
Obviously unused CMake functions, and `include()` of modules that do not exist in the official CMake documentation can be removed.
Other than that, there is no need to change them right now, as they may cause unexpected side effects.

**Comment by killerbot242** [comment]
I can create PRs , most probably per subtopic, but I can not make branches in here in github, and I am not familiar with the process on github, and this specific repo ?
And quick pointers on your preferred procedure ?

**Comment by tt4g** [comment]
1. You can press the fork button on GitHub to create a copy of this repository in your account
2. Create a branch in the forked repository and work on it
3. When you are done working on the branch, push it to the forked repository
4. Then, visit this repository and you will see a button to create a Pull Request

You can find many explanations of this procedure by searching for "GitHub Fork Pull Request".

See also GitHub Document:

- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by jtv** [comment]
Thanks @killerbot242,  some PRs would be most appreciated!  I'm in a place with 74% packet loss, high temperatures, and incredible noise — and CMake is a topic for which I rely mostly on contributors.

(Also I like to see contributors credited in the git logs.  I used to spell this out in change logs, but it's easy to get wrong and mixing it in with the technical details tends to become messy.  Better if git just tells people that you contributed something.)

**Comment by killerbot242** [comment]
I tried to  create my first commit/push to the fork, and it fails :-( during the push.

git push
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/killerbot242/libpqxx.git/'


Any suggestions ?

**Comment by killerbot242** [comment]
I was able to create a token, and with that I could push.

**Comment by tt4g** [comment]
Can you create a pull request to merge pushed code into this repository?

**Comment by killerbot242** [comment]
first PR is created, once this one is processed I will move on to the next one. I would like to bring them in little chunks, each focusing at one topic.

**Comment by jtv** [comment]
That you for that by the way @killerbot242 - I find it's much better to get through these things in small chunks.
