### ISSUE TITLE
std::ranges undefined?

### ISSUE THREAD

**Issue by abrownsword** [jtv/libpqxx#858]
I'm having an issue compiling on an Ubuntu 20.04 aarch64 host using Clang 18.1.7 where it has decided that concepts are available, but `std::ranges` is undefined.  I've commented out the cmake check for concepts, and now it seems to be building, but I was wondering if anyone has seen this before and if there is a better solution?

**Comment by jtv** [comment]
What C++ version did you use?

**Comment by abrownsword** [comment]
Setting to 20 via cmake.

**Comment by tt4g** [comment]
Does the CMake output include a message that clang is used?
The compiler used by CMake may have to change variables.
See: https://stackoverflow.com/questions/7031126/switching-between-gcc-and-clang-llvm-using-cmake

And it is the compiler's responsibility to provide the STL header, so if it does not work, that should be the compiler's problem.

**Comment by abrownsword** [comment]
I've been using this set of cmake scripts for years, updating the clang compiler on the system periodically.  This latest update (from 14.0.4 to 18.1.7) is the first time I've seen this happen.  Turning on the -v option seems to show that the llvm libc++ include paths aren't being set properly.  I was hoping somebody else had seen this, but if not it must be something strange I'm doing locally and I'll figure it out.  Thanks.

**Comment by abrownsword** [comment]
I think I've figured it out.  I'm using the prebuilt LLVM images from github, but I'm not installing them per se.  The --stdlib option presumes that the library you choose is installed, and it has been working for me for years because the ubuntu distro happens to have a reasonably recent libc++ installed.  With v18, however, there are some files added, so for the first time I have run into this mismatch.  I need to use command line options that entirely disable the installed libc++, and then provide the paths to the one in the package.

**Comment by tt4g** [comment]
The compiler and tools assume that the relevant resources are installed.
However, if the compiler is not provided by the system, it would be dangerous to replace it with an installed compiler and related resources.
It is probably best to set up your `CMakeLists.txt` to use the Github-built LLVM instead of the system compiler.

**Comment by abrownsword** [comment]
Yeah, that's what I've done, and I got a working build out of it.
