### ISSUE TITLE
Linker error LNK2019 due to check_library_version (msvc vs2017)

### ISSUE THREAD

**Issue by edwinvp** [jtv/libpqxx#86]
Disclaimer: the following may only apply to the Windows build (using VS2017).

When linking an application that actually uses the pqxx library, I receive the following linker error: LNK2019. The linker cannot find symbol: `check_library_version<6,2>(void)`.
I understand this is a clever way to verify the correct combination of actual library version and expected library version from the application.

The definition of `check_library_version` can be found here:

File: version.hxx:
`template<int, int> PQXX_LIBEXPORT int check_library_version() noexcept;`

And the template instantiation that cannot be resolved at link time can be found here:

File: connection_base.hxx:
`static const auto version_ok =
 internal::check_library_version<PQXX_VERSION_MAJOR, PQXX_VERSION_MINOR>();`

I suspect somewhere inside the sources of the library, that `check_library_version<6,2>(void)` must also be both (explicitly) implemented and (DLL) exported (PQXX_LIBEXPORT)...

Temporary workaround:

Simply disabled the whole check for now. To get our app linking again I replaced that last line with:
`static const auto version_ok = true;`

**Comment by jtv** [comment]
The `PQXX_LIBEXPORT` dance is a little complicated.  When _building the library,_ it means: "if `PQXX_SHARED` is set, export this symbol from the library."  When _building a client against the library,_ it means: "if `PQXX_SHARED` is set, import this symbol from the library."  I wouldn't bet against that dance going wrong somewhere in this instance, but I'm just not seeing it.  It's all in the details of the "compiler-internal.hxx" and "compiler-public.hxx" headers.

One obvious way in which it could go wrong is if `PQXX_SHARED` did not get set.  But then I would expect to see _every_ libpqxx symbol in your code fail to link.

**Comment by edwinvp** [comment]
Thanks for your quick reply! That is indeed a very obvious way in which it could go wrong. But I know the basic steps of that dance! ;-)

Your expectation about seeing _every_ symbol fail makes a lot of sense. Still `check_library_version` is the **only** symbol the linker complains about.

Found that adding `PQXX_LIBEXPORT` to the following line - unlike my previous workaround - preserves the intended functionality and still make it compile and link:

In file `version.cxx`, add `PQXX_LIBEXPORT` to the implementation of `check_library_version`:

```template<> PQXX_LIBEXPORT 
int check_library_version<PQXX_VERSION_MAJOR, PQXX_VERSION_MINOR>() noexcept
```

**Comment by edwinvp** [comment]
As for the string-conversion template: quickly glanced over the files. Looks like most (if not all) of the templates there are fully defined within the header file. 

This means the compiler can already generate code based on this header file alone (similar to what happens with `std::vector<T>` etc.). Does not need to look for a compiled version of the code inside the DLL/LIB anymore.

The check library function was split into two, so it needs the library (since there is no code/implementation in the header). If we were to store everything in the header file it would also work but then we would have defeat the compatibility check :-)
