### ISSUE TITLE
Cross compile of the pqxx in c++ for arm7

### ISSUE THREAD

**Issue by fuadsmed** [jtv/libpqxx#865]
I want to use the library libpqxx in my plc next project, and i used the toolchain of the plc next and after i followed the instructions how to build my library:

$env:ARP_TOOLCHAIN_ROOT = "C:/SDKs/AXCF2152/2024.0"

cd C:\Libraries\libpqxx\build_arm cmake -DCMAKE_TOOLCHAIN_FILE=C:/SDKs/AXCF2152/2024.0/toolchain.cmake -DCMAKE_INSTALL_PREFIX=C:/Libraries/libpqxx_arm -DPostgreSQL_INCLUDE_DIR="C:/Program Files/PostgreSQL/16/include" -DPostgreSQL_LIBRARY="C:/Program Files/PostgreSQL/16/lib/libpq.lib" ..

cmake --build . --config Release

After the last command i got this at the end:

libpqxx-7.9.a(connection.obj) : error LNK2019: unresolved external symbol __imp_ioctlsocket referenced in function "pub lic: void __cdecl pqxx::connection::set_blocking(bool)& " (?set_blocking@connection@pqxx@@QEGAAX_N@Z) [C:\Libraries\lib pqxx\build_arm\test\runner.vcxproj] libpqxx-7.9.a(connection.obj) : error LNK2019: unresolved external symbol __imp_WSAGetLastError referenced in function "public: void __cdecl pqxx::connection::set_blocking(bool)& " (?set_blocking@connection@pqxx@@QEGAAX_N@Z) [C:\Libraries \libpqxx\build_arm\test\runner.vcxproj] libpqxx-7.9.a(wait.obj) : error LNK2001: unresolved external symbol __imp_WSAGetLastError [C:\Libraries\libpqxx\build_a rm\test\runner.vcxproj] libpqxx-7.9.a(wait.obj) : error LNK2019: unresolved external symbol __imp_WSAPoll referenced in function "void __cdecl pqxx::internal::wait_fd(int,bool,bool,unsigned int,unsigned int)" (?wait_fd@internal@pqxx@@YAXH_N0II@Z) [C:\Libraries\l ibpqxx\build_arm\test\runner.vcxproj] C:\Libraries\libpqxx\build_arm\test\Release\runner. : fatal error LNK1120: 3 unresolved externals [C:\Libraries\libpqxx \build_arm\test\runner.vcxproj]

i tried to change the CMakeLists and everything, but nothing happened.

i tried the instructions so i can include the library into my plc next project, because i cant build my project without the proper library.

**Comment by jtv** [comment]
The errors make it look as if this is a build for a Windows ARM system.  Is that correct?  For some reason the Windows networking library does not seem to be present.

I don't know too much about this kind of situation, but a few things may be worth checking:  Perhaps one or more of the Windows socket libraries is actually for a different architecture.  Could be a subtle architecture difference, such as between different ARM versions.  Or one of those system library files is missing or truncated.  And of course it's important that the the libraries in the build are either all debug builds, or all release builds.  Mixing those binaries won't work.

**Comment by jtv** [comment]
Oh @fuadsmed another thing to make really sure of: make sure you're not just using your cross-compiler, but also that you're using the cross-compiler's _linker._
