### ISSUE TITLE
Build error when using path that has spaces (win32)

### ISSUE THREAD

**Issue by edwinvp** [jtv/libpqxx#87]
This might be more of a docs / makefile improvement rather than an actual bug, but here goes:

The Windows build instructions (`win32/INSTALL.TXT`) suggests pointing the `PGSQLSRC` variable to the PostGreSQL installation directory. It is the easiest way to obtain libpq.dll etc. etc. I fully agree!

However, the problem with this is that (by default) the postgres installation path includes a space character (e.g. `C:\Program Files\PostGreSQL`).

The library seems to build fine but copying over the `libpq.dll` file and friends will fail.

It also seems difficult to me to be able to build both the 32- and 64-bits version on the same development machine, since you probably can't have both server versions installed at any time.

My workaround is to install both PostGreSQL programs back to back, so that I can capture (copy) the entire program files folder of each to a more permanent and build friendly location. 

So after some install/uninstall fun for instance I will have
`C:\pq\x86\PostgreSQL\10` (the 32-bits edition)
and
`C:\pq\x64\PostgreSQL\10` (the 64-bits edition)

Next, the `common` file needs to be adjusted so it automatically selects the right directory.
It means pointing PGSQLSRC at one of both directories depending on the target architecture.
This would be something like this:

```# declarations for use on Intel x86 systems
!IF "$(CPU)" == "i386"
PGSQLSRC="C:\pq\x86\PostgreSQL\10"
!ENDIF

# declarations for use on AMD64 systems
!IF "$(CPU)" == "AMD64"
PGSQLSRC="C:\pq\x64\PostgreSQL\10"
!ENDIF
```

Since `CPU` is normally undefined, you will also need something like this:

```# -------------------------------------------------------------------------
# Get CPU Type - exit if CPU environment variable is not defined
# -------------------------------------------------------------------------

# Win95 does not define PROCESSOR_ARCHITECTURE - default to i386

!IF "$(PROCESSOR_ARCHITECTURE)" == ""
CPU=i386
PROCESSOR_ARCHITECTURE=x86
!endif

!IF !DEFINED(CPU) || "$(CPU)" == ""
CPU = $(PROCESSOR_ARCHITECTURE)
!ENDIF # CPU

# if PROCESSOR_ARCHITECTURE was x86 or X86 change CPU to i386

!IF ( "$(CPU)" == "X86" ) || ( "$(CPU)" == "x86" )
CPU = i386
!ENDIF # CPU == X86

!IF "$(CPU)" != "i386"
!IF "$(CPU)" != "IA64"
!IF "$(CPU)" != "AMD64"
!ERROR  Must specify CPU environment variable ( CPU=i386, CPU=IA64, CPU=AMD64)
!ENDIF
!ENDIF
!ENDIF
```
@

**Comment by jtv** [comment]
It's not clear to me what I could do about this...  There's a whole bunch of problems to be solved, on a platform I don't normally build on.  It may be worth seeing what install options PostgreSQL offers on Windows — because all you really need is the libpq library and headers, not the server per se.

It would be great to have the spaces-in-paths problem resolved, but we used to have quoted names all over the place and that wasn't right either.  I seem to remember that the quotes got copied into the filenames.

I'd be really happy if you could help with any of these issues, but you'll have to treat me a bit like a child in this matter.  :-)

**Comment by edwinvp** [comment]
Neither to me (yet?). I'm not comfortable with all these different build systems in general.

The problem now seems to have something to do with the nmake's `copy` command.

I read it always expects two quoted arguments (no matter whether we are passing long files names - potentially having space character(s) - or not).

Now it is being asked to do something like this `copy "C:\Program Files\PostGreSQL\bin\""filename.a" "filename.b"` . So the copy thinks it got 3 arguments instead of the expected 2 and bombs out.

**Comment by jtv** [comment]
Yeah, I think that was why I was asked to remove some of the quoting to begin with.  :-(

I'm beginning to wonder if we could solve this by replacing more of the shell commands in the Windows Makefiles with Python scripts...

**Comment by jtv** [comment]
I've updated the documentation for CMake, but I'm hindered by a lack of experience with CMake.  I'll close this issue, on the assumption that the CMake build gets the problem out of the way.
