### ISSUE TITLE
query() for prepared statements

### ISSUE THREAD

**Issue by jtv** [jtv/libpqxx#871]
This is a re-filing of an older ticket that got hijacked for a different problem: #644.

The original question from @maresc-g was:

《We're looking to upgrade our version of pqxx in our application so I just came across the release note of the 7.7.4 in which you ask for feedback on if we still use pqxx::result.
I'd like to use the feature to automatically convert types like with query() but we only use prepared queries so we call exec_prepared() which still returns a pqxx::result.
Is it planned to add this for prepared queries as well in future releases ?》

**Comment by jtv** [comment]
In PR #875 I bring this a step closer.

**Comment by jtv** [comment]
I'm redoing the "exec" functions, so that parameterised statements, regular statements, and prepared statements will look much more alike.  Next I want to refactor the `exec1()`, `exec_n()`, `prepared_exec1()`, etc. by moving the row-count checks out of those functions.  Instead, you'll make a separate function call to check that you're getting the number of rows you expect.

That will greatly reduce, in the end, the number of exec functions that I need to support.  As a part of the ongoing work I think I can implement `query()` for both prepared statements and parameterised statements, without too much trouble.  This work is happening in #875.

**Comment by alexolog** [comment]
That sounds like a big breaking change.  Not something people will be looking for.

**Comment by jtv** [comment]
The existing functions will stay around for a long time, **as always,** with a deprecation attribute so everybody gets warnings when they compile code that uses them, telling them what to use instead.  This is standard procedure.

**Comment by jtv** [comment]
Actually, this is resolved now.  You can now call `query()` and pass a `prepped` statement instead of an SQL string.
