### ISSUE TITLE
Link in navigation bar is wrong

### ISSUE THREAD

**Issue by Paebbels** [jtv/libpqxx#883]
The link in the navigation bar is wrong. it should point to [pqxx.org/libpqxx/](http://pqxx.org/libpqxx/).

```diff
- pqxx.org/pqxx/
+ pqxx.org/libpqxx/
```

**Comment by tt4g** [comment]
Perhaps it is about this link.

![navbar](https://github.com/user-attachments/assets/d09c4c6d-e8c6-46fe-ab6d-5a28a847501e)

**Comment by jtv** [comment]
Ahh, thanks @tt4g.  I was trying to find it on the site itself.

Fixed now @Paebbels.
