### ISSUE TITLE
Invalid error message in non blocking pqxx::connection constructor

### ISSUE THREAD

**Issue by vurdalaque** [jtv/libpqxx#894]
I've encountered persistent error message 'connection pointer is NULL' when tried to use `pqxx::connection` in non blocking mode.
I believe it's in delegated contstructor `connection(connection::connect_mode, zview)`
```cpp
  if (status() == CONNECTION_BAD)
  {
    PQfinish(m_conn);
    m_conn = nullptr;
    throw pqxx::broken_connection{PQerrorMessage(m_conn)};
  }
```
First of all, `PQerrorMessage` called on `nullptr` handle, and moreover has no meaning, since according to documentation all error strings will be freed after `PQfinish`. Possible solution is to get error message before `PQfinish`, copy it and after throw with `pqxx::broken_connection`. 
```cpp
    const std::string message{ PQerrorMessage(m_conn) };
    PQfinish(m_conn);
    m_conn = nullptr;
    throw pqxx::broken_connection{message};
```

Sorry, if I messed with report design.

**Comment by jtv** [comment]
Ah yes, that looks like it's happening in the wrong order!  There's still a _different_ problem of course, but we'll need to read the error message to know what it is.

Have you tried making the change you suggested to your own copy of libpqxx, to find out what the error message is?

Meanwhile I can update the error-handling code on my end.

**Comment by jtv** [comment]
@vurdalaque I've merged the fix.  (Took a while — there were some complications.)  If you're building your own libpqxx, try using the latest master.
