### ISSUE TITLE
after i built this source code by cmake i cant include the headerfile correctly

### ISSUE THREAD

**Issue by LunaticLegacy** [jtv/libpqxx#896]
as the picture goes:
![image](https://github.com/user-attachments/assets/7aab99e7-1ff2-468e-bc30-f2687835d264)
_fig1. after cmake, the files in dir "include"_

![image](https://github.com/user-attachments/assets/a8a5396b-e653-4757-a72d-1edd2be4f2e0)
_fig.2 i dont want to explain what is it..._

idk what happened. i used command as fig.3:

![image](https://github.com/user-attachments/assets/41268801-f724-411e-ac70-0d52afcc9d67)
_fig.3 the command i've used in building_

(i'm a total greenhand in how to use cmake)

**Comment by LunaticLegacy** [comment]
wait, i understood. i can simply use that source code the author released without execute it with cmake...
i did 7 hrs and finally realized i'm suck haha

**Comment by jtv** [comment]
@LunaticLegacy what you'd normally do is `make install` to install both the headers and the library binaries in their default place on your system.

**Comment by LunaticLegacy** [comment]
> @LunaticLegacy what you'd normally do is `make install` to install both the headers and the library binaries in their default place on your system.

thx ;),  but i already solved it yesterday haha. and i finally know how to use cmake
