### ISSUE TITLE
here comes:

### ISSUE THREAD

**Issue by LunaticLegacy** [jtv/libpqxx#898]
Wait...

![image](https://github.com/user-attachments/assets/45015076-4033-49d5-9588-14e4691443b4)
Fig.1 | param "args" had been included but not expanded

![image](https://github.com/user-attachments/assets/9b13fc30-8982-477d-a3cc-ffa24158a6ef)
Fig.2 | not defined "text" "len" "text" "len"

![image](https://github.com/user-attachments/assets/27dc6021-a4ff-4dd7-b424-fb272954b58a)
Fig.3 | not defined "str"

idk why this happened, i had already made and built all the files related to the code. which libs or dlls should i link to this project?

**Comment by LunaticLegacy** [comment]
confirmed of these errors does not affects compling.

**Comment by jtv** [comment]
@LunaticLegacy I guess that's Chinese — of which I can only read one or two characters.  So I have no idea what the problem was.  Please use English!

**Comment by LunaticLegacy** [comment]
fine i will edit soon sorry ;)



---- Replied Message ----
| From | Jeroen ***@***.***> |
| Date | 10/12/2024 21:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [jtv/libpqxx] here comes: (Issue #898) |

@LunaticLegacy I guess that's Chinese — of which I can only read one or two characters. So I have no idea what the problem was. Please use English!

**Comment by LunaticLegacy** [comment]
> @LunaticLegacy I guess that's Chinese — of which I can only read one or two characters. So I have no idea what the problem was. Please use English!

Here is the exact errors my Visual Studio shows. _(I confirmed these errors does not affect compling... So is it not worthy to fix?)_
E1919 - Parameter pack "Args" is already used but expanded.    (Line 1200, at conversions.hxx)
E1919 - Parameter pack "Args" is already used but expanded.    (Line 1200, at conversions.hxx)
E0020 - Identifier "text" is undefined.  (Line 44, at zview.hxx)
E0020 - Identifier "len" is undefined.  (Line 44, at zview.hxx)
E0020 - Identifier "text" is undefined.  (Line 50, at zview.hxx)
E0020 - Identifier "len" is undefined.  (Line 50, at zview.hxx)
E0020 - Identifier "str" is undefined.  (Line 78, at zview.hxx)

**Comment by jtv** [comment]
Ahhh, that's a known long-standing bug in the IDE (I think it was a plugin but I'm not sure about the details).  If you search through the bug reports you'll find other people who had the same problem.

So it's not really something I can fix.  It's just the IDE (not the compiler!) that gives off a mistaken warning.

**Comment by jtv** [comment]
Actually I'm not entirely sure now...  I would recommend doing a Google search for these messages.  The messages do not make sense to me.
