### ISSUE TITLE
Problem with linking using clang++ in Visual Studio Code mac m1

### ISSUE THREAD

**Issue by Kakoluki** [jtv/libpqxx#904]
Hi, I've trying to connect to a PostgreSQL database but when I try to build appears the following problem. The other C++ files compiles just fine, so i wonder if this is something related to the libpqxx connector. 

I'm using a mac m1, hence the arm64 architecture. 

Starting build...
/usr/bin/clang++ -std=gnu++14 -fcolor-diagnostics -fansi-escape-codes -g /Users/kakolu/VStudio/Database/post.cpp -std=gnu++2b -o /Users/kakolu/VStudio/Database/post -std=c++17 -stdlib=libc++
Undefined symbols for architecture arm64:
  "pqxx::connection::read_copy_line()", referenced from:
      pqxx::internal::gate::connection_stream_from::read_copy_line() in post-9c840b.o
  "pqxx::connection::init(char const*)", referenced from:
      pqxx::connection::connection(char const*) in post-9c840b.o
  "pqxx::connection::close()", referenced from:
      pqxx::connection::~connection() in post-9c840b.o
  "pqxx::usage_error::usage_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      int pqxx::transaction_base::query_value<int>(pqxx::zview) in post-9c840b.o
      pqxx::internal::result_iteration<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int>::result_iteration(pqxx::result const&) in post-9c840b.o
      pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::stream_query(pqxx::transaction_base&, std::__1::basic_string_view<char, std::__1::char_traits<char>>) in post-9c840b.o
      pqxx::row::check_size(int) const in post-9c840b.o
  "pqxx::argument_error::argument_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      pqxx::internal::(anonymous namespace)::throw_for_encoding_error(char const*, char const*, unsigned long, unsigned long) in post-9c840b.o
  "pqxx::internal_error::internal_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      unsigned long (*pqxx::internal::get_s_char_finder<(char)9, (char)92>(pqxx::internal::encoding_group))(std::__1::basic_string_view<char, std::__1::char_traits<char>>, unsigned long) in post-9c840b.o
  "pqxx::conversion_error::conversion_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::to_string<unsigned long>(unsigned long const&) in post-9c840b.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::to_string<int>(int const&) in post-9c840b.o
  "pqxx::transaction_base::exec(std::__1::basic_string_view<char, std::__1::char_traits<char>>, std::__1::basic_string_view<char, std::__1::char_traits<char>>)", referenced from:
      pqxx::transaction_base::exec(std::__1::basic_string_view<char, std::__1::char_traits<char>>) in post-9c840b.o
  "pqxx::transaction_base::close()", referenced from:
      pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)1>::~transaction() in post-9c840b.o
  "pqxx::transaction_base::commit()", referenced from:
      _main in post-9c840b.o
  "pqxx::transaction_base::exec_n(int, pqxx::zview, std::__1::basic_string_view<char, std::__1::char_traits<char>>)", referenced from:
      pqxx::transaction_base::exec_n(int, pqxx::zview) in post-9c840b.o
  "pqxx::transaction_base::do_abort()", referenced from:
      vtable for pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)1> in post-9c840b.o
  "pqxx::transaction_focus::register_me()", referenced from:
      pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::stream_query(pqxx::transaction_base&, std::__1::basic_string_view<char, std::__1::char_traits<char>>) in post-9c840b.o
  "pqxx::transaction_focus::unregister_me()", referenced from:
      pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::close() in post-9c840b.o
  "pqxx::conversion_overrun::conversion_overrun(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      pqxx::string_traits<char const*>::into_buf(char*, char*, char const* const&) in post-9c840b.o
      pqxx::string_traits<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::into_buf(char*, char*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in post-9c840b.o
      pqxx::string_traits<std::__1::basic_string_view<char, std::__1::char_traits<char>>>::into_buf(char*, char*, std::__1::basic_string_view<char, std::__1::char_traits<char>> const&) in post-9c840b.o
  "pqxx::internal::integral_traits<int>::from_string(std::__1::basic_string_view<char, std::__1::char_traits<char>>)", referenced from:
      int pqxx::from_string<int>(std::__1::basic_string_view<char, std::__1::char_traits<char>>) in post-9c840b.o
  "pqxx::internal::integral_traits<int>::into_buf(char*, char*, int const&)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::to_string<int>(int const&) in post-9c840b.o
      pqxx::internal::enum_traits<pqxx::internal::encoding_group>::into_buf(char*, char*, pqxx::internal::encoding_group const&) in post-9c840b.o
      void pqxx::internal::render_item<int>(int const&, char*&, char*) in post-9c840b.o
  "pqxx::internal::integral_traits<unsigned long>::into_buf(char*, char*, unsigned long const&)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::to_string<unsigned long>(unsigned long const&) in post-9c840b.o
      void pqxx::internal::render_item<unsigned long>(unsigned long const&, char*&, char*) in post-9c840b.o
  "pqxx::internal::basic_transaction::do_commit()", referenced from:
      vtable for pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)1> in post-9c840b.o
  "pqxx::internal::basic_transaction::basic_transaction(pqxx::connection&, pqxx::zview)", referenced from:
      pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)1>::transaction(pqxx::connection&) in post-9c840b.o
  "pqxx::internal::basic_transaction::~basic_transaction()", referenced from:
      pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)1>::~transaction() in post-9c840b.o
  "pqxx::internal::demangle_type_name(char const*)", referenced from:
      ___cxx_global_var_init in post-9c840b.o
      ___cxx_global_var_init.17 in post-9c840b.o
      ___cxx_global_var_init.18 in post-9c840b.o
      ___cxx_global_var_init.19 in post-9c840b.o
      ___cxx_global_var_init.20 in post-9c840b.o
      ___cxx_global_var_init.21 in post-9c840b.o
  "pqxx::internal::state_buffer_overrun(int, int)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::internal::state_buffer_overrun<long, unsigned long>(long, unsigned long) in post-9c840b.o
  "pqxx::internal::throw_null_conversion(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::from_string<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(pqxx::field const&) in post-9c840b.o
      int pqxx::from_string<int>(pqxx::field const&) in post-9c840b.o
      std::__1::basic_string_view<char, std::__1::char_traits<char>> pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::parse_field<std::__1::basic_string_view<char, std::__1::char_traits<char>>>(pqxx::zview, unsigned long&, char*&) in post-9c840b.o
      int pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::parse_field<int>(pqxx::zview, unsigned long&, char*&) in post-9c840b.o
      int pqxx::field::as<int>() const in post-9c840b.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::field::as<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>() const in post-9c840b.o
  "pqxx::internal::check_pqxx_version_7_9()", referenced from:
      pqxx::check_version() in post-9c840b.o
  "pqxx::internal::pq::pqfreemem(void const*)", referenced from:
      pqxx::internal::stream_query_input_iterator<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::stream_query_input_iterator(pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>&) in post-9c840b.o
  "pqxx::internal::enc_group(int)", referenced from:
      pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::get_finder(pqxx::transaction_base const&) in post-9c840b.o
  "pqxx::connection::encoding_id() const", referenced from:
      pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::get_finder(pqxx::transaction_base const&) in post-9c840b.o
  "pqxx::connection::dbname() const", referenced from:
      _main in post-9c840b.o
  "pqxx::row::operator[](int) const", referenced from:
      int pqxx::transaction_base::query_value<int>(pqxx::zview) in post-9c840b.o
      auto pqxx::row::get_field<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int>, 0ul>() const in post-9c840b.o
      auto pqxx::row::get_field<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int>, 1ul>() const in post-9c840b.o
  "pqxx::field::size() const", referenced from:
      pqxx::field::view() const & in post-9c840b.o
  "pqxx::field::is_null() const", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::from_string<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>(pqxx::field const&) in post-9c840b.o
      int pqxx::from_string<int>(pqxx::field const&) in post-9c840b.o
      int pqxx::field::as<int>() const in post-9c840b.o
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> pqxx::field::as<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>() const in post-9c840b.o
  "pqxx::result::size() const", referenced from:
      decltype(fp.size()) std::__1::size[abi:ne180100]<pqxx::result>(pqxx::result const&) in post-9c840b.o
  "pqxx::result::empty() const", referenced from:
      decltype(fp.empty()) std::__1::empty[abi:ne180100]<pqxx::result>(pqxx::result const&) in post-9c840b.o
  "pqxx::result::front() const", referenced from:
      pqxx::transaction_base::exec1(pqxx::zview) in post-9c840b.o
  "pqxx::result::columns() const", referenced from:
      _main in post-9c840b.o
      pqxx::internal::result_iteration<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int>::result_iteration(pqxx::result const&) in post-9c840b.o
      pqxx::internal::result_iteration<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int>::result_iteration(pqxx::result const&) in post-9c840b.o
      pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::stream_query(pqxx::transaction_base&, std::__1::basic_string_view<char, std::__1::char_traits<char>>) in post-9c840b.o
      pqxx::internal::stream_query<std::__1::basic_string_view<char, std::__1::char_traits<char>>, int>::stream_query(pqxx::transaction_base&, std::__1::basic_string_view<char, std::__1::char_traits<char>>) in post-9c840b.o
  "pqxx::result::operator[](int) const", referenced from:
      pqxx::internal::result_iter<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, int>::read() in post-9c840b.o
  "pqxx::field::c_str() const &", referenced from:
      pqxx::field::view() const & in post-9c840b.o
  "pqxx::result::column_name(int) const &", referenced from:
      _main in post-9c840b.o
  "typeinfo for pqxx::internal::basic_transaction", referenced from:
      typeinfo for pqxx::transaction<(pqxx::isolation_level)0, (pqxx::write_policy)1> in post-9c840b.o
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by KayEss** [comment]
You don't say what build system you're using, but it looks like you're trying to build the executable through a single invocation of `clang` (which is fine), but there's no `-l` directive for linking libpqxx. Probably you need to add `-lpqxx` and possibly also `-lpq` -- this requires that they're both available somewhere clang can find them.

**Comment by Kakoluki** [comment]
Thank you for your fast reply. That error is from the terminal integrated in Visual Studio Code when I run the source file. Sorry if I should have specified that before. The source file have the #include <pqxx/pqxx>

Anyway, I used the following command: `clang++ -o source_code.cpp -lpqxx`

Which gave: 

Undefined symbols for architecture arm64:
  "_main", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by KayEss** [comment]
Presumably you're not building the file that contains `main` given that error, but I think this is not  a libpqxx problem, this is a "using Visual Studio Code" problem and we can't help you with that I'm afraid.

**Comment by tt4g** [comment]
> ld: library 'pq' not found

This is because libpq is not installed on your machine or `ld` is not able to find it.
Please install libpq.

**Comment by Kakoluki** [comment]
> Presumably you're not building the file that contains `main` given that error, but I think this is not a libpqxx problem, this is a "using Visual Studio Code" problem and we can't help you with that I'm afraid.

It has a `main` function. Also tried with CLion and CMake to the same result. But yeah, probably is something related with my configuration. 




> > ld: library 'pq' not found
> 
> This is because libpq is not installed on your machine or `ld` is not able to find it. Please install libpq.

Is installed with Homebrew, maybe is something with the location of the packages. I'm thinking the best is reinstall everything and start again. 

Thank you both for your help.

**Comment by Kakoluki** [comment]
When I add it, it says that the pq library wasn’t found. But libpq is installed with Homebrew.

El jue, 21 nov, 2024 a las 15:09, Jeroen Vermeulen ***@***.***(mailto:El jue, 21 nov, 2024 a las 15:09, Jeroen Vermeulen <<a href=)> ha escrito:

**Comment by Kakoluki** [comment]
When I add it, it says that the pq library wasn’t found. But libpq is installed with Homebrew. For example, with `clang++ -o source_code.cpp -lpqxx -lpq`, the output is ld: library 'pq' not found.

**Comment by jtv** [comment]
Then maybe libpq is not installed in a place where the compiler knows where to find it (which you can fix with the `-L` option, followed by the directory path); or maybe it's not of a right kind, e.g. if you're trying to link a Visual Studio library with a clang library.

**Comment by Kakoluki** [comment]
Also tried with the `-L` and `-I` options, but nothing, it keeps giving the same message with the Visual Studio debugger button:

ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1

With the ` clang++ -L /usr/local/include/pqxx/ main.cpp -o main` it gives a lot of errors like 

/usr/local/include/pqxx/types.hxx:78:22: error: no template named 'remove_cv_t' in namespace 'std'
   78 | using strip_t = std::remove_cv_t<std::remove_reference_t<TYPE>>;

There must be something wrong with my configuration, but I don't know what it is. Thanks you all for your help and time.

**Comment by KayEss** [comment]
> With the ` clang++ -L /usr/local/include/pqxx/ main.cpp -o main` it gives a lot of errors like

For `-L` you give the path to the library, not a path to the include files. Include file paths are `-I`. Also, for include files, you'll want to use the path to the `include` directory not the `pxxx` directory (as that part of the path is in the `#include` directive.

I think you need to find somewhere you can get some interactive beginners help, for example on [includecpp](https://www.includecpp.org/discord/)

**Comment by jtv** [comment]
Any luck @Kakoluki?

(Hard to type right now... cat on my elbow, French keyboard w US keymap)

**Comment by Kakoluki** [comment]
Sorry for the delay. Finally switched to a SQLite3 connector. I'm not sure why but it worked that way.  Probably I'll need PostgreSQL in the future so I'm not giving up, but for the moment I'm closing this issue.
