### ISSUE TITLE
How to actively(immediately) drop a connection?

### ISSUE THREAD

**Issue by leonleeann** [jtv/libpqxx#905]
I'm using libpqxx-6.4.5(that comes with Debian12 by defaults) to work with Postgresql-13 server, and my project needs my client app to disconnect actively, in order to let other clients can connect the server.

I used a pqxx::connection obj, and called the method `disconnect()` of it, furthermore, I have **destroied** this obj, after the query is done. But in the pgAdmin monitoring window, I still see the connection inited by this client app, and the other clients can **NOT** connect to the server, if all the available connections have been occupied.

If this client app exited, or was killed, the connection inited by it immediately disappeared from the monitoring window, so I guess that maybe there are some codes in libpqxx keeping a connection alive?

Now I can **NOT** upgrade the serve to PG14 that has `idle_session_timeout` option to drop idle connections from the server side, I can **NOT** upgrade immediately to libpqxx-7.x also.

Is there a way I can forcely drop a connection from client side?

Or I did not yet use libpqxx-6.4 in correct way?

**Comment by jtv** [comment]
That's very strange.  Destroying a connection should immediately disconnect it.

You're running a much older version of the code, when connections were actually more complicated things than they are today.  But even then I can't think of anything that would make this happen, unless you did something strange like doing a `fork()` with the connection open.

**Comment by leonleeann** [comment]
Since my producing codes are very complicated, I simply descript the starting steps of my clients here:

1. I do certainly did a `fork` in the parent process, but followed by a `execv`;
2. In the parent, I have called `pqxx::connection::disconnect()` and destroied it before every time I calling `fork()` and `execv()`;
3. In every children, I create a new pqxx::connection obj, with different `application_name=child**` args such as `application_name=child01`, `application_name=child02` and so on respectively for each child;
4. In child, I destroied the pqxx::connection obj after a query, and then begin to do other long time works;
5. The parent re-connects to the db after fork/execv, of course, with old args `application_name=master`.

But in the dashboard of the pgAdmin4, I still can see many connections with different `application_name`  such as "child01", "child02" and only one ''master".
After all the available connections of PG-server have been occupied, the subsequent children can NOT connect to the server.

**Comment by leonleeann** [comment]
If because of `fork/execv`, the connection args were carried into children as your suspecting, I think the `application_name` listed in pgAdmin would have same value as "master"? while entries name I saw are "child01", "child02" and so on...

In other words, I guess my connecting codes in children have taked effects, those connections are not carried from parent, but created by child own.

**Comment by KayEss** [comment]
Are you sure you're not going through an external connection pool? That would also explain the held open connection

**Comment by leonleeann** [comment]
After debugging again, we found this is because of an our own bug!
Sorry for wasting your time, gentlemen...
