### ISSUE TITLE
7.10.0 and min cmake version

### ISSUE THREAD

**Issue by devrimgunduz** [jtv/libpqxx#916]
Hi @jtv ,

I hope you are doing well.

I was reading https://github.com/jtv/libpqxx/releases/tag/7.10.0 and noticed that the minimum cmake version is now 3.28.

This eliminates RHEL 9 users , which is the majority of our user base.  RHEL 9 ships with cmake 3.26. We already lost RHEL 8 users in the recent versions because of GCC requirements, and losing RHEL 9 just won't help.

Any chance to review this decision?

Thanks!

Cheers, Devrim

**Comment by tt4g** [comment]
I believe that is a 3.12 typo.

https://github.com/jtv/libpqxx/blob/a409278c13c26e5f1728a5dc2b875ca62a098e95/CMakeLists.txt#L1

**Comment by jtv** [comment]
Hey @devrimgunduz!  Always good to hear from you.  Yes, as @tt4g says — seems to be a typo.  There was a lot of confusion over cmake changes back then but I don't know exactly how this happened.

I'm working up one of the silliest patch releases ever.  And I'll fix the release announcement.

**Comment by jtv** [comment]
And thanks once again @tt4g for your _incredibly_ fast and effective help.  :-)

**Comment by devrimgunduz** [comment]
Thanks a lot!
