### ISSUE TITLE
expirement/optional cause a bug when building using clang 6 

### ISSUE THREAD

**Issue by khairy-mohamed** [jtv/libpqxx#93]
build options 
`-I /usr/include/openssl -lssl -lcrypto -lpqxx -lpq -Wall -std=c++11`
**i got this error :** 
```
/usr/local/include/pqxx/internal/statement_parameters.hxx:213:13: error: no member named 'experimental' in namespace 'std'
        const std::experimental::optional<Arg> &arg)
              ~~~~~^
In file included from /home/khairy/Documents/Projects/backend/crow-demo/src/main.cpp:7:
In file included from /usr/local/include/pqxx/pqxx:12:
In file included from /usr/local/include/pqxx/cursor:12:
In file included from /usr/local/include/pqxx/cursor.hxx:23:
In file included from /usr/local/include/pqxx/transaction_base.hxx:32:
In file included from /usr/local/include/pqxx/row.hxx:20:
/usr/local/include/pqxx/field.hxx:170:29: error: no member named 'experimental' in namespace 'std'
  template<typename T> std::experimental::optional<T> get() const
                       ~~~~~^
/usr/local/include/pqxx/field.hxx:171:27: error: no member named 'experimental' in namespace 'std'
        { return get_opt<T, std::experimental::optional<T>>(); }
                            ~~~~~^
/usr/local/include/pqxx/field.hxx:171:50: error: 'T' does not refer to a value
        { return get_opt<T, std::experimental::optional<T>>(); }
                                                        ^
/usr/local/include/pqxx/field.hxx:170:21: note: declared here
  template<typename T> std::experimental::optional<T> get() const

```

**Comment by jtv** [comment]
As far as I can see, field.hxx includes the same header that the configure script also uses when checking whether `std::experimental::optional` is available.  So if this fails, the check in the configure script should also have failed, and so the library should not have tried to use `std::experimental::optional`.

Was libpqxx configured and built with that same compiler and those same language options?  Some differences should be OK, but some aren't.  For instance, maybe the library was built without the `-std=c++11`, or with a version of the compiler that defaults to a different version of the C++ standard?

**Comment by jtv** [comment]
Very similar problems pop up in #95 — different compiler!

**Comment by jtv** [comment]
I've just added a workaround for this problem.  Now, if you want to build your application against a C++ implementation which does _not_ have `std::experimental::optional`, but using a libpqxx which was built against an implementation which _does_ have it, define a new  macro `PQXX_HIDE_EXP_OPTIONAL` in your build.
