### ISSUE TITLE
./tools/splitconfig change in commit 1ef5738173746 breaks build in systems with no 'stdout' (as in Docker builds)

### ISSUE THREAD

**Issue by daniel347x** [jtv/libpqxx#94]
A link to the specific line that fails (line 174):

https://github.com/jtv/libpqxx/commit/1ef5738173746bbdd377b92588e1195410c535aa#diff-10d5641a3bbf714e822b353ecb61b999R174

... The error message (when I attempt to perform a './configure; make; make install;' from a Dockerfile):

> Traceback (most recent call last):
>   File "./tools/splitconfig", line 239, in <module>
>     main()
>   File "./tools/splitconfig", line 235, in main
>     directory, original_header, items_map, publication, factor)
>   File "./tools/splitconfig", line 174, in generate_config
>     unicode_path = config_file.encode(stdout.encoding, 'replace')
> TypeError: encode() argument 1 must be string, not None

The error is that the first argument to `config_file.encode` is not set (it is `None`).

Is there a way around this that doesn't break my build in a Docker system?

Thanks!

**Comment by jtv** [comment]
So `stdout` exists but `stdout.encoding` is None?

I suppose we could just go with ASCII in that case, on the principle that you should have an encoding set if you're using non-ASCII paths.

**Comment by daniel347x** [comment]
Thanks - I'll check this out over the next few days and let you know.

**Comment by daniel347x** [comment]
Just created pull request https://github.com/jtv/libpqxx/pull/96 - the function in the commit wasn't actually being called... :)

**Comment by daniel347x** [comment]
To confirm - this is indeed resolved (I just built the latest in the Docker container).

**Comment by jtv** [comment]
Thanks again!
